### ISSUE TITLE
Hue and hoobs 4.0 Lights and Scenes not showing up

### ISSUE THREAD

**Issue by cdaniels77** [ebaauw/homebridge-hue#1001]
#### Issue
Hue Lights and Scenes are not showing up in Hoobs 4.0 or Homekit

#### Log Messages
"platform":·"Hue",
"name":·"Hue",
"brightnessAdjustment":·100,
"heartrate":·5,
"lowBattery":·25,
"timeout":·1,
"waitTimePut":·50,
"waitTimePutGroup":·1000,
"waitTimeResend":·300,
"waitTimeUpdate":·20,
"users":·{
"001788FFFE24F66F":·"iaIFvggDeOen36Cq8Z1migw6LaL0
},
"groups":·true,
"group0":·true,
"lights":·true,
·"hueDimmerRepeat":·false,
"hueMotionTemperatureHistory":·false,
"linkButton":·true,
"stealth":·false,
"sensors":·false,
"schedules":·false,
"scenesAsSwitch":·false,
"scenes":·true,
"rules":·false,
"rooms":·true,
"resource":·true

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Configuration:
- You need to set `nativeHomeKitLights` to false if you want Homebridge Hue to expose lights already exposed by the Hue bridge;
- You need to use a decent HomeKit app to interact with scenes, or set `scenesAsSwitch` to see them in the Home app.

**Comment by cdaniels77** [comment]
Was able to get the lights working thank you. Still having issues with the senes showing up in the home app. It worked great with hoobs 3.3.5 no luck so far with hoobs 4.0.92.

**Comment by ebaauw** [comment]
Please attach the debug dump file, and capture and attach a debug log file, see FAQ.

**Comment by cdaniels77** [comment]
Attached is my debugging log, I hope i did this correctly 

[Debug.txt](https://github.com/ebaauw/homebridge-hue/files/6856384/Debug.txt)

**Comment by ebaauw** [comment]
Could you also please attach the dump file, `/var/lib/hoobs/huehoobsbridge/homebridge-hue.json.gz`?

**Comment by cdaniels77** [comment]
ok I think i have it now. good thing is im learning alot :)

[Debug second time.txt](https://github.com/ebaauw/homebridge-hue/files/6857472/Debug.second.time.txt)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6857475/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
You didn't set `scenes` in config.json.  Nor `groups`, nor `group0`, nor `rooms`.

**Comment by cdaniels77** [comment]
it finally worked. at one point i had them all turned on expect rooms this was the missing piece. thank you so much for your help
