### ISSUE TITLE
Unsupported accessories appear in HomeKit

### ISSUE THREAD

**Issue by Addy010** [ebaauw/homebridge-hue#1002]
#### Unsupported accessories appear in HomeKit

I have installed and linked the hue plugin through hoobs and attached it to HomeKit. Everything is working fine only there is a very large amount of accessories that show as unsupported in HomeKit. None of these seem to be actual accessories as they have all come up and are working fine but there are these other accessories. Does anybody have any idea how to delete them or even just hide them?
![IMG_3F1060573C75-1](https://user-images.githubusercontent.com/87718568/126369108-3f0104d5-c658-4a00-a75f-6897fa81b5ee.jpeg)

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Looks like CLIPGenericFlag sensors created for rules on the Hue bridge.  Use `excludeSensorTypes` to prevent Homebridge Hue from exposing them.

**Comment by Addy010** [comment]
> Looks like CLIPGenericFlag sensors created for rules on the Hue bridge. Use `excludeSensorTypes` to prevent Homebridge Hue from exposing them.

Can I ask how you do that?

**Comment by ebaauw** [comment]
Use the Homebridge UI or edit config.json.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by Addy010** [comment]
> Use the Homebridge UI or edit config.json. See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

Thank you so much, that's amazing I've been scratching my head over that for hours. all working now
