### ISSUE TITLE
Ability to configure transitionTime for Hue lights

### ISSUE THREAD

**Issue by akosut** [ebaauw/homebridge-hue#1003]
One of the frustrations I have with the built-in behavior of Hue bulbs is that the 500ms transition time for turning on or off can't be changed.  I know from looking at the Hue API that the transitiontime parameter to the HTTP API can be used to give a different fade time.  I've done this by hand with Python scripts, etc.

It would be great if the homebridge-hue plugin supported being able to add and configure the transitiontime parameter so I could expose HomeKit controls for my Hue bulbs with custom fade time.  In my case, for example, I prefer setting the transitiontime to 200ms ("2") when turning bulbs on, and 0ms ("0") when turning them off.

**Comment by ebaauw** [comment]
Homebridge Hue has already supported _TransitionTime_ for a long time.  It's under the bridge service; you need a decent HomeKit app to use it, as Apple's Home app doesn't support custom characteristics.  Best create a HomeKit scene including _Transition Time_ (in Eve) and recall that scene from Siri or Home.

Note that _Transition Time_ resets to the default 0.4s automatically, shortly after use.

**Comment by akosut** [comment]
I'll have to experiment with that, but I was hoping just for a setting I could set that would make it so that when I clicked the light in the Home app, it would turn on/off with no (or less) fade.
