### ISSUE TITLE
Nonsense device

### ISSUE THREAD

**Issue by mano87** [ebaauw/homebridge-hue#1004]
Good evening,

from our new kitchen I have now added the "Unterbauleuchten" in HomeKit. When adding it automatically added another device "Philips Hue". Why is this and can I turn this off if necessary?

![kitchen](https://user-images.githubusercontent.com/25568300/126880197-e2b67459-5e37-4f3a-852e-b13bea4a62e4.png)

```
{
    "name": "Hue",
    "anyOn": true,
    "effects": true,
    "hosts": [
        "192.168.1.52"
     @`],`
    "lights": true,
    "nativeHomeKitLights": true,
    "nativeHomeKitSensors": true,
    "resource": true,
    "platform": "Hue",
    "_bridge": {
        "username": "xxxxxxx",
        "port": 12345
    }
}
```

**Comment by ebaauw** [comment]
See FAQ

**Comment by mano87** [comment]
Which FAQ is meant here - I have not found the corresponding place. Please for more info

**Comment by ebaauw** [comment]
https://github.com/ebaauw/homebridge-hue/wiki/FAQ

**Comment by mano87** [comment]
@ebaauw 
Good I have found them. But here it is not mentioned that a device is added, which is called "Philips hue" and is not operable? What exactly is this supposed to be for?
