### ISSUE TITLE
TRADFRI Remote Control E1524 On/Off/Toggle-Switch not working

### ISSUE THREAD

**Issue by ghdbwise** [ebaauw/homebridge-hue#1005]
No reaction on pressing On/Off (Toggle Button on Trafri Remote Control

Using deconz:
Button 1 was created, but homekit shows no reaction
The other four buttons react as aspected.

Using zigbee2mqtt only four buttons are created (see: https://github.com/itavero/homebridge-z2m/issues/240)

#### Log Messages
No reaction an pressing toggle button
[25.7.2021, 20:41:21] [HUE Device] TRÅDFRI Fernbedienung Dim Up: homekit button single press
[25.7.2021, 20:41:22] [HUE Device] TRÅDFRI Fernbedienung Dim Down: homekit button single press
[25.7.2021, 20:41:23] [HUE Device] TRÅDFRI Fernbedienung Previous: homekit button single press
[25.7.2021, 20:41:23] [HUE Device] TRÅDFRI Fernbedienung Next: homekit button single press
```
```

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6874418/homebridge-hue.json.gz)
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/6874420/homebridge.log.gz)

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4900.  Should be fixed in deCONZ v2.12.1 and later.

**Comment by ghdbwise** [comment]
Thank you Erik for that fast response. In deCONZ:  2.12.03 / 12.7.2021 with Firmware: 26660700 using a ConBee II the error occourse.
I‘m not familiar now the version counter is used. 
Regards
Peter

**Comment by ebaauw** [comment]
Can you double-check, e.g. with `dc_eventlog` or in the deCONZ logging (I think with `--dbg-info=2` that deCONZ actually sends web socket notifications when you press the _On/Off_ button?

**Comment by ghdbwise** [comment]
Hi Eric,
i’m sorry, i cannot get the requested information.

i can’t get my raspberry to write a deconz logfile.

**Comment by ebaauw** [comment]
And _Help_ | _Debug View_ in the GUI?

Alternatively use `dc_eventlog` or capture and attach a debug log file (making sure Homebridge debug mode has been enabled).

**Comment by ghdbwise** [comment]
Hi Eric,

is this the information you are looking for?

{
    "22:45:20:439": {
        "e": "changed",
        "id": "58",
        "r": "sensors",
        "state": {
            "buttonevent": 1002,
            "lastupdated": "2021-07-27T20:45:20.521"
        },
        "t": "event",
        "uniqueid": "00:0b:57:ff:fe:31:45:e9-01-1000"
    },
    "22:45:24:361": {
        "e": "changed",
        "id": "58",
        "r": "sensors",
        "state": {
            "buttonevent": 2002,
            "lastupdated": "2021-07-27T20:45:24.440"
        },
        "t": "event",
        "uniqueid": "00:0b:57:ff:fe:31:45:e9-01-1000"
    },
    "22:45:26:119": {
        "e": "changed",
        "id": "58",
        "r": "sensors",
        "state": {
            "buttonevent": 3002,
            "lastupdated": "2021-07-27T20:45:26.202"
        },
        "t": "event",
        "uniqueid": "00:0b:57:ff:fe:31:45:e9-01-1000"
    },
    "22:45:28:31": {
        "e": "changed",
        "id": "58",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-07-27T20:45:28.113"
        },
        "t": "event",
        "uniqueid": "00:0b:57:ff:fe:31:45:e9-01-1000"
    },
    "22:45:29:275": {
        "e": "changed",
        "id": "58",
        "r": "sensors",
        "state": {
            "buttonevent": 4002,
            "lastupdated": "2021-07-27T20:45:29.357"
        },
        "t": "event",
        "uniqueid": "00:0b:57:ff:fe:31:45:e9-01-1000"
    }
}

**Comment by ebaauw** [comment]
The first event is from the _On/Off_ button.  You should see a corresponding message in the Homebridge log.

**Comment by ghdbwise** [comment]
After upgrade deconz to v2.12.3 everything is fine again.

Thank you for your support.

Best regards from Germany
