### ISSUE TITLE
Ledvance GU10 „Not Supported“

### ISSUE THREAD

**Issue by Fastdesigner** [ebaauw/homebridge-hue#1009]
#### Issue

Ledvance GU10 Bulbs (non native Homekit) appear as not supported since last update. Other non native Bulbs work fine.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Please attach the debug dump file and a screenshot of Home showing the settings of the unsupported device.

**Comment by Fastdesigner** [comment]
![screen-home](https://user-images.githubusercontent.com/67697036/128130482-662b4e60-7f0b-46fe-99a0-46d68501b78a.jpg)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6928983/homebridge-hue.json.gz)
[screen-not-supported-details](https://user-images.githubusercontent.com/67697036/128130664-badd5f87-5949-4e5b-9b3f-8ca7afb2837a.jpg)

I´m sorry for leaving them out earlier. Had difficulties on the phone doing so. Here is the dump file and a screenshot of the Home-App schowing "Nicht unterstützt" = "not Supported"

**Comment by ebaauw** [comment]
Can you show the setting of one of those tiles?

**Comment by Fastdesigner** [comment]
You mean this? Already attached to my first reply: https://user-images.githubusercontent.com/67697036/128130664-badd5f87-5949-4e5b-9b3f-8ca7afb2837a.jpg

**Comment by ebaauw** [comment]
Yes, thanks.

**Comment by ebaauw** [comment]
Very odd.  Looking at the dump file the Hue bridge exposes the light correctly.  Is this the case for all four LEDVANCE spots, or just the two Büro spots?  What about the innr Büro bulb?  Did you recently rename them?  Maybe someone is unhappy about the umlaut?  I haven't seen this before, though.

Were there any errors in the Homebridge log?  Could you please capture and attach a debug dump, with the debug messages from when Homebridge Hue is starting up?  Do you know what version you upgraded from?

**Comment by Fastdesigner** [comment]
Thank you for your quick replies. Really appreciate it.

there should not be any innr bulb anymore. Yes this is also happening in the „Badezimmer“

i have updated from a version which has been 6 months old. I‘m sorry i don‘t have the old version number on hand.

i am on vacation until next tuesday and will deliver the logs then if that is okay with you.

**Comment by ebaauw** [comment]
> there should not be any innr bulb anymore.

The dump file (from early this morning) lists three innr RF 265 bulbs: "Schlafzimmer Bulb 2", "Büro Bulb 4", and "Schlafzimmer Bulb 1".  All three of them are reported reachable.

> Yes this is also happening in the „Badezimmer“

So not released to the umlaut in the name.

> i am on vacation until next tuesday and will deliver the logs then if that is okay with you.

Sure.

The "funny" part is that, by the looks of it, Homebridge Hue exposes the accessory for the spot alright, but not the _Lightbulb_ service, causing HomeKit to show an unsupported tile.  If I still understand my code, that would happen only if there's an error processing the resource, hence the request for the debug log file.  Could you remotely have a look what the spot looks like in Eve?  In particular, if it shows anything under _Names_ or _Type & Names_ in the accessory info screen (behind the little gear icon).  You might need to find the accessory under _Accessories_  in the _Settings_ window.

**Comment by Fastdesigner** [comment]
Ahh. Now i know which innr. Yes in the bedroom and these work fine.

here are screenshots from eve
![Uploading FF69D665-8639-48B9-8DB0-FD2ED515BE03.png…]()

**Comment by ebaauw** [comment]
That doesn't work; it's a link to this very page.

**Comment by Fastdesigner** [comment]
![58CCD299-4C96-42CF-8551-F897CA4CFE0C](https://user-images.githubusercontent.com/67697036/128228395-c602f19e-fc5e-44cc-9c2e-91cf90a0b148.png)
![FA8FC041-ACFD-419E-8FAC-04651AD8D480](https://user-images.githubusercontent.com/67697036/128228404-cecd29be-fd11-4e44-be3b-586099b41f64.png)

**Comment by Fastdesigner** [comment]
Worked now?

**Comment by ebaauw** [comment]
Indeed, no service here either.

**Comment by Fastdesigner** [comment]
Alright, I´m back. Attached you´ll find the syslog startup.

Sidenote: I deleted one of the four lights in Hue, restarted Homebridge to clear the light. Then i have added the light with a new name "Deckenlicht 1" and restarted homebridge again.

The result is the same as can be seen in the screenshot. I checked syslog and your plugin exposes this new light to homekit.

One thing i noticed is that the lights are the only ones in my home labeled as "Extended Color Light", whereas other "Dimmable Light" just work fine.

![screen-11-08-2021](https://user-images.githubusercontent.com/67697036/128993796-5b12dcab-86fa-469e-b85b-fa57bae22651.jpg)


[syslog.txt](https://github.com/ebaauw/homebridge-hue/files/6966794/syslog.txt)

**Comment by ebaauw** [comment]
You're running an older version of Homebridge (and HAP-NodeJS), which hasn't defined the characteristics used for Adaptive Lighting:
```
Aug 11 08:22:36 raspberrypi homebridge[328]: [8/11/2021, 08:22:36] [Hue] Initializing Hue platform...
Aug 11 08:22:36 raspberrypi homebridge[328]: [8/11/2021, 08:22:36] [Hue] homebridge-hue v0.13.19, node v12.2.0, homebridge v1.1.6
Aug 11 08:22:36 raspberrypi homebridge[328]: [8/11/2021, 08:22:36] [Hue] warning: recommended version: node v14.17.4 LTS
Aug 11 08:22:36 raspberrypi homebridge[328]: [8/11/2021, 08:22:36] [Hue] warning: recommended version: homebridge v1.3.4
Aug 11 08:22:36 raspberrypi homebridge[328]: [8/11/2021, 08:22:36] [Hue] config.json: nupnp: invalid key
```
This causes an error when Homebridge Hue tries to expose the _Lightbulb_ service:
```
Aug 11 08:22:37 raspberrypi homebridge[328]: TypeError: Cannot read property 'updateValue' of undefined
Aug 11 08:22:37 raspberrypi homebridge[328]:     at new HueLight (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:479:9)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at HueAccessory.exposeLightResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:235:19)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at HueAccessory.exposeLightResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:225:12)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:589:49)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:118:16)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at processTicksAndRejections (internal/process/task_queues.js:89:5)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at async Promise.all (index 0)
Aug 11 08:22:37 raspberrypi homebridge[328]:     at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:234:29)
```
> One thing i noticed is that the lights are the only ones in my home labeled as "Extended Color Light", whereas other "Dimmable Light" just work fine.

Indeed, Adaptive Lighting is only for _Extended Color Light_ and _Color Temperature Light_ lights.

I'm afraid you'll have to upgrade your Homebridge installation.  Downgrading Homebridge Hue will probably not work, as you need a recent version with changes to support the latest Hue bridge firmware.

**Comment by Fastdesigner** [comment]
Thank you. You are totally right. Was afraid updating right away but did now after backup. Had to recreate all scenes and automations using these lights but they work just fine now.

thank you for your patience and help!
