### ISSUE TITLE
Phoscon API key not showing in Hoobs' log when click on Authenticate app button

### ISSUE THREAD

**Issue by freemanuk** [ebaauw/homebridge-hue#1012]
I am using my Conbee II via Docker from my Synology NAS.  Lately, I have upgraded to Synology DSM 7 and I managed to run my Conbee II with some new commands:(https://www.reddit.com/r/synology/comments/nuameo/how_to_make_conbee_2_work_with_home_assistant_on/?utm_source=share&utm_medium=web2x&context=3)

Even though, my Conbee II is up and running now, I could not add that to Hoobs, as the Phoscon API key is not showing in Hoobs' log, every time I clicked on Authenticate app button. 

Is that a way to resolve this?

**Comment by ebaauw** [comment]
See #973.
