### ISSUE TITLE
Tradfri On/Off Switches show as lights in HomeKit?

### ISSUE THREAD

**Issue by gmum4d** [ebaauw/homebridge-hue#1013]
#### Issue

Hi, I have added 3 Tradfri On/Off switches to my conbee2 via phoscon and exposed them to HomeKit Via Hoobs with the home bridge-hue plugin. But they show up in HomeKit as Lights instead of switches. 
#### Log Messages

```
1/08/2021, 17:56:54 Hue Bridge Hue TRADFRI on/off switch : homekit transition control set to {"colorTemperature":{"iid":18}}
11/08/2021, 17:56:54 Hue Bridge Hue TRADFRI on/off switch : homekit transition control set to {"colorTemperature":{"iid":18}}
11/08/2021, 17:56:54 Hue Bridge Hue TRADFRI on/off switch : homekit transition control set to {"colorTemperature":{"iid":18}}

```

#### Debug Files

{
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "name": "Hue",
            "brightnessAdjustment": 100,
            "heartrate": 5,
            "lowBattery": 25,
            "timeout": 5,
            "waitTimePut": 50,
            "waitTimePutGroup": 1000,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20,
            "users": {
                "00212EFFFF065333": "9637C5FD40"
            },
            "linkButton": true,
            "groups": true,
            "scenesAsSwitch": false
        }
    ]
}

11/08/2021, 18:10:39 Hue Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
11/08/2021, 18:10:42 Hue Bridge Loaded plugin 'homebridge-hue'
11/08/2021, 18:10:42 Hue Bridge [ DEBUG ] Registering platform 'homebridge-hue.Hue'
11/08/2021, 18:10:42 Hue Bridge Loading 1 platforms...
11/08/2021, 18:10:42 Hue Bridge Hue homebridge-hue v0.13.19, node v14.17.4, homebridge v1.3.4
11/08/2021, 18:10:42 Hue Bridge Hue searching bridges and gateways
11/08/2021, 18:10:47 Hue Bridge Hue Phoscon-GW: dresden elektronik deCONZ gateway v2.11.5, api v1.16.0
11/08/2021, 18:10:47 Hue Bridge Hue Phoscon-GW: 5 accessories
11/08/2021, 18:10:47 Hue Bridge Hue masked debug info dumped to /var/lib/hoobs/huebridge/homebridge-hue.json.gz
11/08/2021, 18:10:47 Hue Bridge Hue Phoscon-GW: 3 services
11/08/2021, 18:10:47 Hue Bridge [ DEBUG ] Preparing Advertiser for 'Hue Bridge DA54' using bonjour-hap backend!
11/08/2021, 18:10:47 Hue Bridge [ DEBUG ] Starting to advertise 'Hue Bridge DA54' using bonjour-hap backend!
11/08/2021, 18:10:47 Hue Bridge Bridge is running on port 52826.
![Screenshot 2021-08-11 at 20 16 30](https://user-images.githubusercontent.com/16610988/129089604-2d2ba7f9-39e3-4443-b2c3-5ded50cfee5b.png)
![Screenshot 2021-08-11 at 20 15 41](https://user-images.githubusercontent.com/16610988/129089624-18aba117-2a11-4163-b1e3-e205197d5427.png)

**Comment by ebaauw** [comment]
See FAQ
