### ISSUE TITLE
Aqara H1 Switch appears as house icon ("not supported")

### ISSUE THREAD

**Issue by lawrencebensaid** [ebaauw/homebridge-hue#1016]
#### Issue
Two of my Aqara H1 Wireless Remote Switch (Double Rocker) accessories were added as a house icon with the text "not supported" and I can't remove them from my favourites. How do I either change them into a switch or remove them from the favourites screen?

**homebridge-hue plugin version:** *v0.13.19*

**deCONZ version:** *2.12.06 / 19/08/2021*

**Product:** [Wireless Remote Switch H1](https://www.aqara.com/en/product/wireless-remote-switch-h1)

**Apple Home app:**

![IMG_0510](https://user-images.githubusercontent.com/43364935/130653681-3eb51b5b-233f-42fd-9648-a8349e6da7fa.jpeg)

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/7040796/homebridge-hue.json.gz)

[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/7040807/homebridge.log)

**Comment by ebaauw** [comment]
Please attach the debug dump file and screenshots of the accessory details.

**Comment by lawrencebensaid** [comment]
@ebaauw Sorry, I've added it to the original post.

**Comment by ebaauw** [comment]
What are the serial numbers for the accessories?

**Comment by lawrencebensaid** [comment]
**Model:** lumi.remote.b28ac1

**Serial numbers:**
- 54EF4410001B09D5
- 54EF441000068CDF

*They are supposed to be the exact same

![IMG_10D4E0410DF5-1](https://user-images.githubusercontent.com/43364935/130664338-3be77121-7b20-4111-a493-b9cdf341888d.jpeg)

**Comment by bollekkk** [comment]
Hey there!
Trying to add Aqara H1 to my Homekit too. It's succesfully connected via deConz.
Can you tell a beginner what to do with the HueSensor.js File?

Thanks and best regards
