### ISSUE TITLE
Graphical configuration broken

### ISSUE THREAD

**Issue by sschuste** [ebaauw/homebridge-hue#1019]
#### Issue

It is not possible to add/edit the "users" via homebridge-config-ui-x 

<img width="895" alt="homebridge-hue settings" src="https://user-images.githubusercontent.com/37613765/131487537-5d139859-6bbf-40f2-a500-f347891b6afa.png">

#### Log Messages

```
```

**Comment by ebaauw** [comment]
No, it’s not.  The UI doesn’t support variable keys.

**Comment by sschuste** [comment]
Ah, ok. That was quick :-D
