### ISSUE TITLE
Programmable Switches Lutron Pico

### ISSUE THREAD

**Issue by ajiuo666** [ebaauw/homebridge-hue#102]
I read the thread on the hue switches, but what about the Lutron pico remotes and/or connected Bulb remotes? Any pathway to thoes working? They look som much nicer then the hue dimmer and can be mounted in a standard switch plate.

**Comment by ebaauw** [comment]
I'm unfamiliar with these.  Are they even available in Europe?

Note that homebridge-hue doesn't connect directly to any switch (or sensor, or light).  It connects to the Hue bridge, which, in turn, connects to the device over ZigBee wireless networking.

Looking at their web site, the Lutron connected bulb remote uses ZigBee as well.  In theory, you might be able to connect these to your Hue bridge, and I could add support in homebridge-hue.  In practice, Philips use vendor specific extentions to the ZigBee standard in connecting their dimmer switches and motion sensors.  I doubt you'll get the Hue bridge to work with any non-Philips switch or sensor.  The pico remotes use a different wireless technology altogether, still looking at the Lutron web site.  Connecting these to the Hue bridge is technically impossible.

**Comment by ebaauw** [comment]
@ajiuo666 Did you post [this](https://developers.meethue.com/content/lutron-connected-bulb-remote) in the Hue developer forum?  If so, does the mentioned hack make the Lutron switch visible on the Hue bridge, or does it just pair the switch directly with the lights?  In the first case: could you please post a dump of your bridge state (see README).

**Comment by ajiuo666** [comment]
You first have to pair the switch with the hue bridge, and then pair it with the bulb, manually. If you don't pair it with the bridge first it will just steel the bulbs from the bridge. You pair it with the bridge the same way you pair a Lutron dimmer... The Lutron Switch eventually detects that it's linked, but it never shows up in the bridge... at least on the UI end... I'm not sure if the bridge has some reference to it... I will see if I can get a dump when I get home.

**Comment by toogle9** [comment]
I've got 6 of these around the house so far, with plans for more.  As you said, they are more attractive, and they fit into a standard US wallplate unlike the Hue dimmers.

You are not actually "pairing" the Lutron remote with the bridge, when you go through the light link process with the bridge, the remote just listens and sets itself to the correct Zigbee channel that your bridge is using.  The bridge is completely unaware of the remote as far as I know.  In fact, I only paired the first one with the bridge, the others have all been paired against one of the other Lutron remotes that is already working.  The reason why they steal the lights from the bridge, is that a new or factory reset remote is most likely on a different channel than you are using with your bridge, so unless you pair it with the bridge or another remote first to get the channel set correctly, it steals the bulb over to the channel the remote is using out of the package or from reset.

The Hue dimmers are nice because you can set specific button functions, but you are limited in the number of dimmers or taps you can have.  The Lutron remotes are nice because of the size, but you can't set button functions because the bridge is not aware of them, they talk directly to the lights you pair with.  On the plus side as far as I know there is no limit to the number you can have because they aren't defined to the bridge.  On the negative side, if you have a lot of these and ever have to change Zigbee channels, they will all have to be manually reset and re-paired to the correct channel and bulbs again.

This is my current understanding of how they work, hope that helps!

**Comment by ajiuo666** [comment]
I currently use connected Bulb remotes for basic light control and pico remotes for scene triggering.

You can actualy use a Lutron lamp dimmer to trigger HomeKit scenes...  The dimmer doesn't even have to be plugged in once HomeKit has learned it.  You basically just set up a HomeKit trigger to activate a scene when the lamp dimmer it's a specific percentage that corresponds to the button on the pico remote...  and then you need another trigger to reset the lamp dimmer to a default value when any change takes place..  The response time is pretty quick...  it would be nice if they were officially supported though.  A little bit easier set up

**Comment by ebaauw** [comment]
Thanks, @toogle9, @ajiuo666 

> You are not actually "pairing" the Lutron Connected Bulb Remote with the bridge, when you go through the light link process with the bridge, the remote just listens and sets itself to the correct Zigbee channel that your bridge is using.

Also, the Hue bridge exchanges the ZigBee network key with the dimmer, and the dimmer joins the network.

> The Lutron Switch eventually detects that it's linked, but it never shows up in the bridge... at least on the UI end... I'm not sure if the bridge has some reference to it

I don't think it has.  Joining the ZigBee network is separate from the bridge configuring the sensor resource.  When performing a touchlink with the bridge, "any" device might join the network; when searching for new devices, the bridge only configures devices it likes.

> The reason why they steal the lights from the bridge, is that a new or factory reset remote is most likely on a different channel than you are using with your bridge, so unless you pair it with the bridge or another remote first to get the channel set correctly, it steals the bulb over to the channel the remote is using out of the package or from reset.

A factory-new dimmer actually creates a ZigBee network on the fly.  The light joins this network and is no longer in the Hue bridge network.

> The Hue dimmers are nice because you can set specific button functions, but you are limited in the number of dimmers or taps you can have.

The number of dimmers that can be recognised/configured by the Hue bridge is limited by the number of sensor resources (63).  The Hue app limits this even further by creating Hue bridge rules for each dimmer.  The number of dimmers that can be on the same ZigBee network is "unlimited", just as for the Lutron remotes.

> On the negative side, if you have a lot of these and ever have to change Zigbee channels, they will all have to be manually reset and re-paired to the correct channel and bulbs again.

Did you actually test this?  I think a channel change is broadcast, so each device on the network should pick it up, not only the ones known by the Hue bridge.

**Comment by toogle9** [comment]
@ebaauw thanks for all the clarifications!  No, I hadn't tested the Lutron Connected Bulb Remote / channel change scenario, I was just assuming it would be a challenge because they weren't registered with the bridge.  I've had some random Hue "no response" issuses and was considering changing channels, but it seems to have stabilized more lately.

@ajiuo666 the Lutron lamp dimmer / Pico remote / HomeKit trigger thing sounds interesting, do you have any links on that with any additional setup details?  I did a quick Google and didn't get any interesting hits.  When you said they didn't have to remain plugged in once HomeKit has learned it, did you mean it didn't have to have a device/lamp connected to it, or the dimmer module itself no longer needed to be plugged in?  Not seeing how it could communicate it's status if it wasn't plugged in at all.  I'm considering getting one of the Caseta switches for a dining room light, where it would not be cost effective for the new Hue E14 bulbs.  I don't really need color there anyway, just want to be able control/dim.  Disappointed I would need another bridge though, but sounds like I would need that for the lamp dimmer setup anyway.

**Comment by jocamero** [comment]
Did anyone ever get the Lutron pico switches to show up in homebridge-hue?

**Comment by ebaauw** [comment]
They would need to show up in the Hue bridge first, before homebridge-hue can do anything with them.

**Comment by jocamero** [comment]
Ohhh!  I didn't understand that was the limitation.  Thanks.  So, is this even technically feasible?  Hue would need to update the Bridge firmware to support them via the app?  Then...  homebridge-hue would make them 'HomeKit compatible'?

As a sidenote, I have my Lutron Pico remotes working perfectly, I would recommend them to others.  Even when I change the channel in the Hue app for troubleshooting purposes, the remotes continued to work on the new channel.  Any idea how the Pico remotes learn the new channel??

**Comment by ebaauw** [comment]
> Ohhh! I didn't understand that was the limitation.

Like any other Hue app, homebridge-hue has no access to the ZigBee network (you'd need ZigBee hardware for that), and uses the Hue bridge as a gateway to interact with ZigBee devices.

> So, is this even technically feasible? Hue would need to update the Bridge firmware to support them via the app? Then... homebridge-hue would make them 'HomeKit compatible'?

I don't think Philips will update the Hue bridge to support non-Philips sensors and switches.  Ever.  It would be possible to add support for the Pico to [deCONZ](https://github.com/dresden-elektronik/deconz-rest-plugin), and use homebridge-hue to expose it to HomeKit.

> I have my Lutron Pico remotes working perfectly
> Even when I change the channel in the Hue app for troubleshooting purposes, the remotes continued to work on the new channel. Any idea how the Pico remotes learn the new channel?

ZigBee isn't a standard for a single single protocol, but for a set of protocols, covering the entire OSI model, all the way down from the phisical layer all the way up through the application layer.  The Pico is connected at the lower network level, where the channel change is managed.  It's not compatible at the higher application level, where the Hue bridge provides the REST API.  The same holds for IKEA bulbs (on old firmware) and OSRAM bulbs (on US firmware) and any non-Hue sensors and switches.

To give an example: Both my iPhone and printer are connected to the same WiFi network, but still I cannot print from my iPhone, which only supports AirPrint, to my printer, which doesn't.  Yet both devices will handle a change of the WiFi channel.  Of course, in this example we use different names for the different levels (viz. "WiFi" for the network level vs "AirPrint" for the application level).  The confusing part is that "ZigBee" sometimes refers to all these levels at the same time, and sometimes not.  It's a bit like the early Bluetooth days, where two devices, both supporting Bluetooth would pair, but wouldn't connect, as they lacked a common profile.

**Comment by logname** [comment]
There is a path to this. It would be nice if it was node.js to Hue Bridge, but for now it needs SmartThings AND since SmartThings needs the cloud, it doesn't communicate with SmartThings or the Hue Bridge if there's no access to the cloud. But, it does work and really well. Once configured, adding and configuring remotes is simple. Plus this opens up access to a lot of devices and interactions that are not possible with the Hue Bridge alone.

https://community.smartthings.com/t/how-to-control-anything-with-inexpensive-lutron-pico-remotes/117761

**Comment by luczk0wiak** [comment]
Was support for the Lutron Connected Bulb Remote ever added to homebridge-hue? It is supported in deCONZ, and I can pair it to my conbee ii, but it is only throwing up errors with the hue plugin.

**Comment by ebaauw** [comment]
Probably not.  Please attach the debug dump file, so I can see what the switch looks like.  What buttonevent values does it use?

**Comment by luczk0wiak** [comment]
Here are the logs:

>   12/7/2020, 8:28:36 AM Loaded plugin 'homebridge-hue'
12/7/2020, 8:28:36 AM [12/7/2020, 6:28:36 AM] Registering platform 'homebridge-hue.Hue'
12/7/2020, 8:28:36 AM Loading 1 platforms...
12/7/2020, 8:28:36 AM [Hue] Initializing Hue platform...
12/7/2020, 8:28:36 AM [Hue] config.json: warning: plugin_map: ignoring unknown key
12/7/2020, 8:28:36 AM [Hue] homebridge-hue v0.12.8, node v12.19.0, homebridge v1.1.6
12/7/2020, 8:28:36 AM [Hue] warning: not using recommended node version v14.15.1 LTS
12/7/2020, 8:28:36 AM [Hue] searching bridges and gateways
12/7/2020, 8:28:41 AM [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.88, api v1.16.0
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.88, api v1.16.0
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: /sensors/3: warning: ignoring unknown ZHASwitch sensor {"config":{"on":true,"reachable":true},"ep":1,"etag":"cac068a2ca5d7a9642b72ff77e9f438b","lastseen":"2020-12-07T13:28Z","manufacturername":"Lutron","mode":4,"modelid":"LZL4BWHL01 Remote","name":"Connected Bulb Remote","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.1","type":"ZHASwitch","uniqueid":"ff:ff:00:0f:e7:ff:43:c3-01-1000"}
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: error: /sensors/3: {"config":{"on":true,"reachable":true},"ep":1,"etag":"cac068a2ca5d7a9642b72ff77e9f438b","lastseen":"2020-12-07T13:28Z","manufacturername":"Lutron","mode":4,"modelid":"LZL4BWHL01 Remote","name":"Connected Bulb Remote","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.1","type":"ZHASwitch","uniqueid":"ff:ff:00:0f:e7:ff:43:c3-01-1000"}
TypeError: Cannot read property 'addOptionalCharacteristic' of undefined
    at new HueSensor (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueSensor.js:1728:16)
    at HueAccessory.exposeSensorResource (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:324:20)
    at HueAccessory.exposeSensorResources (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:314:12)
    at HueAccessory.expose (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:126:8)
    at HueBridge.exposeResources (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:573:49)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:103:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HuePlatform.js:324:29)
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: 3 accessories
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: /sensors/3: warning: ignoring unknown ZHASwitch sensor {"config":{"on":true,"reachable":true},"ep":1,"etag":"cac068a2ca5d7a9642b72ff77e9f438b","lastseen":"2020-12-07T13:28Z","manufacturername":"Lutron","mode":4,"modelid":"LZL4BWHL01 Remote","name":"Connected Bulb Remote","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.1","type":"ZHASwitch","uniqueid":"ff:ff:00:0f:e7:ff:43:c3-01-1000"}
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: error: /sensors/3: {"config":{"on":true,"reachable":true},"ep":1,"etag":"cac068a2ca5d7a9642b72ff77e9f438b","lastseen":"2020-12-07T13:28Z","manufacturername":"Lutron","mode":4,"modelid":"LZL4BWHL01 Remote","name":"Connected Bulb Remote","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.1","type":"ZHASwitch","uniqueid":"ff:ff:00:0f:e7:ff:43:c3-01-1000"}
TypeError: Cannot read property 'addOptionalCharacteristic' of undefined
    at new HueSensor (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueSensor.js:1728:16)
    at HueAccessory.exposeSensorResource (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:324:20)
    at HueAccessory.exposeSensorResources (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:314:12)
    at HueAccessory.expose (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:126:8)
    at HueBridge.exposeResources (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:573:49)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:103:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
    at async HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HuePlatform.js:324:29)
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: 3 accessories
12/7/2020, 8:28:42 AM [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
12/7/2020, 8:28:42 AM Initializing platform accessory 'Phoscon-GW'...
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: 2 services
12/7/2020, 8:28:42 AM Initializing platform accessory 'Daylight'...
12/7/2020, 8:28:42 AM Initializing platform accessory 'Connected Bulb Remote'...
12/7/2020, 8:28:42 AM Initializing platform accessory 'Phoscon-GW'...
12/7/2020, 8:28:42 AM [Hue] Phoscon-GW: 2 services
12/7/2020, 8:28:42 AM [Hue] homebridge: error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 62afca17-a996-474f-8006-f5a85fecc7af

And I believe this is the button info in deCONZ:

```
+static const Sensor::ButtonMap lutronLZL4BWHLSwitchMap[] = {
+//    mode                          ep    cluster cmd   param button                                       name
+//  vendor specific
+    // top button
+    { Sensor::ModeDimmer,           0x01, 0x0008, 0x04, 0xfe,  S_BUTTON_1 + S_BUTTON_ACTION_SHORT_RELEASED, "on" },
+    // second button
+    { Sensor::ModeDimmer,           0x01, 0x0008, 0x06, 0x00,  S_BUTTON_2 + S_BUTTON_ACTION_HOLD,           "dimm up" },
+    { Sensor::ModeDimmer,           0x01, 0x0008, 0x03, 0x00,  S_BUTTON_2 + S_BUTTON_ACTION_LONG_RELEASED,  "dimm up release" },
+    // third button
+    { Sensor::ModeDimmer,           0x01, 0x0008, 0x02, 0x01,  S_BUTTON_3 + S_BUTTON_ACTION_HOLD,           "dimm down" },
+    { Sensor::ModeDimmer,           0x01, 0x0008, 0x03, 0x01,  S_BUTTON_3 + S_BUTTON_ACTION_LONG_RELEASED,  "dimm down release" },
+    // bottom button
+    { Sensor::ModeDimmer,           0x01, 0x0008, 0x04, 0x00,  S_BUTTON_4 + S_BUTTON_ACTION_SHORT_RELEASED,  "off" },
+
+    // end
+    { Sensor::ModeNone,             0x00, 0x0000, 0x00, 0,    0,                                           0 }
+};
```

**Comment by ebaauw** [comment]
There’s more going on than an unsupported switch.  Homebridge Hue seems to find your deCONZ gateway twice?

**Comment by luczk0wiak** [comment]
Yeah, I'm new to homebridge and did a quick and dirty setup. I'm about to do a fresh install that should fix that.

**Comment by luczk0wiak** [comment]
I fixed the duplication error on my end. Here is the cleaned up log:

> 12/7/2020, 11:10:53 AM Loaded plugin 'homebridge-hue'
12/7/2020, 11:10:53 AM Loading 1 platforms...
12/7/2020, 11:10:53 AM [12/7/2020, 9:10:53 AM] Registering platform 'homebridge-hue.Hue'
12/7/2020, 11:10:53 AM [Hue] Initializing Hue platform...
12/7/2020, 11:10:53 AM [Hue] config.json: warning: plugin_map: ignoring unknown key
12/7/2020, 11:10:53 AM [Hue] homebridge-hue v0.12.8, node v12.19.0, homebridge v1.1.6
12/7/2020, 11:10:53 AM [Hue] warning: not using recommended node version v14.15.1 LTS
12/7/2020, 11:10:54 AM [Hue] searching bridges and gateways
12/7/2020, 11:10:59 AM [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.88, api v1.16.0
12/7/2020, 11:10:59 AM [Hue] Phoscon-GW: /sensors/1: warning: Daylight sensor not configured
12/7/2020, 11:10:59 AM [Hue] Phoscon-GW: /sensors/2: warning: ignoring unknown ZHASwitch sensor {"config":{"on":true,"reachable":true},"ep":1,"etag":"d9c6141565256719c57d3a28cae0a3a8","lastseen":"2020-12-07T15:34Z","manufacturername":"Lutron","mode":4,"modelid":"LZL4BWHL01 Remote","name":"Connected Bulb Remote","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.1","type":"ZHASwitch","uniqueid":"ff:ff:00:0f:e7:ff:43:c3-01-1000"}
12/7/2020, 11:10:59 AM [Hue] Phoscon-GW: error: /sensors/2: {"config":{"on":true,"reachable":true},"ep":1,"etag":"d9c6141565256719c57d3a28cae0a3a8","lastseen":"2020-12-07T15:34Z","manufacturername":"Lutron","mode":4,"modelid":"LZL4BWHL01 Remote","name":"Connected Bulb Remote","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.1","type":"ZHASwitch","uniqueid":"ff:ff:00:0f:e7:ff:43:c3-01-1000"}
TypeError: Cannot read property 'addOptionalCharacteristic' of undefined
    at new HueSensor (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueSensor.js:1728:16)
    at HueAccessory.exposeSensorResource (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:324:20)
    at HueAccessory.exposeSensorResources (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:314:12)
    at HueAccessory.expose (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueAccessory.js:126:8)
    at HueBridge.exposeResources (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:573:49)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HueBridge.js:103:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-hue/lib/HuePlatform.js:324:29)
12/7/2020, 11:10:59 AM [Hue] Phoscon-GW: 3 accessories
12/7/2020, 11:10:59 AM [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
12/7/2020, 11:10:59 AM Initializing platform accessory 'Phoscon-GW'...
12/7/2020, 11:10:59 AM [Hue] Phoscon-GW: 2 services
12/7/2020, 11:10:59 AM Initializing platform accessory 'Daylight'...
12/7/2020, 11:10:59 AM Initializing platform accessory 'Connected Bulb Remote'...
12/7/2020, 11:10:59 AM Bridge is running on port 51826.
12/7/2020, 11:11:00 AM [Hue] Daylight: set homekit dark from 1 to 0

**Comment by ebaauw** [comment]
In v0.10.12.

**Comment by isaacniebeling** [comment]
Is there anything special to do to get the Hue Bridge to recognize the switch? I've followed the steps that are posted everywhere [1], and while the dimmer _will_ adjust the bulbs in the room on its own (after pairing them in step 5), I don't see any evidence of it, well.. anywhere. It's not showing up in the dump or in the verbose debugging log or anything. 

Logs are attached if it's helpful. If you'd rather I start a new issue, I'm happy to do so. I also totally get it if this isn't really a question you can answer.

Thanks!

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5670236/homebridge-hue.json.gz)
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/5670237/homebridge.log.gz)

[1] Steps:

> 1/Pair bulb and hub as normal, test functions of bulb with Hue app
> 
> 2/unwrap the remote Hold On and Off on remote for 10s to factory reset
> 
> 3/use Hue app to add a Hue Dimmer Switch, selecting Option 1, New Remote
> 
> 4/Use the On button on the remote, hold it next to Hue Hub and hold on for about 4s. Watch the remote LED. You are looking for fast blinking of the remote LED to indicate pairing was successful. The Hue app will not display >any information about the pairing.
> 
> 5/Go to the smart bulb and hold the remote to it, hold On for 10s, wait for the bulb to finish flashing, the remote to finish blinking fast indicating successful pairing. (keep holding it down until after the blink!)
> 
> 6/Remote joined master network at Hue Hub, then made secondary network with bulb.

**Comment by ebaauw** [comment]
> Is there anything special to do to get the Hue Bridge to recognize the switch?

Technically, there are two routes to this, but its probably easier and quicker just to move to deCONZ:
1. Get Signify to change the Hue bridge firmware.  As far as I know, they only do that for Friends-of-Hue switches, which are all ZGP devices, except for the Lutron Aurora.  That Aurora actually looks like its Zigbee part has been designed, or at least co-designed, by Signify/Philips;
2. Get Lutron to change the switch firmware, so it appears to be a (Friends-of-)Hue device to the Hue bridge.  I’m not sure what the legal implications would be, but technically it’s possible e.g. for non-Hue lights to expose the _Manufacturer Code_ of Philips, so the Hue bridge exposes them to HomeKit.

**Comment by isaacniebeling** [comment]
> Technically, there are two routes to this, but its probably easier and quicker just to move to deCONZ:

Ah, gotcha — it wasn’t super clear that deCONZ was required for it to work. Thanks!
