### ISSUE TITLE
ph tool remote access

### ISSUE THREAD

**Issue by Razeeer** [ebaauw/homebridge-hue#1025]
I have two raspberry pi in use with deconz and use the ph tool from you in the network to access the REST api on both.
Within the network it is even possible to send commands from pi 1 shell to pi 2. I find this feature very useful as I can also switch sockets from pi 1 to pi 2 via a script.

My question to you about the ph tool. Is it possible to send other commands remotely to my second pi. 
For example a sudo reboot now -h ? 

So far I have not found a way so I would be happy if you can give me a hint if it is possible or if you can make it possible? Thank you.

**Comment by ebaauw** [comment]
Set `PH_HOST` or use `ph -H `_hostname_`:`_port_ to specify what gateway/bridge `ph` works on.  If you don't, it uses `127.0.0.1:80`, which typically is the local deCONZ instance.

`ph` is a Hue/deCONZ API client; it doesn't interact with the (local or remote) system the API server is running on.  To issue shell commands, like `sudo reboot now -h`, to a remote system securely, use `ssh`.

**Comment by Razeeer** [comment]
Hey thanks for the quick reply. Because remote access for the rest api I have already successfully in use. I was hoping to use this also for normal shell commands. Would this be technically possible to implement or are you saying this is not something the ph tool should be able to do?

So far I haven't found any other way to do it via ssh. Do you have a tip what I should look for?

**Comment by ebaauw** [comment]
> Would this be technically possible to implement

No, the Hue/deCONZ API does not provide a way to execute a command.

> So far I haven't found any other way to do it via ssh. Do you have a tip what I should look for?

https://en.wikipedia.org/wiki/Secure_Shell.  Once setup, you can simply run commands remotely:
```
$ uname -a
Darwin macmini.stdnkd 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
$ ssh pi1 uname -a
Linux pi1 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
$ ssh pi10 uname -a
Linux pi10 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

**Comment by Razeeer** [comment]
Thanks for the tip. Now I got it right! Have a nice Sunday.
