### ISSUE TITLE
Logging temperature scale

### ISSUE THREAD

**Issue by toogle9** [ebaauw/homebridge-hue#103]
Hello.  Apologies if this has already been asked before, but I searched through the issues and wiki and couldn't find any mention.

When homebridge-hue reports temperature of my hue sensor to the homebridge.log file, it's using celsius.  Is there a way to change that to fahrenheit?  The temperature reports as °F through the iOS Home app just fine, it's just being logged in the log as °C.  I'm not finding this as a homebridge setting either.  My homebridge-nest plugin logs correctly as °F.

This is more of an annoyance than a problem, just wondered if there was a way to change.

Thanks!

**Comment by ebaauw** [comment]
The Hue bridge only supports Celsius.  HomeKit only supports Celsius.  It's up to the HomeKit app to convert the temperature to Fahrenheit.

Apparently, Nest supports both Celsius and Fahrenheit.  It looks like homebridge-nest actually [converts](https://github.com/KraigM/homebridge-nest/blob/master/lib/nest-thermostat-accessory.js#L108) the temperature from Fahrenheit to Celsius and then the Home app converts it back to Fahrenheit.

**Comment by toogle9** [comment]
Great information, was not aware that both Hue and HomeKit only supported Celsius and that Nest apparently is the odd man out.  Not a huge deal, just wondered if there was an option lurking somewhere that I was missing.

Thanks for the prompt reply!
