### ISSUE TITLE
HomeKit unresponsive when changing settings from a large group

### ISSUE THREAD

**Issue by eliteladen** [ebaauw/homebridge-hue#1030]
I started using the plugin now, currently I have 11 Zigbee lights that are not compatible with HomeKit. After the plug-in exposed them, I tried grouping all as 1 device and it works. However, if I try to change the brightness or change colors, my whole app starts freezing and becomes extremely unresponsive, is there anything I can do to mitigate that? Using adaptive lights is pretty much impossible, since the app will completely stop work. I’m using a Hue Brige v2, don't know if that's relevant or not. 

Thank you for all the help and for the plug-in.

**Comment by ebaauw** [comment]
Please attach the debug dump file, and capture and attach a debug log file.  See the FAQ on how to do that.

What HomeKit app are you using?  What version of iOS?

In general, using groups on the Hue bridge is more responsive and more reliable than using HomeKit groups.
