### ISSUE TITLE
query for power characteristic history

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#1036]
Would you apply historical data to the (Power) on / off characteristic just like eve energy?

![0A480B7D-2454-48B0-931C-F527B6122A0A](https://user-images.githubusercontent.com/34716572/139046408-0dfead18-3542-4ed2-a2b7-cd3c0b45780a.jpeg)

**Comment by ebaauw** [comment]
So with fakegato,  it's either history for _On_ or for _Consumption_.  I can do both with the homebridge-lib implementation of Eve history, but need to refactor Homebridge Hue for that, see #4.

**Comment by ebaauw** [comment]
Closing this issue.  The combined history will be included in Homebridge deCONZ, see #1070.
