### ISSUE TITLE
Support for Node.js V16

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#1038]
Hi, 
Do you have planned to bring support for Node.js version 16?

Thanks!

**Comment by ebaauw** [comment]
Yes, I’m working on that.  Also got a new M1 Pro macbook and a Pi Zero 2 W this weekend, so it’s taking a bit longer to set everything up.

**Comment by jostrasser** [comment]
Great, thanks!
FYI: Already running V16, cannot see any issues right now.

**Comment by ebaauw** [comment]
In v0.13.27.

I don't see any issues either, after updating my installations to Node v16.13.0 LTS.

**Comment by jostrasser** [comment]
Many thanks @ebaauw !
Have a great weekend
