### ISSUE TITLE
Adding switches

### ISSUE THREAD

**Issue by kapps7** [ebaauw/homebridge-hue#104]
Hey.

I have installed the plugin with the following json and the bridge is running normally.

> "platform": "Hue",
      "name": "Hue",
      "host": "",
      "users": {
        "001788FFFExxxx": "xxxxxxxxxxxxxxxxxxxxxxxxx"
      },
      "sensors": true,
      "excludeSensorTypes": [],
      "lowBattery": 25,
      "lights": false,
      "philipsLights": false,
      "ct": false,
      "wallSwitch": true,
      "groups": false,
      "group0": false,
      "rooms": false,
      "schedules": true,
      "rules": true,
      "heartrate": 5,
      "timeout": 5,
      "parallelRequests": 10,
      "waitTimeResend": 300,
      "waitTimeSwitch": 100,
      "waitTimeUpdate": 20

- I am trying to find my dimmer switch to map buttons. Do I need to install it as an accessory or should it have come up by itself.
- I also have a new accessory that I hadn't seen before called Daylight that is point to this bridge. Am wondering if that is part of this somehow. -- Ok I have since understood that is part of the bridge. Is it possible to set the location within Homebridge ?

Thanks.

Edit: Do I need the Eve app to get it working ?

**Comment by ebaauw** [comment]
If the dimmer switch is connected to the Hue bridge, it should show up by itself.  Can you see it in the Hue app?  You are on iOS 10.3?

Daylight is the Hue bridge built-in daylight sensor.  You need to configure it on the Hue bridge, specifying your local latitude and longitude coordinates.  You can disable this sensor being exposed to HomeKit by specifying`"excludeSensorTypes": [ "Daylight" ]` in config.json.

If you start `homebridge -D`, homebridge-hue will log a debug message for each sensor resource on the Hue bridge.

**Comment by kapps7** [comment]
Thanks Eric, it was just a matter of restarting Homebridge.

With regards to daylight, it seems that it doesn't allow to trigger x minutes before or after sunrise or sunset so I might use the json in the daylight plugin.

Thanks of your help, a good start. Lets see how we go with a few switches running :)

**Comment by ebaauw** [comment]
> it was just a matter of restarting Homebridge

Odd - I've got no clue how a simple restart would change anything, given that homebridge-hue did expose the Daylight sensor already.

> With regards to daylight, it seems that it doesn't allow to trigger x minutes before or after sunrise or sunset

You can configure sunriseoffset and sunsetoffset on the Hue bridge, but you'll only get one trigger per sunrise or sunset.

**Comment by kapps7** [comment]
I'll revisit the dev docs and locate the offsets. Thanks for your help on the one.
