### ISSUE TITLE
Detect/report non reachable sensors

### ISSUE THREAD

**Issue by keness521** [ebaauw/homebridge-hue#1047]
Homebridge-hue is not doing anything wrong, but I’m wondering is I have missed an option, setting or possibility.

I feel I’ve read about this, but can’t find it anywhere. Apologies if it has been asked before!

I have oodles of temperature sensors all over the place. (All Aqara or Mi.)

I only JUST noticed that a couple of them show as ‘Not Reachable’ in the Phoscon web app. If I understand correctly, in this state, deconz and/or homebridge-hue continue to report their last valid reading. That would make sense based on the readings I see in the Home app. (I thought I had some warm spots in some of my rooms, but I think it is just the last reading from a week or two ago! haha)

If I hadn’t gone into the Phoscon app, I wouldn’t have seen that those sensors were grayed out.

Is there a way to be alerted when a sensor has become non-reachable? Or has become non-reachable for longer than a certain amount of time? With lights, it’s kind of hard to miss when they’re non-reachable. But with sensors…

Or is someone aware of maybe an additional plug-in that can keep track of sensors and send an alert if it goes to a certain status or if it hasn’t had activity in longer than a certain amount of time?

Or am I just doing something totally wrong?

**Comment by ebaauw** [comment]
Homebridge Hue sets _Status Fault_ when the gateway reports devices as non-reachable.  Unfortunately the Home app ignores this, but Eve shows an exclamation mark.

See also https://github.com/ebaauw/homebridge-hue/wiki/No-Response.

**Comment by keness521** [comment]
Are you aware of any kind of plugin or other app or service that can act as a watchdog and alert to a "Status Fault" situation perhaps? I could swear I remember reading about something like this, somewhere, many months ago, before I realized it might be useful. But I can't find anything now. It might have been a dream...

**Comment by ebaauw** [comment]
_Status Fault_ can be used in HomeKit automations, just like any other numeric characteristic.  You just need to use a decent HomeKit app.  If you want a non-HomeKit approach, better use the deCONZ API to monitor `reachable`.

HomeKit only sends notifications for certain sensors, like smoke, motion, door/window.  See the _Home Settings_ in the Home app.  You could create a CLIP sensor in deCONZ, set that based on the light `state.reachable`, using deCONZ rules and then expose this virtual sensor through Homebridge Hue.  I’m not sure if deCONZ have implemented a CLIP version for each sensor type, but CLIPOpenClose works.  I use that to get a notification if my washing machine has finished.  I’m triggering the virtual sensor from `state.power` of the Heiman smart plug (when trying this at home, make sure to use a smart plug that can handle 16A, unlike the innr).
