### ISSUE TITLE
Phoscon Scenes do not appear in Homekit

### ISSUE THREAD

**Issue by spaggi** [ebaauw/homebridge-hue#1049]
Hi, 

we had a chat earlier on discord. Thank you very much for your assistance

I can't figure out how to show my Phoscon Scenes in Homekit.

According to everything I read and understood, the scene "Testi" which I created below the group "GROUP Küche Spots" should be visible as a switch in the GROUP Küche Spots-Accessory which is available in Homekit.

This is a screenshot of the scene in Phoscon
![image](https://user-images.githubusercontent.com/5416955/143098009-9f5f284c-1a63-4336-a695-7e39c435e5f0.png)

This is a screenshow of the detail view of said accessory
<img width="537" alt="Bildschirmfoto 2021-11-23 um 21 20 49" src="https://user-images.githubusercontent.com/5416955/143097903-3658453c-9234-449d-9555-7517d0821488.png">

#### Debug Files
Output of ph get /groups
[ph get groups.txt](https://github.com/ebaauw/homebridge-hue/files/7590797/ph.get.groups.txt)

Homebridge-Hue configuration
[homebridge-hue-config.txt](https://github.com/ebaauw/homebridge-hue/files/7590788/homebridge-hue-config.txt)

Homebridge-Hue dump file
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/7590743/homebridge-hue.json.gz)

Sorry, due to my minimal Linux skills, I'm not able to collect the homebridge log. What I did is enabled debug mode, restart HB and copy-pasted the log from the ui into a text file. I hope this suffices...
[homebridge-startup-log.txt](https://github.com/ebaauw/homebridge-hue/files/7590786/homebridge-startup-log.txt)

**Comment by ebaauw** [comment]
As mentioned in Discord: set `scenesAsSwitch` to see them in Home.  By default, Homebridge Hue exposes scenes using a custom service, not to confuse Siri.
