### ISSUE TITLE
Cant start Hue Plugin anymore

### ISSUE THREAD

**Issue by guzzzi** [ebaauw/homebridge-hue#1050]
#### Issue
Hue Plugin doesnt start anymore on Hoobs 4.0.100

I dont know if this is a Plugin oder a Hoobs Failure, so i have to start and want to ask here first, if someone can help me.

#### Log Messages
27.11.2021, 09:20:14Hue BridgeFEHLER[31mThe plugin "homebridge-hue" requires a Homebridge version of ^1.3.6 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
27.11.2021, 09:20:19Hue BridgeLoaded plugin 'homebridge-hue'
27.11.2021, 09:20:19Hue BridgeLoading 1 platforms...
27.11.2021, 09:20:20Hue BridgeHuehomebridge-hue v0.13.28, node v14.18.1, homebridge v1.3.4
27.11.2021, 09:20:20Hue BridgeHuesearching bridges and gateways
27.11.2021, 09:20:30Hue BridgeHuephoscon: request 1: GET /
27.11.2021, 09:20:30Hue BridgeHueWARNUNGphoscon: request 1: timeout after 10 seconds
27.11.2021, 09:20:30Hue BridgeHuephoscon: request 1: GET /
27.11.2021, 09:20:30Hue BridgeHueWARNUNGphoscon: request 1: timeout after 10 seconds
27.11.2021, 09:20:30Hue BridgeHueno bridges or gateways found - retrying in 30s

**Comment by ebaauw** [comment]
Looks like Homebridge Hue cannot connect to your deCONZ gateway.  By design, it will prevent Homebridge from starting, or you would lose all you HomeKit accessories.

**Comment by guzzzi** [comment]
Still getting this in the Log File

27.11.2021, 13:57:40Hue BridgeFEHLER[31mThe plugin "homebridge-hue" requires a Homebridge version of ^1.3.6 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m

But after the reinstall of the Conbee II it seems to work again. I dont know what happend, normaly it works perfect for month.
Never the less, thank you for your Help! And thank you for this great Plugin.

**Comment by ebaauw** [comment]
That warning just signals that I develop and test my plugins against the latest release of Homebridge.
