### ISSUE TITLE
Tasmota doesn’t support resourcelinks

### ISSUE THREAD

**Issue by suhajda3** [ebaauw/homebridge-hue#1052]
The beauty about updating is that something will brake.

I have updated to homebridge-hue v0.13.29 and Tasmota 10.0.0.
It looks like homebridge-hue tries to get the resourcelinks and since Tasmota doesn't support it, it cannot start.

> [11/29/2021, 1:33:10 PM] [Hue] Philips hue: request 3: GET /resourcelinks
> [11/29/2021, 1:33:10 PM] [Hue] Philips hue: request 3: timeout after 5 seconds
> [11/29/2021, 1:33:10 PM] [Hue] Philips hue: timeout after 5 seconds - retrying in 15s

$ ph -H 192.***.***.13 get /

> {
>   "lights": {
>     "234250913": {
>       "state": {
>         "on": true,
>         "alert": "none",
>         "effect": "none",
>         "reachable": true
>       },
>       "type": "Extended color light",
>       "name": "Snowflakes",
>       "modelid": "Generic",
>       "manufacturername": "Tasmota",
>       "uniqueid": "dc:**:**:**:**:2a:00:11-01"
>     }
>   },
>   "groups": {},
>   "schedules": {},
>   "config": {
>     "name": "Philips hue",
>     "mac": "DC:**:**:**:**:2A",
>     "dhcp": true,
>     "ipaddress": "192.***.***.13",
>     "netmask": "255.255.255.0",
>     "gateway": "192.***.***.1",
>     "proxyaddress": "none",
>     "proxyport": 0,
>     "bridgeid": "DC************2A",
>     "UTC": "2021-11-29T13:42:02",
>     "whitelist": {
>       "df662a": {
>         "last use date": "2021-11-29T13:42:02",
>         "create date": "2021-11-29T13:42:02",
>         "name": "Remote"
>       }
>     },
>     "swversion": "01041302",
>     "apiversion": "1.17.0",
>     "swupdate": {
>       "updatestate": 0,
>       "url": "",
>       "text": "",
>       "notify": false
>     },
>     "linkbutton": false,
>     "portalservices": false
>   }
> }

At least the manufacturername is now "Tasmota". 👍

**Comment by ebaauw** [comment]
That’s a breaking change on the Tasmota side.  They used to return an empty object, see https://github.com/ebaauw/homebridge-hue/issues/512.

**Comment by suhajda3** [comment]
I increased the `timeout` but homebridge-hue still prevents Homebridge from starting.

I believe the root cause of this issue when Tasmota compressed more strings with UnishoxStrings: https://github.com/arendst/Tasmota/commit/0ed519184bb1c6afd050e0789bfe7a8e8cf2a7e9

It looks like resourcelinks is still supported but somehow it causes an error.

**Comment by ebaauw** [comment]
Best open an issue with Tasmota, then.

**Comment by suhajda3** [comment]
The last version of Tasmota to support resourcelinks is [9.2.0](https://github.com/arendst/Tasmota/releases/tag/v9.2.0).
OTA update: http://ota.tasmota.com/tasmota/release-9.2.0/tasmota.bin

They have no plans to fix [this issue](https://github.com/arendst/Tasmota/pull/10405) so it's advised to stick with Tasmota 9.2.0.
