### ISSUE TITLE
Hue Hub - Link Every Restart

### ISSUE THREAD

**Issue by patrickoleary1977** [ebaauw/homebridge-hue#1053]
The plugin works great.  However, every time I restart Homebridge I have to relink the Hue hub by pressing the button.  Otherwise, its exactly what I need.  Thoughts?

**Comment by patrickoleary1977** [comment]
PEBCAK
Problem exists between chair and keyboard.

**Comment by ItsaBastI** [comment]
I have the same issue - probably also PEBCAK, but I don't see what I am doing wrong. How did you fix it?

**Comment by ItsaBastI** [comment]
Ok, I fixed it, too. Here's how:
After you linked Hue Hub to DeCONZ (after you "pushed" the button in the Phoscon UI) there will be a line like this in the log:

[deCONZ] Phoscon-Gateway: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "00000000000000": "99999999999"
      }
    }
  ]

You may have to scroll up through the log to find this line - this was my fault, I didn't scroll up far enough.

copy "users" and the data, don't forget the "," after "Hue"

find "Plattform": "Hue" in the configuration, add the colon and paste the data.

Save. Restart.
