### ISSUE TITLE
Can’t update to v0.13.30

### ISSUE THREAD

**Issue by mareeekkkk** [ebaauw/homebridge-hue#1055]
Updating the plug-in fails with the following error. I tried installing it directly via npm, this results in the same problem. 

Other plugins update/install fine. 

Running on RPi3+
NodeJS 16.13.1
NPM v8.1.2
Homebridge v1.3.8

![image](https://user-images.githubusercontent.com/52048049/144894658-bc957962-d64d-47a3-9b09-f2bb152cc1c3.png)

**Comment by ebaauw** [comment]
It’s an `npm` error, nothing to do with Homebridge Hue.  Never seen this particular error before, though.  Did you try and delete the offending directory?  Or try to delete Homebridge Hue, before upgrading it?
