### ISSUE TITLE
Hue Says Unreachable HomeKit Says All Good

### ISSUE THREAD

**Issue by patrickoleary1977** [ebaauw/homebridge-hue#1056]
I added some Innr outlets to Hue hub.  Works great.  Sometimes though, the Hue app will say unreachable, but HomeKit things all is good.  Is it possible for the plugin to read the status of the device in Hue as unreachable and then to set to Not Responding in HomeKit.  Otherwise, it gives a false sense of security in thinking the device is on or off.  Thanks.

**Comment by ebaauw** [comment]
Possible, though not advised, see https://github.com/ebaauw/homebridge-hue/wiki/No-Response.
