### ISSUE TITLE
Add dummy switch to Phoscon-GW 

### ISSUE THREAD

**Issue by WendelFelius** [ebaauw/homebridge-hue#1065]
Hi ebaauw,

I've connected my deconz gateway and in the home app there's now a accessory 'Phoscon-GW'. Can you maybe expose a dummy Stateless Programmable Switch service on this accessory so I can unfavourite it? Just like you did for homebridge-p1: https://github.com/ebaauw/homebridge-p1/releases/tag/v1.1.3

Thanks in advance,

Wendel

**Comment by ebaauw** [comment]
Already have; set `linkButton` to enable it.

**Comment by WendelFelius** [comment]
Amazing, thanks! Wasn't clear to me because the description only mentioned the hue link button. Thanks anyway!

**Comment by ebaauw** [comment]
Yeah, I changed that when Apple broke the favourite setting for unsupported accessories.
