### ISSUE TITLE
Original Hue devices getting exposed since last update

### ISSUE THREAD

**Issue by tornenen** [ebaauw/homebridge-hue#1066]
Since last Addon update, all devices are synchronised to homekit. 
Since i have activated "Don't expose lights already exposed by the v2 (square) Hue bridge." this shouldn't happen, right? 

Here are my Settings in Homebridge: 
![HB](https://user-images.githubusercontent.com/76594569/147633873-726b32cb-3ea2-4820-a1ac-815fc01f2205.jpg)

An here you can see my Home App. With all the native devices exposed. 

![Hassio](https://user-images.githubusercontent.com/76594569/147633925-d4290308-0701-4f43-801c-6e1c49724b0b.png)

Any ideas?

**Comment by ebaauw** [comment]
Please attach the debug dump file.  Please capture and attach a debug log file.

**Comment by tornenen** [comment]
Here are the Logs.
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/7788585/homebridge.log.gz)
[homebridge-hue (1).json.gz](https://github.com/ebaauw/homebridge-hue/files/7788586/homebridge-hue.1.json.gz)

**Comment by tornenen** [comment]
nvm.. this was my fault.
They are exposed through homeassistant.
Sorry
