### ISSUE TITLE
"Local Only"

### ISSUE THREAD

**Issue by Calorion** [ebaauw/homebridge-hue#1067]
I've noticed that the plugins has a "Local Only" option. What calls to the Internet does it make if this is off?

**Comment by ebaauw** [comment]
See the Wiki, with the description of that setting.

**Comment by Calorion** [comment]
I searched the Wiki before posting. I can't find any mention of this option. https://github.com/ebaauw/homebridge-hue/search?q=local+only&type=wikis

**Comment by ebaauw** [comment]
I don't know where you found the term "Local Only".  The setting is called `stealth`; you can find this in the _Settings_ dialogue in the Homebridge UI and in the Configuration page of the Wiki.

**Comment by Calorion** [comment]
In both HOOBS and Homemanager. ![image](https://user-images.githubusercontent.com/3050950/147861676-e8e57031-9252-49a4-85b5-11fa5813f5c7.png) ![image](https://user-images.githubusercontent.com/3050950/147861677-1e569e8b-5e0a-49e6-aaf5-f750041872bd.png)

**Comment by ebaauw** [comment]
I use nor support neither.
