### ISSUE TITLE
Single accessory for sensors

### ISSUE THREAD

**Issue by Calorion** [ebaauw/homebridge-hue#1068]
The [Wiki](https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started) says, "As of v0.3, homebridge-hue creates a single accessory combining these three services," referring to `Motion Sensor`, `Light Sensor`, and `Temperature Sensor`. However, that's not what happened for me; they're showing up as three separate sensors in Home+ and Eve.

**Comment by ebaauw** [comment]
Are you sure you’re looking at the accessory view in Eve?  You’re probably looking at the services.  Apple’s Home app uses the term “accessory” when referring to services as well as accessories, leading to lovely inconsistencies.  Home+ seems to have copied that behaviour.  The easiest check to see if tiles belong to the same accessory is moving one tile to another room.  The tiles for other services of the same accessory will automagically move with it.

**Comment by Calorion** [comment]
I see now. I mainly use Home+, and there's nowhere it shows them as one accessory. Thanks.
