### ISSUE TITLE
Hue plugin preventing Homebridge from starting

### ISSUE THREAD

**Issue by redjoto** [ebaauw/homebridge-hue#1073]
#### Issue

The Hue plugin is suddenly preventing Homebridge from starting. It was discovered tonight, when I tried to turn off the lights with the Hue dimmer switch (which I always use) and it didn’t react.
Seems like all the lights can be adjusted from the Eve app though, except for a Sunricher dimmer. All the lights can be adjusted from the Hue app, even the Sunricher dimmer. Is it possible that the Sunricher dimmer can prevent Homebridge from starting? It has worked fine for months.
#### Log Messages

```
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/7831851/homebridge-hue.json.gz)

![319C125A-D6D0-4A7D-AE78-461D92645790](https://user-images.githubusercontent.com/79904766/148620596-9cafe798-e4fc-49f6-a5fe-e4c8f79f6c9f.png)

**Comment by ebaauw** [comment]
The messages indicate that Homebridge Hue cannot find the Hue bridge.  By design, it delays Homebridge startup, so you won’t lose your accessories from HomeKit.

**Comment by redjoto** [comment]
Any idea why this is happening? Haven’t made any changes with the system at all.

**Comment by ebaauw** [comment]
No, I don’t know your environment.  ENOTFOUND means the system running Homebridge cannot resolve the configured name of the bridge, `philips-hue`, to an IP address.

**Comment by redjoto** [comment]
I identified the problem just after my last post. My Hue Bridge had changed its name by itself, from philips-hue to philips hue.
