### ISSUE TITLE
Expose devices as Fan service (with speed control)

### ISSUE THREAD

**Issue by mlaurijsse** [ebaauw/homebridge-hue#1077]
#### Feature request
First off all my compliments for this awesome plugin! Might I add a suggestion for further improvement (at least for my use case :)).

I use a 0-10v Zigbee dimmer to control my central mechanical ventilation system. I use deCONZ and this plug-in to expose the controller to homekit. Unfortunately, the controller shows up as Lightbulb service, which cases difficulty with e.g. Siri commands. I've tried using the `switch` resource link, but this disables the dimming (=speed control) functionality. 

Would it be possible to add another resource link category to expose 'dimmable' units as Fan service with speed control to Homekit?

I've wrote some homebridge plug-ins a couple of years ago. I would need to dive into the latest API. With some pointers, I am willing to have a go at it myself as well. However, since the project is in the middle of restructuring, I'd figured it be best to align first.

Please let me know your thoughts.

Kind regards,

Marcel

#### Device details

```
{
  "etag": "8e5dd8f1c77073ea9dd662e34db8edcb",
  "hascolor": false,
  "lastannounced": null,
  "lastseen": "2022-01-11T13:49Z",
  "manufacturername": "Philips",
  "modelid": "053",
  "name": "Ventilation",
  "state": {
    "alert": "none",
    "bri": 10,
    "on": true,
    "reachable": true
  },
  "swversion": "3.1.0",
  "type": "Dimmable light",
  "uniqueid": "cc:86:ec:ff:fe:0f:0a:5f-01"
}
```

**Comment by ebaauw** [comment]
Technically that’s relatively easy.  Not sure it makes sense still to do in Homebridge Hue.   I’m ditching resourcelinks in Homebridge deCONZ in favour of dynamic settings and can definitely include it there.
