### ISSUE TITLE
Eve temperature history missing for new Hue outdoor motion sensor

### ISSUE THREAD

**Issue by AndersKlinting** [ebaauw/homebridge-hue#1078]
Having aquired a second Hue Outdoor Motion Sensor and succesfully configured it in the Hue Bridge, I was surprised to see that displaying temperature in the Eve App (iPad) did not show history as was the case of my first motion sensor.

The only difference I find seems to be the model number.
The old sensor is model SML002, while the new is SML004.
The ID details from Eve:
<img width="518" alt="SML002" src="https://user-images.githubusercontent.com/30745841/149209499-0eb60329-2555-4bf1-8f30-e83b7d7894b0.png">
<img width="507" alt="SML004" src="https://user-images.githubusercontent.com/30745841/149209546-9220ba30-68d9-4ea7-b717-02c4697a0efd.png">

is there a problem with the new hardware and history?

**Comment by ebaauw** [comment]
I don't think I've seen an SML004 before.  Could you please attach the debug dump file, so I can see what it looks like from an API perspective?

I think the sensors are working alright, although you'd probably get some "unknown ... sensor" warnings, but because the model isn't recognised, Homebridge Hue doesn't expose the temperature as a separate accessory (which is needed for the temperature history next to the motion history).

**Comment by AndersKlinting** [comment]
Correct. I get warnings on the log

<img width="1024" alt="Hblog" src="https://user-images.githubusercontent.com/30745841/149244859-8c979b37-2002-40c8-99c0-1e7788cded80.png">

attached is the debug dump file
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/7858823/homebridge-hue.json.gz)

**Comment by PatrickB90** [comment]
There a indeed new indoor motion sensors around with model SML003
`[16/01/2022, 23:22:08] [Hue] Homebridge-GW: /sensors/16: warning: unknown ZHAPresence sensor {"config":{"alert":"none","battery":100,"delay":0,"ledindication":false,"on":true,"pending":[],"reachable":true,"sensitivity":2,"sensitivitymax":4,"usertest":false},"ep":2,"etag":"f843c478dd4347db29d2031d9b4b4713","lastannounced":null,"lastseen":"2022-01-16T22:20Z","manufacturername":"Philips","modelid":"SML003","name":"Bewegungsmelder","state":{"lastupdated":"2022-01-16T22:17:24.490","presence":true},"swversion":"2.53.6","type":"ZHAPresence","uniqueid":"00:17:88:01:0b:cd:19:b1-02-0406"}
[16/01/2022, 23:22:08] [Hue] Homebridge-GW: /sensors/18: warning: unknown ZHALightLevel sensor {"config":{"alert":"none","battery":100,"ledindication":false,"on":true,"pending":[],"reachable":true,"tholddark":12000,"tholdoffset":7000,"usertest":false},"ep":2,"etag":"cd984ebe9a61171a502dec2224d58576","lastannounced":null,"lastseen":"2022-01-16T22:20Z","manufacturername":"Philips","modelid":"SML003","name":"LightLevel 18","state":{"dark":true,"daylight":false,"lastupdated":"2022-01-16T22:20:24.850","lightlevel":3578,"lux":2},"swversion":"2.53.6","type":"ZHALightLevel","uniqueid":"00:17:88:01:0b:cd:19:b1-02-0400"}
[16/01/2022, 23:22:08] [Hue] Homebridge-GW: /sensors/17: warning: unknown ZHATemperature sensor {"config":{"alert":"none","battery":100,"ledindication":false,"offset":0,"on":true,"pending":[],"reachable":true,"usertest":false},"ep":2,"etag":"2eef4fc88ef782d49295c3c4cb86db88","lastannounced":null,"lastseen":"2022-01-16T22:20Z","manufacturername":"Philips","modelid":"SML003","name":"Temperature 17","state":{"lastupdated":"2022-01-16T22:20:33.416","temperature":2131},"swversion":"2.53.6","type":"ZHATemperature","uniqueid":"00:17:88:01:0b:cd:19:b1-02-0402"`

**Comment by ebaauw** [comment]
With a `sensitivitymax` of 4, upgraded from 2 for the SML001.

**Comment by PatrickB90** [comment]
As far as I can tell, they improved the sensor lens for higher sensitivity (which is causing the new sensitivitymax of 4) and now can detect motion up to an distance of seven meters, before it was "only" five meters: https://hueblog.com/2021/12/01/philips-hue-improves-its-motion-sensor-with-new-technology/

**Comment by ebaauw** [comment]
Thanks for the link.

Does it still have the `T` (Touchlink) button inside the battery compartment?  Never got that to work, though.

**Comment by Patr-ick** [comment]
Not sure, I am not using the new sensor. I've just forwarded the warning messages from someone else in here, since we have a discussing going on in our community. But if you need to know it, I could gather this information.
Fun fact: Another member mentioned, that he is using the SML003 Model for quit a while and doesn't get any warning messages in the Homebridge log.

**Comment by ebaauw** [comment]
Homebridge Hue won’t issue any warnings, unless it’s exposing the sensor.

**Comment by ebaauw** [comment]
In v0.13.35.

**Comment by AndersKlinting** [comment]
> In v0.13.35.

I have updated (including update of node.js and homebridge) and now both my models of outdoor motion sensors appear with separate temperature sensors.
<img width="704" alt="Tempsensors" src="https://user-images.githubusercontent.com/30745841/150685160-730a7098-cb3c-4c56-85d2-6069c34c7d2b.png">
And Eve offers display of temperature history of both… but now all history has gone for both, and it looks like no new history is stored either (where is that stored by the way?)

**Comment by Patr-ick** [comment]
Would delete the corresponding history file `history_MacAddress.json` of the sensor as described here: https://github.com/ebaauw/homebridge-hue/issues/957

**Comment by AndersKlinting** [comment]
> Would delete the corresponding history file `history_MacAddress.json` of the sensor as described here: #957

Thank you.
I have tried,  but did not get the result I hoped for.
After having deleted the files and restarted the service (and the server), new files are created for both sensors. However, no temperature history is created.
After a couple of hours the files look like this
<img width="1024" alt="History" src="https://user-images.githubusercontent.com/30745841/150696382-aac6a1a4-5e5c-4b91-ad32-4c1f947523dd.png">

and the new sensor shows history like this, i.e. Motion events are present but temperature is not. The same for the old sensor.
<img width="686" alt="Motionhistory" src="https://user-images.githubusercontent.com/30745841/150696485-f84363ef-1dbe-4554-b4a8-801094143555.png">

before I deleted the files, I noticed the old sensor had a second history file with suffix “_T” in the name (I suspect it was the temperature). After reboot no such files are created.

**Comment by redjoto** [comment]
I have the same problem with my indoor sensors. Suddenly no temperature history is to be found in the Eve app.

**Comment by ebaauw** [comment]
My bad.  Bloody cut & paste error. I must have looked over it a dozen times, at least.

Anyway fixed in v0.13.36.  I had to remove the `history_`_macaddress_`-T.json` files to get the temperature history back up, not sure why.  Better wait 20 minutes (or two new history entries) before concluding that it doesn't work and deleting the files.

Note that with `hueMotionTemperatureHistory` set, Homebridge Hue exposes two separate accessories, each with their own history (and history file).  Eve doesn't even know that these accessories are the same device.  
Without the setting, Homebridge Hue exposes a single accessory with history only for the motion.  This is a limitation of the `fakegato` repo, and will be solved in Homebridge deCONZ and Homebridge Hue2.  Because there is no temperature data in the history, Eve shows empty history for the temperature characteristic.  It actually does that for any characteristic that could have history, but doesn't have any history data.

**Comment by AndersKlinting** [comment]
> My bad. Bloody cut & paste error. I must have looked over it a dozen times, at least.

we have all been there :-)

It seems to work now. I had to remove my history files and restart.
And funny enough - Eve is still able to show old history (for my first motion sensor) that cannot be in the history file, so I guess it has some cache…

<img width="711" alt="Evehist" src="https://user-images.githubusercontent.com/30745841/151157768-a5e09724-d969-4fe8-943e-4ffa86d74a5e.png">

**Comment by ebaauw** [comment]
> Eve is still able to show old history (for my first motion sensor) that cannot be in the history file, so I guess it has some cache…

The Eve app stores the history on your Apple device.  I think this is for eternity, or until you uninstall the app.  This is stored under the accessory UUID, independently from HomeKit.  If you unpair an accessory from HomeKit, Eve will hang on to the history.  If you re-join the accessory to HomeKit, Eve will show the old history, even though HomeKit treats it as a new accessory.  This history is not synced between Apple devices.

An Eve accessory (real or faked by Homebridge) only maintains like four weeks of history.  You need to view the accessory in the Eve app on each of your Apple devices during that period, or you’ll have gaps in the history.  If you uninstall and re-install the Eve app, it will load the history from the accessory.
