### ISSUE TITLE
Filter / exclude devices

### ISSUE THREAD

**Issue by Matthijn** [ebaauw/homebridge-hue#1079]
I was wondering if it was possible to show only selected devices in homekit. I have a bunch of HUE lamps, and one zigbee lamp. I wanted to expose the zigbee lamp to homekit too.

So I intalled homebridge and homebridge-hue on a raspberry pi. And it works, but now both the hue bridge and homebridge expose the same hue lights to homekit, and they now all appear twice. 

Is it possble to only expose selected lights? In homebridge in the accessories tab, I can check "hide this accessory" but that only seems to hide it in the web interface and not in the home app. 
<img width="1579" alt="Screenshot 2022-01-11 at 20 21 01" src="https://user-images.githubusercontent.com/1755544/149362219-2178b50b-e524-467c-b8ff-406fedfb3409.png">

I found the configuration of hiding specific types of items, but I want to be able to hide some lights and not the others.

**Comment by ebaauw** [comment]
RTFM, https://github.com/ebaauw/homebridge-hue#configuration.
