### ISSUE TITLE
Dew point for temperatur sensors

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#1080]
Hello @ebaauw 

would it be possible to have the plugin calculate a dew point value from temperature and humidity for temperature sensors like Aqara and display the dew point value in homekit on the device?

I think it would be a great function to use the values of two sensors in an automation to detect the right time for air exchange / ventilation.

King Regards
Nastras

**Comment by ebaauw** [comment]
Happy to expose dew point for devices that report it, but Homebridge Hue won’t be calculating it.  That’s a feature for a home automation system, nothing to do with exposing devices to HomeKit.

**Comment by Nastras** [comment]
In principle, I agree with you. Unfortunately, it is not so easy to calculate this dew point reliably in Homekit. Shortcuts would be a possibility. But it is also quite unreliable.

Therefore, my idea was that you can calculate these two values Temp and humidity possibly from homebridge-hue.

Would be a great function but I can also understand your answer 😉

Thanks and have a nice weekend!
