### ISSUE TITLE
Identifying problem device

### ISSUE THREAD

**Issue by ghdbwise** [ebaauw/homebridge-hue#1082]
in log i find:

[17.1.2022, 13:02:56] [HUE Device] heartbeat 584011, drift 281

But i cannot identify which is the problem device or bridge.

**Comment by ebaauw** [comment]
That message has nothing to do with any bridge nor device.  It indicates the NodeJS triggered the heartbeat 281ms late.  If this happens occasionally, especially during Homebridge startup, you can ignore the message.  If you see these structurally, and with larger value, it might indicate a problem with overall system load, or another plugin blocking NodeJS (e.g by doing synchronous I/O).
