### ISSUE TITLE
Is it safe to test Homebridge 1.4.0 (beta 7 or newer)?

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#1083]
Hi @ebaauw 
I only want to ask if Version 0.13.34 of Homebridge-Hue is safe for testing Homebridge 1.4.0 b7 or newer. 

I read your comments about better response / faster updates when you are using Apple Home in combination with the new Avahi advertiser and I want to give it a try if possible. 

Thanks!

**Comment by ebaauw** [comment]
Still running beta 4 in my production environment, and beta 7 only in a test environment.  No issues on either, though.

You can always set `advertiser` to `bonjour` or `ciao`, if `avahi` doesn't work (in which case HomeKit won't be able to find Homebridge).  Note that the new advertiser only works on systems with Avahi, like Raspberry Pi OS.

**Comment by jostrasser** [comment]
Great, thanks @ebaauw !

I am running Homebridge on an RPi 4b with the following OS version:

`pi@homebridge:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian`

I think it's the 32bit version.

Are there any additional packages what I have to install manually on my RPi via apt (eg. Avahi daemon or package) or is it enough to upgrade Homebridge to the beta?

**Comment by ebaauw** [comment]
I think the Avahi package is installed, even on the lite version, but I don't know if it's enabled by default.

**Comment by jostrasser** [comment]
Great, thank you.
If you mean the enablement in Homebridge: it should be enabled by default if it is installed and not selected a dedicated advertiser I think.

Notes from Homebridge 1.4.0 b7
"Rely on hap-nodejs to select a default for the advertiser":
> This PR removes the logic in homebridge to use a default advertiser. Instead it fully relies on hap-nodejs to select a default if no advertiser is supplied.
> Avahi advertiser will be automatically used on supported platforms.

I will give it a try, thanks! :)
