### ISSUE TITLE
Too much logs for Outlet Voltage

### ISSUE THREAD

**Issue by Dominik-1980** [ebaauw/homebridge-hue#1084]
Hello.

My Zigbee Outlets show every change of Voltage, for example from 231V to 230V or 232V which is normal fluctuation.

Is there any way to suppress those loggings if the change of voltage is so small. 

Perhaps show message every 10V instead of every 1V?

My homebridge log is full with those.

**Comment by ebaauw** [comment]
Change the attribute reporting configuration in deCONZ.

**Comment by Dominik-1980** [comment]
How can I change this.
I found nothing like this in deconz...

And can I only turn off all reporting or just report changes above 10V?

**Comment by Dominik-1980** [comment]
Hmmm, it doesn't save the change.
If I click write, wait some seconds and click read it stays at 10.
But after a minute it sets back to 1.

**Comment by ebaauw** [comment]
I’m sorry, that’s an issue for deCONZ.  I will be offering a dynamic log level per accessory in Homebridge deCONZ (and Homebridge Hue2), but there’s nothing I can do I here.

**Comment by Dominik-1980** [comment]
Okay. Thank you Erik. You're doing a great job!

I will ask in the deconz forum.

Will deconz and hue be split into 2 plugins?
Can I delete hue and use deconz and hue2 instead, when it's out?

**Comment by ebaauw** [comment]
Yes, unless you still have a gen-1 (round) Hue bridge.  For details, see: https://github.com/ebaauw/homebridge-hue/issues/1070.
