### ISSUE TITLE
This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN"

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#1086]
#### Issue

Since the update to Homebridge 1.4.0 I get this message displayed in Log. I have not been able to detect any negative effects so far.

#### Log Messages
This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN"

#### Debug Files
![651AC624-CEDD-4710-B437-300694477414](https://user-images.githubusercontent.com/27686185/150624198-a7fe2092-73b1-4f86-9e94-21186f435b27.jpeg)

**Comment by ebaauw** [comment]
That’s usually an issue with the history, as _Last Activation_ is computed using the history timestamp.  I don’t think it’s related to Homebridge v1.4.0.

Best stop Homebridge, delete the history file for this sensor, and restart Homebridge.

**Comment by Nastras** [comment]
You were right 💪. I deleted the file and now the error is gone.
Thanks for the help again! Have a nice weekend!
