### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by PointingP** [ebaauw/homebridge-hue#1088]
#### Issue

I did a normal update of homebridge-hue today and apparently it failed. Also tried to roll back to old version and uninstall, but pretty much get the same error. (Command failed due to directory not empty)

Log says to rename '/usr/local/lib/node_modules/homebridge-hue' -> '/usr/local/lib/node_modules/.homebridge-hue-34H5WCcU'

How do i do this from homebridge? I'm a long time user, but my skill level is very low unfortunately.

#### Log Messages

```
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-hue@0.13.36

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-hue
npm ERR! dest /usr/local/lib/node_modules/.homebridge-hue-34H5WCcU
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-hue' -> '/usr/local/lib/node_modules/.homebridge-hue-34H5WCcU'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-24T14_53_04_585Z-debug.log

Command failed. Please review log for details.```

#### Debug Files
<!-- Please attach homebridge-hue.json.gz, see https://github.com/ebaauw/homebridge-hue#debug-dump-file -->

<!-- Please attach homebridge.log.gz here, see https://github.com/ebaauw/homebridge-hue#debug-log-file -->

**Comment by Damianod27** [comment]
I join the topic. I have the same problem. Any ideas ? Solutions ? Best Regards

**Comment by Damianod27** [comment]
How did you solve this problem?

**Comment by PointingP** [comment]
#1072 

@Damianod27 Check that issue for the solution. Hope it helps.
