### ISSUE TITLE
Lamps are changing back to Adaptive Light color after setting a scene that is exposed as switch

### ISSUE THREAD

**Issue by Hubsi3** [ebaauw/homebridge-hue#1090]
#### Issue
Hi, first of all thanks a lot for your great work!

I have one issue/question: As long as adaptive Light is enabled for some lamps in a room and I'm setting a new scene that is exposed as a switch, the lights change to that scene, but then directly changing back to the Adaptive light color. Is there any chance in disabling Adaptive light before setting the scene via switch in HomeKit. Because for now using Adaptive light is completely useless for me, as I can't set scenes by voice afterwards, as they are changing back... I hope it is understandable.

**Comment by ebaauw** [comment]
Adaptive lighting should be disabled automatically when you change the colour.  As per the specs, it should also be disabled when manually setting the colour temperature, but Homebridge Hue doesn’t honour that.  I had a hard time distinguishing that from adaptive lighting changing the colour temperature.  I think I managed to correct that in Homebridge deCONZ

**Comment by Hubsi3** [comment]
Ok, so I’m using a Hue Bridge. Will this also work in Homebridge Huev2?

**Comment by ebaauw** [comment]
Yes, I'll use the same logic for Homebridge Hue 2.

Did you enable adaptive lighting on a group accessory?  I could probably disable that rather easily.  If you mean disable adaptive lighting on each of the accessories corresponding to lights in that group: that won't be doable.

**Comment by Hubsi3** [comment]
Ok, sounds great!

Yes, I activated it on a group accessory. 

For instance my room: „Arbeitszimmer“ is exposed as a group as I set groups: true and rooms: true in config. If I now set my group „Arbeitszimmer“ to adaptive light and after that recall a scene, that is exposed under this group accessory as a switch, the scene sets just fine, but it gets overwritten by the adaptive light color after some seconds again.

I have one other little question at this point: The scenes that are exposed as switch (under a group accessory) don’t count to the 150 accessory’s limit, right? So I can expose all my 200 hue scenes without hitting any HomeKit limit this way?

**Comment by ebaauw** [comment]
Each scene is exposed as additional service on the group accessory.  There is a limit of 100 services per accessory, so with the _Accessory Information_ and _Lightbulb_ services, there’s only room for 98 scenes per group.

**Comment by Hubsi3** [comment]
Ok, that’s far enough for me. My maximum is 36 scenes in one room 👍

**Comment by ebaauw** [comment]
In v0.13.38.

**Comment by Hubsi3** [comment]
Wow, thank you! Will test it later :)

**Comment by Hubsi3** [comment]
Perfectly working!
