### ISSUE TITLE
Is it possible to exclude sensors based on their IDs?

### ISSUE THREAD

**Issue by maisun** [ebaauw/homebridge-hue#1095]
Hi,

First thanks for the great homebridge plugin!
I have enabled the plugin and immediately noticed it creates many sensors (most of them are not supported by Home app), and I'm only interested in a couple of them (for controlling Hue Lab scenes for example), but couldn't find out how to hide them. In the configure I find the option "excludeSensorTypes", but it's not good enough because most of these sensors are in type "CLIPGenericStatus" and I only want to keep 2 of them. Below is an example:
`
   "103":{
      "state":{
         "status":0,
         "lastupdated":"2022-02-19T15:25:56"
      },
      "config":{
         "on":true,
         "reachable":true
      },
      "name":"dimming",
      "type":"CLIPGenericStatus",
      "modelid":"HUELABSENUM",
      "manufacturername":"Philips",
      "swversion":"1.0",
      "uniqueid":"2:1:572c-d8ac-4099-bd08",
      "recycle":true
   },
   "104":{
      "state":{
         "status":0,
         "lastupdated":"2021-09-25T08:17:04"
      },
      "config":{
         "on":true,
         "reachable":true
      },
      "name":"Start and stop",
      "type":"CLIPGenericStatus",
      "modelid":"HUELABSVTOGGLE",
      "manufacturername":"Philips",
      "swversion":"2.0",
      "uniqueid":"2:0:284d-961c-4545-be0f",
      "recycle":true
   }
`

I'd like to hide sensor 103 and keep sensor 104 (which is a switch controlling Hue Lab Colorloop), both are in type "CLIPGenericStatus".

Hope I can get some suggestion here, thank you in advance!

**Comment by ebaauw** [comment]
Use whitelist or blacklist resourcelinks, see Wiki.

**Comment by pjvds** [comment]
For the lazy few out here: https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links#whitelist-and-blacklist
