### ISSUE TITLE
Support for Tradfri driver

### ISSUE THREAD

**Issue by tooh** [ebaauw/homebridge-hue#1099]
Have a lot of Hue lights and accessories. Have now installed Tradfri driver for our wardrobe cabinet. Managed to pair driver to Hue gateway. Have no Tradfri gateway. I see the device as Dimmable light in Hue app.

I know there are restrictions.

I don't see the device in Home app.

Is this expected behaviour.

**Comment by ebaauw** [comment]
Did you set `lights` in config.json?  And did you restart Homebridge after pairing the driver to the Hue bridge?

**Comment by tooh** [comment]
Lights = true

Feel stupid, forgot to restart.

All is working now.

Thanks.
