### ISSUE TITLE
Original Hue Bridge support

### ISSUE THREAD

**Issue by TonyFeestneus** [ebaauw/homebridge-hue#11]
Is the original hue bridge supported?

**Comment by ebaauw** [comment]
I plugged in my old v1 bridge and homebridge-hue connected to it just fine and found the Daylight sensor.  I haven't tested it with any lights or other sensors, but the API is the same, so I don't expect any issues.
You might want to be careful with lowering the heartbeat interval, as the old bridge is less powerful than the v2 bridge.
