### ISSUE TITLE
Sorry - NUBE ? - and Likely Something Stupid I am Doing

### ISSUE THREAD

**Issue by bbhomekitguy** [ebaauw/homebridge-hue#1100]
#### Issue

I attempted to post on Discord, but can't get the server to populate the channels... so I reverted here... Any help is GREATLY appreciated. I recently had an issue where all my hue bulbs stopped showing as responsive in the Homekit App (I have a v2 Bridge and around 32 lights and 14 switches [friends of Hue Runless Wire]). So, I reset those, but something Hue did with the last update seems to have broken the homekit connection. So, I reset hue (3x) and rebuilt the ecosystem to no avail...

Since I use HOOBS for Meross, Ring and MyQ I thought it might be a good solution for my Hue issues, given that I can see and use the system within the Hue app natively.

However, try as I might and even after reading the troubleshooting, wiki and other issues, I can't get the Hue Bridge to show my lights. The only way I have gotten it to work is to pull Group 0 which then makes them all function as one light - not practical of course.

So.... I didn't want to waste an issue, but here it goes... how do I get the lights to show up?

#### Log Messages

```5/10/2022, 11:39:27 PMHue Bridge starting
5/10/2022, 11:39:31 PMHue BridgeERROR[31mThe plugin "homebridge-hue" requires a Homebridge version of ^1.4.0 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
5/10/2022, 11:39:35 PMHue BridgeLoaded plugin 'homebridge-hue'
5/10/2022, 11:39:35 PMHue BridgeLoading 1 platforms...
5/10/2022, 11:39:35 PMHue BridgeHuehomebridge-hue v0.13.39, node v14.19.2, homebridge v1.3.4
5/10/2022, 11:39:35 PMHue BridgeHueWARNINGwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
5/10/2022, 11:39:35 PMHue BridgeHuesearching bridges and gateways
5/10/2022, 11:39:40 PMHue BridgeHuePhilips hue: Signify Netherlands B.V. BSB002 bridge v1950207110, api v1.50.0
5/10/2022, 11:39:41 PMHue BridgeHuePhilips hue: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "ECB5FAFFFE82B9D6": "nqzB7qSFM4M9zt9GfcRDgsbitdsLcEkhtLIjK31a"
      }
    }
  ]
5/10/2022, 11:39:41 PMHue BridgeHuePhilips hue: 1 accessories
5/10/2022, 11:39:41 PMHue BridgeHuemasked debug info dumped to /var/lib/hoobs/huebridge/homebridge-hue.json.gz
5/10/2022, 11:39:41 PMHue BridgeHuePhilips hue: 2 services
5/10/2022, 11:39:41 PMHue BridgeBridge is running on port 51856.
5/10/2022, 11:39:41 PMHue BridgeHuePhilips hue: event stream connected to https://192.168.1.70/eventstream/clip/v2
5/10/2022, 11:40:21 PMHue BridgeHueWARNINGheartbeat 38, drift 778
5/10/2022, 11:40:22 PMHue BridgeHueWARNINGheartbeat 39, drift 993

{
    "platform": "Hue",
    "name": "Hue",
    "brightnessAdjustment": 100,
    "heartrate": 5,
    "lowBattery": 25,
    "timeout": 5,
    "waitTimePut": 50,
    "waitTimePutGroup": 1000,
    "waitTimeResend": 300,
    "waitTimeUpdate": 20,
    "lights": true,
    "noResponse": true,
    "nativeHomeKitLights": true,
    "group0": true,
    "wallSwitch": true,
    "resource": true,
    "rooms": true,
    "scenes": true,
    "scenesAsSwitch": true
}
```

**Comment by kaibae19** [comment]
I'm not 100% sure how HOOBS does it, but HOOBS is just a user friendly Homebridge box. What this error is indicating is that the version of the hue plugin on your HOOBS device is way newer than the Homebridge version running on HOOBS. See if there are pending updates for HOOBS and install those.

**Comment by bbhomekitguy** [comment]
kaibae19, thanks for the note. I am not sure how my version could be out of date. I am running 4.0.110 which it says is the latest fully supported version. The Hue plugin is 0.13.39. both of these say they are the latest versions and when I check for udpates they are all up to date. Any other ideas?

**Comment by bbhomekitguy** [comment]
Oh, and if it helps Node Version 14.19.2 and Homebridge Version 1.3.4 - again all of which say they are the latest versions. I am stumped!

**Comment by kaibae19** [comment]
Looks like HOOBS is not current: https://github.com/hoobs-org/HOOBS/releases shows current version as you indicated of 4.1, however, the hue plugin is newer and requires a newer homebridge build. Until HOOBS makes that available not sure how you'd address short of running a separate, newer, homebridge instance.

**Comment by bbhomekitguy** [comment]
Yea, I saw 4.1, but it is still technically beta at this point. So, the Hue Plugin is newer than even the 4.1 version of HOOBS? Just making sure I am understanding.

**Comment by bbhomekitguy** [comment]
If so, could I just use an older version of the Hue plugin? Like maybe 0.13.34?

**Comment by kaibae19** [comment]
Yes and likely

**Comment by ebaauw** [comment]
You need to set `nativeHomeKitLights` to false, to make Homebridge Hue expose lights that would already be exposed natively by the Hue bridge.
