### ISSUE TITLE
Upgrade to v0.13.41 breaks phoscon connection

### ISSUE THREAD

**Issue by mruepp** [ebaauw/homebridge-hue#1102]
#### Issue
I recently upgraded to v0.13.41. After upgrade certain plugs didn't work - see log.
I run a raspberry pi with phoscon raspbee.

The downgrade to v0.13.40 resolved the issue immediately.

#### Log Messages

```
raspbee: request 824: api error 202: resource, /lights/4/state, is not modifiable. Device is not reachable.
```

**Comment by ebaauw** [comment]
This is an error returned by deCONZ and should not be impacted by the Homebridge Hue version.  The problem would probably be “solved” if you’d just wait a little while for the plug to be reachable again.  Could be an issue with the power to the plug, or with the Zigbee signal.
