### ISSUE TITLE
couldn't run ph -H *.*.*.* outlet

### ISSUE THREAD

**Issue by pseudonym187** [ebaauw/homebridge-hue#1103]
i have reinstalled my homebridge. after trying to get the new deconz plugin to run i am back with home bridge hue what im using since I started with homebridge. 

now I’ve tried to set my osram plug from bulb to plug with ph -H *.*.*.* outlet

the request I get in terminal is -bash: ph: command not found

i have reinstalled the hue plugin but I doesn't work. with my old home bridge installation I got no problem with that. 
what I´m doing wrong?

**Comment by ebaauw** [comment]
That means that `ph` is not in your `$PATH`.

Could be an issue with your PATH, could be an issue with the way you install Homebridge Hue.  `npm` should create a symlink from `/usr/bin/ph` to `/usr/lib/node_modules/homebridge-hue/cli/ph.js`, but I'm not sure about new installations based on the `apt` package for Raspberry Pi, that no longer uses `npm`.

**Comment by pseudonym187** [comment]
Thanks for your fast reply. 
is there anything I can do?

**Comment by ebaauw** [comment]
Check whether there's a symlink for `ph` in `/usr/bin` (or `/usr/local/bin` on some systems like macOS);
Check the this directory is in your PATH;
Find out where Homebridge-Hue is installed and manually create the symlink.
Try `npx ph`, but I think that only works for in combination with `npm`.
