### ISSUE TITLE
Plugin Installation not possible (homebridge-config-ui-x)

### ISSUE THREAD

**Issue by cl4udiu5** [ebaauw/homebridge-hue#1105]
#### Issue
Setup a new homebridge (https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started).
All plugins I wanted, were successfully installed.
Plugin homebridge-hue not successful.
Also tried 0.13.39 -> same error

It's a Raspberry Pi Model B Rev 2.
Reinstalled Node.js from https://unofficial-builds.nodejs.org/download/release/v16.15.1/
Everything is working fine but homebridge-hue installation.

<img width="789" alt="Bildschirmfoto 2022-06-28 um 16 43 13" src="https://user-images.githubusercontent.com/74124378/176208404-8e3585b0-0b66-44bc-8f70-ad949ba95285.png">

**Comment by cl4udiu5** [comment]
Tried to find the debug file but couldn't find it. Could you please help me with that?

**Comment by ebaauw** [comment]
The path is listed on screen.  If it’s no longer there, I’d give it another try and look at it immediately after.

**Comment by cl4udiu5** [comment]
Tried something new...

Flashed SD card again and installed homebridge manually.
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

After that installed Node.js again because I need arm6 compatible version. 
wget https://unofficial-builds.nodejs.org/download/release/v16.15.1/node-v16.15.1-linux-armv6l.tar.gz
tar xf node-v16.15.1-linux-armv6l.tar.gz
sudo cp -R node-v16.15.1-linux-armv6l/* /usr/local

Restarted Pi, Homebridge started, everything is fine. Installed plugins with no issues (Harmony, Samsung Tizen,...). Tried to install homebridge-hue Plugin - same error

**Comment by ebaauw** [comment]
What does the `npm` log say?

**Comment by cl4udiu5** [comment]
Solved the problem by opening console in Homebridge UI and then installed the plugin with 

`hb-service add homebridge-hue`
