### ISSUE TITLE
Hue Bridge -  API version upgrade to 1.53.0

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#1112]
#### Issue
After updating / restart of my Homebridge I am getting the following warning. See logs (API version recommendation)

#### Log Messages

```
[30/09/2022, 21:35:06] [Homebridge-Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1953188020, api v1.53.0
[30/09/2022, 21:35:06] [Homebridge-Hue] Philips hue: warning: not using recommended Hue bridge api version 1.52.0
```

**Comment by ebaauw** [comment]
Hadn’t seen that before, but indeed, my Hue bridge has upgraded its firmware as well.  The bastards haven’t published any release notes for over two years, since 1.39.0, so I’ll have to check for any changes myself.  In the meantime, please report if you run into any issues.

**Comment by jostrasser** [comment]
I'll do. 
Thanks @ebaauw !

**Comment by jostrasser** [comment]
Hi, short feedback:
Alonso working fine and as expected with the newest firmware. 

Thanks JO

**Comment by ebaauw** [comment]
In v0.13.47.
