### ISSUE TITLE
Ikea Shortcut button double press

### ISSUE THREAD

**Issue by frogger11** [ebaauw/homebridge-hue#1114]
#### Issue
Hi I have a question regarding the Ikea Shortcut button. It seems that the latest firmware for button/ (Ikea hub) gives extra functionality with double press. Is this something that could be added to the Homebridge-Hue plugin?

More info
https://www.reddit.com/r/tradfri/comments/syg7hz/shortcut_button_double_press_now_available_on/

Thank you for this good plugin.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Is it supported by deCONZ already?  Do you know the issue and/or PR?

**Comment by frogger11** [comment]
> Is it supported by deCONZ already? Do you know the issue and/or PR?

That's a good question. I didn't think as far as that, but I'll look into it. So, if I understand you correctly, it seams that deCONZ currently has a limitation?

**Comment by ebaauw** [comment]
When I added support for the shortcut button to deCONZ, in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3975, it only sent Zigbee commands on press/release, on hold, and on release after hold.  deCONZ maps these to `buttonevent` value 1002 (which Homebridge Hue maps to _Single Press_) and to 1001/1003 (_Long Press_).

I expect (hope), the latest firmware of the button now causes it to send a Zigbee message on double press.  deCONZ would need to map this to 1004, so Homebridge Hue can map it to _Double Press_.

**Comment by frogger11** [comment]
I see. I figured out that I have HA installed and can listen to what the button sends with deconz_event. Below is what occurs when I double click with the latest firmware 2.3.080.
I have two shortcut buttons, and the other one has the older firmware that has the command you mentioned. This "2002" appears to have been added.

{
    "event_type": "deconz_event",
    "data": {
        "id": "tradfri_shortcut_button_2",
        "unique_id": "94:de:b8:fe:fe:0e:0f:91",
        "event": 2002,
        "device_id": "4ea68eb20b38a45d4597553e2d096fb9"
    },
    "origin": "LOCAL",
    "time_fired": "2022-10-02T16:29:08.889467+00:00",
    "context": {
        "id": "d5b87503f41aae92c992b9bb9a60351d",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by ebaauw** [comment]
That doesn’t make sense, as the device physically only has one button.  I suppose on double press,  it sends the command that the on/off button sends on press/release of the _Off_ button.  The shortcut button shares the button map with the on/off button.

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6383.

**Comment by ebaauw** [comment]
Now we just have to wait for deCONZ v2.19.

**Comment by frogger11** [comment]
That sounds promising. Looking forward to it.
Thanks.

**Comment by ebaauw** [comment]
Published v0.13.47.
