### ISSUE TITLE
Update - Plugin not working anymore

### ISSUE THREAD

**Issue by xnobelx** [ebaauw/homebridge-hue#1115]
Can't get the hue plugin to work after update. Log says:

[06/10/2022, 17:47:39] [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1953188020, api v1.53.0
[06/10/2022, 17:47:39] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.52.0
[06/10/2022, 17:47:39] [Sonos] listening on http://0.0.0.0:34069/notify
[06/10/2022, 17:47:40] [Hue] Philips hue: request 1: POST / {"devicetype":"homebridge-hue#homebridge"}
[06/10/2022, 17:47:40] [Hue] Philips hue: request 1: write EPROTO 1995577808:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

What can I do?

#### Log Messages

```
```

**Comment by ebaauw** [comment]
No clue, this seems to be an error with SSL.  Did you upgrade NodeJS as well?  Do you get the same error when running `ph -H x.x.x.x createuser` (filling in the IP address of your Hue bridge)?  If so, try uninstalling/reinstalling NodeJS.  If not: are you running any other plugins besides Homebridge Hue?  What happens if you run Homebridge Hue as only plugin?

**Comment by ebaauw** [comment]
I use the latest LTS version of NodeJS, 16.17.1.  The error seems to suggest that it has been compiled against the wrong version of SSL.  Not sure if that’s an issue of NodeJS, or with your system having a too old version of SSL.  16.16.0 did include an update of SSL, see https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md#2022-07-07-version-16160-gallium-lts-danielleadams.

**Comment by ebaauw** [comment]
Are you by change running Homebridge on an original Pi Zero (with ARM6 processor)?

**Comment by xnobelx** [comment]
No, I am running a pi 3+.Will try to fix it tomorrow. Maybe I will setup a ne Homebridge - this seems to be messed up…Thanks for your help!!!Am 07.10.2022 um 20:42 schrieb Erik Baauw ***@***.***>:﻿
Are you by change running Homebridge on an original Pi Zero (with ARM6 processor)?

**Comment by xnobelx** [comment]
Solved the issue! After installing the update via Config UI I entered the Bridge IP and port. This is not necessary and ended up in the error messages.
Thanks again for your support and keep up the good work!
