### ISSUE TITLE
iOS 16 - Missing scene names

### ISSUE THREAD

**Issue by sascharucks** [ebaauw/homebridge-hue#1122]
#### Issue
Starting with iOS 16 I lost the names from my Hue scenes in the Home app.
![IMG_4355](https://user-images.githubusercontent.com/670855/200828704-d454de55-766b-429e-ab30-d492a400a463.PNG)
Before I could see the names. Screenshot from old Mac Home app:
![Bildschirmfoto 2022-11-09 um 13 17 40](https://user-images.githubusercontent.com/670855/200828808-563f2c2c-6b0e-487a-b888-9153088a692b.jpg)

It is a bit inconvenient without the names to find the right scene. Could this be fixed? Thanks!
For reference the same view in Hue.
![IMG_4356](https://user-images.githubusercontent.com/670855/200828906-1d412e5e-b943-49be-be71-49166a04a610.PNG)

My settings (version homebridge-hue v0.13.47)
![Bildschirmfoto 2022-11-09 um 13 21 12](https://user-images.githubusercontent.com/670855/200829170-fda7adbe-37c4-4ff2-a946-92a197292da9.jpg)

**Comment by sascharucks** [comment]
Thanks for the feedback! Could you elaborate how to change/delete the service name? I couldn't find anything in the iOS Home app.

I also created a feedback ticket with Apple under FB11774172.

**Comment by ebaauw** [comment]
Open the tile for the accessory, scroll down to settings, select _Accessories_, to see a tile per service (!), select a tile, scroll down to settings, and change the name.

I find it easier to use Eve for this, where you have a single screen for all services under _Types & Names_ in the accessory settings.

**Comment by ebaauw** [comment]
I think I tackled it.  When `scenesAsSwitch` has been set, _Configured Name_ is added to the _Switch_ service, and Home shows the scene names.  Both when showing the accessory as a single tile as well as separate tiles.

**Comment by ebaauw** [comment]
In v0.13.49.

**Comment by sascharucks** [comment]
I just tested it. Works perfect. Thanks a lot!

**Comment by Mallepi** [comment]
Hello, I have to get on the subject. I think that the problem is related. 

For me, through homebridge-hue the hue scene name is displayed correctly in homekit. 
If I change the name of the scene switch in homekit homekit forgets this own name again after a certain time.
After that, the scene name from the Hue app is displayed again in homekit.

I could not find out why? Would be happy about help. Thank you!
