### ISSUE TITLE
Nach Update auf neueste Version Zigbee-Geräte nicht mehr verfügbar

### ISSUE THREAD

**Issue by samoht0403** [ebaauw/homebridge-hue#1123]
Hallo zusammen,

seit dem Update auf die neueste Version bekomme ich die Zigbee-Geräte nicht mehr in Home angezeigt und kann die Child-Bridge nicht starten.

System: 
Raspi 4B, 
bullseye, 
Plattform: linux,
RAM: 922.5 MB,
Node.js: v18.12.1,
NPM: v8.19.2

#### Log Messages
Vermutlich liegt der Fehler hierin: 

```
homebridge: error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: ac1eede6-319a-432b-a08d-b0559db22e27)
```

Auf der Plugin-Seite steht 
```
"Homebridge neu starten, um die Einrichtung dieser Unter-Bridge abzuschließen. 
Zu dieser Seite zurückkehren, nachdem Homebridge neu gestartet wurde, um den Kopplungs-QR-Code zu sehen." 
```
Nach dem Neustart der Bridge bleibt das allerdings unverändert.

Versucht habe ich bereits das Unterverzeichnis  
```
~/.homebridge/accessories
```
zu löschen, erfolglos.

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/9997677/homebridge-hue.json.gz)

Ich hoffe, ich habe nicht zu viele Infos vergessen, das mit der debug-FIle hat nicht funktioniert. Vielleicht brauche ich sie ja nicht :-(

Danke vorab!

**Comment by ebaauw** [comment]
The debug file is very helpful, thanks.

Looks like you reset a couple of lights and paired them to the other bridge/gateway, without deleting them.  This causes Homebridge Hue to try and expose the same light twice, causing the duplicate UUID error.

Homebridge Hue still uses the old static platform accessory model, so there's no cached accessories.

**Comment by samoht0403** [comment]
Thank you @ebaauw, deleted the device and it's working again.
