### ISSUE TITLE
Hide native Hue Tap Switch?

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#1124]
Hey,

I am using some Hue Tab Switches as wall mount added to the HUE bridge.
All of them are exposed twice.

Once native via HUE and once via the plugin I think.
Is there a way to hide those exposed from HUE native?
Because I want to use them from the plugin because in that way I have 6 actions instead of 4.

Will the behaviour be the same when adding them in DECONZ/Conbee?

Thanks.

**Comment by ebaauw** [comment]
The native HomeKit feature of the Hue bridge is all or nothing.  You can only “hide” them by removing the Hue bridge from HomeKit. Hue tab works just as well with deCONZ, see https://github.com/ebaauw/homebridge-hue/wiki/Features.

**Comment by Phoenix-DH** [comment]
Thanks.
When I got you right, when adding the Hue Tab Switch to Deconz I will only have it once.
I just ordered some new ones, I will try it.

Thank you.

Because now I have created one room called "BLACKLISTED" :)
