### ISSUE TITLE
Bridge doesn't start after Update

### ISSUE THREAD

**Issue by MasterofKungfu9999** [ebaauw/homebridge-hue#1125]
#### Issue
After Updating i get the log messages and no light is found and the bridge isn't starting

#### Log Messages
6.12.2022, 17:24:54HOOBSHuePhoscon-GW: /resourcelinks/5: /lights/3: not available
6.12.2022, 17:24:54HOOBSHuePhoscon-GW: gateway not yet initialised - wait 1 minute

**Comment by MasterofKungfu9999** [comment]
Yes, i deleted a power switch at deconz. 
How can i do in deconz. I only have the frontend installed

**Comment by ebaauw** [comment]
What port is deCONZ running on?  Did you try this immediately after starting deCONZ or some time after?

**Comment by ebaauw** [comment]
What’s the output of `ph -DD config`?

**Comment by MasterofKungfu9999** [comment]
ph: localhost: request 1: GET /config
ph: localhost: request 1: GET http://localhost/api/config
ph: localhost: request 1: response: {"api":{"orgin":"*","polling_seconds":5,"inactive_logoff":30,"disable_auth":false},"theme":"light"}
ph: localhost: request 1: 200 OK
ph: localhost: request 1: GET /config
ph: warning: localhost: request 1: invalid response
ph: error: localhost: not a Hue bridge nor deCONZ gateway

**Comment by MasterofKungfu9999** [comment]
But i haven't changed standard port. how can i find the port?

**Comment by MasterofKungfu9999** [comment]
The port is 8080
