### ISSUE TITLE
Exclude the Hue Bridge .. I would like to use only RaspBee II .. 

### ISSUE THREAD

**Issue by The-Paw** [ebaauw/homebridge-hue#1128]
Sorry for the "simple" question. But how can I use it only with my deCONZ RapsBee II ?? When I delete the HueBridge User, the PlugIn asked to connect to hue every time :-((

TheHue: press link button on the bridge to create a user - retrying in 15s .. I'll "remove" this.

**Comment by ebaauw** [comment]
Set `hosts` in config.json to disable discovery and specify only the deCONZ hostname/port.

**Comment by The-Paw** [comment]
This is my config, yet ..

        {
            "platform": "Hue",
            "name": "Hue",
            "brightnessAdjustment": 100,
            "heartrate": 5,
            "lowBattery": 25,
            "timeout": 5,
            "waitTimePut": 50,
            "waitTimePutGroup": 1000,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20,
            "users": {
                "001788FFFE220AB6": "...",
                "00212EFFFF0A5728": "..."
            },
            "sensors": true
        }

**Comment by The-Paw** [comment]
This doesn't work:

        {
            "platform": "Hue",
            "name": "Hue",
            "hosts": ["192.168.178.106"],
            "brightnessAdjustment": 100,
            "heartrate": 5,
            "lowBattery": 25,
            "timeout": 5,
            "waitTimePut": 50,
            "waitTimePutGroup": 1000,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20,
            "users": {
                "001788FFFE220AB6": "...",
                "00212EFFFF0A5728": "..."
            },
            "sensors": true
        }

With Port :443 .. doesn't work, too :-((

**Comment by The-Paw** [comment]
21.12.2022, 20:29:29HOOBS starting
21.12.2022, 20:29:39HOOBSLoaded plugin 'homebridge-broadlink-rm-pro'
21.12.2022, 20:29:39HOOBSLoaded plugin 'homebridge-eveatmo'
21.12.2022, 20:29:40HOOBSLoaded plugin 'homebridge-hue'
21.12.2022, 20:29:40HOOBSLoaded plugin 'homebridge-midea-air'
21.12.2022, 20:29:41HOOBSLoaded plugin 'homebridge-xiaomi-fan'
21.12.2022, 20:29:41HOOBSLoading 5 platforms...
21.12.2022, 20:29:41HOOBSeveatmo platformLoading new data from API for: weatherstation
21.12.2022, 20:29:41HOOBSBroadlink[INFO] Automatically discovering Broadlink RM devices.
21.12.2022, 20:29:41HOOBSBroadlink[INFO] Running Bridge Broadlink RM Plugin version 4.4.11
21.12.2022, 20:29:41HOOBSBroadlinkSomplex Accessory Ready
21.12.2022, 20:29:41HOOBSBroadlinkTV Accessory Ready
21.12.2022, 20:29:41HOOBSBroadlinkSoundbar Accessory Ready
21.12.2022, 20:29:41HOOBSHuehomebridge-hue v0.13.42, node v16.18.1, homebridge v1.5.0
21.12.2022, 20:29:41HOOBSHueWARNUNGwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
21.12.2022, 20:29:41HOOBSHuesearching bridges and gateways
21.12.2022, 20:29:41HOOBSmidea-airLoading accessory from cache: AirCon_5204
21.12.2022, 20:29:41HOOBSmidea-airLoading accessory from cache: Living Room
21.12.2022, 20:29:41HOOBSxiaomifanInit - initializing devices
21.12.2022, 20:29:41HOOBSxiaomifan[Ventilator] Init - got fan configuration, initializing device with name: Ventilator
21.12.2022, 20:29:42HOOBSBroadlink[INFO] Discovered Broadlink RM4 Mini (5216) at 192.168.178.105 (ec:0b:ae:9e:e4:69)
21.12.2022, 20:29:42HOOBSHuemeethue: request 1: GET /
21.12.2022, 20:29:42HOOBSHueWARNUNGmeethue: request 1: http status 429 Too Many Requests
21.12.2022, 20:29:42HOOBSHuemeethue: request 1: GET /
21.12.2022, 20:29:42HOOBSHueWARNUNGmeethue: request 1: http status 429 Too Many Requests
21.12.2022, 20:29:43HOOBSmidea-airCreated device: AirCon_5204, with ID: ***, and type: 172
21.12.2022, 20:29:43HOOBSmidea-airCreated device: Living Room, with ID: ***, and type: 161
21.12.2022, 20:29:46HOOBSHueTheHue: Signify Netherlands B.V. BSB002 bridge v1955082050, api v1.55.0
21.12.2022, 20:29:46HOOBSHueWARNUNGTheHue: warning: not using recommended Hue bridge api version 1.52.0
21.12.2022, 20:29:46HOOBSHuePhoscon: dresden elektronik deCONZ gateway v2.19.3, api v1.16.0
21.12.2022, 20:29:46HOOBSHueWARNUNGPhoscon: warning: support for deCONZ will be deprecated in favour of Bridge deCONZ
21.12.2022, 20:29:46HOOBSHueWARNUNGPhoscon: warning: not using recommended deCONZ gateway version 2.17.1
21.12.2022, 20:29:46HOOBSHuePhoscon: 3 accessories
21.12.2022, 20:29:46HOOBSHuePhoscon: websocket connected to ws://192.168.178.106:443
21.12.2022, 20:29:47HOOBSHueTheHue: 21 accessories
21.12.2022, 20:29:47HOOBSHuemasked debug info dumped to /var/lib/hoobs/hoobs/homebridge-hue.json.gz
21.12.2022, 20:29:47HOOBSHueTheHue: 2 services
21.12.2022, 20:29:47HOOBSHuePhoscon: 2 services
21.12.2022, 20:29:47HOOBSBridge is running on port 51826.
21.12.2022, 20:29:47HOOBSHueTheHue: event stream connected to https://192.168.178.48/eventstream/clip/v2
21.12.2022, 20:29:52HOOBSHuenpm registry: request 1: GET /homebridge-hue/latest
21.12.2022, 20:29:52HOOBSHueWARNUNGnpm registry: request 1: timeout after 5 seconds

**Comment by The-Paw** [comment]
Wrong Port .. 1881 in hoobs. Is working now ;)
