### ISSUE TITLE
Homebridge-hue plugin no bridges or gateways found.

### ISSUE THREAD

**Issue by Jaysson47** [ebaauw/homebridge-hue#1129]
Hi I'm new to home Bridge and having some issues getting homebridge-Hue plugin running. I downloaded homebridge and spun up HyperV and was able to install homebridge. I installed homebridge hue according to the WIn 10 HyperV instructuctions, added the platform in the json config file. I rebooted and received "searching Bridges and gateways", meethue : request 1: GET /, meethue: request 1: HTTP status 429 Too many requests. Im sure the bridge/gateway isn't getting an ip. 

Thanks in advance.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
>  Im sure the bridge/gateway isn't getting an ip.

Do you have a Hue bridge or deCONZ gateway?  Can you access these through the Hue app or Phoscon?  If these don’t get an IP address, there’s an issue with your network setup, nothing do to with Homebridge or Homebridge Hue.

> meethue : request 1: GET /, meethue: request 1: HTTP status 429 Too many requests.

The Meethue portal, used to discover Hue bridges, thinks it’s being spammed and won’t accept the query.  Haven’t seen that before, maybe your ISP is sharing “your” public IP address with others?

Normally, the bridge or gateway should also be discovered through UPnP.  Alternatively, you can bypass discovery by setting `hosts` in config.json, but then you better have a static IP address for your bridge or gateway.

> spun up HyperV

Are you sure you setup the VM correctly?  It needs to be on the same subnet as your bridge/gateway for UPnP to work.  Did you try and pair Homebridge to HomeKit already?  It also needs to be on the same subnet as your iPhone or other Apple devices used with HomeKit.

**Comment by Jaysson47** [comment]
Thanks again, you responded in discord also. I will just respond to this thread. 
1. I’m using the hue bridge plugin in homebridge. 

2. Is there syntax to bypass the host discovery? I will set the gateway to a open address. 

3. VM is on the same subnet and I have homebridge connected to HomeKit. 

I hope that answers your questions. 

Here’s my config file. 
{
    "bridge": {
        "name": "Homebridge 19D2",
        "username": "0E:B6:A6:5D:19:D2",
        "port": xxxx,
        "pin": "xxxxxx",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "groups": false,
            "heartrate": 5,
            "hosts": [
                "192.168.1.1"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "rules": false,
            "schedules": false,
            "sensors": false,
            "timeout": 5,
            "users": {
                "bridgeid": "username"
            },
            "platform": "Hue"
        }
    ]
}

**Comment by ebaauw** [comment]
> "hosts": [
"192.168.1.1"
],

What device is at `192.168.1.1`?   It should be the IP address of your Hue bridge or deCONZ gateway.  Typically, the `.1` address is used by your router. 

> Is there syntax to bypass the host discovery?

Yes, specify `hosts`.
