### ISSUE TITLE
Osram lights

### ISSUE THREAD

**Issue by deba2908** [ebaauw/homebridge-hue#113]
Hi, I get following error when starting my homebridge

Philips hue: /lights/7: warning: unknown light model {"state":{"on":false,"bri":254,"hue":0,"sat":0,"effect":"none","xy":[0.3805,0.3769],"ct":370,"alert":"select","colormode":"ct","reachable":true},"type":"Extended color light","name":"Extended color light 3","modelid":"Classic A60 RGBW","manufacturername":"OSRAM","uniqueid":"84:18:26:00:00:01:01:2b-03","swversion":"V1.03.07"}

**Comment by ebaauw** [comment]
Thanks.  I'll add it to the list of known lights.

Do you know what range of colours and what range of colour temperatures it supports?

Note that it's just a warning - homebridge-hue probably just works with this light model.  However when you set a colour or colour temperature that's not supported by the light, it might take a while before HomeKit reflects the actual values.

**Comment by ebaauw** [comment]
I notice it's on firmware v1.03.07.  Some of the other OSRAM lights on that firmware version have a bug that they won't turn off, unless you explicitly specify a transitiontime of 0 (instead of the 400ms default).  Is your light having the same issue?

**Comment by deba2908** [comment]
So the color range is only white. 
I have three of those lights and for one of the I'm facing the issue.

**Comment by ebaauw** [comment]
> So the color range is only white.

That's odd, it seems to support colour.  What app are you using?  
I've written a `bash` script that discovers the range of `ct` and `xy` values supported by a light.  Would you be able to download [`ph.sh`](https://github.com/ebaauw/ph.sh), run it, and post the output of `ph_light_values 7`?

> I have three of those lights and for one of the I'm facing the issue.

What are their `swversion` values and which one has the issue?  homebridge-hue should issue an unsupported light warning for each of them.  If you have an OSRAM gateway, you can update the light firmware.  homebridge-hue will work around the issue, but native Hue apps won't benefit from that.
