### ISSUE TITLE
Accessory non compliant

### ISSUE THREAD

**Issue by alexhall1986** [ebaauw/homebridge-hue#1136]
#### Issue

After adding a second Gen 2 Hue bridge to my Homebridge Hue plugin, whenever I try to add the Hue child bridge to HomeKit I get a non compliant accessory message. it seems to be happening since the second bridge was added.

See config below:

{
    "name": "Hue",
    "anyOn": true,
    "effects": false,
    "excludeSensorTypes": [
        "CLIPGenericFlag",
        "CLIPGenericStatus",
        "CLIP"
    ],
    "hosts": [
        "192.168.1.165",
        "192.168.1.230"
    ],
    "lights": true,
    "nativeHomeKitLights": false,
    "nativeHomeKitSensors": false,
    "noResponse": true,
    "resource": true,
    "users": {
        "001788FFFE7FA123": "3w6WdbUGEpwQhIoUzxi1UgZc2JEmaW1MaY-hTIlp",
        "ECB5FAFFFE972FEF": "ORLj-WOIFu-Q76YgpOkgIKALQi8IyvkXk7AEJDnP"
    },
    "sensors": true,
    "platform": "Hue",
    "_bridge": {
        "username": "0E:2F:27:0C:2A:6A",
        "port": 58517
    }
}

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Please attach:
- A screenshot of the error;
- The debug dump file;
- A debug log file, capturing the startup of Homebridge.

See the FAQ on how to obtain the log files.

**Comment by alexhall1986** [comment]
[](url)
![IMG_2502](https://user-images.githubusercontent.com/122186472/211196743-035ab45f-9c10-471c-943c-4586b955cbb8.jpeg)
[homebridge.log.txt](https://github.com/ebaauw/homebridge-hue/files/10368430/homebridge.log.txt)

**Comment by ebaauw** [comment]
I really need to see the log file when running Homebridge in DEBUG mode.  Please also attach the dump file.

Not sure if that's the cause, but the built-in Daylight sensor hasn't been configured.  The Hue app used to do that automatically, based on your current location, but apparently it no longer does that.

**Comment by alexhall1986** [comment]
Ok that should have been in debug mode- let me check again and do a reboot.

Basically if I remove the second bridge everything works perfectly. The minute I add the second bridge when already paired everything stops responding in HomeKit, regardless of reboots etc.

If I try pairing with HomeKit with both bridges added it comes up with the compliance error.

so essentially it’s the second bridge being present that’s causing the issue- but no idea why!

everything works okay within Homebridge on the web UI though…

**Comment by ebaauw** [comment]
It sounds like one of the devices on the second bridge is exposed illegally, causing HomeKit to kick out the entire bridge.  We need to figure out which, and what’s the offending bit.  I hope by comparing the devices on the two bridges we can nail it down.  Otherwise we need to add the devices one by one to see when it breaks.

Typically it’s some weird value like an empty string for `swversion` or underscores in the manufacturer or model name.  Or a missing attribute causing Homebridge Hue to expose an incomplete service.

Did you move any of the devices to the new bridge, or are these all new devices?

**Comment by alexhall1986** [comment]
I only moved devices over from the 1st bridge that’s been working fine. The only exception were a couple of new smart buttons I added.

see attached screen shot.

The 3rd party devices that have the underscores were working fine on the solo bridge config..
![95C4F7D5-889F-42E6-B26A-C1A9974D014F](https://user-images.githubusercontent.com/122186472/211217618-6ba32baa-9ec8-4174-b596-2d453a431f0e.jpeg)

**Comment by alexhall1986** [comment]
Okay so found the issue- a rouge osram light was still on the first bridge and added to second bridge- thus presenting a duplicate device across two bridges. Removed that and a smart button which was the same and everything sprung back…

thank you for you assistance
