### ISSUE TITLE
Hue light switch and iOS 10.3 on ATV3

### ISSUE THREAD

**Issue by sejoki** [ebaauw/homebridge-hue#114]
When I upgraded to 10.3, something went wrong with my home kit configuration because I thought I'd use my old iPhone 5 as a control device, which was running 10.3 beta at the time. Anyways, I reconfigured everything and while I was at it, tried to add my hue dimmable switches to home kit. Every time I tried to add an action to the button, I got the error message that the automation could not be added.
I gave up on it quickly and kept them in my hue app, since they are working independently from home kit as well.

Now it was bugging me, because every change I make to a scene in home kit, I also have to adapt in the hue app. I reset my home bridge and created a new home, but I still get the same error message.

It's not so much an issue I have with the hue plugin, so a little off topic, but I thought I'd ask here since you really seem to know about changes in home kit.

I use my old Apple TV 3 for automation, since according to Apple, the only downside is that it doesn't support home kit cameras, which I don't have anyways. However, before 10.3, I was able to configure programmable switches (which were't even supported) just fine with this setup.

Now, after reconfiguring everything, it dawned on me that while adding programmable switches to home kit, Apple further limited support for the ATV3. Is there anything documentation wise that confirms this? Or anyone else with this issue?

**Comment by ebaauw** [comment]
In the __Prerequisites__ there's a link to the [Apple support page](https://support.apple.com/en-us/HT207057) for the Home Hub.  From that page:

> If you have an Apple TV (3rd generation)*, you can control your HomeKit accessories in the Home app while you’re away from your home. To change user permissions, create automations, or stream HomeKit-enabled cameras remotely, you need an Apple TV (4th generation). If you add an Apple TV (4th generation) to a home that has an Apple TV (3rd generation) set up, the Apple TV (3rd generation) will stop being used for HomeKit remote access.
