### ISSUE TITLE
why i have this waning in my log this is error or what how can i solve this 

### ISSUE THREAD

**Issue by steve-mahdi** [ebaauw/homebridge-hue#1140]
[23/01/2023, 23:58:35] [homebridge-hue] warning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070

**Comment by ebaauw** [comment]
As the message says: see #1070

**Comment by steve-mahdi** [comment]
Every thing is work but i get this error 1070 
What i missing to do to get this warning @ebaauw

**Comment by ebaauw** [comment]
1070 isn’t an error code, but a link to the issue on GitHub, explaining the planned changes.
