### ISSUE TITLE
HUE-Plugin, 2 HUE-Bridges, Child-Bridge; User-Entries

### ISSUE THREAD

**Issue by Stelzi76** [ebaauw/homebridge-hue#1144]
Hi,
since a new installation of homebridge I use the hue-plugin with two hue-bridges and enabled child-bridge. My problem is that if I write the 2 users in my config.json and then restart Homebridge there is an „unauthorized User“ message in the log. In my past installation without enabled child-bridge there is no error. I added the following entry under „platform…“ in my attached config.json. I searched the web for these problem but couldn‘t solve my problem. Without the user entriss I have to press the Linkbuttons on every reboot. 

> "platform": "Hue",
"users": {
"001788FFFEA": "9TP6EfXGTDWXX XXXXXXXXXXXX",
"ECB5FAFFFE0A917D": "8ng-JRI3100QC5py00skonbmXXXXXXXXXXX"
}

![E4EC20DB-8860-43C6-B9ED-3D1277898D18](https://user-images.githubusercontent.com/78620483/216819454-b7b89576-b8d6-4fc6-bb1d-7b73bc4c83f6.jpeg)

**Comment by ebaauw** [comment]
Make sure to copy/paste the `bridgeid` and `username` values from the log; both are case sensitive.  The copied text above looks broken: the `bridgeid` should be 16 hex digits; the `username` is 30 printable characters.  Try to add one bridge first, before doing the second bridge.

**Comment by Stelzi76** [comment]
Hi,
thanks for the quick response. I tried two different ways (See pictures please). First way there is the "unauthorized User" message. Trying the second way I must press the link buttons. Which way is correct?![image](https://user-images.githubusercontent.com/78620483/216836493-6586a637-a2f6-47b1-bcd5-5f3e85c6890f.jpeg)
![image](https://user-images.githubusercontent.com/78620483/216836499-001bd031-82c5-41f1-82ad-2997d688484b.jpeg)

**Comment by ebaauw** [comment]
The first way looks correct.  On which bridge do you get the "unauthorised user" message?  What does that messages read exactly?  Does the `username` for the other bridge work?  Are you sure you didn't mix the `bridgeid` and `username` values?

**Comment by Stelzi76** [comment]
A gewesen restarts und edits later ist finally worked with the settings in the picture. Thanks a lot for you support!!!![image](https://user-images.githubusercontent.com/78620483/216907698-be2cb53f-cc92-49ad-bcfb-05b88d9cad9b.jpeg)
