### ISSUE TITLE
Problem with Moes Knob (via Phoscon Conbee II - Hoobs 4.2.8)

### ISSUE THREAD

**Issue by The-Paw** [ebaauw/homebridge-hue#1147]
PlugIn Problem on hoobs 4.2.8 ??

2.3.2023, 17:59:17HOOBSHueWARNUNGPhoscon: /sensors/3: warning: ignoring unknown ZHASwitch sensor {"config":{"battery":100,"group":null,"on":true,"reachable":false},"ep":1,"etag":"44bf7f51ceb178e2997da05796ba8cbe","lastannounced":null,"lastseen":"2023-03-02T16:44Z","manufacturername":"_TZ3000_qja6nq5z","mode":1,"modelid":"TS004F","name":"Knob","state":{"buttonevent":null,"lastupdated":"none"},"type":"ZHASwitch","uniqueid":"70:ac:08:........"}

Under conbee Webinterface it was displayed under switch ..

**Comment by ebaauw** [comment]
How many buttons does it have?  What are the button names / labels?  What events can it send for which button?

**Comment by The-Paw** [comment]
@ebaauw https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6759

**Comment by ebaauw** [comment]
That link doesn't contain the answers to my questions.
