### ISSUE TITLE
Osram lights

### ISSUE THREAD

**Issue by DSchumacher2104** [ebaauw/homebridge-hue#115]
I use Osram Gardenspot RGB with my hue bridge. This lights are signed as known lights, perhaps you can add it to complete your plugin.

warning: unknown light model {"state":{"on":false,"bri":254,"hue":57856,"sat":234,"effect":"none","xy":[0.4,0.15],"alert":"select","colormode":"xy","reachable":true},"type":"Color light","name":"Gartenspots","modelid":"Gardenspot RGB","manufacturername":"OSRAM","uniqueid":"xx:xx:xx:xx:xx:xx:xx:xx-xx","swversion":"V1.04.12"}

**Comment by kapps7** [comment]
Do they show up in HomeKit because you are using it with the Hue Bridge?

**Comment by DSchumacher2104** [comment]
Yes, and i can control them without problems.

**Comment by ebaauw** [comment]
I can add them, no problem.

Does the `uniqueid` start with `84:18:26` and end with `-03` as for the other OSRAM lights?

Would you be able to check what range of colours they support by installing a bash script from https://github.com/ebaauw/ph.sh, and running `ph_light_values`?

**Comment by DSchumacher2104** [comment]
Yes, do you need more details of the `uniqueid`? I'll try to run this script :-)

**Comment by ebaauw** [comment]
Thanks.

No, the first numbers of the `uniqueid` are the vendor code and the part after the dash is the ZigBee endpoint.  The rest makes up the unique ZigBee mac address.  I'm not even sure it could be abused, but there's no need to share it.
