### ISSUE TITLE
Add support for HUE AURA

### ISSUE THREAD

**Issue by sphings79** [ebaauw/homebridge-hue#1151]
#### Issue
Hue Aura is not detected

#### Log Messages

```
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/11021096/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Because you've set `nativeHomeKitLights`.

**Comment by sphings79** [comment]
Thx, that was the trick.
