### ISSUE TITLE
Philips Hue bulbs power state after power outage

### ISSUE THREAD

**Issue by costingheonea** [ebaauw/homebridge-hue#1155]
Hello,
What is the best way to set power state of a philips hue bulb so after a power outage the light will remain off or on?
I read the other threads, but I cant understand what I have to do exactly. Is there a tutorial somewhere or a simpler way to change the behaviour?
Thank you and keep up the good work!

**Comment by ebaauw** [comment]
Technically it's the _Startup OnOff_ attribute (0x4003) on the _On/Off_ cluster (0x0006).  You can set this directly from the deCONZ GUI.  For the (extended) colour lights, the deCONZ REST API exposes this as `config/on/startup`, with values `true`, `false`, and `"previous"`.

I seem to remember having seen this on the Hue API as well, but the documentation only mentions it under APIv2.  The Hue app exposes some of these settings, but, if memory serves, not the option to leave the light off.

Homebridge Hue doesn't support changing these settings, as typically you would only do this once, after installing the light, and you don't want HomeKit users to be able to mess with these settings.

**Comment by costingheonea** [comment]
Let's assume that the light bulbs are updated to the latest version of the Hue application, and then added via Conbee in Zigbee. I had to access the Raspberry Pi through VNC and modify the general.xml file, following the instructions from the previous comments. I encountered some issues because I didn't have administrator rights, but I managed to solve them.
