### ISSUE TITLE
Node 18.16.0 requirement?

### ISSUE THREAD

**Issue by FezVrasta** [ebaauw/homebridge-hue#1156]
#### Issue

Hi, I use Homebridge on a Synology NAS that doesn't support Docker so I'm stuck with Node 17.9.1 for now, I was wondering why this plugin recently dropped support for Node 17.x, is there anything specific that v18 provides and the plugin needs?

#### Log Messages

```
```

**Comment by ebaauw** [comment]
I develop and test agains the latest active LTS version of node.  Other versions might work, or not; I simply don't have the bandwidth to test.
