### ISSUE TITLE
Hue API 1.19.0

### ISSUE THREAD

**Issue by DSchumacher2104** [ebaauw/homebridge-hue#116]
Yesterday the official Philips Hue App updated my hue bridge (v2) to firmware 1705121051, which brought API Version 1.19.0. With this API Version i cannot control my light groups anymore. When i turn on a group with iOS build-in Home App, the light group goes on and in about 2-3 seconds they automatically turn off. I tried this serveral times, but no chance to keep them on. Controlling my Osram Gardenspot RBG light, which is also exposed to HomeKit with Homebridge-hue, still works without problems. With the iConnectHue App controlling the light group works flawless.

Homebridge log:
[2017-5-31 21:26:56] [Hue] xxx: warning: api version 1.19.0

**Comment by ebaauw** [comment]
I just got the same update - I'll have a look at the new firmware and API version.  Once again, Philips has provided no release notes and no change log...

Having said that, I've yet to see a Hue API update which breaks homebridge-hue.  Just for my understanding, when you control a light group from HomeKit, do you mean a group created in HomeKit or a Hue bridge group, exposed to HomeKit by homebridge-hue as a light, using the `"groups": true` setting in config.json.  What happens when you control an individual light from the group from HomeKit?

I sometimes see this behaviour on an individual light: it switches off automatically 2-3 seconds after turning it on.  Powering off the light for a couple of seconds seems to cure this.

Could you attach the output of `homebridge -D` (see __Troubleshooting__ in the README).

**Comment by DSchumacher2104** [comment]
I created 2 light groups each with 4 blubs on hue bridge with the iOS App iConnectHue. i expose this two groups to homekit using `"groups": true` in config.json. I also expose  `"group0": true`. Every time i switch on 1 of the 2 light groups on, equal if using iOS Home-App or iConnectHue, the lights turn automatically off in 1-3 seconds. Even if i switch a single bulb which is in 1 of the 2 light group, it turns off automatically in 1-3 seconds. When running homebridge i have no possibillty to keep them on. If i stop homebridge and switch the light groups or a single light with iConnectHue, they behave normal and stay on. The behaviour is similar, if i turn on all light using group0 (which means all connected light). All lights turn on for 1-3 seconds and after 1-3 seconds all lights turn off automatically.

I have restarted the hue bridge and homebridge, but nothing changed. I will try to get a debug log, but i'm not very good in linux.

**Comment by ebaauw** [comment]
Just a hunch: did you set `"wallSwitch": true` in config.json?  
In that case, homebridge-hue forces the lights to off when the Hue bridge reports them as unreachable (under the assumption that you turned them off using the wall switch).  However, when they're actually reachable and only being reported unreachable, the lights turn off.  The 2-3 seconds is probably homebridge-hue's heartrate.  You should see messages in the homebridge log like:
> 6/1/2017, 7:13:28 AM] [Hue] Bedroom 3: not reachable: set homekit power from 1 to 0

Homebridge-hue sets Status Fault when a light is reported unreachable (regardless of the wallSwitch setting), but the iOS built-in Home app ignores that.  You need another HomeKit app, like Eve, to see that.  Alternatively, you can check in the Hue app (easiest under Light Setup in Settings) whether the bridge reports lights as unreachable.

**Comment by DSchumacher2104** [comment]
Didn't set `"wallSwitch": true`, but yes, that is exactly what i see in the log. They are stated as "not reachable" and then power turns off, after power changes from 0 to 1. In fact they are reachable and they turn on. The Hue app or iConnectHue don't report a problem with reachability of the light. Coud it be, that homebridge receives a missleading information from the hue bridge due to API change, when fetching light group information?

This is the log:

> [2017-6-2 08:41:14] [Hue] Wohnzimmerwand: homekit power changed from 0 to 1
[2017-6-2 08:41:14] [Hue] Wohnzimmerwand: not reachable: set homekit power from 1 to 0
[2017-6-2 08:41:14] [Hue] Wohnzimmerwand: set homekit any on from 0 to 1
[2017-6-2 08:41:14] [Hue] Group 0: set homekit any on from 0 to 1
[2017-6-2 08:41:16] [Hue] Wohnzimmerwand: set homekit any on from 1 to 0
[2017-6-2 08:41:16] [Hue] Group 0: set homekit any on from 1 to 0

I can't explain this bevahiour.

**Comment by ebaauw** [comment]
> [2017-6-2 08:41:14] [Hue] Wohnzimmerwand: not reachable: set homekit power from 1 to 0

This is a bug in homebridge-hue, probably introduced in v0.4.6: groups don't have a `reachable` attribute, so it shouldn't apply this logic, irrespective of the config.json `wallSwitch` setting.  I don't see how this would be related to the new bridge firmware, however.

Anyway, v0.4.8 should solve this.

**Comment by DSchumacher2104** [comment]
Yes, i updated from v0.3.9 to 0.4.7 exactly the same time as firmware on bridge updated. So i thought, it could be due to API change. Anyway, it works perfect now, many thanks :-)
