### ISSUE TITLE
Error upgrading Hue pugin

### ISSUE THREAD

**Issue by pjannink** [ebaauw/homebridge-hue#1161]
The upgrade to version v0.13.63 failed

**Comment by pjannink** [comment]
![Schermafbeelding Hue](https://github.com/ebaauw/homebridge-hue/assets/85283776/6daabba9-90a9-4f77-b9ae-f84d85055829)

**Comment by ebaauw** [comment]
This is not a Homebridge Hue issue.  Looks like a broken `npm` and/or NodeJS installation.

**Comment by pjannink** [comment]
Hi Erik,

 

Thanks.

Ik heb via Portainer de container laten “vernieuwen”. Toen moest ik weer een aantal plug-ins vernieuwen en dat ging nu goed. Problem solved!

 

Groet,

 

Paul

 

Van: Erik Baauw ***@***.***> 
Verzonden: woensdag 5 juli 2023 07:36
Aan: ebaauw/homebridge-hue ***@***.***>
CC: pjannink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ebaauw/homebridge-hue] Error upgrading Hue pugin (Issue #1161)

 

This is not a Homebridge Hue issue. Looks like a broken npm and/or NodeJS installation.
