### ISSUE TITLE
hoobs 4.3.0 - no connection to ConBee II

### ISSUE THREAD

**Issue by The-Paw** [ebaauw/homebridge-hue#1162]
#### Issue
Got an error since a few days .. 

21.7.2023, 14:03:38HueHueWARNUNG192.168.178.47: request 1: connect ECONNREFUSED 192.168.178.47:1881
21.7.2023, 14:03:38HueHueFEHLER192.168.178.47:1881: not found - retrying in 30s

RaspBee Config is working on http://phoscon.de/pwa - can use my to PowerSwitches (in Lights) .. but no one in HomeKit :-((

PlugIn Config (without :1881 is working):

{
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "name": "Hue",
            "hosts": [
                "192.168.178.47"
            ],
            "brightnessAdjustment": 100,
            "heartrate": 5,
            "lowBattery": 25,
            "timeout": 5,
            "waitTimePut": 50,
            "waitTimePutGroup": 1000,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20,
            "users": {
                "001788FFFE2*****": "***",
                "00212EFFFF0*****": "***"
            },
            "sensors": true,
            "lights": true
        }
    ]
}

21.7.2023, 14:02:54Hue starting
21.7.2023, 14:03:00HueFEHLER[31mThe plugin "homebridge-hue" requires a Homebridge version of ^1.6.1 which does not satisfy the current Homebridge version of 1.6.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
21.7.2023, 14:03:08HueLoaded plugin 'homebridge-hue'
21.7.2023, 14:03:08HueLoading 1 platforms...
21.7.2023, 14:03:08HueHuehomebridge-hue v0.13.63, node v16.20.1, homebridge v1.6.0
21.7.2023, 14:03:08HueHueWARNUNGwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
21.7.2023, 14:03:08HueHue192.***.***.47: request 1: GET /config
21.7.2023, 14:03:08HueHueWARNUNG192.168.178.47: request 1: connect ECONNREFUSED 192.168.178.47:1881
21.7.2023, 14:03:08HueHueFEHLER192.168.178.47:1881: not found - retrying in 30s
21.7.2023, 14:03:37HueConfiguration change
21.7.2023, 14:03:37hue stopping
21.7.2023, 14:03:38HueHue192.***.***.47: request 1: GET /config
21.7.2023, 14:03:38HueHueWARNUNG192.168.178.47: request 1: connect ECONNREFUSED 192.168.178.47:1881
21.7.2023, 14:03:38HueHueFEHLER192.168.178.47:1881: not found - retrying in 30s
21.7.2023, 14:03:39HueHuegoodbye
21.7.2023, 14:03:42Hue starting
21.7.2023, 14:03:47HueFEHLER[31mThe plugin "homebridge-hue" requires a Homebridge version of ^1.6.1 which does not satisfy the current Homebridge version of 1.6.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
21.7.2023, 14:03:53HueLoaded plugin 'homebridge-hue'
21.7.2023, 14:03:53HueLoading 1 platforms...
21.7.2023, 14:03:53HueHuehomebridge-hue v0.13.63, node v16.20.1, homebridge v1.6.0
21.7.2023, 14:03:53HueHueWARNUNGwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
21.7.2023, 14:03:53HueHueTheHue: Signify Netherlands B.V. BSB002 bridge v1958159030, api v1.58.0
21.7.2023, 14:03:55HueHueTheHue: 23 accessories
21.7.2023, 14:03:55HueHuemasked debug info dumped to /var/lib/hoobs/hue/homebridge-hue.json.gz
21.7.2023, 14:03:55HueHueTheHue: 2 services
21.7.2023, 14:03:55HueBridge is running on port 51846.
21.7.2023, 14:03:55HueHueTheHue: event stream connected to https://192.168.178.47/eventstream/clip/v2

**Comment by ebaauw** [comment]
I don't know HOOBS and strongly recommend to use a standard Homebridge installation.

Homebridge Hue doesn't connect to a ConBee II, see the [README](https://github.com/ebaauw/homebridge-hue#introduction) and [deCONZ for Dummies](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-for-Dummies).

From your config.json, it seems like you have both a Hue bridge and a deCONZ gateway, but only the Hue bridge is mentioned under `hosts`.

> 21.7.2023, 14:03:38HueHueWARNUNG192.168.178.47: request 1: connect ECONNREFUSED 192.168.178.47:1881

I don't understand what's happening here, in particular where the port 1881 comes from.  After the restart, Homebridge Hue does find and connect to the Hue bridge.

**Comment by The-Paw** [comment]
@ebaauw how could I add the RaspBee II Conbee .. via host ??

**Comment by The-Paw** [comment]
@ebaauw 

25.7.2023, 17:07:38HueHueWARNUNG192.168.178.106: request 1: invalid response
25.7.2023, 17:07:38HueHueFEHLER192.168.178.106: not found - retrying in 30s

..106 IP from the Phoscon RaspBee II

**Comment by The-Paw** [comment]
@ebaauw with an older version of the PlugIn it works great with the RaspBee II .. and I would like to use only the ConBee devices without the HueBridge

**Comment by The-Paw** [comment]
@ebaauw I´ve "fixed" it with your new decent-plugin ..
