### ISSUE TITLE
Plugin does not connect to hue bridge

### ISSUE THREAD

**Issue by code0482** [ebaauw/homebridge-hue#1166]
Hello,

I have installed the plugin then clicked the button then saved the user info in the configuration, then the plugin stops and starts and states that the button has not been pushed. I do see the issue that states that you are in the process of splitting the plugin. Is there a way to make this plugin still work? 

System is up to date, posting the config and the log with my user info.

**BELOW IS THE CONFIG**

{
    "platform": "Hue",
    "name": "Hue",
    "brightnessAdjustment": 100,
    "heartrate": 5,
    "lowBattery": 25,
    "timeout": 5,
    "waitTimePut": 50,
    "waitTimePutGroup": 1000,
    "waitTimeResend": 300,
    "waitTimeUpdate": 20,
    "users": {
        "userinfo": "userinfo"
    },
    "groups": true,
    "group0": true,
    "lights": true,
    "wallSwitch": true
}

**BELOW IS THE LOGS**
8/20/2023, 2:01:53 PMHue Bridge starting
8/20/2023, 2:02:03 PMHue BridgeERROR[31mThe plugin "homebridge-hue" requires a Homebridge version of ^1.6.1 which does not satisfy the current Homebridge version of 1.6.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
8/20/2023, 2:02:14 PMHue BridgeLoaded plugin 'homebridge-hue'
8/20/2023, 2:02:14 PMHue BridgeLoading 1 platforms...
8/20/2023, 2:02:14 PMHue BridgeHuehomebridge-hue v0.13.66, node v16.20.2, homebridge v1.6.0
8/20/2023, 2:02:14 PMHue BridgeHueWARNINGwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
8/20/2023, 2:02:14 PMHue BridgeHuesearching bridges and gateways
8/20/2023, 2:02:19 PMHue BridgeHuePhilips hue: Signify Netherlands B.V. BSB002 bridge v1959097030, api v1.59.0
8/20/2023, 2:02:19 PMHue BridgeHuePhilips hue: Signify Netherlands B.V. BSB002 bridge v1959097030, api v1.59.0
8/20/2023, 2:02:19 PMHue BridgeHuePhilips hue: request 1: POST / {"devicetype":"homebridge-hue#hoobs"}
8/20/2023, 2:02:19 PMHue BridgeHueWARNINGPhilips hue: request 1: : api error 101: link button not pressed
8/20/2023, 2:02:19 PMHue BridgeHuePhilips hue: press link button on the bridge to create a user - retrying in 15s
8/20/2023, 2:02:19 PMHue BridgeHuePhilips hue: request 1: POST / {"devicetype":"homebridge-hue#hoobs"}
8/20/2023, 2:02:19 PMHue BridgeHueWARNINGPhilips hue: request 1: : api error 101: link button not pressed
8/20/2023, 2:02:19 PMHue BridgeHuePhilips hue: press link button on the bridge to create a user - retrying in 15s
8/20/2023, 2:02:35 PMHue BridgeHuePhilips hue: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "userinfo": "userinfo"
      }
    }
  ]
8/20/2023, 2:02:35 PMHue BridgeHuePhilips hue: request 2: POST / {"devicetype":"homebridge-hue#hoobs"}
8/20/2023, 2:02:35 PMHue BridgeHueWARNINGPhilips hue: request 2: : api error 101: link button not pressed
8/20/2023, 2:02:35 PMHue BridgeHuePhilips hue: press link button on the bridge to create a user - retrying in 15s
8/20/2023, 2:02:35 PMHue BridgeHuePhilips hue: 1 accessories
8/20/2023, 2:02:35 PMHue BridgeHuePhilips hue: event stream connected to https://10.0.0.226/eventstream/clip/v2
8/20/2023, 2:02:50 PMHue BridgeHuePhilips hue: request 3: POST / {"devicetype":"homebridge-hue#hoobs"}
8/20/2023, 2:02:50 PMHue BridgeHueWARNINGPhilips hue: request 3: : api error 101: link button not pressed
8/20/2023, 2:02:50 PMHue BridgeHuePhilips hue: press link button on the bridge to create a user - retrying in 15s
8/20/2023, 2:03:05 PMHue BridgeHuePhilips hue: request 4: POST / {"devicetype":"homebridge-hue#hoobs"}
8/20/2023, 2:03:05 PMHue BridgeHueWARNINGPhilips hue: request 4: : api error 101: link button not pressed
8/20/2023, 2:03:05 PMHue BridgeHuePhilips hue: press link button on the bridge to create a user - retrying in 15s
8/20/2023, 2:03:20 PMHue BridgeHuePhilips hue: request 5: POST / {"devicetype":"homebridge-hue#hoobs"}
8/20/2023, 2:03:20 PMHue BridgeHueWARNINGPhilips hue: request 5: : api error 101: link button not pressed
8/20/2023, 2:03:20 PMHue BridgeHuePhilips hue: press link button on the bridge to create a user - retrying in 15s
8/20/2023, 2:03:28 PMHue BridgeConfiguration change
8/20/2023, 2:03:29 PMhuebridge stopping
8/20/2023, 2:03:31 PMHue BridgeHuegoodbye
8/20/2023, 2:03:34 PMHue Bridge starting
8/20/2023, 2:03:34 PMHue Bridge starting
8/20/2023, 2:03:44 PMHue BridgeERROR[31mThe plugin "homebridge-hue" requires a Homebridge version of ^1.6.1 which does not satisfy the current Homebridge version of 1.6.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
8/20/2023, 2:03:55 PMHue BridgeLoaded plugin 'homebridge-hue'
8/20/2023, 2:03:55 PMHue BridgeLoading 1 platforms...
8/20/2023, 2:03:55 PMHue BridgeHuehomebridge-hue v0.13.66, node v16.20.2, homebridge v1.6.0
8/20/2023, 2:03:55 PMHue BridgeHueWARNINGwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
8/20/2023, 2:03:55 PMHue BridgeHuesearching bridges and gateways
8/20/2023, 2:04:00 PMHue BridgeHuePhilips hue: Signify Netherlands B.V. BSB002 bridge v1959097030, api v1.59.0
8/20/2023, 2:04:00 PMHue BridgeHuePhilips hue: Signify Netherlands B.V. BSB002 bridge v1959097030, api v1.59.0
8/20/2023, 2:04:00 PMHue BridgeHuePhilips hue: request 1: POST / {"devicetype":"homebridge-hue#hoobs"}
8/20/2023, 2:04:00 PMHue BridgeHueWARNINGPhilips hue: request 1: : api error 101: link button not pressed
8/20/2023, 2:04:00 PMHue BridgeHuePhilips hue: press link button on the bridge to create a user - retrying in 15s
8/20/2023, 2:04:01 PMHue BridgeHuePhilips hue: 2 accessories
8/20/2023, 2:04:01 PMHue BridgeHuePhilips hue: event stream connected to https://10.0.0.226/eventstream/clip/v2

**Comment by ebaauw** [comment]
The plugin connects to your Hue bridges alright.  It finds two of them, and you only pressed the link button on one.
