### ISSUE TITLE
No more possibility to switch the motion detector on or off

### ISSUE THREAD

**Issue by tuxnetDE** [ebaauw/homebridge-hue#1167]
Good morning from Germany.

I no longer have the option to turn the motion detector on or off.

I have created a scene for each room, through which I could turn the motion detector on or off. 

Strangely, this no longer works.

Docker Synology - Ubuntu Focal Fossa (20.04.5 LTS)
Node.js Version | v18.17.1
homebridge-hue v0.13.66 (2023-08-11)
hb-lib-tools form 02.09.2023

When starting the scene, no log information.

In home you see only failed

**Comment by ebaauw** [comment]
I really need some more info:
- Do you mean HomeKit scenes?  Do they still show the motion sensor's _Enabled_ characteristic in Eve (or another deccent HomeKit app)?
- Can you enable/disable the motion sensor from Eve by flipping _Enabled_?  You should see a message in the Homebridge log for this.
- Can you enable/disable the motion sensor through the Hue/deCONZ API?  Something like:
  `ph -H x.x.x.x put /sensors/xxx/config '{"on": false}'`
