### ISSUE TITLE
0.13.67 version mismatch

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#1169]
Hi @ebaauw ,

I got an information about the release v0.13.67 - v0.13.57 after 0.13.66. is this correct?

I saw that you have now a dependency to Node.js 20.7. Is this really required (and an upgrade more risky than minor updates) because many installations are still running on Node.js 18 LTS. 

Thanks JO

**Comment by ebaauw** [comment]
That was just a typo in the release name, thanks for reporting.  Release should now be v1.13.67.

I moved to NodeJS v20 a month early.  Latest v18 release should work just as well.  I just recommend the version I use for development and testing.

**Comment by jostrasser** [comment]
> That was just a typo in the release name, thanks for reporting.  Release should now be v1.13.67.
> 
> 
> 
> I moved to NodeJS v20 a month early.  Latest v18 release should work just as well.  I just recommend the version I use for development and testing.

Hi @ebaauw 
Thanks!

FYI: the release is still not visible / recognized on my homebridge but it can maybe take some time until it's distributed. 

About Node.js: I have to check all other plugins first if the upgrade to V20 can impact the others. I have no idea if this can break anything. However, the goal is V20. 

Thanks JO!

**Comment by ebaauw** [comment]
Hm, looks like the version wasn't published to the NPM registry.  Corrected now.

The upgrade to NodeJS v20 went surprisingly well for me.  Of course, changing the major version of NodeJS is always a challenge for repositories that use C++ extensions.  I find it easiest simply to re-install them.

**Comment by jostrasser** [comment]
Hi @ebaauw 

Great to hear, thanks!

I am always doing the Node updates with `hb-service update-node`. Do you know, is there a parameter to change the LTS version with it from 18 to 20? Of what is your recommendation to update Node in my case?

Thanks JO

**Comment by jostrasser** [comment]
> Hi @ebaauw 
> 
> Great to hear, thanks!
> 
> I am always doing the Node updates with `hb-service update-node`. Do you know, is there a parameter to change the LTS version with it from 18 to 20? Or what is your recommendation to update Node in my case?
> 
> Thanks JO

Got it, after Homebridge-UI update. 

Thanks, issue fixed.
