### ISSUE TITLE
Exclude lux ambient sensors

### ISSUE THREAD

**Issue by jdshkolnik** [ebaauw/homebridge-hue#117]
Hi,

Is there a way to exclude those lux ambient sensor accessories from appearing in Home?

**Comment by ebaauw** [comment]
Yes, through `excludeSensorTypes` in config.json., see the [Wiki](https://github.com/ebaauw/homebridge-hue/wiki/Configuration).  The light sensor is `"ZLLLightLevel"`.

**Comment by jdshkolnik** [comment]
Thanks.
