### ISSUE TITLE
error:0A00010B 

### ISSUE THREAD

**Issue by cryptotimb** [ebaauw/homebridge-hue#1173]
#### Issue
Having issues setting up, please see log

Running homebridge version 1.6.1
node version 18.16.1
plugin version 0.13.67
### Log Messages

05:41:56 PMHue BridgeHueinfohomebridge-hue v0.13.67, node v18.16.1, homebridge v1.6.1
05:41:56 PMHue BridgeHuewarnwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
05:41:56 PMHue BridgeHueinfoHue Bridge: Signify Netherlands B.V. BSB002 bridge v1960149090, api v1.60.0
05:41:56 PMHue BridgeHueinfoHue Bridge: request 1: POST / {"devicetype":"homebridge-hue#hoobs"}
05:41:56 PMHue BridgeHuewarnHue Bridge: request 1: write EPROTO 10F02A88FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
05:42:11 PMHue BridgeHueinfoHue Bridge: request 2: POST / {"devicetype":"homebridge-hue#hoobs"}
05:42:11 PMHue BridgeHuewarnHue Bridge: request 2: write EPROTO 10F02A88FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
05:42:26 PMHue BridgeHueinfoHue Bridge: request 3: POST / {"devicetype":"homebridge-hue#hoobs"}
05:42:26 PMHue BridgeHuewarnHue Bridge: request 3: write EPROTO 10F02A88FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:

#### Debug Files

05:41:56 PMHue BridgeHueinfohomebridge-hue v0.13.67, node v18.16.1, homebridge v1.6.1
05:41:56 PMHue BridgeHuewarnwarning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
05:41:56 PMHue BridgeHueinfoHue Bridge: Signify Netherlands B.V. BSB002 bridge v1960149090, api v1.60.0
05:41:56 PMHue BridgeHueinfoHue Bridge: request 1: POST / {"devicetype":"homebridge-hue#hoobs"}
05:41:56 PMHue BridgeHuewarnHue Bridge: request 1: write EPROTO 10F02A88FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
05:42:11 PMHue BridgeHueinfoHue Bridge: request 2: POST / {"devicetype":"homebridge-hue#hoobs"}
05:42:11 PMHue BridgeHuewarnHue Bridge: request 2: write EPROTO 10F02A88FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
05:42:26 PMHue BridgeHueinfoHue Bridge: request 3: POST / {"devicetype":"homebridge-hue#hoobs"}
05:42:26 PMHue BridgeHuewarnHue Bridge: request 3: write EPROTO 10F02A88FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:

**Comment by ebaauw** [comment]
Looks like you have a version of OpenSSL that is incompatible with the version of NodeJS.  Nothing to do with Homebridge Hue.  As a workaround, you might try setting `forceHttp`, so Homebridge Hue doesn’t use HTTPS.
