### ISSUE TITLE
Unable to update to version 0.13.68

### ISSUE THREAD

**Issue by ruudbol** [ebaauw/homebridge-hue#1174]
There is a update available message in HomeBridge, however when i try to update the plugin i get the following messages

USER: pi
DIR: /var/lib/homebridge
CMD: pnpm install --save homebridge-hue@0.13.68

 WARN  GET https://registry.npmjs.org/homebridge-hue error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/homebridge-hue error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/homebridge-hue: Value of "this" must be of type URLSearchParams
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for homebridge-hue@0.13.68

The latest release of homebridge-hue is "0.13.65".

If you need the full list of all 335 published versions run "$ pnpm view homebridge-hue versions".
Progress: resolved 5, reused 5, downloaded 0, added 0

Operation failed. Please review log for details.

**Comment by ebaauw** [comment]
Lastest version is 0.13.68, see https://www.npmjs.com/package/homebridge-hue.

This is an issue with whatever software you use to try and update Homebridge Hue, not with Homebridge Hue itself.

**Comment by ruudbol** [comment]
Hi Erik, thx for your reply, i am rebuilding homebridge now, i will use deconz for conbee , but can you advise me if i should use your hue or hue2 plugin for my hue v2 bridge ?Best regards, RuudOp 8 nov 2023 om 18:45 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
Lastest version is 0.13.68, see https://www.npmjs.com/package/homebridge-hue.
This is an issue with whatever software you use to try and update Homebridge Hue, not with Homebridge Hue itself.

**Comment by ebaauw** [comment]
Hue2 is still just a placeholder.
