### ISSUE TITLE
Reset Timeout parameter throws error

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-hue#1175]
#### Issue

Hello, I tried using the new slider for the Reset Timeout parameter but it seems somethings wrong. I get the following error thrown in the log. This is what my config.json entry looks like  "resetTimeout": 2000,
#### Log Messages

```
[Hue] config.json: resetTimeout: not a boolean
```

**Comment by ebaauw** [comment]
In v0.13.69.
