### ISSUE TITLE
Log level settings

### ISSUE THREAD

**Issue by 350d** [ebaauw/homebridge-hue#1176]
Hello! I've downloaded latest EVE app on my iPhone but can't find any LogLevel options in TYPES or on any devices I've checked (bridges, lights). How to change the log level for specific bridge or accessory? I have DiyHue bridge for my TV zone where I have thousands lines of logs about TV dynamic backlight lights.

**Comment by ebaauw** [comment]
It's on the accessory that Homebridge Hue exposes for the bridge.

**Comment by 350d** [comment]
Sorry, but it's not clear where is this device available? In EVE app? There is DiyHUE bridge available but no any TYPES in any UI screens I have. DO you have any demo/screenshots?
![919E8837-AD24-4811-912A-B400F93DAC6C_4_5005_c](https://github.com/ebaauw/homebridge-hue/assets/429208/2a52d72c-d933-46f7-be43-81fdf92e9901)
![66FF171B-85A6-4E2F-BC91-62A05825287B_4_5005_c](https://github.com/ebaauw/homebridge-hue/assets/429208/de3d0900-842f-456a-96d1-9003b05c1a95)
![0ACFDB51-F2D0-4402-B61E-6FF93A41BC3E_4_5005_c](https://github.com/ebaauw/homebridge-hue/assets/429208/352209ba-2492-42fe-a4c0-68bd94580d85)

**Comment by ebaauw** [comment]
Damn, my bad.  Homebridge Hue doesn’t support setting the log level.  This feature is based on homebridge-lib, and only works for dynamic platform accessory plugins.  Homebridge Hue uses the old static platform accessories paradigm.  Changing this would cause you to lose all HomeKit accessories and associated rooms, groups, scenes, and automations, see https://github.com/ebaauw/homebridge-hue/issues/1070.

After having split off deCONZ support to Homebridge deCONZ, I want to split off support for the gen-2 Hue bridge to Homebridge Hue2.  Only after that I might consider refactoring Homebridge Hue for the gen-1 Hue bridge and the likes of DIYHue, if there is enough demand.  No ETA - too many other interesting devices and not enough time.
