### ISSUE TITLE
2nd Hue Bridge needs manual pressing of button

### ISSUE THREAD

**Issue by MJV74** [ebaauw/homebridge-hue#1178]
I have homebridge running on a pi.
I have 2 HUE bridges in my house (to many bulbs and switches for 1)
I have added both bridges in homebridge via "homebridge-hue"
only the first bridge connects automatically on every restart. the second one requires a button press on the bridge every time.
I have also switched position of the bridges in the config editor, and it remains the 2nd Bridge requiring the hard button press.

Anyone any idea what I am doing wrong?
thanks in advance for any help

**Comment by ebaauw** [comment]
You need to add the bridge ID and username (API key) of the second bridge to config.json as well.

**Comment by MJV74** [comment]
I have added both to config.json as required.
Only the first one listed in the file works automatically. the second one (I switched the following order to test) always requires  manually pressing the bridge button

**Comment by ebaauw** [comment]
Double-check the bridge ID, it’s case sensitive.  And it should be a single object with the two bridge IDs as keys and the two usernames as values.

**Comment by Daan1203** [comment]
Hello Erik,

I have the same problem here. Using the standard settings. Everytime i restart the Homebridge, I need to press the button.
I am new to homebridge, so i don’t know what i have to config file.
Everything is working great after pressing the button, but is there a solution, so I don’t have to press it everytime when startup homebridge?

(You can answer in dutch if you prefer)

![IMG_3782](https://github.com/ebaauw/homebridge-hue/assets/67052137/480f2929-2896-45f6-b29d-a590c0e79ddd)

**Comment by MJV74** [comment]
> Double-check the bridge ID, it’s case sensitive. And it should be a single object with the two bridge IDs as keys and the two usernames as values.

Ah, thank you, I had added them as two separate objects. Now combined and it works like a charm!

**Comment by Daan1203** [comment]
@MJV74 Can you show me a printscreen of your config? So I can do the same with my problem. Thanks

**Comment by MJV74** [comment]
> @MJV74 Can you show me a printscreen of your config? So I can do the same with my problem. Thanks

![image](https://github.com/ebaauw/homebridge-hue/assets/153365513/75e50161-25a2-4dce-ba4b-d3688f2c3ca5)

**Comment by Daan1203** [comment]
@MJV74 @ebaauw 
![afbeelding](https://github.com/ebaauw/homebridge-hue/assets/67052137/2bf32fd0-c60e-4b2c-8ac7-34b33b4d4a92)

Where do I need to put the "users"? Onder the last section?

**Comment by MJV74** [comment]
![image](https://github.com/ebaauw/homebridge-hue/assets/153365513/8e901676-5817-4e2a-b359-b78d57665f5f)

**Comment by Daan1203** [comment]
@MJV74 Do I need to delete the rest of the Hue config?

**Comment by MJV74** [comment]
No need to delete anything, just add this under platforms.
when you start up home bridge, it asks you to press the button on the bridge. then the startup log shows the hue ID and Key as on my print screen. Copy those and add them under platforms in the config file

**Comment by ebaauw** [comment]
I realise this is awkward, but back in the day when I created Homebridge Hue, this was the only way to get it to work.

Homebridge Hue2 will use the dynamic platform accessory setup, and persist the username (API key) in the cached accessories, so there will be no more need to edit config.json manually.
