### ISSUE TITLE
Trying to add an outlet

### ISSUE THREAD

**Issue by dezinarts** [ebaauw/homebridge-hue#1180]
Hello, sorry in advance, I know there have already been several topics on this subject.

I have 4 sonoff mini in huebridge, but there is one that I would like to appear as a socket and not as a light.

I tried to follow the wiki and the FAQ but I'm a newbie and have absolutely no knowledge of the json language. Every time I add a line to the file it gives me a syntax error.

Can you help me please ?

Here is the basic json config file:
{
    "name": "Hue",
    "anyOn": true,
    "effects": true,
    "hosts": [
        "10.0.0.9"
    ],
    "lights": true,
    "linkButton": false,
    "nativeHomeKitLights": true,
    "nativeHomeKitSensors": true,
    "resource": true,
    "sensors": false,
    "platform": "Hue"
}

I would like to add "Fontaine" as a socket and not as a light.

Thanks for advance.

**Comment by ebaauw** [comment]
Note that Homebridge Hue will stop supporting deCONZ as of the next version.  Best migrate to Homebridge deCONZ and use the `ui` command to change how to expose the device, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration.

For Homebridge Hue, you need to create a resourcelink on the deCONZ gateway, see https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links.

There are plenty of resources online that explain JSON.  Use a validator, like https://jsonlint.com to check for syntax errors.

**Comment by dezinarts** [comment]
How can I use my hue bridge in the homebridge deCONZ? I don't have any Conbee USB stick or a RaspBee II. My sonoff device is natively support by Hue app

**Comment by ebaauw** [comment]
Ah OK, in that case stick with Homebridge Hue and create a resourcelink on the Hue bridge.

**Comment by dezinarts** [comment]
Can you help me to do this? pleeeeease

**Comment by dezinarts** [comment]
Anyone ?

**Comment by steffensammet** [comment]
Hello,

hooking in on this topic, as I am also looking for an example how to deal with ressourcelinks (couldn't find any). 
In my case, I want to put a room on a blacklist.

Thanks,
Steffen
