### ISSUE TITLE
Unable to setup - Unauthorized 

### ISSUE THREAD

**Issue by airbornetrooper82573** [ebaauw/homebridge-hue#1181]
I had to setup HomeBridge from scratch and when adding Hue, I'm getting this error:

[12/23/2023, 5:12:48 PM] [Hue] Hue Bridge: Signify Netherlands B.V. BSB002 bridge v1961135030, api v1.61.0
[12/23/2023, 5:12:48 PM] [Hue] Hue Bridge: request 1: /: api error 1: unauthorized user
[12/23/2023, 5:12:48 PM] [Hue] Hue Bridge: /: api error 1: unauthorized user - retrying in 15s
[12/23/2023, 5:12:53 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtM

I remember from past use, the log would say to hit the button on the hub. But I'm never getting told this. I see in the log to add the users info, which I have added exactly as it asks. I'm pretty sure that "undefined" isn't going to work. Any help? Only one I saw having this issue said they referred to their old Pi but that's not an option for me because I run Homebridge on my TrueNAS server. 

`        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "192.168.1.216"
            ],
            "users": {
                "001788FFFE262050": "undefined"
            },
            "lights": true,
            "linkButton": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "platform": "Hue"
        }`

**Comment by ebaauw** [comment]
You need to remove the bridgeid/username from `users`.  For sure, `undefined` isn’t a valid username, hence, the “unauthorized user” error.

**Comment by airbornetrooper82573** [comment]
My mistake, TrueCharts made some recent changes. I forgot to go to Global Pod Options (Advanced) > Check Export -Pod Options > Check Host Networking. 

It was using Kubernetes IP so couldn't talk to the rest of my LAN. Once I did that it was behaving like I'm used to.
