### ISSUE TITLE
Hue light group shows as Off even if some of the lights are On

### ISSUE THREAD

**Issue by oransterf** [ebaauw/homebridge-hue#1187]
#### Issue
In the Home app, the Light for the corresponding room hue light group will show as "Off" if any single light within the group is off. 
I have hue scenes that have some of the lights off in the group and the group light will show Off in those scenes. 

Any way to fix this? Thanks!

**Comment by ebaauw** [comment]
By default, the _On_ characteristics for a group _Lightbulb_ follows the `state/any_on` attribute, so it would show as off, when all lights in the group are off.  This behaviour can be changed by setting `anyOn` in config.json, see the [Wiki](https://github.com/ebaauw/homebridge-hue/wiki/Configuration).

Please double-check that:
- You haven't set `anyOn`;
- The Hue bridge correctly reports `state/any_on` as true (and `state/all_on` as false);
- The Home app has refreshed the state of the group accessory.

If these all check out and you think there's an issue with Homebrdige Hue, please attach the [debug dump file](https://github.com/ebaauw/homebridge-hue?tab=readme-ov-file#debug-dump-file) and a capture and attach a [debug log file](https://github.com/ebaauw/homebridge-hue?tab=readme-ov-file#debug-log-file).

**Comment by oransterf** [comment]
> By default, the _On_ characteristic for a group _Lightbulb_ follows the `state/any_on` attribute, so it would show as off, when all lights in the group are off. This behaviour can be changed by setting `anyOn` in config.json, see the [Wiki](https://github.com/ebaauw/homebridge-hue/wiki/Configuration).
> 
> Please double-check that:
> 
> * You haven't set `anyOn`;
> * The Hue bridge correctly reports `state/any_on` as true (and `state/all_on` as false);
> * The Home app has refreshed the state of the group accessory.
> 
> If these all check out and you think there's an issue with Homebrdige Hue, please attach the [debug dump file](https://github.com/ebaauw/homebridge-hue?tab=readme-ov-file#debug-dump-file) and a capture and attach a [debug log file](https://github.com/ebaauw/homebridge-hue?tab=readme-ov-file#debug-log-file).

I got confused thinking enabling this would do the opposite of what it does. Thank you!
