### ISSUE TITLE
This plugin causes JavaScript heap error

### ISSUE THREAD

**Issue by kylewhirl** [ebaauw/homebridge-hue#1188]
#### Issue

I have quite a few plugins and I went through the process of disabling them in order to find which one was causing a memory leak leading to Homebridge crashing every day. After disabling this plugin, Homebridge has not crashed at all in a few weeks. 

Not sure why the plugin is causing errors, but I have a hue bridge v1 that works fine with home assistant, not this Homebridge plugin though

#### Log Messages

```
```

#### Debug Files

https://www.icloud.com/iclouddrive/053O45wBPkJU7f3kUuPZh8blA#homebridge-hue

**Comment by ebaauw** [comment]
Do you also see a crash when running Homebridge Hue in a separate child bridge?  Please attach a debug log file of Homebridge starting and of the error / crash.  What makes you think there's a memory leak?   How do you monitor memory usage?  Please provide logs.
