### ISSUE TITLE
Error calling to AirzoneCloud. Status: 403 Forbidden

### ISSUE THREAD

**Issue by hbouy** [ebaauw/homebridge-hue#1189]
It seems the plugin cannot connect to the AirzoneCloud API. 
Using:

- Homebridge v1.8.4 (HAP v0.12.2)

- Homebridge Airzone Cloud v0.5.2

 Getting the following error message:

`[9/2/2024, 6:00:42 PM] [AirzoneCloud] Unable to login to AirzoneCloud. Request: {"url":"https://www.airzonecloud.com/users/sign_in","method":"POST","mode":"cors","headers":{"Content-Type":"application/json;charset=utf-8","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"},"body":"{\"email\":\"XXXXXX\",\"password\":\"XXXXXXX\"}"} {"size":0,"timeout":0}
[9/2/2024, 6:00:42 PM] [AirzoneCloud] Error calling to AirzoneCloud. Status: 403 Forbidden`

**Comment by ebaauw** [comment]
I don't think this is Homebridge Hue.  I have no clue what AirzoneCloud is.

**Comment by hbouy** [comment]
Sorry, for some reason I had selected "AirzoneCloud" instead of "New AirzoneCloud" in the dropdown list in the settings... Using "New AirzoneCloud" works! Sorry for the noise...
