### ISSUE TITLE
Homebridge-Hue 0.14.0: config.json: effects: invalid key

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#1190]
#### Issue
Since updating to 0.14.0 I can see the following warning in the log after restarting the bridge, but have no idea if it impacts something:

#### Log Messages
```
[22/10/2024, 07:50:31] [Homebridge-Hue] Initializing Hue platform...
[22/10/2024, 07:50:31] [Homebridge-Hue] homebridge-hue v0.14.0, node v20.18.0, homebridge v1.8.4
[22/10/2024, 07:50:31] [Homebridge-Hue] config.json: effects: invalid key
```

#### Debug Files
[homebridge-hue.json.gz](https://github.com/user-attachments/files/17470790/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
The `effects` key in `config.json` has been removed in v0.14.0.

It was used to "Expose special effects (on supported lights) as separate services."  As this was only supported for lights exposed by deCONZ, it's no longer relevant to Homebridge Hue.  Note that the Hue bridge exposes special effects for Hue lights only over API v2.

**Comment by jostrasser** [comment]
Done, looks fine so far. Thank you!
