### ISSUE TITLE
TypeError: HueClient.isHueBridgeId is not a function at HueBridge.exposeBridge

### ISSUE THREAD

**Issue by Mupton1** [ebaauw/homebridge-hue#1195]
Getting error “TypeError: HueClient.isHueBridgeId is not a function at HueBridge.exposeBridge” after Plugin update to latest version 0.14.2

Does anyone have the same issue? 
Mine was working perfectly until update. 

Thanks!

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Damn, it looks like it picked up hb-hue-tools@1.0.2, but expects hb-hue-tools@1.0.1.  I've (re-)marked that version as latest, so it should be picked up when you re-install Homebridge Hue.

**Comment by joolz789** [comment]
Yep I had the same issue, I just rolled back to fix it for now

**Comment by ebaauw** [comment]
Fixed in v0.14.3.
