### ISSUE TITLE
Can I use this *only* for motion sensors?

### ISSUE THREAD

**Issue by zeve-zz** [ebaauw/homebridge-hue#12]
I currently have all my hue lights set up with Homekit, since they are supported out of the box.

I want to use Hue Motion Sensors, but haven't purchased because they don't work with HomeKit. I know there are other sensors available, but I'd prefer Hue ones.. I'd like to set it up to create scenes/rules using the Hue sensor. Example, detect motion with the hue sensor, set lights to X, set Nest to X. 

Can I use this plugin, to ignore all the lights, but ONLY support the Motion Sensor? I don't want any duplicate lights, etc, showing up via siri, home app, etc.

**Comment by ebaauw** [comment]
You can only enable sensors  in `config.json` and disable lights, groups, etc., see the README.  Note that this will expose all sensors to homekit, not just the motion sensors.

I think the hue motion sensors are great value for money, but the standard hue app doesn't do them justice.  I actually control my lights through manually created hue bridge rules (so they work even when homekit doesn't feel like it), any I control my Sosos speakers through homekit rules (and another homebridge plug-in, which I haven't published yet).  When I enter a room, the lights (when it's dark) and speakers turn on automatically.  Leaving a room off is a bit more complicated, as the sensor detects motion, not presence.  I'm actually using a `CLIPGenericStatus` sensor to keep a presence state and the motion sensors in the adjacent rooms / hallway to detect leaving a room.  The lights and speakers only turn off automatically (after 5 minutes) when motion detected turns off within 15 seconds of motion detected turning on in an adjacent room.
