### ISSUE TITLE
Toggle Hue Motion Sensor on/off

### ISSUE THREAD

**Issue by fraannk** [ebaauw/homebridge-hue#120]
Hi. I successfully got the plugin running and now have three different "boxes" in HomeKit, showing motion, temperature and light levels. However I'm not able to disable/toggle the sensor so that it won't register motion. Did I miss a step? 

Thanks

**Comment by ebaauw** [comment]
The sensor's `config.on` attribute is exposed to HomeKit as a custom characteristic `Enabled` (so Siri won't unintentionally disable the sensor when you ask her to turn off a room).  Unfortunately the iOS builtin Home app doesn't support custom characteristics, so you need to use another HomeKit app, like Eve.

**Comment by fraannk** [comment]
Okay, would it be possible to change this characteristic so Siri actually turns it off when turning off a room? I never turn off rooms, and I would like to have a sensor toggle switch for movie mode etc. :)

**Comment by ebaauw** [comment]
You can include `Enabled` in your Movie Mode scene using Eve and then recall the scene from Home and/or Siri.

**Comment by fraannk** [comment]
Yup, works perfectly. Thanks a lot.
