### ISSUE TITLE
Error when running `ph` command line utility

### ISSUE THREAD

**Issue by SkrilaxCZ** [ebaauw/homebridge-hue#1200]
Updated to node.js 22.10 LTS (from 20.x) but still getting this error whenever I try to run `ph` cmdline utility.

```
$ ./ph
file:///var/lib/homebridge/node_modules/homebridge-hue/node_modules/hb-hue-tools/lib/HueClient.js:659
      for (const e of response.body?.errors ?? []) {
                                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```

**Comment by ebaauw** [comment]
What file is `./ph`?  Just running `ph` without any arguments should result in:
```
$ ph
ph: error: parameter command missing
usage: ph [-hVD] [-H hostname] [-K apiKey] [-t timeout] command [argument ...]
```

What's the output of ` /usr/bin/env node` ?  Does that indeed start NodeJS v22.10.0.  By the way, the latest version is v22.11.0.

**Comment by SkrilaxCZ** [comment]
Sorry, my bad homebridge is using v22.11.0. I installed `node.js` via homebridge and kept system version as is (which is `v12.22.9`) though I understand that one is not invoked for homebridge.

`./ph` is in `/var/lib/homebridge/node_modules/.bin` which links to `/var/lib/homebridge/node_modules/homebridge-hue/cli/ph.js`

**Comment by SkrilaxCZ** [comment]
I see, because when I invoke it through cmdline, it will pick system `node.js` which will cause error. Adding `export PATH=/opt/homebridge/bin:$PATH` fixes the problem.
