### ISSUE TITLE
Hue Zones showing up as light bulbs

### ISSUE THREAD

**Issue by JakeMalis** [ebaauw/homebridge-hue#1204]
#### Issue
The 3 zones I have setup in the Hue app are also showing in Homebridge as light bulbs even though my configuration doesn't include that. How do I stop the zones (Home, Upstairs, Downstairs) from showing up as bulbs if I only want the scenes to show as switches?
<img width="1728" alt="Screenshot 2024-12-06 at 1 36 31 PM" src="https://github.com/user-attachments/assets/8e6e01db-d3ae-4647-b22e-a120b198c288">

#### Configuration
```
{
    "name": "Hue",
    "anyOn": true,
    "groups": true,
    "hosts": [
        "XXX"
    ],
    "linkButton": false,
    "nativeHomeKitLights": true,
    "nativeHomeKitSensors": true,
    "resource": false,
    "rooms": false,
    "scenes": true,
    "scenesAsSwitch": true,
    "users": {
        "XXX": "XXX"
    },
    "platform": "Hue",
    "exclude": [
        "group:87",
        "group:85"
    ]
}
```

**Comment by ebaauw** [comment]
Technically, zones are groups.  You need to expose a group to expose its associated scenes.  You can blacklist groups (without scenes) that you don’t want to expose, using a blacklist resource link, see Wiki.
