### ISSUE TITLE
Colour Temperature

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#121]
Looks like Apple silently introduced a standard `Color Temperature` characteristic in iOS 10.3, which holds the mired value.  I still need to test whether this one is supported by the builtin Home app.  I would expect Philips to use the standard characteristic eventually for their v2 bridge.

I plan to use only the standard `Color Temperature` characteristic and deprecate the `ct` setting in config.json.

**Comment by ebaauw** [comment]
The Apple standard Color Temperature characteristic is indeed supported by Home in iOS 10.3.  Made the changes to v0.5.0.

**Comment by jojost1** [comment]
What kind of effect will this have on my configuration when I don't have any lights exposed by homebridge-hue?

Will the Home-app now support setting Color Temperature of Hue White Ambience lights? Currently only supported by for example the Eve app..

**Comment by ebaauw** [comment]
> What kind of effect will this have on my configuration when I don't have any lights exposed by homebridge-hue?

None.

> Will the Home-app now support setting Color Temperature of Hue White Ambience lights? Currently only supported by for example the Eve app.

Yes.  Eve will break (sort of) as it doesn't recognise the standard Color Temperature.  It will show it anyways, but not as part of the colour setting.  I've contacted Elgato support - they were very helpful earlier, pointing me to the Nanoleaf characteristic, and I expect them to add support in some future version.

**Comment by jojost1** [comment]
Awesome. For the Home app to support the Ambience lights I have to expose them via homebridge-hue don’t I..? Either that or wait for an update from Philips officially.

Thanks for your support as always :)

**Comment by ebaauw** [comment]
Yup.  I also posted a message to the Hue developers forum, let's see if Philips react...

**Comment by jojost1** [comment]
Any reaction to the forum post? :)

**Comment by ebaauw** [comment]
No, see https://developers.meethue.com/content/color-temperature.
