### ISSUE TITLE
[Hue] config.json: warning: ct: deprecated

### ISSUE THREAD

**Issue by DJay79** [ebaauw/homebridge-hue#122]
Hi and thanks for the update and the fantastic ongoing development and improvement of this great plugin.

I just want to inform, with the latest v0.5.0 I got this warning at homebridge start.

[2017-6-10 08:53:09] [Hue] Initializing Hue platform...
[2017-6-10 08:53:09] [Hue] config.json: warning: ct: deprecated
[2017-6-10 08:53:09] [Hue] homebridge-hue v0.5.0, node v7.10.0, homebridge v0.4.20

But it seems homebridge is running.

**Comment by ebaauw** [comment]
The warning is issued because homebridge-hue no longer uses `ct` in config.json, see the [release notes](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.5.0).  Just remove that key from config.json to get rid of the warning.
