### ISSUE TITLE
Correct startup message

### ISSUE THREAD

**Issue by det-box** [ebaauw/homebridge-hue#124]
Hello,
Is it possible to clean up this message?

Here the log:
Jun 11 10:19:04 PM hbridge2 homebridge [24962]: [2017-6-11 10:19:04] [Hue] Hue room: / lights / 9: warning: unknown light model {'state': {'on' : False, 'bri': 1, 'ct': 385, 'alert': 'none', 'colormode': 'ct', 'reachable': true}, 'type': 'color temperature light' ':' Dresden elektronik ',' uniqueid ':' 0:21:2e:ff:ff:00:ed:33-0a ',' , 'Swversion': '020F. 20100 0CF'}
Jun 11 10:19:04 hbridge2 homebridge [24962]: [2017-6-11 10:19:04] [Hue] Hue Room: / lights / 10: warning: unknown light model {'stat e': {'on ':' Color ',' color ',' color ':' color ',' color ',' color ' Name ':' kitchen right ',' modelid ':' FLS-CT ',' manufacturername ':' dresden elektronik ',' uniqueid ':' 00:21:2e:ff:ff:00:ec:ec-0a' , 'Swversion': '020F. 2010 00CF'}
 
Thanks

**Comment by ebaauw** [comment]
The warning is because you've got lights that aren't (yet) known to homebridge-hue.  I can add them to the list of known lights, no problem.  However, it looks like the log messages are corrupted.  Could you please start homebridge manually and caputure the output by
```bash
  homebridge -D > output.log 2>&1
```
and than attach output.log?

**Comment by det-box** [comment]
Hello,
Here the desired LOG.
[output.zip](https://github.com/ebaauw/homebridge-hue/files/1066395/output.zip)

Thanks

**Comment by ebaauw** [comment]
Thanks.  Added the FLS-CT to v0.5.1.  Do you know what range of colour temperature they support?

**Comment by det-box** [comment]
The FLS-CT is for warm white / cold white LED stripes.

https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/wireless-ballasts/fls-ct/?L=1&cHash=c9c902ccdb43164696acccf81b62b2bd
Thanks

**Comment by det-box** [comment]
Hello,
Is unfortunately not yet ok.
├── homebridge-hue@0.5.1

`Jun 11 18:39:39 hbridge2 homebridge[5817]: [2017-6-11 18:39:39] [Hue] Hue Stube: /lights/9: warning: unknown light model {"state":{"on":false,"bri":1,"ct":385,"alert":"none","colormode":"ct","reachable":true},"type":"Color temperature light","name":"Flur Schrank","modelid":"FLS-CT","manufacturername":"dresden elektronik","uniqueid":"00:21:2e:ff:ff:00:ed:33-0a","swversion":"020F.201000CF"}
Jun 11 18:39:39 hbridge2 homebridge[5817]: [2017-6-11 18:39:39] [Hue] Hue Stube: /lights/10: warning: unknown light model {"state":{"on":false,"bri":1,"ct":371,"alert":"none","colormode":"ct","reachable":true},"type":"Color temperature light","name":"Küche rechts","modelid":"FLS-CT","manufacturername":"dresden elektronik","uniqueid":"00:21:2e:ff:ff:00:ec:ec-0a","swversion":"020F.201000CF"}`

**Comment by ebaauw** [comment]
My bad.  Could you try v0.5.2?

**Comment by det-box** [comment]
With v0. 5. 2 tested, everything in order

Super Thank you, can be closed
