### ISSUE TITLE
Can custom Characteristic or Service work in iPhone Homekit??

### ISSUE THREAD

**Issue by rench** [ebaauw/homebridge-hue#127]
Hello ebaauw, I see your project using a custom Characteristic or Service, and I also try to customize some Characteristic such as the display unit for kWh. But these are not shown in the iphone's Homkit software. Can these custom attributes be used in Homekit? How do I need to work?

**Comment by ebaauw** [comment]
They work in HomeKit, but not in the iOS builtin Home app, nor in Siri.  You need another HomeKit app, like Eve, see README.

**Comment by rench** [comment]
Ok, I see. IPhone comes with the family App does not support. Thank you
