### ISSUE TITLE
Warning unknown light model

### ISSUE THREAD

**Issue by ashdwells** [ebaauw/homebridge-hue#128]
The light works but this error comes up during boot process

Philips hue: /lights/9: warning: unknown light model {"state":{"on":false,"bri":203,"alert":"select","reachable":true},"type":"Dimmable light","name":"Dining Room Main","modelid":"RB 165","manufacturername":"innr","uniqueid":"00:15:8d:00:01:74:2d:e6-01","swversion":"2.1"}

**Comment by ebaauw** [comment]
I'll add it to the list of known lights.

**Comment by ashdwells** [comment]
Thanks

**Comment by ebaauw** [comment]
v0.5.3 should no longer issue the warning.
