### ISSUE TITLE
Homebridge restarts require unlocking deCONZ

### ISSUE THREAD

**Issue by grover** [ebaauw/homebridge-hue#132]
Not sure where to file the bug, if here or with the deCONZ REST API... Anyways: I'm using the latest homebridge-hue (0.5.5) and tried various deCONZ version (now at 2.04.49) on a RPi Zero W and every time I restart homebridge I have to unlock the gateway and homebridge-hue tries to create a new user. Even if I add this new user to config.json and immediately restart homebridge I have to unlock again.

Is this expected behavior? Where's the user database stored and which steps do I need to take to ensure smooth homebridge restarts?

**Comment by ebaauw** [comment]
homebridge-hue should use the username in config.json.  Could you please attach your config.json (with the user added), so I can check it?  Could you also run `homebridge -D` from the command line and attach the output here?

The users are stored on the gateway, under the resource `/api/<username>/config/whitelist`.
