### ISSUE TITLE
Remove temperature sensor

### ISSUE THREAD

**Issue by leonbarrett** [ebaauw/homebridge-hue#133]
I have other devices that I wish to use for the temperature. Is there a way to disable the temperature service?

**Comment by ebaauw** [comment]
Yes, specify `"excludeSensorTypes": ["ZLLTemperature"]` in config..json.

**Comment by leonbarrett** [comment]
That's great, is there a list of all types anywhere please? Thanks

**Comment by ebaauw** [comment]
It's the Hue API sensor **type**, as documented on the [Hue developers portal](https://developers.meethue.com/documentation/supported-sensors).  You need to register (free) to view these pages.

Alternatively, UTSL: https://github.com/ebaauw/homebridge-hue/blob/master/lib/HueSensor.js#L84.
