### ISSUE TITLE
Can't find bridgeid/username & trouble with UUID

### ISSUE THREAD

**Issue by matthieudu06** [ebaauw/homebridge-hue#136]
Hi,

I've tried to install homebridge-hue, but when I first launched it, I wasn't able to find the bridgeid/username automatically as you describe in the installation.

Here's the result (for the first time and still the same) : 

> [2017-7-24 19:27:07] Loaded plugin: homebridge-dash
> [2017-7-24 19:27:08] Registering accessory 'homebridge-dash.Dash'
> [2017-7-24 19:27:08] ---
> [2017-7-24 19:27:09] Loaded plugin: homebridge-hue
> [2017-7-24 19:27:09] Registering platform 'homebridge-hue.Hue'
> [2017-7-24 19:27:09] ---
> [2017-7-24 19:27:09] Loaded plugin: homebridge-tado-ac
> [2017-7-24 19:27:09] Registering accessory 'homebridge-tado-ac.TADO'
> [2017-7-24 19:27:09] ---
> [2017-7-24 19:27:09] Loaded config.json with 3 accessories and 1 platforms.
> [2017-7-24 19:27:09] ---
> [2017-7-24 19:27:09] Loading 1 platforms...
> [2017-7-24 19:27:09] [Hue homebridge] Initializing Hue platform...
> [2017-7-24 19:27:09] [Hue homebridge] homebridge-hue v0.5.7, node v6.11.0, homebridge v0.4.22
> [2017-7-24 19:27:09] Loading 3 accessories...
> [2017-7-24 19:27:09] [Dash bureau] Initializing Dash accessory...
> [2017-7-24 19:27:09] [Clim] Initializing TADO accessory...
> [2017-7-24 19:27:10] [Clim] Minimum setpoint 16
> [2017-7-24 19:27:10] [Clim] Maximum setpoint 30
> [2017-7-24 19:27:10] [Clim] Initializing TADO accessory...
> [2017-7-24 19:27:10] [Clim] Minimum setpoint 16
> [2017-7-24 19:27:10] [Clim] Maximum setpoint 30
> /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:225
>       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
>       ^
> 
> Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: ff590fda-293c-4aab-b158-ff18b6360cd4
>     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:225:13)
>     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:269:18)
>     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)

Here's the config file (without the bridge identifiant and username because I can't find them) : 

> "platforms": [
>       {
>         "platform": "Hue",
>         "name": "Hue homebridge",
>         "users": {
>         "001788FFFExxxxxx": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>         "001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
>         },
>         "sensors": true,
>         "excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
>         "lights": true
>       }
>     ]
> }

Thanks for your help...

**Comment by ebaauw** [comment]
Did you install any other plugins at the same time?  It looks like homebridge crashes before homebridge-hue has had the time to find your bridge.  The crash is because the same accessory (UUID) is being registered twice, while loading _accessory_ plugins (in `Server._loadAccessories`).  Homebridge-hue is a _platform_ plugin.  Also, you should see a message that homebridge-hue found your bridge, before it creates any accessories.

**Comment by matthieudu06** [comment]
Yes, you were right ! I had too devis renamed today as “Clim” that was the problem. Everything works fine now. Another question, what are the other sensor types that we can exclude ? For example I want to disable “Hue ambiant light sensor” what should I use ? Can you make a list of all the sensor type that we can exclude ?

Thanks !

**Comment by matthieudu06** [comment]
Yes, you were right ! I had too devices renamed today as “Clim” that was the problem. Everything works fine now. Thanks for your quick reply !
