### ISSUE TITLE
Error "Cannot add a bridged Accessory with the same UUID"

### ISSUE THREAD

**Issue by tkropf** [ebaauw/homebridge-hue#14]
Hi,
when using homebridge-hue I get the following error message:
throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);

I assume this is due to the fact that I have a non Philips hue light which registers always twice: 
[2016-11-03 20:51:13] [Hue] Philips hue: found 3 accessories
[2016-11-03 20:51:17] [Hue] Initializing platform accessory 'Philips hue'...
[2016-11-03 20:51:17] [Hue] Initializing platform accessory 'Treppenhaus-LED-Streifen'...
[2016-11-03 20:51:17] [Hue] Initializing platform accessory 'Dimmable light 1'...

However, the last two accessories are just one light! It is a RGBW-LED stripe module which simultaneously drives an RGB and a white (W) channel. The RGB part and the W part register as separate lights. It works without problems using the Philips Hue app. However, this light is not accessible via Homekit - hence my hope was to get it working via hombridge.
Link to the product web site below.

Any suggestion how to circuvent this error?
Thanks!
Thomas

https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/wireless-ballasts/fls-pp-lp/?L=1&cHash=c9c902ccdb43164696acccf81b62b2bd

**Comment by ebaauw** [comment]
Hi Thomas,

Thanks for your post.  The good new: I think I can fix this; the bad news: I need a little help from you.

I suspect this is a bug in homebridge-hue, related to issue #2: for Zigbee devices, I now base the Accessory UUID on the Zigbee ID (xx:xx:xx:xx:xx:xx:xx:xx).  I suspect both bridge lights have the same Zigbee ID but a different suffix in the `uniqueid` field (xx:xx:xx:xx:xx:xx:xx:xx-yy).  They did the same for the hue motion sensor, which registers as three different sensors on the bridge.

Could you please do a GET of /lights on your bridge using its CLIP API debugger and post the output here?  See [http://www.developers.meethue.com/documentation/getting-started](http://www.developers.meethue.com/documentation/getting-started).  I don't have any Dresden Electronic lamps myself and I need to see how the hue bridge sees them.

**Comment by tkropf** [comment]
Hi Erik @ebauwee

Thanks for the quick response. Much appreciated. Below is the complete result from the GET /lights command. The potential culprit is "8" and "9". And it seems your suspicion is right.

{
	"1": {
		"state": {
			"on": true,
			"bri": 254,
			"hue": 8904,
			"sat": 106,
			"effect": "none",
			"xy": [
				0.4647,
				0.3824
			],
			"ct": 375,
			"alert": "none",
			"colormode": "xy",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Stehlampe",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:e0:ab:7d-0b",
		"swversion": "5.23.1.13452"
	},
	"2": {
		"state": {
			"on": true,
			"bri": 20,
			"hue": 136,
			"sat": 254,
			"effect": "none",
			"xy": [
				0.6736,
				0.323
			],
			"ct": 500,
			"alert": "none",
			"colormode": "xy",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Dekolampe",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:d6:07:ad-0b",
		"swversion": "5.23.1.13452"
	},
	"3": {
		"state": {
			"on": false,
			"bri": 217,
			"hue": 12662,
			"sat": 223,
			"effect": "none",
			"xy": [
				0.5235,
				0.4138
			],
			"ct": 492,
			"alert": "none",
			"colormode": "xy",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Nachttisch Thomas",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:e0:ab:a4-0b",
		"swversion": "5.23.1.13452"
	},
	"4": {
		"state": {
			"on": true,
			"bri": 63,
			"alert": "none",
			"reachable": true
		},
		"type": "Dimmable light",
		"name": "Leselampe",
		"modelid": "LWB004",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:db:70:0b-0b",
		"swversion": "5.38.2.19136"
	},
	"5": {
		"state": {
			"on": true,
			"bri": 107,
			"alert": "none",
			"reachable": true
		},
		"type": "Dimmable plug-in unit",
		"name": "Leselämpchen",
		"modelid": "LWL001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:2e:b5:e1-0c",
		"swversion": "1.0.1.4591"
	},
	"6": {
		"state": {
			"on": false,
			"bri": 145,
			"alert": "none",
			"reachable": false
		},
		"type": "Dimmable plug-in unit",
		"name": "Weihnachtsgirlande außen",
		"modelid": "LWL001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:2e:ba:d8-0c",
		"swversion": "1.0.1.4591"
	},
	"7": {
		"state": {
			"on": false,
			"bri": 254,
			"alert": "none",
			"reachable": false
		},
		"type": "Dimmable plug-in unit",
		"name": "Weihnachtsgirlande Dach",
		"modelid": "LWL001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:2e:b5:c2-0c",
		"swversion": "1.0.1.4591"
	},
	"8": {
		"state": {
			"on": false,
			"bri": 1,
			"hue": 6024,
			"sat": 241,
			"effect": "none",
			"xy": [
				0.5053,
				0.4153
			],
			"ct": 454,
			"alert": "none",
			"colormode": "ct",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Treppenhaus-LED-Streifen",
		"modelid": "FLS-PP3",
		"manufacturername": "dresden elektronik",
		"uniqueid": "00:21:2e:ff:ff:00:9f:4f-0a",
		"swversion": "020E.201000A0"
	},
	"9": {
		"state": {
			"on": false,
			"bri": 203,
			"alert": "none",
			"reachable": true
		},
		"type": "Dimmable light",
		"name": "Dimmable light 1",
		"modelid": "FLS-PP3 White",
		"manufacturername": "dresden elektronik",
		"uniqueid": "00:21:2e:ff:ff:00:9f:4f-0b",
		"swversion": "020E.201000A0"
	},
	"10": {
		"state": {
			"on": true,
			"bri": 33,
			"hue": 9111,
			"sat": 254,
			"effect": "none",
			"xy": [
				0.5803,
				0.3918
			],
			"ct": 153,
			"alert": "none",
			"colormode": "xy",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Deckenlampe",
		"modelid": "LCT007",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:10:5a:58:fd-0b",
		"swversion": "5.50.1.19085"
	},
	"11": {
		"state": {
			"on": false,
			"bri": 254,
			"alert": "none",
			"reachable": true
		},
		"type": "Dimmable light",
		"name": "Hue white lamp 1",
		"modelid": "LWB004",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:db:63:50-0b",
		"swversion": "5.38.2.19136"
	}
}

**Comment by ebaauw** [comment]
I just published version 0.0.11 which should address this issue.  The Dresden Electronic light should show as two homekit accessories, each with their own Lightbulb service. Eventually, I want to make this one homekit accessory with two Lightbulb services, but the changes for that are more elaborate (see also issue #4).
@tkropf please let me know if this works for you.  For something different, if you don't mind me asking: are lamps 5, 6, 7 the Philips Living White Plugs?  I've been trying to get some of these, but they seem to be sold out permanently.

**Comment by tkropf** [comment]
Erik,

Thank for your quick update. Unfortunately, I am currently on a business trip to China. I will be back next Friday and will immediately try out your fix (which I would love to do right now!). 

And yes, 5,6,7 are Living White Plugs. I bought them about 3 years ago as they are really useful to connect 'legacy lamps'.  When I wanted to buy some more about a year ago I also was also unable to get them anywhere. It really is a shame that Philips has decided to stop selling them.

Thomas

**Comment by tkropf** [comment]
Erik,

I was looking forward the whole week to return home and to try out your fix.
And...

Ta-dahhhh! 

..it works :-)

@ebaauw Thank you so much!

Thomas

**Comment by ebaauw** [comment]
Hi Thomas, @tkropf 
Good to hear!  I'll close this issue.
