### ISSUE TITLE
Bridge Link Button

### ISSUE THREAD

**Issue by DanielWeeber** [ebaauw/homebridge-hue#140]
Hey,

loving your plugin so far. Just having one small problem. If I do not want to see the Link Button of the Bridge in HomeKit I'll set "linkButton" to false.
This will change the button to "Not supported" instead of removing it.

I run homebridge in a docker container, so I already removed accessory/persist folders and so on - I even started a new fresh container. 

Any idea?

Greets!

**Comment by ebaauw** [comment]
You cannot delete the bridge service, as homebridge-hue needs it.  When using another HomeKit app, like Eve, you can change the heartrate using this service, but the iOS builtin Home app doesn't support custom services.

**Comment by DanielWeeber** [comment]
I'm not talking about the bridge itself, I'm only talking about the (physical) Linkbutton on the bridge.

**Comment by ebaauw** [comment]
There's two different HomeKit accessories:
- A HomeKit bridge accessory (with the triangle symbol), that homebridge provides to expose the accessories created by plugins;
- A regular HomeKit accessory that homebridge-hue provides for each Hue bridge it exposes.  This accessory contains a custom service, that holds, a.o., `Heartrate`, `Last Updated`, `Transition Time` and will hold the bridge username in future.  Home displays this as Not Supported.  When you set `linkButton`, homebridge-hue creates a second `Stateless Programmable Switch` service for this accessory, which Home does support.

**Comment by DanielWeeber** [comment]
Now I got it. Thanks for the explanation.

Is it needed though? I frankly do not care if Heartrate, Last Updated, Transition Time is available in (non-supported) HomeKit.

Anyhow I greatly appreciate your also realtime answer to my question.

**Comment by ebaauw** [comment]
Once homebridge-hue uses dynamic platform accessories (see issue #4), this accessory will hold the bridge username, so you no longer need to edit config.json.  Eventually I want to move most config.json settings here, so they can be changed dynamically from HomeKit, but I need to refactor homebridge-hue to use dynamic accessories first.  That's a big one...

**Comment by ebaauw** [comment]
> but it is still popping up in my homekit logs every 5 secs.

Are you running `homebridge -D`?  Then you would expect a debug message for each command homebridge-hue sends to the Hue bridge.  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by paqpaqpaq** [comment]
> > but it is still popping up in my homekit logs every 5 secs.
> 
> Are you running `homebridge -D`? Then you would expect a debug message for each command homebridge-hue sends to the Hue bridge. See https://github.com/ebaauw/homebridge-hue#debug-log-file.

I don't mean the homebridge log, that is fine.
e.g. the homekit log in Controlle for homekit app.
Really nice feature to debug. 

The bridge shows up at the set heartrate, as "last updated"
When I set it to 30 sec (highest) it will do so. After a reboot it is back on 5 again.

**Comment by ebaauw** [comment]
> the homekit log in Controller for homekit app.

You'll have to take that up with de developer of that app.

> When I set it to 30 sec (highest) it will do so. After a reboot it is back on 5 again.

Unfortunately, with the current design of homebridge-hue, I cannot persist the setting between homebridge restarts.  This will be changed after moving to homebridge's dynamic platform accessories model, see #4.

Note that when setting the heartrate to 30, it will take up to 30 seconds before a change made on the Hue bridge (e.g. through a Hue app, through a rule, or by pressing the button on the OSRAM outlet) is reflected in HomeKit.
