### ISSUE TITLE
Connecting to the bridge

### ISSUE THREAD

**Issue by alexlab963** [ebaauw/homebridge-hue#142]
Hey,

I am trying to use my hue to tap to control other devices, however i am having trouble connecting homebridhe-hue to my bridge, and while this is a noob question could you please elaborate on how to establish the connection between the plugin and the bridge?

**Comment by ebaauw** [comment]
homebridge-hue should find your bridge through the meethue portal and/or UPnP.  When it does, it logs a message to the homebridge output/log, asking you to press the link button, so it can create a username.  After that, it should connect to the Hue bridge and find the relevant resources (based on the settings in config.json).  It also logs a message to edit config.json and add the username it just created.

In case your bridge cannot be found, you can skip the discovery and specify the hostname or IP address of the bridge in config.json.
