### ISSUE TITLE
RPI startup

### ISSUE THREAD

**Issue by andygroves** [ebaauw/homebridge-hue#145]
Dear Sirs, 
Please can you help, I am i total novice with the RPI homebridge, i currently use the homebridge with lightwave RF, Harmony and limitless LED plug ins, and they work well, this was set up for me.
I have installed the hue plug in hopefully correctly and added the script in in the middle of the other plugs in the JSON file, but the HomeBridge will not start.
I have checked the JSON file in a JSON validation utility at it appears to verify.

Please can you offer any pointer, im sure i can send you a beer, for your efforts.

best regards,

Andy G

**Comment by ebaauw** [comment]
Make sure homebridge runs when you start it from the command line.  From a terminal run `homebridge`.  You should see something like:
```
[8/7/2017, 1:44:04 PM] Loaded plugin: homebridge-hue
[8/7/2017, 1:44:04 PM] Registering platform 'homebridge-hue.Hue'
[8/7/2017, 1:44:04 PM] ---
[8/7/2017, 1:44:04 PM] Loaded config.json with 0 accessories and 1 platforms.
[8/7/2017, 1:44:04 PM] ---
[8/7/2017, 1:44:04 PM] Loading 1 platforms...
[8/7/2017, 1:44:04 PM] [Hue] Initializing Hue platform...
[8/7/2017, 1:44:04 PM] [Hue] homebridge-hue v0.5.12, node v6.11.1, homebridge v0.4.22
```
If not, fix that before trying to run homebridge on startup.  See the [homebridge WiKi](https://github.com/nfarina/homebridge/wiki/Running-Homebridge-on-a-Raspberry-Pi) how to start homebridge on boot on a Raspberry.

**Comment by andygroves** [comment]
Dear Sir,

I will check read about homebridge when I get home tonight.

My homebridge was set up by an internet friend called Grant, he set it up for me for Lightwave RF, not sure if your familiar with LWRF.

He set it up to auto start of boot up or reset.

Ive seen this error before the cpu goes 0 to 25 to 0 to 25 each time it reads the JSON and I assume crashes out.

Do I need to change anything in users.

"platforms": [
    {
      "platform": "Hue",
      "name": "Hue",
      "users": {
        "001788FFFExxxxxx": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
      },
      "sensors": true,
      "excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
      "lights": true
    }
  ]


If I post my JSON file would you be able to offer some pointers.

If your on pay pal im sure I can fire you over a beer, for  a little help.

Best regards,

Andy

**Comment by ebaauw** [comment]
OK, if you already have homebridge running on boot, don't change that.  If you just install homebridge-hue (`npm -g install homebridge-hue`), homebridge should find it.  Next, you need to edit your existing config.json (in `~/.homebridge`) and add the homebridge-hue part to the existing "platforms" array.  It should look like:
```
{
  "bridge": {
    ...
  },
  "platforms": [
    {
      "platform": "LightWaveRF",
      "name": "LightWaveRF",
      ...
    },
    {
      "platform": "Hue",
      "name": "Hue",
      ...
    }
  ]
}
```
