### ISSUE TITLE
Unknown Light

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-hue#146]
Hello,

first thanks for this awesome plugin.
Maybe you can add this to the known lights list, it's the Osram Gardenspot white only version:

`Aug 08 23:48:33 raspberrypi homebridge[10946]: [2017-8-8 23:48:33] [Hue] Philips hue: /lights/18: warning: unknown light model {"state":{"on":true,"bri":89,"alert":"select","reachable":true},"type":"Dimmable light","name":"Beleuchtung Balkon","modelid":"Gardenspot W","manufacturername":"OSRAM","uniqueid":"84:18:26:00:00:d9:da:47-03","swversion":"V1.04.12"}`

Then I have one question, I have occasionally popping up the following message in the log:

`Aug 09 00:01:00 raspberrypi homebridge[10946]: [2017-8-9 00:01:00] [Hue] Beleuchtung Terrasse: set homekit status fault from 0 to 1`

and then some time later (like a minute or so)

`homebridge[10946]: [2017-8-9 00:02:10] [Hue] Beleuchtung Terrasse: set homekit status fault from 1 to 0`

What does it mean?

Thanks
Anatol

**Comment by ebaauw** [comment]
homebridge-hue sets `Status Fault` to match the `state.reachable` attribute the Hue bridge reports for the light.  The iOS built-in Home app ignores this, but it's visible in Eve (see #144).

Note that `state.reachable` doesn't reflect whether the light is currently reachable, just whether the Hue bridge received a response the last time it polled the light.

**Comment by ebaauw** [comment]
The Gardenspot W should be recognised in v0.5.14.

**Comment by CooperCGN** [comment]
Ah thanks, I've been reading through most of the closed topics a few days ago so I actually missed that one when posting yesterday.
going to check later for the update. :)
