### ISSUE TITLE
Does this plugin support Ikea bulbs?

### ISSUE THREAD

**Issue by iCarl** [ebaauw/homebridge-hue#147]
Since the new Ikea bulbs is compatible with the Hue-hub if they have been upgraded to the latest firmware, do you need to use this plugin or does it work out of the box?
https://developers.meethue.com/content/philips-hue-and-ikea-tr%C3%A5dfri?page=2

**Comment by ebaauw** [comment]
With the new firmware, the IKEA bulbs pair with the Hue bridge and can be used by any Hue app.

As the Hue bridge only exposes Philips lights to HomeKit, you'll need homebridge-hue to expose the IKEA lights to HomeKit, just as for the Hue motion sensor or dimmer switch.

**Comment by adekka** [comment]
Is there a special trick for the Ikea lights? I tried it yesterday with no result.

**Comment by ebaauw** [comment]
What did you try?

**Comment by adekka** [comment]
- Of course the firmware update :)
- reset of the ikea bulb by power off and on 6 times
- find bulb via hue app

The hue hub is ~5 meters away of the bulb

2017-08-13 9:33 GMT+02:00 Erik Baauw <notifications@github.com>:

**Comment by ebaauw** [comment]
Did you double-check that the bulb reports firmware 1.2.21x?

I haven't actually yet tried it myself, but I read it can be done: https://developers.meethue.com/comment/3701#comment-3701.

You might need to touchlink the IKEA bulb with the Hue bridge, before the bridge finds the bulb.  Hold the powered-on bulb next to the Hue bridge and PUT `{"touchlink": true}` to `/config` through the Hue API, or, in Eve, use the `Touchlink` characteristic in bridge accessory provided by homebridge-hue.  Then, search for new lights from the Hue app as before.

**Comment by ebaauw** [comment]
I tested it today, and had no problem pairing the updated `TRADFRI bulb E27 WS opal 980lm` (v1.2.217) to my 2nd gen Hue bridge (v1707040932).  I didn't need to touchlink it or anything.

Note that you need to power cycle the bulb, after pressing `Search` in the Hue app.  I think this is needed for all lights, except for the Philips Hue lights.

**Comment by adekka** [comment]
I did some testing with the power cycle but no luck. How do I get to know the firmware? I do not own a IKEA hub :(

**Comment by ebaauw** [comment]
Then how did you upgrade the firmware?

**Comment by adekka** [comment]
I thought that you did the same as you never mentioned the hub. Now I see
that I made a wrong assumption ;)

2017-08-15 20:14 GMT+02:00 Erik Baauw <notifications@github.com>:

**Comment by ebaauw** [comment]
I never mentioned the IKEA hub, because I don't have one.  I updated the IKEA bulb firmware through deCONZ.
