### ISSUE TITLE
Hue Tap

### ISSUE THREAD

**Issue by PsynapseX** [ebaauw/homebridge-hue#148]
Hello,

I successfully added my Hue Taps to Homekit but when I press any of the buttons, the command for the button does not execute (I set a Hue lightbulb to each of the Hue Tap' 4 buttons in the stock iOS Home app).

I see the animation in the Home app after I press one of the Tap's buttons, but the light will not turn on.
What could be the issue?
Thank you

**Comment by ebaauw** [comment]
Either the rules haven't been synched to your HomeKit Hub (typically your AppleTV) or the HomeKit hub has lost the connection to homebridge.  See https://GitHub.com/ebaauw/homebridge-hue/issues/118#issuecomment-311798530.
