### ISSUE TITLE
Questions about Hue Accessories (Motion & Dimmer Switches)

### ISSUE THREAD

**Issue by JJJ** [ebaauw/homebridge-hue#149]
Hello, and thanks a ton for maintaining this Homebridge plugin. It's pretty neat, and seems to work really well considering how fragile the rest of the entire setup process all is.

In my experience, it looks like the dimmer buttons always brighten or dim the lights in the room they are setup in the native Hue app to control. It's also a little weird to configure the "Long Press" actions in the Home app, because there is no "Continue to brighten these lights regardless of the current brightness level" type of command.

* The Hue app gives the top button 5 different tap commands, but the Home app only has 4 buttons exposed. How do these compete with each other?
* How does the Home app interpret the 2 dimmer buttons?
* Is the "Off" button always just for turning stuff off?
* What other types of button controls are available via the Home app?
* The iConnectHue app was able to program the dimmer switches in other ways, like the duration of fade, and the percentage of brightness each press would cause. Can the Home app expose similar settings?
* What's the preferred way to setup the dimmer switches so that there isn't confusion regarding which app is setting up what commands? Is there a way to completely disable one or the other, without causing a mismatch of configurations between them?

----

Regarding the Hue motion detectors, it's great having these setup in the Home app to trigger other automations outside of Hue accessories. Again, the Hue app exposes a very limited capacity for defining times, to the point of not really being very useful, but HomeKit allows Sunrise/Sunset (which is variable, and the most logical IMO.) What's the best way to configure these in the Hue app so they don't mess with the settings in the Home app?

Any other tips/tricks/pointers?

**Comment by ebaauw** [comment]
The Hue dimmer switch and Hue motion sensor are pretty straightforward devices.  They only report what they sense: button actions, motion, light level, and temperature.  The official Hue app, and other apps using the Hue API, like iConnectHue, setup rules on the Hue bridge for these devices.  These rules specify how the system reacts to the events from the switches and/or sensors.

Homebridge-hue "just" exposes the switches and sensors to HomeKit.  In HomeKit, you can setup rules as well, called automations.  Again these automations determine how the system reacts to events from the switches and/or sensors.

In my personal opinion, the Hue bridge rules created by the Hue app are crap.  The rules mechanism on the Hue bridge, however, is very powerful.  More powerful and more reliable than HomeKit automations, but, of course, limited to interacting with devices connected to the Hue bridge.  You can create your own rules using the Hue API to unlock fully the potential of the Hue system.  See the Wiki for some examples.

> The Hue app gives the top button 5 different tap commands, but the Home app only has 4 buttons exposed. How do these compete with each other?

The Hue app creates a CLIPGenericStatus "sensor" (variable) that keepms track of how many times you've pressed the _On_ button.  It then creates five rules to react differently on the same button press, depending on the value of this variable, updating the variable at the same time.  By exposing CLIP sensors to HomeKit, you could create the same logic in HomeKit automations.  Note however that the iOS builtin Home app doesn't support `Status`, so you would need another HomeKit app for that.

> How does the Home app interpret the 2 dimmer buttons?
> Is the "Off" button always just for turning stuff off?
> What other types of button controls are available via the Home app?

Homebridge-hue exposes the four buttons on the Hue dimmer switch to HomeKit, issuing _Short Press_ or _Long Press_ events to HomeKit.  Natively, Home reacts by flasing the tile of the switch, or, if you're on the details page, the corresponding action line.  It's up to you to define actions for each if these events.

> The iConnectHue app was able to program the dimmer switches in other ways, like the duration of fade, and the percentage of brightness each press would cause. Can the Home app expose similar settings?

iConnectHue creates more sophicticated Hue bridge rules than the Hue app to achieve this.  Homebridge-hue exposes the underlying attributes to HomeKit, so you could create the same functionality in HomeKit.  Again, you'd need another HomeKit app for `Transition Time`.

> What's the preferred way to setup the dimmer switches so that there isn't confusion regarding which app is setting up what commands? Is there a way to completely disable one or the other, without causing a mismatch of configurations between them?

As I said, by default HomeKit doesn't do anything with the events from the Hue dimmer switch or motion sensor.  You can disable Hue bridge rules through the API, or delete them altogether.  When you configure homebridge-hue to expose rules, you can even disable them from HomeKit (but again, not from the Home app), but currently only the first 90 or so rules are exposed.
