### ISSUE TITLE
Issue with Hue Dimming Switches

### ISSUE THREAD

**Issue by Nastra888** [ebaauw/homebridge-hue#151]
Hello Erik,

I need your help, but am not sure if it is related to your plugin. Since the switches are indicated by your plugin, it could be connected to many?

It is a problem with my Hue dimming switch which I have programmed in the Apple Home App. The problem has existed since yesterday. I updated yesterday to node@8.4.0 and homebridge@0.4.25.

But I am not sure about whether it has something to do with it, since the switches are still reacting just not as they should actually.

Since it is relatively hard to describe and my English is not the best, I hope you can follow me anyway and have many ideas.

Problem Description:

The buttons on the switch only react in a fixed order to a kind of loop that starts with holding down the key and then reacts to the key once. It is no longer possible to switch on the light when pressing the button for the first time. It is mandatory to press and hold key 1 until the loudspeaker is switched on, thus pressing button 1 once and the light is switched on.

I have observed in the Apple Home App the switches since there after pressing a button it is symbolically displayed. Also there is no reaction to see if just push button 1 once. It is mandatory to press and hold down key 1 before.

In the log of the Homebridge, any operation is displayed, regardless of whether it is pressed or held down.

Measures taken so far have been unsuccessful:

- Hue Bridge disconnected from electricity
- Homebridge restart and reboot
- Plugin downgrade to 0.5.15 now back to 0.5.18
- Hue and HomeKit switches removed and newly added

The only thing I can think of is the complete Hue Bridge to reseten but which is very much work.

Here are some technical specifications for my Homebridge:

- node@8.4.0
- homebridge@0.4.25.
- npm@5.3.0

I thank you already times with you and look forward to your answer.

Greeting Nastra

**Comment by ebaauw** [comment]
It would seem like homebridge-hue is incompatible with homebridge@0.4.25.  I'm seeing the same under homebridge@0.4.25, but not under homebridge@0.4.22.

**Comment by Nastra888** [comment]
You can fix the problem for your plugin? Or do I need to downgrade Homebridge?

**Comment by alexlewer** [comment]
@ebaauw May be related to this? https://github.com/KhaosT/HAP-NodeJS/issues/486

**Comment by ebaauw** [comment]
> May be related to this? KhaosT/HAP-NodeJS#486

No.  It's this one: https://github.com/KhaosT/HAP-NodeJS/issues/488.  I'll see if I can patch this in homebridge-hue for now.

**Comment by Nastra888** [comment]
Wonderful! It all works again! Great thanks for the quick help!
