### ISSUE TITLE
Unkown light model: innr RB 185

### ISSUE THREAD

**Issue by Yardco** [ebaauw/homebridge-hue#152]
Hello, 

is it possible to add the following light to homebridge hue? light works but error comes up when starting homebridge:

`Philips hue: /lights/1: warning: unknown light model {"state":{"on":true,"bri":127,"hue":3514,"sat":248,"effect":"none","xy":[0.5857,0.3839],"ct":500,"alert":"select","colormode":"xy","reachable":true},"type":"Extended color light","name":"Extended color light 1","modelid":"RB 185 C","manufacturername":"innr","uniqueid":"","swversion":"2.0"}`

**Comment by ebaauw** [comment]
Yes, I'll add it.  Would you feel comfortable running a shell script to determine the range of colors and colour temperatures it supports?  It's `ph_light_values` from https://github.com/ebaauw/ph.sh.  I haven't yet integrated this functionality in homebridge-hue...

**Comment by Yardco** [comment]
Yeah no problem.

getting the following when running `ph_light_values`:

`{
  "manufacturer": "innr",
  "modelid": "RB 185 C",
  "type": "Extended color light",
  "bri": true,
  "ct": {
    "min": 153,
    "max": 500
  },
  "xy": {
    "r": [
      1.0000,
      0.0000
    ],
    "g": [
      0.0000,
      1.0000
    ],
    "b": [
      0.0000,
      0.0000
    ]
  }
}
`

**Comment by ebaauw** [comment]
Thanks, @Yardco.

I'm afraid `ph_light_value` didn't run correctly, due to a bug.  Could I trouble you once more and ask you to download the latest version from GitHub and try again?  Thanks.

**Comment by Yardco** [comment]
@ebaauw no problem at all, happy to help

`{
  "manufacturer": "innr",
  "modelid": "RB 185 C",
  "type": "Extended color light",
  "bri": true,
  "ct": {
    "min": 153,
    "max": 500
  },
  "xy": {
    "r": [
      0.8817,
      0.1033
    ],
    "g": [
      0.2204,
      0.7758
    ],
    "b": [
      0.0551,
      0.1940
    ]
  }
}
`

**Comment by Yardco** [comment]
Updated the homebridge-hue package, but the lamp still isn't recognized. Should I do something extra to make homebridge recognize the lamp?

**Comment by ebaauw** [comment]
That's not good.  Does it still show the same message?

**Comment by Yardco** [comment]
Ah no problem. Thanks for the fast response!

**Comment by ebaauw** [comment]
Should be fixes in v0.5.23.

**Comment by Yardco** [comment]
Yes, error isn't displayed any longer. Thanks!
