### ISSUE TITLE
Connecting Xiaomi Mi Sensor

### ISSUE THREAD

**Issue by Bankaifan** [ebaauw/homebridge-hue#154]
Hi,

If I want to use the xiaomi gear, do I Need the Mi-Gateway? And how do I add that gear?

**Comment by ebaauw** [comment]
You need a deCONZ gateway, as that provides a Hue-compatible API.  Once the Xiaomi devices have paired with the deCONZ gateway, homebridge-hue picks them up.

**Comment by AntiHeld889** [comment]
Hello, I have a window/door sensor from Xiaomi paired with the deCONZ gateway. Homebridge shows only the light and my tradfri remote. Could you help me?

{
	"platform": "Hue",
	"name": "RaspBee",
	"host": "127.0.0.1",
	"users": {
	"00212EFFFF01102E": "C3D454629B"
	},
	"sensors": true,
	"lights": true,
	"philipsLights": true
	},

**Comment by ebaauw** [comment]
Has the sensor been registered by the REST API plugin?  It should create a resource under `/sensors`.  If you run`homebridge -D`, homebridge-hue issues a debug message for each resource.

If there's no resource, deCONZ probably hasn't read the manufacturer and/or model.  In the _Cluster Info_ panel of the deCONZ GUI, try reading the sensors  _Basic_ cluster attributes, while moving the magnet to make sure the sensor is awake.  It might take a few attempts.  Open the networkonce this succeeded, and the resource is created.

If there is a resource, but homebridge-hue doesn't recognise it, please post the log of `homebridge -D` (see **Troubleshooting** in the README).

**Comment by AntiHeld889** [comment]
Now it's working, thanks! There was no resource in the REST API plugin.
