### ISSUE TITLE
3rd party light using osram tech (e.g. EGLO Fornes)

### ISSUE THREAD

**Issue by Kugelfang666** [ebaauw/homebridge-hue#155]
I recently pick d up a lamp from a manufacturer named EGLO. They produce smart light compatible with Osrams lightify system. In fact within the device there is a small box from osram actually controlling the leds. I added the light (EGLO Fornes Smart) to my Hue bridge and so far everything is working. Also homebridge-hue works as intended but always classifies this as an unknown device type. Would it be possible to add these lamps to the list of known devices?

**Comment by ebaauw** [comment]
Sure, could you post the exact message homebridge-hue issues?

**Comment by Kugelfang666** [comment]
Hi, thanks for the quick reply! The log says: 

Hue Bridge One: /lights/31: warning: unknown light model {"state":{"on":true,"bri":204,"ct":370,"alert":"none","colormode":"ct","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Color temperature light","name":"Esstisch","modelid":"Control box TW","manufacturername":"OSRAM","uniqueid":"84:18:26:00:00:0a:be:40-03","swversion":"V1.04.90"

**Comment by ebaauw** [comment]
Should be recognised in v0.5.23.

**Comment by Kugelfang666** [comment]
Great! Thanks a lot, this works now!
