### ISSUE TITLE
Hue tap button pressed (icon bounces in HomeKit app) but the scene is not triggered

### ISSUE THREAD

**Issue by iandronowicz** [ebaauw/homebridge-hue#156]
First of all, great work!.

Randomly it happens that I press a hue tap button and no action is taken. I open up the HomeKit app and I see the hue tap icon bouncing when I press a button but the scene I configured takes no effect. Im guessing it has something to do with HomeKit more than with homebridge-hue or even home bridge... but still.... maybe it happens to others.

thanks in advance

**Comment by ebaauw** [comment]
Either the rules haven't been synched to your HomeKit Hub (typically your AppleTV) or the HomeKit hub has lost the connection to homebridge. See https://GitHub.com/ebaauw/homebridge-hue/issues/118#issuecomment-311798530.

**Comment by iandronowicz** [comment]
I've just tried it again (without doing anything at all) and started working. That's why I said randomly! Ok great thanks I'll look up to it.

**Comment by iandronowicz** [comment]
You were right, neither the hue tap nor the hue dimmer switch worked, the gray icon did flash on the apple home app but no action was taken. I turned off the HomeKit option on both of my apple tvs and turned it back on and both remotes started worked. Thanks!
