### ISSUE TITLE
Xiaomi Door Sensor - Cannot read property 'modelid' of undefined

### ISSUE THREAD

**Issue by stefan-kaiser** [ebaauw/homebridge-hue#161]
Hello,
I have bought a new Xiaomi Door Sensor and connected successfully to deconz.
In HomeKit I haven't found the sensor. After some troubleshooting I found the entry "Cannot read property 'modelid' of undefined" in the homebridge log.
I'm running the latest version of homebridge und homebridge-hue.
I have started homebridge as a separate process with only hombebridge-hue configured and attached the logfile.
I wasn't able to attach the "dump" because I don't know, how to add the "Identify" setting.

Using the REST-API I can successfull read sensors state.

I hope you can help me.

Kind regards
Stefan

[log.txt](https://github.com/ebaauw/homebridge-hue/files/1289818/log.txt)

**Comment by ebaauw** [comment]
Oops, looks like a typo on my part.  Will be fixed in next version, hopefully later today.

**Comment by stefan-kaiser** [comment]
Thank you very much for your quick response!

**Comment by ebaauw** [comment]
Should be fixed in v0.5.30.

**Comment by stefan-kaiser** [comment]
It's working like a charm, thanks!
