### ISSUE TITLE
mqtt not used to send messages to domoticz coming from Hue plug-in

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue#162]
Hi, a week ago, I added mqtt to my domoticz. Since then, my homekit updates in realtime when something changes on domoticz and, vice versa, when I switch on or off a domoticz switch from my Home app, it reacts instantly. Really appreciated the upgrade brought by mqtt.

However, it seems mqtt is not used when the switch order comes from a Hue Dimmer, via the Hue Plug-in. In that case, it is still sent the old way, not via mqtt. This leads to slowdowns and sometimes no response at all.

I can't say if this is due to the Hue Plug-in or the [eDomoticz](https://github.com/PatchworkBoy/homebridge-edomoticz/) one, I'm then posting this issue on both plug-in repositories.

**Comment by ebaauw** [comment]
> Hi, a week ago, I added mqtt to my domoticz. Since then, my homekit updates in realtime when something changes on domoticz and, vice versa, when I switch on or off a domoticz switch from my Home app, it reacts instantly. Really appreciated the upgrade brought by mqtt.

So you switched on mqtt between domiticz and the domoticz homebridge plugin?

> However, it seems mqtt is not used when the switch order comes from a Hue Dimmer, via the Hue Plug-in.

Of course not.  What makes you think it would?  Homebridge-hue talks to the Hue bridge using the Hue API.  Even if that would support mqtt (which it doesn't) changing the protocol between domiticz and the domoticz plugin doesn't change the protocol between the Hue bridge and homebridge-hue.

> In that case, it is still sent the old way, not via mqtt. This leads to slowdowns and sometimes no response at all.

Worse: it's not sent at all.  The Hue API does not provide push notifications, so homebridge-hue needs to poll the bridge to detect button presses (just as any Hue app).  You might want to try different settings of `heartrate` to increase the polling rate, but typically the Hue bridge won't handle a faster rate than once every 2 seconds.

**Comment by ooii** [comment]
>Hi, a week ago, I added mqtt to my domoticz. Since then, my homekit updates in realtime when something changes on domoticz and, vice versa, when I switch on or off a domoticz switch from my Home app, it reacts instantly. Really appreciated the upgrade brought by mqtt.
>>So you switched on mqtt between domiticz and the domoticz homebridge plugin?

Yes.
>However, it seems mqtt is not used when the switch order comes from a Hue Dimmer, via the Hue Plug-in.
>>Of course not. What makes you think it would? 

My (probably wrong) understanding of how it works. I thought that when a button is pressed on the dimmer, then (1) when the hue plugin polls the bridge and if it detects a button press, it informs homekit of that and then (2) homekit triggers the actions associated (in my case, switching on/off the concerned domoticz switch). And, still in my understanding, when homekit triggers this domoticz switch, it does it with mqtt.

>>In that case, it is still sent the old way, not via mqtt. This leads to slowdowns and sometimes no response at all.
>Worse: it's not sent at all. The Hue API does not provide push notifications, so homebridge-hue needs to poll the bridge to detect button presses (just as any Hue app). You might want to try different settings of heartrate to increase the polling rate, but typically the Hue bridge won't handle a faster rate than once every 2 seconds.

It is already set to 2 seconds and the reaction time is acceptable (≤ 2 seconds).

**Comment by ebaauw** [comment]
>  I thought that when a button is pressed on the dimmer, then (1) when the hue plugin polls the bridge and if it detects a button press, it informs homekit of that and then (2) homekit triggers the actions associated (in my case, switching on/off the concerned domoticz switch).

Correct.

> And, still in my understanding, when homekit triggers this domoticz switch, it does it with mqtt.

HomeKit triggers the homebridge/the domoticz plugin over HAP.  It's up to the domoticz pluging to inform domoticz using the appropriate protocol.  If you set the domoticz switch manually in HomeKit, does the plugin update domoticz over mqtt?  Maybe the mqtt is used only one-way, from domoticz to its client app (i.c. the plugin), but not from the app (i.c. the plugin) to domoticz?

**Comment by ooii** [comment]
>>And, still in my understanding, when homekit triggers this domoticz switch, it does it with mqtt.

>HomeKit triggers homebridge/the domoticz plugin over HAP. It's up to the domoticz pluging to inform domoticz using the appropriate protocol. If you set the domoticz switch manually in HomeKit, does the plugin update domoticz over mqtt? 

Yes.

>Maybe the mqtt is used only one-way, from domoticz to its client app (i.c. the plugin), but not from the app (i.c. the plugin) to domoticz?

I don't think so (cf. my previous answer). 
So, asking the question on domoticz plugin is also appropriate.

**Comment by ebaauw** [comment]
> > If you set the domoticz switch manually in HomeKit, does the plugin update domoticz over mqtt?

> Yes.

And when you activate the HomeKit scene (which is called from the Hue dimmer switch action and sets the domoticz switch) manually?  How many characteristics do you set from this scene?  HomeKit pushes all these changes in one go - it took me quite some effort to throttle the requests to the Hue bridge, not to swamp it when a HomeKit scene is recalled.

**Comment by ooii** [comment]
Sorry for the delay to answer.

I configured my dimmer to switch on/off a [Fibaro double switch](https://www.amazon.fr/Fibaro-FGS-222-Interrupteur-relais-868/dp/B00WH0S8F0/ref=sr_1_1?ie=UTF8&qid=1505510051&sr=8-1&keywords=fgS-221), not specific scenes. So, if I well understood, I cannot activate a HomeKit scene manually.

Here is my setting:
- Button 1: both switches on
- Button 2: switche1 on, switch 2 off
- Button 3: switche1 off, switch 2 on
- Button 4: both switches off

I'd say 2 characteristics are set for each button press.

**Comment by ooii** [comment]
Hi @ebaauw,
I don't know if you're aware of that or not but Hue is officially adding accessories to HomeKit this October. According to [this tweeter thread](https://twitter.com/elgarne/status/909793224377688069), motion sensor, dimmer and tap will be supported natively but, from I understood, not the dim up/down buttons.

**Comment by ebaauw** [comment]
Yeah, I saw the annoncement.  The obvious advantage is that they can push changes directly over HAP - no need to poll the bridge.  We'll have to see what they'll expose to HomeKit and how.  If they're smart, they took a look at homebridge-hue ;-)

**Comment by ooii** [comment]
>The obvious advantage is that they can push changes directly over HAP - no need to poll the bridge. 

Sure.

>If they're smart, they took a look at homebridge-hue ;-)

Let's cross our fingers.

**Comment by ebaauw** [comment]
@ooii is there anything we need to change in homebridge-hue or can we close this issue?

**Comment by ooii** [comment]
Absolutely.

**Comment by ooii** [comment]
Just to mention that the ios hue app has been updated. Most features of the plugin are provided. 
Missing ones are long and short presses. Only "press" is mentioned. Temperature and ambient light are also exposed.
I'll test this evening how it reacts when a button is pressed, if it is similar to polling or not.
Also, curious to see if attributing an action to a button will overwrite the natural behavior.

**Comment by ebaauw** [comment]
The gen2 Hue bridge exposes the Hue accessories very similar to homebridge-hue:
- The motion sensor is a single HomeKit accessory with different services for Motion Sensor, Ambient Light Sensor, Temperature Sensor, Battery, and Accessory Information.  For the sensors, only the Motion Detected (state.presence), Current Ambient Light Level (state.lightlevel), Current Temperature (state.temperature) and Status Active (config.on) are provided.  No custom characteristics for state.lastupdated, state.dark, state.daylight, nor the other config attributes.  The Home app reacts instantly to motion;
- The Hue dimmer switch is a single HomeKit accessory with a Stateless Programmable Switch service for each button, and services for Battery, Accessory Information, and a (custom?) service for Label Namespace.  The Switch services provide Programmable Switch Event and Label Index (just as homebridge-hue).  The (custom?) service for Label Index just provides that - no Status Active for config.on.  Indeed, only support for Short Press is provided - pity.  The Home app reacts instantly to button presses (double pressing results in two successive "blinks").
- The Hue tap is similar to the Hue dimmer, except for the Battery service and Label Namespace - which is now set to dots.  Again, the Home app reacts instantly to button presses.

> I'll test this evening how it reacts when a button is pressed, if it is similar to polling or not.

As I expected, no polling delay.  The Hue bridge pushes the changes directly over HAP to HomeKit clients.  I'm inclined to say that with a gen2 Hue bridge, you'd better use the native HomeKit support for the accessories than homebridge-hue, especially of you're only using Siri and/or the Apple Home app.  You'd only need homebridge-hue for HomeKit support for non-Hue lights, long presses on the dimmer, the custom characteristics for state and config attributes, and the button on the bridge.   And, of course, when you only have a gen1 bridge.

> Also, curious to see if attributing an action to a button will overwrite the natural behavior.

It would seem that the Hue app removes the accessory setup when you select _Configure in Apple Home app_, but you can re-configure it afterwards.

They also seem to have mode some changes to the Hue app:
- It no longer needs a resourcelinks resource to show the motion sensor;
- The on/off switch for the motion sensor now acts on config.on of all three sensor resources, not just of the ZLLPresence resource.

**Comment by ooii** [comment]
> You'd only need homebridge-hue for HomeKit support for non-Hue lights, long presses on the dimmer, the custom characteristics for state and config attributes, and the button on the bridge.

I'll keep using it at least for enabling/disabling the sensors.

**Comment by ooii** [comment]
@ebaauw I have one question regarding the battery level of dimmers and sensors. I have a dozen of dimmers and 7 sensors and all of them are 100% of battery while they're running for more than a year now. I'm wondering if the provided value is wrong or if Philips has magically found a way to not drain batteries.

**Comment by ebaauw** [comment]
I understand that measuring battery capacity is inherently unreliable, especialy for button cells.  They’ll probably drop quickly when the battery is almost depleted.
