### ISSUE TITLE
Xiaomi accessories to hue Bridge?

### ISSUE THREAD

**Issue by TonyFeestneus** [ebaauw/homebridge-hue#165]
So are you saying all these xiaomi sensors can be paired with the Hue Bridge then? Without the Xiaomi gateway? How did you find that out and how to pull it off?

**Comment by deanlyoung** [comment]
I believe they require the Deconz Zigbee hub. This is kind of a Hue/Deconz plug-in, not just Hue.

**Comment by TonyFeestneus** [comment]
Ah, good to know, thanks for the info.
