### ISSUE TITLE
Unrecognised inner bulbs

### ISSUE THREAD

**Issue by Lorccan** [ebaauw/homebridge-hue#166]
I have the following inner bulbs that are not recognised: SL 110 N, SL 110 M, SL 110 W:

Sep 22 13:15:59 milos homebridge[3300]: [9/22/2017, 1:15:59 PM] [Hue] Philips hue: /lights/31: warning: unknown light model {"state":{"on":false,"bri":254,"alert":"none","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Dimmable light","name":"zzz","modelid":"SL 110 M","manufacturername":"innr","uniqueid":"00:15:8d:00:00:5b:6a:b2-01","swversion":"0x10000c46"}

Sep 22 13:15:59 milos homebridge[3300]: [9/22/2017, 1:15:59 PM] [Hue] Philips hue: /lights/32:
warning: unknown light model {"state":{"on":false,"bri":254,"alert":"none","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Dimmable light","name":"yyy","modelid":"SL 110 W","manufacturername":"innr","uniqueid":"00:15:8d:00:00:76:88:f1-01","swversion":"0x10000c46"}

Sep 22 13:15:59 milos homebridge[3300]: [9/22/2017, 1:15:59 PM] [Hue] Philips hue: /lights/34: warning: unknown light model {"state":{"on":false,"bri":254,"alert":"none","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Dimmable light","name":"xxx","modelid":"SL 110 N","manufacturername":"innr","uniqueid":"00:15:8d:00:00:76:89:8f-01","swversion":"0x10000c46"}
Sep 22 13:15:59 milos homebridge[3300]: [9/22/2017, 1:15:59 PM] [Hue] Philips hue: /lights/36:

**Comment by ebaauw** [comment]
Thanks, I'll whitelist them in the next release.

**Comment by Lorccan** [comment]
This appears to prevent the plugin from loading correctly.  Is that right?  Is there any workaround please?

**Comment by ebaauw** [comment]
No, these are just a warning messages.  If homebridge isn’t starting, something else is wrong.  Please post / attach the entire log/output of `homebridge -D`

**Comment by Lorccan** [comment]
Sorry.  I tried rebooting and it all launched OK.

**Comment by ebaauw** [comment]
The should be recognised in v0.5.32.

**Comment by Lorccan** [comment]
Sorry for delay in responding.  Tested and all OK.  Thanks.
