### ISSUE TITLE
Sensors - slow updates

### ISSUE THREAD

**Issue by LP0101** [ebaauw/homebridge-hue#167]
I'm running the homebridge server on a Linux box. Using the first sample configuration, I'm having wildly varying results with the lights. Sometimes, they trigger almost instantly, other times it will take up to 10 seconds for motion to turn them on.

Is there any way to configure the polling rate, or anything similar, to more reliably trigger the sensors?

**Comment by deanlyoung** [comment]
Which version hub do you have (v1.round or v2.squircle)?
How far apart are your devices and/or what sort of building materials in the walls/floors?
