### ISSUE TITLE
[Question] Hue Motion Sensor, green indicator LED

### ISSUE THREAD

**Issue by DJay79** [ebaauw/homebridge-hue#168]
Hi there. I bought my first Hue Motion Sensor so please excuse when I ask stupid questions. :/
I added the Motion Sensor with the hue app but disabled, switched it off there.
Running the homepridge-hue Plugin on my Raspberry Pi the new Sensor was detected immediately with motion, light and temperature which is great.
I configured a new routine in the Eve App and everything seems to work when motion is detected.
But the green indicator LED on the hue Motion Sensor did not work. I only notice this when I'm in the original hue App and configure the sensor intensity.
What am I doing wrong? 
Thanks in advance for you help and reply.

**Comment by ebaauw** [comment]
> But the green indicator LED on the hue Motion Sensor did not work.

By default, this indication is off.  I don't think you can turn it on using the Hue app.  Using the Hue API, you need to set the ZLLPresence sensor's `config.ledindication` to `true`.  Sorry, no support for this yet in homebridge-hue, so you need to use the CLIP API debugger or `ph.sh`:
```bash
ph_put /sensors/xx/config '{"ledindication": true}'
```
> I only notice this when I'm in the original hue App and configure the sensor intensity.

While calibrating the sensor, the Hue app sets `config.usertest`, which enables the LED indication and makes sure the sensor doesn't go to sleep.  The sensor switches `config.usertest` off automatically after two minutes.  The sensitivity is set to `config.sensitivity`.  En/disabling the sensor in the Hue app changes `config.on`.  The motion sensor still works when this is set, but the resources on the Hue bridge aren't updated, effectively disabling the sensor.

> I configured a new routine in the Eve App and everything seems to work when motion is detected.

Yeah, luckily Apple fixed the bug in tvOS 11 (issue #118).

**Comment by DJay79** [comment]
Thanks @ebaauw 
I have to ask something else. As mentioned, hue motion sensor is new to me.
Is it correct that I do have to turn hue motion sensor "on" in the hue App to work with homebridge-hue? In the hue App itself all three option with "do nothing". Is that correct? 🤔
Thanks again.

**Comment by ebaauw** [comment]
The Hue app just creates rules on the Hue bridge, to turn on or off the lights when motion is detected below a certain ambiant lightlevel.  If you use HomeKit automations instead, you might not need the Hue bridge rules.  homebridge-hue just looks at the sensor resource - it doesn’t need any bridge rules.

**Comment by DJay79** [comment]
Thank you @ebaauw . But the device itself has to be turned "on" in the hue App, although I don't use it HomeKit with the Hue App or anything else like your Plugin? Correct? 
![img_1062](https://user-images.githubusercontent.com/3874239/30799057-e5d76080-a1db-11e7-9907-6e59711e9676.PNG)
![img_1063](https://user-images.githubusercontent.com/3874239/30799058-e605a576-a1db-11e7-905e-511064f0f1e0.PNG)
For the moment thats.

**Comment by ebaauw** [comment]
Yes, that’s what I meant with en/disabling the sensor.  The switch on the first screen links to `config.on`.

**Comment by DJay79** [comment]
So I understand that everything is okay the way I did it. ;) 
One really last question... In the Eve App I see the Light lux sensor which is gerat.
I configured a rule for the bathroom that when motion is detected my speaker turns on.
A second rule when no motion is detected turn the speaker off. I tried to do something more usable not just turning off. Because when under the shower no motion is detected. So I used the lux as a requirement when <X (because the light is off) only then turn off when no motion is detected. But that was not working very reliable because the bathroom door was open or something else.

Any tip how to configure my scenario the best way? When entering the bathroom speaker on and when no movement is detected longer than xx minutes or lux is <X ?? Something like this.
I noticed that the lux is not updating very reliable even when clearly the light from 76.5 lux is switched off so it must be a significant lower lux. But the sensor only updates the lux only when movement is detected. But when I leave the bathroom and then switch off the light there is no motion in the bathroom and lux didn't update. 🙄😬

**Comment by ebaauw** [comment]
> One really last question

Don't make any promises you cannot keep ;-)

> I noticed that the lux is not updating very reliable even when clearly the light from 76.5 lux is switched off so it must be a significant lower lux. But the sensor only updates the lux only when movement is detected.

The sensor wakes up when motion is (no longer) detected to report this change to the Hue bridge.  Changes to light level or temperature don't wakeup the sensor once it's asleep, so it looks like it only updates these when motion has been detected.  If you monitor the sensor's _Last Updated_, you'll see that it wakes up spontaneously every five minutes to update the lightlevel and temperature (and presence, actually).  So the lights should be turned off in your case, but it might take up to five minutes.

> Any tip how to configure my scenario the best way? 

The real issue is that you want to turn off the speaker when you leave the bathroom, not when motion is no longer detected.  I implemented this using Hue bridge rules, the motion sensor in the bathroom and and the motion sensor in the connecting room/hallway, in combination with a CLIPGenericStatus sensor that keeps the bathroom state.  See https://github.com/ebaauw/ph.sh.

> But when I leave the bathroom and then switch off the light

Huh?!  You want to switch off your speaker automatically, but the lights manually?  That is so 20th century.

**Comment by DJay79** [comment]
> Huh?! You want to switch off your speaker automatically, but the lights manually? That is so 20th century.

🤣 You are so right about the light in the bathroom. 

And as always, thanks for all the great explanation. 👍🏻

**Comment by patrickharris** [comment]
Sorry to hijack the thread, but do you know if the 'heartbeat' can be started and the cache file accessed via the http API? I can't see any reference to it - only for the sdk.

**Comment by ebaauw** [comment]
I never used the Hue SDK, only the REST API.  Afaik, the SDK wraps around the REST API, so whatever you do in the SDK (caching, heartbeat) will not be visible in the REST API.  Better ask these kind of questions on the Hue development forum (https://developers.meethue.com/forum).

**Comment by patrickharris** [comment]
Thanks!
