### ISSUE TITLE
Unknown light mode Ikea GU10

### ISSUE THREAD

**Issue by Nastra888** [ebaauw/homebridge-hue#173]
Hi Erik, 

i get the following error message with my new Ikea GU10 spotlights. Can you take it with you?

Okt 01 17:29:25 Server homebridge[1587]: [2017-10-1 17:29:25] [Lampenbridge Universal Abstellkammer] Lampenbridge Abs: /lights/26: warning: unknown light model {"state":{"on":true,"bri":254,"alert":"none","reachable":false},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Dimmable light","name":"Decke 6 Flur","modelid":"TRADFRI bulb GU10 W 400lm","manufacturername":"IKEA of Sweden","uniqueid":"00:0b:57:ff:fe:a7:d8:9b-01","swversion":"1.2.214"}

**Comment by ebaauw** [comment]
I'll add it to the list of known lights.

**Comment by Nastra888** [comment]
Thank You👍

**Comment by ebaauw** [comment]
In v0.5.33.

**Comment by toshibochan** [comment]
Ikea light bulb can be added hue bridge?

**Comment by ebaauw** [comment]
Yes, once the bulb has the latest firmware.

**Comment by toshibochan** [comment]
Ikea bulb can be used in HomeKit without ikea hub and homebridge-hue?

**Comment by ebaauw** [comment]
Once it’s connected to the Hue bridge, homebridge-hue can expose it to HomeKit.  The Hue bridge only exposes Hue lights to HomeKit, no lights from other manufacturers.

You might need an IKEA gateway to update the bulb’s firmware, though.  I’m not sure if the bulbs currently for sale have the latest firmware.  This weekend, I bought a colour bulb with remote and a standalone dimmer at the local IKEA store.  The colour bulb was already at a firmware that allows it to connect to the Hue bridge, but both the remote and dimmer were still on old firmware.
