### ISSUE TITLE
Trådfri lights without color show colour-wheel

### ISSUE THREAD

**Issue by jsve** [ebaauw/homebridge-hue#175]
TRÅDFRI bulbs that are just temperatures of white (like the E14 WS opal 400) get reported with characteristics hue and saturation. This is not actually true and confuses the interface in the "home" app, which shows the colour-wheel even though that is not applicable.

![img_0951](https://user-images.githubusercontent.com/9053945/31463935-0edfb6de-aed0-11e7-8733-bb83c1c10142.PNG)

EDIT: I'm using the latest plugin and homebridge version. Also connecting to the lights via ConBee

**Comment by ebaauw** [comment]
> TRÅDFRI bulbs that are just temperatures of white (like the E14 WS opal 400) get reported with characteristics hue and saturation.

I don't think so.  Did you double-check using another HomeKit app?   It looks like a bug in the Home app.

I just saw the same for my E27 white spectrum bulb, using Apple's Home app on iOS 11.0.3.  And now it only shows Temperature. Afaik, I didn't change anything.  homebridge-hue exposes just the Colour Temperature characteristic, as it should - double checked in Eve and Matthias' Home app.

**Comment by jsve** [comment]
![765ec7eb-7d9f-47ee-b6fe-39daa283ee59](https://user-images.githubusercontent.com/9053945/31467939-10a09162-aedc-11e7-859e-804edb8722be.jpeg)
![4281382d-81dd-4b5e-9355-53d53d94677b](https://user-images.githubusercontent.com/9053945/31467941-10c3369a-aedc-11e7-877a-cb48ad32c154.jpeg)

**Comment by ebaauw** [comment]
Thanks!  I’d like to see how deCONZ exposes the light.  Could you do a `ph_get /lights/2` and post the output?  Or alternatively, in Eve, do an Identify of the deCONZ accessory and attach the dump of the gateway state here.

**Comment by jsve** [comment]
Not sure how to do the “ph_get” or “dump the gateway state”. Could you elaborate?

I’m on version 2.04.81.

**Comment by ebaauw** [comment]
See **Troubleshooting** in the README: In Eve, select the accessory for the deCONZ gateway (the one with the Heartrate).  Then press the [ID] button in the upper right corner.  homebridge-hue will now dump the full gateway state (masking passwords and other sensitive info) into a JSON file in your ~/.homebridge directory.

![image-1](https://user-images.githubusercontent.com/22179355/31506485-d2ce63fe-af77-11e7-9478-90d282239e88.jpg)

You should be able to see this in the homebridge log:
```
[10/12/2017, 5:28:54 PM] [Hue] pi2: identify
[10/12/2017, 5:28:54 PM] [Hue] pi2: dumping masked state to /home/pi/.homebridge/pi2.json
```

**Comment by jsve** [comment]
{
	"config": {
		"UTC": "2017-10-15T15:29:58",
		"apiversion": "1.0.4",
		"backup": {
			"errorcode": 0,
			"status": "idle"
		},
		"bridgeid": "xxxxxxFFFExxxxxx",
		"datastoreversion": "60",
		"dhcp": true,
		"factorynew": false,
		"gateway": "xxx.xxx.xxx.xxx",
		"internetservices": {
			"remoteaccess": "disconnected"
		},
		"ipaddress": "xxx.xxx.xxx.xxx",
		"linkbutton": false,
		"localtime": "2017-10-15T17:29:58",
		"mac": "xx:xx:xx:xx:xx:xx",
		"modelid": "deCONZ",
		"name": "RaspBee-GW",
		"netmask": "255.255.255.0",
		"networkopenduration": 60,
		"panid": 10241,
		"portalconnection": "disconnected",
		"portalservices": false,
		"portalstate": {
			"communication": "disconnected",
			"incoming": false,
			"outgoing": false,
			"signedon": false
		},
		"proxyaddress": "none",
		"proxyport": 0,
		"replacesbridgeid": null,
		"starterkitid": "",
		"swupdate": {
			"checkforupdate": false,
			"devicetypes": {
				"bridge": false,
				"lights": [],
				"sensors": []
			},
			"notify": false,
			"text": "",
			"updatestate": 0,
			"url": ""
		},
		"swversion": "2.04.81",
		"timeformat": "24h",
		"timezone": "Europe/Stockholm\n",
		"uuid": "5a9ff3b8-53ab-46f5-8d8d-64fe1db60055",
		"websocketnotifyall": true,
		"websocketport": 8080,
		"whitelist": {
			"xxxxxxxxx1": {
				"create date": "2017-10-11T19:29:54",
				"last use date": "2017-10-15T07:03:33",
				"name": "homebridge-hue#homebridger"
			},
			"xxxxxxxxx2": {
				"create date": "2017-01-22T11:38:23",
				"last use date": "2017-03-27T19:37:21",
				"name": "insomnia"
			},
			"xxxxxxxxx3": {
				"create date": "2017-01-15T14:41:36",
				"last use date": "2017-01-15T14:41:36",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxxx4": {
				"create date": "2017-10-11T19:27:01",
				"last use date": "2017-10-11T19:27:36",
				"name": "homebridge-hue#homebridger"
			},
			"xxxxxxxxx5": {
				"create date": "2017-10-11T21:39:05",
				"last use date": "2017-10-15T07:33:36",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxxx6": {
				"create date": "2017-01-15T12:19:47",
				"last use date": "2017-01-15T13:10:32",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxxx7": {
				"create date": "2017-01-15T14:36:02",
				"last use date": "2017-01-15T15:45:18",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxxx8": {
				"create date": "2017-01-15T11:32:26",
				"last use date": "2017-01-15T12:21:49",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxxx9": {
				"create date": "2017-10-15T07:33:34",
				"last use date": "2017-10-15T15:29:58",
				"name": "homebridge-hue#homebridger"
			},
			"xxxxxxxx10": {
				"create date": "2017-01-15T12:23:52",
				"last use date": "2017-01-15T13:10:38",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx11": {
				"create date": "2017-01-15T11:24:30",
				"last use date": "2017-01-15T12:22:00",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx12": {
				"create date": "2017-01-15T11:33:20",
				"last use date": "2017-01-15T12:21:02",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx13": {
				"create date": "2017-01-15T15:44:33",
				"last use date": "2017-01-15T15:45:03",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx14": {
				"create date": "2017-03-28T17:00:43",
				"last use date": "2017-03-28T17:00:48",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx15": {
				"create date": "2017-10-11T18:18:11",
				"last use date": "2017-10-15T15:04:45",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx16": {
				"create date": "2017-10-15T14:52:44",
				"last use date": "2017-10-15T14:56:40",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx17": {
				"create date": "2017-01-15T12:19:38",
				"last use date": "2017-01-15T12:19:44",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx18": {
				"create date": "2017-01-18T20:28:31",
				"last use date": "2017-01-18T20:52:02",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx19": {
				"create date": "2017-01-15T13:24:54",
				"last use date": "2017-01-23T20:45:38",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx20": {
				"create date": "2017-01-23T20:29:41",
				"last use date": "2017-03-29T19:58:54",
				"name": "deCONZ WebApp"
			},
			"xxxxxxxx21": {
				"create date": "2017-01-15T12:23:05",
				"last use date": "2017-01-15T12:23:47",
				"name": "deCONZ WebApp"
			}
		},
		"wifi": "not-installed",
		"wifiappw": "",
		"wifichannel": "1",
		"wifiip": "192.168.8.1",
		"wifiname": "Not set",
		"wifitype": "accesspoint",
		"zigbeechannel": 15
	},
	"groups": {
		"1": {
			"action": {
				"bri": 127,
				"colormode": "hs",
				"ct": 0,
				"effect": "none",
				"hue": 0,
				"on": false,
				"sat": 127,
				"xy": [
					0,
					0
				]
			},
			"devicemembership": [],
			"etag": "b22481ff9bc0eef9ace48bf163681e16",
			"hidden": false,
			"id": "1",
			"lights": [
				"2"
			],
			"lightsequence": [
				"3"
			],
			"multideviceids": [],
			"name": "Fönsterlampor, kök",
			"scenes": [
				{
					"id": "1",
					"name": "Natta",
					"transitiontime": 0
				}
			],
			"state": {
				"any_on": true
			},
			"type": "LightGroup"
		},
		"2": {
			"action": {
				"bri": 127,
				"colormode": "hs",
				"ct": 0,
				"effect": "none",
				"hue": 0,
				"on": false,
				"sat": 127,
				"xy": [
					0,
					0
				]
			},
			"devicemembership": [],
			"etag": "544ae80a73c73fca57302b04852995ec",
			"hidden": false,
			"id": "2",
			"lights": [],
			"lightsequence": [],
			"multideviceids": [],
			"name": "temp",
			"scenes": [],
			"state": {
				"any_on": false
			},
			"type": "LightGroup"
		},
		"13427": {
			"action": {
				"bri": 127,
				"colormode": "hs",
				"ct": 0,
				"effect": "none",
				"hue": 0,
				"on": false,
				"sat": 127,
				"xy": [
					0,
					0
				]
			},
			"devicemembership": [],
			"etag": "544ae80a73c73fca57302b04852995ec",
			"hidden": false,
			"id": "13427",
			"lights": [],
			"lightsequence": [],
			"multideviceids": [],
			"name": "Group 13427",
			"scenes": [],
			"state": {
				"any_on": false
			},
			"type": "LightGroup"
		},
		"16823": {
			"action": {
				"bri": 127,
				"colormode": "hs",
				"ct": 0,
				"effect": "none",
				"hue": 0,
				"on": false,
				"sat": 127,
				"xy": [
					0,
					0
				]
			},
			"devicemembership": [
				"3"
			],
			"etag": "544ae80a73c73fca57302b04852995ec",
			"hidden": false,
			"id": "16823",
			"lights": [],
			"lightsequence": [],
			"multideviceids": [],
			"name": "Fjärr, kök",
			"scenes": [],
			"state": {
				"any_on": false
			},
			"type": "LightGroup"
		},
		"39176": {
			"action": {
				"bri": 127,
				"colormode": "hs",
				"ct": 0,
				"effect": "none",
				"hue": 0,
				"on": false,
				"sat": 127,
				"xy": [
					0,
					0
				]
			},
			"devicemembership": [
				"5"
			],
			"etag": "5998532e09434d8d73a33b63af81f567",
			"hidden": false,
			"id": "39176",
			"lights": [],
			"lightsequence": [],
			"multideviceids": [],
			"name": "TRADFRI remote control 5",
			"scenes": [],
			"state": {
				"any_on": false
			},
			"type": "LightGroup"
		},
		"40911": {
			"action": {
				"bri": 127,
				"colormode": "hs",
				"ct": 0,
				"effect": "none",
				"hue": 0,
				"on": false,
				"sat": 127,
				"xy": [
					0,
					0
				]
			},
			"devicemembership": [],
			"etag": "544ae80a73c73fca57302b04852995ec",
			"hidden": false,
			"id": "40911",
			"lights": [],
			"lightsequence": [],
			"multideviceids": [],
			"name": "Group 40911",
			"scenes": [],
			"state": {
				"any_on": false
			},
			"type": "LightGroup"
		},
		"45234": {
			"action": {
				"bri": 127,
				"colormode": "hs",
				"ct": 0,
				"effect": "none",
				"hue": 0,
				"on": false,
				"sat": 127,
				"xy": [
					0,
					0
				]
			},
			"devicemembership": [],
			"etag": "544ae80a73c73fca57302b04852995ec",
			"hidden": false,
			"id": "45234",
			"lights": [],
			"lightsequence": [],
			"multideviceids": [],
			"name": "Group 45234",
			"scenes": [],
			"state": {
				"any_on": false
			},
			"type": "LightGroup"
		}
	},
	"lights": {
		"2": {
			"ctmax": 454,
			"ctmin": 250,
			"etag": "45dc7e7529d25201c53039e60e55052d",
			"hascolor": true,
			"manufacturername": "IKEA of Sweden",
			"modelid": "TRADFRI bulb E14 WS opal 400lm",
			"name": "Trådfri_2",
			"state": {
				"alert": "none",
				"bri": 254,
				"colormode": "ct",
				"ct": 250,
				"effect": "none",
				"hue": 0,
				"on": true,
				"reachable": true,
				"sat": 0,
				"xy": [
					0,
					0
				]
			},
			"swversion": "1.2.217",
			"type": "Dimmable light",
			"uniqueid": "00:0b:57:ff:fe:0c:9d:f3-01"
		}
	},
	"rules": {},
	"schedules": {},
	"sensors": {
		"1": {
			"config": {
				"alert": "none",
				"battery": 100,
				"on": true,
				"reachable": false
			},
			"ep": 1,
			"etag": "544ae80a73c73fca57302b04852995ec",
			"manufacturername": "IKEA of Sweden",
			"mode": 1,
			"modelid": "TRADFRI bulb E14 WS opal 400lm",
			"name": "TRADFRI bulb E14 WS opal 400lm 1",
			"state": {
				"buttonevent": -1,
				"lastupdated": "2017-01-15T07:51:42"
			},
			"swversion": "0.9.8.0-5.7.0.0",
			"type": "ZHASwitch",
			"uniqueid": "00:0b:57:ff:fe:10:e0:e3-01-1000"
		},
		"2": {
			"config": {
				"alert": "none",
				"battery": 100,
				"on": true,
				"reachable": false
			},
			"ep": 1,
			"etag": "544ae80a73c73fca57302b04852995ec",
			"manufacturername": "IKEA of Sweden",
			"mode": 1,
			"modelid": "TRADFRI bulb E14 WS opal 400lm",
			"name": "TRADFRI bulb E14 WS opal 400lm 2",
			"state": {
				"buttonevent": -1,
				"lastupdated": "2017-01-15T10:24:33"
			},
			"swversion": "0.9.8.0-5.7.0.0",
			"type": "ZHASwitch",
			"uniqueid": "00:0b:57:ff:fe:0c:9d:f3-01-1000"
		},
		"3": {
			"config": {
				"alert": "none",
				"battery": 100,
				"group": "",
				"on": true,
				"reachable": false
			},
			"ep": 1,
			"etag": "544ae80a73c73fca57302b04852995ec",
			"manufacturername": "IKEA of Sweden",
			"mode": 1,
			"modelid": "TRADFRI remote control",
			"name": "TRADFRI remote control 3",
			"state": {
				"buttonevent": -1,
				"lastupdated": "2017-01-23T17:49:56"
			},
			"swversion": "0.9.8.1-5.7.0.0",
			"type": "ZHASwitch",
			"uniqueid": "00:0b:57:ff:fe:10:91:7c-01-1000"
		},
		"4": {
			"config": {
				"alert": "none",
				"battery": 100,
				"on": true,
				"reachable": false
			},
			"ep": 1,
			"etag": "544ae80a73c73fca57302b04852995ec",
			"manufacturername": "IKEA of Sweden",
			"mode": 1,
			"modelid": "TRADFRI bulb E27 WS clear 950lm",
			"name": "TRADFRI bulb E27 WS clear 950lm 4",
			"state": {
				"buttonevent": -1,
				"lastupdated": "2017-01-23T18:01:15"
			},
			"swversion": "1.1.1.1-5.7.2.0",
			"type": "ZHASwitch",
			"uniqueid": "00:0b:57:ff:fe:1f:87:b7-01-1000"
		},
		"5": {
			"config": {
				"alert": "none",
				"battery": 87,
				"group": "39176",
				"on": true,
				"reachable": true
			},
			"ep": 1,
			"etag": "4f044c65644d79089b015a13c88c158a",
			"manufacturername": "IKEA of Sweden",
			"mode": 3,
			"modelid": "TRADFRI remote control",
			"name": "Remote control 5",
			"state": {
				"buttonevent": 1002,
				"lastupdated": "2017-10-15T15:13:39"
			},
			"swversion": "1.1.1.1-5.7.2.0",
			"type": "ZHASwitch",
			"uniqueid": "00:0b:57:ff:fe:8b:c8:9a-01-1000"
		}
	}
}

**Comment by ebaauw** [comment]
Hm there's something really funny going on in your deCONZ configuration.  Sensor resources 1, 2, and 4 have a `modelid` that corresponds to a light.  The light resource exposes `xy` (and `hue` and `sat`, so that explains why homebridge-hue exposes `Hue` and `Saturation`.  Also, it reports as _Dimmable Light_, where I would expect a _Color Temperature Light_.  Also, sensor resource 2 and the light resource have the same `uniqueid`, so they seem to refer to the same light.  They do report different firmware versions, though.  Did you update the light firmware using deCONZ?  The old firmware seems older than I've ever seen.  Do you indeed have two E14s, one E27 and two remotes?

I think you might have paired the light (back in January?), using a version of deCONZ that still exposed `xy` for colour temperature lights (see #30, point 3)?  If memory serves, the dimmable light vs colour temperature light was an issue with ZHA device types vs ZLL device types, but I cannot find the issue.  I'm afraid I have no clue about the sensor resources.

I hate to say it, but I would delete the deCONZ configuration (in `~/.local/share/dresden-elektronik/deCONZ`), and reset and re-pair every light and remote.  Alternatively, you could try and just delete the resources using the API.

**Comment by jsve** [comment]
You are probably right. I was quite early in trying out deconz stuff with Trådfri, and haven't really thought about the need to reset that. I have mainly moved over to the Trådfri gateway now, but still have a few units connected to the connbee. 

I'll try to delete the configuration in a few days.

**Comment by jsve** [comment]
Removed all files in that folder (~/.local/share/**data/**dresden-elektronik/deCONZ) and reconnected my units. Lights are now reported with only color temperature, not color.

In the process I managed to beak the connection to remotes and some of the lights, but I think we can consider this issue solved!

**Comment by ebaauw** [comment]
> ~/.local/share/**data/**dresden-elektronik/deCONZ

I guess that's also a leftover from an old version of deCONZ.
