### ISSUE TITLE
deCONZ-GW: unknown light model Classic A60 W clear - LIGHTIFY and more...

### ISSUE THREAD

**Issue by oleg77s** [ebaauw/homebridge-hue#178]
Hi
i get the following error messages:
Aren't  Osram lights  and Xiaomi Door sensor in the list of known lights?
 Loaded plugin: homebridge-hue
[10/15/2017, 6:11:23 PM] Registering platform 'homebridge-hue.Hue'
[10/15/2017, 6:11:23 PM] ---
[10/15/2017, 6:11:23 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/15/2017, 6:11:23 PM] ---
[10/15/2017, 6:11:23 PM] Loading 1 platforms...
[10/15/2017, 6:11:23 PM] [Hue] Initializing Hue platform...
[10/15/2017, 6:11:23 PM] [Hue] homebridge-hue v0.5.37, node v6.11.4, homebridge v0.4.28
[10/15/2017, 6:11:23 PM] Loading 0 accessories...
[10/15/2017, 6:11:24 PM] [Hue] deCONZ-GW: deCONZ gateway v2.4.82, api v1.0.4
[Hue] homebridge-hue v0.5.37, node v6.11.4, homebridge v0.4.28
[10/15/2017, 6:11:23 PM] Loading 0 accessories...

[Hue] deCONZ-GW: /lights/2: warning: unknown light model {"etag":"03741a300ae80dac92894b7b84e2b2e6","hascolor":false,"manufacturername":"OSRAM","modelid":"Classic A60 W clear - LIGHTIFY","name":"A60W","state":{"alert":"none","bri":127,"on":true,"reachable":true},"swversion":"V1.04.12","type":"Dimmable light","uniqueid":"84:18:26:00:00:06:c5:6d-03"} 

[Hue] deCONZ-GW: /lights/4: warning: unknown light model {"ctmax":370,"ctmin":153,"etag":"51709ddd177f8312a4ed089c5831a4cb","hascolor":true,"manufacturername":"OSRAM","modelid":"Classic A60 TW","name":"A60TW","state":{"alert":"none","bri":127,"colormode":"ct","ct":153,"on":true,"reachable":true},"swversion":"V1.04.13","type":"Color temperature light","uniqueid":"84:18:26:00:00:c9:7d:04-03"}

[Hue] deCONZ-GW: /sensors/5: warning: unknown ZHAOpenClose sensor {"config":{"on":true,"reachable":true},"ep":1,"etag":"f60c7bcf67e62df72a14dda553f8b5ef","modelid":"lumi.sensor_magnet","name":"OpenClose 5","state":{"lastupdated":"2017-10-15T15:03:45","open":false},"type":"ZHAOpenClose","uniqueid":"00:15:8d:00:00:d6:1f:6d-01-0006"}

b.r.
Oleg

**Comment by jsve** [comment]
Looks like those OSRAM lights are not in the list yet: https://github.com/ebaauw/homebridge-hue/blob/4b153a809df40457114c63fda1220ba0df4018b6/lib/HueLight.js#L395

Should be easy to add to the list, using one of the existing cases, though.

**Comment by ebaauw** [comment]
> i get the following error messages:

Hm, it looks like something went wrong in cutting/pasting the output.  I take it the bulbs and sensor do work in HomeKit?

> Aren't Osram lights and Xiaomi Door sensor in the list of known lights?

I only had a colour A60 in the list.  I'll add these two.

The door sensor is already whitelisted, but it looks like `manufacturername` is missing from the sensor resource, so homebridge-hue doesn't recognise it.  Could you check in the deCONZ GUI in the Cluster Info panel for the Basic cluster that Manufacturer Name has been read.  If not, you might need to re-read the attributes, or re-pair the sensor.  Maybe you need to press briefly the setup button, so the sensor reports the basic cluster attributes.  Make sure to move the magnet while reading the attributes or re-pairing the sensor, or the sensor might fall asleep and deCONZ cannot read the attributes.

**Comment by oleg77s** [comment]
You are right, after re-reading the attributes, warning about door sensor disappears :)
