### ISSUE TITLE
node seems to have been updated.

### ISSUE THREAD

**Issue by jsve** [ebaauw/homebridge-hue#180]
This:
https://github.com/ebaauw/homebridge-hue/blob/4b153a809df40457114c63fda1220ba0df4018b6/lib/HuePlatform.js#L514

Still requests 6.11.3. Latest:
https://nodejs.org/en/blog/release/v6.11.4/

**Comment by ebaauw** [comment]
As of v0.5.35, homebridge-hue should check for node v6.11.4 (or v6.11.x, where x >= 4).  Version is in package.json:
https://github.com/ebaauw/homebridge-hue/blob/544c98a17dbd18afd0293ccba2999fd3cf632f99/package.json#L24

**Comment by jsve** [comment]
👍
