### ISSUE TITLE
newest Version do not run in Docker on Synology NAS

### ISSUE THREAD

**Issue by Thors77** [ebaauw/homebridge-hue#182]
Hello,

I only can use homebridge-hue@0.1.14 on my homebridge, running in Docker on a Synology NAS.
If I want to install version 0.5.22 it always crash.

**Comment by ebaauw** [comment]
What’s the error, log, output?

**Comment by Thors77** [comment]
Hallo Erik, thanks for you helping. I am now switch to a RasPi. the Pi simply needs less energy ;)
