### ISSUE TITLE
Update Homebridge 0.4.29

### ISSUE THREAD

**Issue by Nastra888** [ebaauw/homebridge-hue#184]
Dear Erik,

after Update Homebridge I get this Error:

`ERROR LOADING PLUGIN homebridge-hue:
Okt 21 07:09:32 server homebridge[16232]: [2017-10-21 07:09:32] Error: Plugin /usr/local/lib/node_modules/homebridge-hue requires a HomeBridge version of 0.4.28 which does not satisfy the current HomeBridge version of 0.4.29. You may need to upgrade your installation of HomeBridge.
Okt 21 07:09:32 server homebridge[16232]:     at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
Okt 21 07:09:32 server homebridge[16232]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:134:14)
Okt 21 07:09:32 server homebridge[16232]:     at Array.forEach (<anonymous>)
Okt 21 07:09:32 server homebridge[16232]:     at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:130:22)
Okt 21 07:09:32 server homebridge[16232]:     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:55:24)
Okt 21 07:09:32 server homebridge[16232]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
Okt 21 07:09:32 server homebridge[16232]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Okt 21 07:09:32 server homebridge[16232]:     at Module._compile (module.js:573:30)
Okt 21 07:09:32 server homebridge[16232]:     at Object.Module._extensions..js (module.js:584:10)
Okt 21 07:09:32 server homebridge[16232]:     at Module.load (module.js:507:32)
Okt 21 07:09:32 server homebridge[16232]:     at tryModuleLoad (module.js:470:12)
Okt 21 07:09:32 server homebridge[16232]:     at Function.Module._load (module.js:462:3)
Okt 21 07:09:32 server homebridge[16232]:     at Function.Module.runMain (module.js:609:10)
Okt 21 07:09:32 server homebridge[16232]:     at startup (bootstrap_node.js:158:16)
Okt 21 07:09:32 server homebridge[16232]:     at bootstrap_node.js:598:3
Okt 21 07:09:32 server homebridge[16232]: [2017-10-21 07:09:32] ====================`

**Comment by ebaauw** [comment]
Current version of homebridge-hue requires homebridge 0.4.28.

I’ll have a look at what changed in homebridge 0.4.29 and update homebridge-hue in the next days.

**Comment by Nastra888** [comment]
👍 Thanks

**Comment by ebaauw** [comment]
v0.5.39
