### ISSUE TITLE
Some issues with Xiaomi devices

### ISSUE THREAD

**Issue by oleg77s** [ebaauw/homebridge-hue#188]
Some problems with Xiaomi devices:
1. Xiaomi switch (round button, WXKG01LM): only single click is available
2. Xiaomi Motion sensor (not an Aqara, RTCGQ01LM), Node info: manufacturer code: 0x1135. 
deCONZ-GW: /sensors/1: undefined lumi.sensor_motion (ZHAPresence) "Presence 1"
deCONZ-GW: /sensors/1: warning: unknown ZHAPresence sensor {"config":{"on":true,"reachable":true},"ep":1,"etag":"2f1a92a7108520426688fa0c4dd175d2","modelid":"lumi.sensor_motion","name":"Presence 1","state":{"lastupdated":"2017-10-23T09:00:59","presence":true},"type":"ZHAPresence","uniqueid":"00:15:8d:00:00:ef:86:6d-01-0406"}
and has presense state always true and change  state from true to true, if motion appears.
(Aqara motion sensor is ok, btw)

**Comment by ebaauw** [comment]
1. deCONZ needs to support double click, before homebridge-hue can expose these to HomeKit.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/168.  HomeKit doesn’t support triple click, etc.

2. I could add the sensor to homebridge-hue’s whitelist, but homebridge-hue only uses `state.presence` as reported by deCONZ.  Could you check, e.g. with [dc_eventlog](https://github.com/ebaauw/dc_eventlog), whether `state.lastupdated` changes?  Also it looks like it hasn’t been setup fully - `manufacturername` is missing.  Could you try and read the attributes of the sensor’s Basic cluster in the Cluster Info panel in the deCONZ GUI, while waving in front of the sensor, making sure it’s awake?  When looking at the Occupancy Sensing cluster, does the value of attribute 0x0000 change when motion is detected?

**Comment by oleg77s** [comment]
" deCONZ needs to support double click, before homebridge-hue can expose these to HomeKit"
And how about Xiaomi Cube: one click, double click and long pressure are supported ?

**Comment by ebaauw** [comment]
deCONZ reports different values for `state.buttonevent` for the cube.  Homebridge-hue translates these to the correponding “button” and action.  For the switch, deCONZ currently only issues value 1002 for `state.buttonevent`, which homebridge-hue translates to a single press.  You can see the values reported by deCONZ with dc_eventlog, or in the debug output of homebridge-hue, when running `homebridge -D`.

**Comment by oleg77s** [comment]
more info:
[10/24/2017, 9:12:58 AM] [Hue] deCONZ-GW: /sensors/1: LUMI lumi.sensor_motion (ZHAPresence) "Presence 1"
[10/24/2017, 9:12:58 AM] [Hue] deCONZ-GW: /sensors/1: warning: unknown ZHAPresence sensor {"config":{"duration":0,"on":true,"reachable":true},"ep":1,"etag":"83b5bbaee722fd4c18ae2763aae27650","manufacturername":"LUMI","modelid":"lumi.sensor_motion","name":"Presence 1","state":{"lastupdated":"2017-10-24T06:10:33","presence":true},"type":"ZHAPresence","uniqueid":"00:15:8d:00:00:ef:86:6d-01-0406"}

Tue Oct 24 2017 09:18:00: /sensors/1/state: {"lastupdated":"2017-10-24T06:18:00","presence":true}
Tue Oct 24 2017 09:19:48: /sensors/1/state: {"lastupdated":"2017-10-24T06:19:47","presence":true}
Tue Oct 24 2017 09:27:12: /sensors/1/state: {"lastupdated":"2017-10-24T06:27:12","presence":true}

In Occupancy Sensing cluster the value 0x01 of attribute 0x0000 dont change when motion is detected

**Comment by oleg77s** [comment]
Is it  possible to add Xiaomi Plug (ZNCZ01LM) to your plugin ?

**Comment by ebaauw** [comment]
I think it’s already supported by deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/153.  Like all plugs, it’s exposed as a light resource in the REST API, so you need to set `”lights”: true` in config.json.  Homebridge-hue should then issue an _unknown light_ warning, if you could post that message, I can whitelist the plug.

**Comment by ebaauw** [comment]
> In Occupancy Sensing cluster the value 0x01 of attribute 0x0000 dont change when motion is detected

I think the Xiaomi sensor doesn't send a message to deCONZ when motion is no longer detected.  So it's up to deCONZ to set `state.presence` back to false.  Try setting `config.duration` to 10 through the API and see if `state.presence` changes to false 10 seconds after last reporting motion.

**Comment by oleg77s** [comment]
Yep, I set 10 sec in setting Duration from Eve and it helped to solve an   always true issue:
Thu Oct 26 2017 13:06:02: /sensors/1/state: {"lastupdated":"2017-10-26T10:06:02","presence":true}
Thu Oct 26 2017 13:06:12: /sensors/1/state: {"lastupdated":"2017-10-26T10:06:12","presence":false}
Thu Oct 26 2017 13:06:24: /sensors/1/state: {"lastupdated":"2017-10-26T10:06:24","presence":true}
Thu Oct 26 2017 13:06:35: /sensors/1/state: {"lastupdated":"2017-10-26T10:06:35","presence":false}

**Comment by ebaauw** [comment]
Cool!

Any luck with the plug?

**Comment by oleg77s** [comment]
Cluster info:
0x004 Manufactur Name LUMI
0x005 Model Identifier  lumi.plug
But from API:
[10/26/2017, 4:38:10 PM] [Hue] deCONZ-GW: /lights/1: warning: unknown light model {"etag":"9590546ac7ca76e02248665c2963e2a0","hascolor":false,"manufacturername":"Unknown","modelid":"","name":"Light 1","state":{"alert":"none","on":false,"reachable":true},"swversion":"","type":"Smart plug","uniqueid":"00:15:8d:00:00:f8:53:be-01"}

**Comment by ebaauw** [comment]
You might try and open the network (from the WEB UI) and then re-read the attributes in the Basic cluster (from the GUI).  If that doesn't populate the `manufacturername`, `modelid` and `swversion`, delete the light resource through the API, delete the node from the GUI, reset the plug and re-pair it, manually reading its Basic cluster attributes, as soon as it's discovered.

Does it at least turn on/off when you update `state.on`?

**Comment by oleg77s** [comment]
I spent two days doing all these manipulations and no luck
and almost in all cases plug not recognized as light :(
Yes, plug turns on/off

**Comment by oleg77s** [comment]
It's a very good idea to hack deCONZ database :) Thank you Erik so much.
now it's ok:
10/27/2017, 8:47:24 AM] [Hue] deCONZ-GW: /lights/1: warning: unknown light model {"etag":"776d1a8b11681c83367212a9c7063b08","hascolor":false,"manufacturername":"LUMI","modelid":"lumi.plug","name":"Light 1","state":{"alert":"none","on":false,"reachable":true},"swversion":"","type":"Smart plug","uniqueid":"00:15:8d:00:00:f8:53:be-01"}
[10/27/2017, 8:47:24 AM] [Hue] deCONZ-GW: 2 accessories
[10/27/2017, 8:47:24 AM] [Hue] Initializing platform accessory 'deCONZ-GW'...
[10/27/2017, 8:47:24 AM] [Hue] deCONZ-GW: 2 services
[10/27/2017, 8:47:24 AM] [Hue] Initializing platform accessory 'Light 1'...

[10/27/2017, 8:48:25 AM] [Hue] Light 1: identify
[10/27/2017, 8:48:30 AM] [Hue] Light 1: homekit power changed from 0 to 1
[10/27/2017, 8:48:32 AM] [Hue] Light 1: homekit power changed from 1 to 0

Fri Oct 27 2017 08:48:30: /lights/1/state: {"on":true}
Fri Oct 27 2017 08:48:30: /groups/0/state: {"any_on":true}
Fri Oct 27 2017 08:48:32: /lights/1/state: {"on":false}
Fri Oct 27 2017 08:48:32: /groups/0/state: {"any_on":false}

**Comment by oleg77s** [comment]
Erik, don't forget to add Xiaomi Motion sensor to whitelist

**Comment by ebaauw** [comment]
Thanks for reminding me!  Does it also come with a lightlevel sensor, like the Aqara?

**Comment by oleg77s** [comment]
nope, only presence

**Comment by ebaauw** [comment]
Motion sensor and smart plug whitelisted in v0.5.41.
