### ISSUE TITLE
Support for Ikea FLOALT LED light panels

### ISSUE THREAD

**Issue by tvanzele** [ebaauw/homebridge-hue#189]
Hi ebaauw,

Thanks for your excellent Hue plugin!

I plan to add some IKEA Floalt LED panels at home, I checked the HueLight.js first, but they are not yet referenced, so I guess that they will not work?
What information would you need to support them?

Thanks, Tom

**Comment by ebaauw** [comment]
Probably they’ll work just fine, only homebridge-hue will issue a warning message about an unknown light.  The warning message should contain all the info I need to whitelist the panel.  I would be nice if you could actually confirm that they work ;-)

**Comment by ebaauw** [comment]
I'll close this one for now.  If you have the panels, please re-open with the warning message.
