### ISSUE TITLE
Osram lightify Garden Spots - 

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#191]
I recognized in my homebridge log, that the garden spot switch goes off (0) and on (1), lights won‘t get lights on/off.

pi@raspberrypi:~ $ sudo journalctl -f -u homebridge
-- Logs begin at Mo 2017-10-16 20:17:01 CAT. --
Okt 23 18:51:04 raspberrypi homebridge[22842]: [2017-10-23 18:51:04] [Hue] Gartenspot: set homekit status fault from 1 to 0
Okt 23 18:52:24 raspberrypi homebridge[22842]: [2017-10-23 18:52:24] [Hue] Gartenspot: set homekit status fault from 0 to 1
Okt 23 18:53:44 raspberrypi homebridge[22842]: [2017-10-23 18:53:44] [Hue] Gartenspot: set homekit status fault from 1 to 0
Okt 23 18:54:54 raspberrypi homebridge[22842]: [2017-10-23 18:54:54] [Hue] Gartenspot: set homekit status fault from 0 to 1
Okt 23 18:56:14 raspberrypi homebridge[22842]: [2017-10-23 18:56:14] [Hue] Gartenspot: set homekit status fault from 1 to 0
Okt 23 18:59:55 raspberrypi homebridge[22842]: [2017-10-23 18:59:55] [Hue] Gartenspot: set homekit status fault from 0 to 1
Okt 23 19:00:40 raspberrypi homebridge[22842]: [2017-10-23 19:00:40] [Hue] Gartenspot: set homekit status fault from 1 to 0
Okt 23 19:01:10 raspberrypi homebridge[22842]: [2017-10-23 19:01:10] [Hue] Gartenspot: set homekit status fault from 0 to 1
Okt 23 19:01:40 raspberrypi homebridge[22842]: [2017-10-23 19:01:40] [Hue] Gartenspot: set homekit status fault from 1 to 0
Okt 23 19:02:45 raspberrypi homebridge[22842]: [2017-10-23 19:02:45] [Hue] Gartenspot: set homekit status fault from 0 to 1
Okt 23 19:03:40 raspberrypi homebridge[22842]: [2017-10-23 19:03:40] [Hue] Gartenspot: set homekit status fault from 1 to 0
Okt 23 19:08:21 raspberrypi homebridge[22842]: [2017-10-23 19:08:21] [Hue] Gartenspot: set homekit status fault from 0 to 1
Okt 23 19:09:41 raspberrypi homebridge[22842]: [2017-10-23 19:09:41] [Hue] Gartenspot: set homekit status fault from 1 to 0
Okt 23 19:12:11 raspberrypi homebridge[22842]: [2017-10-23 19:12:11] [Hue] Gartenspot: set homekit status fault from 0 to 1
Okt 23 19:12:36 raspberrypi homebridge[22842]: [2017-10-23 19:12:36] [Hue] Gartenspot: set homekit status fault from 1 to 0

Sorry for my bad english ;-)

**Comment by ebaauw** [comment]
The gardenspot doesn’t go on and off, the Hue bridge constantly changes its `state.reachable`.  Homebridge-hue exposes this to HomeKit as _Status Fault_.

**Comment by Kohle81** [comment]
Hello,

thanks for this answer.

Greetings from Germany,

Manuel

Von meinem iPhone gesendet
