### ISSUE TITLE
Ikea sensors howto

### ISSUE THREAD

**Issue by JeremyHX** [ebaauw/homebridge-hue#192]
Hi!
Not really an issue but more of a question - I've setup homebridge-hue just like the documentation said. It communicates with my Hue Bridge v2, everything seems to work fine.
I have a few Ikea motion sensors and remotes, how can I link them to my Hue Bridge 2 / use them with your plugin?
I can't find the steps in the doc.
Thanks,
Jeremy

**Comment by ebaauw** [comment]
You cannot link them to the Hue bridge.  To use them with homebridge-hue, link them to deCONZ instead.

**Comment by JeremyHX** [comment]
Oh ok, thanks.
I'm running homebridge on an arm64 SBC (odroid C2), I couldn't get deCONZ to run as they dont offer arm64 binaries. Installing all the 32 bit dependencies as well turned out to be problematic :-(.
