### ISSUE TITLE
IKEA motion sensor shows as "Triggered" all the time

### ISSUE THREAD

**Issue by jsve** [ebaauw/homebridge-hue#193]
I have added a motion sensor (TRÅDFRI) to deconz. In deconz, it seems to be working: GUI flashes only when there is motion and when asking the api I get:
```
		"state": {
			"dark": true,
			"lastupdated": "2017-10-24T22:21:25",
			"presence": true
		},
```
And the "last updated" updates when there is motion.

The icon I home, however, shows as "triggered" no matter what.

**Comment by ebaauw** [comment]
What did you set the sensor’s duration dial to?  `config.duration` should reflect the setting of the duration dial.  deCONZ will continue to show `state.presence` as true for the full duration.  homebridge-hue just copies this value into _Motion Detected_.

When running `homebridge -D`, homebridge-hue logs the events it receives from deCONZ.  You should see an event for `presence` becoming false, when there’s no motion for `duration` seconds.

**Comment by jsve** [comment]
Not sure that I have set a duration for this. Where do I do that? The sensor looks like this:

```
"3": {
		"config": {
			"alert": "none",
			"group": "9676",
			"on": true,
			"reachable": true
		},
		"ep": 1,
		"etag": "eb4dd0abc8d27ab57ee2a3d9a3b712f1",
		"manufacturername": "IKEA of Sweden",
		"modelid": "TRADFRI motion sensor",
		"name": "TRADFRI motion sensor ",
		"state": {
			"dark": true,
			"lastupdated": "2017-10-24T22:37:35",
			"presence": true
		},
		"swversion": "1.2.214",
		"type": "ZHAPresence",
		"uniqueid": "00:0b:57:ff:fe:92:bf:55-01-0006"
	}
}
```

**Comment by ebaauw** [comment]
On the back of the sensor, there are two dials: one for day/night mode, one for duration (1 to 10 minutes).  deCONZ should show a `config.duration`.  What version of deCONZ are you on?  Is `state.dark` changed when you set the other dial to night mode and keep the sensor in tye light while triggering it?

**Comment by jsve** [comment]
Yes, on the sensor I have set the switch to 1 minute. But do I need to set that somewhere else also, you mean?

I'm in deconz 2.04.82. The sensor has the latest firmware (updated through the IKEA app).

Not sure if ```state.dark``` changes. I'll give it a try tonight.

**Comment by ebaauw** [comment]
> Yes, on the sensor I have set the switch to 1 minute. But do I need to set that somewhere else also, you mean?

No, deCONZ should pick that up.

>  The sensor has the latest firmware

Figured that from `swversion`.

**Comment by jsve** [comment]
Flipped the switches. Set the day/night switch to night and the timer to 10 min (was 1 min). This is the sensor now:

```
	"3": {
		"config": {
			"alert": "none",
			"battery": 87,
			"group": "9676",
			"on": true,
			"reachable": true
		},
		"ep": 1,
		"etag": "6f427b7decfebb7c72b5e98148c84c43",
		"manufacturername": "IKEA of Sweden",
		"modelid": "TRADFRI motion sensor",
		"name": "TRADFRI motion sensor ",
		"state": {
			"dark": false,
			"lastupdated": "2017-10-25T16:56:15",
			"presence": true
		},
		"swversion": "1.2.214",
		"type": "ZHAPresence",
		"uniqueid": "00:0b:57:ff:fe:92:bf:55-01-0006"
	}
```

**Comment by ebaauw** [comment]
OK, so the motion sensor does send something to deCONZ.  Still `config.duration` is missing, I suspect that's causing `state.presence` to remain true (the IKEA motion sensor doesn't send a notification when motion is no longer detected - deCONZ resets the state after `config.duration` seconds).

I saw @manup made a recent commit, https://github.com/dresden-elektronik/deconz-rest-plugin/commit/dcac40df0c905942c68cb93aed6fc864497c4be2, to add `config.duration` if not yet present.  I must have missed a scenario while implementing `duration` and `dark` for this sensor.  Did you pair the motion sensor while already in 2.04.82 or using an older version?  Have you restarted deCONZ after pairing the sensor?

**Comment by jsve** [comment]
I did a reinstall of deconz and some other stuff, then a couple of restarts. Now it all seems to work like it should. Might be because of having paired it with an older version. Might be something else. So maybe not "solved" (for future reference), but fixed for me. 

Thanks for your help!
