### ISSUE TITLE
Support for Belkin Wemo Smart LED F7C0033

### ISSUE THREAD

**Issue by oleg77s** [ebaauw/homebridge-hue#195]
Hi Erik
Belkin Wemo Smart LED F7C0033МАУ27 (ZHA, EU version, 230v) bulb just added to deCONZ as 
Home Automation Dimmable Light:
API/Lights:
 "2": {
		"etag": "d40463b239d1a20f56d0effb6b70479f",
		"hascolor": false,
		"manufacturername": "MRVL",
		"modelid": "MZ100",
		"name": "Light 2",
		"state": {
			"alert": "none",
			"bri": 137,
			"on": false,
			"reachable": true
		},
		"swversion": "",
		"type": "Dimmable light",
		"uniqueid": "94:10:3e:a2:b2:78:b3:f2-01"
	}
}
Homebridge-hue:
[10/28/2017, 9:30:53 PM] [Hue] deCONZ-GW: /lights/2: MRVL MZ100 (Dimmable light) "Light 2"
[10/28/2017, 9:30:53 PM] [Hue] deCONZ-GW: /lights/2: warning: unknown light model {"etag":"5a01154cc378444910c4eeadf0acec1b","hascolor":false,"manufacturername":"MRVL","modelid":"MZ100","name":"Light 2","state":{"alert":"none","bri":28,"on":true,"reachable":true},"swversion":"","type":"Dimmable light","uniqueid":"94:10:3e:a2:b2:78:b3:f2-01"}
dc_eventlog:
Sat Oct 28 2017 21:31:45: /lights/2/state: {"on":true}
Sat Oct 28 2017 21:31:51: /lights/2/state: {"bri":43}
Sat Oct 28 2017 21:31:51: /lights/2/state: {"bri":56}
Sat Oct 28 2017 21:31:51: /lights/2/state: {"bri":66}
Sat Oct 28 2017 21:31:51: /lights/2/state: {"bri":86}
Sat Oct 28 2017 21:31:52: /lights/2/state: {"bri":104}
Sat Oct 28 2017 21:31:52: /lights/2/state: {"bri":117}
Sat Oct 28 2017 21:31:52: /lights/2/state: {"bri":132}
Sat Oct 28 2017 21:31:53: /lights/2/state: {"bri":152}
Sat Oct 28 2017 21:31:53: /lights/2/state: {"bri":168}
Sat Oct 28 2017 21:31:53: /lights/2/state: {"bri":183}
Sat Oct 28 2017 21:31:54: /lights/2/state: {"bri":201}
Sat Oct 28 2017 21:31:54: /lights/2/state: {"bri":218}
Sat Oct 28 2017 21:31:54: /lights/2/state: {"bri":234}
Sat Oct 28 2017 21:31:54: /lights/2/state: {"bri":244}
Sat Oct 28 2017 21:31:55: /lights/2/state: {"bri":254}
Sat Oct 28 2017 21:31:59: /lights/2/state: {"bri":226}
Sat Oct 28 2017 21:31:59: /lights/2/state: {"bri":198}
Sat Oct 28 2017 21:31:59: /lights/2/state: {"bri":170}
Sat Oct 28 2017 21:32:00: /lights/2/state: {"bri":135}
Sat Oct 28 2017 21:32:00: /lights/2/state: {"bri":107}
Sat Oct 28 2017 21:32:00: /lights/2/state: {"bri":76}
Sat Oct 28 2017 21:32:00: /lights/2/state: {"bri":51}
Sat Oct 28 2017 21:32:01: /lights/2/state: {"bri":28}
Sat Oct 28 2017 21:32:01: /lights/2/state: {"bri":8}
Sat Oct 28 2017 21:32:01: /lights/2/state: {"on":false}
Sat Oct 28 2017 21:32:01: /lights/2/state: {"bri":0}
Sat Oct 28 2017 21:32:09: /lights/2/state: {"on":true}
Sat Oct 28 2017 21:32:09: /lights/2/state: {"bri":28}
Sat Oct 28 2017 21:32:10: /lights/2/state: {"bri":71}
Sat Oct 28 2017 21:32:10: /lights/2/state: {"bri":117}
Sat Oct 28 2017 21:32:10: /lights/2/state: {"bri":137}
Sat Oct 28 2017 21:32:12: /lights/2/state: {"on":false}

It's working fine in Home.app,so can you add it to the whitelist?
P.S. datasheet: 800lm, 3000k, 230v, 60ma, eq 60w
Wemo app says fw ver 83
Osram app says: MZ100 ver. 01020083

b.r.
Oleg

**Comment by ebaauw** [comment]
Whitelisted in v0.5.41.
