### ISSUE TITLE
Support for Osram Lightify Surface Light TW

### ISSUE THREAD

**Issue by oleg77s** [ebaauw/homebridge-hue#196]
Hi Erik
Another Osram Lightify light added to home bridge-hue :)
It's Osram Lightify Surface Light Tunable White W38 (28watt) luminaires
It's working fine in Home.app,so can you add it to the whitelist too?
API/Lights:
"3": {
		"ctmax": 370,
		"ctmin": 153,
		"etag": "828ad70ec4d6a6c26c8c87de75e4408c",
		"hascolor": true,
		"manufacturername": "OSRAM",
		"modelid": "Surface Light TW",
		"name": "Light 3",
		"state": {
			"alert": "none",
			"bri": 107,
			"colormode": "ct",
			"ct": 370,
			"on": true,
			"reachable": true
		},
		"swversion": "V1.05.10",
		"type": "Color temperature light",
		"uniqueid": "84:18:26:00:00:d9:fc:66-03"
	}
Homebridge-hue:[10/29/2017, 9:45:34 AM] [Hue] deCONZ-GW: /lights/3: warning: unknown light model {"ctmax":370,"ctmin":153,"etag":"34bf1a03c0ba67879013972a88181938","hascolor":true,"manufacturername":"OSRAM","modelid":"Surface Light TW","name":"Light 3","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"on":true,"reachable":true},"swversion":"V1.05.10","type":"Color temperature light","uniqueid":"84:18:26:00:00:d9:fc:66-03"}
dc_eventlog:
Sun Oct 29 2017 09:43:31: /lights/3/state: {"on":true}
Sun Oct 29 2017 09:43:33: /lights/3/state: {"bri":254}
Sun Oct 29 2017 09:43:33: /lights/3/state: {"ct":370}
Sun Oct 29 2017 09:47:30: /lights/3/state: {"bri":203}
Sun Oct 29 2017 09:47:31: /lights/3/state: {"bri":152}
Sun Oct 29 2017 09:47:31: /lights/3/state: {"bri":127}
Sun Oct 29 2017 09:47:31: /lights/3/state: {"bri":99}
Sun Oct 29 2017 09:47:31: /lights/3/state: {"bri":76}
Sun Oct 29 2017 09:47:32: /lights/3/state: {"bri":66}
Sun Oct 29 2017 09:47:32: /lights/3/state: {"bri":51}
Sun Oct 29 2017 09:47:32: /lights/3/state: {"bri":48}
Sun Oct 29 2017 09:47:32: /lights/3/state: {"bri":185}
Sun Oct 29 2017 09:47:33: /lights/3/state: {"bri":147}
Sun Oct 29 2017 09:47:34: /lights/3/state: {"bri":107}
Sun Oct 29 2017 09:47:34: /lights/3/state: {"bri":102}
Sun Oct 29 2017 09:47:39: /lights/3/state: {"ct":372}
Sun Oct 29 2017 09:47:40: /lights/3/state: {"ct":153}
Sun Oct 29 2017 09:47:40: /lights/3/state: {"ct":360}
Sun Oct 29 2017 09:47:40: /lights/3/state: {"ct":257}
Sun Oct 29 2017 09:47:42: /lights/3/state: {"bri":107}
Sun Oct 29 2017 09:47:44: /lights/3/state: {"ct":265}
Sun Oct 29 2017 09:47:44: /lights/3/state: {"ct":329}
Sun Oct 29 2017 09:47:44: /lights/3/state: {"ct":158}
Sun Oct 29 2017 09:47:44: /lights/3/state: {"ct":194

Osram app says: Surface Light TW ver. 01020510 (updated from 01020315)
PS:  latest Osram fw:
Plug                           01020509 (updated from 01020412)
Classic A60 TW        01020509 (updated from 01020413)
Classic A60 W clear 01020510 (updated from 01020412)
Classic A60 RGBW   01020510 (updated from 01020412)
Classic B40 TW        01020510 (updated from 01020412)
Switch                        01020000
Motion Sensor           1E005310

b.r.
Oleg

**Comment by ebaauw** [comment]
Whitelisted in v0.5.41.
