### ISSUE TITLE
Motion Sensor

### ISSUE THREAD

**Issue by marcodesantis71** [ebaauw/homebridge-hue#200]
HI All,

I'va a problem with MotionSensor and Home App.
On my app, I see the incompatible status with MotionSensor.

Any idea ?

**Comment by ebaauw** [comment]
Not sure what you mean.  Could you post a screen shot?

**Comment by marcodesantis71** [comment]
Of course.
![img_1626](https://user-images.githubusercontent.com/23100741/32176772-e02d67d8-bd88-11e7-940f-b1275834aba4.png)
