### ISSUE TITLE
Flooded logs with bridge requests

### ISSUE THREAD

**Issue by SilentGob** [ebaauw/homebridge-hue#201]
Hello,

First thank you for your work on this plugin !

My logs are flooded with this kind of lines
"[Homebridge Hue] Philips hue: bridge request XXX: get /sensors
[Homebridge Hue] Philips hue: bridge request XXX: ok"

Did I misconfigured something somewhere ? 
If not, is there a way to only display errors and not every request gone right ?

regards,

**Comment by ebaauw** [comment]
If you don’t want (grey) debug messages, don’t start homebridge with `-D`.  If you only want (red) error and (amber) warning messages, only capture stderr in your logs; (green) info and debug massages are written to stdout.

**Comment by SilentGob** [comment]
Found the culprit (me). I am using PM2 to manage homebridge and `pm2 logs homebridge` shows the flooding messages mentioned earlier (it displays error and output).
Your plugin and homebridge are not responsible for the way PM2 displays logs.
 
For anyone asking, you can filter the output logs of PM2 to only see err with `pm2 logs homebridge --err`

Sorry for the noise.
