### ISSUE TITLE
Almost off topic question about behavior since homekit hue bridge update

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue#202]
Hi all,

First, I'm sorry to ask this off topic question but I believe that's one of the best places to ask it.
Since last Hue bridge update that brought HomeKit support to Hue accessories, my two bridges (I need two because of the number of accessories I have) behave weirdly. I observed the following:

- Lights triggered by motion sensors that used to react instantly are very slow to respond or do not respond at all. This behavior does not concern HomeKit but is observed since the last update.
- The bridges do not respond. The three lights are blue but nothing happens when I use a dimmer or try to switch on/off lights from the Home or Hue app. Restarting the bridge fixes the problem.
- It happens frequently that Home app is not notified when a dimmer button is pressed.
- And, one of the most strange behaviors, is a dimmer exposed both natively and through homebridge. When I press one of its buttons, only the one exposed through homebridge reacts and not the one exposed natively. I can post a video showing that.

Is there other persons experiencing some of these behaviors? 
Thanks.

**Comment by ebaauw** [comment]
I moved all my lights, sensors, and switches to deCONZ and haven’t really used/tested the latest Hue bridge firmware.  There’s something weird in #197, not sure if it’s due to Hue Labs or to the new firmware.

How many and what brands of lights do you connect to each bridge?  IKEA?  OSRAM?  Could you post the full dump of each bridge (see **Troubleshooting** in the README)?

When the lights don’t respond, do the motion sensor or dimmer switch blink red?  Does the link button on the bridge still work?  Is the sensor resource in the API updated?  You might check the CLIP API debugger (see https://developers.meethue.com/documentation/getting-started) or expose motion sensors, switches, and link button through homebridge-hue check (in Eve) for changes to _Lastupdated_.  Do the symptoms still appear when you switch off the bridge’s native HomeKit?

What heartrate do you use in homebridge-hue?  Do the symptoms still appear when homebridge isn’t running?  In that case you might try the Hue developers forum, https://developers.meethue.com/forums/apple-homekit.

**Comment by ooii** [comment]
> There’s something weird in #197, not sure if it’s due to Hue Labs or to the new firmware.

The only formula I'm using is a timer. And I'm going to delete it to see if it has any effect.
> How many and what brands of lights do you connect to each bridge? IKEA? OSRAM? 

I have 17 white bulbs, 7 dimmers, 7 motion sensors, and 2 Hue Go on bridge 1. On bridge 2, I have 4 while bulbs, 12 GU10 color bulbs, 7 dimmers, and 1 tap.
> Could you post the full dump of each bridge (see Troubleshooting in the README)?

[Here](https://www.dropbox.com/s/qoy8grd6ydwd0ht/Hue%201.json?dl=0) and [here](https://www.dropbox.com/s/trjm3abot1f0x8q/Hue%202.json?dl=0).
> When the lights don’t respond, do the motion sensor or dimmer switch blink red? 

No. But it happens that a motion sensor blinks red but the associated bulb switches on.
>Does the link button on the bridge still work? 

I assume it still works. However, when I press it, I don't see any of my `link` or `touch link` accessories changing in Eve app. Are those the accessories that should react to a link press when "linkButton" is configured to true in `config.json` file?
>Is the sensor resource in the API updated? You might check the CLIP API debugger (see https://developers.meethue.com/documentation/getting-started) or expose motion sensors, switches, and link button through homebridge-hue check (in Eve) for changes to Lastupdated. 

I'll check that the next time it misbehaves. The problem appears frequently but I cannot reproduce it on demand.
>Do the symptoms still appear when you switch off the bridge’s native HomeKit?

That's a very good question. I'll disable it and see the result. But note that all the issues appeared since the last update *and* the activation of the bridge's native HomeKit.
> What heartrate do you use in homebridge-hue? 

2 seconds.
> Do the symptoms still appear when homebridge isn’t running?

Need to disable it and see if it works better.

But I was also asking the community here if other people than me are facing the same issues. Since I'm having troubles with two bridges and that these issues started very short time after the HomeKit update, it seems very likely to be related to that. But I can be wrong too :)
@ebaauw, thanks a lot again.

**Comment by ebaauw** [comment]
> > Could you post the full dump of each bridge (see Troubleshooting in the README)?

> Here and here.

These are old dumps from early September, before the firmware update.  I don't see anything excessive or weird in the lights, sensors, and rules.  The bridges are on different ZigBee channels (as they should).

> > Does the link button on the bridge still work?

> I assume it still works. However, when I press it, I don't see any of my link or touch link accessories changing in Eve app. Are those the accessories that should react to a link press when "linkButton" is configured to true in config.json file?

`Link` and `Touchlink` are (regular) switches and can be changed from HomeKit and start the search for new lights/sensors or the touchlink procedure on the bridge.  The link button on the bridge is exposed as stateless programmable switch (like the Hue tap or Hue dimmer).  It cannot be set from HomeKit, but it can trigger HomeKit actions.  Eve doesn't display these, but Apple's Home app does.

**Comment by ooii** [comment]
>These are old dumps from early September, before the firmware update. I don't see anything excessive or weird in the lights, sensors, and rules. The bridges are on different ZigBee channels (as they should).

Deleted them and created new ones available [here](https://www.dropbox.com/s/2zps5wv4fqoez7y/Hue%201.json?dl=0) and [here](https://www.dropbox.com/s/zi7jq4wnf3nk1g0/Hue%202.json?dl=0).

>Link and Touchlink are (regular) switches and can be changed from HomeKit and start the search for new lights/sensors or the touchlink procedure on the bridge. 

Very good. I was exactly looking for that.

>The link button on the bridge is exposed as stateless programmable switch (like the Hue tap or Hue dimmer). It cannot be set from HomeKit, but it can trigger HomeKit actions. Eve doesn't display these, but Apple's Home app does.

Found it.

**Comment by ebaauw** [comment]
> new ones available here and here

Performance could be impacted by the Hue bridges still being busy updating the firmware of connected devices.  It looks like Hue 1 is updating the firmware of _Dimmer Zach_ (/sensors/31) and Hue 2 the firmware of _Dimmer cuisine_ (/sensors/4).  There's a firmware update pending on the _Hue go Parents_ (/lights/19) on the Hue 2 bridge.

> And, one of the most strange behaviors, is a dimmer exposed both natively and through homebridge. When I press one of its buttons, only the one exposed through homebridge reacts and not the one exposed natively. I can post a video showing that.

Do you actually see the same dimmer switch twice, once exposed by the v2 Hue bridge, once by homebridge-hue.  What about the motion sensors?  I hear they're only shown once, even when exposed simultaneously by the v2 Hue bridge and by homebridge-hue.

**Comment by ooii** [comment]
>Performance could be impacted by the Hue bridges still being busy updating the firmware of connected devices. It looks like Hue 1 is updating the firmware of Dimmer Zach (/sensors/31) and Hue 2 the firmware of Dimmer cuisine (/sensors/4). There's a firmware update pending on the Hue go Parents (/lights/19) on the Hue 2 bridge.

I started the update. I keep you informed if any difference. 
>Do you actually see the same dimmer switch twice, once exposed by the v2 Hue bridge, once by homebridge-hue? 

Yes, absolutely. 
>What about the motion sensors? I hear they're only shown once, even when exposed simultaneously by the v2 Hue bridge and by homebridge-hue.

They also appear twice. [This screenshot](https://akalat.fr/4823ee8806a6690435bced6cfc3eefca) shows the motion sensor (Red) and a dimmer (green), both of them appearing twice, for every accessory.

**Comment by ebaauw** [comment]
> And, one of the most strange behaviors, is a dimmer exposed both natively and through homebridge. When I press one of its buttons, only the one exposed through homebridge reacts and not the one exposed natively.

I cannot reproduce this, see also https://github.com/ebaauw/homebridge-hue/issues/211#issuecomment-343726920.

**Comment by ooii** [comment]
Is there any logs on the hue bridge that allows to figure out what has triggered something? Sometimes, my motion sensor triggers a light while it shows in the Hue app that there is enough light to not do so.

**Comment by ebaauw** [comment]
> Is there any logs on the hue bridge that allows to figure out what has triggered something?

Each rules resource has a `lasttriggered` and `timestriggered` attribute, that records the time the rule was last triggered and the total number of times the rule has been triggered.  You can view these through the API, but there's no notification or log.

When setting `"rules": true` in config.json, homebridge-hue exposes rules to HomeKit, so you can monitor these attributes from HomeKit.  This also supports to enable/disable the rule from HomeKit.  For each rule, a custom service is added to the bridge accessory, so you need Eve (or another HomeKit app) to see them.  Unfortunately, there's a HomeKit limit of 99 services per accessory, so not all rules might be shown.  By creating a blacklist of uninteresting rules, you can expose the rules of interest.  The blacklist is implemented as a resourcelink on the bridge, see https://github.com/ebaauw/homebridge-hue/issues/170#issuecomment-338417513.

> Sometimes, my motion sensor triggers a light while it shows in the Hue app that there is enough light to not do so.

Typically, the value of the light sensor gets updated on the Hue bridge, right after motion has been detected.  So the rule is triggered with the light level just before the lights turn on, and then when you look in the app, you see the light level with the lights on.

**Comment by ooii** [comment]
Thanks again @ebaauw. 
I need to spend some time understanding what are resources, resourcelinks, etc to understand what I'm exactly doing.

**Comment by ebaauw** [comment]
You might want to check out the homebridge-hue README and [wiki](https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started)

**Comment by ooii** [comment]
Do you mind if I pinpoint what does not seem clear to me in these documents? Just to make it clear for the community and for myself.

**Comment by ebaauw** [comment]
Please do!
