### ISSUE TITLE
Delete Hue Motion Temperature Sensor

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#204]
Hello,

I use the Motion Sensor nativ in HomeKit.

I used deCONZ about RaspBee and I have some Xiaomi Temperature Sensors. Now I can not exclude the ZLLTemperature. Now I have from the Hue Motion two Sensors with the temperature.

Can I exclude only the Hue Motion Temperature?

**Comment by ebaauw** [comment]
Create a blacklist resourcelink with the resources corresponding to the Hue motion sensors temperature.  See #170.
