### ISSUE TITLE
Xiaomi Aqara flood sensor

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#205]
Hello,
my deCONZ have noticed the flood sensor.

I have some excluded things in config.

"excludeSensorTypes": ["CLIPGenericStatus", "CLIPPresence", "CLIPGenericFlag", "Daylight", "Geofence", "ZLLPresence", "ZLLLightLevel", "ZGPSwitch", "ZLLSwitch"]

The flood sensor is actually not to see in Homekit.

**Comment by ebaauw** [comment]
Is the flood sensor visible in the deCONZ REST API?  If so, could you post the json returned when GETting the sensor resource?  Alternatively, enable all sensor types and homebridge-hue should issue an unknown sensor warning.

**Comment by oleg77s** [comment]
In my setup the flood sensor is not visible in the deCONZ REST API

**Comment by ebaauw** [comment]
Then homebridge-hue doesn't see it and cannot expose it to HomeKit.

**Comment by Kohle81** [comment]
Here the picture from the aqara flood sensor in deCONZ.



Von meinem iPhone gesendet

**Comment by ebaauw** [comment]
@Kohle81,  No picture?

Best open an issue in https://github.com/dresden-elektronik/deconz-rest-plugin to add support for the flood sensor to the deCONZ REST API.  After that, I can add support in homebridge-hue.

**Comment by ebaauw** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/263

**Comment by ebaauw** [comment]
I managed to add the sensor manually to deCONZ and add support for it to homebridge-hue.  I even get HomeKit notifications:
![img_0010](https://user-images.githubusercontent.com/22179355/35476199-5cff8052-03ac-11e8-8664-73a563c9125c.jpg)

**Comment by ebaauw** [comment]
Now supported as ZHAWater sensor in deCONZ v2.05.04 and homebridge-hue v0.6.5.

```json
{
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "b0a179599eb96cee2fa9e803e1ec932c",
  "manufacturername": "LUMI",
  "modelid": "lumi.sensor_wleak.aq1",
  "name": "Leak",
  "state": {
    "lastupdated": "2018-02-17T10:09:13",
    "water": false
  },
  "swversion": "3000-0001",
  "type": "ZHAWater",
  "uniqueid": "00:15:8d:00:01:xx:xx:xx-01-0500"
}
```
