### ISSUE TITLE
No bridgeid/password generated at first start

### ISSUE THREAD

**Issue by megavoid** [ebaauw/homebridge-hue#207]
Hi there,

I am having an issue with setting up homebridge-hue on a Raspberry Pi with a RaspBee / deCONZ. Everything else seems to be working just fine. RaspBee is working on its own ZigBee network and I was able to add a Trådfri Remote control via web interface. The remote shows up in the deCONZ application and Homebridge itself is working and can be added to HomeKit.

I followed the instructions on this Git to setup the homebridge-hue: I unlocked the gateway and started homebridge-hue for the first time. The instructions say that the bridgeid/password should show up in the log for integration in the config file. This is the log output:

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] Loaded plugin: homebridge-hue

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] Registering platform 'homebridge-hue.Hue'

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] ---

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] Loaded config.json with 0 accessories and 1 platforms.

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] ---

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] Loading 1 platforms...

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] [Hue] Initializing Hue platform...

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] [Hue] homebridge-hue v0.5.43, node v8.9.0, homebridge v0.4.31

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] [Hue] TypeError: Cannot read property 'toLowerCase' of undefined

Nov  8 18:13:35 zigberrypi homebridge[23251]: at HueBridge.<anonymous> (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:103:53)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at Function.then (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:60:18)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:84:26)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:127:15)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at HueBridge.<anonymous> (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:213:7)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at Function.then (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:60:18)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:84:26)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:127:15)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at HueBridge.<anonymous> (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:878:14)

Nov  8 18:13:35 zigberrypi homebridge[23251]: at Request.self.callback (/usr/lib/node_modules/homebridge-hue/node_modules/request/request.js:186:22)

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] [Hue] undefined: 0 accessories

Nov  8 18:13:35 zigberrypi homebridge[23251]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

--- Code ---

Nov  8 18:13:35 zigberrypi homebridge[23251]: [2017-11-8 18:13:35] Homebridge is running on port 51826.

Nov  8 18:14:12 zigberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Wed Nov  8 18:15:42 2017 [try http://www.rsyslog.com/e/2007 ]

I have deleted the homebridge accessories and persist folders and tried again with the same result.

**Comment by ebaauw** [comment]
Looks like homebridge-hue gets an unexpected answer when probing the gateway.  Could you please post the output of `homebridge -D` and your config.json?  What version of deCONZ are you running?

**Comment by megavoid** [comment]
Thanks for your reply, here is the data:

![bildschirmfoto 2017-11-09 um 20 40 31](https://user-images.githubusercontent.com/33493992/32626045-726b4324-c58e-11e7-8a4d-bbd92f2fce24.png)

[config.json.txt](https://github.com/ebaauw/homebridge-hue/files/1458981/config.json.txt)

I am running deCONZ 2.04.35.

**Comment by ebaauw** [comment]
Ah, you need the latest beta of deCONZ, 2.04.86, see https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz.  Just do steps 1-3; no need to compile the REST API plugin yourself.

**Comment by megavoid** [comment]
Ah okay, I was not aware of that! Thanks for your support!
