### ISSUE TITLE
example to expose only hue sensor (enable/disable) - hue bridge square

### ISSUE THREAD

**Issue by sommo** [ebaauw/homebridge-hue#208]
Hi,
i would like to expose only my hue sensors for enable and disable them, not all the other features, that already were exposed from my hue bridge square.
Can someone help to create che config.json?
Thank you

**Comment by ebaauw** [comment]
homebridge-hue doesn't support that: either it exposes a sensor or it doesn't.

**Comment by sommo** [comment]
@ebaauw , ok thank you.
