### ISSUE TITLE
Out-of-the-box actions for Tradfri Remote

### ISSUE THREAD

**Issue by JeremyHX** [ebaauw/homebridge-hue#209]
Hi,
I bought a ConBee and set up my Ikea lights, sensors, and remotes using homebridge-hue.
In Apple's Home app, I can wire the remote's buttons to do some basic actions, but I'm missing some important ones. Unless I missed something, I don't think the paid Home app would help with this either.
What's the best way to restore the "Increase brightness", "Decrease brightness", and "Toggle power" actions?
Thanks,
Jeremy

**Comment by ebaauw** [comment]
Easiest way is to use the deCONZ web app and assign the lights you want to control with the remote to the group deCONZ has associated with the remote.

**Comment by ebaauw** [comment]
The _Previous_ and _Next_ button use manufacturer specific commands, which are understood only by the IKEA white spectrum and colour bulbs, in factory new state.  I still haven’t been able to figure out what causes the bulbs no longer to understand these commands.

You might want to double-check whether the colour change is indeed initiated from HomeKit, or from rules on the deCONZ gateway (that deCONZ creates when pairing the remote).  Best run `homebridge -D` to check what requests homebridge-hue sends to deCONZ.  When the HomeKit action is setup correctly, there should be a single PUT request with both `bri` and `ct` when pressing the button.

**Comment by manup** [comment]
If you press the large button for about 10 seconds deCONZ will create some default color temperature rules for the *Previous* and *Next* buttons (albeit the color transition is too long and should be more fast).

**Comment by JeremyHX** [comment]
Thank you!

**Comment by rikroe** [comment]
Sorry to bring this up again but I cannot get the color temperature rules to work. 
I've set up a remote and two lights in Phoscon. After adding the lights to the remote I'm able to control on/off and the dimmer. But even after pressing the large button for 10 seconds (the lights flash after 3 or 4 seconds), nothing happens. 
Am I missing something? 
Thanks!

**Comment by manup** [comment]
Please use the Switch Editor to configure the remote (recommended to use the latest deCONZ version 2.0.5.49).

* Select a normal light group which should be controlled
* Edit
* Switch editor

Here you can assign various actions to arbitrary buttons, the color temperature is currently not supported (the implementation had issues), but will be added later.

**Important:** For the switch editor to work please remove the lights from the remote which are assigned directly to it. Since the remote should control only the light group.

**Comment by rikroe** [comment]
Many thank for the quick reply - will use the Switch Editor and wait for updates :)
