### ISSUE TITLE
Not Seeing Sensors

### ISSUE THREAD

**Issue by RickNunn** [ebaauw/homebridge-hue#21]
Hi, I've recently installed homebridge-hue and believe I have set it up correctly. I only want access to the sensors as I have a gen 2 bridge already connected to HomeKit. 

When I run homebridge I get:
```
[11/21/2016, 7:46:51 AM] [Hue] Initializing Hue platform...
[11/21/2016, 7:46:51 AM] Loading 3 accessories...
```

However in the Home app and in the Eve app I can't see any new devices.

My config is as follows:
```
{
	"platform": "Hue",
	"name": "Hue",
	"host": "",
	"users": {
		"###": "###-###"
	},
	"heartrate": 5,
	"timeout": 5,
	"lights": false,
	"alllights": false,
	"groups": false,
	"sensors": true,
	"schedules": false,
	"rules": false
}
```

Does sensors need to be something other than True? I have 2 Hue Motion Sensors, a Hue Tap and a Hue Dimmer.

Thanks

**Comment by ebaauw** [comment]
Hi Rick @RickNunn 
Your config.json looks fine to me.  Setting sensors to true should do the trick.  I don't know what could be wrong.  Homebridge-hue reports only 3 accessories, I'd expect at least 10 (one for the hue bridge, one for the Daylight sensor, 2x3 for the motion sensors, one for the tap, and one for the dimmer). Apparently it does connect to the bridge, or it would report only one accessory.
Could you run homebridge -D and post the debug messages here?
Also, hoping homebridge-hue does indeed create an accessory for the hue bridge, could you do an Identify on that accessory?  Homebridge-hue should dump your bridge config (usernames and ip address masked) to a json file.  Could you attach that file here?
