### ISSUE TITLE
Apple Home App on iOS 11.2 beta crashes when adding hue plugin to homebridge

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-hue#211]
Good evening,

I have several plugins running on homebridge like your ZP plugin, everything runs well until I add the hue plugin to add my osram lights to HomeKit. The Apple Home app crashes immediately.

I then created a second instance of homebridge with just the hue plugin in the config file. It shows up but after adding the virtual hue bridge and selecting a room a window pops up that the accessors can’t be configured and the app crashes again. Weird is if I go into the Elgato Eve app all is added to the standard room. 

Any idea where to search? It used to work earlier but I had to reset my home configuration and do everything from scratch.

**Comment by ebaauw** [comment]
iOS 11.2 beta?  The Apple Home app crashes on Stateless Programmable Switches.

**Comment by CooperCGN** [comment]
It's indeed the 11.2 beta. :( So I assume the bridge is a stateless switch? Any way to change that or just wait for it to hopefully get fixed?

**Comment by ebaauw** [comment]
> So I assume the bridge is a stateless switch?

Yes, for the link button on the bridge.

> Any way to change that [...]?

Specify `"linkButton": false` in config.json and it goes back to being a _Not Supported_ accessory in Home.  Also, make sure not to expose Hue dimmer switches or Hue taps (`"excludeSensorTypes": ["ZLLSwitch", "ZGPSwitch"]` or simply `"sensors": false`).

> [...] or just wait for it to hopefully get fixed?

Or don't run beta versions in a production environment.  Apple's Home app crashed similarly on the Speaker service in the first 11.2 beta (see https://github.com/nfarina/homebridge/issues/1326#issuecomment-340537385) - looks like they're messing with it (hopefully to enable speaker control for Airplay 2).

**Comment by CooperCGN** [comment]
Thanks, I knew about the speaker service. What’s weird though is that the hue taps work, I have them connected over the Hue bridge since the HomeKit update for the hue came out.
I go with the parameter in the config file then and wait what’s happening in future updates.

**Comment by ebaauw** [comment]
> What’s weird though is that the hue taps work

That _is_ weird.  I got word on Slack that 11.2 beta Home also crashes on the Amazon Dash buttons, but I’m not sure if they’re exposed natively or through homebridge.  Time permitting I’ll do some testing with the HomeKit Accessory Simulator and my v2 Hue bridge.

**Comment by CooperCGN** [comment]
The Dash buttons are definitely not HomeKit compatible, the use homebridge too. Seems Apple has changed something in the background then.

**Comment by KhaosT** [comment]
@ebaauw are you sure it's crashing because of programmable switch service? I tried that with 11.2 beta 2 and it's working fine... Do you use `Service.ServiceLabel` by any chance?

**Comment by ebaauw** [comment]
I don’t use `ServiceLabel`, but I do use a custom service (to enable/disable the switch), next to the `Battery` service and the `Stateless Programmable Switch` services per button.  I think the Hue bridge only exposes these and `Battery`.
Looks like I need to spend some quality time with HAS...

**Comment by CooperCGN** [comment]
@ebaauw there is something wrong here, hue motion sensors are suddenly shown as not supported devices too.

Still I think something else is messed up with HomeKit/the programmable switches. As I said I have several Hue Taps in HomeKit exposed from the bridge the 'official' way. I see the little animation when I trigger them but the assigned scene/device isn't responding.

**Comment by KhaosT** [comment]
@CooperCGN if you see the "Not Supported" message, please check if you still using homebridge 0.4.22 or earlier. You should not see that issue if you are using recent Homebridge versions.

**Comment by CooperCGN** [comment]
I'm on version 0.4.31

**Comment by KhaosT** [comment]
@CooperCGN Huh that's interesting... Not really sure what's happening then...

**Comment by ebaauw** [comment]
> hue motion sensors are suddenly shown as not supported devices too.

As exposed by the v2 Hue bridge or by homebridge-hue?

> something else is messed up with HomeKit/the programmable switches

As far a I can tell: Apple’s Home app, not HomeKit.

> I see the little animation when I trigger them but the assigned scene/device isn't responding.

Typically this happens when your AppleTV has lost connection to the Hue bridge or when automations haven’t been synced to the AppleTV, see https://github.com/ebaauw/homebridge-hue/issues/118#issuecomment-311798530.  Do other HomeKit automations work?

**Comment by CooperCGN** [comment]
no, I mean by homebridge-hue. I am going to check on the Apple TV thing, other automations work, maybe I need to restart my hue bridge

**Comment by ebaauw** [comment]
Maybe Home crashes when an assessory has both supported (standard) services and unsupported (custom) services.  I use an additional custom service for the motion sensor as well (also to enable/disable it).

**Comment by ebaauw** [comment]
Found it!  Home crashes on the `minValue` and `maxValue` properties of the `ProgrammableSwitchEvent` characteristic.  Using `validValues` instead works.  Will publish a new version of homebridge-hue later today.

On iOS 11.2 public beta 2, the Hue motion sensors exposed by homebridge-hue display just fine in Apple's Home, with separate tiles for Motion, Light Level, and Temperature.  Also the IKEA Trådfri motion sensor (connected through deCONZ) displays fine, as do all my other sensors (temperature/humidity/pressure, door/window, CLIP).

**Comment by ebaauw** [comment]
Fixed in v0.5.44.

**Comment by Krocko** [comment]
@KhaosT can you please update your homebridge-amazondash plugin also?

**Comment by CooperCGN** [comment]
Thanks, the bridge is now working again, still if I set sensors to true I get this:

![img_0007](https://user-images.githubusercontent.com/29116509/32691968-5f781f66-c710-11e7-9737-e936d38e26a9.jpg)

Maybe it's because I have the motion sensors also connected the 'official' way, although it used to work before.

**Comment by ebaauw** [comment]
Aren’t these the CLIPGenericStatus companion sensors that the Hue app created for each motion sensor?  Could you hold one of the non supported tiles, select details, and post a acreenshot?

**Comment by CooperCGN** [comment]
![img_0008](https://user-images.githubusercontent.com/29116509/32692250-af303a62-c714-11e7-82a5-c28e96fa0dd1.jpg)

**Comment by ebaauw** [comment]
> Aren’t these the CLIPGenericStatus companion sensors that the Hue app created for each motion sensor?

Yes, they are, see name: _MotionSensor 45.Companion_ and/or model: _CLIPGenericStatus_.  You can prevent these from being exposed by including in config.json:
```json
"excludeSensorTypes": ["CLIPGenericStatus"]
```

**Comment by CooperCGN** [comment]
Thanks. So it seems that switches and sensors that are already connected directly over the bridge won't get exposed to HomeKit a second time. To bad, I then need to figure out how to change my bedroom lights not to trigger during the night. I simply switched the sensor of before.

**Comment by ebaauw** [comment]
> So it seems that switches and sensors that are already connected directly over the bridge won't get exposed to HomeKit a second time.

I still need to do some serious testing here (see also #202).  I suspect the Hue bridge and homebridge-hue generate the same UUID for the accessory, based on the sensor's ZigBee mac address.  Consequently, HomeKit sees only one accessory (exposed through two HomeKit bridges).  I suspect the Hue bridge would take precedence, since that's HomeKit certified.  
This would be kinda cool, in that you can switch exposing the sensor between the v2 Hue bridge and homebridge-hue (or move the sensor from one Hue bridge to another) without losing the room assignment and automations in HomeKit, but it prevents seeing two accessories.  
I could generate the accessory UUID from "homebridge-hue" and the sensor's ZigBee mac address, so it would differ from the UUID used by the v2 Hue bridge.  This would cause HomeKit to see all accessories as new accessories, though.  
Oddly, I never encountered this for lights.  Maybe the Hue bridge generates the UUID for light accessories differently.

> I simply switched the sensor of before.

That's exactly why I expose the sensor's `config.on` as `Enabled`.

**Comment by CooperCGN** [comment]
I did that before but wanted to take advantage of the much improved reaction times of the sensors when using them directly over the bridge. Before I walked into the bathroom or bedroom and sometimes had to wait at the door for a few seconds. My wife almost 'killed' me for that and I was actually happy when Philips announced the update to HomeKit. To bad they didn't get the idea on their own that some people might need to disable the sensors in automations. I guess it would be possible for them as you can turn them off manually in the Hue app.

**Comment by ebaauw** [comment]
> My wife almost 'killed' me for that

Best to control your lights from Hue bridge rules instead of from HomeKit automations.  They're quicker and far more reliable, but more troublesome to create and maintain.  I'm using my own scripts for this, see https://github.com/ebaauw/ph.sh, but there's plenty of Hue apps that allow more sophisticated schemes than the Philips Hue app.

> I guess it would be possible for them as you can turn them off manually in the Hue app.

Indeed it would, homebridge-hue proves it.

**Comment by ebaauw** [comment]
> So it seems that switches and sensors that are already connected directly over the bridge won't get exposed to HomeKit a second time.

Did some serious testing and that does _not_ seem to be the case.  See also https://github.com/ebaauw/homebridge-hue/issues/202#issuecomment-343696347.

I tried both iOS 11.1.1 as well as iOS 11.2 public beta 2.  Home shows two accessories when exposing the same switch or motion sensor twice, once using the v2 Hue bridge, and once using homebridge-hue.  Both accessories trigger on button press or when motion is detected (the one exposed by homebridge-hue a bit later, due to the polling delay).

It looks like the Hue app changes the accessory and/or service names of the accessories already exposed through homebridge-hue, when connecting the v2 Hue bridge to HomeKit.  I suspect this is due to using the same `uniqueid`.  The original accessories keep their old room assignments, independent from the room assignments of the v2 Hue bridge exposed accessories.

**Comment by CooperCGN** [comment]
I am sorry that I have to come back again. So I just reset my whole HomeKit config, went back to 11.1 on all devices and now wanted to connect homebridge-hue first and after that the hue bridge itself for the faster response times.

My config.json looks like this after the user-part:
`"lights": true,
"wallSwitch": false,
"sensors": true,
"excludeSensorTypes": ["ZLLSwitch", "ZGPSwitch", "CLIPGenericStatus"]`

When I fire up the Homebridge I still get only a few things added:
[HomebridgeHue] Philips hue: BSB002 bridge v1709131301, api v1.21.0
[HomebridgeHue] Philips hue: 6 accessories
[HomebridgeHue] Initializing platform accessory 'Philips hue'...
[HomebridgeHue] Philips hue: 3 services
[HomebridgeHue] Initializing platform accessory 'Gardenspot oben'...
[HomebridgeHue] Initializing platform accessory 'Gardenspot unten'...
[HomebridgeHue] Initializing platform accessory 'Daylight'...
[HomebridgeHue] Initializing platform accessory 'Neuer Benutzer'...
[HomebridgeHue] Initializing platform accessory 'XFDAnybodyHome'...

Homebridge is running these versions: homebridge-hue v0.5.44, node v8.9.0, homebridge v0.4.31

Any idea why no sensor is showing up? I have restarted the Pi several times, I have deleted the accessories and persist folders for that homebridge instance... I am absolutely clueless.

**Comment by ebaauw** [comment]
As of v0.5.43, homebridge-hue by default doesn't expose Philips lights, switches, and sensors connected to a v2 Hue bridge.  Set `"nativeHomekit": false` in config.json to change that.

If you run `homebridge -D`, you would see debug messages indicating the corresponding resources are (presumably) already exposed by the Hue bridge.

**Comment by CooperCGN** [comment]
I see, now I get confused. So there's no way to just get the motion sensors without the Philips lights?

**Comment by ebaauw** [comment]
I'm afraid I didn't anticipate wanting to expose the Philips sensors and switches, but not the Philips lights.  Maybe I need to split up `"nativeHomekit"` into (re-introduced) `"philipsLights"` and `"philipsSensors"` (and `philipsSwitches`?).

As a workaround, you can set `"nativeHomekit": false` and create a blacklist for the Philips lights.  The blacklist is a resourcelink on the Hue bridge, see #170.

**Comment by CooperCGN** [comment]
Good morning, I went with the blacklist and excluded all original Philips light bulbs and strips. So now my config.json looks like this:
`            "nativeHomekit": false,
            "lights": true,
            "wallSwitch": false,
            "sensors": true
`

I still get no sensors except for the "daylight" of the bridge, during startup homebridge throws the following error:

[HomebridgeHue] TypeError: Cannot read property 'updateCharacteristic' of undefined
Nov 13 08:19:17 raspberrypi homebridge[3471]: at HueSensor.checkBattery (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:923:8)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at HueSensor.checkConfig (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:857:14)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at new HueSensor (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:651:10)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at HueBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:396:26)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:60:18)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:84:26)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:127:15)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at HueBridge.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:882:14)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:186:22)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at emitTwo (events.js:126:13)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Request.emit (events.js:214:7)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1163:10)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at emitOne (events.js:116:13)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Request.emit (events.js:211:7)
Nov 13 08:19:17 raspberrypi homebridge[3471]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1085:12
Nov 13 08:19:17 raspberrypi homebridge[3471]: at Object.onceWrapper (events.js:313:30)

**Comment by ebaauw** [comment]
That doesn’t look good :-(

Could you please post the full output of `homebridge -D`

**Comment by CooperCGN** [comment]
hmm, how do I get that? I'm running a separate instance of homebridge named 'homebridgehue' and it's started as a service. I guess I need to stop the service and then somehow run it manually specifying the correct config.json?

**Comment by ebaauw** [comment]
Indeed, kill the service and run `homebridge -D -U /path/to/config > log 2>&1` or add `-U` to the service definition.

**Comment by CooperCGN** [comment]
I have no idea what happened but it's working now. I restarted my bridge, maybe something got stuck before. No more errors. Sorry for the hassle and thanks for your patience :)
