### ISSUE TITLE
what does "set homekit status fault from 1 to 0" mean

### ISSUE THREAD

**Issue by pponce** [ebaauw/homebridge-hue#214]
I'm getting messages like this below:

Nov 17 05:10:08 raspberrypi homebridge[27067]: [2017-11-17 05:10:08] [Philips Hue 1] Kitchen Top RGB: set homekit status fault from 0 to 1
Nov 17 05:11:50 raspberrypi homebridge[27067]: [2017-11-17 05:11:50] [Philips Hue 1] Kitchen Top RGB: set homekit status fault from 1 to 0

Not sure what status fault means and why it's changing from 0 to 1 and back.

**Comment by ebaauw** [comment]
It corresponds to the `state.reachable` attribute of the light resource, see https://github.com/ebaauw/homebridge-hue/wiki/Characteristics.  Run `homebridge -D` to see debug messages about the changed attribute values, see https://github.com/ebaauw/homebridge-hue#troubleshooting.

**Comment by pponce** [comment]
thanks!
