### ISSUE TITLE
Support for LCT015 and FLOALT

### ISSUE THREAD

**Issue by snozzlebert** [ebaauw/homebridge-hue#215]
Can you add support for the following model id's:
Philips "LCT015" (an extended color light similar to "LCT014")
IKEA "FLOALT panel WS 30x30" (similar to "TRADFRI bulb GU10 WS 400lm" same ct range)

**Comment by ebaauw** [comment]
Can you please post the warning messages that homebridge-hue issues for these?

**Comment by snozzlebert** [comment]
Sorry for the late reply. For the Philips light the warning was:
```[11/24/2017, 4:24:45 PM] [Hue] deCONZ-GW: /lights/1: warning: unknown light model {"ctmax":500,"ctmin":153,"hascolor":true,"manufacturername":"Philips","modelid":"LCT015","name":"Zuiver","state":{"alert":"none","bri":254,"colormode":"ct","ct":366,"effect":"none","hue":8418,"on":false,"reachable":true,"sat":140,"xy":[0.459137,0.411633]},"swversion":"1.29.0_r21169","type":"Extended color light","uniqueid":"00:17:88:01:03:00:aa:00-0b"}```

I don't have the log for the IKEA FLOALT anymore, however I can confirm that the it works as expected in version 0.5.46
Thanks for adding!
