### ISSUE TITLE
questin: use with deCONZ / xiaomi aqara humidity sensor

### ISSUE THREAD

**Issue by Somberland** [ebaauw/homebridge-hue#216]
hello everyone, I'm not quite sure I got that right:

I want to use homebridge-hue with some xiaomi aqara humidity sensors. So I need to install deCONZ on my raspberrypi, and also the zigbee-hardware (RaspBee/ConBee) to use them. than I add these semsors to deCONZ and can use them via homebridge-hue?

thanks for helping me out here :D

**Comment by ebaauw** [comment]
Yes.  I have two Xiaomi Aqara weather sensors myself.
