### ISSUE TITLE
Hue bridge error 2: body contains invalid json

### ISSUE THREAD

**Issue by miliante** [ebaauw/homebridge-hue#22]
Everything works fine until it asks to click the button to create a user. I have clicked several times but I get: "Philips hue: hue bridge error 2: body contains invalid json".

Anything simple I am missing?

**Comment by rudibarani** [comment]
Same problem here...

...and it crashes after some time throwing this error:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 10.0.1.95:6600
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

**Comment by ebaauw** [comment]
My bad.  Seems like I published v0.0.13 too early.  Good thing I'm not superstitious...

Should be fixed in v0.0.14.  If not, please revert to v0.0.12.  You can install a specific version by:

`sudo npm install -g homebridge-hue@0.0.12`

**Comment by rudibarani** [comment]
Thanks for the quick reply. 
v=0.0.14 solved it :)

**Comment by miliante** [comment]
Thank you. I will try tonight.

**Comment by miliante** [comment]
Perfect!!! Thanks.
