### ISSUE TITLE
Not picking up all Hue accessories

### ISSUE THREAD

**Issue by jdshkolnik** [ebaauw/homebridge-hue#220]
I have 2 Hue bridges at home. It's been working fine for a while but, in the last week or two, this plugin has stopped picking up all the accessories from one of the bridges. It's all the same config yet it gets all 9 sensors upstairs yet only 1 out of the 5 downstairs. I'm on the latest version of everything.

**Comment by jdshkolnik** [comment]
I removed both bridges and, when attempting to add, it throws this error:

![fullsizeoutput_53b6](https://user-images.githubusercontent.com/2047520/33190926-d5794bb2-d080-11e7-9fc2-ebc58e4ac102.jpeg)

**Comment by ebaauw** [comment]
Please post the output of `homebridge -D` (see **Troubleshooting** in the README), so I can have a look.

**Comment by CooperCGN** [comment]
@ebaauw If you remember I had the same problem. I added a new lamp and a new Hue tap yesterday and the problems are back again. 
I hope I did the right thing, attached ist the log
[log.txt](https://github.com/ebaauw/homebridge-hue/files/1503284/log.txt)

**Comment by ebaauw** [comment]
Thanks, @CooperCGN.  Could you please post as well your config.json (the line is cut off in this log) and a full dump of your bridge (see **Troubleshooting** in the README)?

Does the error still occur when you remove the `"ZLLTemperature"` from the `"excludeSensorTypes"` array in config.json?

**Comment by ebaauw** [comment]
I might have found a bug that the Battery service isn't created when the sensor's `config.battery` is `0`.  This would cause the error and it would explain why it disappears spontaneously restarting homebridge after a while: the Hue bridge has updated the battery value.

Not sure how the Hue bridge works here - I don't have any motion sensors connected to my Hue bridge at the moment.  But I could image it initialises `config.battery` to `0` and waits for the first report from the sensor before updating it.  This could be up to two hours for the Hue motion sensor.  Would be nice if you can confirm `config.battery` is/was `0` at the time of the error.

**Comment by CooperCGN** [comment]
I guess you’re right as just shortly before that happened the Home app told me that the batteries were almost empty on a few devices. I will install the new version today in the afternoon and then see what happens. How can I find out what state config.battery is in?

**Comment by ebaauw** [comment]
>  I will install the new version today

v0.5.47

> How can I find out what state config.battery is in?

Using the [CLIP API debugger](https://developers.meethue.com/documentation/getting-started) on the Hue bridge or with [`ph.sh`](https://github.com/ebaauw/ph.sh):
```
$ ph_get /sensors/xx/config/battery
100
```

**Comment by CooperCGN** [comment]
OK,now it's getting even more weird. Version 0.5.43 was the one I had installed before. Now with the latest version the service enters a failed state, see attached log.txt. Also attached the dump for the sensors from the bridge and my config.json.
[config.txt](https://github.com/ebaauw/homebridge-hue/files/1503863/config.txt)
[log.txt](https://github.com/ebaauw/homebridge-hue/files/1503860/log.txt)
[sensors.txt](https://github.com/ebaauw/homebridge-hue/files/1503861/sensors.txt)

**Comment by CooperCGN** [comment]
Oh I see, I might need to update my homebridge version first

**Comment by ebaauw** [comment]
```
Nov 26 13:01:50 raspberrypi homebridge[3077]: Error: The requested platform 'Hue' was not registered by any plugin.
```
Homebridge throws this error when you try and initialise a platform from config.json for which the plugin wasn't loaded.  Typically, the plugin hasn't been installed, or has been installed to the wrong directory.  Make sure to install homebridge and homebridge-hue using:
```
sudo npm -g install homebridge --unsafe-perm
sudo npm -g install homebridge-hue
```
