### ISSUE TITLE
Clarify installation section in README.md

### ISSUE THREAD

**Issue by ricni306** [ebaauw/homebridge-hue#224]
The last bullet in the installation section in README.md reads:
"Run homebridge-hue for the first time, press the link button on (each of) your bridge(s), or unlock the deCONZ gateway(s) through their web app. Note the bridgeid/username pair for each bridge and/or gateway in the log output. Edit config.json to include these, see Configuration below."

Is it possible to specify what log output I should be looking at? And/or specify where in deCONZ GUI I could find these values?

**Comment by ebaauw** [comment]
You need to look at the homebridge output.  In the the deCONZ web app (not the GUI!), under Menu, Settings, there’s an Unlock Gateway button.  After you select that, homebridge-hue creates a username for the REST API, which you need to copy/paste into config.json.
