### ISSUE TITLE
Homebridge Version

### ISSUE THREAD

**Issue by NorthernMan54** [ebaauw/homebridge-hue#225]
Just looking at the package.json, and you have homebridge 0.4.33 as a dependancy, and the current homebridge version is 0.4.32.

**Comment by ebaauw** [comment]
https://www.npmjs.com/package/homebridge

**Comment by NorthernMan54** [comment]
Something weird is going on

https://github.com/nfarina/homebridge/blob/master/package.json

Shows 0.4.32

**Comment by ebaauw** [comment]
Yes, but when you install thru npm you get .33.  I suspect a missing or failed sync between the local repository used for `npm publish` and GitHub.

**Comment by NorthernMan54** [comment]
Agreed.  I just changed my alexa version of homebridge to 0.4.33
