### ISSUE TITLE
Adding new TRÅDFRI bulbs -  it showing in Home app

### ISSUE THREAD

**Issue by Mellow73** [ebaauw/homebridge-hue#226]
I have done the Homebridge-hue config. The Homebridge is showing in Home app and the existing Hue and TRÅDFRI bulbs are showing and can be controlled in the Home app. But when adding new TRÅDFRI bulbs they appear in the Hue app but not in the Hone app. 

Do I need to take away the existing Homebridge in the Home app and start over again?

**Comment by ebaauw** [comment]
Did you restart homebridge after adding the new lights?  Currently, homebridge-hue only discovers devices at startup, see #4.

**Comment by Mellow73** [comment]
Thanks for quick feedback. Stupid question, how do I restart Homebridge? ☺️

Regards
Ola

Skickat från min iPhone

**Comment by ebaauw** [comment]
That depends on how you started it.  If you started it manually from the command line, just hit ctrl-C to stop it, and then restart it.  If you started it as a service, you need to restart the service, typically using `systemctl` on unix-like platforms.

**Comment by Mellow73** [comment]
Hmm, i have it on my iMac using Terminal… Is that an answer?

**Comment by ebaauw** [comment]
Yes.  So issue crtl-C in the terminal and homebridge stops.  The issue another `homebridge` in the terminal.

**Comment by Mellow73** [comment]
That worked great!

Another question I have, I have added IKEA TRÅDFRI into the Hue Bridge and Apple Home app. I feel though that the lamps sometimes loose connection and some times says “updating”. Something you know about or is it a setting that is wrong on my side?


Skickat från min iPhone

**Comment by ebaauw** [comment]
> I feel though that the lamps sometimes loose connection and some times says “updating”. Something you know about or is it a setting that is wrong on my side?

Yes this happens, sometimes even followed by "no response", both with homebridge (see https://github.com/nfarina/homebridge/issues?utf8=✓&q=is%3Aissue+is%3Aopen+%22no+response%22) as well as with the Hue bridge (see https://developers.meethue.com/content/homekit-no-response-issue).

As far as I can tell, there's a hickup in the communication between the HomeKit app and the accessory (i.c. homebridge).  It seems to be on the iOS side: sometimes I have one app reporting "No Response" while another app on the same iPhone or iPad works.
