### ISSUE TITLE
Hue Bridge: warning: not using recommeneded Hue bridge api version 1.21.0

### ISSUE THREAD

**Issue by m4d-maNu** [ebaauw/homebridge-hue#228]
Hello,
I habe this warning in the terminal, when I start the Homebridge with the homebridge-hue plugin. Is that warning normal?

**Comment by ebaauw** [comment]
I still need to test the latest bridge firmware, which provides 1.22.0.

**Comment by m4d-maNu** [comment]
Okay, thank you for the answer
