### ISSUE TITLE
Expose some sensors only

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue#229]
Hi @ebaauw,

Is it possible to expose some of the sensors and not others?
I'd like to expose the motion sensors, only for being able to disable them with homekit, without having all my accessories exposed twice (natively and through your plugin).

Thanks.

**Comment by ebaauw** [comment]
Yes, specify `excludeSensorTypes` in config.json (see https://github.com/ebaauw/homebridge-hue/wiki/Configuration) and/or create a resroucelink on the bridge as blacklist, see #170.

**Comment by ooii** [comment]
Thank you @ebaauw. I found the right type in the [https://github.com/ebaauw/homebridge-hue/wiki/Services](services) section of the wiki.
