### ISSUE TITLE
Use Etag and If-None-Match headers to optimize heartbeat calls to deCONZ

### ISSUE THREAD

**Issue by snozzlebert** [ebaauw/homebridge-hue#231]
From: https://dresden-elektronik.github.io/deconz-rest-doc/polling/

> To keep the processing overhead low in the gateway as well as on the client low the API supports the common HTTP ```ETag``` and ```If-None-Match``` headers to prevent full state updates in each polling attempt.

This is implemented for full state and for the /lights and /groups endpoints:
https://github.com/dresden-elektronik/deconz-rest-plugin/commit/b81715122a043210331a995de93f3de6a6a8bdd5
https://github.com/dresden-elektronik/deconz-rest-plugin/commit/ec50881fabe9bfdc1110e78dcc9743d35267aff4

If ```Etag``` is present in the response of a api call, it can be used in the ```If-None-Match``` in the next call to the same url. In this case calls will still be compatible with the Hue bridge, because the Hue bridge doesn't return ```Etag``` headers.

**Comment by ebaauw** [comment]
I’m not going to implement that.  homebridge-hue already subscribes to the websocket notifications issued by deCONZ, so the heartbeat is needed only for changes for which deCONZ issues no notifications.  In my experience, you can set heartrate to 30 without impacting responsiveness.
