### ISSUE TITLE
[question] WiZ LED Lights

### ISSUE THREAD

**Issue by DJay79** [ebaauw/homebridge-hue#232]
I recently discovered [WiZconnected LED Lights]( https://www.wiz.world/en/products/the-collection.html/) and they have a wide variety of LED Lights, some interesting design, for example the WiZ "Quest" or "Elixir", to a fair price. They work without a hub, just by connecting to your Wifi. 
Any chance to see this somehow include in the plugin? Or does anybody know an already existing plugin?
@ebaauw If there is something I can help to figure out with my existing WiZ, of course let me know.

**Comment by ebaauw** [comment]
> Any chance to see this somehow include in the plugin?

No.  These lights are WiFi based, not ZigBee.  They won't connect to the Hue bridge or deCONZ gateway.  They probably have a completely different API, you'd need a different plugin for that.

> Home  Search results for: 'api'
Your search returned no results.

Looks like they haven't published their API.  Even if they had, I would never buy these, as they are cloud based.  Call me paranoid, but I want to run my home automation at home.  No clouds in my sky!
