### ISSUE TITLE
Xiaomi temperature sensor shows weird values

### ISSUE THREAD

**Issue by jsve** [ebaauw/homebridge-hue#233]
I put a temperature sensor in the freezer and it shows up as 640-645 degrees celsius instead of a negative value (temp in freezer is about -18).

I put another in the fridge, and it shows as 6 degrees (should be about 4 degrees). This I'm not certain is an error, and I'll make some tests to verify.

**Comment by ebaauw** [comment]
You're probably running an older version of deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/292.

**Comment by jsve** [comment]
Great help, as always. Seems like my version was a bit old.

After updating the freezer reports as 0 degrees and the fridge still as 6 degrees. I did a api-request and got the response below:

```
"7": {
		"config": {
			"on": true,
			"reachable": true
		},
		"ep": 1,
		"etag": "3f20e0d8a793deac483b4119f2abd1ae",
		"manufacturername": "LUMI",
		"modelid": "lumi.sensor_ht",
		"name": "Temperature 7",
		"state": {
			"lastupdated": "2017-12-21T17:06:29",
			"temperature": 0
		},
		"swversion": "3000-0001",
		"type": "ZHATemperature",
		"uniqueid": "00:15:8d:00:01:b9:16:e6-01-0402"
	}
```

Do you know if deconz even reports values below zero? The sensor should have a range to about -20.

**Comment by ebaauw** [comment]
I don't know about the Mi Temperature/Humidity sensor, but the Aqara weather sensor (Temperature, Humidity, Air Pressure) did register my freezer as -18°C.

You could check the cluster info panel in the deCONZ GUI, to see whether the _Measured Value_ (0x0000) in the _Temperature measurement_ has been updated.
