### ISSUE TITLE
Echo Plus ZigBee Support?

### ISSUE THREAD

**Issue by TerryLansdown** [ebaauw/homebridge-hue#238]
Hi, should it be possible for the plug-in to detect the Echo’s ZigBee home hub? I have homebridge working, but can’t see how to get the Echo’s config details.

Thanks, Terry

**Comment by ebaauw** [comment]
Does it provide a Philips Hue compatible API?

**Comment by TerryLansdown** [comment]
Hi,

I can’t find any published info on that, although I have a Hue Bulb which is recognised by it.

Thanks, Terry

**Comment by ebaauw** [comment]
The communication between the Echo and the Hue bulb is based on ZigBee Light Link (ZLL).  That should (more or less) ensure compatibility between bridges/gateways/hubs and devices from different manufacturers.  homebridge-hue, like any other app, interacts with the bridge/gateway/hub through an API over IP.  As the deCONZ gateway provides (almost) the same REST API as the Hue bridge, homebridge-hue supports both.  homebridge-hue doesn't (and won't) support gateways with a completely different API (like the OSRAM Lightify gateway) - you'd need a different plugin for that.  If Echo haven't published their API, some serious (IP) sniffing will be required to figure out how such a plugin would communicate with the Echo.
