### ISSUE TITLE
Missing some sensors

### ISSUE THREAD

**Issue by jaytay79** [ebaauw/homebridge-hue#24]
On my Hue bridge I have two motion sensors, one Tap switch and one Dimmer switch. I have enabled the sensors in homebridge-hue and when homebridge starts up I see the following:

```
[12/6/2016, 3:33:12 PM] [Hue] Initializing platform accessory 'Philips hue'...
[12/6/2016, 3:33:12 PM] [Hue] Initializing platform accessory 'Daylight'...
[12/6/2016, 3:33:12 PM] [Hue] Initializing platform accessory 'Downstairs tap'...
[12/6/2016, 3:33:12 PM] [Hue] Initializing platform accessory 'Go to sleep'...
```

I can see that the Tap appears as does one of the motion sensors but there's no sign of the second motion sensor or Dimmer switch (I believe that "Go to sleep" is a currently inactive routine I have set-up)

**Comment by ebaauw** [comment]
@jaytay79 That's odd, each hue motion sensor should be exposed as three accessories: one motion sensor, one light sensor, and one temperature sensor.  If you use the hue app, it also creates a CLIPGenericStatus sensor for each hue motion sensor.  I suspect the Go to sleep is also a CLIP sensor created by the app to support the routine.
Please see the Troubleshooting section in README.  Start homebridge -D for more detailed  log massages. Do an Identify on the hue bridge accessory in homekit to dump the bridge configuration. Please post the log messages, config.json and bridge config, so I can check what's happening.

**Comment by jaytay79** [comment]
I'm sorry but I'm not sure what this means: "Do an Identify on the hue bridge accessory in homekit to dump the bridge configuration." Each accessory added by the plugin is showing in Home as "Not Supported" so I suspect that may be part of the issue - https://www.dropbox.com/s/v59icw1rdne0pyg/2016-12-08%2010.06.43.png?dl=0

My config.json is below:

`{
                "platform": "Hue",
                "name": "Hue",
                "host": "",
                "users": {
                        "removed": "removed"
                },
                "heartrate": 5,
                "timeout": 5,
                "lights": false,
                "alllights": false,
                "groups": false,
                "sensors": true,
                "schedules": false,
                "rules": false
        }`

**Comment by ebaauw** [comment]
Hi @jaytay79  your config looks fine to me, as does the screenshot.  Unfortunately, the iOS 10 Home app doesn't provide full homekit support.  You need another app, e.g. Elgato's Eve (free) which provides an Identify button for each accessory.  The accessories are listed under Settings.  You would also need another app to create homekit rules for your tap and dimmer switches, and for the Daylight sensor.
I don't think your issue is related, though.  The iOS 10 Home app does support the motion, light, and temperature sensors homebridge-hue exposes for the Hue motion sensor.
Could you also try and capure the homebridge output (homebridge -D > logfile) and post the logfile here.  It would seem like there's something in your bridge config that homebridge-hue doesn't like.

**Comment by jaytay79** [comment]
Aha, didn't realise the Elgato app could do an identify. I have it installed so have just run an identify and the logs are attached. Thanks for your help so far!

[log.txt](https://github.com/ebaauw/homebridge-hue/files/640178/log.txt)
[hue.json.txt](https://github.com/ebaauw/homebridge-hue/files/640179/hue.json.txt)

**Comment by jaytay79** [comment]
Interesting! I believe these were created by the Hue app itself in the Routines section. I have "Leaving Home" enabled to turn off some lights when I leave the house.

**Comment by ebaauw** [comment]
Could you try v0.0.17 I just published?

**Comment by jaytay79** [comment]
Looking better!

[Hue] Philips hue: found 26 accessories

**Comment by ebaauw** [comment]
That's what's in your bridge, @jaytay79 .  The last 8 sensors are related to your motion sensors.  The funny names are CLIPGenericStatus and CLIPGenericFlag sensors created by the various apps to keep some state (e.g. cycling through scenes).

I quickly created v0.0.17 to expose the Geofence to homekit as a motion sensor (just like ZLLPresence and CLIPPresence).  Now I'm thinking, maybe it should have been an occupancy sensor instead.  Please let me know what you think.

**Comment by jaytay79** [comment]
Thanks for sorting the issue. I think occupancy would be better if possible - I can see that motion has been triggered for one "iPhone" and one "HomeAway" sensor at the moment. Would the other versions of each sensor be triggered after I left the geofenced area?

(Elgato Eve screenshot for reference: https://www.dropbox.com/s/cer2y341yj78tao/2016-12-08%2019.37.08.png?dl=0)

**Comment by ebaauw** [comment]
I don't know, @jaytay79 .  It looks like the iPhone sensors are updated from the app (they're not changed by any rules) and the HomeAway sensors are updated by rules when the iPhone sensor changes.  The first iPhone/HomeWay pair only turns lights off when presence is false; the second pair turns lights on when presence is true (and daylight is off) and turns lights off when presence is false.  My guess would be that the first pair is a leftover from a deleted/overwritten routine.

Technically it's no big deal to change the sensors to occupancy sensors.  The iPhone sensors are type Geofence, but the HomeAway sensors are CLIPPresence sensors.  This is the CLIP equivalent of the Hue Motion's inaptly named ZLLPresence sensors (ZLLMotion would seems more appropriate, but that's probably not in the Zigbee standard).  I'm a bit hesitant to change the mapping of the CLIPPresence sensors.
Looks like I'll be looking into these hue app routines this weekend...

**Comment by ebaauw** [comment]
Ok, I changed the CLIPPresence and Geofence to Occupancy Sensors in v0.0.18.  @jaytay79 could you please check that this works for you?
Also added a check for non-supported sensors in case Philips has some more surprises waiting for us.

**Comment by jaytay79** [comment]
Yup that looks good to me, Home now shows "Occupancy detected" rather than motion.
