### ISSUE TITLE
On/Off lights show brightness control

### ISSUE THREAD

**Issue by grover** [ebaauw/homebridge-hue#241]
I've got the following Busch Jäger switch through deCONZ:

```
{
    "etag": "cd8f553b27919afae6cf67aa4cc0fb13",
    "hascolor": false,
    "manufacturername": "Busch-Jaeger",
    "modelid": "RM01",
    "name": "K-RS-01",
    "state": {
      "alert": "none",
      "bri": 173,
      "on": false,
      "reachable": true
    },
    "swversion": "1.0.0",
    "type": "On/Off light",
    "uniqueid": "d8:5d:ef:11:a1:00:17:4f-12"
  }
```

The switch is visible to HomeKit. It doesn't support dimming or any specific controls, but still shows the brightness control characteristic:

![img_2417](https://user-images.githubusercontent.com/220877/34447601-b3e130d8-ece5-11e7-8a37-de649a376c58.jpg)

Contrast this to dimmable Busch Jäger switches:

```
{
    "etag": "fd7e727f3d97f71480f72bd02292f28c",
    "hascolor": false,
    "manufacturername": "Busch-Jaeger",
    "modelid": "RM01",
    "name": "S-LL-01",
    "state": {
      "alert": "none",
      "bri": 0,
      "on": false,
      "reachable": true
    },
    "swversion": "1.0.0",
    "type": "Dimmable light",
    "uniqueid": "d8:5d:ef:11:a1:00:18:46-12"
}
```

This one has the brightness controls and should keep them.

I'd contribute a patch based on the type of the light unless there's a different way to handle this.

**Comment by grover** [comment]
(I assume that these shouldn't expose state.bri as there's no brightness control. I'll file a separate issue in deCONZ for that.)

**Comment by ebaauw** [comment]
Indeed, this is a bug in the deCONZ REST API: it shouldn't expose `state.bri` for an _On/Off light_ (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/30, https://github.com/dresden-elektronik/deconz-rest-plugin/issues/315.  homebridge-hue looks at the `state` attributes rather than at the `type`.  I considered looking at `type` instead, but then was hit by https://github.com/dresden-elektronik/deconz-rest-plugin/issues/288.

I'll see if I can submit a PR for deCONZ.

**Comment by grover** [comment]
Could've guessed that you've already seen this. Thanks!

**Comment by ebaauw** [comment]
This is more complicated than I thought.  Apparently the ZHA device code for an _On/Off light_ is the same as the ZLL device code for a _Dimmable light_.  And in the wonderful world of ZigBee standards, some manufacturers use the ZHA device codes on a ZLL enpoint or vice versa.  
Then, there appears to be some code in deCONZ reporting 0 or 254 for `state.bri` even if there's no _Level Control_ cluster (based on the _On/Off_ cluster).

Indeed, best open an issue in deCONZ.  Could you please post there a screenshot of these nodes in the deCONZ GUI.  In particular showing what endpoints and what device types they advertise, and whether they have a _Level Control_ cluster (0x0008).

**Comment by grover** [comment]
Oh my. Will do although that will likely have to wait until I've managed to update the firmware in these wall switches. Might be that this is a side effect of the old firmware they're on.

**Comment by ebaauw** [comment]
OK.  Probably best to delete the switch from deCONZ after the firmware update and re-pair them to make sure no leftovers from the previous configuration remain.  One of my OSRAM lights still shows an _Electrical Measurement_ cluster in the deCONZ GUI, even thought its current firmware no longer supports it.

**Comment by grover** [comment]
This is the change I'll run with for now: https://github.com/grover/homebridge-hue/commit/cc2459db9734d62ac562bd220c38cadffe8a4682 - works as far as I can tell.

**Comment by ebaauw** [comment]
That will do it, although it is somewhat crude.  Instead of deleting `state.bri` from the gateway response, it would be nicer to check for `type` in `setConfig()` and set/update `this.config.bri` accordingly.

Not sure what happens when you change the `state.bri` value through the REST API.  I guess the characteristic might still appear after that.  I'm cleaning up the HueLights code and will make sure to check for `this.config.bri` before processing `state.bri` during heartbeat or websocket notifications.

**Comment by manup** [comment]
In this case the problem is that the switch reports it supports level cluster, which has no function. Will need to add a if () branch here to ignore bri.

**Comment by ebaauw** [comment]
Hey @manup, I thought you were out.  Thanks for chiming in!

Hm, both switches have the same `modelid` but a different `type`?  They're probably the same control element, but different inserts?

@grover in that case it's best to add a `fix` function for this model in `knownLights`, setting `this.config.bri` to false.

**Comment by grover** [comment]
That's a good hint. I'll update the branch to provide a fix function. Didn't see them before.

**Comment by ebaauw** [comment]
As I said, I'm cleaning up the HueLights code.  This was introduced two days ago, https://github.com/ebaauw/homebridge-hue/commit/3a8da3d85380bc790c68bdc3424220464f4d94d3.
