### ISSUE TITLE
Osram LIGHTIFY Outdoor Flex RGBW

### ISSUE THREAD

**Issue by MikeDeltaHH** [ebaauw/homebridge-hue#242]
Hi!
After install the plugin hb works fine for some minutes and crashed... can se the following entries in the livelog:

Dez 29 23:10:49 homebridge homebridge[24449]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389
Dez 29 23:10:49 homebridge homebridge[24449]: var mac = hueDevices[lightid].uniqueid.split(':');
Dez 29 23:10:49 homebridge homebridge[24449]: ^
Dez 29 23:10:49 homebridge homebridge[24449]: TypeError: Cannot read property 'uniqueid' of undefined
Dez 29 23:10:49 homebridge homebridge[24449]: at _getAid (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389:32)
Dez 29 23:10:49 homebridge homebridge[24449]: at hueToHK (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:167:14)
Dez 29 23:10:49 homebridge homebridge[24449]: at Object.handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:55:24)
Dez 29 23:10:49 homebridge homebridge[24449]: at HAPServer._handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:875:7)
Dez 29 23:10:49 homebridge homebridge[24449]: at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:214:39)
Dez 29 23:10:49 homebridge homebridge[24449]: at emitNone (events.js:105:13)
Dez 29 23:10:49 homebridge homebridge[24449]: at IncomingMessage.emit (events.js:207:7)
Dez 29 23:10:49 homebridge homebridge[24449]: at endReadableNT (_stream_readable.js:1059:12)
Dez 29 23:10:49 homebridge homebridge[24449]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Dez 29 23:10:49 homebridge homebridge[24449]: at process._tickCallback (internal/process/next_tick.js:180:9)
Dez 29 23:10:49 homebridge systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Dez 29 23:10:49 homebridge systemd[1]: Unit homebridge.service entered failed state.

This is my config:

{
			"platform": "Hue",
			"users": {
				"001788FFFE22018B": "xGUJmf4CLQ1TNtRLENPtYTFEaCxrg6SRWediAVPP"
			},
			"lights": true

I use the Osram "LIGHTIFY Outdoor Flex RGBW!

Can you help me?

Regards!
Mike

**Comment by ebaauw** [comment]
> /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js

This file is not part of my plugin, nor of (the current version of) the HAP-nodeJS package used by (the current version of) homebridge.

Are you sure you installed homebridge-hue?  Can you please post the start of the log?

**Comment by NorthernMan54** [comment]
@ebaauw Erik, that is my fork of HAP-NodeJS that supports alexa.

@MikeDeltaHH Please raise an issue here for this, and include a DEBUG log.  Tks

https://github.com/NorthernMan54/homebridge-alexa

PS I think you need to ask Alexa to discover devices again.

**Comment by MikeDeltaHH** [comment]
Thankx, will i do!

**Comment by ebaauw** [comment]
See https://github.com/NorthernMan54/homebridge-alexa/issues/38.

I'll add the _LIGHTIFY Outdoor Flex RGBW_ to the list of known lights.  Does it only provide a single resource?  Most RGBW controllers provide multiple.

**Comment by MikeDeltaHH** [comment]
The Outdoor Flex provide a single ressource! Thanks for add! :)

**Comment by ebaauw** [comment]
Added in v0.5.55.
