### ISSUE TITLE
TypeError: host.split is not a function

### ISSUE THREAD

**Issue by Brklnbnc** [ebaauw/homebridge-hue#247]
Just updated to the latest version 0.5.54 but get this error when starting up HomeBridge:

[2018-1-1 20:59:42] [Philips Hue] homebridge-hue v0.5.54, node v8.9.3, homebridge v0.4.33
/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:69
const elt = host.split('.');
^
TypeError: host.split is not a function

**Comment by ebaauw** [comment]
Could you please post your config.json?

**Comment by Brklnbnc** [comment]
{
    "bridge": {
        "name": "Homebridge Hue",
        "username": "DD:21:3E:E2:DE:45",
        "port": 51827,
        "pin": "031-45-165"
    },
    "description": "Configuration file Homebridge Hue",
    "platforms": [
        {
            "platform": "Hue",
            "name": "Philips Hue",
            "host": ["192.168.1.101"],
            "users":
                {
                "001733FFFE20C331":"XaqXrRx5IB8oJvsivvJnUizSwwXUb6MOAI3KetdfO"
                },
            "lights": true
        }
    ],
    "accessories": [
    ]
}

**Comment by ebaauw** [comment]
Thanks.  As I expected.  If you remove the `[` and `]` or change the key to `"hosts"`, homebridge-hue@0.5.54 won't crash.  Will publish v0.5.55 shortly, which once again will accept this config.json.

**Comment by ebaauw** [comment]
Fixed in v0.5.55.

**Comment by Brklnbnc** [comment]
Installed version 0.5.55 and it's working again. Thanks so much Erik.
