### ISSUE TITLE
blacklist don't work anymore with v0.5.55

### ISSUE THREAD

**Issue by Krocko** [ebaauw/homebridge-hue#248]
With v0.5.55 `blacklist` don't work. `lightlist` works. If i install v0.5.54 `lightlist` is handled as `blacklist`.

**Comment by ebaauw** [comment]
Yeah, just noticed that, sorry.  Will be fixed in v0.5.56, see 3b4d04c1ad487b17dd9d10512e4cd78e93273b1b.

**Comment by Krocko** [comment]
Thank you. Have you any ETA for vo.5.56?

**Comment by ebaauw** [comment]
> Have you any ETA for vo.5.56?

Now.

**Comment by Krocko** [comment]
Fast as always. ;-)
