### ISSUE TITLE
OSRAM Lightify connected to Hue Bridge not working with 0.5.56 or higher

### ISSUE THREAD

**Issue by DSchumacher2104** [ebaauw/homebridge-hue#251]
Hello!

Since the "state.reachable"-change with homebridge-hue v0.5.56 i can't control my OSRAM Lightify devices connected to my Hue bridge with HomeKit(Apple's HomeApp, cause the Hue bridge/Philips Hue App stated them as "not reachable" but they work perfect, when controlling them with the Hue App. I haven't found a way to fix the "not reachable" state of the Lightify lights.

Is it possible to integrate a switch in config which allows to use the old Status Fault characteristic?

I'vw gone back v0.5.55 now and they work with HomeKit/Apple's HomeApp.

Thanks for your work!
Daniel

**Comment by ebaauw** [comment]
I'm about to revert the reachable change in v0.5.58 - it seems to do more harm than good.

**Comment by DSchumacher2104** [comment]
Okay, that sounds good. Thank you!

**Comment by ebaauw** [comment]
v0.5.58 is out.

**Comment by DSchumacher2104** [comment]
I have installed v0.5.58 and the lights are accessible, thank you!
