### ISSUE TITLE
[Question] How can I disable motion sensor for a given duration?

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue#252]
Hi,

Any idea how I can disable a motion sensor (from a dimmer) for a given duration? A hue labs formula exists but it does not allow duration lower than 45 minutes.

Thanks.

**Comment by ebaauw** [comment]
Enabling or disabling the motion sensor is done through the `config.on` attribute of the ZLLPresence sensor resource.  To disable, set `on` to false, to re-enable, set `on` to true.

I don't think you can use `config` attributes in rule conditions, so you'd probably need a proxy CLIPGenericFlag sensor to automate re-enabling the motion sensor.

To disable it from the dimmer switch (e.g. on Long Release of the Off button):
```
{
  "name": "Disable motion sensor" ,
  "conditions": [
    {
      "address": "/sensors/<dimmer>/state/buttonevent",
      "operator": "eq",
      "value": "4003"
    },
    {
      "address": "/sensors/<dimmer>/state/lastupdated ",
      "operator": "dx"
    }
  ],
  "actions": [
    {
      "address": "/sensors/<presence>/config",
      "method": "PUT",
      "body": { "on": false }
    },
    {
      "address": "/sensors/<flag>/state",
      "method": "PUT",
      "body": { "flag": true }
    }
  ]
}

```
and you'd re-enable it automatically after 1:30 hours through:
```
{
  "name": "Re-enable motion sensor" ,
  "conditions": [
    {
      "address": "/sensors/<flag>/state/flag",
      "operator": "eq",
      "value": "true"
    },
    {
      "address": "/sensors/<flag>/state/lastupdated ",
      "operator": "ddx",
      "value": "PT01:30:00"
    }
  ],
  "actions": [
    {
      "address": "/sensors/<motion>/config",
      "method": "PUT",
      "body": { "on": true }
    },
    {
      "address": "/sensors/<flag>/state",
      "method": "PUT",
      "body": { "flag": false }
    }
  ]
}
```
Note that after rebooting the Hue bridge, a CLIPGenericFlag sensor's `state.flag` is initialised to false and a ZLLPresence sensor's `config.on` is initialised to true, so the flag holds the inverse of `config.on`.

**Comment by ooii** [comment]
Hi Eric,

Thanks a lot for your help.
And all the best for this new year.
