### ISSUE TITLE
Node version greater than required, but not recognised as such?

### ISSUE THREAD

**Issue by TerryLansdown** [ebaauw/homebridge-hue#254]
#### Issue

Can Ignore this warning? When I query my node version the terminal reports v9.3.0?
Is it a bug or can I fix remove the warning?

Thanks for your efforts with this plug-in.

Best wishes, Terry

#### Log Messages

```
From the terminal after launching homebridge:

Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^8.9.3 which does not satisfy the current Node version of v9.3.0. You may need to upgrade your installation of Node.
```

**Comment by ebaauw** [comment]
I develop and test homebridge-hue against the latest LTS version of NodeJS.  Using the next major version might work, but might also lead to incompatibilities.

**Comment by TerryLansdown** [comment]
Ah, of course. Many thanks and apologies. 

For anyone who may have missed the subtlety, the specific LTS (Long Term Support) version was lower than the default install of node. I needed to:
- remove node, reinstall using the 'brew install node@8' option
- this broke homebridge, so I needed to uninstall and rebuild this then reinstall using the newly installed LTS version of node.

Thanks for clarifying.

Best wishes, Terry

**Comment by ebaauw** [comment]
Yeah, you need to uninstall homebridge when changing to another major version of node.  The mdns library won’t be recompiled when just installing homebridge over an existing installation.  Hopefully, we’ll be free of this hazzle soon, once homebridge uses the native javascript mdns library, see https://github.com/KhaosT/HAP-NodeJS/pull/495.
