### ISSUE TITLE
Hue Motion Sensor disappeared

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-hue#256]
I don't know what you changed, I just upgraded to the latest version and my motion sensors are gone. Has it anything to do with the battery status problem I reported earlier? I saw that you fixed a bug that services based on /sensor resources don't return their value.

All my actions are messed up :(

**Comment by CooperCGN** [comment]
Just reverted to v0.5.56 and they are back.

**Comment by ebaauw** [comment]
> I don't know what you changed, I just upgraded to the latest version and my motion sensors are gone. 

Nothing that would cause that.  My 11 Hue motion sensors work just fine with v0.5.60.  Did homebridge-hue issue any errors?

> Has it anything to do with the battery status problem I reported earlier?

Maybe, but gone is different that showing no value.  Could you please attach the dump file that v0.5.60 made on startup (see https://github.com/ebaauw/homebridge-hue#debug-dump-file)?  v0.5.56 doesn't create the dump file, so it should still be there from v0.5.60.

> I saw that you fixed a bug that services based on /sensor resources don't return their value.

That caused sensors showing no value, not disappearing.

**Comment by CooperCGN** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/1612980/homebridge-hue.json.gz)

**Comment by CooperCGN** [comment]
What is weird, the json still shows v.0.5.56

**Comment by ebaauw** [comment]
My bad, I introduced the dump file in v0.5.54.

I don't see anything weird in this dump, ... of course - no problems now.

Did you power cycle the Hue bridge when upgrading to the latest version of homebridge?  Does it reboot occasionally?  homebridge-hue should log ETIMEDOUT errors while the bridge is rebooting (which show the IP address still unmasked... oops).

Are you running homebridge as a service?  If so, the logs from starting the latest version could still be available through `journalctl -au homebridge` or in one of the `syslog` files in `/var/log` (this assumes you're running on a Raspberry Pi).  And could you change the service to run `homebridge-hue -D` (see https://github.com/ebaauw/homebridge-hue#debug-log-file), so we have a full log the next time this happens?

**Comment by CooperCGN** [comment]
I think I found something in the log file
[syslog.txt](https://github.com/ebaauw/homebridge-hue/files/1613440/syslog.txt)

**Comment by ebaauw** [comment]
That _is_ something, thanks.  Which version of homebridge-hue was this?

**Comment by CooperCGN** [comment]
0.5.60 throws this error, 0.5.54 does not. That’s why my idea was it has something to do with the fix you brought up with 0.5.57?

**Comment by ebaauw** [comment]
It’s a typo: `setvalue()` instead of `setValue()`, introduced in v0.5.58, dec927074f59288cea15c1a37ac89626d8a6ca08.

**Comment by ebaauw** [comment]
Fixed in v0.5.61.

**Comment by CooperCGN** [comment]
Perfect! Got it running after first encountering errors which were due to my outdated homebridge version :)

I know this is not the right place but I know you have deCONZ running. I got a Raspbee for my Pi but even after extensive contact to Dresden support can't get it running. I also got a separate Pi and used their preconfigured sd card image. Still the deCONZ software tells me after every reboot that there is an firmware update to run and I can't get the Raspbee to show up as the basic node. Have you ever encountered something during setup? I am already assuming that the Raspbee might be defective.

**Comment by ebaauw** [comment]
Did you disable login on the serial port?

**Comment by CooperCGN** [comment]
This is what my cmdline.txt looks like:
`dwc_otg.lpm_enable=0  console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles`

In the config.txt I added 
`enable_uart=1`

I still think that it is a problem with the serial port, which I definitely enabled in the raspi-config tool

**Comment by ebaauw** [comment]
What about `$ systemctl status serial-getty@ttyAMA0.service`?  You need to _enable_ the port, but _disable_ logins from it.

**Comment by CooperCGN** [comment]
Response is:
serial-getty@ttyAMA0.service - Serial Getty on ttyAMA0
   Loaded: loaded (/lib/systemd/system/serial-getty@.service; disabled)
   Active: inactive (dead)
     Docs: man:agetty(8)
           man:systemd-getty-generator(8)
           http://0pointer.de/blog/projects/serial-console.html

**Comment by ebaauw** [comment]
> Perfect! Got it running after first encountering errors which were due to my outdated homebridge version :)

There's issues with homebridge@0.4.35.  Best revert to homebridge@0.4.33 and upgrade to homebridge-hue@0.5.62, see #258.

As for the RaspBee problem: I'm out of ideas.  Best open an issue on https://github.com/dresden-elektronik/deconz-rest-plugin.
