### ISSUE TITLE
Hide the Button from the Bridge?

### ISSUE THREAD

**Issue by m4d-maNu** [ebaauw/homebridge-hue#261]
Can I hide the Button from the Hue Bridge?

I tried it with `linkButton` and with `ZPGSwitch` and now with `StatelessProgrammableSwitch` in the excludeSensorTypes List. But the button does not disappear

**Comment by ebaauw** [comment]
`linkButton` should work, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by m4d-maNu** [comment]
Unfortunately, no.

I even removed the Homebridge with the Hue plugin from Homekit and added it. But the button from Hue Bridge is still there.

Here my config.
```
 {
	    "platform": "Hue",
            "name": "Osram",
            "host": "192.168.1.10",
            "users": {"001788FFFE78F45F": "6lgPwvHW1pRz1nAukga8t-wvUpydaWzb7ruMJQyh"},
	    "sensors": "true",
 	    "excludeSensorTypes": ["CLIP", "CLIPPresence", "CLIPGenericStatus", "Daylight", "ZPGSwitch", "linkButton" ],
	    "lights": "true",
 	    "nativeHomeKit": true
          }

```

**Comment by ebaauw** [comment]
Again, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration: 
- `"linkButton"` isn't a sensor type, it's a key on its own;
- The values for `"lights"` and `"sensors"` are Boolean, not string;
- You don't need `"nativeHomeKit"` - that's true by default;
- You don't need `"ZPGSwitch"` in `"excludeSensorTypes"`.  This is the Hue tab, which is already excluded by `"nativeHomeKit"`, as are the Hue dimmer switch (`"ZLLSwitch"`) and the Hue motion sensor (`"ZLLPresence"`, `"ZLLLightLevel"`, and `"ZLLTemperature"`);
- You don't need `"CLIPPresence"` and `"CLIPGenericStatus"` in `"excludeSensorTypes"`.  They're already excluded by `"CLIP"`.

Try:
```json
{
	    "platform": "Hue",
            "name": "Osram",
            "host": "192.168.1.10",
            "users": {"001788FFFE78F45F": "6lgPwvHW1pRz1nAukga8t-wvUpydaWzb7ruMJQyh"},
	    "sensors": true,
 	    "excludeSensorTypes": ["CLIP", "Daylight"],
            "linkButton": false,
	    "lights": true
}
```
I'm not sure what sensors you're trying to expose, but this will only expose the undocumented `Geofence` sensors created by the Hue app _Home & away_ routines.

**Comment by m4d-maNu** [comment]
Thx, the button is gone.

But now an unsupported HomeKit device is available. It has the same name as the button before.

**Comment by ebaauw** [comment]
That's the accessory for the Hue bridge itself.  Setting `"linkButton"` to false removes the `StatelessProgrammableSwitch` from the Hue bridge accessory, but not the accessory.  You cannot get rid of it, homebridge-hue needs it.  Under Eve, you can change the heartrate, simulate pressing the button, initiate a touchlink or set the transitiontime with this service.

**Comment by m4d-maNu** [comment]
Ah okay, andere Plugins haben nicht ein solches Zubehör. Daher war ich ein wenig irritiert. Aber der LinkButton ist nun weg, denn diesen benötige ich nicht.

Nochmals danke, das Iusse kann dann zugemacht werden
