### ISSUE TITLE
Problem with Ikea Tradfri Status

### ISSUE THREAD

**Issue by Maxx4** [ebaauw/homebridge-hue#262]
Hello everybody!

I have got a Problem with the Homebridge Hue Plugin and the Ikea bulbs. I have setted up the Plugin and the Bulbs where shown in Homekit. But if i turn off the light switch, Homekit didn´t show that they turned off. The Status doesnt change, the bulbs are "on" in Homekit. The Hue Bulbs are schowing " no connection" in this case.
Is this a configuration problem?

Thanks for the help and sorry for my bad english ;)

**Comment by ebaauw** [comment]
> But if i turn off the light switch, Homekit didn´t show that they turned off.

Set `"wallSwitch": true` in config.json if you want homebridge-hue to report the lights as Off when they're unreachable.  

Note that the Hue bridge cannot detect whether the lights are actually powered off, only that it cannot reach them.  With the `wallSwitch` setting, lights might be reported Off in HomeKit while they're actually still on.

Note that, depending on the number of lights connected to your bridge, it might take some time (a minute or more), before the bridge detects that a powered-off light has become unreachable.

Also note that sometimes the Hue bridge reports lights as unreachable, even though they're working perfectly.  With the `wallSwitch` setting, you cannot control the lights from HomeKit in that case.

> The Status doesnt change, the bulbs are "on" in Homekit. The Hue Bulbs are schowing " no connection" in this case.

Sounds like homebridge-hue v0.5.56 or v0.5.57.  Better upgrade to the latest version, which, again, uses _Status Fault_ to indicate unreachable lights.  See https://github.com/ebaauw/homebridge-hue/releases.

**Comment by Maxx4** [comment]
Hi!

Thanks for the help. I added the wallswitch in the config and now the Status changed to off if i turn off the Lightswitch. Hue bulbs are natively added in the Hue bridge, thats working fine in my configuration!
