### ISSUE TITLE
unauthorized user?

### ISSUE THREAD

**Issue by FezVrasta** [ebaauw/homebridge-hue#265]
When I run homebridge I get:

```
[2018-1-14 12:48:32] [Hue] Initializing Hue platform...
[2018-1-14 12:48:32] [Hue] homebridge-hue v0.5.64, node v8.9.4, homebridge v0.4.36
[2018-1-14 12:48:38] [Hue] Home: BSB002 bridge v1711151408, api v1.22.0
[2018-1-14 12:48:38] [Hue] Home: bridge request 2: get /
[2018-1-14 12:48:38] [Hue] Home: bridge error 1: unauthorized user
```

What could it be?

**Comment by ebaauw** [comment]
The Hue bridge doesn't accept the username (key) in config.json.

**Comment by FezVrasta** [comment]
thanks, I removed the "users" section and it worked.

**Comment by romanlucas** [comment]
sorry to follow up on this, but I have the same problem.
I get this error on first startup of Homebridge after a complete new installation of Homebridge and the Homebridge Hue plugin. I never got the token to edit the config.json. deleting the "users" section as recommended by FezVrasta has no effect. 
Any ideas?

**Comment by ebaauw** [comment]
What error do you get?

**Comment by romanlucas** [comment]
hey,
thanks for your response.
this is the error-message:

```
Dec 05 19:36:05 raspberrypi systemd[1]: Started Homebridge.
Dec 05 19:36:06 raspberrypi homebridge[1568]: [12/5/2019, 19:36:06] Loaded config.json with 0 accessories and 1 platforms.
Dec 05 19:36:06 raspberrypi homebridge[1568]: [12/5/2019, 19:36:06] ---
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] Loaded plugin: homebridge-hue
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] Registering platform 'homebridge-hue.Hue'
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] ---
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] Loading 1 platforms...
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] [Hue] Initializing Hue platform...
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] [Hue] homebridge-hue v0.11.44, node v12.13.1, homebridge v0.4.50
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] Loading 0 accessories...
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] [Hue] 192.***.***.50: bridge request 1: get /config
Dec 05 19:36:09 raspberrypi homebridge[1568]: [12/5/2019, 19:36:09] [Hue] 192.***.***.50: bridge error 1: unauthorized user
Dec 05 19:36:24 raspberrypi homebridge[1568]: [12/5/2019, 19:36:24] [Hue] 192.***.***.50: bridge request 2: get /config
Dec 05 19:36:24 raspberrypi homebridge[1568]: [12/5/2019, 19:36:24] [Hue] 192.***.***.50: bridge error 1: unauthorized user
```

**Comment by ebaauw** [comment]
What’s your config.json?  What bridge do you have?

**Comment by romanlucas** [comment]
The bridge is a raspberry pi with diy hue emulator. Had it running flawlessly with your plugin until two days ago. Then I did the usual updates via apt-get update/upgrade and also updated to the latest node version. Since then it stopped working and gave me the above mentioned error. So i did a fresh reinstall of the raspberry, diy hue, Homebridge and your plugin. Unfortunately its still not working.
This is my config.json:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [],
    "platforms": [
        {
                "platform": "Hue",
                "users": {
                        "": ""
                },
                "hosts": "192.168.178.50",
                "lights": true
                }
]
}
```

**Comment by ebaauw** [comment]
See #567: it would seem that diyhue doesn’t (no longer?) implements the full Hue API.  Did you update diyhue as well?

What’s the output of `ph -H 192.168.178.50 config`?

**Comment by romanlucas** [comment]
I regularly start the diyhue automatic install-script wich updates diyhue if there is a new version. I did it before it stoped working, but I am not sure if there really was an update. but its definitely the actual version.
output of ph -H 192.168.178.50 config is:

```
ph: error: 192.168.178.50: 1 unauthorized user
ph: fatal: 192.168.178.50: not a Hue bridge nor deCONZ gateway
```

**Comment by ebaauw** [comment]
So it no longer support an unauthenticated GET of `/api/config`.  As a workaround, you might try and create a username by `ph -H 192.168.178.50 createuser` and use that for homebridge-hue.

**Comment by romanlucas** [comment]
ph -H 192.168.178.50 createuser leads to the same "unauthorized user" error.
@andre68723 created an issue regarding this problem in the diyhue repository, maybe we can get a solution there.
