### ISSUE TITLE
Add ip_address ?

### ISSUE THREAD

**Issue by ostgardh** [ebaauw/homebridge-hue#267]
Hi.

Great plugin.
But is it possible to add specific hub ip?
I have 2 Hub and One of this Hub is not working to homebridge-hue.

If I have only one hue running the homebridge-hue is ok.
So If is possible to add specific ip is solve my problem.

//

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by ostgardh** [comment]
Ok.

I missed this.
Thanks..

//P
