### ISSUE TITLE
How to get dimmers exposed?

### ISSUE THREAD

**Issue by iRonin** [ebaauw/homebridge-hue#269]
I'm looking to expose Hue dimmers to be able to program long presses on buttons - how do I get your plugin to expose them? Here is my config:

```
	      "sensors": false,
	      "nativeHomeKitSensors": true,
	      "excludeSensorTypes": ["CLIP", "Geofence", "Daylight"],
	      "lights": false
```

It actually does not expose anything. Here is the log:

```
[2018-1-16 17:41:50] [Hue] Philips hue: BSB002 bridge v1711151408, api v1.22.0               
[2018-1-16 17:41:50] [Hue] Philips hue 2: BSB002 bridge v1711151408, api v1.22.0             
[2018-1-16 17:41:51] [Hue] Philips hue 2: 1 accessories                                      
[2018-1-16 17:41:51] [Hue] Philips hue: 1 accessories                                        
[2018-1-16 17:41:51] [Hue] masked debug info dumped to /homebridge/homebridge-hue.json.gz    
[2018-1-16 17:41:51] [Hue] Initializing platform accessory 'Philips hue'...                  
[2018-1-16 17:41:51] [Hue] Philips hue: 3 services                                           
[2018-1-16 17:41:51] [Hue] Initializing platform accessory 'Philips hue 2'...                
[2018-1-16 17:41:51] [Hue] Philips hue 2: 3 services 
```

**Comment by ebaauw** [comment]
No, you need to set `”sensors”: true, “nativeHomeKitSensors”: false`.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by iRonin** [comment]
Thank you! Unfortunately now I get the following error (which I was getting previously with the default config):

```
[2018-1-17 09:40:42] [Hue] Initializing platform accessory 'Hue temperature sensor 1'...     
[2018-1-17 09:40:42] [Hue] Error: Cannot add a bridged Accessory with the same UUID as anothe
r bridged Accessory: 8da97133…
```

Is it because I already have this accessory added to HomeKit? Is there a way to identify the accessory?

Also, the motion sensors now get initialized which I don't want. Is my `excludeSensorTypes` setting ok?

**Comment by iRonin** [comment]
PS. When this error is thrown the whole homebridge does not respond is Homekit (I get readings in homebridge log but it's unresponsive - all accessories).

**Comment by ebaauw** [comment]
Can you please attach the debug dump file that homebridge-hue created (see https://github.com/ebaauw/homebridge-hue#debug-dump-file) and the debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file).

> PS. When this error is thrown the whole homebridge does not respond is Homekit (I get readings in homebridge log but it's unresponsive - all accessories).

homebridge throws this error and because of it, it doesn't start it's server to HomeKit, so yes, it's unresponsive from a HomeKit perspective.

**Comment by iRonin** [comment]
> Most likely you connected a Hue motion sensor to one bridge, then reset it and connected it to the other bridge

That's very likely - I maxed out one bridge and had to move certain accessories to the other one…

**Comment by iRonin** [comment]
Is there any way to get UUIDs of all accessories from the Hue API?

**Comment by iRonin** [comment]
I managed to remove that zombie sensor.

How do I get only dimmers listed, without motion sensors?

**Comment by ebaauw** [comment]
> Is there any way to get UUIDs of all accessories from the Hue API?

No, the UUIDs are generated by homebridge-hue, from the device’s ZigBee MAC address.  The Hue bridge doesn’t know about these.  You can get the MAC adress through the API, it’s the first part (before the `-`) of the `uniqueid` attribute of a light or sensor resource.  homebridge-hue exposes this as the `Serial Number` in the `Accessory Information`service.

Add `”ZLLPresence”`, `”ZLLLightLevel”`, and `”ZLLTemperature”` to `excludeSensorTypes` in config.json.

**Comment by iRonin** [comment]
Thank you for explaining the UUID, it took me a while to find out the messed up accessory.
Thanks for the sensor tip.

Do you know what's the easiest way to remove taps exposed by Hue bridge directly to HomeKit from Home?

**Comment by ebaauw** [comment]
As far as I know it's all or nothing: either you don't pair the Hue bridge with HomeKit, or it exposes all Hue lights, taps, dimmer switches, and motion sensors.

**Comment by iRonin** [comment]
Thanks for the plugin, at last I can program the long presses!
