### ISSUE TITLE
dependency on homebirdge v0.4.36

### ISSUE THREAD

**Issue by Kugelfang666** [ebaauw/homebridge-hue#270]
Hi,

I'm currently running homebirdge on an home assistant installation. Judging by the homebridge git, the latest homebridge release is v0.4.32 which is automatically installed by the home [assistant addon](https://github.com/hassio-addons/addon-homebridge). Also the addon automatically installs teh latest version of your plugin as homebridge-hue is part of my config.json.. However, as your plugin has a dependancy on homebirdge v0.4.36 it trows an error and does not start. 

Is there any way around it?

**Comment by ebaauw** [comment]
Lastest homebridge version is 0.4.36, see https://www.npmjs.com/package/homebridge and #225.

You can edit package.json and change the dependency... at your own risk.  I develop and test against the listed version only.

**Comment by Kugelfang666** [comment]
ok, i see. Thats very odd as the latest released version on the homebridge [git is 0.4.32.](https://github.com/nfarina/homebridge/releases). In any case. this question can be closed and i apprechiate your fast response. I guess I'll have to figure it out somhow :-)
