### ISSUE TITLE
Error initializing homebridge

### ISSUE THREAD

**Issue by FezVrasta** [ebaauw/homebridge-hue#271]
#### Issue
I added some more lights, restarted the homebridge and now I get this error.
I see something related to PiHole blocking a resource, but I can't understand which URL is being blocked.... Also, I always get an error for https://dresden-light.appspot.com/, even before I installed PiHole.

I tried to disable PiHole and run `sudo /etc/init.d/dnsmasq restart` to flush the DNS cache but I get the same error.

#### Log Messages

```
[2018-1-20 18:17:10] [Hue] dresden appspot ipv6: communication error ENETUNREACH on https://dresden-light.appspot.com/
[2018-1-20 18:17:15] [Hue] Home: BSB002 bridge v1711151408, api v1.22.0
[2018-1-20 18:17:15] [Hue] undefined: warning: ignoring unknown bridge/gateway "\n    <html><head>\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\"/>\n        <link rel='stylesheet' href='/pihole/blockingpage.css' type='text/css'/>\n    </head><body id='splashpage'><img src='/admin/img/logo.svg'/><br/>Pi-<b>hole</b>: Your black hole for Internet advertisements</body></html>\n    "
[2018-1-20 18:17:15] [Hue] undefined: 0 accessories
[2018-1-20 18:17:15] [Hue] Home: 9 accessories
[2018-1-20 18:17:15] [Hue] TypeError: Cannot read property 'config' of undefined
    at HuePlatform.dump (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:655:11)
    at request.then.catch.then.then (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:593:17)
    at Function.then (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at Function.<anonymous> (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/ext/promise/_array.js:34:4)
    at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at DMap.processValue (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/ext/array/map.js:77:49)
    at Function.done (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:85:12)
```

**Comment by ebaauw** [comment]
This is a new one for me.  Do you also have deCONZ, or just the Hue bridge?  Could you please create a debug log file and attach that here?  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by FezVrasta** [comment]
So, I just found out the problem. I have deCONZ running but I have not yet the RaspBee module installed, if I kill deCONZ everything works just fine.

I guess it's a bit of an edge case

**Comment by ebaauw** [comment]
> I guess it's a bit of an edge case

Yes, but that shouldn't cause homebridge-hue to prevent homebridge from starting.  I think I found the issue.

**Comment by Solusan** [comment]
Hello @ebaauw . Thanks for your amazing job. :)

I've got also the error "[Hue] dresden appspot ipv6: communication error ENETUNREACH on https://dresden-light.appspot.com/" I resolve it setting the `host` key in `config.json` but anyway I'm curious about why cannot understand ipv6.

Do know why could be the problem?

Thanks in advance. ^^

**Comment by FezVrasta** [comment]
@Solusan how do you "resolve" it? May you elaborate pls?

**Comment by Solusan** [comment]
@FezVrasta Just setting the `host` key. 

`                "host": "192.168.0.38",
`

^^

**Comment by FezVrasta** [comment]
Umh, what's the IP? Just the deCONZ server IP? (in my case 127.0.0.1)

**Comment by Solusan** [comment]
“There's no place like 127.0.0.1” 💃 

No, `host` means the ip assigned to your hue bridge. You can get it with `nmap` or `avahi-browser` or you can get it accessing to your Hue app -- Settings -- Hue bridges. 

Now I have a lot of nasty false sensors detected by Homebridge (@ebaauw), but that's fo other thread, I think. :D

**Comment by ebaauw** [comment]
If you run homebridge-hue with deCONZ on the same Raspberry (which I do an would recommend) you’d specify 127.0.0.1.  If you run homebridge-hue with a Hue bridge, you’d specify the IP address of the bridge.

The ENETUNREACH error on dresden’s appspot can be ignored safely.  It’s the deCONZ variant of the meehue portal for discovering bridges/gateways, but there’s something odd with that.  On a dual stack machine deCONZ registers there over IPv6, so the gateway won’t be reported when contacting appspot over IPv4, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/41.  So homebridge-hue issues two requests, one over IPv4 and one over IPv6.  If you don’t have IPv6 internet connectivity (but only local link), the appspot won’t be reachable.

**Comment by Solusan** [comment]
Hello, @ebaauw thanks for our quick answer. I'd like to install deCONZ. Sounds great to discover devices but I'm running a raspbian in Virtualbox and to get the API it's quite impossible for me.

May I ask you for a kind installation of it?

Thanks a lot.

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin.  Note that you need ZigBee hardware to run deCONZ.  You won't be able to use a RaspBee with Virtual Box.  I managed to expose my ConBee to a Ubuntu VM running under Parallels for Mac.  You might be able to do the same with Virtual Box, but I haven't seen any-one doing that before.

**Comment by Solusan** [comment]
Then I need this hardware to run it: [https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/gateways/conbee/?L=1&cHash=c9c902ccdb43164696acccf81b62b2bd](url) 

An this one can't work with Virtualbox.

Until now I can work without this hardware. Please, could you make me know what things will not works without this hard?

Thanks a lot and thanks a lot for your work. 💯

**Comment by ebaauw** [comment]
deCONZ doesn’t work without the hardware.

**Comment by Solusan** [comment]
Hello, 

Yes, that's what I understood. 👍

Sorry for not to make well my question. I mean, directly communicate with the ZigBee devices from Homebridge it's really necessary?

In other words. What feature I cannot get without Conbee?

Thanks a lot.

**Comment by ebaauw** [comment]
> I mean, directly communicate with the ZigBee devices from Homebridge it's really necessary?

It's technically impossible for homebridge-hue (or any other app) to communicate directly with ZigBee devices.  You need a gateway with ZigBee hardware to translate the REST API over TCP/IP into ZigBee commands and back.  The Hue bridge is such a gateway (which has ZigBee hardware on board); deCONZ is an alternative, but it needs a ConBee or RaspBee as ZigBee hardware.

> What feature I cannot get without Conbee?

You cannot communicate with ZigBee devices.

**Comment by Solusan** [comment]
Hi, @ebaauw 

Thanks a lot for your answer. :)

Here in Japan is quite impossible to get a ConBee. The most accurate device for to get the ZigBee features is this one. [https://www.amazon.co.jp/dp/B00VKEH1BQ/ref=cm_sw_r_oth_api_QVfBAb27GTQQS](url)

I'm wondering if this one could works well with homebridge-hue. 

Thanks a lot, always. 🥇
