### ISSUE TITLE
Xiaomi Aqara Smart Wireless Switch only single press?

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#272]
Hi Erik,

short question to you .-)

The Xiaomi Aqara Smart Wireless Switch how many functions should it currently have?

(Https://www.gearbest.com/access-control/pp_626695.html?)

I have one to test here, but with this I can only prove with single press.

I was already happy where I saw the update but unfortunately not for this switch.

Greeting Nastra

**Comment by Nastras** [comment]
Ok, if I understand you correctly, the support will come through your plugin for aqara switches soon?

**Comment by ebaauw** [comment]
homebridge-hue already supports the Aqara smart switch, but only _Single Press_.  Support for _Double Press_ is coming.

**Comment by Nastras** [comment]
I also meant the support for the double press. I already have a switch involved for a long time .-)

Thanks again for the quick answer!

**Comment by davidkristof** [comment]
hey im a newbie with homebridge and all this stuff. With lots of help from everyone who develops, i managed to have a homebridge with xiaomi window sensor and temperature humidity sensor added to home app but for some reason my mi wireless switch (button) https://xiaomi-mi.com/mi-smart-home/xiaomi-mi-wireless-switch/
is not showing in home app, although its in mi home app. I'd like to control my hue bulbs with this mi switch. Any help would be appreciated. I'm using homebridge-aqara plugin now. i tried the others homebridge-mi-aqara and homebridge-mi-aqara-2 and so on. None of them see the switch and only homebridge-aqara works properly with my other mi sensors.
