### ISSUE TITLE
Errormessage in the EVE App

### ISSUE THREAD

**Issue by MikeDeltaHH** [ebaauw/homebridge-hue#275]
Hi!

I have the homebridge-hue@0.5.67 with node 8.9.4 and the hb alexa version 0.4.33 installed. The plugin works fine, i need it only for my Osram Lightify Outdoor Flex RGBW - the only thing i wonder is an error showing in the Eve App: "Errorcode 1" in the Light status of the light - i have no warnings or errors @homebridge start and the light works normaly,so it isn´t a big thing and i cannot see this errormessage in the Apple HomeKit App... i´m not sure that the source of the error is your plugin!

**Comment by ebaauw** [comment]
Not exactly sure what error you’re seeing (a screenshot would help), but I suspect it’s the following: homebridge-hue sets _Status Fault_ when the Hue bridge reports a light as `”reachable”: false`.  You should see messages for that in the homebridge log.  The Hue bridge tends to report non-Hue lights as unreachable, even when they are.

**Comment by MikeDeltaHH** [comment]
Strange... i replug the power supply of the light and the error is gone... do an hb reboot and no new message is show so this "issue" is solved... thanks for your fast reply and for this useful plugin!
