### ISSUE TITLE
Tradfri Remote Bug?

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#276]
Hello Erik,

I have a problem with my Tradfri remote switch. This always loses the connection to deconz between 2 - 3 days. The node is no longer displayed in deconz. It is still available in the phoscon web interface, but in homebridge-hue it will also be displayed when restarting.

deconz will find the switch again after deleting and re-adding the switch if this command is executed before that you had told me:

sudo GCFFlasher_internal -r

Do you have an idea why the switch always disappears? Is probably a deconz bug or?

Greeting Nastra

**Comment by ebaauw** [comment]
Sounds like https://github.com/dresden-elektronik/deconz-rest-plugin/issues/316.  Upgrading the RaspBee firmware seemed to have solved most of it.

**Comment by Nastras** [comment]
Alright. I almost thought so. Did not find the issue at github under deconz unfortunately.
Thank you for the hint.

What surprised me that the xiaomi devices are not affected only the Ikea or Philips devices as it look.

Let's hope that soon a troubleshooting appears.
