### ISSUE TITLE
Built-in Daylight sensor not reporting changes in light levels? Button not reporting multiple presses?

### ISSUE THREAD

**Issue by TerryLansdown** [ebaauw/homebridge-hue#278]
Hi, 

Very much enjoying Homebridge, thanks for your efforts.

I have a v1 Hub which shows the built-in daylight sensor and the Hub button. The lights work great, and the button registers a single press with ' homebridge -D ', but the light levels never change from 0.0001 lux, and multiple/long presses aren't registered. Anyone have any ideas? Thanks, t

**Comment by ebaauw** [comment]
The button on the bridge only reports single press, so that’s the only thing I can support.

Did you configure the Daylight sensor?  You need to enter your coordinates before the Hue bridge retrieves your local sunrise/sunset times from the meethue portal.

**Comment by TerryLansdown** [comment]
Hi, 

Thanks. Is there published guidance on how to set the daylight sensor? I see from the dev API info you provide decimal lat/long, and found reference to someone setting them using curl, but don’t know how to do this.

I saw elsewhere on the homebridge-hue git pages reference to virtual switches, would it be possible to set up a virtual switch to emulate an on/off with the hue bridge button?

Thanks again, t

**Comment by ebaauw** [comment]
With the latest version of homebride-hue you should get a `ph` command to interact with the Hue bridge.  Try `ph —help`.  After you’ve create a username with `ph -H `_address_ `createuser` (where _address_ is the hostname or IP address of your Hue bridge), you can configure the Daylight sensor through:
```
ph -H address put /sensors/1/config ’{
  ”lat”: ”...”,
  ”long”: ”...”
}’
```
(Best not copy/paste this - I think my iPad screwed up the quotation marks.)  See 2.6 on https://developers.meethue.com/documentation/supported-sensors.

> would it be possible to set up a virtual switch to emulate an on/off with the hue bridge button?

Not sure what you mean by emulate?  To turn lights on/off by the bridge button, simply setup a HomeKit automation.  You might need to use Eve instead of Apple’s Home app, to specify a condition (whether the lights are currently on or off).

If you want to use a virtual switch, create a CLIPGenericFlag sensor, use a HomeKit automation to set it, use a bridge rule with a `ddx` condition to clear it automatically after a second and create a set of bridge rules to turn the lights on or off, based on the flag and current light state.

**Comment by TerryLansdown** [comment]
Thanks that’s very helpful.

Sorry to be thick but how can I issue the command in an interactive shell? I’m routinely running as a background process, but if I run Homebridge in the active terminal session, it’s not interactive, status reports only?

Will look into switches, looks straightforward, but more reading required!

Thanks again, t

**Comment by ebaauw** [comment]
Just open a terminal window type type `ph`.  It’s a command line utility that runs independent from homebridge-hue.

**Comment by TerryLansdown** [comment]
Hi,

Thanks again for your help. Some progress. For others following the same path, I needed to update both home bridge and homebridge-hue. I used the following commands.

sudo npm install -g homebridge
sudo npm -g install homebridge-hue@latest

With latest versions, I could use ph in the terminal, I think I created a user by pressing the Hue Bridge button and then issuing:

ph -H 192.168.1.100 createuser

This seems to write a file ~/.ph with a bit of JSON inc. a username.

Then if I try to set the lat long with (using the lat long information from the Hue Dev pages):

ph -H 192.168.1.100 put /sensors/1/config '{ "lat": "010.5186N", "long": "000.3295W" }'

I get:

ph put: error: http status 400

Any ideas where to go from here? I’m running Homebridge on a Mac-mini.

Thanks, t

> Just open a terminal window type type ph. It’s a command line utility that runs independent from homebridge-hue.

**Comment by ebaauw** [comment]
400 means: bad request.  Maybe you need to set the offsets as well.  Maybe it doesn’t like the leading zeroes.  This is not something I do on a daily basis ;-)

What version of `ph` did you install (see `ph -V`)?  The later versions should only report back an http error status when the Hue bridge returns an empty body.  Typically, it will issue a more descriptive error message in the body.  You might try enabling debugging to see the request to and response from the Hue bridge (amongst a whole lot of other stuff):
```
DEBUG=* ph -H 192.168.1.100 put /sensors/1/config '{
  "long": "0.3295W",
  "lat": "10.5186N",
  "sunriseoffset": 0,
  "sunsetoffset": 0
}'
```
Hint: you can also specify the bridge address in the PH_HOST environment variable, so you don’t have to specify it with `-H` each time:
```
export PH_HOST=192.168.1.100
```

**Comment by TerryLansdown** [comment]
Hi,

Thanks for thugging away at this with me.

Tried with and without the leading zeros, no difference status 400.

Looking through the debug, I can’t see any obvious errors (with my very limited knowledge). Any other suggestions? Debug listed below. Looks like the Hub is talking, but there’s something wrong with the json?

Thanks, t

> 400 means: bad request. Maybe you need to set the offsets as well. Maybe it doesn’t like the leading zeroes. This is not something I do on a daily basis ;-)
> 
> What version of ph did you install (see ph -V)? The later versions should only report back an http error status when the Hue bridge returns an empty body. Typically, it will issue a more descriptive error message in the body. You might try enabling debugging to see the request to and response from the Hue bridge (amongst a whole lot of other stuff):
> 
> DEBUG=* ph -H 192.168.1.100 put /sensors/1/config '{
>   "long": "0.3295W",
>   "lat": "10.5186N",
>   "sunriseoffset": 0,
>   "sunsetoffset": 0
> }'
> 
> Hint: you can also specify the bridge address in the PH_HOST environment variable, so you don’t have to specify it with -H each time:
> 
> export PH_HOST=192.168.1.100
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

```
home:~ media$ DEBUG=* ph -H 192.168.1.100 put /sensors/1/config '{ "long": "0.3295W", "lat": "10.5186N", "sunriseoffset": 0, "sunsetoffset": 0 }'
  OptionParser #0 constructor({"chalk":false,"debug":false,"program":true,"timestamp":false}) +0ms
  OptionParser #0 boolKey("chalk") +3ms
  OptionParser #0 boolKey("debug") +0ms
  OptionParser #0 boolKey("program") +0ms
  OptionParser #0 boolKey("timestamp") +1ms
  OptionParser #0 enumKey("mode") +0ms
  OptionParser #0 enumKeyValue("mode", "command") +0ms
  OptionParser #0 enumKeyValue("mode", "daemon") +0ms
  OptionParser #0 enumKeyValue("mode", "service") +0ms
  OptionParser #0 parse({"mode":"command","debug":false}) +1ms
  OptionParser #0 parse() => {"chalk":false,"debug":false,"program":true,"timestamp":false} +0ms
  CommandLineParser #0 constructor() +0ms
  CommandLineParser #0 flag("h", "help") +1ms
  CommandLineParser #0 flag("V", "version") +0ms
  CommandLineParser #0 optionHost("H", "host") +0ms
  CommandLineParser #0 optionInt("t", "timeout", 1, 30) +1ms
  CommandLineParser #0 option("u", "username") +0ms
  CommandLineParser #0 parameter("command") +0ms
  CommandLineParser #0 remaining() +0ms
  CommandLineParser #0 parse(["-H","192.168.1.100","put","/sensors/1/config","{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"]) +1ms
  CommandLineParser #0 parse() => option: -H 192.168.1.100 +0ms
  CommandLineParser #0 parse() => parameter command: put +1ms
  CommandLineParser #0 parse() => remaining: ["/sensors/1/config","{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"] +0ms
  HueClient #1 constructor({"host":"192.168.1.100"}) +0ms
  OptionParser #1 constructor({"hostname":"localhost","port":80,"username":"unknown","timeout":5}) +0ms
  OptionParser #1 hostKey("host", "hostname", "port") +1ms
  OptionParser #1 stringKey("username", true) +0ms
  OptionParser #1 intKey("timeout", 1, 60) +0ms
  OptionParser #1 parse({"host":"192.168.1.100"}) +0ms
  OptionParser #1 parse() => {"hostname":"192.168.1.100","port":80,"username":"unknown","timeout":5} +0ms
  HueClient #1 constructor() => {"hostname":"192.168.1.100","port":80,"username":"unknown","timeout":5,"url":"http://192.168.1.100"} +1ms
  HueClient #1 getConfig() +1ms
  HueClient #1 get("/config") +0ms
  HueClient #1 request({"method":"get","url":"http://192.168.1.100/api/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true}) +1ms
  HueClient #1 request({"method":"get","url":"http://192.168.1.100/api/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true}) => {"statusCode":200,"body":{"name":"Hue Bridge G’s","datastoreversion":"59","swversion":"01038802","apiversion":"1.16.0","mac":"00:17:88:1a:1d:86","bridgeid":"001788FFFE1A1D86","factorynew":false,"replacesbridgeid":null,"modelid":"BSB001"},"headers":{"cache-control":"no-store, no-cache, must-revalidate, post-check=0, pre-check=0","pragma":"no-cache","expires":"Mon, 1 Aug 2011 09:00:00 GMT","connection":"close","access-control-max-age":"3600","access-control-allow-origin":"*","access-control-allow-credentials":"true","access-control-allow-methods":"POST, GET, OPTIONS, PUT, DELETE, HEAD","access-control-allow-headers":"Content-Type","content-type":"application/json"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.1.100","port":80,"hostname":"192.168.1.100","hash":null,"search":null,"query":null,"pathname":"/api/config","path":"/api/config","href":"http://192.168.1.100/api/config"},"method":"get","headers":{"Connection":"keep-alive","accept":"application/json","content-length":0}}} +35ms
  HueClient #1 get("/config", []) => {"name":"Hue Bridge G’s","datastoreversion":"59","swversion":"01038802","apiversion":"1.16.0","mac":"00:17:88:1a:1d:86","bridgeid":"001788FFFE1A1D86","factorynew":false,"replacesbridgeid":null,"modelid":"BSB001"} +0ms
  HueClient #1 getConfig() => {"name":"Hue Bridge G’s","datastoreversion":"59","swversion":"01038802","apiversion":"1.16.0","mac":"00:17:88:1a:1d:86","bridgeid":"001788FFFE1A1D86","factorynew":false,"replacesbridgeid":null,"modelid":"BSB001"} +0ms
  CommandLineParser #1 constructor() +0ms
  CommandLineParser #1 flag("h", "help") +0ms
  CommandLineParser #1 flag("v", "verbose") +0ms
  CommandLineParser #1 parameter("resource") +0ms
  CommandLineParser #1 remaining() +0ms
  CommandLineParser #1 parse(["/sensors/1/config","{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"]) +0ms
  CommandLineParser #1 parse() => parameter resource: /sensors/1/config +0ms
  CommandLineParser #1 parse() => remaining: ["{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"] +1ms
  HueClient #1 put("/sensors/1/config", {"long":"0.3295W","lat":"10.5186N","sunriseoffset":0,"sunsetoffset":0}) +12ms
  HueClient #1 request({"method":"put","url":"http://192.168.1.100/api/[object Object]/sensors/1/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true,"body":{"long":"0.3295W","lat":"10.5186N","sunriseoffset":0,"sunsetoffset":0}}) +0ms
  HueClient #1 request({"method":"put","url":"http://192.168.1.100/api/[object Object]/sensors/1/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true,"body":{"long":"0.3295W","lat":"10.5186N","sunriseoffset":0,"sunsetoffset":0}}) => {"statusCode":400,"body":"<html><head></head><b>Bad URL in request</b></html>","headers":{"cache-control":"no-store, no-cache, must-revalidate, post-check=0, pre-check=0","pragma":"no-cache","expires":"Mon, 1 Aug 2011 09:00:00 GMT","connection":"close","access-control-max-age":"3600","access-control-allow-origin":"*","access-control-allow-credentials":"true","access-control-allow-methods":"POST, GET, OPTIONS, PUT, DELETE, HEAD","access-control-allow-headers":"Content-Type","content-type":"text/html"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.1.100","port":80,"hostname":"192.168.1.100","hash":null,"search":null,"query":null,"pathname":"/api/[object%20Object]/sensors/1/config","path":"/api/[object%20Object]/sensors/1/config","href":"http://192.168.1.100/api/[object%20Object]/sensors/1/config"},"method":"put","headers":{"Connection":"keep-alive","accept":"application/json","content-type":"application/json","content-length":70}}} +7ms
ph put: error: http status 400
home:~ media$ 
home:~ media$ DEBUG=* ph -H 192.168.1.100 put /sensors/1/config '{ "long": "0.3295W", "lat": "10.5186N", "sunriseoffset": 0, "sunsetoffset": 0 }'
  OptionParser #0 constructor({"chalk":false,"debug":false,"program":true,"timestamp":false}) +0ms
  OptionParser #0 boolKey("chalk") +3ms
  OptionParser #0 boolKey("debug") +1ms
  OptionParser #0 boolKey("program") +0ms
  OptionParser #0 boolKey("timestamp") +0ms
  OptionParser #0 enumKey("mode") +0ms
  OptionParser #0 enumKeyValue("mode", "command") +0ms
  OptionParser #0 enumKeyValue("mode", "daemon") +1ms
  OptionParser #0 enumKeyValue("mode", "service") +0ms
  OptionParser #0 parse({"mode":"command","debug":false}) +0ms
  OptionParser #0 parse() => {"chalk":false,"debug":false,"program":true,"timestamp":false} +0ms
  CommandLineParser #0 constructor() +0ms
  CommandLineParser #0 flag("h", "help") +1ms
  CommandLineParser #0 flag("V", "version") +0ms
  CommandLineParser #0 optionHost("H", "host") +0ms
  CommandLineParser #0 optionInt("t", "timeout", 1, 30) +0ms
  CommandLineParser #0 option("u", "username") +1ms
  CommandLineParser #0 parameter("command") +0ms
  CommandLineParser #0 remaining() +0ms
  CommandLineParser #0 parse(["-H","192.168.1.100","put","/sensors/1/config","{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"]) +1ms
  CommandLineParser #0 parse() => option: -H 192.168.1.100 +0ms
  CommandLineParser #0 parse() => parameter command: put +0ms
  CommandLineParser #0 parse() => remaining: ["/sensors/1/config","{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"] +0ms
  HueClient #1 constructor({"host":"192.168.1.100"}) +0ms
  OptionParser #1 constructor({"hostname":"localhost","port":80,"username":"unknown","timeout":5}) +0ms
  OptionParser #1 hostKey("host", "hostname", "port") +0ms
  OptionParser #1 stringKey("username", true) +0ms
  OptionParser #1 intKey("timeout", 1, 60) +1ms
  OptionParser #1 parse({"host":"192.168.1.100"}) +0ms
  OptionParser #1 parse() => {"hostname":"192.168.1.100","port":80,"username":"unknown","timeout":5} +0ms
  HueClient #1 constructor() => {"hostname":"192.168.1.100","port":80,"username":"unknown","timeout":5,"url":"http://192.168.1.100"} +1ms
  HueClient #1 getConfig() +0ms
  HueClient #1 get("/config") +1ms
  HueClient #1 request({"method":"get","url":"http://192.168.1.100/api/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true}) +0ms
  HueClient #1 request({"method":"get","url":"http://192.168.1.100/api/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true}) => {"statusCode":200,"body":{"name":"Hue Bridge G’s","datastoreversion":"59","swversion":"01038802","apiversion":"1.16.0","mac":"00:17:88:1a:1d:86","bridgeid":"001788FFFE1A1D86","factorynew":false,"replacesbridgeid":null,"modelid":"BSB001"},"headers":{"cache-control":"no-store, no-cache, must-revalidate, post-check=0, pre-check=0","pragma":"no-cache","expires":"Mon, 1 Aug 2011 09:00:00 GMT","connection":"close","access-control-max-age":"3600","access-control-allow-origin":"*","access-control-allow-credentials":"true","access-control-allow-methods":"POST, GET, OPTIONS, PUT, DELETE, HEAD","access-control-allow-headers":"Content-Type","content-type":"application/json"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.1.100","port":80,"hostname":"192.168.1.100","hash":null,"search":null,"query":null,"pathname":"/api/config","path":"/api/config","href":"http://192.168.1.100/api/config"},"method":"get","headers":{"Connection":"keep-alive","accept":"application/json","content-length":0}}} +35ms
  HueClient #1 get("/config", []) => {"name":"Hue Bridge G’s","datastoreversion":"59","swversion":"01038802","apiversion":"1.16.0","mac":"00:17:88:1a:1d:86","bridgeid":"001788FFFE1A1D86","factorynew":false,"replacesbridgeid":null,"modelid":"BSB001"} +0ms
  HueClient #1 getConfig() => {"name":"Hue Bridge G’s","datastoreversion":"59","swversion":"01038802","apiversion":"1.16.0","mac":"00:17:88:1a:1d:86","bridgeid":"001788FFFE1A1D86","factorynew":false,"replacesbridgeid":null,"modelid":"BSB001"} +0ms
  CommandLineParser #1 constructor() +0ms
  CommandLineParser #1 flag("h", "help") +0ms
  CommandLineParser #1 flag("v", "verbose") +0ms
  CommandLineParser #1 parameter("resource") +0ms
  CommandLineParser #1 remaining() +0ms
  CommandLineParser #1 parse(["/sensors/1/config","{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"]) +0ms
  CommandLineParser #1 parse() => parameter resource: /sensors/1/config +0ms
  CommandLineParser #1 parse() => remaining: ["{ \"long\": \"0.3295W\", \"lat\": \"10.5186N\", \"sunriseoffset\": 0, \"sunsetoffset\": 0 }"] +1ms
  HueClient #1 put("/sensors/1/config", {"long":"0.3295W","lat":"10.5186N","sunriseoffset":0,"sunsetoffset":0}) +11ms
  HueClient #1 request({"method":"put","url":"http://192.168.1.100/api/[object Object]/sensors/1/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true,"body":{"long":"0.3295W","lat":"10.5186N","sunriseoffset":0,"sunsetoffset":0}}) +0ms
  HueClient #1 request({"method":"put","url":"http://192.168.1.100/api/[object Object]/sensors/1/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true,"body":{"long":"0.3295W","lat":"10.5186N","sunriseoffset":0,"sunsetoffset":0}}) => {"statusCode":400,"body":"<html><head></head><b>Bad URL in request</b></html>","headers":{"cache-control":"no-store, no-cache, must-revalidate, post-check=0, pre-check=0","pragma":"no-cache","expires":"Mon, 1 Aug 2011 09:00:00 GMT","connection":"close","access-control-max-age":"3600","access-control-allow-origin":"*","access-control-allow-credentials":"true","access-control-allow-methods":"POST, GET, OPTIONS, PUT, DELETE, HEAD","access-control-allow-headers":"Content-Type","content-type":"text/html"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.1.100","port":80,"hostname":"192.168.1.100","hash":null,"search":null,"query":null,"pathname":"/api/[object%20Object]/sensors/1/config","path":"/api/[object%20Object]/sensors/1/config","href":"http://192.168.1.100/api/[object%20Object]/sensors/1/config"},"method":"put","headers":{"Connection":"keep-alive","accept":"application/json","content-type":"application/json","content-length":70}}} +7ms
ph put: error: http status 400
home:~ media$ 

```

**Comment by ebaauw** [comment]
Thanks, this looks like a bug in `ph`.  I’ll have to look when I get home...

**Comment by ebaauw** [comment]
There is a bug in v0.3.4 with `ph createuser`.  It creats the wrong entry in `~/.ph`, causing an "error: http status 400" for each subsequent `ph` command to the same bridge/gateway.

Please re-install homebridge-hue through `sudo npm -g i homebridge-hue`, this should update homebridge-hue-utils to v0.3.5.  After that, create a new API username through `ph -H 192.168.1.100 createuser` - this will overwrite the wrong entry in `~/.ph`.  After that, re-try setting the Daylight configuration.

**Comment by TerryLansdown** [comment]
Excellent, thanks, that seems to have allowed setup. homebridge -D looks okay. Should I see the sensor in Home on iOS, show a daytime/nighttime switch? I seems to be reporting daytime with no lux values (as previously), and it’s night right now. If I query the Hub with ph, I’m getting 503 errors. Definitely progress though!

Thanks, Terry

**Comment by ebaauw** [comment]
> Should I see the sensor in Home on iOS, show a daytime/nighttime switch?

No, it shows as a lightlevel sensor, 0.0001 lux when it's dark and 100000 lux (give or take a 0) when it's daylight.  
The bridge needs an Internet connection to retrieve the daylight settings for your location from the meethue portal.  You should be able to do a `ph -H 192.168.1.100 get /sensors/1`, and check `state.daylight` and `state.lastupdated`.  The latter should be (more or less) the time of setting the sensor's config.

> I’m getting 503 errors.

http status 503 means: service unavailable.  This would indicate that the Hue bridge is in error, or overloaded.  The v1 bridge is far less powerful than the v2 bridge.  How many apps are connected to the bridge while you issue `ph`?  Do you see any errors in the homebridge log?  What heartrate setting do you use for homebridge-hue - a value of 2 might be stretching it (and 1 doesn't even work for a v2 bridge).

Best power-cycle your bridge and see if it sets the Daylight sensor (should be well within a minute after rebooting).

**Comment by TerryLansdown** [comment]
Hi Erik,

Excellent, we’re up and running. Home app reporting 100,00 lux. I can query the sensor with:

ph -H 192.168.1.100 get /sensors/1

and it returns:

```
{
  "state": {
    "daylight": true,
    "lastupdated": "2018-02-07T08:24:00"
  },
  "config": {
    "on": true,
    "configured": true,
    "sunriseoffset": 30,
    "sunsetoffset": -30
  },
  "name": "Daylight",
  "type": "Daylight",
  "modelid": "PHDL00",
  "manufacturername": "Philips",
  "swversion": "1.0"
}

```

Many thanks for all your help with this.

Best wishes, t
