### ISSUE TITLE
No Groups exposed since v0.5.70 and higher

### ISSUE THREAD

**Issue by DSchumacher2104** [ebaauw/homebridge-hue#279]
Hello Erik,

i think there is a bug since version 0.5.70 and higher (even 0.6.00) with hue bridge v2 that causes alle groups not to be exposed. When i switch back to v0.5.69 all groups are there again.

Perhaps you can look and fix it :-)

Thanks for your work!
Daniel

**Comment by ebaauw** [comment]
Hm, afaik I haven’t touched that part of the code.  Could you please attach a debug log file and debug dump file, see https://github.com/ebaauw/homebridge-hue#troubleshooting.

**Comment by DSchumacher2104** [comment]
Okay, thank you!!!

I'm glad you found it, cause making an debug log would cause to loose the groups in all scenes and rules again. I have just rebuild all after loosing them with 0.5.71.

**Comment by ebaauw** [comment]
Fixed in v0.6.1.
