### ISSUE TITLE
Is it really excludeNativeHomeKitLights and excludeNativeHomeKitSensors?

### ISSUE THREAD

**Issue by jdshkolnik** [ebaauw/homebridge-hue#281]
Hi,

In my opinion, it's a bit confusing when true means include for sensors yet exclude for nativeHomeKitSensors. I think it'd be more intuitive with exclude in the name, like excludeNativeHomeKitSensors. You use it for excludeSensorTypes because all the others seem to consider "include" implied, like (include)Sensors, (include)LinkButton, (include)Group0, etc.

**Comment by ebaauw** [comment]
My thinking was: you specify that you use the native HomeKit feature of the Hue bridge for lights or sensors, therefore you don’t want homebridge-hue to expose the Hue lights or sensors.  Similar to wallSwitch to indicate that you use traditional wall switches to control your lights.

**Comment by jdshkolnik** [comment]
I understand. I've been using your add-on for a while now and have become a bit used to your naming convention and this confused me just now. I thought it was worth some feedback.

**Comment by ebaauw** [comment]
Thanks, I’ve updated the Wiki.
