### ISSUE TITLE
Temperatur range Xiaomi Mi and Aquara sensor

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#282]
Hi Erik,

It is possible to limit the temperature range of the Xiaomi Mi and Aqara temperature sensors to the same values ​​as the Elagto Eve Degree -30 to + 100 degrees.

At the moment, the Xiaomi sensors have a bandwidth of -270 to +1000 degrees.

As a result, you can not adjust the exact temperature in the most HomeKit apps that use to adjust a slider.

Greeting Nastra

**Comment by ebaauw** [comment]
In HomeKit _CurrentTemperature_ is read-only.  How would you adjust it?

The ZigBee standard actually includes the min and max value of a Temperature Sensing cluster, but these aren’t exposed through the REST API.  The ones I’ve seen report a minumum value of -273.15 (absolute zero), but I’m pretty sure they won’t work at this temperature.

**Comment by Krocko** [comment]
If you create a homekit rule and use temperature as condition, you get this slider.

**Comment by Nastras** [comment]
Just like Krocko says.

👍

**Comment by ebaauw** [comment]
That’s indeed a brilliant use case I hadn’t considered before.  Yes, I set the range somewhere, because the standard HomeKit range doesn’t allow negative temperatures (which makes sense for a thermostat, but not for an outdoor sensor).  I figured I set a large range, so I won’t have to change in future.  Shows what I know...

Would -30 to 100 be the appropriate range for all temperature sensors?

**Comment by Nastras** [comment]
I now have all the temperature sensors I have checked with me to the min and max default value.

Hue Motion -40 to +100 degrees
Degree -30 to +100 degrees
Tado 0 to +100 degrees
Netatmo -100 to +100 degrees with HB plugin

I think from -100 to +100 degrees should be sufficient for all realistic cases.

What do you think?

**Comment by QempZor** [comment]
Here in Europe, the lowest outdoor temperature ever is -30,4 in Belgium haha. 

So i think -40 to +100 is very nice

**Comment by Nastras** [comment]
The value should be usable worldwide, I do not think that Belgium reflects the whole world again.

The coldest place in the world is in sibiria with 71 degree 😉

**Comment by QempZor** [comment]
Damn, thats cold😅
-100 to 100 will be more suitable then. 

And still very usable with those sliders I guess

**Comment by ebaauw** [comment]
I doubt these battery powered sensors would still be operational at -40ºC, let alone at -70ºC.  I'll set the range to -40ºC to 100ºC.

**Comment by ebaauw** [comment]
Should be in v0.6.1.

**Comment by Nastras** [comment]
Thank You !
