### ISSUE TITLE
Altitude meters Xiaomi Aqara sensor

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#284]
Hey Erik,

i noticed that the Xiaomi Aqara sensors show altitude meters under air pressure just like the Elgato Eve Degree.

At the degree you can adjust the altitude via a slider, do you mean that you can do that with the Aqara sensors as well?

Degree:
![15027364-0e95-40d2-9040-26479a0dd7f4](https://user-images.githubusercontent.com/27686185/35924651-ea20d93e-0c23-11e8-949e-acb1863e881b.jpeg)

Aqara:
![2f0bbdf5-106e-44c2-bc0b-ada1abe9db31](https://user-images.githubusercontent.com/27686185/35924569-ae1b6440-0c23-11e8-895e-4e56cb012add.jpeg)

**Comment by ebaauw** [comment]
To Eve, the Xioami Aqara weather needs to look just like an Eve Degree, including the Elevation in the Accessory setting, or the Eve app won't show history.  Same for a multi-CLIP temperature/humidity/pressure sensor.

I have no idea how Eve handles Elevation - in the app or in the sensor.  There's no support for this in the Aqara sensor nor in deCONZ.  I can change the Elevation for the Aqara in Eve, from -430m to 8850m in 10m steps.

**Comment by Nastras** [comment]
> I can change the Elevation for the Aqara in Eve, from -430m to 8850m in 10m steps.

If I understand your last sentence correctly can you adjust the aqara in the eve app?


If so, can you make a screenshot of what you look like in the eve app? With me there is nothing to adjust.

**Comment by ebaauw** [comment]
Are you on v0.6.1.  I fixed a bug from v0.6.0 which might be related.

**Comment by Nastras** [comment]
The screenshot is of a degree if I see it right?

Yes I am at 0.6.1

**Comment by ebaauw** [comment]
No it's of an Aqara weather - I don't even have an Eve Degree.

**Comment by Nastras** [comment]
Looked like this 😬

I've found the mistake of setting the elevation in the eve app for the degree and aqara both in the device settings.

In the app I used HomeDash I searched for the slider like the degree to adjust as above on my screenshoots.

This slider does not appear to be displayed by the Hue plugin in other apps.

But good to know that you have to set the altitude once on the eve app.

**Comment by ebaauw** [comment]
I still doubt it will do anything, but lemme know what you find out.
