### ISSUE TITLE
TRÅDFRI motion sensor dark setting as state not config 

### ISSUE THREAD

**Issue by Larsn1** [ebaauw/homebridge-hue#286]
I‘ve set my motion sensors to react only when its dark. Currently I see no way to work with that in deconz automations. Is there a way to get the lumen readings from the sensors?

Moreover how does deconz get the setting from the sensor? Woulndt it be better if I can configure that?

**Comment by ebaauw** [comment]
> Currently I see no way to work with that in deconz automations

There's a `state.dark` in the sensor resource.  Note that it's updated only when the sensor detects motion.

> Is there a way to get the lumen readings from the sensors?

No, the sensor doesn't provide this.

> Moreover how does deconz get the setting from the sensor?

It doesn't, at least not directly.  The sensor sends a different command when in Night mode and it's dark.  There's no way to distinguish between Day mode and Night mode when there's enough light.

> Woulndt it be better if I can configure that?

Much better.  Tell IKEA.

**Comment by Larsn1** [comment]
I am now considering to build an Mqtt lumen sensor with an esp8266 or get another motion sensor. Could you recommend one that could be configured to keep the lights off when there is enough light?

I have a raspbee and deconz

**Comment by ebaauw** [comment]
Actually, that’s exactly what the Trådfri does, when controlling the lights directly.  Just add the lights to the group associated with the sensor.  
Using a rule on the deCONZ gateway you could achieve the same, if you use conditions on state.presence, state.dark, and state.lastupdated.  You might need a ddx instead of a dx on the last one, to make sure state.dark has been updated.

**Comment by Larsn1** [comment]
I am not very skilled with this rules and I honestly dont know how to start with that. If there is a sample I could adapt that would help. I also have problems with delay on this motion sensors. Wouldnt a rule add more delay?

**Comment by ebaauw** [comment]
The deCONZ API is largely the same as the Hue API.  Best check out https://developers.meethue.com/documentation/getting-started to understand the API.

**Comment by Larsn1** [comment]
I appreciate your help but there are always some questions you don‘t answer.

**Comment by ebaauw** [comment]
What do you mean?

**Comment by Larsn1** [comment]
I asked for the Delay this could cause and when I asked if it wouldnt be better if I can configure that dark setting in deconz I should tell that Ikea. Why? The timer setting on the sensor is completly managed by deconz. Ive set the wheel to 10 minutes but the lights go off in 4 minutes. I am so frustrated with the rules that i would rather build an additional sensor with an esp8266 because I think its quicker. Maybe someone has a working sample or there is a space where rules can be shared as long as the rule creation is so complicated ( at least for me).

**Comment by Larsn1** [comment]
Can you reopen this? I am sure there are more people with the ikea sensors

**Comment by Larsn1** [comment]
I am using the phoscon app automation to handle the lights. You don‘t need to connect your sensor with the bulbs directly. In this very easy to use GUI you can set when the lights should dimm and to which sensor they listen to. I‘ve set my sensors to 10 Minutes and the light goes off in 3 because of the automation. Would it be possible to extend the settings there and let me choose regarding the dark setting? Does it really require a full set of rules? 
I have tried to set up a rule once but I had to give up after 4 hours straight.

**Comment by Larsn1** [comment]
When I said I have set my sensor to 10 minutes I mean the small wheel on the back of the device. 3 minutes is configured in pwa and that is working

**Comment by ebaauw** [comment]
This is not related to homebridge-hue.  Better open an issue with the phoscon app.
