### ISSUE TITLE
Creat a User Acc - RaspBee/ConBee not yet initialised wait 1 minute

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#289]
Hello Erik,

I would need your help again.

I bought a ConBee USB because of a system change. Now I get the following message when creating a user:

![img_0480](https://user-images.githubusercontent.com/27686185/36293218-eb612352-12d7-11e8-9a39-726028099cdc.jpg)

Do you have an idea why?

Besides, I still have a problem with the firmware update can it be related?

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/417

Thanks!

**Comment by ebaauw** [comment]
Sometimes deCONZ reports a bridgeid of all 0s, when it hasn’t been able to read the RaspBee’s/ConBee’s mac address.  Typically this goes away after a while, after it has initialised the RaspBee/ConBee.  I don’t know what’s causing this.

**Comment by Nastras** [comment]
Roger that!

This is a deconz bug probably, do you know if this bug has already been reported?

I've been deconz for several hours so far it has not resolved by itself.

I just looked for the mac address this is in deconz but available.

![ohne titel](https://user-images.githubusercontent.com/27686185/36295859-6fb0586e-12ea-11e8-89fc-d65b8c9436e5.jpeg)

**Comment by ebaauw** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/279 and https://github.com/dresden-elektronik/deconz-rest-plugin/pull/44

**Comment by Nastras** [comment]
Thank you for the hints!

That's a really stupid bug.

You wrote that it usually fixes itself after a certain time. How would you proceed now?

Every few hours unlock the app search in deconz and restart homebridge-hue to see if a user is shown?

**Comment by ebaauw** [comment]
You don’t need to restart homebridge-hue - it’s just waiting/retrying for the bridgeid to become available.  As I said before, I don’t know what’s causing this.

**Comment by Nastras** [comment]
Ok i understand. Thank you to here.  .-)

**Comment by Nastras** [comment]
Hey Erik,

the mistake from above is gone as you said.

He now shows a new error. I have tried in WebApp and Phoscon to create a user but in homebridge-hue no key is displayed.

Only this error -.-

![ohne titel](https://user-images.githubusercontent.com/27686185/36321183-3dc08676-1349-11e8-8c47-a1ff24ecb9eb.jpeg)

Do you have one more tip for the problem?

**Comment by Nastras** [comment]
Here is my config.json:
![ohne titel](https://user-images.githubusercontent.com/27686185/36321451-32fe276a-134a-11e8-8fb0-1766f2ce6b15.jpeg)

That should be ok?

**Comment by Nastras** [comment]
Here is my config.json

![ohne titel](https://user-images.githubusercontent.com/27686185/36321549-7c1b76d2-134a-11e8-8287-d0c5285f379b.jpeg)



That should be ok?

**Comment by Nastras** [comment]
I was able to create a user via the REST API. I have entered this in the config.json. However, the bug still exists for Forbidden 403 and Homebridge does not want to start.

**Comment by ebaauw** [comment]
> He now shows a new error. I have tried in WebApp and Phoscon to create a user but in homebridge-hue no key is displayed.

deCONZ will create the username (API key) at request of homebridge-hue, but you need deCONZ to accept such request.  In the Phoscon app, under Advanced Settings, select Authenticate App.
You need to enter the bridgeid in uppercase.  Or in the old web app, under Settings, select Unlock Gateway.

> the bug still exists for Forbidden 403 and Homebridge does not want to start.

This is not a bug - you didn't unlock deCONZ.

> I have entered this in the config.json. 

You need to specify the bridgeid in uppercase.  And you need to specify the username (API key)

**Comment by Nastras** [comment]
> You need to specify the bridgeid in uppercase. 

Ohhhh god,

that was the problem. I fight so much with problems from deconz that it works that I have overlooked this detail at the end.🤪

It's almost embarrassing. 🤭

Thank you again for your help !!!
