### ISSUE TITLE
Xiaomi Door Sensor 

### ISSUE THREAD

**Issue by erikproper** [ebaauw/homebridge-hue#290]
Having some problems in getting deConz (and finally HomeAssistant) to recognise a new Xiaomi door 
sensor. 

In the deCONZ GUI, the sensor does show up with a gray banner. However, in the RestAPI there is no sensor entry created. 

Attached an image with the cluster info. Relevant elements from the LOG are listed below.

Any suggestions?

Cheers,
  Erik

------
![img_3113](https://user-images.githubusercontent.com/4380053/36321021-a9fa9102-1348-11e8-9e60-2a6eb3d862a5.JPG)
18:18:15:018 MGTM_Lqi_req zdpSeq: 131 to 0x00212EFFFF01728F start index 0
18:18:15:114 ZDP status = 0x00 -> SUCCESS
18:18:15:114 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
18:18:15:114 ZDP Mgmt_Lqi_rsp zdpSeq: 131 from 0x00212EFFFF01728F total: 1, startIndex: 0, listCount: 1
18:18:15:114     * neighbor: 0x00158D00017C5B22 (0x0CFB), LQI: 252, relation: 0x01 rxOnWHenIdle: 1
18:18:15:216 MAC Poll 0x02 0xC7A1
18:18:15:259 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 16 s
18:18:15:299 device announce 0x00158D0001C105A3 (0xC7A1) mac capabilities 0x80
18:18:15:299 set fast probe address to 0x00158D0001C105A3 (0xC7A1)
18:18:15:299 APS-DATA.indication from unknown node 0x00158D0001C105A3
18:18:15:299 ZDP status = 0x00 -> SUCCESS
18:18:15:299 ZDP device announce: 0x00158D0001C105A3, 0xC7A1, 0x80
18:18:15:299 CTRL restore cached node 0x00158d0001c105a3
18:18:15:301 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 2, node: 0xC7A1
18:18:15:302 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 1, node: 0xC7A1
18:18:15:302 new node - ext: 0x00158d0001c105a3, nwk: 0xC7A1
18:18:15:374 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0000
18:18:15:374 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0000
18:18:15:393 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0000
18:18:15:394 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0000
18:18:15:418 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0000
18:18:15:418 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0000
18:18:15:499 node with nwk address 0x0000 but different mac address already exist
18:18:15:738 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:16:218 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 17 s
18:18:16:349 [1] get node descriptor for 0x00158d0001c105a3
18:18:16:539 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:16:539 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:16:698 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:16:700 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:16:700 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:123 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:123 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:179 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 18 s
18:18:17:547 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:547 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:659 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:17:728 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:728 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:852 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:853 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:18:138 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 19 s
18:18:18:619 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:18:628 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:18:629 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:18:749 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:18:749 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006

**Comment by ebaauw** [comment]
deCONZ hasn't yet read the Manufacturer Name and Model ID, so it doesn't know what sensor this is.  The Xiaomi devices are notoriously obnoxious when pairing.  Make sure to open the network from the web app (not from the GUI).  Keep the sensor awake by presssing/releasing the reset button (hole) regularly.  Try and read the attributes of the Basic cluster from the Cluster Info panel in the deCONZ GUI.

**Comment by erikproper** [comment]
Seems to work! Now I'm getting from "api/../sensors":

{"1":{"config":{"on":true,"reachable":true},"ep":1,"etag":"c98644d28f70aef61a3c3121389645dd","manufacturername":"LUMI","modelid":"lumi.sensor_magnet","name":"OpenClose
1","state":{"lastupdated":"2018-02-16T22:43:54","open":false},"type":"ZHAOpenClose","uniqueid":"00:15:8d:00:01:c1:05:a3-01-0006"}}

And ... in HomeAssistant (thanks to the deConz platform), I now also see
appearing:

{
  "friendly_name": "OpenClose 1",
  "battery_level": null,
  "device_class": "opening"
}

while, in its (HA's) Web GUI, I can see the state change ...
