### ISSUE TITLE
Living Whites Plug

### ISSUE THREAD

**Issue by erikproper** [ebaauw/homebridge-hue#291]
Dear all,
  Also having difficulty in getting some LivingWhites plugs (see: https://www.amazon.de/Philips-6916531PH-Living-Whites-Leuchten-Adapter/dp/B005ER7MX2 ) to pair with deCONZ.
When doing a touchlink scan in the WebApp, I do see the plugs. I can also get it to reset itself.
However, it refuses to pair with deCONZ. Moving the plug back to the Hue Bridge works fine. 

Attached some relevant snippets from the LOG files, showing that the deCONZ app is receiving at least something from 0x00158D0001C105A3

Cheers,
  Erik

18:18:15:018 MGTM_Lqi_req zdpSeq: 131 to 0x00212EFFFF01728F start index 0
18:18:15:114 ZDP status = 0x00 -> SUCCESS
18:18:15:114 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
18:18:15:114 ZDP Mgmt_Lqi_rsp zdpSeq: 131 from 0x00212EFFFF01728F total: 1, startIndex: 0, listCount: 1
18:18:15:114     * neighbor: 0x00158D00017C5B22 (0x0CFB), LQI: 252, relation: 0x01 rxOnWHenIdle: 1
18:18:15:216 MAC Poll 0x02 0xC7A1
18:18:15:259 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 16 s
18:18:15:299 device announce 0x00158D0001C105A3 (0xC7A1) mac capabilities 0x80
18:18:15:299 set fast probe address to 0x00158D0001C105A3 (0xC7A1)
18:18:15:299 APS-DATA.indication from unknown node 0x00158D0001C105A3
18:18:15:299 ZDP status = 0x00 -> SUCCESS
18:18:15:299 ZDP device announce: 0x00158D0001C105A3, 0xC7A1, 0x80
18:18:15:299 CTRL restore cached node 0x00158d0001c105a3
18:18:15:301 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 2, node: 0xC7A1
18:18:15:302 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 1, node: 0xC7A1
18:18:15:302 new node - ext: 0x00158d0001c105a3, nwk: 0xC7A1
18:18:15:374 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0000
18:18:15:374 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0000
18:18:15:393 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0000
18:18:15:394 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0000
18:18:15:418 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0000
18:18:15:418 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0000
18:18:15:499 node with nwk address 0x0000 but different mac address already exist
18:18:15:738 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:16:218 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 17 s
18:18:16:349 [1] get node descriptor for 0x00158d0001c105a3
18:18:16:539 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:16:539 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:16:698 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:16:700 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:16:700 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:123 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:123 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:179 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 18 s
18:18:17:547 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:547 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:659 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:17:728 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:728 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:17:852 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:17:853 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:18:138 Node 0x00158D00017C5B22 is known by 1 neighbors, last seen 19 s
18:18:18:619 Node 0x00158D0001C105A3 is known by 0 neighbors, last seen 0 s
18:18:18:628 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:18:629 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006
18:18:18:749 ZCL attribute report 0x00158D0001C105A3 for cluster 0x0006
18:18:18:749 Node data 0x00158d0001c105a3 profileId: 0x0104, clusterId: 0x0006

**Comment by manup** [comment]
Hi, LivingWhite products can't be paired to deCONZ since these use a security key only known and supported by Philips Hue bridge. They predate Hue products which use inter-operable security keys.

**Comment by erikproper** [comment]
Aha. Did have more luck with a LivingColors. So, I guess for now I will have to work with a dual-bridge solution ;-)

Leaves the door sensors (other reported issue)
