### ISSUE TITLE
Dresden Elektronik Scene Switch

### ISSUE THREAD

**Issue by electromitter** [ebaauw/homebridge-hue#293]
Hi, 

is it possible to add the dresden elektronik scene switch to homekit with homebridge-hue and deconz?
I have 2 scene switches connected to deconz but i dont see them in Homekit.

[Phillips Hue] deconz: /sensors/19: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"883","on":true,"reachable":true},"ep":1,"etag":"0483ff8025252ba4764b5522445aeb0e","manufacturername":"dresden elektronik","mode":1,"modelid":"Scene Switch","name":"Scene Switch Küche","state":{"buttonevent":2002,"lastupdated":"2018-02-21T06:52:24"},"swversion":"02010032","type":"ZHASwitch","uniqueid":"00:21:2e:ff:ff:01:30:66-01-1000"}

**Comment by electromitter** [comment]
[Phillips Hue] deconz: /sensors/19: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"883","on":true,"reachable":true},"ep":1,"etag":"0483ff8025252ba4764b5522445aeb0e","manufacturername":"dresden elektronik","mode":1,"modelid":"Scene Switch","name":"Scene Switch Küche","state":{"buttonevent":2002,"lastupdated":"2018-02-21T06:52:24"},"swversion":"02010032","type":"ZHASwitch","uniqueid":"00:21:2e:ff:ff:01:30:66-01-1000"}

**Comment by ebaauw** [comment]
Sure.  Do you know what buttonevent values it generates for what actions to what buttons?

**Comment by electromitter** [comment]
no i dont know what it generates. why ignores deconz the switch so that i cant see them? im a newbie in homebridge.

**Comment by manup** [comment]
> Sure. Do you know what buttonevent values it generates for what actions to what buttons?

If it helps, the switch has a defined button map in sensor.cpp

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/sensor.cpp#L58

**Comment by ebaauw** [comment]
Yes, that helps, thanks!  I’ll have a look this weekend.

**Comment by electromitter** [comment]
hi,

same as before, no homekit.

[2018-2-24 17:46:34] [Phillips Hue] deconz: /sensors/17: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"9125","on":true,"reachable":true},"ep":1,"etag":"7913a06992dbaac40b4105dd16a8807a","manufacturername":"dresden elektronik","mode":1,"modelid":"Scene Switch","name":"Scene Switch","state":{"buttonevent":6002,"lastupdated":"2018-02-24T16:45:17"},"swversion":"02010032","type":"ZHASwitch","uniqueid":"00:21:2e:ff:ff:01:30:66-01-1000"}

**Comment by ebaauw** [comment]
Did you download the latest commit from GitHub?  I haven’t yet created a new release.

**Comment by ebaauw** [comment]
In homebridge-hue v0.7.0.
