### ISSUE TITLE
Warning triangle with exclamation point in EVE App for my OSRAM Smart+ plug

### ISSUE THREAD

**Issue by Patrick-Ber** [ebaauw/homebridge-hue#294]
Hello,

i get Warning triangle with exclamation point in EVE App for my OSRAM Smart+ plug.
I use the lastest Version of homebridge and homebridge-hue.

I see in the Status from homebridge that all is good.
And it the on/off switch within EVE work also.

But i have this Warning triangle .. can you help ?
(Fernseher is not a HUE Lamp :) )
![image-1](https://user-images.githubusercontent.com/36695911/36511736-1837db02-1768-11e8-9aca-cde65e4092e2.png)

**Comment by ebaauw** [comment]
If you touch the triangle, Eve should give a popup message what it’s about.  Most likely, fault status 1, which means the Hue bridge reports the plugs as unreachable.  You should also see messages in the homebridge log, when homebridge-hue sets or clears the status fault.

**Comment by Patrick-Ber** [comment]
yes, eve show errorcode 1. How can i fix it ?

**Comment by ebaauw** [comment]
Not sure you can.  Sometimes the Hue bridge marks a light (or plug) as unreachable, even thought the light (or plug) is perfectly reachable.  It seems to happen more often with non-Hue lights (or plugs).

You might try to power-cycle the plug (unplug it from the mains), but there’s a good chance the bridge will mark it unreachable again after some time.
