### ISSUE TITLE
Philips Hue Motion Sensor: Custom Duration not working

### ISSUE THREAD

**Issue by lukasroegner** [ebaauw/homebridge-hue#295]
Dear Erik, first of all, thank you very much for your work on this plugin, it just awesome!

I have a problem with the the original Philips Hue Motion Sensor and setting a custom duration via the Eve Duration Characteristic, the `clearTimeout` and `setTimeout` method in the `checkValue` method in the `HueSensor.js` file are executed every time the `checkValue` is executed (as `this.hk[this.type.key] !== hkValue` is always `true`: the HomeKit value is true to indicate presence, the `hkValue` is `false` as the actual state of the sensor is `false`). This leads to the following behaviour: as soon as a motion is detected, the presence never ends, as the timer is always reset (every heartbeat).

I already tried to fix this issue (in order to help you with resolving the problem), but I haven't figured out how to do it. The obvious solution is to change the conditions in the `checkValue` method.

If you need more information, just ask me, however, the issue in the execution flow is obvious in the code.

**Comment by ebaauw** [comment]
Are you using this in combination with the Hue bridge or with deCONZ?

**Comment by lukasroegner** [comment]
I'm using the Hue Bridge v2, only original Philips light bulbs, light strips, switches and motion sensors, not third-party hardware.

**Comment by ebaauw** [comment]
Should work in homebridge-hue v0.7.0.

Note that this behaviour mimics the behaviour of the `config.duration` of the Hue motion sensor (and other sensors that report no more motion) in deCONZ: it delays reporting no motion when motion is no longer detected (_PIR Occupied to Unoccupied Delay_).  This is different from the `config.duration` of sensors that don't report no more motion (like the Trådfri motion sensor): it automatically turns the lights off (_On Time_).

**Comment by lukasroegner** [comment]
I tested the latest release for the last two hours, everything works as expected.
Thank you so much for fixing the bug!
