### ISSUE TITLE
gateway communication error ECONNREFUSED

### ISSUE THREAD

**Issue by Razeeer** [ebaauw/homebridge-hue#296]
Hello,
i have a question, i constantly get this error after a certain time. Can you tell me why?

`deconz: gateway communication error ECONNREFUSED on 192.***.***.31`

Here is my config.json

"platforms": [
{
"platform": "Hue",
"hosts": ["192.XXX.X.31“],
"users": {
"00212EFXXXXXX“: „XXXXXXX“
},
"sensors": true,
"excludeSensorTypes": 
["CLIPGenericStatus", "CLIPGenericFlag", "Geofence"],
"nativeHomeKitLights": true,
"lights": true,
"resource": false
}
]
}

**Comment by ebaauw** [comment]
It means that homebridge-hue cannot open a network connection to the deCONZ web server, serving the REST API.  Are you running homebridge and deCONZ on the same or on different servers?  If different, I’d look for firewall issues.  If the same I’d use 127.0.0.1 in `”hosts”` and check for some other program using port 80.  Could also be that the server’s ip address has changed (if you use DHCP).  There might be more clues in the homebridge logfile.

**Comment by Razeeer** [comment]
Everything works now. Many Thanks!
