### ISSUE TITLE
*_persist.json

### ISSUE THREAD

**Issue by det-box** [ebaauw/homebridge-hue#298]
Hello,
you're creating '* _persist. json 'files.
Can you either save this to 'hombridge / persist /' or be configurable in the 'config. make json '.
Other plugins have an entry in the config.json for the location. 

That would be great, because I want to have the homebridge folder free.

Many Thanks

edit:
should concern this
from readme.md in fakegato-history
``path: '/ place / to / store / my / persistence /' // if empty it wants to use the -U homebridge option if `present, or. homebridge in the user's home folder`

Thanks again

**Comment by det-box** [comment]
in the plugin 'https: // github. com / standards / home bridge-bravia '
  this entry is usable:
'cookiepath': '/ var / homebridge / plugin-persist / sony-bravia / sonycookie',

in the wol plugin "https://www.npmjs.com/package/homebridge-wol" it is this entry:
'cacheDirectory': '/ var / homebridge / plugin-persist / wol-storage',

The plugin for NukiBridge "https://github.com/benzman81/homebridge-nukiio" has this entry:
'cache_directory': '/ var / homebridge / plugin-persist / nuki-persist / storage',

I hope it helps

**Comment by ebaauw** [comment]
No, it doesn’t.  Neither of these plugins use fakegato-history (to mimic the sensor history of Elgato devices in the Eve app, see #277).

**Comment by det-box** [comment]
I had edited in the first post,
you have to put 'path:'

**Comment by det-box** [comment]
Hello,
Unfortunately, I am not a programmer.
It has been checked in:
Store persist files in `~ /. homebridge / accessories`, see # 298.

Is the folder firmly inside?
My homebridge data folder is:
`/var/homebridge/accessories`

or is the entry configurable?

Thank you very much

**Comment by det-box** [comment]
Hi,
have the app updated.
The homebridge stopped.
All _persist. json files deleted in /var/homebridge.
The homebridge started.
Now these files are back in the homebridge folder.

`-rw-r--r--  1 root       root   178 Mär  1 18:01 hbridge3_00158d0001b1482a_persist.json
-rw-r--r--  1 root       root   178 Mär  1 18:01 hbridge3_00158d0001b14841_persist.json
-rw-r--r--  1 root       root   178 Mär  1 18:01 hbridge3_00158d0001dad04c_persist.json
-rw-r--r--  1 root       root   178 Mär  1 18:01 hbridge3_00158d0001dad11d_persist.json
-rw-r--r--  1 root       root   178 Mär  1 18:01 hbridge3_00158d0001e44c15_persist.json
-rw-r--r--  1 root       root   15K Mär  1 18:01 homebridge-hue.json.gz
`
Thanks

**Comment by ebaauw** [comment]
> It has been checked in:

I’m working on these (and other) changes, but they haven’t been released yet.

> or is the entry configurable?

It will be the `accessories` folder of the homebridge user directory, specified with `-U` on startup, or `~/.homebridge` by default.

**Comment by det-box** [comment]
Ok, I'll wait until it's released.

**Comment by ebaauw** [comment]
In v0.8.2.  Please be aware that you need to re-do you HomeKit configuration after upgrading to v0.8.x., see #299.

**Comment by det-box** [comment]
Thank you,
so far okay.
Only one file still appears after a reboot
'homebridge-hue. json. gz'

Can you outsource these to ./accessories?

Thank's

**Comment by ebaauw** [comment]
No, that's the debug dump of the bridge(s) and gateway(s) and config.json - see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by det-box** [comment]
OK
Thank you
go now, can be closed
