### ISSUE TITLE
v0.8.4 doesn't work

### ISSUE THREAD

**Issue by DSchumacher2104** [ebaauw/homebridge-hue#306]
the plugin crashes here when starting. I'm using node v9.6.1, going back to v0.8.3 worked without problems. 

Here is the log:
`Mar 10 13:57:17 raspberrypi3 homebridge[19217]: [2018-3-10 13:57:17] [Hue] TypeError: Cannot read property 'sType' of undefined
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at parseServiceJSON (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:103:26)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:69:19
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at Array.forEach (<anonymous>)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at Object.parseAccessoryJSON (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/AccessoryLoader.js:68:17)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:395:28)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:374:32)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at request.then.catch.then.then.then (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:301:5)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at Function.then (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at fs.writeFile (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:372:11)
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at /usr/lib/node_modules/homebridge-config-ui-x/node_modules/graceful-fs/graceful-fs.js:43:10
Mar 10 13:57:17 raspberrypi3 homebridge[19217]: at FSReqWrap.oncomplete (fs.js:153:20)
`

**Comment by ebaauw** [comment]
I don't know what's happening here.  It's actually homebridge choking on something it gets from homebridge-hue.  What version of homebridge are you running?  Does the error also occur with node v8.10.0?  Does the error also occur when you don't have homebridge-config-ui installed?  

Could you please attach the full debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file).

**Comment by ebaauw** [comment]
Fixed 311 in v0.8.6.  Please re-open and attach files if there's still an issue with that version.

**Comment by DSchumacher2104** [comment]
Thank you, v0.8.6 works here!
