### ISSUE TITLE
Xiaomi Aqara Smart Light Switch Wireless double press

### ISSUE THREAD

**Issue by DocIndiana** [ebaauw/homebridge-hue#307]
HI,
thanks for this awesome plugin.
I have an Aqara Smart Light Switch (Single button). It works fine but only with single press. In HomeKit I can choose the double press option, but a double press is always recognized as two single press. Can I use the double press function witch this switch (an how to set it up), or does it only works with the Aqara smart switch?
I'm using homebridge v0.4.38 with deConz v2.5.8 and your hue plugin v0.8.4

Thanks for your help.

**Comment by ebaauw** [comment]
Which switch is that (modelid)?  Homebridge-hue depends on deCONZ to deliver the right buttonevent value for double press.  I only have the small aqara smart switch, not the wireless or wired wall switches, so I’m not exactly sure what buttonevents they support.

**Comment by DocIndiana** [comment]
Thanks for your answer.
It's the wireless wall switch WXKG03LM. Any chance it will bei supported in one of the next versions?

Off topic: The osram lightify switch isn't supported as well, according to your list, correct?
