### ISSUE TITLE
Add support for CLIPPower sensor

### ISSUE THREAD

**Issue by vbyjsue** [ebaauw/homebridge-hue#310]
It would be a nice feature to be able to set power-consumption to a CLIPPower sensor and have it expose history to Eve in the same way as the currently supported sensors. As I understand this needs to be implemented i Deconz first?

**Comment by ebaauw** [comment]
Yes.  Still on my todo list.

**Comment by ebaauw** [comment]
I created a PR for deCONZ, which should be included in v2.05.14, due later today.

Note that Eve needs both _Total Consumption_ and _Current Consumption_ to display the power history.  There's three scenarios to achieve this:
1. Use a single CLIPConsumption sensor resource and update `state.consumption` regularly with the (total) consumption (in Wh) as reported by the non-ZigBee plug.  In this case homebridge-hue will:
    - Map _Total Consumption_ to `state.consumption`.  You cannot reset _Total Consumption_ from Eve;
    - Create a history entry (every 10 minutes) based on the change to _Total Consumption_ since the previous history entry;
    - Update _Current Consumption_ when creating the history entry, by dividing the change to _Total Consumption_ by 10 minutes;
2. Use a single CLIPPower sensor resource and update `state.power` as the non-ZigBee plug reports a changed value for power (in W).  In this case homebridge-hue will:
    - Map _Current Consumption_ to `state.power`;
    - Create a history entry (every 10 minutes) based on _Current Consumption_, by multiplying `state.power` by the duration since the previous change or history entry;
    - Update _Total Consumption_ when it creates a history entry.  _Total Consumption_ will be reset when you restart homebridge, and when you reset it from Eve.
3. Use a multi-CLIP accessory, combining a CLIPConsumption and a CLIPPower sensor resource and, from your non-ZigBee plug, update `state.consumption` regularly, and `state.power` when the value changes.  In this case homebridge-hue will:
    - Map _Total Consumption_ to `state.consumption`.  You cannot reset _Total Consumption_ from Eve;
    - Map _Current Consumption_ to `state.power`;
    - Create a history entry (every 10 minutes) based on the change to _Total Consumption_ since the previous history entry.

homebridge-hue uses the equivalent of 3) for the Heiman and Xiaomi plugs (as well as for the ubisys dimmer) as these report both `state.consumption` (through the _Metering_ cluster) and `state.power` (through the _Electrical Management_ cluster).  For the OSRAM plug, which only reports `state.power`, homebridge-hue uses the equivalent of 2).

**Comment by ebaauw** [comment]
deCONZ v2.5.14 is out.  homebridge-hue v0.8.7 works with this version.

**Comment by Krocko** [comment]
Can you explain how to create such a ClipPower sensor and how to map devices to it?

**Comment by ebaauw** [comment]
You create CLIP sensors through the deCONZ REST API, by doing a POST to `/sensors`.  Basically, this creates a variable on the gateway, which can be set (through PUT) and read (through GET).  Your real sensor needs to set the CLIP sensor when its value changes.  See https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started#24-clip-sensors.

**Comment by Krocko** [comment]
I know how to create a clip sensor. I successfully created the CLIPPower sensor. But i don't know how to map a osram plug to see the history for on/off like you describe it here

> 2. Use a single CLIPPower sensor resource and update state.power as the non-ZigBee plug reports a changed value for power (in W). In this case homebridge-hue will:
> Map Current Consumption to state.power;
> Create a history entry (every 10 minutes) based on Current Consumption, by multiplying state.power by the duration since the previous change or history entry;
> Update Total Consumption when it creates a history entry. Total Consumption will be reset when you restart homebridge, and when you reset it from Eve.

**Comment by ebaauw** [comment]
You don't.  The CLIP sensors are for non-ZigBee sensors, not connected to deCONZ or the Hue bridge.  The deCONZ REST API creates a ZHAPower sensor for the OSRAM plug, which is picked up by homebridge-hue.  You might need to re-pair the plug, or just open the network from the web/Phoscon app and refresh the basic cluster in the deCONZ GUI.  Unfortunately, the OSRAM plug doesn't seem to report anything useful.

**Comment by Krocko** [comment]
Thank you. Re-pair did the trick.

**Comment by vbyjsue** [comment]
This works really great, although it took me some time to understand how to create the multiclip sensor in DeConz. All examples I found were objects of the result of the get /resourcelinks which included some extra properties, but after checking in deconz code what properties that were expected I got it working. This is how it's done if someone is looking for that info:

POST to /resourcelinks 

```javascript
{
  "classid": 1,
  "description": "multiclip",
  "links": [
    "/sensors/{CLIPPower id}",
    "/sensors/{CLIPConsumption id}"
  ],
  "name": "homebridge-hue",
  "recycle": false
}
```
