### ISSUE TITLE
No more Philips Lights in Home

### ISSUE THREAD

**Issue by hajanet** [ebaauw/homebridge-hue#312]
Hello,
we have a homebridge setup with hue included.
We use a v2 (square)-Bridge with Philips and also other lights.

Since a few days only the Philips lights are dropped off the homekit apps (Apple Home and also Elgato Eve). The Osram- and IKEA-lights are still shown there.

I've read about the major changes of v0.8, but even when I try to reinitialize all the bulbs inside Home everything stays the same: no philips lights.

Is there anything I can do?

Thanks and best regards!
P.S: Very good job here!

**Comment by ebaauw** [comment]
Have you upgraded from a very old version?  I changed the handling of the v2 Hue bridge around the time when Philips started exposing the Hue motion sensor and switches natively to HomeKit.  You need to set `”nativeHomekitLights”: false` in config.json if you want homebridge-hue to expose Hue lights connected to a v2 bridge, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration and https://github.com/ebaauw/homebridge-hue/issues/259.
