### ISSUE TITLE
question: how to prevent double entries

### ISSUE THREAD

**Issue by QHose** [ebaauw/homebridge-hue#314]
hi,

thanks for this wonderful tool!

When I first installed this tool, I got double entries in homekit, so I turned off units also exposed by philips hue bridge, But now I noticed I miss cool features which I think your tool creates (like custom duration for a sensor). 

So how can I make sure all hue items use your homebridge with your tool and stop using the philips bridge?

thanks a lot!

PS: I tried looking for "double" in your help but could not find this challenge.

**Comment by ebaauw** [comment]
The only way to do that is to remove the Hue bridge from HomeKit and only use homebridge-hue.  Afaik, there's no way to tell the Hue bridge to expose just the lights to HomeKit.

**Comment by QHose** [comment]
Thanks, and will the physical hue bridge still be used for the Zigbee Communications?

Verstuurd vanaf mijn iPhone

Op 16 mrt. 2018 om 12:39 heeft Erik Baauw <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The only way to do that is to remove the Hue bridge from HomeKit and only use homebridge-hue. Afaik, there's no way to tell the Hue bridge to expose just the lights to HomeKit.

**Comment by ebaauw** [comment]
Yes, homebridge-hue connects to the Hue bridge using the Hue REST API, just like any other Hue app.
