### ISSUE TITLE
nativeHomeKitSensors „false“ not working 

### ISSUE THREAD

**Issue by krmkrx** [ebaauw/homebridge-hue#316]
My Hue motion sensors and dimmer switches do not get exposed when setting "nativeHomeKitSensors" to „true“. This worked for me in a previous version (prior 8.x).

However, the „true“ setting for "nativeHomeKitLights" does work, all lights get exposed alongside the already to HomeKit exposed lights which are natively connected to the Hue Bridge.

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Configuration: these parameters only have meaning for the v2 Hue bridge.  By default they’re true, meaning homebridge-hue will _not_ expose Hue lights or Hue sensors already exposed by the Hue bridge.  Set them to false to expose Hue lights and/or Hue sensors (also) through homebridge-hue.

Note that you need to set `”lights”` and/or `”sensors”` to true for homebridge-hue to expose any light or sensor.  Also note that whitelists and blacklists override any config.json settings.

If you still think homebridge-hue is in error, please attach your debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by krmkrx** [comment]
> Note that you need to set ”lights” and/or ”sensors” to true for homebridge-hue to expose any light or sensor. 

Thank you. Ths was the culprit.
