### ISSUE TITLE
Danalock v3

### ISSUE THREAD

**Issue by HazCod** [ebaauw/homebridge-hue#318]
#### Issue
Would the Danalock v3 Z-Wave/Zigbee be supported?

**Comment by ebaauw** [comment]
It would need to be supported by deCONZ first.  It seems to support ZigBee HA, so it would be technically possible, but currently deCONZ doesn't yet support any locks.  Best open an issue there.

They mention they support HomeKit.

**Comment by HazCod** [comment]
To keep this issue updated, the response from Dresden Electronics:

```
thanks for contacting the dresden elektronik support.
 
Locks and thermostats also are great products. Our developers plan to integrate things like that in future. But it’s no short term thing. Maybe the community contribute code for such devices.
 
Feel free for contacting us again and have a nice day.
 
Best Regards
 
```

**Comment by ebaauw** [comment]
Sorry, I meant best open an issue here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues.

**Comment by HazCod** [comment]
No problem, created: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/520

**Comment by bohtho** [comment]
Any news with this? It is supported by other zigbee systems bur I pit all my eggs in Deconz/Phoscon and Homebridge-Hue. Not complaining but it has been available and popular for some years, and now I can only use the Danalock app. I am more than willing to test and report.

**Comment by ebaauw** [comment]
We need support in deCONZ, before I can do anything in homebridge-hue.  Even then, adding support might be challenging without having an actual device available for testing. My apartment's front door has weird locks so I don't expect to buy a smart lock anytime in the foreseeable future.  I'll be happy to have a look at any device I can borrow for a while.  Not sure if they work without being installed, though.

**Comment by bohtho** [comment]
I believe they work without being installed.

If you would be able to and bother to get it at a physical store with 90 Days return policy or something (after all it wouldnt even be installed) I could test on an installed one as well, and would of course donate to both OSS projects to make it worth the trouble.

For information there’s postings of screenshots ofthe zigbee clusters etc in the issue under Deconz rest API.

**Comment by bohtho** [comment]
I finally got an answer, but they wouldn’t be able to support development (by a loaner To you etc.) before Q1 2020.
But I did get a zipped long description of their zigbee implementation if you are interested?

**Comment by ebaauw** [comment]
That could be helpful, although I find it very hard to add support for devices I don't have myself.  It typically takes several try and error cycles before the device is fully supported.

Best post the info to the deCONZ issue.

**Comment by bohtho** [comment]
Done! I regret not being able to supply you developers devices, but I promise to be available for testing if that is worth anything.

**Comment by simonbove** [comment]
We are not getting into q1 of 2020. Maybe we should take their offer for a loaner now? We really need locks in deconz :)

**Comment by kneisel** [comment]
in  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/520 @arnerek presented a solution on Jan. 18.  Please consider his repository (https://github.com/arnerek/deconz-rest-plugin/tree/Danalock) - if he misses to make a pull request ...

**Comment by simplenotezy** [comment]
@kneisel any updates on Danalock integration?

**Comment by simplenotezy** [comment]
@ebaauw I believe if you could make the integration, homebridge-hue would be the very first to support Danalock. That would mean we don't need to buy their "HomeKit" version which lacks ZigBee/Z-Wave support. See their comparison between their Bluetooth, Homekit, ZigBee and Z-Wave integrations: https://danalock.com/products/danalock-v3-smart-lock/

**Comment by ebaauw** [comment]
I'm happy to add support to Homebridge Hue, once the Zigbee version of the Danalock is supported by the deCONZ REST API.  Please list what the resource(s) look like, or attach a debug dump file, created after the Danalock has been paired to deCONZ.  I cannot add support in the deCONZ REST API for devices I don't have my hands on.
