### ISSUE TITLE
Xiaomi Door Sensor

### ISSUE THREAD

**Issue by woinkeyman** [ebaauw/homebridge-hue#320]
Similar issue to - https://github.com/ebaauw/homebridge-hue/issues/290

Unable to get the name of the Xiaomi door sensor - it shows up as 0x0000
![screen shot 2018-03-26 at 9 48 00 pm](https://user-images.githubusercontent.com/35811385/37910242-9e63c3f8-313f-11e8-8306-957bc26d375d.png)

First time using the system, I'd opened the gateway using the deCONZ GUI instead of WebApp - after reading issue #290 I tried deleting the sensor, resetting it (long press on reset hole), and re-pairing after opening gateway on WebApp - still no luck :(. Interesting thing is, it detects the door open/close state on the Cluster Info - but not showing up on Homebridge. And name is still 0x0000.

Thanks in advance for your help :)

**Comment by QHose** [comment]
Hi, and how can we add switches Or water sensors etc? Thank you
