### ISSUE TITLE
Philips motion on DeConz don't work anymore in Homebridge Hue

### ISSUE THREAD

**Issue by stefan1957** [ebaauw/homebridge-hue#321]
Hey Erik,

i have a problem with the motion sensor from Philips. I made some rules in deconz, they turn on the lights but leave them on(they need to be turned off after 4 minutes) i use version 2.05.16 of DeConz with the latest firmware.
In homebridge Hue 0.8.8 i see the warning below when i add the rules in deconz:

Log
Mar 26 14:30:29 raspberrypi homebridge[809]: HAP Warning: Characteristic 00000027-0000-1000-8000-656261617577 not in required or optional characteristics for service 00000084-0000-1000-8000-0026BB765291. Adding anyway.
Mar 26 14:32:52 raspberrypi homebridge[809]: HAP Warning: Characteristic 00000027-0000-1000-8000-656261617577 not in required or optional characteristics for service 00000085-0000-1000-8000-0026BB765291. Adding anyway.
Do you no what goes wrong?

Thx in advance
Gr Stefan

**Comment by ebaauw** [comment]
The warning messages don't compute.  They indicate that homebridge-hue tries to access a `Status` characteristic in a Light Level service and in a Motion Sensor service, without adding the characteristic first.  Could you please attach de debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file) and debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file).

As for the lights not turning off, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/494.

**Comment by stefan1957** [comment]
Hoi Erik,

Something like this?

Grtz Stefan

**Comment by ebaauw** [comment]
No attachments?

**Comment by stefan1957** [comment]
Again

M vr gr Stefan
S.J.Koopman
Deventerstraatweg 105
8012AD Zwolle



Begin doorgestuurd bericht:

**Comment by ebaauw** [comment]
You need to upload the attachments to GitHub, I don't think they are passed on through email.

**Comment by stefan1957** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/1853498/homebridge-hue.json.gz)
[homebridge.log.zip](https://github.com/ebaauw/homebridge-hue/files/1853499/homebridge.log.zip)

**Comment by ebaauw** [comment]
I cannot find the warning messages in the log.  Also, the log does not contain debug messages.

```
Mar 26 20:24:08 raspberrypi systemd[1]: Stopping HomeBridge Service...
Mar 26 20:24:08 raspberrypi homebridge[8332]: [2018-3-26 20:24:08] Got SIGTERM, shutting down Homebridge...
Mar 26 20:24:08 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=143/n/a
Mar 26 20:24:08 raspberrypi systemd[1]: Stopped HomeBridge Service.
Mar 26 20:24:08 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Mar 26 20:53:30 raspberrypi systemd[1]: Starting HomeBridge Service...
Mar 26 20:53:30 raspberrypi systemd[1]: Started HomeBridge Service.
...
Mar 26 20:54:28 raspberrypi systemd[1]: Stopping HomeBridge Service...
Mar 26 20:54:28 raspberrypi homebridge[10829]: [2018-3-26 20:54:28] Got SIGTERM, shutting down Homebridge...
Mar 26 20:54:28 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=143/n/a
Mar 26 20:54:28 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Mar 26 20:54:28 raspberrypi systemd[1]: Starting HomeBridge Service...
Mar 26 20:54:28 raspberrypi systemd[1]: Started HomeBridge Service.
...
Mar 26 20:59:23 raspberrypi systemd[1]: Stopping HomeBridge Service...
Mar 26 20:59:23 raspberrypi homebridge[10946]: [2018-3-26 20:59:23] Got SIGTERM, shutting down Homebridge...
Mar 26 20:59:23 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=143/n/a
Mar 26 20:59:23 raspberrypi systemd[1]: Stopped HomeBridge Service.
Mar 26 20:59:23 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Mar 26 21:01:35 raspberrypi systemd[1]: Starting HomeBridge Service...
Mar 26 21:01:35 raspberrypi systemd[1]: Started HomeBridge Service.
```
Did you restart the homebridge service manually or is there something wrong with the setup of the homebridge service?

**Comment by stefan1957** [comment]
Hey Erik,
I restarted homebridge manually that causes the strange log. The strange messages are gone now but the motion sensor still don’t work in phoscon/deconz version 2.05.17. I use HomeKit for that without problems

M vr gr Stefan

**Comment by ebaauw** [comment]
OK, if there's no issue with homebridge-hue, I'm closing this issue.  

Please check the deCONZ issue I mentioned above or open a new issue under deCONZ for Phoscon.

**Comment by ooii** [comment]
> I made some rules in deconz, they turn on the lights but leave them on(they need to be turned off after 4 minutes) i use version 2.05.16 of DeConz with the latest firmware.

I have similar problems. If you added the rule with Phoscon, that may be the problem origin. In my case, the rules created on the bridge are not equivalent to the setup on the web interface. Look this [comment](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/494#issuecomment-376476778).
