### ISSUE TITLE
Philips Hue bridge bulbs and accessories lost after power loss

### ISSUE THREAD

**Issue by saveriospeziali** [ebaauw/homebridge-hue#322]
#### Issue

Hi 
Was a couple of times that my homebridge (running on raspberry pi) loose all the accessories connected to a Philips Hue bridge after a power loss.

It seem a problem similar to the one with deConz..

Adding a delay in homebridge service startup ("ExecStartPre=/bin/sleep 30" in homebridge.service) help a lot but in may opinion the is not an elegant solution also because in this way the delay is applied to every "sudo systemctl restart homebridge" command..

Any suggestion?

#### Log Messages

```
```

**Comment by ebaauw** [comment]
See #246.

**Comment by saveriospeziali** [comment]
Dear Erik I tried the suggestions in #246, at the moment I am not sure they work for me because is quite hard to test.
If I understood well the workaround, with "ph lightlist" you write the lights configuration in the bridge itself in order to retrive the configuration at startup time also if the bridge is still collecting real light data.. right?  :)

I also want to thank you for your VERY great jog !!

Best regards

**Comment by ebaauw** [comment]
Yeah, that’s right.  There will be a message in the homebridge log when deCONZ hasn’t yet fully initialised causing homebridge-hue to delay the startup of homebridge.
