### ISSUE TITLE
Switch off a switch after n minutes?

### ISSUE THREAD

**Issue by jaal2001** [ebaauw/homebridge-hue#324]
Hi,
as Homekit still has no native support for this:
Is it possible to add a default auto off routine to a switch? I have a heater behind a power switch, which should be shut down after n minutes (to prevent forgetting this ...)

Thanks
J

**Comment by ebaauw** [comment]
That's easily done using Hue bridge or deCONZ gateway rules, using a condition with a `ddx` operator.  For example, assuming your switch is on `/lights/1` and you want it to turn off automatically after one minute, you'd create the following rule:
```
$ ph post /rules '{
  "actions": [
    {
      "address": "/lights/1/state",
      "body": {
        "on": false
      },
      "method": "PUT"
    }
  ],
  "conditions": [
    {
      "address": "/lights/1/state/on",
      "operator": "eq",
      "value": "true"
    },
    {
      "address": "/lights/1/state/on",
      "operator": "ddx",
      "value": "PT00:01:00"
    }
  ],
  "name": "Auto turn off"
}'
```
See https://developers.meethue.com/documentation/rules-api or http://dresden-elektronik.github.io/deconz-rest-doc/rules/ for more info on the Hue API.  Type `ph -h` for more into on the `ph` command.

**Comment by jaal2001** [comment]
Took me some work to identify which lightid I had to use, but works like a charm! Thanks for your help!

**Comment by ebaauw** [comment]
Homebridge-hue exposes a _Resource_ characteristic for that reason, but Apple’s home app doesn’t support it.
