### ISSUE TITLE
Bridge discovery not working properly on IPv6 connections

### ISSUE THREAD

**Issue by ustaerk** [ebaauw/homebridge-hue#326]
#### Issue
On an IPv6 internet connection with a DS-LITE IPv4 tunnel, such as used by Vodafone/KabelDeutschland, outgoing connections from multiple users will use the same public IPv4 address. The meethue API will use the outgoing IPv4 address to determine the internal ip address(es) of the bridge(s) in the user's local network. If two (or more) users share the same external IPv4 address, the API will return bridges not actually belonging to the user.

This is not by itself a bug in homebridge-hue but it would help tremendously if one could disable meethue API usage without also disabling UPnP as is the case when putting a "host" directive in config.json

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Added `nupnp` key to config.json, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.  Will be published in next release.
