### ISSUE TITLE
Osram Smart+ Plugs and homebridge-hue power consumption reporting

### ISSUE THREAD

**Issue by linusz99** [ebaauw/homebridge-hue#327]
Hi,
is there any chance that the issue with the not correct reported power consumption with the Osram Smart+ Plug will be fixed. 
Is there any workaround available

- Running Homebridge with homebridge-hue plugin and deconz on Raspi3 and Rasbee

kind regards,
Ralf

**Comment by ebaauw** [comment]
The issue is with the plug itself, you’ll have to ask OSRAM.  I don’t even know if it’s a hardware limitation or if it could be fixed in firmware.
