### ISSUE TITLE
Error with latest deCONZ commits

### ISSUE THREAD

**Issue by Krocko** [ebaauw/homebridge-hue#328]
Hello Erik.

#### Issue
With the latest deCONZ commits https://github.com/dresden-elektronik/deconz-rest-plugin/commit/034c55be3190bb8a83ee14e70fd7a98f7a021596 i get the following error.

#### Log Messages
``` Apr 06 18:13:52 raspberrypi homebridge[8948]: [2018-4-6 18:13:52] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f295f8f1-7da8-4071-910b-6ba807624f58
Apr 06 18:13:52 raspberrypi homebridge[8948]: at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
Apr 06 18:13:52 raspberrypi homebridge[8948]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:377:24)
Apr 06 18:13:52 raspberrypi homebridge[8948]: at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Apr 06 18:13:52 raspberrypi homebridge[8948]: at request.then.catch.then.then.then (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:301:5)
Apr 06 18:13:52 raspberrypi homebridge[8948]: at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
Apr 06 18:13:52 raspberrypi homebridge[8948]: at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
Apr 06 18:13:52 raspberrypi homebridge[8948]: at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
Apr 06 18:13:52 raspberrypi homebridge[8948]: at fs.writeFile (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:372:11)
Apr 06 18:13:52 raspberrypi homebridge[8948]: at FSReqWrap.oncomplete (fs.js:153:20)
```
```

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/1884992/homebridge-hue.json.gz)

[homebridge.3.log.gz](https://github.com/ebaauw/homebridge-hue/files/1884994/homebridge.3.log.gz)

**Comment by ebaauw** [comment]
As I suspected: https://github.com/dresden-elektronik/deconz-rest-plugin/commit/034c55be3190bb8a83ee14e70fd7a98f7a021596 adds `uniqueid` to the Daylight sensor, using the RaspBee's (or ConBee's) mac address.  This causes homebridge-hue to use the same UUID for the gateway and for the Daylight accessories.

Quick workaround: add `"excludeSensorTypes": ["Daylight"]` to config.json.

Structurally: I need to change the logic to generate the UUID for non-ZigBee resources (again...), now taking into account differences between Hue bridge and deCONZ.  (Note to self: double-check `uniqueid` for groups and CLIP sensors).

I think I'll add the Daylight sensor as an additional service to the bridge/gateway accessory (like the link button on the Hue bridge).  This saves another accessory counting towards the 99 accessory limit.

**Comment by Krocko** [comment]
I downgraded to the normal 2.05.19 and deleted the uniqueid. All is working again.
Will wait for the fix.

**Comment by ebaauw** [comment]
In v0.8.10.

**Comment by ebaauw** [comment]
> I think I'll add the Daylight sensor as an additional service to the bridge/gateway accessory (like the link button on the Hue bridge). This saves another accessory counting towards the 99 accessory limit.

That's more complicated than I thought.  Some other time...
