### ISSUE TITLE
Wakeup routine

### ISSUE THREAD

**Issue by friko21** [ebaauw/homebridge-hue#33]
I have 4 different wake up routines in the hue app. But in the home app spear 12 switches for them. (Same in the eve app) 4 have the routine names and the other 8 appear in doubles with names like L_04_NwhyN and L_04_NwhyN_Start. The ones with Start in the ending have the status "on" and all the others are off.
Is this normal? Is there an option to have just one switch per wakeup routine?

**Comment by ebaauw** [comment]
Hi @friko21 ,

I wouldn't go so far as to call this "normal", but apparently this is how the Hue app works (and why I don't use it).  I understand that sometimes the Hue app creates new sensors, even though it already has created them before, and doesn't cleanup old sensors.  You could try to delete your routines from the Hue app, delete these sensors from your Hue bridge, and (re-) create your routines, first-time-right.

You can suppress the CLIP sensors from appearing in HomeKit by setting `clipsensors: false` in config.json (see README), but that will disable all CLIP sensors.
