### ISSUE TITLE
Disable node warning at startup hue plugin?

### ISSUE THREAD

**Issue by Razeeer** [ebaauw/homebridge-hue#330]
Hello, is it possible to disable the node warning when starting the Homebridge via the config.json?

I use a report toole which alerts me to warnings and errors while running the Homebridge. When I start the hue plugin but I always get notified with Telegram. I am using node 9.11.1

HINWEIS: Apr 13 07:08:55 homebridge[30973]: [2018-4-13 07:08:55] [Hue] warning: not using recommended node version v8.11.1 LTS

http://forum.smartapfel.de/forum/thread/1403-homebridge-tool-s-zum-system-update-und-instanzen-überwachen-mit-telegram/

**Comment by ebaauw** [comment]
Sure, use the recommended version ;-).

I develop and test against the latest LTS version of node, use another version at your own risk.  I've seen plenty of issues with incompatibilities between node versions, so I won't remove the warning.

Looking at the example scripts in smartapfel, they don't look for warnings, so I assume you added these yourself?  Best to do more intelligent matching of what messages you want to notify over telegram.

The recommended version is in package.json, `engines.node`.  You can patch that after installing homebridge-hue, again, at your own risk.

**Comment by Razeeer** [comment]
Thanks for the answer,

I would have liked only one option in the config. hide warning .-)
I did not want the message to be turned off completely for all.

Thanks a lot for the great plugin.

**Comment by Razeeer** [comment]
But I changed it with the tip of you in engines.node now the warning is gone until the next update
 😉👍👍👍
