### ISSUE TITLE
Phillips Hue Go Light not exposed

### ISSUE THREAD

**Issue by ConstantinSchreiber** [ebaauw/homebridge-hue#332]
#### Issue

A recently added a Phillips Hue Go Light doesn't get exposed by homebridge although it is visible/working with the phillips hue app.

Any Ideas?

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/1913063/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
You have set `nativeHomeKitLights` in config.json, so homebridge-hue doesn't expose Philips Hue lights.  There's also some invalid entries for the `"Hue"` platform, but homebridge-hue will ignore these after issuing a warning message.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by ConstantinSchreiber** [comment]
Removing nativeHomeKitLights in the config unfortunately did not solve it.

These are the warning messages I get when starting homebridge:

> [4/15/2018, 7:48:38 PM] Loaded plugin: homebridge-hue
> [4/15/2018, 7:48:38 PM] Registering platform 'homebridge-hue.Hue'
> [4/15/2018, 7:48:38 PM] ---
> [4/15/2018, 7:48:38 PM] Loaded config.json with 0 accessories and 1 platforms.
> [4/15/2018, 7:48:38 PM] ---
> [4/15/2018, 7:48:38 PM] Loading 1 platforms...
> [4/15/2018, 7:48:38 PM] [Hue] Initializing Hue platform...
> [4/15/2018, 7:48:38 PM] [Hue] config.json: warning: nativeHomeKit: ignoring unknown key
> [4/15/2018, 7:48:38 PM] [Hue] config.json: warning: classid: ignoring unknown key
> [4/15/2018, 7:48:38 PM] [Hue] config.json: warning: description: ignoring unknown key
> [4/15/2018, 7:48:38 PM] [Hue] config.json: warning: excludephilips: ignoring unknown key
> [4/15/2018, 7:48:38 PM] [Hue] homebridge-hue v0.8.7, node v9.8.0, homebridge v0.4.38
> [4/15/2018, 7:48:38 PM] [Hue] warning: not using recommended node version v8.10.0 LTS
> [4/15/2018, 7:48:45 PM] [Hue] warning: lastest version: homebridge-hue v0.9.0
> [4/15/2018, 7:48:45 PM] [Hue] Philips hue BER: Philips BSB002 bridge v1802201122, api v1.24.0
> [4/15/2018, 7:48:45 PM] [Hue] Philips hue BER: warning: not using recommended Hue bridge api version 1.23.0
> [4/15/2018, 7:48:45 PM] [Hue] Philips hue BER: 6 accessories
> [4/15/2018, 7:48:45 PM] [Hue] masked debug info dumped to /root/.homebridge/homebridge-hue.json.gz
> [4/15/2018, 7:48:45 PM] [Hue] Initializing platform accessory 'Philips hue BER'...
> [4/15/2018, 7:48:45 PM] [Hue] Philips hue BER: 3 services
> [4/15/2018, 7:48:45 PM] [Hue] Initializing platform accessory 'Dimmable light 1'...
> [4/15/2018, 7:48:45 PM] [Hue] Initializing platform accessory 'Dimmable light 2'...
> [4/15/2018, 7:48:45 PM] [Hue] Initializing platform accessory 'Dimmable light 3'...
> [4/15/2018, 7:48:45 PM] [Hue] Initializing platform accessory 'Dimmable light 4'...
> [4/15/2018, 7:48:45 PM] [Hue] Initializing platform accessory 'Dimmable light 5'...
