### ISSUE TITLE
Do you need the Xiaomi gateway ?

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-hue#339]
#### Issue

I have now several Xiaomi sensors attached to the Xiaomi gateway. If I buy a Rasbee or a ConBee do I still need the Xiaomi gateway?

#### Log Messages

```
```

**Comment by ebaauw** [comment]
No, you don't.  You pair the sensors to the RaspBee or ConBee instead.

**Comment by tomsteenbakkers** [comment]
One more thing: which zigbee device is the best: RaspBee or ConBee. Besides that raspbee is cheaper but in the specifications it’s says that it is not compatible with Philips hue.

**Comment by ebaauw** [comment]
As far as deCONZ is concerned, they’re the same device (they even share the same firmware).  The difference is how they connect to your server.

The RaspBee obviously only works on a Raspberry Pi.  The ConBee works on any platform that deCONZ supports.  Also,  the ConBee can be flashed with different firmware to support ZigBee sniffing.  By using a USB extention cable (female A - A), you can position the ConBee away from you computer’s WiFi and Bluetooth, to reduce interference.

Neither RapsBee nor ConBee is compatible with the Hue bridge.  Both are compatible with Hue lights, sensors, and switches (although there’s still an issue with the Hue tap).  Neither supports, older, pre-Hue Philips lights (Living Colors, Living Whites), that need to be touchlinked to the Hue bridge using a remore.

**Comment by tomsteenbakkers** [comment]
Thanks 👍👍
