### ISSUE TITLE
Rooms and Name not saved 

### ISSUE THREAD

**Issue by WinceWe** [ebaauw/homebridge-hue#34]
Hello friends,

i've set up homebridge-hue and everything is working good except for the room and Name setup. 
Everytime i set rooms and namens to my motion sensors and the rest which is added by homebridge, it gets back to "standard room" after a few seconds. It's not working with different Apps (Apple Home, eve..) and parameters in config. 
Does anybody know what could be wrong?

Thank you very much!
Wince

**Comment by ebaauw** [comment]
The Rooms and accessory/service names are stored in the HomeKit database, like HomeKit scenes and triggers.  They can only be accessed by HomeKit apps; they're inaccessible to HomeKit accessories, such as homebridge.

I suspect you have multiple iOS devices and/or AppleTVs in your setup?  I experience the same behaviour on occasion, especially when setting up HomeKit triggers.  It would appear the synchronisation of the HomeKit database between iDevices (through iCloud) somehow overrides the changes you just made.  I find that making only a few changes at a time and waiting for them to appear on your other iOS devices tends to solve, or at least workaround, this issue.  If that fails, log out of iCloud from all your iOS devices (including your AppleTV), except one, where you make the changes.  Then re-login to iCloud on each device.

**Comment by WinceWe** [comment]
Thank you very much for your quick and helpful reply!

I have my iPad set as the control center, so as you said, this was the problem.
Thanks to your hint, I solved the problem in the following way:

_Updated all included iOS devices to newest iOS-Version
_On all iOS-devices, except the iPad (control center):
  Settings > iCloud > In the list, disable iCloud for "Home"
_Set all rooms and names on the iPad
_Enable iCloud for "Home" again on all other devices

Thank you again! I hope that helps for everybody who has the same problem.
Greetings
