### ISSUE TITLE
HEIMAN Siren HS2WD-E killed my homebridge

### ISSUE THREAD

**Issue by saveriospeziali** [ebaauw/homebridge-hue#340]
#### Issue

Hi 
I have a big problem after adding HEIMAN Siren HS2WD-E 
I have both Philips HUE and deconz, today I added the siren to deconz but homebridge stopped working, I continue to have "Cannot add a bridged Accessory with the same UUID as another bridged Accessory" 
I tried to clean both persist accessories directories, no success..
removed siren from deconz and reboot.. no success..

At the moment my homebride is dead

Can you help me ?

Regards

#### Log Messages
May 10 20:24:26 raspberrypi homebridge[541]: [2018-5-10 20:24:26] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4120af75-9013-4c44-8f63-5c955df196d1

**Comment by ebaauw** [comment]
I don't think this is related to the Siren.

Did you move any devices from your Hue bridge to deCONZ, without deleting the corresponding resource from the Hue bridge?  homebridge-hue bases the UUID on the ZigBee mac address, so having the same device on both the Hue bridge and deCONZ would cause this.

If that's not it, please attach the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file) and debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file).

**Comment by saveriospeziali** [comment]
Hi ebaauw

thank you to help me.. !

I am almost sure there is something related with siren because I booted a backup SD from a couple of day ago, it worked.. after that  I re-added siren and AGAIN still the same error.. !
well I bricked both production an backup !! :(

Is seem something related with Daylight 

May 10 23:46:00 raspberrypi homebridge[514]: [2018-5-10 23:46:00] [Hue] Initializing platform accessory 'Daylight'...
May 10 23:46:00 raspberrypi homebridge[514]: [2018-5-10 23:46:00] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4120af75-9013-4c44-8f63-5c955df196d1
May 10 23:46:00 raspberrypi homebridge[514]:     at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
May 10 23:46:00 raspberrypi homebridge[514]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:377:24)
May 10 23:46:00 raspberrypi homebridge[514]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
May 10 23:46:00 raspberrypi homebridge[514]:     at request.then.catch.then.then.then (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:301:5)
May 10 23:46:00 raspberrypi homebridge[514]:     at Function.then (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
May 10 23:46:00 raspberrypi homebridge[514]:     at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
May 10 23:46:00 raspberrypi homebridge[514]:     at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
May 10 23:46:00 raspberrypi homebridge[514]:     at fs.writeFile (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:372:11)
May 10 23:46:00 raspberrypi homebridge[514]:     at FSReqWrap.oncomplete (fs.js:135:15)

I am so tired..
Tomorrow I will send you all the logs

Best regards

**Comment by ebaauw** [comment]
> Is seem something related with Daylight

Sounds like #328.  What version of deCONZ and of homebridge-hue are you running?

**Comment by saveriospeziali** [comment]
Hi ebaauw

I am running the latest version of homebridge-hue and deCONZ because i tried to update after the problem occurred, I do not remember which version was installed before.

**"excludeSensorTypes": ["Daylight"]** finally helped but all my configuration was destroyed.. I cut a lot of thinks and I was forced tho re-add homebride to HomeKit.. a lot of work was lost !! :(

I still do not understand well what happened.. can you explain ?

Regards

**Comment by saveriospeziali** [comment]
Dear ebaauw

Thank you very much for your great support I am unable to sen logs because at the moment everything is working, thank you again for your great job

Regards
