### ISSUE TITLE
not working with 0.4.42?

### ISSUE THREAD

**Issue by QHose** [ebaauw/homebridge-hue#341]
hi,

I have the idea that this software does not work together with the homebridge 0.4.42 update. I installed it yesterday and now I have the issue that I can't control my devices via the raspbee anymore. I do see that e.g. when I press a button, I do see that notification in the homebridge log, but nothing more happens (the light does not go on)

**Comment by ebaauw** [comment]
> I have the idea that this software does not work together with the homebridge 0.4.42 update.

I don't.  I'm running homebridge-hue v0.9.2 with homebridge v0.4.42 without any problems.  Raspberry Pi, node v8.11.1.

> now I have the issue that I can't control my devices via the raspbee anymore

Can you control your devices from the Phoscon app or from the old web app?  Does the deCONZ GUI show red nodes?

> I do see that notification in the homebridge log

Please attach the full debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file).

**Comment by pponce** [comment]
I had an issue with homebridge 0.4.42 where i experienced the same type of problem. There appears to be an at least with the rPI3 that has multiple network interfaces. 
See issue https://github.com/nfarina/homebridge/issues/1843
I on my pi3 i had to run this command for things to start working.
sudo ifdown wlan0

**Comment by QHose** [comment]
thanks, yeah somehow it now all works, with exactly the same version...
