### ISSUE TITLE
Cannot get individual light bulbs

### ISSUE THREAD

**Issue by tellice** [ebaauw/homebridge-hue#342]
#### Issue

I am using the latest version of homebridge, v0.4.42, the latest version of homebridge hue v0.9.2. up to date node.js v9.11.1 (as its required for my other plugins)

I cannot get the individual light bulbs to show. I can get the rooms, entertainment areas, senors, hue tap, groups all to show. And the light bulbs operate as the groups etc. But i want them to show individually in the home app. I have tried all i can think off with no success, and i didnt know where to post.  Can you help?

My config.jsn for hombridge-hue looks like this (i have masked the hue bridge access codes):
        {
            "platform": "Hue",
            "users": {
                "xxxxxxxxxxxxxxxx": "xxxxxxxxxxxxxxxxxxxxxxxxx"
            },
            "sensors": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "linkButton": false,
            "excludeSensorTypes": [
                "CLIPPresence",
                "Geofence",
                "Daylight"
            ],
            "lights": true
        }

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Setting `nativeHomeKitLights` will prevent homebridge-hue from exposing Philips lights on a v2 Hue bridge.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.
