### ISSUE TITLE
Phillips Hue Motion Sensor not support HomeKit?

### ISSUE THREAD

**Issue by Ghost108** [ebaauw/homebridge-hue#346]
Hello :)

today I give my ikea motion sensor back and bought the Phillips hue motion sensor instead.
All Works good.

With the hue app I add the motion sensor to the bridge and configured it.
But via HomeKit App, the sensor will shown with a "Home"-Icon and the comment "Not supported"

Any idea why?

**Comment by ebaauw** [comment]
Are you using the v2 Hue bridge or homebridge-hue to expose the sensor to HomeKit?  If homebridge-hue, did you restart homebridge after adding the sensor?

**Comment by Ghost108** [comment]
i hope that i can answer your question correctly.
I using the v2 hue bridge and pair the motion sensor with iOS hue app.

i ales use homebridge on my Raspberry with the homebridge-hue plugin.
This is my config:

`{
            "platform": "Hue",
            "name": "homebridge-hue",
            "host": "MY_IP",
            "parallelRequests": 5,
            "users": {
                "xxx": "xxx"
            },
            "heartrate": 2,
            "timeout": 5,
            "lights": true,
            "sensors": true,
            "excludeSensorTypes": [
                "Daylight",
                "Geofence",
                "CLIPSwitch",
                "CLIPLightLevel",
                "CLIPOpenClose",
                "CLIPPressure",
                "CLIPHumidity",
                "CLIPTemperature",
                "CLIPGenericFlag",
                "CLIPPresence"
            ],
            "linkButton": false
        },`

**Comment by ebaauw** [comment]
You need to set nativeHomeKitSensors to false in config.json, if you want homebridge-hue to expose sensors that the v2 Hue bridge also exposes.  I wouldn’t know why the sensor as exposed by the Hue bridge shows as not supported.  Did you try and restart the bridge?  If that doesn’t help: what dies the sensor look like in other HomeKit apps?
