### ISSUE TITLE
Exclude lumi.sensor_switch_aq2

### ISSUE THREAD

**Issue by QempZor** [ebaauw/homebridge-hue#351]
I'm trying to exclude the Xiaomi buttons from homebridge.
I already programmed them through Home Assistant, however they show up, because they're linked through DeCONZ.

Is there a way to exclude them? 
I think it's not possible to exclude all kind of lumi.sensor because my smoke detectors also starts with lumi.sensor...

Any ideas?

**Comment by ebaauw** [comment]
Create a blacklist resourcelink with the sensor resources you want to exclude.  See https://github.com/ebaauw/homebridge-hue#configuration.

**Comment by jerzytraczynski** [comment]
Hi, I don't get it. Can you please elaborate and give an example of blacklisting or whitelisting specific sensor/devices/accessories?

**Comment by ebaauw** [comment]
Use the API to create the resourcelink, by doing a POST to `/resourcelinks` with a body like what's shown in https://github.com/ebaauw/homebridge-hue#configuration.  See https://developers.meethue.com/develop/get-started-2/ for how the API works (the deCONZ API is almost the same).
