### ISSUE TITLE
I really need an example of a config.json file

### ISSUE THREAD

**Issue by SolarDiode** [ebaauw/homebridge-hue#355]
I apologies for being new to all this stuff but despite all my reading and attempts I need a hand with the config.json file.  

I have homebridge installed fine on my Arm7 Pi.  

At home I have the Hue Bridge and several innr bulbs. 

Are you able to show me an example config file with explanation.   As a newbie it's tough enough to get to grips with the installation let alone decrypting a file. 
Thanks so much

**Comment by ebaauw** [comment]
See http://json.org for a description of the format for config.json.  There's no encryption.

See https://github.com/nfarina/homebridge#installation-details for an example config.json and how to edit it.  Make sure the structure is like:
```
{
  "bridge": {
    ...
  },
  "platforms": [
    {
      "platform": "homebridge-hue",
      ...
    }
  ]
}
```

See https://github.com/ebaauw/homebridge-hue#configuration for the `"platform"` object for homebridge hue.
