### ISSUE TITLE
Homebridge keeps asking for pressing the link button

### ISSUE THREAD

**Issue by Tobi2707** [ebaauw/homebridge-hue#363]
#### Issue

Hello,
just installed mein homebrdige hue plugin which seems to work fine, but when restarting homebridge it keeps staying in a loop asking for pressing the link button and an isue with devicetype. What's wrong there?
I copied the user which was generated the first time into the config.json but it keeps staying in this loop until I pres the button. Then it works fine.

Maybe you have some advice oder help for me.

#### Log Messages

```
2018-7-20 12:23:17] [Hue] Philips hue: bridge request 1 post / {"devicetype":"homebridge-hue#raspberrypi"}
2018-7-20 12:23:17] [Hue] Philips hue: bridge error 101: link button not pressed
2018-7-20 12:23:17] [Hue] Philips hue: press link button on the bridge to create a user

2018-7-20 12:23:31] [Hue] Philips hue: bridge request 2: post / {"devicetype":"homebridge-hue#raspberrypi"}
2018-7-20 12:23:31] [Hue] Philips hue: bridge error 101: link button not pressed
2018-7-20 12:23:31] [Hue] Philips hue: press link button on the bridge to create a user

2018-7-20 12:23:44] [Hue] Philips hue: bridge request 3: post / {"devicetype":"homebridge-hue#raspberrypi"}
2018-7-20 12:23:44] [Hue] Philips hue: bridge error 101: link button not pressed
2018-7-20 12:23:44] [Hue] Philips hue: press link button on the bridge to create a user
```

**Comment by ebaauw** [comment]
You probably didn’t copy the text correctly.  The bridge id and username are case sensitive.  Did you double-check you’re using the correct config.json?

**Comment by Tobi2707** [comment]
I'will check it again after work today. But i should be correct, because I copied it, of course I'will doublecheck it.
What das the message with devicetype mean? is this an error? And what is the correct way to set up the data?
1. Start the homebridge
2. Wait till "press link button..." and press it
3. Copy the bridge id and user into the config.json
4. restart homebridge?

**Comment by ebaauw** [comment]
It’s the request homebridge-hue sends to the Hue bridge to create a username (apikey).  I log the request in case of an error.

That is the correct way.  If it still won’t work, please attach the debug log file (see 
https://github.com/ebaauw/homebridge-hue#debug-log-file) and the debug dump file (see 
https://github.com/ebaauw/homebridge-hue#raising-issues)

**Comment by Tobi2707** [comment]
So, just double-checked the config.json.
The problem was not the user, the bridge id was wrong. Did not use uppercase.
Now I replaced the bridge id and it works fine. Thank you for your help and sorry for me stupid mistake.

Maybe you can answer me another question, i start the homebridge in terminal and when I close the terminal, also homebridge stops. What's the correct way to start homebridge and maybe to start it if the pi restarts on startup?

**Comment by ebaauw** [comment]
If you start it from a terminal, use `nohup`.  To start it automatically on (re-)boot, create a service for `systemctl`, see 
https://github.com/nfarina/homebridge/wiki/Running-Homebridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd

**Comment by buenso** [comment]
hello @ebaauw 
I have some problems with adding  "users" in json concerning automatic login on hue hub via homebridge.

Although typing the correct information, I keep getting the error : " Config syntax error, Config contains invalid json

   "name": "Hue",
            "anyOn": false,
            "groups": false,
            "hosts": [
                "192.168.xxx.xxx"
            ],
            "users": {
                "00178xxxxxxxxxx": "4QKLhSksuYtbw-KZXbBPRrbhpAWTTyMMcLPjpeC5"
            ]
            "lights": true,
            "linkButton": false,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": false,
            "sensors": false,
            "platform": "Hue"


            ]
