### ISSUE TITLE
Group of power outlets shown as light bulb

### ISSUE THREAD

**Issue by aryelevin** [ebaauw/homebridge-hue#366]
#### Issue

Hi again with another issue:
I have a group of power outlets mixed from innr and osram, for some reason the group itself shown as lightbulb service, any explanation why this happens?
Isn't the design is to show it as a switch or outlet service?

thanks in advance for the help

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Groups are always exposed as _Lightbulb_, see https://github.com/ebaauw/homebridge-hue/blob/6f28597e00c5a0479217705436bca66a74cfee29/lib/HueLight.js#L441-L444  There's no easy way to recognise that a group consists only of plugs (in fact, it's not even straightforward to recognise that a light resource is, in fact, a plug, see e.g. #361).

**Comment by aryelevin** [comment]
Hmmm, OK, I understand that...
I think I will solve that by tweaking the code to my needs.

It's weird that it is structured like that.

Thank you so much.

**Comment by ebaauw** [comment]
I've been thinking about supporting a special whitelist (`/resourceitems` resource) to indicate which `/lights` and `/groups` resources should be exposed as _Outlet_ instead of _Light bulb_.  That would solve issues with plugs or in-wall switches not exposing the right ZigBee device id, and would provide greater flexibility.  Would that be of help to you?

**Comment by aryelevin** [comment]
Yea, this idea is a good one, very flexible, and will be useful to solve those issues.

Thanks a lot Erik

**Comment by aryelevin** [comment]
Thanks Erik

I saw your release

Will give it a try

**Comment by wuzefacke** [comment]
I'm running it in a docker container so I can't access with this codes.
Would it be possible to integrate it in Homebridge config?

**Comment by ebaauw** [comment]
> I'm running it in a docker container so I can't access with this codes.

`ph` is just another app using the REST API.  You can still access the deCONZ REST API when deCONZ is running in a container, or you wouldn't be able to use the Phoscon app.  You can run `ph` from a shell inside the container, or on any another machine where you install homebridge-hue-utils.  Alternatively, you can use any tool (including `curl`) to create the resourcelink on the deCONZ gateway.

> Would it be possible to integrate it in Homebridge config?

I'm not going to do that -- too error prone.

**Comment by wuzefacke** [comment]
I got no deconz Gateway. I‘m using Philips Hue Bridge 2

Von meinem iPhone gesendet

**Comment by ebaauw** [comment]
Even simpler.  Specify the ip address of the hue bridge, using `ph -H 192.x.x.x`.  Run `ph` from a shell inside the homebridge container, or install homebridge-hue-utils on your host system.

**Comment by clipse2004** [comment]
Hi, 
sorry but i have to warm up the topic again. 
I think I'm being too stupid, I just can't find the resource links. 
I Terminal I was now in the following folder: 
/usr/local/lib/node_modules/homebridge-hue/lib 
then I tried ph outlet -v with the following result: 

ph: error: get /config: http status 404 Not Found
ph: fatal: localhost: not a Hue bridge nor deCONZ gateway

then I tried it under /var/homebridge where the config is located, same result. 

I just want the Osram Outlets to be shown as sockets :( can you help me a little bit please?

I thank you

**Comment by ebaauw** [comment]
The resourcelinks are resources on the Hue bridge or the deCONZ gateway, see the API documentation.  You need to specify the ip address of the bridge or gateway to `ph` by using `-H` or by setting `PH_HOST`, see `ph -h`.

**Comment by clipse2004** [comment]
in the same moment i decided to have a look at the rest of the client. 
See there, there are the resource links :) 
I can't use RESTClient ph with Firefox, does it matter if I create the resource over it?

**Comment by clipse2004** [comment]
uh i got it, holy shit this is really easy if you know how. :) thanks for your help
