### ISSUE TITLE
Support ubisys J1 as shutter

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#367]
See https://github.com/dresden-elektronik/deconz-rest-plugin/pull/727.

**Comment by ebaauw** [comment]
@ma-ca, I've added support for window covering devices in v0.10.3.  Not yet tested for the J1 - would love to hear your experiences.  I haven't yet implemented tilting using `state.sat`.

**Comment by ma-ca** [comment]
I will try next weekend.

**Comment by ma-ca** [comment]
Very nice. The ubisys J1 devices are now shown with a symbol for blinds in the Home app. They have the states _Open_, _Closed_ or, if partially open,  _Open xx%_. The state 100% corresponds to fully open.

Also Siri now reacts to commands _Open_ or _Close_. The command _Open 80%_ does move the shade either up or down until the position is 80% open. Very nice.

A little confusion in the first place is that the command _Close 80%_ does exactly the same what _Open 80%_ does. 

I have venetian blinds which only know the command move to lift, so I don't know which Siri command would send a move to tilt.

The support for window covering is working great. Thanks for that. And at the same time it now is possible again to tell Siri to turn off all lights without also moving the shades.
