### ISSUE TITLE
Hue dimmer switch repeat setting

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#368]
If you're as old a me, you might remember your first analogue joystick had a _normal_/_repeat_ switch.  Normally, you would have to press/release the trigger repeatedly in quick succession to fire a salvo, but in the _repeat_ setting, you could keep the trigger pressed and the joystick would send press events repeatedly.  I'm thinking of a similar option for the Hue dimmer switch.

As you might know, the Hue dimmer switch generates the following events (`buttonevent` values):
- x000: initial press;
- x001: hold;
- x002: release (after initial press);
- x003: release (after hold).
As far as I know, the Hue dimmer switch is the only switch that sends a _hold_ event every second (or so), while the button is held.

Currently homebridge-hue issues a HomeKit _Single Press_ on the x002 event, and a _Long Press_ on the first x001 or x003 event (the x000 and first x001 from the Hue bridge might be missed, due to polling).  With the "repeat" setting, homebridge-hue would issue a HomeKit _Single Press_ on each x001 event and on the x002 and x003 event, while _Long Press_ would no longer be issued.  Of course this would work best with deCONZ, issuing a web socket event for every button event.

This idea came to mind while controlling my Sonos speakers from an IKEA remote.  I would like to be able to hold a button for _Volume Up_, instead of having to press/release the _Up_ button repeatedly.  However, neither HomeKit nor Sonos supports anything equivalent to the typical ZigBee _Move to level_ and _Stop_ commands, which map so well to the x001 and 0x003 events. With repeat, a HomeKit automation could simply do a _Volume increase_ on each _Single Press_ event.

Note that this still wouldn't allow for light dimming from HomeKit automations, as HomeKit lacks a `bri_inc` equivalent.

Help wanted:
- Would you be interested in such an option?  What would you use it for?
- Would you be interested in custom characteristics to increase/decrease the brightness, as I've created for volume and track in homebridge-zp?
- How would you want to set repeat mode?
  - Using a resourcelink?  What about different settings per button?  Four resourcelinks?
  - Using another custom characteristic.  That would involve re-introducing a custom service for the switch to hold this characteristic.  _LastUpdated_, _Enabled_, and _Resource_ would then also move there (they're actually still there in the _Service Label_ service, but even Eve doesn't show this service).  Also this would require dynamic homebridge accessories (see issue #4) to persist the setting accross homebridge restarts.

**Comment by Garywoo** [comment]
Am I right in thinking that `hueDimmerRepeat` is only supported when `nativeHomeKitSensors` is set to  `false`?

I currently have 10 sensors and switches set up using the native Hue HomeKit support. Would I need to re-configure my automations to enable `hueDimmerRepeat`?

**Comment by ebaauw** [comment]
Yes, you need to expose the Hue dimmer through homebridge-hue.  Note that, unlike deCONZ, the Hue bridge doesn’t send notifications, so you’ll get one _Single Press_ per `heartrate` interval.

The Hue bridge will continue to expose the Hue dimmer switch, unless you remove it from HomeKit, so your existing automations will still be there.  HomeKit will see the Hue dimmer switch exposed by homebridge-hue as a different accessory, so you would need to do the room, scene, and automation settings for that.

**Comment by ckeech** [comment]
I'm a bit confused by this. I have used this for the same reason you mentioned, Symfonisk sound controller vol up and down. I've noticed you have to move it slowly left and right and the repeats are quite slow.

Alternatively now I'm trying to use the Ikea TRADFRI on/off switch and long presses don't seem to ever repeat. I'm using deCONZ.  `nativeHomeKitSensors ` is on true, tried changing to false and it didn't seem to make a difference.
