### ISSUE TITLE
Feature request: Living Scenes support (Hue Labs)

### ISSUE THREAD

**Issue by Brklnbnc** [ebaauw/homebridge-hue#369]
In Hue Labs it is possible to create living scenes. Each living scene seems to be saved in the bridge as six individual color schemes. A living scene can be added to a dimmer switch or tap switch, but do you think it somehow be possible to have these scenes available as regular scenes in HomeKit?

**Comment by ebaauw** [comment]
homebridge-hue, or any HomeKit accessory, cannot access HomeKit scenes.  The HAP protocol only allows accessories to expose themselves to HomeKit.  To interact with HomeKit scenes, rooms, automations, etc, you need a (companion) HomeKIt app on iOS, that talks the HomeKit API.

If you reverse-engineer the rules created by the Hue lab routine, they probably use some CLIPGenericStatus (or CLIPGenericFlag) sensors to maintain state, and some rules to recall the scenes based on the CLIP sensor's value.  By exposing these CLIP sensors to HomeKit, you can include their value in a HomeKit scene (use Eve for Status, as Apple's Home doesn't support it).  When the HomeKit scene is recalled, it sets the status, which causes the bridge to recall the Hue lab scene.

**Comment by mikesalz** [comment]
Sorry to bring this one back up.  I think @Brklnbnc was not looking to access HomeKit scenes but rather to access Hue scenes from within Homebridge/HomeKit.  I would also love the ability to have living scenes exposed to HomeKit.  @ebaauw - Is there any way to do this, or is the only option to reverse engineer the Hue scene?  And if that is the case, how would you go about doing that?  Thanks in advance!!
