### ISSUE TITLE
DeCONZ how fill config?

### ISSUE THREAD

**Issue by igitlin** [ebaauw/homebridge-hue#370]
i have Raspbee board for RPI3b, how correct fill config, how add Aqara device and etc.?

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue#configuration and https://github.com/ebaauw/homebridge-hue/wiki/Configuration.  If you run homebridge and deCONZ on the same Raspberry Pi, best use `"host": "127.0.0.1"`.

You need to pair your devices with deCONZ, through the Phoscon app or through the old web app, and then restart homebridge.  homebirdge-hue only looks for new devices on startup.

**Comment by igitlin** [comment]
thanks, 
i see your links, but all example for HUE bridge, no one for deCONZ.
can you share complete example config for deconz?
homebridge and deCONZ on some RPI
i'm connect Philips bulb, Ikea tradfri dimmer, INNR LED stripe and Aqara Door\Window sensor

**Comment by igitlin** [comment]
Very thanks - all work, except Scenes. Dimmer IKEA look like a Philips 4 button remote in homekit,

**Comment by ebaauw** [comment]
Yes, the IKEA dimmer is exposed (by deCONZ) as having four buttons: _On_, _DimUp_, _DimDown_, and _Off_, corresponding to the commands the dimmer sends.  For the Hue dimmer switch, homebridge-hue also provides _Long Press_ for each button.

Do you mean HomeKit scenes?  These cannot be accessed by a HomeKit accessory (which is homebridge).  You need a HomeKit app running on iOS to create them (they’re created by the Hue app,  ot by the Hue bridge).

**Comment by igitlin** [comment]
Phoscon (deCONZ) scenes and rules

**Comment by igitlin** [comment]
How to disable VPIR motion and FSM_STATE motion?
Maybe add new key "DisableDevice": [Light1, Motion3]

**Comment by ebaauw** [comment]
There’s no way to expose Phoscon scenes to HomeKit.  You can expose rules, to en/disable them and to monitor when they’re executed.  Note that Apple’s Home app doesn’t support this, so you’d need another HomeKit app, like Eve.

I think these are CLIP sensors?  Use `excludeSensorTypes` to disable an entire type.  To disable individual resources, create a blacklist resourcelink, see 
https://github.com/ebaauw/homebridge-hue/issues/179.
