### ISSUE TITLE
Pairing iOS with Hue Bridge - Scan Finds Two Bridges

### ISSUE THREAD

**Issue by Lorccan** [ebaauw/homebridge-hue#371]
I had to delete the Hue app from my iPhone. When I tried to re-pair with the Hue Bridge, it could not be found. When I examined the problem more closely, I noticed that actually 2 Hue Bridges were found at the beginning of the process, but that the pairing process did not complete. (I was not asked, for example, to press the Hue Bridge button.) I was able to reproduce the issue using my iPad.

When I stopped homebridge, I was able to pair normally so I am wondering whether something to do with homebridge-hue could be causing the issue.

Here's the relevant part of my config.json:

```
 {
            "platform": "Hue",
            "users":    {
                "001788FFXX41735F": "ueJZuXXOt4irIEimmdkRuz8AjMT-v-NCWnwQkeNe"
                        },
            "nativeHomeKitSensors":     true,
            "nativeHomeKitLights":      true,
            "sensors":                  true,
            "lights":   true,
            "linkButton":       false,
            "heartrate":        2,
            "host":     "192.168.0.102"
    }
```

**Comment by ebaauw** [comment]
Technically, homebridge-hue cannot interfere in the communication between the v2 Hue bridge and HomeKit.
