### ISSUE TITLE
Feature request: Add convert devicetype

### ISSUE THREAD

**Issue by igitlin** [ebaauw/homebridge-hue#372]
if possible please add convertation of device
example:
button convert to motion sensor
this need to create Video door bel from Aqara button, any ip or usb camera (homebridge-camera-ffmpeg) and door lock in one room.
if anybody push button (as motion sensor in homekit) iphone open window with video from camera and button for unlock door .
This plugin has a some convertation functions https://www.npmjs.com/package/homebridge-zway

**Comment by ebaauw** [comment]
Create a CLIPPresence sensor, which homebridge-hue exposes as a motion sensor, and some deCONZ rules, to set `state.presence` when the button is pressed.  See
https://github.com/ebaauw/homebridge-hue/issues/179.
