### ISSUE TITLE
Question: Fade In/Out 6 Lights

### ISSUE THREAD

**Issue by RGSMA** [ebaauw/homebridge-hue#373]
Hello and sorry if I didn't search enough to answer this question. I read closed issue #131 which helped quite a bit.

I have both your plugin running via Homebridge on a RPi as well as a 2nd generation Hue Bridge. I have 6 hue color bulbs in a straight line. I am trying to have all bulbs start at the same color 0% brightness, then the outer most 2 bulbs transition to 100% and fade down to 0%, followed by the next inner most 2 bulbs that transition to 100% and down to 0%, and finally the last 2 (and then repeat). Your plugin is fantastic for controlling individual bulbs in a group for this purpose. I'm just trying to figure out the most efficient way to accomplish this task. I will probably use the Eve app to create my scenes with transition times but since you are very knowledgable with regards to Hue, I'm wondering if you have any thoughts on the best way to accomplish this. Thanks in advance.

**Comment by RGSMA** [comment]
Thanks for the code, Erik. I'm not currently running deCONZ gateway; I use a hardware Hue Bridge as well as your plugin. Is deCONZ gateway pretty easy to configure?

**Comment by ebaauw** [comment]
The [API](
http://dresden-elektronik.github.io/deconz-rest-doc/) is very similar to the Hue API.  It comes with a [web app](
https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/phoscon-app/?L=1).

**Comment by RGSMA** [comment]
I will give deCONZ gateway a shot. Thanks again for a fantastic plugin!

**Comment by fezzz** [comment]
Hi @ebaauw, I created a scene in deconz that includes a 10min transition for a lights-group. Starting it from there, it's exactly what I want. Is there a way to expose this scene to homebridge similar to the "groups"? I didn't figure out, yet, how to trigger it with a time-based rule from homekit.
Thanks, felix

**Comment by fezzz** [comment]
fyi. for a quick workaround I'm calling the api "curl -i -X PUT http://192.168.x.x/api/xxxxx/groups/5/scenes/1/recall" using the homebridge-script2 plugin

**Comment by ebaauw** [comment]
homebridge-hue doesn't expose bridge/gateway scenes to HomeKit.  As a workaround, I create a CLIPGenericFlag sensor, which homebridge-hue exposes as a _Switch_ to HomeKit.  On the bridge/gateway, I create a rule to recall the "on" scene when the flag is set and another one to recall the "off" scene when the flag is cleared.

To trigger timed transitions from HomeKit, include the custom _Transition Time_ characteristic in the HomeKit scene.  This is in the service homebridge-hue creates for the bridge/gateway.  Apple's Home app doesn't support this, so you need to create the scene in Eve or another HomeKit app.  After that, you can recall it alright from Apple's Home app.

I suppose I could try and expose scenes to HomeKit.  They would be mapped to _Switch_, which would revert automatically to _Off_ after the scene has been recalled (cf. the _Volume Change_ characteristic in homebridge-zp).  Currently, neither the Hue nor deCONZ API reports whether a scene is still active, and there's no way to un-recall a scene.

Note however, that every other Hue app tends to create a lot of scenes, so this could lead to a lot of switches.  I could try and expose the scenes as additional services to the group, to limit the number of accessories created, but then the scenes are bound to the same HomeKit room as the group.  This might work well for deCONZ, where scenes are created under a group, but not for Hue, where all scenes are stored under `/groups/0`.

**Comment by fezzz** [comment]
thank you for your detailed answer! Maybe a whitelist in the config section could only allow certain scenes to be exposed.
