### ISSUE TITLE
Homebridge not starting because resource and lights missing by mistake

### ISSUE THREAD

**Issue by brandungskieker** [ebaauw/homebridge-hue#376]
#### Issue

I did an update to Node.js v10.x and because of homebridge starting issues I rolled back to node.js v8.11.4. Now when I start homebridge I get a homebridge-hue error 

```
/resourcelinks/1: 6 lightlist entries
/resourcelinks/2: 2 outlet entries
/resourcelinks/2: /lights/5: not available
```

I tried `ph get -al /resourcelinks | grep /name:` with the result
```
/1/name:"homebridge-hue"
/2/name:"homebridge-hue"
/7/name:"opt_callNextScene"
/8/name:"opt_callPrevScene"
```
and `ph get -al /lights | grep /name:` and got

```
/1/name:"Deckenlampe"
/2/name:"Bold M"
/3/name:"Esstisch rechts"
/4/name:"Esstisch links"
/6/name:"Stereoanlage"
/7/name:"TV Lampe"
```
But: the list is complete - there is actually no device missing.
How can I rebuild/fix this list to get homebridge starting correctly?

**Comment by ebaauw** [comment]
Run `ph lightlist -v` (again).  That will update `/resourcelinks/1` with the available lights (1, 2, 3, 4, 6, 7).  Then run `ph outlet -v` (again) to update `/resourcelinks/2`.  If that doesn't select the right outlets, update them manually by:
```
ph put /resourcelinks/2 '{"links": ["/lights/...", "/lights/...", "/lights/..."]}'
```

With deCONZ 2.05.37, the lightlist won't be needed anymore, but that version is alpha-ish, see https://github.com/dresden-elektronik/deconz-rest-plugin/releases.
