### ISSUE TITLE
Enhancement: Let the bulbs blink

### ISSUE THREAD

**Issue by brandungskieker** [ebaauw/homebridge-hue#379]
I like to put this enhancement back to topic: In case of creating a DIY alarm system with HomeKit Support it's obvious to let a siren run and in addition to let some (all) lights blink.
I noticed #219, get this feature by triggering the "IDENTIFY" function. But this doesn't work for me in this case because I use RaspBee instead of the Hue Bridge. (Obviously Hue "misuse" the Identify-function to let the bulbs blink as well and as it's provided in an IFTTT applet).
I can't imagine there is no other way to realize blinking bulbs with RaspBee?

**Comment by ebaauw** [comment]
The CLIPGenericFlag and rule as described in #219 work the same for deCONZ and the Hue bridge; only `state.alert` works differently.  When setting `"alert": "select"` or `"alert": "lselect"`, the Hue bridge actually sends a ZigBee _Trigger Effect_ command for the _Breathe_ effect, followed by a _Trigger Effect_ command for _Stop_.  deCONZ sends a ZigBee _Identify_ command (which stops automatically) for these.

To send _Trigger Effect_ commands from deCONZ, set `state.alert` to `"blink"`, `"breathe"`, `"okay"`, `"channelchange"`, or `"finish"` for the corresponding effect, and to `"stop"` to end the effect.

Note that lights from different vendors react differently to _Trigger Effect_.  Some of the innr lights actually crash (requiring a power cycle to recover) when receiving _Breathe_ and _Stop_ within 2 seconds.  This is why homebridge-hue, when connected to deCONZ, sends `"breathe"` only to Hue lamps on (HomeKit) _Identify_.

**Comment by brandungskieker** [comment]
Thanks for this advices!
Sure, I can set this commands by API calls on command line (but didn't yet try it). But how can I integrate commands like this in a scene or rule of HomeKit to work with homebridge-hue?

**Comment by ebaauw** [comment]
See #219: Use a CLIPGenericFlag in the HomeKit scene to trigger the rules on deCONZ.

**Comment by brandungskieker** [comment]
Thank you, I played with the CLIPGenericFlag and it works. I think it's another way to let the lights blink for a pre-defined duration.
