### ISSUE TITLE
You may need to upgrade your installation of HomeBridge?

### ISSUE THREAD

**Issue by haudegen9** [ebaauw/homebridge-hue#38]
Hello, everything worked fine. Thank you!

Today i just wanted to include some lightify plugs, which are in hue. But now the dockers on my synology stopped. So i reinstalled the homebridge, but i always get this message:

Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.16 which does not satisfy the current HomeBridge version of 0.4.6. You may need to upgrade your installation of HomeBridge

**Comment by ebaauw** [comment]
I develop and test homebridge-hue against homebridge v0.4.16.  That doesn't necessarily mean homebridge-hue breaks on an older version of homebridge, but to be sure, I set the dependency to this version in package.json.

v0.4.16 is the latest version of homebridge on NPM.  When you install homebridge using `npm -g install homebridge` this version should be installed.

Are you running homebridge on a Synology in a Docker container?  Cool!  I have no experience with running homebridge in Docker, however, but maybe the Docker image needs to be updated to the latest homebridge version?

**Comment by haudegen9** [comment]
Thank you!

I will retry to install homebridge. 

I did it like this howto: https://github.com/marcoraddatz/homebridge-docker/blob/master/readme.md

Yes, it was working very fine on the ds415+.
With ur plugin i could see the temperature, lighting and so on in the home-app.

**Comment by haudegen9** [comment]
I’m sorry. Now it’s working again. Now i can change the colour in the home-app. Nice.
Thank you!

**Comment by ebaauw** [comment]
I'm happy it's working again - no need to be sorry.
