### ISSUE TITLE
Home app: 'not responding', OK in Hue app

### ISSUE THREAD

**Issue by Lorccan** [ebaauw/homebridge-hue#382]
#### Issue
The Home app is reporting (an Innr) lamp connected to Hue bridge as 'not responding'. However, it is not shown as 'unreachable' in the Hue app, so I am able to control it. 

#### Log Messages

```
 I can't see anything obvious in homebridge logs.
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2399011/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
homebridge-hue doesn't set nor clear the _Not responding_ state.  The Home app sets this when it doesn't receive a response from the HomeKit accessory (i.c. homebridge) when querying the state.  Afaik the only way to clear this state is to switch to another room (or switch from the Home tab to the Rooms tab) and back, forcing Home to refresh the state.

Since only one light shows _Not responding_, I think it's just a glitch.  If all your homebridge accessories show _Not responding_, there's usually an issue with your network not handling Bonjour well.

**Comment by Lorccan** [comment]
Thanks Erik. I think I’ve narrowed the problem to single lights (although different ones) in Home app-defined grouped accessories. I intend to plug the Homebridge server directly to my router to obviate network throughout issues (though I appreciate that’s not necessarily going to help flaky Bonjour).

Given that I’ve no need to control the grouped lights individually, and that I have never seen a case where _none_ of a group is unresponsive, I think I might be better doing the grouping at the Hue side.

**Comment by ebaauw** [comment]
> I think I might be better doing the grouping at the Hue side.

You can expose groups on the Hue bridge as HomeKit lights by setting `"groups": true` in config.json.  Alternatively, for finer-grained control, whitelist the group(s) you want to expose, and blacklist the member lights, see https://github.com/ebaauw/homebridge-hue#configuration.

Generally, it's a good idea to minimise the traffic between HomeKit and the Hue birdge (or deCONZ gateway).  I control my lights using Hue bridge (deCONZ gateway) rules recalling scenes and/or issuing group commands.  I use CLIPGenericFlag sensors (exposed to HomeKit as _Switch_) to trigger the rules from HomeKit, both manually and through HomeKit automations.

**Comment by Lorccan** [comment]
I'm getting there - slowly! May I just check something please: with the blacklist/whitelist setup, I notice that you say that homebridge-hue ignores the classid, so do I just put all my blacklisted lights into a single blacklist definition and all my groups into a single whitelist?

I initially stumbled because I think there's a new requirement to include `"recycle": true|false` in definition of **resourcelinks**.

Finally - to your last point about using the CLIPGenericFlag (exposed to HomeKit as _Switch_) - do you mean that you do not generally expose the group at all, but rely on a Hue rule acting on HomeKit turning the switch on|off?

**Comment by Lorccan** [comment]
Thank you Erik. I appreciate your help and patience!
