### ISSUE TITLE
Renaming of optional Power/Consumption services

### ISSUE THREAD

**Issue by flobernd** [ebaauw/homebridge-hue#385]
Hi there,

I just added an "innr 120" plug to my deCONZ bridge and exposed it to HomeKit by using your homebridge-hue plugin.

The plug works perfectly fine and even the power and consumption sensors are available in the Eve app. Sadly there seems no way to rename these sensors (or I did not found one at least). Would it be possible to derive their default names from the name of the corresponding outlet? E.g. if the outlets name is "My Plug", expose the sensor services as "My Plug Power" and "My Plug Consumption".

Best regards

**Comment by ebaauw** [comment]
homebridge-hue takes the service names from the `name` attribute of corresponding resources in deCONZ.  The accessory name is copied from the `lights` resource.  You can change these through the deCONZ REST API, e.g.
```
ph put /sensors/xxx '{"name": "New Name"}'
```

However, HomeKit only uses these names when the accessory is first exposed.  After that, a name change by the accessory (i.c. homebridge) is ignored and the names can only be changed from HomeKit apps.  Eve calls the service name _Siri Names_.  Normally, there's an entry for each service, but Eve somehow combines multiple services into one when the accessory has a history service.  Apple's Home app doesn't show custom services, so you cannot change the names there either.  You would need another HomeKit app, like Matthias' Home app (paid), or maybe Hesperus or HMCatalog (compile yourself).  
Alternatively, blacklist the plug, restart homebridge, change the names in deCONZ, unblacklist the plug and restart homebridge once again.

**Comment by flobernd** [comment]
Ahh I see, thanks for the explanation. Changing the name through the deCONZ REST API worked for me. The device already had the correct name assigned (did that during the pairing process in the Phoscon app), so that's not a problem.
