### ISSUE TITLE
How to delete a Hue-Bridge?

### ISSUE THREAD

**Issue by iGodPhil** [ebaauw/homebridge-hue#386]
I want to delete a Hue Bridge but how?

I have disconnected my original Bridge and deleted the user but get every time the following error:

[2018-10-20 22:58:59] [Hue] 192.***.***.81: bridge request 1: get /config
[2018-10-20 22:58:59] [Hue] 192.***.***.81: bridge communication error EHOSTUNREACH on 192.***.***.81

**Comment by ebaauw** [comment]
What’s your config.json?  Do you use automatic discovery of bridges/gateways?  After you power down the Hue bridge, it takes some time (half hour or longer?) before the meethue portal no longer reports it.

**Comment by iGodPhil** [comment]
The meethue portal was the problem. So we can close the issue but thanks for the information.
