### ISSUE TITLE
Dynamic heartrate

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#39]
As suggested by @dylanslewis (in issue #4), allow for changing the polling interval from HomeKit instead of from config.json.  Add a `StatefulProgrammableSwitch` service to the Homekit accessory for each bridge, mapping the heartrate to `Output State` and the time of the last sync to `Last Updated`. Could even use `Switch` and use `On` to turn off polling altogether.

Notes to self:
- Need to change setInterval() loop in HuePlatform.accessories() to fire every second and call HueBridge.heartbeat() with counter and check for counter % heartrate === 0 in each bridge.
- Need to change the handling of "get" events from HomeKit to issue ad hoc bridge state refresh when heartbeat is off.

**Comment by ebaauw** [comment]
Dynamic heartrate implemented in v0.1.8.

Disbabling heartrate not yet implemented, as handling of "get" events is more elaborate.

**Comment by dylanslewis** [comment]
Amazing, thank you!
