### ISSUE TITLE
IKEA on/off plug should not be dimmable

### ISSUE THREAD

**Issue by JanMisker** [ebaauw/homebridge-hue#391]
My setup is a RaspBee board with the latest deConz software.
I have the new IKEA on/off socket plug. I can discover it in the Phoscon app, and it is visible in homebridge-hue as a light. However, it reports as being dimmable. It doesn't seem to have an effect, but it looks a bit strange.
I also have an OSRAM on/off socket plug and that one is not reported as dimmable.

Can I override this somewhere?

```
$ ph get /lights
{
  "etag": "xx",
  "hascolor": false,
  "manufacturername": "OSRAM",
  "modelid": "Plug 01",
  "name": "Schakel Osram",
  "state": {
    "alert": "none",
    "on": true,
    "reachable": true
  },
  "swversion": "V1.04.12",
  "type": "On/Off plug-in unit",
  "uniqueid": "xx"
},
{
  "etag": "xx",
  "hascolor": false,
  "manufacturername": "IKEA of Sweden",
  "modelid": "TRADFRI control outlet",
  "name": "Schakel Ikea",
  "state": {
    "alert": "none",
    "bri": 46,
    "on": true,
    "reachable": true
  },
  "swversion": "1.4.020",
  "type": "On/Off plug-in unit",
  "uniqueid": "xx"
}
...
```

**Comment by ebaauw** [comment]
deCONz shouldn’t expose `state.bri` if it’s not dimmable.  It probably does so, because the plug exposes a _Level Control_ cluster (probably so it’ll react to _Move to Level with On/Off_ sent by the Ikea switches).

If you expose it as an _Outlet_ instead, it won’t be dimmable.  See 
https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0

**Comment by JanMisker** [comment]
I just noticed that deCONz also exposes sensors for those two plugs, and I did not yet have `"sensors":true` in config.json yet. I added that and now I see them both exposed as power outlets in homekit. Before they were exposed as lights.
