### ISSUE TITLE
No bridges found - retrying in 30 sec

### ISSUE THREAD

**Issue by llyons92** [ebaauw/homebridge-hue#398]
#### Issue

when i try to run homebridge the hue plugin continues to try to find the bridge. I made the mistake of trying to update homebridge and ran into issues but finally got it running again but the only plug in that wont work is hue. 
#### Log Messages

```
```
[11/19/2018, 3:33:20 PM] [Hue] no bridges found - retrying in 30 seconds
[11/19/2018, 3:33:50 PM] [Hue] searching bridges
[11/19/2018, 3:33:55 PM] [Hue] no bridges found - retrying in 30 seconds
[11/19/2018, 3:34:25 PM] [Hue] searching bridges
[11/19/2018, 3:34:30 PM] [Hue] no bridges found - retrying in 30 seconds
[11/19/2018, 3:35:00 PM] [Hue] searching bridges
[11/19/2018, 3:35:05 PM] [Hue] no bridges found - retrying in 30 seconds
[11/19/2018, 3:35:35 PM] [Hue] searching bridges
[11/19/2018, 3:35:40 PM] [Hue] no bridges found - retrying in 30 seconds
#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2596983/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
homebridge-hue cannot find your Hue bridge; the dump is from a previous homebridge session yesterday.  Did you verify that the Hue app can find the bridge?

You're running fairly old versions of NodeJS, homebridge, and homebridge-hue - updating seems like a good idea.  At least homebridge-hue-utils, so you can run `ph discover -v` to see whether the bridge is discovered.

**Comment by llyons92** [comment]
That's wierd. I thought updated all three of those things. What would be the process to update all three properly

**Comment by llyons92** [comment]
i did verify that the hue app can find the bridge

**Comment by llyons92** [comment]
I am running it on a mac. 

ph discover -v
{
  "deconz4": {},
  "deconz6": {},
  "meethue": {},
  "upnp": {}
}

this is what i get when i run discovery. 

I tried all the trouble shooting steps and get the same results. I am unsure as to where i should put the host part of the bridges ip address in the config.json

sorry I'm a very basic user when it comes to home bridge

**Comment by ebaauw** [comment]
Did you get it running?

**Comment by llyons92** [comment]
I did. Thank you for the help. 

Luke Lyons
