### ISSUE TITLE
press link button each time I restart

### ISSUE THREAD

**Issue by vllevsjm** [ebaauw/homebridge-hue#401]
#### Issue
Hello
Newbie here...

My Homebridge is set to start on boot up. However the plugin requests that I press the link button on my hue bridge each time to create a user. I'm I missing something. Is there a way to avoid this?

I'm using the default config.json example you provided.

tx
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2626194/homebridge-hue.json.gz)

#### Log Messages

```
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/2626228/homebridge.log.gz)
Philips hue: bridge request 2: post / ä"devicetype":"homebridge-hue#raspberrypi"å
Ä2018-11-28 13:53:31Å ÄHueÅ Philips hue: bridge error 101: link button not pressed
Ä2018-11-28 13:53:31Å ÄHueÅ Philips hue: press link button on the bridge to create a user

```

**Comment by vllevsjm** [comment]
Hello
Newbie here...

My Homebridge is set to start on boot up.  However the plugin requests that I press the link button on my hue bridge each time to create a user.  I'm I missing something.  Is there a way to avoid this?

I'm using the default config.json example you provided.

tx

**Comment by ebaauw** [comment]
After you pressed the link button and homebridge-hue created the API user, you need to edit config.json and enter the bridgeid and API user, as instructed in the log.  See https://github.com/ebaauw/homebridge-hue#installation.

**Comment by vllevsjm** [comment]
Thank you!  Got it!

I do have one last error during boot that does not seem to affect anything.

2018-11-28 16:16:34] [Hue] dresden appspot ipv6: communication error ENETUNREACH on https://dresden-light.appspot.com/

Anything I should do to correct this?

Thank you for your fantastic plugin!
LP

**Comment by ebaauw** [comment]
Homebridge-hue fails to query the deCONZ portal over IPv6, probably because you have no IPv6 Internet connectivity.  You can safely ignore this message.
