### ISSUE TITLE
convert lights to outlets 

### ISSUE THREAD

**Issue by Somberland** [ebaauw/homebridge-hue#402]
somehow I missed https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0 and now all my osram-outlets (via deconz) are shown as lightbulbs, not outlets. 
is there a way to readd them as outlet? `ph outlet -v` only outputs:
`ph outlet: /resourcelinks/49217: 0 outlets`

thanks for your great work and help :) 

phil

**Comment by ebaauw** [comment]
`ph outlet` should select the `/lights` resources with a `type` that doesn't end in `light`.  If memory serves, the OSRAM plugs have type `On/Off plug-in unit`, so I'm not sure what's happening.  Could you please attach the debug dump file homebridge-hue makes on startup?

Anyways, you can manually add them to the resourcelink:
```
ph put /resourcelinks/49217 '{"links: ["/lights/...", "/lights/..."]}'
```
Note that you have to specify all links in a single command, unfortunately there's no adding to the existing list (but you could use multiple resourcelinks).

**Comment by Somberland** [comment]
somehow missed to add the log-file. Sorry :) 

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2634731/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
As I thought: `On/Off plug-in unit`.  What version of ph are you running (`ph -V`)?

**Comment by Somberland** [comment]
Should be up 2date:

pi@Elriss:~ $ ph -V
1.1.0




homebridge@0.4.45
homebridge-hue@0.11.1
homebridge-info@1.2.0
homebridge-zp@0.2.34

**Comment by josefs15** [comment]
Hi. 
I have the same problem with the Osram Plug that shows as bulbs. 
Same versions how Somberland. 

Thanks forward for help.

**Comment by ebaauw** [comment]
@Somberland, I don't see anything weird in your dump file, except that no resourcelinks have been created.  Looking at the resourcelink id, 49217, are you sure `ph` runs against deCONZ.  Or do you still have a Hue bridge in your network?

@josefs15, please attach a dump file and the output of `ph outlet -v`.

Just paired one of my unused OSRAM plugs to my test deCONZ network.  `ph outlet` works as expected:
```
$ ph get /lights
{
  "1": {
    "etag": "ec6238e51df2b030046cba90471c1175",
    "hascolor": false,
    "manufacturername": "innr",
    "modelid": "SP 120",
    "name": "Smart Plug",
    "state": {
      "alert": "none",
      "bri": 254,
      "on": true,
      "reachable": true
    },
    "swversion": "2.0",
    "type": "On/Off plug-in unit",
    "uniqueid": "00:15:8d:00:02:17:ad:31-01"
  },
  "2": {
    "ctmax": 500,
    "ctmin": 153,
    "etag": "f538df666886be4729310b0b67844e1a",
    "hascolor": true,
    "manufacturername": "Philips",
    "modelid": "LCT003",
    "name": "Light 2",
    "state": {
      "alert": "none",
      "bri": 1,
      "colormode": "xy",
      "ct": 153,
      "effect": "none",
      "hue": 47104,
      "on": true,
      "reachable": false,
      "sat": 254,
      "xy": [
        1,
        1
      ]
    },
    "swversion": "5.127.1.26420",
    "type": "Extended color light",
    "uniqueid": "00:17:88:01:10:3c:9d:0a-0b"
  },
  "3": {
    "etag": "c3546d2172bef2c3b78b72f75e0bc572",
    "hascolor": false,
    "manufacturername": "OSRAM",
    "modelid": "Plug - LIGHTIFY",
    "name": "Light 3",
    "state": {
      "alert": "none",
      "on": false,
      "reachable": true
    },
    "swversion": null,
    "type": "On/Off plug-in unit",
    "uniqueid": "84:18:26:00:00:06:1d:ed-03"
  }
}
$ ph outlet -v
ph outlet: /resourcelinks/2: 2 outlets
$ ph get /resourcelinks/2
{
  "classid": 1,
  "description": "outlet",
  "links": [
    "/lights/1",
    "/lights/3"
  ],
  "name": "homebridge-hue",
  "owner": "0107043F97",
  "recycle": false,
  "type": "Link"
}
```

**Comment by ebaauw** [comment]
> Can you tell me how to add a dump file, please.

See https://github.com/ebaauw/homebridge-hue#debug-dump-file

> ph: error: localhost: not a Hue bridge nor deCONZ gateway

Are you running homebridge-hue against a Hue bridge or against deCONZ?  If a Hue bridge, you need to specify the bridge's IP address using `ph -H 192.168.x.x outlet -v` or by setting the `PH_HOST` environment variable.  You need to create a username (api key) by pressing the big button on the bridge and then issue `ph -H 192.168.x.x createuser`.

**Comment by josefs15** [comment]
It works now after restart of my Raspberry.
Thanks Erik for your help and your great job!
