### ISSUE TITLE
aqara sensor: air pressure not available

### ISSUE THREAD

**Issue by fezzz** [ebaauw/homebridge-hue#403]
#### Issue
Hi Eric, connecting the aqara sensor for temp/humidity/air pressure with conbee workes fine. All values are available in deconz. Connecting with homebridge-hue to homebridge shows 3 devices for 1 sensor where temp. and humidity are working great but the air-pressure is shown as "not supported". I guess the value mapping is wrong for this single value.
thanks,
Felix

### Debug:

[2018-12-1 11:06:11] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^10.13.0 which does not satisfy the current Node version of v11.2.0. You may need to upgrade your installation of Node.
[2018-12-1 11:06:13] Loaded plugin: homebridge-hue
[2018-12-1 11:06:13] Registering platform 'homebridge-hue.Hue'
(...)

### Config:

"platforms": [
   {
     "platform": "Hue",
     "users": {
     "*********": "123456789"
   },
  "sensors": true,
  "lights": true
 }
]

### Used Versions:
deconz: 2.05.49 / 29.11.2018 (same on 2.5.48)
conbee: 0x262f0500
homebridge: Version 0.4.45
homebridge-hue: v0.11.1
nodejs: v11.2.0

**Comment by ebaauw** [comment]
What HomeKit app are you using?

**Comment by ebaauw** [comment]
Apple's Home app doesn't support custom characteristics, and Apple haven't defined any standard for air pressure.  Nothing I can do to change that.  As you say, it works in Eve.  I don't know what you mean by the "homebridge webinterface".

**Comment by fezzz** [comment]
alright, thanks Eric - appreciate your plugin!
The webinterface I was talking about is homebridge-config-ui-x v3.9.0
air-pressure is not shown here.
![image](https://user-images.githubusercontent.com/6622789/49330152-2122fb00-f58b-11e8-9f8d-b9725ebf6863.png)

**Comment by ebaauw** [comment]
I’m afraid you have to take that up with homebridge-config-ui-x.  I need to expose the air pressure sensor as a separate service, to get history in Eve.

**Comment by udovic2100** [comment]
Any news on this topic? I just installed the mentioned aqara multi sensor and have the problem that air pressure is not displayed in homebridge and consequently not available in Apple HomeKit. Any chance to get the air pressure into HomeKit?

**Comment by ebaauw** [comment]
You'll have to ask Apple.  It's available in HomeKit alright, but the Home app doesn't support it.

**Comment by udovic2100** [comment]
Thanks for the clarification. You are right. With a different app (e.g. Eve) I can see the value.

**Comment by blasterbug** [comment]
Hello, 
I am not sure if it is fully linked to this issue but I don't see any of my sensors enter Home or the Eve app. 
For instance, the Aqara temperature and humidity sensor is correctly linked with the RaspBee, I can see all values under the Phoscon App, I have added the plugin to Homebridge, but even there none of the sensors is displayed. 

This is how it looks under the config.json file:
```JSON
{
            "name": "Raspbee II",
            "anyOn": true,
            "effects": true,
            "excludeSensorTypes": [
                "ZLLLightLevel",
                "ZLLTemperature",
                "ZHAHumidity",
                "ZHAPressure",
                "Daylight"
            ],
            "hosts": [
                "localhost:4530"
            ],
            "lights": true,
            "resource": true,
            "users": {
                "XYZ": "ABC"
            },
            "platform": "Hue"
        }
```
