### ISSUE TITLE
Node version problem

### ISSUE THREAD

**Issue by JacVid** [ebaauw/homebridge-hue#405]
#### Issue

Hello, i'm totally new in programing and i've just installed Homebridge, and you would like to thank you for the plugin which helps me a lot.

But with your plugin, it seems the node version is not up to date. Is it an issue on my side regarding my Hue gateway ?

Thanks for your help.

#### Log Messages

```
[Hue] Initializing Hue platform...
[Hue] homebridge-hue v0.11.1, node v10.14.1, homebridge v0.4.45
[Hue] warning: not using recommended node version v10.13.0 LTS
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2660419/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
The latest release of homebridge-hue was developed and tested under NodeJS v10.13.0.  I try and follow the LTS releases, but I haven't had time yet to upgrade to 10.14.1.  I'm busy firmware upgrading my Hue lights for the new power-on settings ;-).

I've haven't seen many issues when upgrading NodeJS to a new minor version, so homebridge-hue might just work with 10.14.1.

**Comment by JacVid** [comment]
Thanks for the update :)

**Comment by JacVid** [comment]
#### Issue
Hello, 

it seems the node version is not anymore up to date.

Thanks for your help.

#### Log Messages
[1/6/2019, 9:59:19 AM] [Hue] homebridge-hue v0.11.6, node v10.14.1, homebridge v0.4.45
[1/6/2019, 9:59:19 AM] [Hue] warning: not using recommended node version v10.15.0 LTS

**Comment by ebaauw** [comment]
Again, I develop and test against the latest LTS version of node.  Other versions might or might not work.  Also note that each NodeJS release contains security updates, so you might want to keep it up to date.

**Comment by JacVid** [comment]
Ok, so you mean that my system is not up to date, right ? As I said, I'm new in using raspberry Pi and HomeBridge, so I'm really sorry bothering you...

**Comment by ebaauw** [comment]
If you installed NodeJS using the Debian package (as described in the README), issuing
```
sudo apt update
sudo apt upgrade
```
will keep NodeJS up to date (together with the Raspbian software).

See https://github.com/nodesource/distributions/blob/master/README.md

**Comment by JacVid** [comment]
Hello,
I've updated the whole Homebridge package (I didn't find the way to just update the nodejs file inside HomeBridge) and now no more issues in the logs.

Thanks for your help :)
