### ISSUE TITLE
Xiaomi Aqara wall switch not shown as switch/timeouts

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#407]
I got added a light to PHOSCON app via conbee stick.
It was working for hours.

But now I got the following error after a period:
```
[2018-12-10 16:47:05] [ConbeeStick] ConbeeStick: gateway error 3: resource, /lights/3, not available
[2018-12-10 16:47:05] [ConbeeStick] Schlafzimmer Fluter: homekit on changed from 0 to 1
```

Hardware switch and PHOSCON app are still working, only homebridge shows this error.

And the switch is not shown as real switch like the original hue one, only as unknown device.
Will there we an update in future?

**Comment by ebaauw** [comment]
Could you please attach the debug dump file, see 
https://github.com/ebaauw/homebridge-hue#debug-dump-file and a debug logfile, see 
https://github.com/ebaauw/homebridge-hue#debug-log-file

**Comment by Phoenix-DH** [comment]
I reconfigured everything yesterday evening.
Since then I hab not have this issue with the n/a problem.

Do you also need those dump and log file for supporting this new switches?

**Comment by ebaauw** [comment]
The dump file or a listing of the resource.

**Comment by Phoenix-DH** [comment]
Okay, will try to deliver this afternoon or tomorrow ....

If somebody has time in front and the values available, those are the new switches I think:
WXKG02LM
WXKG03LM

**Comment by Phoenix-DH** [comment]
Is this what you need?

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2669104/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
That's a dump from homebridge-hue working on a Hue bridge (hue Küche).  I need the one where homebridge-hue connects to deCONZ.

**Comment by Phoenix-DH** [comment]
Damn ... where can I find the other one?
Searched for the same file through file system ... nothing found ....

My config looks like ...
```
...
        {
            "platform": "Hue",
            "name": "HueBridge",
            "host": "192.XXXXXX.XXX",
            "users": {
                "XXX": "XXX"
            },
            "lights": true
        },
        {
            "platform": "Hue",
            "name": "ConbeeStick",
            "host": "192.XXX.XXX.XXX",
            "users": {
                "XXX": "XXX"
            },
            "sensors": true,
            "lights": true,
            "excludeSensorTypes": [
                "Daylight",
                "ZHASwitch",
                "CLIPGenericFlag"
            ]
        },
...
```

Got 2 blocks in this order ...

**Comment by ebaauw** [comment]
Ok, apparently, the deCONZ starts first and then the dump is overwritten by the Hue.  You should be able to see this in the homebridge log.

This config is not supported and will not be working once I'll have moved to dynamic platform accessories.  Better use one homebridge-hue and specify `"hosts": ["192.x.x.x", "192.x.x.y"]`.  Also make sure to include both bridgeids/usernames in the `"users"` object.  By default, homebridge-hue won't expose the Philips lights and sensors on a v2 Hue bridge, but you might want to exclude all CLIP sensors to suppress those made by Hue routines.  Just use `"CLIP"` instead of `"CLIPGenericFlag"`.

If you really need to different configurations, you'll need to run two instances of homebridge.

**Comment by Phoenix-DH** [comment]
Did get it managed, just added the GEOFENCE too ...
Now everything looks like before .... with 2 sets ...

Attached the new file:
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2669354/homebridge-hue.json.gz)

Hopefully now correct.

**Comment by ebaauw** [comment]
Yeah, config looks good.  And I found one `lumi.remote.b286acn01`.  I'll see if I can find the possible `buttonevent` values from the deCONZ source code.  It's probably going to be this weekend, before I'll have time to make the changes.

**Comment by Phoenix-DH** [comment]
Finally :)

Great... thank you!

**Comment by ebaauw** [comment]
This is the two-button switch, which reacts to left button, right button and both buttons?

**Comment by Phoenix-DH** [comment]
It should be this one:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG02LM-2018

But I read somewhere in this thread here that there might also be hold actions ...
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/811#issuecomment-444621287

But here that they might not work:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/811#issuecomment-445032064

Thank you.

**Comment by ebaauw** [comment]
Could you run `dc_eventlog -s` | grep /sensors/18` and press/release (single press), press/hold/release (long press), press/release/press/release (double press) the left button, the right button, both buttons, and notice the `buttonevent` values?

**Comment by Phoenix-DH** [comment]
Sure, I did. I receivbed the following values without getting connection lost because I resetted the switch :)

Left button:
Single: 1002
Double: 1004
Long: 1001

Right button:
Single: 2002
Double: 2004
Long: 2001

Both:
Single: 3002
Double: 3004
Long: 3001

Need something more?

**Comment by Phoenix-DH** [comment]
x001 is fired while holding the button ...
Means when I start holding the button x001 is fired, then nothing more happens when releasing ...

That would be exactly what I read ... So I think this action can not be used, right?
But Single press? That would be okay for me ...
Because then I can use this switch also for other actions within Homekit, would be fine ...

Thank you.

**Comment by manup** [comment]
Yes I'm afraid the switch isn't meant to be used for long press albeit the `hold` is transmitted together with a basic cluster report, no release is sent and after 8 seconds the show is over.

I'll see to get a Xiaomi gateway in the next weeks to check what they are doing with this switch, maybe it could be configured somehow.

**Comment by Phoenix-DH** [comment]
Would be great, I want not to have an additional bridge.
That was the case for the Conbee Stick decision.

Like I said, starting with 3 actions would also be fine.
It ius the same implemented in PHOSCON.

**Comment by ebaauw** [comment]
> Yes I'm afraid the switch isn't meant to be used for long press

Actually, I think it is.  Xiaomi now natively support HomeKit with their latest Aqara hub and devices.  They advertise HomeKit support for _Single Press_, _Double Press_, and _Long Press_.

I would just issue an x003 on the hold report, instead of a x001, but I'm not sure how that would effect the wireless switch `lumi.remote.b1acn01`.   I'm assuming that switch _does_ issue the 255 value?

**Comment by ebaauw** [comment]
Switches should be supported in v0.11.2, see https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.2.

**Comment by Phoenix-DH** [comment]
Great, thank you, I will try!

**Comment by Phoenix-DH** [comment]
Visible! Great....
Will configure it and do some tests.

**Comment by Phoenix-DH** [comment]
Everything great! Thank you!
All button combinations I use are woeking, also double and long press.
