### ISSUE TITLE
Hue Motion sensor does not gather history data

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#408]
Hi again,

I tried yesterday to implement the hue motion sensor history data to the eve app.
Therefore I added the following to my config:
`hueMotionTemperatureHistory: true`

My whole config looks like:
```
{
"platform": "Hue",
"hosts": [
XXX
XXX
],
"users": {
XXX
},
"sensors": true,
"hueMotionTemperatureHistory": true,
"lights": true,
"excludeSensorTypes": [
"Daylight",
"ZHASwitch",
"CLIP",
"Geofence"
]
},
```
​
Are there any additional switches needed?

In the accessories folder there has been no file created with the ID of the temperature sensor.

**Comment by ebaauw** [comment]
Do you see the history for the motion sensor?  You should already get that without any changes to config.json.

**Comment by Phoenix-DH** [comment]
No, I think it is not visible .... I looks in eve like the following:
![img_3229](https://user-images.githubusercontent.com/44058592/49923126-d40c2680-feb2-11e8-9bca-dfe16055c71a.PNG)

**Comment by ebaauw** [comment]
Looks like you’re exposing the motion sensor from the Hue bridge, not from homebridge-hue.

**Comment by Phoenix-DH** [comment]
... how can I change that? Do I only have to add this:
`"nativeHomeKitSensors: " false`
Or any other config missing... mine is attached at the top of the thread.

I can inagine that if I change this, I will have the sensors twice, right? One out of the plugin and one out of the hue app directly... Is that right? If yes, how can I delete the wrong one?

**Comment by ebaauw** [comment]
Yes, the nativeHomeKitSensors should donthe trick.  Afaik, there’s no way to select what to expose to HomeKit by the Hue bridge - it’s all or nothing.

**Comment by Phoenix-DH** [comment]
Hm, thank you.
I will think about if I will change this and have the sensors twice.

**Comment by Phoenix-DH** [comment]
I implemented the sensor. Now I got some things twice. I moved them into a special room.
But what I have to check at home...
What will happen with the switches with the different settings.
Because now one is configured and one is unconfigured ....

**Comment by Phoenix-DH** [comment]
That was exactly was I am thinking about ... got deconz in use already...

**Comment by Phoenix-DH** [comment]
One last thing I figured out:
Exposed by hue the daylight is now 1lux, exposed by homebridge-hue it is 0,0001lux.

Can this be adapted?

**Comment by ebaauw** [comment]
I don't think the Hue bridge exposes the Daylight sensor?  You're probably seeing two Daylight sensors exposed by homebridge-hue, one for deCONZ and one for the Hue bridge.  They both report 0.0001 lux at night, but deCONZ has more phases than the Hue bridge (which only supports daylight on or off).  You can use the `config.sunriseoffset` and `config.sunsetoffset` to tune the Hue bridge sensor, but I would probably just blacklist it, so it won't be exposed by homebridge-hue.

**Comment by Phoenix-DH** [comment]
No, the one with the resl value was available all the time, also when I got no deconz or non-native sensors installed. The one from deconz I removed. Will have a view at day how the value looks like. If it is normal then it is okay.

Blacklist the sensor where?

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue#configuration
