### ISSUE TITLE
Powered up hue bridge, now homebridge-hue is looking for it

### ISSUE THREAD

**Issue by iantait** [ebaauw/homebridge-hue#409]
So I powered up my hue bridge, and then turned it off again - now homebridge won't start because it (homebridge-hue) is looking for the hue bridge.

How do I make that not happen? 

Its not referred to in config.json btw, and I have rebooted the homebridge machine.

Ta,
Ian

**Comment by iantait** [comment]
OK, so I waited a long time (~2 hours) till ph discover didn't show the hue bridge, restarted homebridge.
All good. Not sitting in the dark anymore :-)

**Comment by ebaauw** [comment]
It takes a while before the registration of the Hue bridge with the meethue portal expires, and the bridge is no longer discovered.  To disable discovery, specify `host` or `hosts`  in config.json to provide the IP address of your bridge(s).
