### ISSUE TITLE
OSRAM outlet

### ISSUE THREAD

**Issue by rgerr** [ebaauw/homebridge-hue#410]
Is it possible for a OSRAM smart plug to be directy used as ‘valve’ instead of ‘outlet’ via ph -H [ip] valve -v ?

**Comment by rgerr** [comment]
I have magnetic valves plugged in, so when the plug turns on, the valve opens and waters the garden. Therefor it would be neat to have the plug exposed as a valve to HomeKit.

**Comment by JacVid** [comment]
Hello,

i'm new using Homebridge, and with your plugin, i'd like to know what to be changed to switch my Osram Plugs into Outlet instead of Lightbulb ?

Thanks

**Comment by ebaauw** [comment]
I haven't included this in the Wiki yet, but It's described in the release notes for v0.10.0: https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0.

**Comment by JacVid** [comment]
Thanks for this link, but I'm not able to do "ph outlet -v". 

it repIies : "-bash: ph : commande introuvable" (its in french sorry)

**Comment by ebaauw** [comment]
Depending on how you installed NodeJS, it should install to `/usr/bin` or `/usr/local/bin` when installing homebridge-hue.  This is the same directory where the `homebridge` executable is installed.  Make sure this directory is in your PATH.

**Comment by JacVid** [comment]
I've followed this link to install Homebridge from step 1. 

![image](https://user-images.githubusercontent.com/45730690/50739707-39b6ae80-11e4-11e9-8f93-1beba5191b69.png)

so homebridge is then installed there : usr/home/pi/homebridge/

I've had this : "export PATH=$PATH:/usr/home/pi/homebridge"

But "ph outlet -v" still doesn't work

**Comment by ebaauw** [comment]
When installing using `sudo npm -g i homebridge-hue`, `npm` creates symlinks in `/usr/bin` or `/usr/local/bin` to `cli/ph.js` of homebridge-hue-utils.  I don't know what the Docker installation looks like.  Maybe you can create a symlink manually.  Also make sure to `chmod 755 cli/ph.js`.
```
$ ll /usr/bin/ph
lrwxrwxrwx 1 root root 78 Dec 28 20:30 /usr/bin/ph -> ../lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/cli/ph.js
```

**Comment by julien94800** [comment]
Hello,

I am not able to define the OSRAM outlet as an outlet. It stays as a lamp. 
I tried this command (ph -H 192.168.0.94 outlet -v) but I get the following message:
ph outlet: error: 1 unauthorized user
Is there a way to manually do it by creating the resourcelink file? If yes, where do I have to put it?

Thanks in advance

**Comment by ebaauw** [comment]
The resourcelink is not a file, but a resource on the deCONZ, created and updated through the REST API.  To interact with the REST API, you need a valid username (API key).  To create one for `ph`, unlock deCONZ for new applications and then run `ph -H 192.168.0.94 createuser`.

**Comment by julien94800** [comment]
Hello,
Thanks for your quick answer. Unfortunately, I do not have a deCONZ. Only the hue bridge.
Does it means that I do not have anyway to set the device as an outlet?

**Comment by ebaauw** [comment]
Sorry, then press the big link button on the Hue bridge before running `ph -H 192.168.0.94 createuser`.

**Comment by rgerr** [comment]
Have you looked in to perhaps changing the ‘outlet’ exposure to HomeKit to different types, like ‘valve’, as I suggested?

**Comment by ebaauw** [comment]
> Even if for me it is strange due to the fact I do not understand how you find what must be an outlet and what must stay as a lamp when setting outlet -v

The issue is that you don't. `ph outlet` creates an `outlet` resourcelink, containing the `lights` resources with a type that doesn't end in "light".  For the OSRAM plug this works, but for plugs or wired switches that report the wrong type, for groups, for other devices it doesn't.  The resourcelink allows you to correct that manually.  And it allows you to indicate that a plug connected to a light should be exposed as a light.

**Comment by julien94800** [comment]
Thanks for the explanation, and thanks again for your support

**Comment by ebaauw** [comment]
> Would you mind giving me a heads up if there is any news on this to report?

@rgerr, In [v0.11.7](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.7).  You'll need to create a resourcelink to list the `/lights` resources to be exposed as value by:
```
ph post /resourcelinks '{
  "name": "homebridge-hue",
  "description": "valve",
  "classid": 1,
  "links": [
    "/lights/12",
    "/lights/34"
  ]
}'

**Comment by rgerr** [comment]
That would make all outlets be exposed as valves, if I’m correct?

**Comment by ebaauw** [comment]
No, just the ones listed in the resourcelink, in this example `/lights/12` and `/lights/34`.

**Comment by rgerr** [comment]
That sounds great. How to implement this? In the config and in terminal?

**Comment by ebaauw** [comment]
It's a command you enter at the command line (just like `ph outlet`).

**Comment by rgerr** [comment]
So I use  ph -H ip outlet -v or  ph -H ip valve -v?

**Comment by ebaauw** [comment]
There’s no `ph valve` as there’s no way to know which resources to expose as valve.  So use

`ph -H ` _ip_ `post /resourcelinks ‘{ ` _body_ `}`

With the body mentioned above, listing the `/lights` resources to expose as valves under the `”links”`.

**Comment by rgerr** [comment]
I’m haring trouble implementing this. What do I put in the terminal and what do I put in the config file?

**Comment by ebaauw** [comment]
In config: nothing; in the terminal (replacing the `x`s with the correct values):
```
ph -H x.x.x.x post /resourcelinks '{
  "name": "homebridge-hue",
  "description": "valve",
  "classid": 1,
  "links": [
    "/lights/xx",
    "/lights/xx"
  ]
}'
```

**Comment by rgerr** [comment]
Great, got the valves in the Home app! Many thanks for that. Will it also be possible to set different valves, instead of the default valve? For instance, sprinkler?

**Comment by rgerr** [comment]
Something I havent taken into account, the valve cannot be used in timed automations. So could you perhaps change/add the sprinkler function?

**Comment by ebaauw** [comment]
The valve type is hard-coded, but feel free to try and change it yourself.
https://github.com/ebaauw/homebridge-hue/blob/95654927241c24a10fbe141afcd810d79dde9bb5/lib/HueLight.js#L433-L434

As far as I can tell, nothing changes with a different valve type, except the symbol displayed in the Home app.

**Comment by rgerr** [comment]
No, with a sprinkler you can set a timer. So you can turn it on for a (default) time. I’m not sure what to look for in the code you linked, but is it possible to create the valve-sprinkler?

**Comment by ebaauw** [comment]
>  is it possible to create the valve-sprinkler?

Yes, change the line I mentioned above to `ValveType.IRRIGATION`.  As I mentioned before,  the only thing that changes is the symbol.

> No, with a sprinkler you can set a timer.  So you can turn it on for a (default) time. And use it in automation.

Can you please provide screenshots of what you mean?

**Comment by ebaauw** [comment]
> Where exactly is the mentioned file?

Depends on how you installed NodeJS and homebridge-hue.  It's in the `lib` directory under the main `homebridge-hue` directory.  When installed using `npm -g`, it's typically `/usr/lib/node_modules/homebridge-hue/lib/HueLight.js` or `/usr/local/lib/node_modules/homebridge-hue/lib/HueLight.js`

> e.g. homebridge-gpio-valve

Looking at that code, the only "automation" they provide is an auto-close after a certain amount of time, specified by the optional _SetDuration_ characteristic.  No schedules, no automatic opening the valve.  They also provide the optional _Remaining Duration_ characteristic, but this is not persisted.  The auto-close will not happen if homebridge is restarted while the valve is open.

This has nothing to do with the valve type - it's additional optional functionality for all valve types.  I could probably add it to homebridge-hue.  However, with the current design of homebridge-hue, _SetDuration_ and _Remaining Duration_ would be reset to the default across on each homebridge restart.  And, as with the gpio-valve plugin, the auto-close will not happen if homebridge is restarted while the valve is open.

I do think this functionality would better (more robustly), albeit less user friendly, be implemented on the Hue bridge instead.  A rule on the Hue bridge can turn `state.on` to false, a specified amount of time after it was turned on.

**Comment by ebaauw** [comment]
Could you try v0.11.10-0?  It adds the _Set Duration_ and _Remaining Duration_ characteristics to the _Valve_ service.  Install using `sudo npm -g i homebridge-hue@beta`.

**Comment by rgerr** [comment]
Strange, with the homebridge-gpio-valve plug-in (as a dummy) I could use it in automations. Now I cannot.

**Comment by ebaauw** [comment]
What did you do in automations?  Screenshot?

**Comment by rgerr** [comment]
Exactly, so in Apple’s native app, it is not supported to control the valve type in automation. Luckily, in some third party apps, it is. :)

**Comment by ebaauw** [comment]
v0.11.10 is out; I retired the beta.

**Comment by rgerr** [comment]
For future reference for other users: with the 0.11.10 update you can also change default valve to e.g. irrigation, by changing line 434 from ‘   .updateValue(Characteristic.ValveType.GENERIC_VALVE)’ to ‘   .updateValue(Characteristic.ValveType.IRRIGATION)’ in the /usr/lib/node_modules/homebridge-hue/lib/HueLight.js file.
