### ISSUE TITLE
Gledopto problem

### ISSUE THREAD

**Issue by netRunner0** [ebaauw/homebridge-hue#416]
It does not work smoothly on and off for gledopto. Previously worked without problems. Perhaps this is due to the recent update of the plugin or SW HueHub?

**Comment by ebaauw** [comment]
I haven't changed anything in that area.  It's not impossible that new Hue bridge firmware changed something there, but I haven't noticed that myself.  I only use the Hue bridge these days to upgrade the firmware of my Hue lights.

You might want to experiment by using different `transitiontime` values while setting the GLEDOPTO's `state.on` and observe the light:
```
ph put /lights/xx/state '{"on": true}'
ph put /lights/xx/state '{"on": false}'
ph put /lights/xx/state '{"on": true, "transitiontime": 0}'
ph put /lights/xx/state '{"on": false, "transitiontime": 0}'
ph put /lights/xx/state '{"on": true, "transitiontime": 4}'
ph put /lights/xx/state '{"on": false, "transitiontime": 4}'
ph put /lights/xx/state '{"on": true, "transitiontime": 40}'
ph put /lights/xx/state '{"on": false, "transitiontime": 40}'
```
The Hue bridge (used to?) insert(s) a default `transitiontime` of `4` (0.4 seconds) with each command, so the light should show the same behaviour for the commands without the `transitiontime` and with a `transitiontime` of `4`.  I'm guessing it now behaves as for a `transitiontime` of `0`?

If you're able to sniff the ZigBee traffic, the Hue bridge used to send an _On_ of _Off_ command when `transitiontime` of `0` is specified, and a _Move to Level with On/Off_ when another `transitiontime` is specified (including the default `4`).

**Comment by netRunner0** [comment]
I have 2 bridges hue and raspberry. Where do I need to enter the command?

**Comment by honk95** [comment]
> In a terminal windows on the Raspberry. You need to set `PH_HOST` os use `ph -H` to specify the ip address of the Hue bridge (where the GLEDOPTO is connected to). You need to create a username (API key) by pressing the link button on the bridge and issuing:
> 
> ```
> ph -H x.x.x.x createuser
> ```

Is there a possibility to use the `ph` commands in a docker container?
Need this to get my osram plugs as outlets instead of lights. Or is there another workaround?

**Comment by ebaauw** [comment]
> Is there a possibility to use the `ph` commands in a docker container?

You should be able to run it on any system that supports NodeJS.  Normally it's installed with homebridge-hue, but if you want to use it on a machine not running homebridge, you can install it separately:
```
sudo npm -g i homebridge-hue-utils
```
