### ISSUE TITLE
Question: Displaying sensor reachability?

### ISSUE THREAD

**Issue by dergreg** [ebaauw/homebridge-hue#417]
Hi,

I just put one of my Xiaomi temperature sensors into the garage (to check for the perfect beer temperature 😂). I still displays 20 degrees, which is obviously too much for winter (a zwave based Sensor next to it correctly displays 8 degrees).

Is there any chance to detect the last update of the device (which is now older than two hours) and display the device as „not responding“ in HomeKit?

Regards
Greg

**Comment by Larsn1** [comment]
Hello Greg,

there is the possibility to determine when the device is reachable or when it has been seen the last time in the free Eve App.

Best regards 
Lars

**Comment by ebaauw** [comment]
I set _Status Fault_ to 1 when a sensor’s `config.reachable` or a light’s `state.reachable` becomes false.  Apple’s Home app seems to ignore it, even though it’s a standard HomeKit characteristic.  Eve shows this as a red warning sign.

A sensor’s `state.lastupdated` is exposed as a custom _Last Updated_ characteristic, which Apple’s Home app doesn’t support.

I don’t set accessories to _Not Responding_, as that causes Apple’s Home app to ignore updates to the accessory.  When I unset _Not Responding_, Apple’s Home app continues to show it, until you refresh the accessory, forcing Home to re-read the characteristics.  During that time, you cannot control the device.

**Comment by dergreg** [comment]
Where is the reachable flag displayed? See my screenshots from the eve app, thanks

**Comment by ebaauw** [comment]
It’s a red triangle with an exclamation mark.  It only shows when it’s set.  In the details screen, it’s on the top bar (next to the battery symbol and the settings gear), on the room screen, it’s to the left of the value.

Note that homebridge-hue depends on deCONZ to report `config.reachable` and that deCONZ depends on the Xioami device to report it’s state.  The battery-powered Xiaomi sensors are very sleepy and cannot be queries by deCONZ.  The Aqara devices report once every hour and when “significant” changes happen.  I’m not sure when deCONZ sets the sensor’s`config.reachable` to false.

**Comment by dergreg** [comment]
Yeah I know the exclamation mark from my Eve thermo (unfortunately), but not from the Aqara sensors so far. I guess this isn't set by deconz.
