### ISSUE TITLE
Newest Version not running on Synology Docker

### ISSUE THREAD

**Issue by henkhb** [ebaauw/homebridge-hue#419]
Hey,

after updating and clean reinstall I always run into this error,
that prevents Homebridge from starting:

[12/28/2018, 1:44:30 PM] [Hue] TypeError: homebridgeLib.UpnpMonitor is not a constructor
    at Promise (/homebridge/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/HueDiscovery.js:66:27)
    at new Promise (<anonymous>)
    at HueDiscovery._upnp (/homebridge/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/HueDiscovery.js:65:12)
    at HueDiscovery.discover (/homebridge/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/HueDiscovery.js:42:12)
    at HuePlatform.findBridges (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:424:21)
    at request.then.catch.then (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:265:17)
    at Function.then (/homebridge/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/homebridge/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/homebridge/node_modules/deferred/deferred.js:142:15)
    at Function.<anonymous> (/homebridge/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/homebridge/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/homebridge/node_modules/deferred/deferred.js:142:15)
    at Function.then (/homebridge/node_modules/deferred/_ext.js:72:4)
    at Deferred._settle (/homebridge/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/homebridge/node_modules/deferred/deferred.js:142:15)
    at Request.request [as _callback] (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:469:14)
    at Request.self.callback (/homebridge/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)

**Comment by ebaauw** [comment]
I had some arguments with `npm`, but I thought I fixed them in homebridge-hue@0.11.5.
Could you please list the output of:
```
sudo npm -g list --depth=1
```

**Comment by henkhb** [comment]
First, thanks for your great work! I switched back to the former version, but hope this output still helps:

/usr/local/lib
+-- homebridge@0.4.45
| +-- chalk@1.1.3
| +-- commander@2.8.1
| +-- hap-nodejs@0.4.47
| +-- node-persist@0.0.8
| +-- qrcode-terminal@0.11.0
| `-- semver@5.0.3
+-- homebridge-config-ui-x@3.9.2
| +-- @oznu/hap-client@0.0.3
| +-- bash-color@0.0.4
| +-- bluebird@3.5.3
| +-- body-parser@1.18.3
| +-- buffer-shims@1.0.0
| +-- commander@2.19.0
| +-- cors@2.8.5
| +-- dotenv@6.2.0
| +-- express@4.16.4
| +-- fs-extra@7.0.1
| +-- helmet@3.15.0
| +-- jsonwebtoken@8.4.0
| +-- lodash@4.17.11
| +-- node-pty@0.7.8
| +-- passport@0.4.0
| +-- passport-http@0.3.0
| +-- qr-image@3.2.0
| +-- request@2.88.0
| +-- request-promise@4.2.2
| +-- semver@5.6.0
| +-- source-map-support@0.5.9
| `-- ws@6.1.2
+-- homebridge-tado-platform@4.5.4 (git+https://git@github.com/mylesgray/homebridge-tado-platform.git#6b0f7baf7f62f3cf5c6e5725667b0698d81eafc6)
| +-- async@2.6.0
| +-- fakegato-history@0.5.3
| +-- moment@2.23.0
| `-- node-persist@0.0.8
`-- npm@6.4.1
  +-- abbrev@1.1.1
  +-- ansicolors@0.3.2
  +-- ansistyles@0.1.3
  +-- aproba@1.2.0
  +-- archy@1.0.0
  +-- bin-links@1.1.2
  +-- bluebird@3.5.1
  +-- byte-size@4.0.3
  +-- cacache@11.2.0
  +-- call-limit@1.1.0
  +-- chownr@1.0.1
  +-- ci-info@1.4.0
  +-- cli-columns@3.1.2
  +-- cli-table3@0.5.0
  +-- cmd-shim@2.0.2
  +-- columnify@1.5.4
  +-- config-chain@1.1.11
  +-- debuglog@1.0.1
  +-- detect-indent@5.0.0
  +-- detect-newline@2.1.0
  +-- dezalgo@1.0.3
  +-- editor@1.0.0
  +-- figgy-pudding@3.4.1
  +-- find-npm-prefix@1.0.2
  +-- fs-vacuum@1.2.10
  +-- fs-write-stream-atomic@1.0.10
  +-- gentle-fs@2.0.1
  +-- glob@7.1.2
  +-- graceful-fs@4.1.11
  +-- has-unicode@2.0.1
  +-- hosted-git-info@2.7.1
  +-- iferr@1.0.2
  +-- imurmurhash@0.1.4
  +-- inflight@1.0.6
  +-- inherits@2.0.3
  +-- ini@1.3.5
  +-- init-package-json@1.10.3
  +-- is-cidr@2.0.6
  +-- json-parse-better-errors@1.0.2
  +-- JSONStream@1.3.4
  +-- lazy-property@1.0.0
  +-- libcipm@2.0.2
  +-- libnpmhook@4.0.1
  +-- libnpx@10.2.0
  +-- lock-verify@2.0.2
  +-- lockfile@1.0.4
  +-- lodash._baseindexof@3.1.0
  +-- lodash._baseuniq@4.6.0
  +-- lodash._bindcallback@3.0.1
  +-- lodash._cacheindexof@3.0.2
  +-- lodash._createcache@3.1.2
  +-- lodash._getnative@3.9.1
  +-- lodash.clonedeep@4.5.0
  +-- lodash.restparam@3.6.1
  +-- lodash.union@4.6.0
  +-- lodash.uniq@4.5.0
  +-- lodash.without@4.4.0
  +-- lru-cache@4.1.3
  +-- meant@1.0.1
  +-- mississippi@3.0.0
  +-- mkdirp@0.5.1
  +-- move-concurrently@1.0.1
  +-- node-gyp@3.8.0
  +-- nopt@4.0.1
  +-- normalize-package-data@2.4.0
  +-- npm-audit-report@1.3.1
  +-- npm-cache-filename@1.0.2
  +-- npm-install-checks@3.0.0
  +-- npm-lifecycle@2.1.0
  +-- npm-package-arg@6.1.0
  +-- npm-packlist@1.1.11
  +-- npm-pick-manifest@2.1.0
  +-- npm-profile@3.0.2
  +-- npm-registry-client@8.6.0
  +-- npm-registry-fetch@1.1.0
  +-- npm-user-validate@1.0.0
  +-- npmlog@4.1.2
  +-- once@1.4.0
  +-- opener@1.5.0
  +-- osenv@0.1.5
  +-- pacote@8.1.6
  +-- path-is-inside@1.0.2
  +-- promise-inflight@1.0.1
  +-- qrcode-terminal@0.12.0
  +-- query-string@6.1.0
  +-- qw@1.0.1
  +-- read@1.0.7
  +-- read-cmd-shim@1.0.1
  +-- read-installed@4.0.3
  +-- read-package-json@2.0.13
  +-- read-package-tree@5.2.1
  +-- readable-stream@2.3.6
  +-- readdir-scoped-modules@1.0.2
  +-- request@2.88.0
  +-- retry@0.12.0
  +-- rimraf@2.6.2
  +-- safe-buffer@5.1.2
  +-- semver@5.5.0
  +-- sha@2.0.1
  +-- slide@1.1.6
  +-- sorted-object@2.0.1
  +-- sorted-union-stream@2.1.3
  +-- ssri@6.0.0
  +-- stringify-package@1.0.0
  +-- tar@4.4.6
  +-- text-table@0.2.0
  +-- tiny-relative-date@1.3.0
  +-- uid-number@0.0.6
  +-- umask@1.1.0
  +-- unique-filename@1.1.0
  +-- unpipe@1.0.0
  +-- update-notifier@2.5.0
  +-- uuid@3.3.2
  +-- validate-npm-package-license@3.0.4
  +-- validate-npm-package-name@3.0.0
  +-- which@1.3.1
  +-- worker-farm@1.6.0
  `-- write-file-atomic@2.3.0

**Comment by ebaauw** [comment]
I don't see homebridge-hue in there.  Did you install it using `sudo npm -g i homebride-hue`?  The latest version should install with the following:
```
├─┬ homebridge-hue@0.11.5
│ ├── deferred@0.7.10
│ ├── fakegato-history@0.5.3
│ ├── homebridge-hue-utils@2.0.3
│ ├── homebridge-lib@4.0.0
│ ├── moment@2.23.0
│ ├── request@2.88.0
│ ├── semver@5.6.0
│ └── ws@6.1.2
```

**Comment by henkhb** [comment]
Its up and running. Don't know why it doesn't show up in the list. I used npm i homebridge-hue, cause sudo is not available in the Onzu Synology image. Also tried installing via ConfigUI with same effect. 

0.11.3 works fine without errors. 

Ihm using the noavahi Version of Homebridge. Maybe this plays a role.

**Comment by ebaauw** [comment]
Sorry, it's a bug in the discovery of bridges, see #420.

**Comment by ottelo9** [comment]
> I don't see homebridge-hue in there. Did you install it using `sudo npm -g i homebride-hue`? The latest version should install with the following:
> 
> ```
> ├─┬ homebridge-hue@0.11.5
> │ ├── deferred@0.7.10
> │ ├── fakegato-history@0.5.3
> │ ├── homebridge-hue-utils@2.0.3
> │ ├── homebridge-lib@4.0.0
> │ ├── moment@2.23.0
> │ ├── request@2.88.0
> │ ├── semver@5.6.0
> │ └── ws@6.1.2
> ```

How can I see this? something like this: npm list homebridge-hue .... ?
