### ISSUE TITLE
Homebridge hangs after update to 0.11.5

### ISSUE THREAD

**Issue by sschuste** [ebaauw/homebridge-hue#420]
Hi Erik,

I just made the update from homebridge-hue@0.11.3 to 0.11.5. The result is the error below preventing the homebridge to start completely. The start process continues normally after the error, at last I can see in the log that homebridge-zp is initialized. Everything seems to be normal but homebridge does not show up with the message _Homebridge is running on port 51826_.

Port 51826 cannot be accessed. Homebridge does not run or hangs somehow. After downgrading the Plugin everything is running smoothly again. Am I missing something? 

I am an experienced Linux user and my system is reasonably well maintained.

homebridge-0.4.45
node-10.15.0

Thanks,
Stefan

Dec 28 18:08:10 raspberrypi homebridge[1405]: [12/28/2018, 6:08:10 PM] [Hue] TypeError: homebridgeLib.UpnpMonitor is not a constructor
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Promise (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/HueDiscovery.js:66:27)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at new Promise (<anonymous>)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at HueDiscovery._upnp (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/HueDiscovery.js:65:12)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at HueDiscovery.discover (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/HueDiscovery.js:42:12)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at HuePlatform.findBridges (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:424:21)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at request.then.catch.then (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:265:17)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Function.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/ext/promise/catch.js:29:4)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:72:4)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:469:14)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Request.self.callback (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:185:22)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Request.emit (events.js:182:13)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1161:10)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Request.emit (events.js:182:13)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1083:12)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at Object.onceWrapper (events.js:273:13)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at IncomingMessage.emit (events.js:187:15)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at endReadableNT (_stream_readable.js:1094:12)
Dec 28 18:08:10 raspberrypi homebridge[1405]:     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by henkhb** [comment]
Same error here.

**Comment by ebaauw** [comment]
See also #419.  I ran into an argument with npm.  Can you please check what versions of the dependencies were installed (`sudo npm -g list --depth=1`).

**Comment by ebaauw** [comment]
Danm, it's an error with the discovery of bridges.  Didn't test that.  Will publish fix shortly.

**Comment by sschuste** [comment]
And it does! Dank u wel. I'm sorry I ruined your evening, but thank you so much for your nice software.
