### ISSUE TITLE
Add Support for ZLL Wall Switches from Busch-Jaeger

### ISSUE THREAD

**Issue by lepatrick** [ebaauw/homebridge-hue#422]
Hey Man!

Busch-Jaeger manaufactured Light & Scene Switches, which ar supported from deCONZ. I add one to deCONZ and I'm able to configure the buttons in phoscon App. This switch (https://www.busch-jaeger.de/produkte/produktloesungen/fernsteuerung/zigbee-light-link/) is not regongnized from the homebridge-hue plugin, because of following error:

#### Log Messages
```
[Hue] HomeBee-GW: /sensors/4: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"2","on":true,"reachable":true},"ep":10,"etag":"4e7e472a30052e6e04579ae4cc7d7b3b","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RM01","name":"RM01 4","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:3b:c2-0a-1000"}
Jan 08 22:45:24 HomeBee homebridge[9897]: [1/8/2019, 10:45:24 PM] [Hue] HomeBee-GW: /sensors/5: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"2","on":true,"reachable":true},"ep":11,"etag":"4e7e472a30052e6e04579ae4cc7d7b3b","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RM01","name":"RM01 5","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:3b:c2-0b-1000"}
Jan 08 22:45:24 HomeBee homebridge[9897]: [1/8/2019, 10:45:24 PM] [Hue] HomeBee-GW: /sensors/6: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"2","on":true,"reachable":true},"ep":12,"etag":"4e7e472a30052e6e04579ae4cc7d7b3b","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RM01","name":"Switch 6","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:3b:c2-0c-1000"}
Jan 08 22:45:24 HomeBee homebridge[9897]: [1/8/2019, 10:45:24 PM] [Hue] HomeBee-GW: /sensors/7: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"2","on":true,"reachable":true},"ep":13,"etag":"4e7e472a30052e6e04579ae4cc7d7b3b","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RM01","name":"Bedienelement 4-fach","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:3b:c2-0d-1000"}
```
<img width="677" alt="bildschirmfoto 2019-01-08 um 23 22 46" src="https://user-images.githubusercontent.com/46504774/50862607-5ac1ff80-139c-11e9-8b15-382516c99c05.png">

**Comment by manup** [comment]
@ebaauw A while ago I've added the Busch-Jaeger, JUNG and GIRA switches for a in-house test to homebridge-hue. It worked very well but unfortunately didn't made a PR yet.

https://github.com/manup/homebridge-hue/commits/master

**Comment by ebaauw** [comment]
Would welcome a PR, but I can probably cut/paste the code.  Would still love for deCONZ REST API to report the possible buttonevent values, so we don’t have to whitelist each switch separately in client applications.

**Comment by ebaauw** [comment]
In v0.11.7.

**Comment by lepatrick** [comment]
Awesome! Guys you are the greatest. Got Switch with 8 Buttons to HK!

**Comment by TangoTaker** [comment]
I have the one that mounts on the wall dimmer, its connected to my hue bridge. I have updates the plugin and restarted holebridge but i cant find it in homekit. Help is appreciated, thanks in advance.

**Comment by ebaauw** [comment]
Could you please attach the debug dump file that homebridge-hue creates?  See https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by manup** [comment]
>its connected to my hue bridge

Note the hue bridge doesn't expose the buttons only the light of mains powered versions.

**Comment by TangoTaker** [comment]
Ok, I attached that. Is there a way that the hue bridge exposes all 8 buttons or is a deconz server necessary?


[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2752210/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Sorry, @manup is right: the Hue bridge only exposes non-Philips friends of Hue green power switches.  You need deCONZ to support the inputs and power metering of wired in wall switches and plugs.

**Comment by lepatrick** [comment]
Dear @ebaauw,

in my Home I'm working with DeCONZ. In Office I just startet with Hue Bridge v2. I connected same switches to bridge, but I just got the first button as light. Am I right, that there is no way to get the buttons through Hue Bridge?

**Comment by ebaauw** [comment]
I need support by the Hue bridge before homebridge-hue can do anything.

**Comment by Kienz** [comment]
> I need support by the Hue bridge before homebridge-hue can do anything.
Any update? Is the eg. Jung Light Link wall transmitter (JUNG ZLL LS 5004 M ZigBee) still only supported by deCONZ? Or can I use it with the Hue Bridge v2 (with all 8 buttons)?

**Comment by ebaauw** [comment]
What update would you expect from me?  It’s up to Signify and Jung to support these switches on the Hue bridge.  Until that happens, there’s nothing Homebridge Hue can do.
