### ISSUE TITLE
Lumi Sensor Smoke labled as unknown ZHAFire sensor

### ISSUE THREAD

**Issue by peer69** [ebaauw/homebridge-hue#425]
I have paired a Xiaomi/Honeywell Smoke Sensor to deCONZ Gateway. It works fine with homebridge-hue in terms of creating the device and reporting an alarm via HomeKit. 
Even though this seems to be working  I see a message in the log which might indicate otherwise: 

`[1/10/2019, 10:47:06 AM] [Hue] zigbee-gateway: /sensors/31: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"reachable":true,"temperature":2800},"ep":1,"etag":"baca327d6fee5b33869874710dd89825","manufacturername":"LUMI","modelid":"lumi.sensor_smoke","name":"lumi.sensor_smoke","state":{"fire":false,"lastupdated":"2019-01-10T09:46:33","lowbattery":false,"tampered":false},"type":"ZHAFire","uniqueid":"00:15:8d:00:02:ad:0b:4f-01-0500"}`

Using ph I receive the following from the API: 

`"31": {
    "config": {
      "battery": 100,
      "on": true,
      "reachable": true,
      "temperature": 2600
    },
    "ep": 1,
    "etag": "52e75aa0dc43bcd7447d9172cace95b7",
    "manufacturername": "LUMI",
    "modelid": "lumi.sensor_smoke",
    "name": "lumi.sensor_smoke",
    "state": {
      "fire": false,
      "lastupdated": "2019-01-10T09:39:15",
      "lowbattery": false,
      "tampered": false
    },
    "type": "ZHAFire",
    "uniqueid": "00:15:8d:00:02:ad:0b:4f-01-0500"
  },`

Is there anything that has to be done or should I just ignore the log-message?

**Comment by ebaauw** [comment]
Just ignore the message.  The warning indicates this model hasn’t been whitelisted explicitly in homebridge-hue.  I heven’t seen much variation in the _IAS Zone_ sensors, so there doesn’t seem to be a need for a model-specific configuration.  Unlike e.g. for switches, where the possible buttonevent values need to be specified per switch.

**Comment by peer69** [comment]
Thanks for the info. I’ll ignore the message then.
