### ISSUE TITLE
Support for ubisys C4, S2, S1

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#427]
Not sure if any-one is actually using the ubisys C4 with homebridge-hue, but looking at the code, homebridge-hue would only expose the first button, since the change in deCONZ to expose it using only a single ZHASwitch resource, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1122.

Also, the S2 switch endpoint is not yet supported by homebridge-hue.

The metering and switch functions of the S1 don't even seem to be supported by deCONZ.

**Comment by ebaauw** [comment]
In v0.11.9.

**Comment by jensflorian** [comment]
Is there any way to disable those ubisys buttons in homebridge-hue? My problem: Each time I add a connected light to the home favourites, the switch will also appear in the favourites as well.

**Comment by ebaauw** [comment]
Yes, use `excludeSensorTypes` in config.json to exclude all switches, see Wiki, or create a `blacklist` resourcelink to exclude individual switches, see README.

**Comment by jensflorian** [comment]
Thanks! Just for future reference, if someone has a similiar problem: The type attribute to be inserted in `config.json` for Ubisys devices is `ZHASwitch`.  For FoH Switches it is `ZGPSwitch`. The Wiki can be found [here](https://github.com/ebaauw/homebridge-hue/wiki/Configuration).
