### ISSUE TITLE
One light accessory per room

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#43]
Currently, homebridge-hue creates a separate HomeKit accessory for each light connected to the Hue bridge, with a single HomeKit `LightBulb` service per accessory.

In my continuous struggle to workaround the HomeKit limitation of 99 accessories per HomeKit bridge (per homebridge instance), I'm playing with the thought to have homebridge-hue create a single accessory per room (as configured in the Hue bridge), with multiple Lightbulb services: one per light.  I would use a config.json parameter to turn on this behaviour.

I'd love to hear your thoughts on this.

**Comment by pponce** [comment]
What would one lose?
Would i still be able to control each light bulb on and off?
Could i still create a scene by selecting only some of the lightbulbs in the room vs having to use all of them?

**Comment by ebaauw** [comment]
Based on my experience with my plugin for Sonos, you'd lose little to nothing.  Most of HomeKit, incl. Siri, works on services; accessories seem to be used only for room assignments.  The iOS built-in **Home** app shows a tile per service; Elgato's **Eve** shows a line per service (in the *Rooms* view), but when you touch that line for details, it shows all services for the accessory; Matthias' **Home** app show a line per accessory in the *Home* view and a line per service in the *Services* view.

I do expect some effects when moving a light from one room to another: HomeKit might treat the corresponding LightBulb service as a different service when attached to another accessory, losing any links to scenes and triggers.  Then again, you'd probably want to change these anyways, when a light is moved to a different room.

Anyway, better wait with trying this out until after we've gained some experience first exposing the Hue Motion sensor as a single accessory with three services, rather than as three separate accessories.

**Comment by pponce** [comment]
makes sense to wait.
Plus as long as it's an option should be safe.

**Comment by ebaauw** [comment]
You would lose the ability to `Identify` an individual light, as that's linked to the `AccessoryInformation` service.

**Comment by ebaauw** [comment]
I've abandoned this idea for now.  While I still think it makes sense to group multiple lights into a single HomeKit accessory, e.g. all spots/bulbs controlled by a single wall switch, you'd want finer grained control than the rooms on the Hue bridge.  Also, deCONZ doesn't support rooms.
