### ISSUE TITLE
Expose Hue Labs Formulas as Switches

### ISSUE THREAD

**Issue by ericboles** [ebaauw/homebridge-hue#431]
I've turned on some Hue Labs Formulas through the native Hue app and have them set to be manually activated. I'd love to get them exposed to HomeKit so they can be activated through Siri/Home app.

When I set  `"sensors": true` in config.json, these formulas are exposed to HomeKit as what seem to be sensors.  

`[1/17/2019, 11:49:23 AM] [Hue] Philips hue: /sensors/3: CLIPGenericStatus "alarm"`
`[1/17/2019, 11:49:23 AM] [Hue] Philips hue: 001788FFFE226CF1-8: Philips HUELABSVTOGGLE "Play and stop"`
`[1/17/2019, 11:49:23 AM] [Hue] Philips hue: /sensors/8: CLIPGenericStatus "Play and stop"`
`[1/17/2019, 11:49:23 AM] [Hue] Philips hue: 001788FFFE226CF1-12: Philips HUELABSVTOGGLE "Start and stop"`
`[1/17/2019, 11:49:23 AM] [Hue] Philips hue: /sensors/12: CLIPGenericStatus "Start and stop"
`
Unfortunately, these aren't configurable directly.  However, when using Matthias Hochgatterer's Home app, I can activate/deactivate the formulas by toggling the "Status" characteristic between 0 & 1. (See screenshot below.)

Is it possible to expose these Formula "sensors" as switches so they can easily be activated/deactivated and incorporated within HomeKit?

![img_925f24b5e001-1](https://user-images.githubusercontent.com/6694920/51342098-31663b00-1a50-11e9-9e02-74e2a1fad256.jpeg)

**Comment by ebaauw** [comment]
No.  homebridge-hue doesn’t know what values `state.status` might take, and cannot decide which sensors, supporting only 0 and 1, to expose as switch, and which as status.  Hue labs should really use CLIPGenericFlag sensors for toggles - these are exposed as switches.

You can create HomeKit scenes containing the status characteristic using Matthias’ Home app or Eve, and recall these scenes from Apple’s Home app or Siri.

**Comment by CarlAmbroselli** [comment]
I've built the plugin [homebridge-hue-labs-switch](https://github.com/CarlAmbroselli/homebridge-hue-labs-switch) if you want to use simple switches for hue labs formulas.
