### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by advanliempt** [ebaauw/homebridge-hue#432]
I do not get the Hue (square) connected. Can you tell me how to connect? The Hue is of course connected with the homebridge itself but not with your plugin.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
What are you trying to connect to what: the Hue bridge to homebridge-hue, or homebridge to HomeKit?  The Hue bridge does not connect to homebridge - that's what homebridge-hue is for.

**Comment by advanliempt** [comment]
sorry am not entirely clear. The hue is already connected to the Housing app (yes I am Dutch).
I understand that it should be as follows, install the plugin and adjust the config with your example. When I start homebridge and press the Hue connection I should get a number that I enter in the second part (xxxxxx). I do not get that number now.

**Comment by ebaauw** [comment]
Can you please attach the homebridge log file?  See https://github.com/ebaauw/homebridge-hue#debug-log-file

**Comment by ebaauw** [comment]
Your config.json is wrong.  The Hue platform should be at the same level as the MiLight platform, not within it.

**Comment by advanliempt** [comment]
Thanks, i have to go now. I look tomorrow!
