### ISSUE TITLE
Idea: Expose Motion Sensor as switch

### ISSUE THREAD

**Issue by dergreg** [ebaauw/homebridge-hue#434]
Hi Erik,

related to #252, just an idea because my wife needs a quick way to turn off the motion sensor in the kitchen 😁
Expose the motion sensor additionally as a switch so you can tell Siri to „turn off the sensor in the kitchen“. That would be really useful, even if nativeHomeKitSensors is true.

Feels feel to close this one if you think it’s a stupid idea 😉

Regards
Greg

**Comment by ebaauw** [comment]
See #120.

**Comment by dergreg** [comment]
Seems like it's not exposed when nativeHomeKitSensors is true and only available via a custom characteristic from within the Eve app. This solution is not compatible with my wife.

I'm thinking of creating such a plugin for solely this purpose 🙂
