### ISSUE TITLE
wallSwitch Settings

### ISSUE THREAD

**Issue by simon2207** [ebaauw/homebridge-hue#435]
Hi,

i have several lights direct attached to a wall switch - powered off while not used. I tried some settings within the config.json - especially with Homebridge-hue and the wallSwitch true and false parameters. 

I ´m using a v2.1 HUE Bridge with Hue, IKEA, and OSRAM lights exposed to Homekit.

But here comes the problem - all powered off ( wallSwitch ) lights are not showing the correct state back to Homekit after turning them off via wallSwitch. For example - you push the wall Switch and the lights goes on - correctly shown in the Homekit app. 
You turn the light off via wall Switch - but the state will not change to off in Homekit. I always have to turn them off manually in the Homekit app. 

Really frustrating - after testing with true and false settings at the wallSwitch entry in config.json I erased those wallSwitch Settings completely. back to default... But that doesn't seem to help either - as those settings will not go away... still no correct state in Homekit... 

Were does homebridge-hue store those settings? any backup? tried by deleting the content in /homebridge/accessories - without success. 

Do i have to delete my /persist folder and will I loose everything??? PLEASE is there any way to fix that??? 

Kind regards
Simon

**Comment by simon2207** [comment]
Got it thanks for that explanation. - do you have any idea how often the hue bridge tries to poll the lamp before switching it to off? Because I recognized no changes in Homekit after several hours... lights still showing on after switching them off via wallswitch. 

Is there any chance to manipulate those polling settings?

**Comment by ebaauw** [comment]
> do you have any idea how often the hue bridge tries to poll the lamp before switching it to off?

The Hue bridge doesn't switch the light off; it only sets `config.reachable` to false.  When `config.reachable` becomes false, homebridge-hue turns the light off when `wallSwitch` is set in config.json.

If memory serves, the Hue bridge makes like one poll request per second; it might take up to three requests per light (on/off, brightness, colour), so with 20 colour lights, each light is polled once a minute.  It takes a couple of cycles before the light is marked unreachable.

> I recognized no changes in Homekit after several hours... lights still showing on after switching them off via wallswitch.

Are you sure these lights are exposed to HomeKit by homebridge-hue (instead of by the Hue bridge natively)?

> Is there any chance to manipulate those polling settings?

Only by reducing the number of lights connected to the Hue bridge.

**Comment by simon2207** [comment]
Are you sure these lights are exposed to HomeKit by homebridge-hue (instead of by the Hue bridge natively)?

yes I am - if my config is correct. Philips lights are natively shown in Homekit - while Osram and IKEA Lights are connected to the Hue Bridge - but are only able to show up in Homekit via Homebridge-hue Plugin... and I have those issues with all 3 types of lamps. 

Please have a look at my settings... maybe you see the issue at a glance. Please have in mint that I m also using deconz / raspee sensors via Homebridge-hue.

"platform": "Hue",
            "name": "Phillips Hue",
            "hosts": [
                "10.1.1.13", 
                "10.1.1.10"
            ],
            "users": {
                "xxx": "xxx-0sv7aA",
                "xxx": "xxx"
            },
            "lights": true,
            "sensors": true,
            "lowBattery": 15,
            "wallSwitch": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ]
        },

Thank you!!!

10.1.1.13 is my V2.0 HUE Bridge and 10.1.1.10 a second raspberry with deconz and raspee installed.

**Comment by ebaauw** [comment]
Config looks fine to me.  Could you capture and attach a debug log file while switching a non-Hue light off using the wall switch and waiting a while? Ser https://github.com/ebaauw/homebridge-hue/blob/master/README.md#debug-log-file

**Comment by simon2207** [comment]
Yes - will do that tomorrow - Time to spent some time with my family during the evening. 
I m also running some firmware upgrades on some new HUE Bulbs and will install a second V2.1 Bridge - cause I m running out of space on my first bridge ( hopefully that is not the trigger for my issues ) ;-)

**Comment by simon2207** [comment]
This issue is been resolved... after adding a second hue bridge to my network and some configuration changes in my light setup ( moved several 3rd party bulbs to the new bridge ) it updates the status in home. Sometimes it takes a little longer but this might be due to the fact that I have more then 60 bulbs at Home. 

Thanks a lot
