### ISSUE TITLE
Save hub user for the next restart.

### ISSUE THREAD

**Issue by shoket** [ebaauw/homebridge-hue#437]
#### Issue
  Hi.
I'm using Homebridge Version 0.4.45 on Raspberry Pi 3.

Is there any way to restart the homebridge does not need to press the link button of the Philips Hub?
When I start the first time it asks me to press the button, I pulse it and I take the generated user, I copy it in config.json and everything works perfectly but when I restart homebridge I get back and ask to press the hub button again and it generates a new user again.

If I do not press the button, homebridge does not start until I do.

#### Log Messages
 
```
```

**Comment by ebaauw** [comment]
> I copy it in config.json and everything works perfectly but when I restart homebridge I get back and ask to press the hub button again and it generates a new user again.

Are you sure you copied it correctly?  The bridgeid and API key are case sensitive.  Please attach your config.json (as a file - don't copy/paste it).

**Comment by ebaauw** [comment]
Config.json looks good.  Not sure what's going on.  Could you please capture a debug log file and attach that, see https://github.com/ebaauw/homebridge-hue#debug-log-file.  Please go through the routine of pressing the bridge button, making sure homebridge has fully started.  And please also attach the debug dump file, https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by ebaauw** [comment]
Sorry, I need the debug log (when running `homebridge -D`.

**Comment by ebaauw** [comment]
Somehow you did manage to copy/paste an additional `E` in the bridgeid.
From the log:
```
[37m[1/26/2019, 10:10:22 AM][39m [36m[Hue][39m Philips hue: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "001788FFFE6DD81A": "pScblZttGDGh-n44T0694kgyuCLMycooqy9PpU4C"
      }
    }
  ]
```

From config.json:
```
  {
    "platform": "Hue",
    "users": {
      "001788FFFEE6DD81A": "***************************************1"
    },
    "lights": true
  },
```

**Comment by shoket** [comment]
Sorry, it's already fixed in debug mode.
[Archivo comprimido2.zip](https://github.com/ebaauw/homebridge-
hue/files/2798906/Archivo.comprimido2.zip)

**Comment by shoket** [comment]
> Somehow you did manage to copy/paste an additional `E` in the bridgeid.
> From the log:
> 
> ```
> [37m[1/26/2019, 10:10:22 AM]�[39m �[36m[Hue]�[39m Philips hue: created user - please edit config.json and restart homebridge
>   "platforms": [
>     {
>       "platform": "Hue",
>       "users": {
>         "001788FFFE6DD81A": "pScblZttGDGh-n44T0694kgyuCLMycooqy9PpU4C"
>       }
>     }
>   ]
> ```
> From config.json:
> 
> ```
>   {
>     "platform": "Hue",
>     "users": {
>       "001788FFFEE6DD81A": "***************************************1"
>     },
>     "lights": true
>   },
> ```

:O going

**Comment by shoket** [comment]
Yes now.
It was that, I had not realized that "E" in the Hub ID, what a silly thing hehehe.

I was trying to find the solution since yesterday.

Thank you very much for taking your time to help me out.

Thank you. 👍
