### ISSUE TITLE
Cannot connect to bridge, preventing homebridge from starting

### ISSUE THREAD

**Issue by peter99330** [ebaauw/homebridge-hue#442]
#### Issue
Homebridge cannot start because of the hue plugin. Hue plugin can seemingly not find the bridge, although it is specified via the "host" config parameter. The two IP addresses do both not belong to my bridge.

Config file:
```
{
            "platform": "Hue",
            "users": {
                "xxxxxxxxx": "xxxxx-xxxxx"
            },
            "host": "192.168.0.104",
            "sensors": true,
            "nativeHomeKitSensors": false,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ],
            "lights": true
        }
```

#### Log Messages
```
[2/16/2019, 11:57:06 AM] [Hue] 192.***.***.33: bridge request 4479: get /config
[2/16/2019, 11:57:06 AM] [Hue] 192.***.***.33: bridge communication error ETIMEDOUT on 192.***.***.33
[2/16/2019, 11:57:06 AM] [Hue] 10.***.***.20: bridge request 4479: get /config
[2/16/2019, 11:57:06 AM] [Hue] 10.***.***.20: bridge communication error ETIMEDOUT on 10.***.***.20
```

**Comment by ebaauw** [comment]
Did you restart homebridge after changing config.json?  Are you sure homebridge is using this config.json file?  If so, please attach the debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file).

**Comment by peter99330** [comment]
Okay, this is slightly embarrassing. A restart of homebridge actually fixed the behavior. 

Thanks for the help!

**Comment by iRonin** [comment]
I've got the same error today after restarting Homebridge. I restarted it a couple of times now and it is still there.

**Comment by iRonin** [comment]
Where does it take this IP from?

```
[2/18/2019, 6:52:52 PM] [Hue] 10.***.***.25: bridge communication error ETIMEDOUT on 10.***.***.25
```

**Comment by iRonin** [comment]
I've got 2 bridges, they both have Its assigned via MAC address assignment, nothing has changed in my configuration, I just restarted my NAS and I get this:

```
[2/18/2019, 6:43:07 PM] [Hue] Philips hue: Philips BSB002 bridge v1901181309, api v1.29.0
[2/18/2019, 6:43:07 PM] [Hue] Philips hue 2: Philips BSB002 bridge v1901181309, api v1.29.0
[2/18/2019, 6:43:07 PM] [Hue] Philips hue: 8 accessories
[2/18/2019, 6:43:07 PM] [Hue] Philips hue 2: 4 accessories
[2/18/2019, 6:43:12 PM] [Hue] 10.***.***.25: bridge request 1: get /config
[2/18/2019, 6:43:12 PM] [Hue] 10.***.***.25: bridge communication error ETIMEDOUT on 10.***.***.25
```

I don't have `host` parameter specified and the IP subnet is 192.168.0.x for the Hue bridges.

**Comment by iRonin** [comment]
All started working now when I specified the IPs in the config but this means there was some change in the code that broke it.

**Comment by ebaauw** [comment]
> Where does it take this IP from?

From UPnP and from the meethue portal.  You can check with `ph discover -v` to see what bridges are discovered.  
Note that the Hue bridge registers with the meethue portal using your _public_ IP address.  When querying the meethue portal, it returns the bridges registered with the same public IP address.  If your ISP uses the same public IP address for other customers, their bridge(s) will be returned as well.

> All started working now when I specified the IPs in the config

Yes, that disables the discovery.

> this means there was some change in the code that broke it

No, it probably means one of the other ISP customers sharing you IPv4 address installed a Hue bridge.

**Comment by iRonin** [comment]
Thank you for explanation, though my current public IP starts with `89` not `10`.
The log also showed that the script  correctly found 2 of my bridges, it just uses incorrect IP to connect to them.

**Comment by hans24o** [comment]
> All started working now when I specified the IPs in the config but this means there was some change in the code that broke it.

Hi, I got the same issue. Which config did you change and where to add the IP?
