### ISSUE TITLE
Feature request: Add dummy bulb to homebridge-hue

### ISSUE THREAD

**Issue by mikesalz** [ebaauw/homebridge-hue#444]
#### Issue

I'm not sure if this is the right forum for a feature request, but I think it could be very handy if you could add the option to create dummy hue bulbs (or switches) in the homebridge-hue plugin.  Here's why: Hue bulbs are controllable from the Logitech Harmony hub's home control buttons.  As of right now, there is no way to directly connect those buttons to HomeKit scenes.  But a Harmony home control button could turn a dummy Hue bulb on/off, which could then be configured within HomeKit to trigger a scene.  I know, brilliant idea, right?? :) 

#### Log Messages

```
```

**Comment by ebaauw** [comment]
So brilliant it’s already possible: create a CLIPGenericFlag sensor on the Hue bridge, configure the Harmony to control it, and let homebridge-hue expose it as a switch to HomeKit.

I know there is a homebridge-harmony plugin, but I have no idea what it does.

**Comment by mikesalz** [comment]
Thanks so much for the quick reply!  This sounds like it will work.  I will give this a try.

**Comment by mikesalz** [comment]
OK, so dumb question - What would you recommend as the easiest way to create a CLIPGenericFlag sensor?

**Comment by ebaauw** [comment]
Throught the Hue API.  For the Hue bridge: use the built-in CLIP API debugger, see https://developers.meethue.com/develop/get-started-2/.  Personally, I use `ph` to issue API commands manually, or place them in scripts, see https://github.com/ebaauw/ph.sh.

**Comment by mikesalz** [comment]
Thanks again, @ebaauw!  I was able to use the API debugger to successfully create two new CLIPGenericFlags.  That's perfect.  Except, now I have discovered that the Harmony remote only sees lights and scenes.  So unfortunately, the CLIPGenericFlag is not helpful in this case.  Do you know of any way to create a fake/emulated bulb that the Hue bridge would see and can turn on/off?

**Comment by ebaauw** [comment]
No, there's no CLIP variant of a light.  Is there no way to customise the commands sent by the Harmony?

**Comment by mikesalz** [comment]
Eh, you can customize the buttons to an extent.  There are four "Home Control" buttons.  There is a Harmony app that lets you assign devices to those buttons.  The available devices are limited to things like Hue bulbs, Lutron Caseta switches, etc.  Well, thanks again for all of your help.  Maybe I'll come up with another workaround.  Or maybe Logitech will eventually make the remote natively HomeKit compatible!

**Comment by ebaauw** [comment]
Did you have a look at https://github.com/nicoduj/homebridge-harmony.

**Comment by mikesalz** [comment]
I actually already have that one installed.  It exposes your activities and devices to HomeKit, which is great.  But it doesn't expose the physical Home Control buttons.

**Comment by ChalesGiron** [comment]
> 

Hi both. This seems to be exactly what I need. I would like to program the dimmer switches in the hue bridge to trigger activities in Homekit (via Homebridge). I therefore need a dummy-switch or light of witch I can change the value based on a press (e.g. long press) on a hue dimmer switch. So, the solution suggested seems perfect. I only cannot figure out how to CLIPGenericFlag sensor? Could you please help me as a dummy. I logged on to "debug/clip.html" but what then? Thanks for your help!! Chales

**Comment by ebaauw** [comment]
Do a POST to `/sensors`, see the API documentation, https://developers.meethue.com/develop/hue-api/5-sensors-api/.
