### ISSUE TITLE
Error: Homebridge version 0.4.46 required

### ISSUE THREAD

**Issue by flobernd** [ebaauw/homebridge-hue#446]
Hi there,

after upgrading `homebridge` and `homebridge-hue`, I get the following error message during startup:
```shell
Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.46 which does not satisfy the current HomeBridge version of 0.4.45. You may need to upgrade your installation of HomeBridge.
```

But I already installed version 0.4.46:
```shell
> npm list -g --depth 0
/usr/lib
├── homebridge@0.4.46
├── ...
├── homebridge-hue@0.11.16
├── ...
├── npm@6.8.0
└── npm-check-updates@2.15.0
```

Anything I can do about that?

Best regards

**Comment by ebaauw** [comment]
Are you sure you don’t have another (local?) installation of homebridge?

**Comment by flobernd** [comment]
Shame on me. Don't know how this happened, but you were right.

Thanks
