### ISSUE TITLE
DeConz connection error ECONNREFUSED 

### ISSUE THREAD

**Issue by Kalvintan** [ebaauw/homebridge-hue#447]
Hi, I got the problem with the connection with DeConz. My Installation is set up as below:

Homebridge Run in the Hyper-V with Debian (Static IP 192.168.0.20)
DeConz and ConBee installed and run on Windows Server (Static IP 192.168.0.101)
Philips HUE (Static IP 102.168.0.105)

And this is the error I got, Philips Hue connected fine, but not the DeConz

![capture](https://user-images.githubusercontent.com/1113098/53291190-549aad80-37a7-11e9-80a8-f8b7d1f2ccb7.PNG)

- I'm not sure if I got the correct user id and key?
- Firewall checked, and open/allow (I can access DeConz from another computer).

`{
            "platform": "Hue",
            "heartrate": 2,
            "name": "Hue",
            "nupnp": true,
            "hosts": [
                "192.168.0.105",
                "192.168.0.101:8080"
            ],
            "users": {
                "001788FFFEXXXXXX": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "00212EFFFFXXXXXX": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            },
            "hueDimmerRepeat": true,
            "linkButton": false,
            "parallelRequestS": 30,
            "lights": true,
            "hueMotionTemperatureHistory": true
        }`

I got the philips HUE users ID by pressing the button and refilled back to config.
and DeConZ user ID got it from deCONZ network setting (TC Link Key).

Any idea?

**Comment by ebaauw** [comment]
EHOSTUNREACH means that the host (i.e. the machine running deCONZ) is unreachable from the machine running homebridge.  ECONNREFUSED means the machine is found, but the port is blocked.  Can you access deCONZ from the Hyper-V?

**Comment by Kalvintan** [comment]
> EHOSTUNREACH means that the host (i.e. the machine running deCONZ) is unreachable from the machine running the home bridge. ECONNREFUSED means the machine is found, but the port is blocked. Can you access deCONZ from the Hyper-V?

Ah thanks for the reminding, the IP address has to refer to Virtual Switch instate of the physical ethernet IP address. It works now.
