### ISSUE TITLE
Ability to expose Aqara (or any other) vibration sensor as motion sensor

### ISSUE THREAD

**Issue by njakobsen** [ebaauw/homebridge-hue#448]
#### Issue
Aqara Vibration sensor appears in homekit as a button, but it would be very handy to have the option to treat it as a motion sensor so it could be used on windows to trigger the camera in the room. That way homekit would automatically send a stillframe of the room when motion on the window was detected.

I'm only a beginner at Homebridge and ZAH components, so all I can tell is that the decision is made here https://github.com/ebaauw/homebridge-hue/blob/master/lib/HueSensor.js#L469. Perhaps a configuration variable could be set to choose between button/motion sensor.

For reference, I am running deCONZ with a Conbee stick.

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/issues/179.  Create a CLIPPresence sensor in deCONZ.  homebridge-hue exposes that as a motion sensor.  Create rules on deCONZ to set the CLIPPresence sensor when the vibration sensor fires.

**Comment by njakobsen** [comment]
Thanks Erik, I'll check that out. I'm running the headless deCONZ instance so I'll have to look at the REST API documentation to see how I can accomplish this.

**Comment by njakobsen** [comment]
That worked great. I adapted the instructions from https://github.com/ebaauw/homebridge-hue/issues/179#issuecomment-338756148.
