### ISSUE TITLE
How to remove a bridged accessory 

### ISSUE THREAD

**Issue by pponce** [ebaauw/homebridge-hue#449]
I used to use HA Bridge as a way to use my harmony hub activities within homekit.
I no longer use it but the HA bridge that was setup to be exposed to homekit via Homebridge-Hue still shows up in homekit. Is there any way to remove it without having to re-setup everything?

**Comment by ebaauw** [comment]
Did you restart homebridge?  Is HA Bridge still running?  You might need to set `hosts` in config.json to disable automatic discovery of bridges.

**Comment by pponce** [comment]
I disabled habridge and no longer use it.
I already use the hosts setup in config.json. I specify the ip address of my real philips hue bridge and also of the deconze gateway running on the same pi that homebridge runs on.

**Comment by ebaauw** [comment]
Could you please attach the debug dump file and the debug log file (see 
https://github.com/ebaauw/homebridge-hue#troubleshooting) and a screenshot of the HA Bridge accessory setting from Apple’s Home app?  In particular: which HomeKit bridge it’s connected to.

**Comment by pponce** [comment]
Ok i think i figured it out.
I must have named the "link buttons" incorrectly when i had both my hue bridge and my emulated HA bridge both running live.  I named the HA bridge link button Hue and the other Hue button HA Bridge.
So when i removed the HA bridge the link button for HUE remained and was just named HA Bridge.

Just to confirm.
Should the serial number for the link button as exposed to homekit in the home app be the user name?

**Comment by ebaauw** [comment]
No, the bridge id, which is the bridge’s mac address.  The username is in fact the API key and should not be visible to HomeKit.

**Comment by pponce** [comment]
Ok. Thanks.
Confirmed the serial number in HomeKit for the link button is the MAC address of my philips hue bridge..... 
This was all just do to user error in naming this link button...
Thanks!
