### ISSUE TITLE
Aqara Cube | what button does what?

### ISSUE THREAD

**Issue by TangoTaker** [ebaauw/homebridge-hue#450]
I cant get behind which of the 9 buttons in Homekit is what cube gesture.
Thanks

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/138#issuecomment-325101635 for an overview of the buttonevents deCONZ issues for the cube, and how the sides are layed out.  This is translated to HomeKit as follows:
- The first six HomeKit buttons map to the 100x, 200x, ..., 600x events.  _Single Press_ for flip, _Long Press_ for push, and _Double Press_ for double tap.   The side (ending) on top determines the button.  The starting side for flip is lost in the translation to HomeKit.
- The seventh button is for the 700x events.  _Double Press_ for drop and _Long Press_ for shake.
- The last two buttons are for rotation left and right.  _Single Press_ for an angle < 45°, _Double Press_ for an angle between 45° and 90°, and _Long Press_ for an angle > 90°.

**Comment by TangoTaker** [comment]
Great overview, thanks

**Comment by Kroellie** [comment]
> * The last two buttons are for rotation left and right.  _Single Press_ for an angle < 45°, _Double Press_ for an angle between 45° and 90°, and _Long Press_ for an angle > 90°.

Hi, I don't really get your 'the last two buttons' remark. Do you mean button 6 and 7? After pairing I have 6 buttons, each with three different 'tap' types. Next to that I have a 7th button with only two 'tap' types. However, I don't find any buttons relating to the rotational movement of the cube. Did I mess up the pairing?

**Comment by ebaauw** [comment]
No, buttons 8 and 9.  If they don’t show, most likely deCONZ hasn’t exposed the second ZHASwitch resource for the _Analog Input_ cluster 0x000c on endpoint 0x03.

**Comment by Kroellie** [comment]
> No, buttons 8 and 9. If they don’t show, most likely deCONZ hasn’t exposed the second ZHASwitch resource for the _Analog Input_ cluster 0x000c on endpoint 0x03.

Sorry to be bothering you, but does this mean I can't use the rotational switches using your homebridge-hue plugin?

**Comment by Kroellie** [comment]
> No, buttons 8 and 9. If they don’t show, most likely deCONZ hasn’t exposed the second ZHASwitch resource for the _Analog Input_ cluster 0x000c on endpoint 0x03.

Meaning I should re-pair the device?

**Comment by ebaauw** [comment]
Probably.  You might also try reading the _Basic_ cluster attributes in the deCONZ GUI while searching for new devices.

If memory serves, there were several issues causing deCONZ not to expose the second ZHASwitch.  You might want to check https://github.com/dresden-elektronik/deconz-rest-plugin/issues.

You might want to double-check that:
- The deCONZ GUI shows three endpoints; and
- The REST API plugin exposes two ZHASwitch `/sensors` resources, one for the digital events (with a `uniqueid` ending in `-02-0012`) and one for the analog events (ending in `-03-000c`).

**Comment by daniel-lo** [comment]
Interesting I found this .. my recommendation would be to check the zigbee adapter for iobroker .. the dev has managed to make the objects quite understandable. In comparisson (and I am a complete newbie to conbee) what I get out of the deconz iobroker adapter (API call) is not understandable at all. 
I am not much into clusters and endpoints - I take the user perspective as a non-dev who automates his home.
