### ISSUE TITLE
Toggle switch button?

### ISSUE THREAD

**Issue by bohtho** [ebaauw/homebridge-hue#451]
I’m sorry if this has been addressed before.

Just got some Aqara wireless switches and while they’re not visible in Phoscon, they were easily added there, and showed up in HomeKit via Homebridge-Hue.

Is it possible to somehow program (in Homebridge, Home.app, Eve, or Deconz) them to toggle the same light on and off on the same button (without having to E.g. short press for on and long press for off)? This is a very common behaviour on similar switches in general, and also long press dimming which remembers the last direction of dimming and toggles this too.

**Comment by ebaauw** [comment]
Afaik, this can only be done through rules on deCONZ, not through HomeKit automations.  See 
https://developers.meethue.com/develop/application-design-guidance/create-a-hue-tap-toggle-button/.  They still use a CLIPGenericFlag, but you can also use the light state.on or group state.all_on as the condition.

**Comment by bohtho** [comment]
Ok. So I dabbled a bit with the REST API and see that there's actually a "toggle" action which works fine. But it would be even better to BIND by the Deconz rules as you say (BINDing would make it quicker, no?). I tried this because it says in the docs that you should use the "ep" value of the Switch as the value of the condition, but this does nothing:
`{
    "actions": [
        {
            "address": "/groups/5/action",
            "body": {
                "on": true
            },
            "method": "BIND"
        }
    ],
    "conditions": [
        {
            "address": "/sensors/11/state/buttonevent",
            "operator": "eq",
            "value": "1"
        }
    ],
    "name": "Kjøkken grp 5 bryter 11 ep 1 all lights On/Off"
}`

**Comment by ebaauw** [comment]
> there's actually a "toggle" action which works fine.

The `toggle` action only works for groups, and uses state.all_on to determine whether to send _On_ or _Off_., see https://github.com/dresden-elektronik/deconz-rest-plugin/pull/396.

> BINDing would make it quicker, no?

In theory yes, although I doubt you notice much difference in practice.  With bindings (from the switch to (a group of) lights), the switch sends a message to the (group of) light(s), controlling them directly (even when the gateway is down).  Without, the switch sends a message to the gateway, causing a rule to be fired, which causes another message to the (group of) lights.

> BIND by the Deconz rules

I never got BIND rules to work.  I setup my bindings manually in the deCONZ GUI.

Note that a binding only specifies to which device/endpoint or group the switch sends its commands.  The switch needs to send the appropriate Zigbee command to control (a group of) lights directly.  Typically the command is hard-coded in the switch firmware, but some professional-grade switches (like ubisys) allow the command to be configured.  Not all switches support sending commands though; some (notably Xiaomi) only send notifications to the coordinator, requiring rules to control (groups of) lights.

**Comment by bohtho** [comment]
Ok, currently doing toggle logic in Node-Red against the Deconz REST API. Just doesn’t *feel* as instant, but I don’t know.

Regarding dimming logic; it’s a shame the websocket notifications from Deconz doesn’t actually notify all button events, especially the hold (push) *and* hold (release) (two distinct for holding events).

**Comment by ebaauw** [comment]
I'm unfamiliar with Node-Red, but I image it introduces some overhead.  Gateway rules would be more responsive.

The `buttonevent` values that deCONZ reports depend on what the switch supports.  Different (versions of) different Xiaomi switches send notifications for different events.  See https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#wireless-switches.

**Comment by bohtho** [comment]
I have the "Aqara smart wireless switch" WXKG11LM 2018 and I'm pretty sure the Deconz websocket only reports the first of the "hold" events.

But anyway, since it's not visible in Phoscon, *and* setting up binding rules through the REST API doesn't seem to work, i will have to get into the GUI again to set up binding/rules. It's been a long time, and I have since an early install of Deconz upgraded many times without changing my deconz.service file. It's now says amongst other things "-platform minimal" and "user 1000".

When I stop it and start Deconz GUI from /lib/bin (with X11 forwarding via SSH) it doesnt seem like the same Deconz used in my ordinary Phoscon. Only a limited devices are visible. And when I exit and return to deconz.service and Phoscon it seems messed up for a while before returning to normal.

I know you have an issue with Deconz-REST-API concerning a similar problem with the GUI and the .service file, but is it generally possible to enter the GUI while Deconz is running its usual business ? And is that an easy fix to my .service file ?

**Comment by ebaauw** [comment]
>  I'm pretty sure the Deconz websocket only reports the first of the "hold" events.

What do you mean "only the first of the hold events"?  The Hue dimmer switch is the only device that continues to issue events, while a button is held; all other switches only issue a single notification while holding.

> is it generally possible to enter the GUI while Deconz is running its usual business

deCONZ installs two services, `deconz.service` and `deconz-gui.service`.  If you disable and stop the first and enable and start the second, the GUI is enabled.  I run this on a headless Raspberry Pi and connect to the GUI over VNC when needed.

**Comment by bohtho** [comment]
The wiki says my switch supports:

> 1 | x001 | Hold
> 
> 3 | x003 | Release (after hold)

But I only get a one message when holding, and not on final release. Will investigate buttonevents more closely, but this would imply 2 events for hlding a button.

Regarding the GUI service, it seems the `deconz-gui.service` depends on VNC and another graphical(?) system which I don't have installed or use (?). I think I got an error the last time I tried to enable this service. Will have to try and delete the dependants and just try again then.

**Comment by ebaauw** [comment]
You should get an x003 after an x001.  Next step would be to enable deCONZ logging and check whether the gateway receives notifications for both.

The deCONZ GUI doesn’t depend on VNC, but it needs the graphical X11 environment.  There’s still some issues that the service is started too early in the boot process and crashes a couple of times, before the graphical environment has initialised, see 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/797.

**Comment by bohtho** [comment]
Actually it only supports button events 1,2,4 (I corrected the Wiki which only said 2,4) which means "hold", "Release (after press)" and "Double press", so advanced logic for hold events then:-/

Anyway, I tried the remote Phoscon (at http://www.dresden-elektronik.de/pwa/) and the Aqara switches were suddenly showing (even though my own Phoscon with no visible switches came with Deconz 2.05.60 which should be the latest), and to my surprise I was able to link simple button toggles to light groups in the GUI (which created a barrage of resource links and rules but that's ok).

**Comment by ebaauw** [comment]
> Actually it only supports button events 1,2,4 (I corrected the Wiki which only said 2,4) which means "hold", "Release (after press)" and "Double press", so no logic for hold events then:-/

It's one of the `lumi.remote.b`_..._`acn01` wireless wall switches, then?  Does homebridge-hue expose it correctly, with support for _Single Press_, _Double Press_, and _Long Press_ (on hold)?

> I tried the remote Phoscon (at http://www.dresden-elektronik.de/pwa/) and the Aqara switches were suddenly showing

I don't use Phoscon myself, but I see a lot of issues related to the browser cache.

**Comment by bohtho** [comment]
Yep, and hb-Hue has been showing them perfectly in Homebridge/Home.app since pairing; 3 kinds of presses for single rocker and 3x3 for the double rocker.

**Comment by kaowiec** [comment]
You can use EVE app to toogle switch.
let's start:
Open SCENES --> RULES and ADD RULE. NEXT

First step (Trigger):
ADD TRIGGER, ACCESSORY --> OTHER VALUE. 
Now - go to room, look for corespondent switch and mark "SINGLE PRESS". 
Then ADD and NEXT

Second step (Value):
Add Value Condition 
Go to room, find lamp (or other device). 
(This is why HK know - to switch ON or OFF)
--> check Your device OFF ("next time" set ON) and NEXT

Third step (Scene):
Add Scene, find Your switch (from second step) and set reverse action for this in Value Condition (Value step).
(if in "Value step" it is OFF then set to ON). Name scene, name rule.
This is half of Your job. 
Now again but reverse  (steps second and third "next time")
