### ISSUE TITLE
Question: Two kinds of Gateway Information (Phoscon-GW) shown in Eve-App 

### ISSUE THREAD

**Issue by gpl1998** [ebaauw/homebridge-hue#453]
not an issue, just a question ...

I'm wondering why there are two different layouts for the Phoscon-GW in the Eve-App (see screenshot). Usually after a reboot, Eve shows left layout - after a while (one day or so) it changes to the right layout.

![Screenshot](https://user-images.githubusercontent.com/47315068/55137973-a6ca4800-5132-11e9-8904-41a32fea9310.jpg)

**Comment by ebaauw** [comment]
I’ve seen this quirk in Eve as well, not just for the gateway accessory, but also for e.g. the accessories for a CLIPGenericStatus.  Unloading Eve from memory (double-click the Home button and swipe the window up) and restarting it seems to fix it.

**Comment by gpl1998** [comment]
Thanks for your quick answer.
