### ISSUE TITLE
API V1.31 message

### ISSUE THREAD

**Issue by pponce** [ebaauw/homebridge-hue#454]
I'm getting an error saying that i'm not running hue bridge API v1.31.
I've been checking for updates on my V2 bridge but there are none.
This what homebridge-hue reports and it matches 
[Hue] Philips hue: Philips BSB002 bridge v1901181309, api v1.29.0
[Hue] Philips hue: warning: not using recommended Hue bridge api version 1.31.0

Is V1.31 out yet? Looked it up on google and i get no hits.

**Comment by ebaauw** [comment]
Mine reports:
```
[4/8/2019, 11:04:23 PM] [Hue] philipshue: Philips BSB002 bridge v1931069120, api v1.31.0
```
Apparently, it was installed Saturday:
```
$ ph -H philipshue get -s /config/swupdate2/bridge
{
  "lastinstall": "2019-04-06T18:35:27",
  "state": "noupdates"
}
```
Typically it takes them some time to roll out new versions worldwide.

**Comment by pponce** [comment]
Figured I had to wait. Just thought it was strange to see no information on it, on the web.. But I guess that is not strange for philips based on your comment. 😄
