### ISSUE TITLE
Unknown Light model "Paul Neuhaus" RGBW

### ISSUE THREAD

**Issue by dergreg** [ebaauw/homebridge-hue#455]
Hi Erik

similar to #360 this is another unknown light model for a Paul Neuhaus RGBW lamp. Any ways to fix this? Using the latest homebridge-hue and hue firmware:

`Apr 08 21:20:09 raspi homebridge[21763]: [2019-4-8 21:20:09] [Hue] Philips hue: /lights/9: warning: using default colour gamut for unknown light model {"state":{"on":false,"bri":1,"hue":7072,"sat":171,"effect":"none","xy":[0.4031,0.392],"ct":275,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Extended color light","name":"Deckenleuchte","modelid":"NLG-RGBW light ","manufacturername":"Neuhaus Lighting Group ","productname":"Extended color light","capabilities":{"certified":false,"control":{"colorgamuttype":"other","ct":{"min":275,"max":295}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"classicbulb","function":"mixed","direction":"omnidirectional"},"uniqueid":"00:15:8d:00:02:41:01:10-02","swversion":"1001-0007"}`

Regards
Greg

**Comment by ebaauw** [comment]
Can you run `ph probe -v /lights/9`to see if we can determine what range of colour it supports?

```
"ct":{"min":275,"max":295}
```
For an extended colour light, it supports a very small range of colour temperatures.  I wonder if the reported values are correct.

```
"modelid":"NLG-RGBW light ","manufacturername":"Neuhaus Lighting Group "
```
Do these end in a space character?

**Comment by dergreg** [comment]
> Can you run `ph probe -v /lights/9`to see if we can determine what range of colour it supports?
> 
> ```
> "ct":{"min":275,"max":295}
> ```
> For an extended colour light, it supports a very small range of colour temperatures. I wonder if the reported values are correct.
> 

Yes color adjustment at a dimmed down level only supports very few color variances, at a dimmed up level it's more.

```
ph probe: /lights/9: cool ... done
ph probe: /lights/9: warm ... done
ph probe: /lights/9: red ..........................^C
```

It's stuck "forever" at red, at least I waited like three minutes. Also tried with `-t 1` and higher.

> ```
> "modelid":"NLG-RGBW light ","manufacturername":"Neuhaus Lighting Group "
> ```
> Do these end in a space character?

Seems so, it's a 1:1 copy&paste from console

**Comment by ebaauw** [comment]
By default, `ph probe` will timeout  after five minutes.  To change that, use
```
ph probe -v -t 1 /lights/9
```
to set the timeout to one minute.  See `ph probe -h`.

The standard `ph` timeout
```
ph -t 1 probe -v /lights/9
```
sets the timeout per bridge request.  `ph probe` does a bridge request every five seconds (on each dot) to see if the bridge reports different `xy` values.

**Comment by dergreg** [comment]
Ok, here we go:

```
ph probe: /lights/9: cool ... done
ph probe: /lights/9: warm ... done
ph probe: /lights/9: red ............... timeout
ph probe: /lights/9: green ............... timeout
ph probe: /lights/9: blue ............... timeout
{
  "manufacturername": "Neuhaus Lighting Group ",
  "modelid": "NLG-RGBW light ",
  "type": "Extended color light",
  "bri": true,
  "ct": {
    "min": 275,
    "max": 295
  },
  "xy": {
    "r": [
      0.9961,
      0.0001
    ],
    "g": [
      0.0001,
      0.9961
    ],
    "b": [
      0.0001,
      0.0001
    ]
  }
}
```

**Comment by ebaauw** [comment]
OK, I'll suppress the message in the next version, but that won't change the fact that we'll still be using the default gamut.
