### ISSUE TITLE
ph returning "not a Hue bridge nor deCONZ gateway"

### ISSUE THREAD

**Issue by zladukas** [ebaauw/homebridge-hue#457]
Hello Eric, 
could You, please, help figure out what's wrong with deCONZ (I've checked old issue) :

pi@ddpi:~/deconz $ ph discover
{
  "11.40.148.17": "00212EFFFF013FBE",
  "11.40.148.17:8080": "00212EFFFF013FBE",
  "11.40.148.50": "001788FFFE2A2108"
}

pi@ddpi:~/deconz $ ph -H 11.40.148.17:8080 -u <deCONZ_USER> get /sensors/4
ph: error: 11.40.148.17:8080: http status 404
ph: error: 11.40.148.17:8080: not a Hue bridge nor deCONZ gateway

curl -X GET http://11.40.148.17:8080/api/<deCONZ_USER>/sensors/4
{"config":{"battery":100,"offset":-60,"on":true,"reachable":true},"ep":1,"etag":"cafa6f60525bf2a19cf87bc4fc5b54d9","manufacturername":"LUMI","modelid":"lumi.sensor_ht","name":"Room sens","state":{"lastupdated":"2019-04-09T16:32:30","temperature":2300},"swversion":"20160516","type":"ZHATemperature","uniqueid":"00:15:8d:00:01:c2:c2:95-01-0402"}

when same time with Philips HUE GW ph is working perfectly:
ph -H 11.40.148.50 -u <philips_hue_user> get /sensors/24
{ 
  "state": {
    "status": 0,
    "lastupdated": "2019-04-08T19:05:38"
  },
  "config": {
    "on": true,
    "reachable": true
  },
  "name": "Dimmer Switch 23 SceneCycle",
  "type": "CLIPGenericStatus",
  "modelid": "PHWA01",
  "manufacturername": "Philips",
  "swversion": "1.0",
  "uniqueid": "WA0001",
  "recycle": true
}

Tried with homebridge-hue 0.11.20 and now downgraded to 0.11.19 with same results.
deCONZ - 2.05.59 & 2.05.60 same result.
Also double checked username exists in deCONZ config, tried to use different ones with same result.

BR Dalius

**Comment by zladukas** [comment]
also found how to make DEBUG output,  it looks like, that port 8080 is lost in the middle:

pi@ddpi:~/deconz $ DEBUG=*  ph -H 11.40.148.17:8080 -u 194584BDF7 get /sensors/4
  OptionParser0 constructor({"chalk":false,"debug":false,"program":true,"timestamp":false}, false) +0ms
  OptionParser0 boolKey("chalk") +11ms
  OptionParser0 boolKey("debug") +1ms
  OptionParser0 boolKey("program") +1ms
  OptionParser0 boolKey("timestamp") +0ms
  OptionParser0 enumKey("mode") +1ms
  OptionParser0 enumKeyValue("mode", "command") +1ms
  OptionParser0 enumKeyValue("mode", "daemon") +1ms
  OptionParser0 enumKeyValue("mode", "service") +0ms
  OptionParser0 parse({"mode":"command","debug":false}) +1ms
  OptionParser0 parse() => {"chalk":false,"debug":false,"program":true,"timestamp":false} +2ms
  CommandLineParser0 constructor() +0ms
  CommandLineParser0 flag("h", "help") +2ms
  CommandLineParser0 flag("V", "version") +1ms
  CommandLineParser0 option("H", "host") +2ms
  CommandLineParser0 flag("p", "phoscon") +1ms
  CommandLineParser0 flag("s", "https") +0ms
  CommandLineParser0 option("t", "timeout") +1ms
  CommandLineParser0 option("u", "username") +1ms
  CommandLineParser0 parameter("command") +1ms
  CommandLineParser0 remaining() +1ms
  CommandLineParser0 parse(["-H","11.40.148.17:8080","-u","194584BDF7","get","/sensors/4"]) +2ms
  CommandLineParser0 parse() => option: -H 11.40.148.17:8080 +1ms
  CommandLineParser0 parse() => option: -u 194584BDF7 +2ms
  CommandLineParser0 parse() => parameter command: get +1ms
  CommandLineParser0 parse() => remaining: ["/sensors/4"] +1ms
  HueClient1 constructor({"host":"11.40.148.17:8080","username":"194584BDF7"}) +0ms
  **OptionParser1 constructor({"hostname":"localhost","port":80,"timeout":5}, false) +0ms**
  OptionParser1 stringKey("bridgeid", true) +1ms
  OptionParser1 hostKey("host", "hostname", "port") +1ms
  OptionParser1 stringKey("fingerprint", true) +1ms
  OptionParser1 boolKey("phoscon") +0ms
  OptionParser1 stringKey("username", true) +1ms
  OptionParser1 intKey("timeout", 1, 60) +1ms
  OptionParser1 parse({"host":"11.40.148.17:8080","username":"194584BDF7"}) +0ms
  OptionParser1 parse() => {"hostname":"11.40.148.17","port":"8080","timeout":5,"username":"194584BDF7"} +1ms
  HueClient1 constructor() => {"hostname":"11.40.148.17","port":"8080","timeout":5,"username":"194584BDF7","url":"http://11.40.148.17"} +9ms
  HueClient1 connect() +1ms
  HueClient1 getConfig() +1ms
  HueClient1 get("/config") +2ms
  **HueClient1 request({"method":"GET","url":"http://11.40.148.17/api/config","headers":**{"Connection":"keep-alive"},"timeout":5000,"json":true}) +3ms
  HueClient1 request({"method":"GET","url":"http://11.40.148.17/api/config","headers":{"Connection":"keep-alive"},"timeout":5000,"json":true}) => {"statusCode":404,"body":"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /api/config was not found on this server.</p>\n<hr>\n<address>Apache/2.4.25 (Raspbian) Server at 11.40.148.17 Port 80</address>\n</body></html>\n","headers":{"date":"Tue, 09 Apr 2019 17:17:29 GMT","server":"Apache/2.4.25 (Raspbian)","content-length":"288","keep-alive":"timeout=5, max=100","connection":"Keep-Alive","content-type":"text/html; charset=iso-8859-1"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"11.40.148.17","port":80,"hostname":"11.40.148.17","hash":null,"search":null,"query":null,"pathname":"/api/config","path":"/api/config","href":"http://11.40.148.17/api/config"},"method":"GET","headers":{"Connection":"keep-alive","accept":"application/json"}}} +75ms
ph: error: 11.40.148.17:8080: http status 404
ph: error: 11.40.148.17:8080: not a Hue bridge nor deCONZ gateway

**Comment by ebaauw** [comment]
Thanks, the DEBUG=* is very useful.

Indeed the port is lost.  I've just released homebrdige-hue-utils@2.0.15 to fix it.  If you re-install homebridge-hue, the new version of homebridge-hue-utils should be used.

**Comment by zladukas** [comment]
Thanks, 
problem is solved.

Many thanks!
