### ISSUE TITLE
Access through the internet / not in LAN

### ISSUE THREAD

**Issue by ottelo9** [ebaauw/homebridge-hue#458]
I use the Deconz/Phoscon + Homebridge ready 2 use image from the Phoscon webpage. I connect my iPhone with homebridge and everything works great. But how can I use HomeKit outside my LAN via Internet? I can’t find any issue about that...  thanks.

**Comment by ebaauw** [comment]
You need to setup a HomeKit hub, see https://support.apple.com/en-us/HT207057.
