### ISSUE TITLE
Remove Device Virtuell Hue Bridge?

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#459]
Hello Erik,

after the Virtual Hue Bridge created by your plugin has no function in Homekit, can you tell me  it is possible to completely remove the virtual device Hue Bridge in Homekit? 

![2BBBF64C-55DE-43E8-8FDE-5BA04FCA79FC](https://user-images.githubusercontent.com/27686185/56679099-915e2480-66c4-11e9-9e74-9f0fdd8ec1bb.jpeg)

Thank You!

Greeting Nastra

**Comment by ebaauw** [comment]
No, it's not, as it does have a function.  See #76.

**Comment by Nastras** [comment]
Alright, thanks for the very fast feedback!
