### ISSUE TITLE
bridge communication error UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by degofedal** [ebaauw/homebridge-hue#461]
Hi,

I'm running Homebridge in a Docker container on my Synology NAS and have deconz up and running also in a Docker container via a ConBee II USB stick.

I have a Hue Bridge v2 which I wan't to exclude and thus only deconz in Homebridge.

#### Issue
I'm getting the error "bridge communication error UNABLE_TO_VERIFY_LEAF_SIGNATURE" in the homebridge log.

#### Log Messages

```
[4/25/2019, 12:38:57 PM] [Hue] 192.***.***.99: bridge request 1: get /config
[4/25/2019, 12:38:57 PM] [Hue] 192.***.***.99: bridge communication error UNABLE_TO_VERIFY_LEAF_SIGNATURE on 192.***.***.99
```

#### Config.json
```
        {
            "platform": "Hue",
            "host": "192.168.0.99",
            "user": {
                "00212EFFFFXXXXXX": "BA40XXXXXX"
            },
            "nativeHomeKit": true,
            "sensors": false,
            "nativeHomeKitSensors": true,
            "lowBattery": 25,
            "lights": false,
            "nativeHomeKitLights": true,
            "wallSwitch": false,
            "groups": false,
            "group0": false,
            "rooms": false,
            "schedules": false,
            "rules": false,
            "heartrate": 5,
            "timeout": 5,
            "resource": true,
            "parallelRequests": 10,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20
        }
```
I can't seems to finde any prior issues online similar to this. 

Any help will be greatly appreciated.

Thanks in advance
Jeppe

**Comment by ebaauw** [comment]
I haven’t seen that error before, but it looks like something related to https or ssl, neither of which is used by deCONZ.  Are you sure 192.168.0.99 is the container’s ip address?  Are you sure deCONZ is running on port 80?  What do you see in your web browser when you open `http://192.168.0.99/`?

**Comment by degofedal** [comment]
@ebaauw Thanks for taking the time to respond. Incredible work you're doing by the way.

The issue seems be related to https. I had all http traffic redirected to https within the Synology DSM (OS). I deactivated https rule and added the port to config.json:
```
            "platform": "Hue",
            "host": "192.168.0.99:99",
```
Now I see a ConBee device in the Home App with a "Home" icon. I haven't seen that before. Seems like it I working! 

![IMG_1965](https://user-images.githubusercontent.com/3520690/56759894-457daf00-679a-11e9-91d5-6f550c0155ec.PNG)
