### ISSUE TITLE
Eve history - bug?

### ISSUE THREAD

**Issue by netRunner0** [ebaauw/homebridge-hue#463]
![IMG_0079](https://user-images.githubusercontent.com/44049295/56913563-695b3080-6acb-11e9-8002-c3f1b739fa74.jpeg)

This problem occurred with only one sensor. Before adding a problem does not solve

**Comment by ebaauw** [comment]
Most likely the time for the history entries is out of sync.  Eve won’t show future history.

To remedy:
- Lookup the mac address of the sensor (serial number in Homebridge or `uniqueid` in the Hue bridge API.
- Shutdown homebridge;
- Delete `~/.homebridge/accessories/history_`_macaddress_`.json`;
- Restart homebridge.

**Comment by netRunner0** [comment]
fixed! Thanks!
