### ISSUE TITLE
FOHSWITCH is "unsupported"; I tried to support it, but not working yet.

### ISSUE THREAD

**Issue by Ulmo** [ebaauw/homebridge-hue#466]
#### Issue

FOHSWITCH is "unsupported"; I tried to support it, but not working yet.

Here is some of the work I've already done:

Here's some buttonevents numbers for this switch:

[buttonevents-bed-switch-share.gz](https://github.com/ebaauw/homebridge-hue/files/3144717/buttonevents-bed-switch-share.gz)

As you can partially see, the above switch is a four button switch, but I've taken the optional two rockers off and placed the optional one rocker on, so there are only two buttons that I'm programming, thus only the up and down states; you might not notice that there are actually more than two buttons from the above diagnosis as a result.  These switches give out an event for button down and  button up, but it looks like software turns that into a button press without release for a while (a delay sense), and button release, which does cover most of the possible interpretation use cases.  These Zigbee switches give out unique events for all the combinations I've tested on an earlier firmware on a switch bought before Philips had implemented the FOH program fully:  each of press and release for:  each possible combination of buttons pressed.  For instance, if I press up left, or up right, or down left, or down right, or up both left and right, or down both left and right, or up left and down right, or dow left and up right, all of those have a unique code.  Now, there is a different brand that sells these same switches but that does not expose the codes for more than one button press at a time; that means when I press both up or both down (or diagonal presses, for that matter), no code is sent, and nothing happens.  As a result, I have 3 of these switches in my home (2 on another "Home" in homekit so you won't see them in my log files here), and 1 of them is programmed properly via hand-coded zigbee event responses in the Hue gateway to turn on both lights when both upper buttons are pressed and all the other obvious combinations (even diagonal!), but since that was not part of the FOH program, that switch doesn't show up as a Homekit accessory exported by the hue bridge, but the other two FOH switches I got do show up as Homekit accessories and are much better supported by Hue & native Homekit, but do not do anything when there are more than one button presses.  Not all progress is improvement.  Anyway, one of those FOH switches is in my personal "Home" that you see in these logs, and I really want to have it control some non-Hue devices, so I need to expose it to homebridge, but homebridge does not yet support it.

Here is how that switch shows up in Home app with homebridge running:

![IMG_0977](https://user-images.githubusercontent.com/224672/57184106-374f2300-6e6b-11e9-891c-06e400e70aa6.jpg)

As you can see, the unsupported device has a Manufacturer of "PhilipsFoH" (which is wrong; it's a different manufacturer; but that's how lying Philips supports it, apparently), and a Model of "FOHSWITCH", which is a total lack of information, since there will be a zillion switch types in FoH, but that's what we have to work with.

I found some code pieces in homebridge-hue that seem like they are templates for support of this type of switch, so I started work on them around April 14:

[HueSensor.js.diff.gz](https://github.com/ebaauw/homebridge-hue/files/3144812/HueSensor.js.diff.gz)

Apparently, Google Node erased those files on April 24, so before I remembered I had TimeMachine running on that host, today I tried to remember a rough version of what I edited and came up with this sort of rough draft of lib/HueSensor.js and copied the case 'ZGPSwitch' in the switch for (this.obj.type) to a new 'FOHSwitch' (which you can see in the above screenshot); you can see I was a little more detailed above on April 14 with that diff file than in this little snippet, but they are conceptually similar; the above diff code was tested and failed, but the below is just conceptual and not as complete (never tested):

```
//===                                                                                                                                                                                               
      } else if (
        this.obj.manufacturername === 'Philips' &&
        this.obj.modelid === 'FOHSWITCH'
      ) {
        // FOH Switch                                                                                                                                                                               
        this.createLabel(Characteristic.ServiceLabelNamespace.ARABIC_NUMERALS)
        this.createButton(1, 'UpDim', SINGLE_LONG)
        this.createButton(2, 'Up', SINGLE)
        this.createButton(3, 'DownDim', SINGLE_LONG)
        this.createButton(4, 'Down', SINGLE)
        this.type = {
          key: 'buttonevent',
          homekitValue: function (v) { return { 16: 1, 20: 2, 17: 3, 21: 4 }[v] },
          homekitAction: function () { return 0 }
//===                                                                                                                                                                                               

```

#### Log Messages

While censoring the log file, I ran across this error message which is about the switch I want supported.  Note that the error message might be slightly different since I started trying to support it.  Edit:  looks like Google erased hours of my work, so no, that code is gone.
```
[4/24/2019, 5:35:24 PM] [Hue] Studio: /sensors/38: warning: unknown ZGPSwitch sensor {"state":{"buttonevent":21,"lastupdated":"2019-04-22T07:48:56"},"swupdate":{"state":"notupdatable","lastinstal\
l":null},"config":{"on":true},"name":"Bed Switch","type":"ZGPSwitch","modelid":"FOHSWITCH","manufacturername":"PhilipsFoH","productname":"Friends of Hue Switch","diversityid":"ded6468f-6b26-4a75-\
9582-f2b52d36a5a3","uniqueid":"00:00:00:00:01:70:xx:xx-xx","capabilities":{"certified":true,"inputs":[{"repeatintervals":[],"events":[{"buttonevent":16,"eventtype":"initial_press"},{"buttonevent"\
:20,"eventtype":"short_release"}]},{"repeatintervals":[],"events":[{"buttonevent":17,"eventtype":"initial_press"},{"buttonevent":21,"eventtype":"short_release"}]},{"repeatintervals":[],"events":[\
{"buttonevent":19,"eventtype":"initial_press"},{"buttonevent":23,"eventtype":"short_release"}]},{"repeatintervals":[],"events":[{"buttonevent":18,"eventtype":"initial_press"},{"buttonevent":22,"e\
venttype":"short_release"}]}]}}
[4/24/2019, 5:35:24 PM] [Hue] Studio: /sensors/38: warning: unknown ZGPSwitch sensor {"state":{"buttonevent":21,"lastupdated":"2019-04-22T07:48:56"},"swupdate":{"state":"notupdatable","lastinstal\
l":null},"config":{"on":true},"name":"Bed Switch","type":"ZGPSwitch","modelid":"FOHSWITCH","manufacturername":"PhilipsFoH","productname":"Friends of Hue Switch","diversityid":"ded6468f-6b26-4a75-\
9582-f2b52d36a5a3","uniqueid":"00:00:00:00:01:70:xx:xx-xx","capabilities":{"certified":true,"inputs":[{"repeatintervals":[],"events":[{"buttonevent":16,"eventtype":"initial_press"},{"buttonevent"\
:20,"eventtype":"short_release"}]},{"repeatintervals":[],"events":[{"buttonevent":17,"eventtype":"initial_press"},{"buttonevent":21,"eventtype":"short_release"}]},{"repeatintervals":[],"events":[\
{"buttonevent":19,"eventtype":"initial_press"},{"buttonevent":23,"eventtype":"short_release"}]},{"repeatintervals":[],"events":[{"buttonevent":18,"eventtype":"initial_press"},{"buttonevent":22,"e\
venttype":"short_release"}]}]}}
```

#### Debug Files

[2019-04-24T173522-0700-censored.log.gz](https://github.com/ebaauw/homebridge-hue/files/3144715/2019-04-24T173522-0700-censored.log.gz)

[homebridge-hue-censored.json.gz](https://github.com/ebaauw/homebridge-hue/files/3144706/homebridge-hue-censored.json.gz)

**Comment by Ulmo** [comment]
While in the shower, I remembered I have TimeMachine, and actually tried it.  Wow!  I haven't used TimeMachine to restore a particular file state before (other than a full upgrade once when I restored the whole thing).  This is great!  I was able to confirm that yes, indeed, I did edit the file, and there is my work, all preserved, before it got overwritten on April 24th for some reason that I can't fathom.  I wonder how that happened?  Anyway, here is the little bit of work I did, which did not reveal the switch in Home (for automations) when I last tested it:

[HueSensor.js.diff.gz](https://github.com/ebaauw/homebridge-hue/files/3144806/HueSensor.js.diff.gz)

I will now try to edit my initial issue post to work this in there and remove my complains about stupid Google.

**Comment by Ulmo** [comment]
Does anybody have any pointers on how to press forward with making this work?  When I last tried, this would not work.  Let me re-run Homebridge to see how it behaves now with those April 14 edits:

Ok, I remember this failure:  I now get the switch showing up with 8 buttons, each with a Single Press and Long Press code.  Progress!  But, when I Add functions in Home app to these buttons, none of them do anything; whenever I press the switch, nothing I assign to those buttons works.  Have I done something wrong?  What's the best way to diagnose that?

For instance, I'm going to add a level of 77ºF to my thermostat to the #1 button and #5 button for Single Press and see if that does anything.

I see in the log file this:
```
[5/4/2019, 1:54:53 PM] Homebridge is running on port 55224.
[5/4/2019, 1:59:11 PM] [Hue] Studio Ceiling Front: set homekit on from 0 to 1
[5/4/2019, 1:59:11 PM] [Hue] Studio Ceiling Front: set homekit brightness from 57% to 100%
[5/4/2019, 1:59:11 PM] [Hue] Studio Ceiling Front: set homekit hue from 37˚ to 39˚
[5/4/2019, 1:59:11 PM] [Hue] Studio Ceiling Front: set homekit saturation from 67% to 53%
[5/4/2019, 1:59:11 PM] [Hue] Studio Ceiling Front: set homekit color temperature from 443 mired to 367 mired
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 1: set homekit on from 0 to 1
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 1: set homekit brightness from 57% to 100%
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 1: set homekit hue from 37˚ to 39˚
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 1: set homekit saturation from 67% to 53%
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 1: set homekit color temperature from 443 mired to 367 mired
[5/4/2019, 1:59:11 PM] [Hue] Studio Desk: set homekit on from 0 to 1
[5/4/2019, 1:59:11 PM] [Hue] Studio Desk: set homekit brightness from 57% to 100%
[5/4/2019, 1:59:11 PM] [Hue] Studio Desk: set homekit hue from 37˚ to 39˚
[5/4/2019, 1:59:11 PM] [Hue] Studio Desk: set homekit saturation from 67% to 53%
[5/4/2019, 1:59:11 PM] [Hue] Studio Desk: set homekit color temperature from 443 mired to 367 mired
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 2: set homekit on from 0 to 1
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 2: set homekit hue from 176˚ to 39˚
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 2: set homekit saturation from 3% to 53%
[5/4/2019, 1:59:11 PM] [Hue] Closet bulb 2: set homekit color temperature from 156 mired to 367 mired
[5/4/2019, 1:59:13 PM] [Hue] Closet bulb 2: set homekit color temperature from 367 mired to 366 mired
[5/4/2019, 1:59:15 PM] [Hue] Closet bulb 1: set homekit color temperature from 367 mired to 366 mired
[5/4/2019, 1:59:15 PM] [Hue] Studio Desk: set homekit color temperature from 367 mired to 366 mired
[5/4/2019, 1:59:17 PM] [Hue] Studio Ceiling Front: set homekit color temperature from 367 mired to 366 mired
```
But what I don't see is anything to do with the Thermostat.  The Thermostat is still set at 74ºF, not 77ºF.  The Hue Bridge seems to get the configured switch to turn on the configured lights, but the Homekit reaction doesn't pick that button up at all; all you see in the above log file is the output of the Hue Bridge turning on lights, nothing to do with the switch press.

**Comment by ebaauw** [comment]
> As you can see, the unsupported device has a Manufacturer of "PhilipsFoH" (which is wrong; it's a different manufacturer; but that's how lying Philips supports it, apparently), and a Model of "FOHSWITCH", which is a total lack of information, since there will be a zillion switch types in FoH, but that's what we have to work with.

These switches use the ZigBee Green Power (ZGP) protocol, which uses very minimal messages to deal with the very limited energy harvested from the button presses.  The protocol doesn't support the reporting of `modelid`, `manufacturername`, `swversion`, or even a full mac address.

> While censoring the log file, I ran across this error message

That's for me to see what the resource looks like.  The message got mangled somehow.  Could you please attach the debug dump file (see README)?

Could you post a (series of) screenshot(s) what the switch looks like in HomeKit when exposed natively by the Hue bridge?

I don't think we can support _Long Press_ for these reliably, when connected to the Hue bridge.  It just reports press and release for each button (and button pair), irrespective of how long the button(s) was (were) pressed.  As the hue bridge doesn't provide push notifications, homebridge-hue needs to poll it.  The press event is often missed and best ignored, using only the release event to issue a _Short Press_.

Supporting these switches in homebridge-hue will be a bit more work, as deCONZ exposes these using regular `buttonevent` values (x000, x001, x002, x003) instead of the ZGP command codes.  See https://github.com/dresden-elektronik/deconz-rest-plugin/commit/5a3767b7c3d6802d619368a63b5f856549d7a1e0.

**Comment by ebaauw** [comment]
Would you be able to try the above commit?  Or is it easier if I publish a beta version?

**Comment by Ulmo** [comment]
> Would you be able to try the above commit? Or is it easier if I publish a beta version?

Thank you!  I will try that immediately, and work through your other queries over the next hour.

**Comment by Ulmo** [comment]
Ok, I ran Homebridge with that patch applied, and I'm getting the following results:

1.  I do not see any log entries particular to this the way I run homebridge.
2.  When I go into Home app, I get the following:

(I will post screenshots.)

3.  When I set each button to go to 60ºF on the thermostat + the button number (button 1 is 61º, button 2 is 62º, and so on), I get:

Press up on single rocker:  

```
[5/4/2019, 7:24:22 PM] Homebridge is running on port 55224.
[5/4/2019, 7:29:22 PM] [Tesla Powerwall] history
[5/4/2019, 7:31:16 PM] [Hue] Bed Switch Top Left: homekit button single press
[5/4/2019, 7:31:16 PM] [Hue] Studio Ceiling Front: set homekit on from 0 to 1
[5/4/2019, 7:31:16 PM] [Hue] Studio Ceiling Front: set homekit brightness from 100% to 43%
[5/4/2019, 7:31:16 PM] [Hue] Closet bulb 1: set homekit on from 0 to 1
[5/4/2019, 7:31:16 PM] [Hue] Closet bulb 1: set homekit color temperature from 366 mired to 367 mired
[5/4/2019, 7:31:16 PM] [Hue] Studio Desk: set homekit on from 0 to 1
[5/4/2019, 7:31:16 PM] [Hue] Studio Desk: set homekit color temperature from 366 mired to 367 mired
[5/4/2019, 7:31:16 PM] [Hue] Closet bulb 2: set homekit on from 0 to 1
[5/4/2019, 7:31:16 PM] [Hue] Closet bulb 2: set homekit color temperature from 366 mired to 367 mired
[5/4/2019, 7:31:18 PM] [Hue] Studio Desk: set homekit color temperature from 367 mired to 366 mired
[5/4/2019, 7:31:18 PM] [Hue] Closet bulb 2: set homekit color temperature from 367 mired to 366 mired
[5/4/2019, 7:31:20 PM] [Hue] Closet bulb 1: set homekit color temperature from 367 mired to 366 mired
[5/4/2019, 7:31:22 PM] [Hue] Studio Ceiling Front: set homekit brightness from 43% to 100%
```

I call that success!  It says "[5/4/2019, 7:31:16 PM] [Hue] Bed Switch Top Left: homekit button single press
".  And, the Thermostat is set to 61ºF!  That's a Button 1 press!

Now, pressing down:

```
[5/4/2019, 7:32:18 PM] [Hue] Bed Switch Bottom Left: homekit button single press
[5/4/2019, 7:32:18 PM] [Hue] Studio Ceiling Front: set homekit on from 1 to 0
[5/4/2019, 7:32:18 PM] [Hue] Closet bulb 1: set homekit on from 1 to 0
[5/4/2019, 7:32:18 PM] [Hue] Studio Desk: set homekit on from 1 to 0
[5/4/2019, 7:32:18 PM] [Hue] Closet bulb 2: set homekit on from 1 to 0
[5/4/2019, 7:32:18 PM] [Hue] Closet bulb 2: set homekit brightness from 100% to 71%
[5/4/2019, 7:32:24 PM] [Hue] Closet bulb 2: set homekit brightness from 71% to 100%
```
And the Thermostat is set to 62ºF.

Now, I'm going to disassemble the switch and put on the double rocker setup to test the other functions of the switch for completeness and testing:  (I will post this draft message now)

**Comment by Ulmo** [comment]
The original reason I wanted to program this switch, having it turn on and off the thermostat display and my desktop computer display, are now working as they originally were before I started using homebridge.  (Now, when I go to bed, a single switch turns all lights off.)  Great!

**Comment by Ulmo** [comment]
I'm curious what other buttonevents could be shown; I'm going to look them up.

**Comment by Ulmo** [comment]
> > As you can see, the unsupported device has a Manufacturer of "PhilipsFoH" (which is wrong; it's a different manufacturer; but that's how lying Philips supports it, apparently), and a Model of "FOHSWITCH", which is a total lack of information, since there will be a zillion switch types in FoH, but that's what we have to work with.
> 
> These switches use the ZigBee Green Power (ZGP) protocol, which uses very minimal messages to deal with the very limited energy harvested from the button presses. The protocol doesn't support the reporting of `modelid`, `manufacturername`, `swversion`, or even a full mac address.

Ok, that's great.

> > While censoring the log file, I ran across this error message
> 
> That's for me to see what the resource looks like. The message got mangled somehow. Could you please attach the debug dump file (see README)?

Here's the latest dump:

[homebridge-hue-public.json.gz](https://github.com/ebaauw/homebridge-hue/files/3145108/homebridge-hue-public.json.gz)

> 
> Could you post a (series of) screenshot(s) what the switch looks like in HomeKit when exposed natively by the Hue bridge?

Done, in post above.

> I don't think we can support _Long Press_ for these reliably, when connected to the Hue bridge. It just reports press and release for each button (and button pair), irrespective of how long the button(s) was (were) pressed. As the hue bridge doesn't provide push notifications, homebridge-hue needs to poll it. The press event is often missed and best ignored, using only the release event to issue a _Short Press_.

Ok.

> Supporting these switches in homebridge-hue will be a bit more work, as deCONZ exposes these using regular `buttonevent` values (x000, x001, x002, x003) instead of the ZGP command codes. See [dresden-elektronik/deconz-rest-plugin@5a3767b](https://github.com/dresden-elektronik/deconz-rest-plugin/commit/5a3767b7c3d6802d619368a63b5f856549d7a1e0).

Nice reference.  Those press and release events match what I reported above.

**Comment by Ulmo** [comment]
https://github.com/ebaauw/homebridge-hue/commit/81d00a39dc2540dacb04b12528b2e017518b331d solves my issue.  Thank you!!!

**Comment by ebaauw** [comment]
The `buttonevent` values that the Hue bridge shows are the raw ZGP commands that the switch sends.  These are hard-coded in the switch’s firmware.  The Hue bridge configures all lights (that support ZGP - all Hue lights do) to forward the ZGP message to the Hue bridge.

When receiving a (forwarded) ZGP message, the Hue bridge sets the `state` attributes (`buttonevent` and `lastupdated`).  These can be used to trigger rules on the Hue bridge, e.g. to toggle a light or recall a scene (typically, the Hue app will create these for you).

Unfortunately, there’s no way for homebridge-hue (or any other Hue API client) to know the state change, other than continuously asking the state (polling).  I find I can do this reliably at most once every two seconds on a second generation (square) Hue bridge.  This means that only the last state change of every 2s interval is visible to homebridge-hue:
- If you were to press a button 0.1s before homebridge-hue queries the bridge, and release it 0.2s later, homebridge-would see a press, and, two seconds later, a release.
- If you were to press the button 0.1s after a poll, and release it 0.2s later, homebridge-hue would only see a release, 1.7s later.  Same action, but different events visible to the API client.
- If you were to press a button 0.1s after a poll, and release it 3.8s later (just before the third poll), homebridge-hue would see a press (1.9 seconds later) and, two seconds thereafter, a release.  Different action (long press vs short press), but same events visible to the API client.

The Hue bridge does push state changes to HomeKit, so using the native HomeKit function is more responsive than homebridge-hue, and potentially offers more functionality (hence my question for screenshots _when the switch is exposed natively by the Hue bridge_).  I don’t think they expose pressing two buttons simultaneously, though.

The Hue dimmer switch uses different `buttonevent` values (or rather: sends different messages) for short release vs long release. homebridge-uses this to expose _Short Press_ vs _Long Press_.  Last time I checked, the Hue bridge only exposes _Short Press_.

So you need to weight the added functionality offered by homebridge-hue against the better resposiveness of the Hue bridge.  If you want both, replace your Hue bridge with deCONZ.

Notes to self:
- Support `FOHSwitch` In `excludeSensorTypes`;
- Don’t expose these when `nativeHomeKitSensors` is true.

**Comment by Ulmo** [comment]
> The Hue bridge does push state changes to HomeKit, so using the native HomeKit function is more responsive than homebridge-hue, and potentially offers more functionality (hence my question for screenshots _when the switch is exposed natively by the Hue bridge_). I don’t think they expose pressing two buttons simultaneously, though.

Setting it up natively to show that one switch can take hours, so I'm going to show the same hardware switch model that is installed on my other "Home" with a similar FOH switch that is run natively straight from the Hue hub to HomeKit (no homebridge on that "Home"):

![IMG_0983](https://user-images.githubusercontent.com/224672/57191236-048f4400-6ed8-11e9-85d4-7cc503a54d25.PNG)
![IMG_0984](https://user-images.githubusercontent.com/224672/57191238-06590780-6ed8-11e9-86c3-e0dc8ddf514e.jpg)

Note that there are no "dots" on that switch.  Also note that the screenshot shows no setting for both pressed at the same time, and indeed, the Hue bridge doesn't have an action for any notice of both being pressed at the same time (which I thought might be a problem for me since I often want to press both down to turn both off, but I realized none of the things controlled by that switch need to be non-Hue devices, so I just now manually created 8 new rules on the Hue bridge to allow both buttons to control the Hue lights that switch is for, and I don't need any HomeKit for that).

**Comment by ebaauw** [comment]
Thanks!

> Note that there are no "dots" on that switch.

Apple's Home app shows either _n_` DOTS` or `BUTTON `_n_; it won't show the button names (shown in the homebridge log).  Other apps (Eve, Matthias' Home) do show the button names.

> the Hue bridge and app doesn't have an action for any notice of both being pressed at the same time (which I thought might be a problem for me since I often want to press both down to turn both off

Yes it would, as no HomeKit event gets triggered when pressing both buttons simultaneously.

> but I realized none of the things controlled by that switch need to be non-Hue devices, so I just now manually created 8 new rules on the Hue bridge to allow both buttons pressed at the same time to control the Hue lights that switch is for, and I don't need any HomeKit for that).

Indeed, Hue bridge rules are preferred over HomeKit automations when you want to control devices connected to the Hue bridge.   Richer functionality, more responsive, and more reliable (no HomeKit hub needed).  On the downside: creating them is less user friendly.

**Comment by mistermog** [comment]
hi guys, i know this is bringing back from the dead but I have a couple of these illumra FOH (part number FOH-DSWH) switches and trying to pair them with a zigbee dongle. It pairs immediately and fine with the hue app/bridge but I dont want to use that. I cant use either the hue pairing method (button 4, then 2+3 simultaneously) or the illumra generic zigbee switch method. (7-2-7 second button press).  Just wondering if anyone might have any info? I am scouring anything I can find and cant seem to find any information on how this might get paired up. I have the dongle side setup fine, and have paired some hue bulbs to it and other switches and stuff and all work perfectly, just these ^*&$*^^)*& switches.

**Comment by ebaauw** [comment]
The button to press for pairing depends on the zigbee channel of the network you want to join.  Maybe Phoscon will guide you through the correct sequence, otherwise you need to set the zigbee channel of the Hue bridge to that of the deCONZ gateway, and check what sequence the Hue app shows for pairing.  Make sure to change the Hue bridge channel back afterwards.

**Comment by mistermog** [comment]
I actually peeled off the sticker on the back of the switch and found the enocean part number for the zigbee module itself. they actually left that on there and just put their sticker on top of it. I found the instructions based on that, all is good finally! I have been fighting this for a week.  :)   Thank you though!
