### ISSUE TITLE
Hue Tap: no button 5/6 in home

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#467]
Hey,

I just installed the latest version.
I have a Hue Tap, but I have no button 5 or 6 ... obly the 4 standard ones.

Is there a special config needed?

**Comment by ebaauw** [comment]
The Home app should pick it up, after restarting homebridge.  Are you sure you expose the tap through homebridge-hue, and not natively through the Hue bridge?  If you attach a debug dump file, I can have a look.

**Comment by Phoenix-DH** [comment]
I got no access to the debug at the moment. But to the config ...

As an extract:
            "sensors": true,
            "hueMotionTemperatureHistory": true,
            "nativeHomeKitSensors": false,
            "lights": true,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ]

I can imagine I have to change something?

Oh in the meanwhile I saw the additional values on an other tap which I move to blacklisted because they are double in home ...

**Comment by ebaauw** [comment]
Config looks fine, but doesn't control what the Hue bridge exposes.  If you see double entries in Home, likely one is exposed by homebridge-hue and the other one by the Hue bridge.  The one exposed by homebridge-hue should report _HomeKit Certified_ as _No_ under _Settings_; the one by the Hue bridge doesn't contain _HomeKt Certified_.

**Comment by Phoenix-DH** [comment]
Understood! Thanks!
I will try ...
Also what happens with the double config ...

Great job.
