### ISSUE TITLE
Cam't reinstall

### ISSUE THREAD

**Issue by henkhb** [ebaauw/homebridge-hue#468]
Amy ideas?

npm ERR! Unexpected end of JSON input while parsing near '...Ns8V+L3tEk8U8Un7vCvgi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-06T16_45_26_678Z-debug.log
/homebridge #

**Comment by ebaauw** [comment]
Haven’t seen anything like this before.  What command were you executing?  What versions of NodeJS and npm do you use?  On what platform?  Please attach the logfile.

Do you have any free space left on your disk?

**Comment by henkhb** [comment]
Will post later. 

It seems there is a problem with NPM at the moment. Many homebridges have problems to load the plugins overview in configui. Iam also in contact with onzu about this issue. Your package seems to be affected by this.

**Comment by Krocko** [comment]
Had the same error this morning. 
Yesterday i installed homebridge-hue v.0.11.24. This takes a very long time (10min+). 
This morning I updated an other homebridge plugin a got this error to. 
 `sudo npm cache clean --force` solved it for me.

**Comment by henkhb** [comment]
Thanks. This exactly solved the issue for me as well. 

Was relegated to incomplete pulls due to npm server issues. Works fine now. 

Please close
