### ISSUE TITLE
Cannot connect to bridge

### ISSUE THREAD

**Issue by gcappucc** [ebaauw/homebridge-hue#469]
Hi. This is the first time I setup home bridge and home bridge-hue. I hope I am not making some gross mistake.

I am having problems with connecting to the hue bridge after starting homebridge.
I read the other related issues. I have tried to set the host IP manually but that didn't help.

This is the error message I get when starting home bridge:
192.***.***.42: bridge request 1: get /config
192.***.***.42: bridge communication error EHOSTUNREACH on 192.***.***.42
192.***.***.42: bridge request 2: get /config
192.***.***.42: bridge communication error EHOSTUNREACH on 192.***.***.42

This is my config.json:
{
"bridge":{
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is a test configuration file.",
    "accessories": [ ],
    "platforms": [
    {
      "platform": "Hue",
      "host":"192.168.1.42",
      "users": {
        "ECB5FAFFFE090F53": "xxxxxxxxxxxxxxxxxxxx"
      },
      "lights": true
    }
  ]
}

Hue bridge seems to be discoverable. if I execute ph discover -v I get the following:
{
  "deconz4": {},
  "deconz6": {},
  "meethue": {
    "192.168.1.42": "ECB5FAFFFE090F53"
  },
  "upnp": {}
}

Not sure what to do.

**Comment by gcappucc** [comment]
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/3150752/homebridge.log)

**Comment by ebaauw** [comment]
Looks like the bridge is powered off, or no longer connected to your network - it doesn’t respond to UPnP either.  The entry in the meethue portal tends to remain for a couple of hours, after the bridge is turned off.

**Comment by gcappucc** [comment]
I am not sure if that the case.
The bridge is reachable via Philips app and I can control the lights.

**Comment by gcappucc** [comment]
Is there a specific setting for upnp that I might have missed? (forgive me the silliness of the question)

**Comment by h0lz** [comment]
Maybe a connection via „cloud“? ![Image](https://i.imgur.com/6eXFBAm.jpg)
Had a similar issue after my dhcp decided to change the IP of the hue bridge. ¯\_(ツ)_/¯

**Comment by ebaauw** [comment]
Connecting to the Hue bridge through the cloud is done through a different API and has severe limitations on the request rate and responsiveness.  It doesn’t make sense for homebridge-hue do support that, also since both homebridge and the Hue bridge run in your home network.

You want the Hue bridge to have a static IP address.  Configure your DHCP server to return a fixed address based on the bridge’s mac address.

**Comment by h0lz** [comment]
My suggestion wasn’t meant as an alternative connection method - I was only sharing my solution for a similar problem. :)

**Comment by ebaauw** [comment]
> The bridge is reachable via Philips app and I can control the lights.
Maybe I should factory reset the bridge and start over...

What IP address does the Hue app report?

> Is there a specific setting for upnp that I might have missed?

No, the Hue bridge should announce itself thru UPnP.  Are you running homebridge on the same network as the Hue bridge?  On what platform?  Did you double-check that the bridge is reachable from the host running homebridge?  Using a VM or a container might break the multicast traffic, unless they’re configured with bridged networking.

**Comment by gcappucc** [comment]
Issue seems to be that Homebridge (RPi) cannot reach bridge.
Mystery is that they are on same network physically attached to the same switch.
I can ping bridge and Homebridge from my laptop. 
So they are up on the network 
I will do some troubleshooting 
Thank you for your help

**Comment by gcappucc** [comment]
Problem solved. Works like a charm.
Thank you for all the help.
