### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by Lestercity** [ebaauw/homebridge-hue#47]
first of all great plugin and thx for all the hard work and effort building/maintaining this. I use homebridge for harmony hub alongside some hue bulbs/hue bridge 2.0 that have homekit build in. Now I just added 2 hue dimmers and I want to add them to homekit through your plugin. I get to the point to add the hue platform and the notification in terminal to push my bridge and then the generated username and password. But when I include those in the config.json alongside the other stuff from heart rate until rules and restart homebridge I get an error message: There was a problem reading your config.json file. SyntaxError: Unexpected token   in JSON at position 262
    at JSON.parse (<anonymous>)

verifying my config.json at jsonlint gives a valid json.

I tried using normal text editor and atom, I'm on Mac.

If you need more files etc. please let me know. Im new to Github so sorry if didn't include things I don't know of. Really would like to use your plugin.

**Comment by Lestercity** [comment]
by the way here is what my config.json looks like:
"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},



	"platforms": [{

			"platform": "HarmonyHub",
			"name": "Living Room Harmony Hub"
		}, {
			"platform": "Hue",
			"name": "Hue",
			"host":   "192.168.178.101",
			"users": {
				"001788FFFExxxxxxx": "mu1w6oAyu87afjyQc1xfGEoohN9E7KLxxxxxxxxx"

			},
			"heartrate": 5,
			"timeout": 5,
			"lights": false,
			"philipslights": false,
			"ct": false,
			"groups": false,
			"group0": true,
			"rooms": false,
			"sensors": false,
			"clipsensors": true,
			"schedules": false,
			"rules": false



		}



	]
}

**Comment by ebaauw** [comment]
> I get an error message: There was a problem reading your config.json file. SyntaxError: Unexpected token   in JSON at position 262 at JSON.parse ()

This error message is issued by homebridge when trying to read config.json, before homebridge-hue (or any other plugin) is initialised.

Visually, your config.json looks fine.  My guess is that somehow it contains an invisible character that is removed when copy/pasting the text to jsonlint.  Try re-creating config.json.

**Comment by Lestercity** [comment]
Thanks so much for your fast respond, really appreciated. I re-created the config.json and now it is running, very happy. One last question, the hue dimmer remote is also visible in my home app but isn't supported and greyed out. Is there a setting I can change to make it useable within the home app?

**Comment by Lestercity** [comment]
oh, about the motion sensor. It is recognized and I can see status from within the Home app. I tried to create a trigger for enabling a specific scene, in my case turn kitchen lights on and switch on an elgato eve energy plug, but it won't activate that scene. Isn't that supported at all, or am I missing something. The same thing works with an out of the box homekit supported motion sensor from Fibaro.

**Comment by ebaauw** [comment]
> the hue dimmer remote is also visible in my home app but isn't supported and greyed out. Is there a setting I can change to make it useable within the home app?

No, there isn't, unfortunately, Home simply doesn't support the Stateful Programmable Switch service.   You'd need to use another HomeKit app, see **Caveats** in the README.

>I tried to create a trigger for enabling a specific scene, in my case turn kitchen lights on and switch on an elgato eve energy plug, but it won't activate that scene. Isn't that supported at all, or am I missing something. 

That should work.  I do find that synchronising the HomeKit database between your iOS devices and AppleTV over iCloud tends to break when making a lot of changes at the same time.  What I do when triggers don't work, is:
- Disable them all on one device, wait like five minutes and check that they show as disabled on all other devices (unfortunately, you cannot check on the AppleTV);
- Reenable them all on one device, wait like five minutes and check that they show as enabled on all other devices.

If that doesn't work: disable iCloud for HomeKit on all your devices (and AppleTV) except one (preferably an iPad which you can setup temporarily as HomeKit Hub).  Make the HomeKit configuration changes on that one device, and check that they work as intended.  Then re-enabled iCould for HomeKit on your other devices, one by one.

**Comment by Lestercity** [comment]
Hi ebaauw. Thanks for all your help. Got the scenes working now, very happy. Would it be possible or do you think homekit will implant, custom notification settings for motion sensor. For example put them off when @home and on when away, or even a schedule for that purpose.

**Comment by ebaauw** [comment]
> Would it be possible or do you think homekit will implant, custom notification settings for motion sensor. For example put them off when @home and on when away, or even a schedule for that purpose.

I'm not privy to any roadmaps from Apple, so your guess is as good as mine.  I didn't get any notifications from the motion sensors before iOS 10.2 (I also tried Apple's HomeKit accessory simulator, so I know it wasn't due to homebridge-hue), so Apple are progressing on HomeKit.

It would seem like the notifications and their settings are part of the Home app, rather than the HomeKit API.  I doubt Apple will make them available to other HomeKit apps.  I think it's a save bet they won't ever be accessible to HomeKit accessories, nor homebridge.
