### ISSUE TITLE
Two bridges 

### ISSUE THREAD

**Issue by mtjoernelund** [ebaauw/homebridge-hue#470]
I have both a Hue v1 bridge and a raspberry pi running deconz. 

I set up the deconz gateway on a separate pi, running a separate instance of Homebridge to play around with without risking breaking my main homebridge instance. This has run nicely, except today I had to restart my main Homebridge which then stalled waiting for me to allow it to pair with the deconz gateway. Once I allowed this in Phoscon it started adding the accessories to my Home so that they now are there twice. 

I guess I can have both bridges connected to the same Homebridge by adding the user/code pair generated like this:
{
            "platform": "Hue",
            "name": "Hue",
            "users": {
                "<uid hue bridge>": "Pass"
                "<uid deconz>": "Pass"
            },

Is this the correct syntax for two bridges?

Can I add anything to the config to avoid my main Hombridge trying to connect to the deconz gateway and just connect to my hue v1 bridge?

**Comment by ebaauw** [comment]
To configure what bridges/gateways homebridge-hue should expose, use the `hosts` key.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.
