### ISSUE TITLE
deCONZ lights lose room assignment and custom names in Homekit after Phoscon GW restart

### ISSUE THREAD

**Issue by robertlandes** [ebaauw/homebridge-hue#471]
#### Issue
I am experiencing a weired behaviour where all subscribed lights (Philips Hue & Ikea Tradfri) are losing their room assignement and custom names in Homekit after the deCONZ services (Phoscon Gateway) are restartet.

**Steps to reproduce:**
- Assign lights to rooms in Homekit
- Rename lights to something different in Homekit
- Restart homebridge -> Everthing OK
- Restart deCONZ / Phoscon gateway services -> Every device from GW is gone in Homekit
- Restart homebridge -> Every light is reassigned to the room, where the gateway device is located in Homekit and names are reset to names from deCONZ. Groups of lights are lost.

This however **DOES NOT** apply to switches (Philips and Ikea) and motion sensors (Philips and Ikea). They are still located in their respective rooms and keep their custom names.

This results in scences and automations beeing lost or left stale (as no services are assigned to them).

**System setup:**
- Platform
  - Raspberyy PI 3 B+
  - Running latest raspian-lite
  - homebridge version: 0.4.49
  - homebridge-hue: v0.11.24

- dresden Conbee II
  - Firmware 26490700
- deCONZ / Phoscon services
  - Version 2.05.64 / 22.4.2019

- Homekit
  - Apple iPhone 8 Plus / iOS 12.2
  - Apple TV 4k running latest tvOS
  - Apps  
    - Apple Home 
    - Eve for Homekit 
    - Controller for Homekit

#### Log Messages

I couldn't identfify any specfice log entries related to this issue. Please see attached files.

#### Debug Files
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/3186231/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3186232/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
> Restart deCONZ / Phoscon gateway services -> Every device from GW is gone in Homekit

I don’t know how this can happen.  Homebridge-hue doesn’t remove devices from HomeKit.  When deCONZ becomes unavailable, homebridge-hue wont’t be able to communicate with any devices, but continues to expose them to HomeKit.  Are you sure homebridge isn’t restarted as well, when restarting deCONZ?  Are you managing homebridge from deCONZ or did you install it yourself?

> Restart homebridge -> Every light is reassigned to the room, where the gateway device is located in Homekit and names are reset to names from deCONZ. Groups of lights are lost.

Basically, HomeKit sees them as new devices, presumably because they were no longer exposed previously.  I do not understand why this doesn’t also happen to the switches and sensors.

**Comment by robertlandes** [comment]
> > Restart deCONZ / Phoscon gateway services -> Every device from GW is gone in Homekit
> 
> I don’t know how this can happen. Homebridge-hue doesn’t remove devices from HomeKit. When deCONZ becomes unavailable, homebridge-hue wont’t be able to communicate with any devices, but continues to expose them to HomeKit. Are you sure homebridge isn’t restarted as well, when restarting deCONZ? Are you managing homebridge from deCONZ or did you install it yourself?
> 
> > Restart homebridge -> Every light is reassigned to the room, where the gateway device is located in Homekit and names are reset to names from deCONZ. Groups of lights are lost.
> 
> Basically, HomeKit sees them as new devices, presumably because they were no longer exposed previously. I do not understand why this doesn’t also happen to the switches and sensors.

As mentioned above, when I just restart homebridge everything is perfectly fine. All devices are shown unavilable or "updating" in Apple Home and are coming back to normal state after hombridge is up again. When I restart deCONZ services (restart is done through Phoscon App > Gateway > Power: Restart Gateway) and all devices are gone in Apple Home app and nothing happens anymore, until I also restart homebridge and it is reconnecting to deCONZ REST Api and Homekit, but then all lights semm to be "new" lights for Homekit. 

Is it maybe possible, that (only) the lights  are getting a new unique identifier exposed to Homekit, so they are seen as if they were new devices?

During restart of deCONZ services, hombridge services keep running. My setup is a custom install (so no original "Phoscon Gateway appliance". It is a RPI 3b+ where I installed homebridge and deCONZ / Phoscon myself based on latest rasbian-lite image.

Is there a way to debug this any further for me, so I can provide you with addional information?
How can I best check if the unique identifier of the lights are changeing during this process?

Thanks,

Robert

P.S.: Thanks btw for your amazing work on this project!

**Comment by ebaauw** [comment]
> When I restart deCONZ services (restart is done through Phoscon App > Gateway > Power: Restart Gateway)

Doesn't that reboot the Pi?

**Comment by robertlandes** [comment]
@ebaauw first of all: Stupid me for assuming something and not confirming it before opening this issue! 

After reading your previous comment regarding restart in Phoscon App actually restarts the Pi, I started investigating in the same direction you mentiuoned in your last post. So I changed homebridge.service to wait for deconz.service at startup. However this did not change the behaviour. 
Just to confirm,  I added a `ExecStartPre=/bin/sleep 30` to homebridge.service to make it wait for 30 seconds after deconz.service is startet and guess what, it fixed it. Not a final solution, but a workaround.

So I can confirm, that deCONZ seems to have reintroduced the behaviour in its latest release. which the guys at dresden fixed in v2.05.37.

I'll have a look at your workaround using lightlist ressourcelink for the time beeing.

I don't no if you able or willing to do something about this on your side, but I guess this needs to be fixed on the right side (deCONZ).

Thanks for your help and I guess this issue is resolved for now.

**Comment by ebaauw** [comment]
I re-introduced `ph lightlist` in homebridge-hue-utils v2.0.19.  That version should be installed when you re-install homebridge-hue (but maybe you need to uninstall it first).  Other than providing a workaround, there’s nothing homebridge-hue can do.

Best open an issue in deCONZ.  It would be helpful to know how long it takes for the resources to re-appear, and if this also happens when you quit deCONZ from the GUI (without rebooting the Pi).

I don’t experience any missing lights myself; maybe it’s related to the ConBee II (haven’t tested with that device).

**Comment by robertlandes** [comment]
I removed my workaround for service delay and used the resourcelinks method you descbribed above. It fixes the issue. The time for deCONZ light resources to be available seems to around 60-70 seconds (or something inbetween your wait intervall after first missing resource)

```
May 16 19:29:22 homebridge homebridge[356]: [5/16/2019, 7:29:22 PM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.64, api v1.16.0
May 16 19:29:23 homebridge homebridge[356]: [5/16/2019, 7:29:23 PM] [Hue] Phoscon-GW: /resourcelinks/1: /lights/1: not available
May 16 19:29:23 homebridge homebridge[356]: [5/16/2019, 7:29:23 PM] [Hue] Phoscon-GW: gateway not yet initialised - wait 1 minute
```
....
```
May 16 19:30:24 homebridge homebridge[356]: #033[0;37m[5/16/2019, 7:30:24 PM] #033[0m#033[0;36m[Config]#033[0m #033[0;31mFailed load accessories from Homebridge: Error: connect ECONNREFUSED 127.0.0.1:51826#033[0m
May 16 19:30:27 homebridge homebridge[356]: #033[0;37m[5/16/2019, 7:30:27 PM] #033[0m#033[0;36m[Config]#033[0m #033[0;31mFailed load accessories from Homebridge: Error: connect ECONNREFUSED 127.0.0.1:51826#033[0m
May 16 19:30:30 homebridge homebridge[356]: [5/16/2019, 7:30:30 PM] [Hue] Phoscon-GW: 39 accessories
May 16 19:30:30 homebridge homebridge[356]: [5/16/2019, 7:30:30 PM] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
May 16 19:30:30 homebridge homebridge[356]: [5/16/2019, 7:30:30 PM] [Hue] Initializing platform accessory 'Phoscon-GW'...
May 16 19:30:30 homebridge homebridge[356]: [5/16/2019, 7:30:30 PM] [Hue] Phoscon-GW: 2 services
```
I'll open an issue with the dresden guys.

**Comment by jensflorian** [comment]
I upgraded deconz yesterday from Version 2.05.72 to Version 2.05.73-beta and observed exactly the same behaviour as described by @robertlandes (just stopping deconz-gui, I did no rebooting of the pi). After starting the new deconz-gui all devices from homebridge-hue were missing so I restarted homebridge-hue (version 0.11.52). Every light is then reassigned to the room, where the gateway device is located in Homekit and names are reset to names from deCONZ. Groups of lights are lost. Sensors and switches however are correctly reassigned to their former rooms.

Does this mean, that the bug still persists in deconz 2.05.73-beta? How can I verify that all resource links have reappeared so I in future updates I will be able to check this before re-starting homebridge-hue?

**Comment by ebaauw** [comment]
Indeed deCONZ v2.05.73 seems to take quite some time to display the nodes after starting, during which the `/lights` resources aren’t available over the API.  If homebridge is (re)started during this time, homebridge-hue won’t expose the missing lights, and HomeKit will remove them.

Create a “lightlist” resourcelink to make homebridge-hue delay the homebridge startup, until all lights in the list are available.  Easiest way to create the resourcelink is through `ph lightlist`.  Make sure to run this when all lights are available.

**Comment by cirrusflyer** [comment]
> Indeed deCONZ v2.05.73 seems to take quite some time to display the nodes after starting, during which the `/lights` resources aren’t available over the API. If homebridge is (re)started during this time, homebridge-hue won’t expose the missing lights, and HomeKit will remove them.
> 
> Create a “lightlist” resourcelink to make homebridge-hue delay the homebridge startup, until all lights in the list are available. Easiest way to create the resourcelink is through `ph lightlist`. Make sure to run this when all lights are available.

Sorry, but can you elaborate on how to create this resourcelink?  I'm also seeing this issue after restarts.

**Comment by ebaauw** [comment]
Type `ph lightlist` in the terminal, or use the API to create it.  See https://github.com/ebaauw/homebridge-hue#configuration and https://developers.meethue.com/develop/hue-api/9-resourcelinks-api/.  They’re still missing from the deCONZ API documentation.

**Comment by plantoschka** [comment]
I have the same issue which is very annoying.
Where do I run the ph lightlist command? I use homebridge in a docker container and inside the container the command is unknown:
```
/homebridge # ph lightlist
sh: ph: not found
```

**Comment by ebaauw** [comment]
It is installed with Homebridge Hue.  I don’t know about docker.

**Comment by plantoschka** [comment]
I use this container: https://github.com/oznu/docker-homebridge

I can see ph.js inside /homebridge/node_modules/homebridge-hue/cli

But when I execute it with ./ph.js lightlist i get the following error
```
ph.js: error: 127.0.0.1:80: cannot connect: ECONNREFUSED
ph.js: fatal: localhost: not a Hue bridge nor deCONZ gateway
```

**Comment by ebaauw** [comment]
You might need to add `-H x.x.x.x` to specify the ip address of deCONZ.  It might bitch about a missing username; unlock the gateway from Phoscon or the web app and run `ph -H x.x.x.x createuser` to generate one.

**Comment by plantoschka** [comment]
Ok managed to do it trough by running
./ph.js -H 172.30.33.8:40850 createuser (unlock the gateway before that)
./ph.js -H 172.30.33.8:40850 lightlist

Lightlist did not generate a response. Can I check if everything worked out fine?

**Comment by ebaauw** [comment]
If you do `lightlist -v` it will list the resourcelink it has created/updated.  Also, Homebridge Hue will issue a debug message when starting Homebridge with `-D`.

**Comment by fjs21** [comment]
Any idea how to do this on a Windows install of home ridge?

**Comment by ebaauw** [comment]
Sorry, no.  I don’t use Windows.  The `ph.js` is in the `cli` folder of `homebridge-hue`.  I have no idea where that is on Windows.

**Comment by Galiwyx** [comment]
> 
> 
> Type `ph lightlist` in the terminal, or use the API to create it. See https://github.com/ebaauw/homebridge-hue#configuration and https://developers.meethue.com/develop/hue-api/9-resourcelinks-api/. Resourcelinks are still missing from the deCONZ API documentation.

I'm trying to do the lightlist but in terminal I have this error : 
``
pi@homebridge:~ $ ph lightlist
ph: error: get /config: http status 404 Not Found
ph: fatal: localhost: not a Hue bridge nor deCONZ gateway
``

I use a raspberry Pi, Homebridge 1.1.0 and deConz 2.05.77

**Comment by ebaauw** [comment]
Run `ph -H localhost:4530 lightlist` or do an `export PH_HOST=localhost:4530`.

**Comment by Galiwyx** [comment]
Thank you @ebaauw, the first command returns : `
ph: fatal: missing username - unlock gateway and run "ph -H localhost:4530 createuser"
`
The second seems ok, but where can I found the export ?

**Comment by ebaauw** [comment]
> The first configuration between homebridge-hue and deConz already created an user, no ?

That's the username (API key) for Homebridge Hue; `ph` has one for itself.

> The second seems ok, but where can I found the export ?

In the environment, try `env`.  If you put the `export` in your `.profile` or `.bashrc`, it will set the variable on login.

**Comment by Elvys8** [comment]
Hi @ebaauw!
First of all thank you for all your work and support.
I'm also having troubles with custom names and room assignment. We have power outages quite frequently where I live, so I've been experiencing this issue for quite a long time. Following the instructions for creating a lightlist have helped a lot, but I've recently noticed that restarting the router causes the problem too, and unfortunately that's something that also happen frequently. Any ideas on how to prevent this issue from happening? I have a lot of automations and rules on my home that I have to redo every time this happens and it's getting really frustrating…
Thanks in advance.

**Comment by ebaauw** [comment]
Did you specify deCONZ in config.json under `hosts`?  If you use automatic discovery of bridges/gateways, Homebridge Hue is satisfied when it find at least one, unaware that you want to expose another.

**Comment by Elvys8** [comment]
No, in fact I didn't do that. I have a deCONZ USB stick and a Philips Hue bridge.
Would it look like this?

>
     "platforms": [
        {
            "platform": "Hue",
            "host": [
                "192.168.0.22:8080",
                "192.168.0.37"
            ],
            "users": {
                "001788FFFE291D83": "IXNnWE5lXLV2kl7DgTPlqaBRypUMk8jkJKgEQ6ub",
                "00212EFFFF03B2D0": "566BEE3B76"
            },

I use a Synology NAS and Docker containers. I now have an UPS on it, but that doesn't prevent the router restart issue (which to be honest I didn't realise was a problem until I solved the UPS/lightlist part).

**Comment by ebaauw** [comment]
That should work.  Make sure you use fixed IP addresses for the bridge and gateway (hard configured, or assigned by your DHCP server (typically your router) based on Mac address).

**Comment by Elvys8** [comment]
Will do. Thanks a lot!!

**Comment by felker** [comment]
I just encountered this issue: 3x Ikea Tradfri smart plugs each connected to lamps had their HomKit room assignments and automations reset when my device reboots. Also, their room assignments in Homebridge were also lost. 

I am using a Raspberry Pi 3B running Raspberry Pi OS Buster, deCONZ and Homebridge running as services at boot. I use a Conbee II.

@ebaauw 's suggestion seems to have fixed the problem for me. In a terminal:
```
ph createuser
ph lightlist
```

Should I store the returned username for any reason?

**Comment by ebaauw** [comment]
> Should I store the returned username for any reason?

`ph` has already stored it in `~/.ph`.

**Comment by Ghitafjorback** [comment]
I am trying to do the lightlist, but when I run the ph -H x.x.x.x:y lightlist I get the responce:
fatal: missing username - unlock gateway and run "ph -H x.x.x.x:y createuser"
I am not sure how to unlock the gateway, but I tried "authenticate app" in Phoscon web app, I tried searching for lights in the Phoscon web app and I tried "Permit join" in deCONZ.
When I run the "ph -H x.x.x.x:y createuser" I get the responce:
ph createuser: fatal: api error 101: link button not pressed

But what button is that? sorry if this is a stupid question.

**Comment by ebaauw** [comment]
It’s authenticate app in Phoscon.  Issue that first, and run `ph createuser` within 30 seconds.

**Comment by Ghitafjorback** [comment]
I had to try the command 50 times or so even though my gateway was open. I wanted to do it one last time and take a screenshot for you to see, but then it worked. hehe... Thank you @ebaauw once again for your guidance!

**Comment by Elvys8** [comment]
I need help with my lightlist again. One of my innr plugs died and I deleted it in the Phoscon web app.
I updated my lightlist with `ph lightlist` and now I get this message:

`[11/27/2020, 11:08:04 PM] [Hue] Phoscon-GW: /resourcelinks/2: /lights/8: not available`

**Comment by ebaauw** [comment]
Is `/lights/8` indeed the former resource for the dead light?  And is `/resourcelinks/2` the `lightlist` resourcelink?  Or did you also create an `outlet` resourcelink?

**Comment by Elvys8** [comment]
I'm pretty sure `/lights/8 `is the dead plug, but I did do an `outlet` resourcelink.
Looks like I have 3 resourcelinks, not sure what is what tough.

```
get -al /resourcelinks | grep /name:
/1/name:"homebridge-hue"
/2/name:"homebridge-hue"
/3/name:"homebridge-hue"
```

**Comment by ebaauw** [comment]
The type is in the `description` attribute.

**Comment by Elvys8** [comment]
Found the problem. I think I used `ph switch` at some point without knowing what it was supposed to do and created the `/resourcelinks/2`, I updated it and now it's working. Thanks a lot!!

**Comment by simplenotezy** [comment]
@ebaauw how come you keep closing this issue? It's obviously a major fault in the app, whether it be this codebase or a dependency. This library ought to have a big warning sign: "Please be aware that lights will be missing if your server should restart/power cycle for ANY reason and you will have to set up all your scenes again in Homekit"

![image](https://user-images.githubusercontent.com/3786627/108276959-e2cc8300-7178-11eb-97f3-1d008d2550f0.png)

**Comment by jensflorian** [comment]
> This library ought to have a big warning sign

It has, from the main page: 

„Caveats
Homebridge Hue is a hobby project of mine, provided as-is, with no warranty whatsoever. I've been running it successfully at my home for years, but your mileage might vary.“

**Comment by fjs21** [comment]
I "fixed" this problem by just having a separate instance of homebridge with the deconz plugin. This instance is NOT set to startup automatically. After a power cycle (intended or otherwise), I then manually start deconz first and then the homebridge service. This way I don't lose room assignments and automations. Its a pain because I lose functionality until it is restarted but this is less of a hassle then the previous situation of having all room assignments and automations lost. 

While I understand that this may not be fixable at the plugin level, I don't see a reason not to keep the issue open so that other users are aware of this problem and aware of the workarounds.

**Comment by simplenotezy** [comment]
@fjs21 totally agree. Keep the issue open. Who knows, perhaps somebody would fix it.
No need to hide away issues that haven't been fixed IMO.

I am considering alternative options and once I have some time I'll look into other providers - perhaps something different than homebridge if homebridge-hue is the only option for homebridge.

**Comment by simplenotezy** [comment]
> > This library ought to have a big warning sign
> 
> 
> 
> It has, from the main page: 
> 
> 
> 
> „Caveats
> 
> Homebridge Hue is a hobby project of mine, provided as-is, with no warranty whatsoever. I've been running it successfully at my home for years, but your mileage might vary.“
> 
> 
> 
> 

That's a pretty understated warning. Obviously this bug is pretty huge, so that should be stated. Also "might" should be replaced with "will" in the warning, if one were to be completely honest..
