### ISSUE TITLE
Support IKEA trafdri switch ?

### ISSUE THREAD

**Issue by souimanga** [ebaauw/homebridge-hue#473]
#### Issue

Hi, do you think add new switch IKEA trafdri switch ? 
Many thanks 

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Is it supported by deCONZ yet?  Could you please list the resource?

**Comment by souimanga** [comment]
Hello, sorry I would said « plug » 
https://www.ikea.com/fr/fr/p/tradfri-prise-connectee-20364476/
Thks

**Comment by ebaauw** [comment]
Still the same questions apply...

**Comment by souimanga** [comment]
Seems to have issue on deconz 
It would be  use on hue bridge

**Comment by ebaauw** [comment]
OK, but can you then list what the resource on the Hue bridge looks like?  If it's a regular `/lights` resource, homebridge-hue probably already supports it.
