### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by toshibochan** [ebaauw/homebridge-hue#477]
I have this warning:

config.json: warning: philipslights: ignoring unknown key

        "platforms": [{
                "platform": "Hue",
                "name": "Hue",
                "host": "10.0.1.21",
                "users": {
                        "001788..........": "U7nB6rt............"
                },
                "heartrate": 5,
                "timeout": 5,
                "lights": true,
                "philipslights": true,
                "wallSwitch": true,
                "sensors": true

**Comment by ebaauw** [comment]
`philipslights` has been deprecated since Nov 2017, see https://github.com/ebaauw/homebridge-hue/releases/tag/v0.5.43.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration for the supported keys.
