### ISSUE TITLE
Ikea bulbs connected to Philips Hue bridge are not responding after connecting to Ikea remote

### ISSUE THREAD

**Issue by lhamrla-dnanexus** [ebaauw/homebridge-hue#479]
I was using this plugin without any problem until today when I connected Ikea Tradfri remote following this tutorial: https://redsilico.com/blog/ikea-tradri-remote-with-hue-hub

After that, Ikea bulb has stopped responding to Homekit commands.

Is this known (and correct) behavior?

Thanks

**Comment by ebaauw** [comment]
Are the IKEA bulbs still responding in the Hue app?

The Trådfri remote sends commands directly to the lights.  The Hue bridge is unaware of this, until it next polls the lights.  Depending on the number of lights connected to your bridge, it might take up to a minute before the Hue bridge and homebridge-hue the the changed light states.  Unlike the Trådfri hub, which configures attribute reporting so the lights immediately report their new state to the hub.

**Comment by lhamrla-dnanexus** [comment]
No, they are not... They are responding only to the newly added Tradfri remote control. But before I added the remote control, everything works correctly.

**Comment by ebaauw** [comment]
Sounds like the remote didn't join the Hue network, but instead stole the light, and created an ad-hoc network with it.

**Comment by lhamrla-dnanexus** [comment]
And is it possible to connect remote to Hue network instead of this? Maybe the tutorial is creating this ad-hoc network? But theoretically is it possible to connect the Ikea remote to the Hue network?

**Comment by ebaauw** [comment]
In theory (haven't tried this myself) you should be able to join the remote to the Hue network, by touchlinking it to the Hue bridge, as described in step 1.  Apart from the methods described to enable touchlink on the bridge, I think holding the link button also still works.

In step 2, make sure not to reset the remote (causing it again to form a network on its own).  Also make sure the light has already been paired to the Hue network.  Best check that step 1 has succeeded on the first light (reacts to the remote and is still controllable from the Hue bridge), before proceeding with other lights.

**Comment by lhamrla-dnanexus** [comment]
Ok, thank you very much for your help! I'll let you know if this works :)
