### ISSUE TITLE
Feature Request: Disabling Hue Motion Sensors

### ISSUE THREAD

**Issue by pauloruberto** [ebaauw/homebridge-hue#48]
It would be great if there was some way we could get a switch within home kit to enable or disable our hue motion sensors from running entirely.

**Comment by ebaauw** [comment]
Yes it would, and there is: as of v0.1.8 (see issue #9), the `Active` characteristic is mapped to the `on` attribute in the sensor's `config` object.  Setting `Active` to `0` will disable the sensor, setting it to `1` re-enables it.  Unfortunately, the iOS built-in Home app doesn't support this, so you'd need to use another HomeKit app for this, see **Caveats** in the README.
