### ISSUE TITLE
.28 throws errors on the actual docker image

### ISSUE THREAD

**Issue by henkhb** [ebaauw/homebridge-hue#480]
The actual Version is not working on the home bridge docker image. Can not provide more details at the moment. Manual install of homebridge lib helps, but gives other yellow warnings.

https://forum.smartapfel.de/forum/thread/306-homebridge-hue/?pageNo=13

**Comment by ebaauw** [comment]
Not sure which warnings you're referring to:
- NodeJS version: I develop and test agains the latest LTS version of NodeJS.  Other versions usually work, but we've seen some incompatibilities in the past.  Use these at your own risk;
- I don't use docker; I know of it, but cannot help you with the setup;
- With recent firmware, the Hue bridge no longer supports software interaction with the link button.  This functionality has been removed from homebridge-hue, including the corresponding `linkButton` config.json key;
- heartbeat drift warning (from homebride-lib): I found that, depending on NodeJS load, the heartbeat isn't happening every second exactly, and drifts over time (so there's less than 86400 beats per day).  homebridge-lib tries to compensate, by taking into account the drift when scheduling each next heartbeat.  It issues a warning when the delta between scheduled time and actual time is greater than 0.25 seconds (250 milliseconds).  Some drifting during startup of homebridge is to be expected, but values of almost half a minute shouldn't occur.  There's probably another plugin doing synchronous I/O, preventing the heartbeat from happening.
- There's no need to install homebridge-hue nor homebridge-lib with `--unsafe-perm` as they don't contain any C / C++ modules that need to be compiled.
- I sometimes get the EACCESS error on `~/.npm` as well.  Deleting `~/.npm` solves it.

Some more backgound info (I read German, but I don't write it well):
- I'm (slowly) preparing for dynamic platform accessories (which get persisted between homebridge restarts).  This will be based on the generic logic in homebridge-lib.
- I setup homebridge-lib as a peer dependency so a single instance of homebridge-lib can be shared between multiple plugins, very much like homebridge itself.  In particular, using a single heartbeat schedular including a single flush of ~/.homebride/accessories/cachedAccessories.
- homebridge-lib is now a (fake) homebridge plugin, so it can be updated from homebridge-config-ui-x.  It doesn't expose anything, and doesn't need to be included in config.json.  It does need to be loaded however, for plugins that make use of the dynamic accessores (currently homebridge-ws and homebridge-otgw), so make sure to include it when you specify `plugins` in config.json.
- I'm trying to simplify the setup, homebridge-hue-utils is now integrated in homebridge-hue.  Homebridge-hue now creates `bin` symlinks only for the commands it includes (`ph` and `dc_eventlog`); the symlinks for `hap`, `json`, and `upnp` are maintained by homebridge-lib.  `npm` might give some warnings when un/re-installing and/or leave some stale symlinks.

**Comment by henkhb** [comment]
Thanks for your detailed explanation.  Cleaned up and now the only error I get is the 
[homebridge-lib.Lib] warning: heartbeat 1, drift 309 

The issue can be closed. Thanks again!
