### ISSUE TITLE
config.json via homebridge-config-ui-x

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#481]
Hey,

thanks for this great plugin.

With the update to the latest version I have a question.
You wrote that homebridge-lib has to be installed seperat.
I did this, I also did the update to the latest version of homebridge-hue.

Do I have to change something in my config.json after installing this plugin?

I did not restart the bridge until now.

Thank you.

**Comment by ebaauw** [comment]
No change in config.json needed.

**Comment by Phoenix-DH** [comment]
Great... thank you!
