### ISSUE TITLE
0.11.28 update 'requires peer of homebridge-lib@4.2.7'

### ISSUE THREAD

**Issue by Lorccan** [ebaauw/homebridge-hue#483]
#### Issue
Updating homebridge-hue with:
`sudo npm -g i homebridge-hue@latest`
returns:
`npm WARN homebridge-hue@0.11.28 requires a peer of homebridge-lib@~4.2.7 but none is installed. You must install peer dependencies yourself.`

Updating homebridge-lib with:
`sudo npm -g i homebridge-lib`
runs without errors or warnings, but running the homebridge-hue update again (as above) still gives the same error.

homebridge is not generating any errors in the log and all seems to be running OK, but I was trying to follow instructions here: https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0 by running:
`ph outlet -v`

but this gives:
```
ph: error: outlet: unknown command
Usage: ph [-hV] [-H hostname[:port]] [-u username] command [argument ...]
```

**Comment by ebaauw** [comment]
`npm` seems to warn about the peer dependency every time homebridge-hue is installed as only package, regardless whether homebridge-lib has already been installed.  Only when you install both from the same command line, it shuts up.

Haven’t seen the `ph` error before.  Could you please list the output of:
```
$ ls -l $(which ph)
$ ph -h
```

**Comment by Lorccan** [comment]
Thanks Erik

What's the one-line command to install both please?

Outputs:
`lrwxrwxrwx 1 root staff 78 Jul 10  2018 /usr/local/bin/ph -> ../lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/cli/ph.js`

and
```
Command line interface to Philips Hue API.

Usage: ph [-hV] [-H hostname[:port]] [-u username] command [argument ...]

Parameters:
  -h, --help
  Print this help and exit.

  -V, --version
  Print version and exit.

  -H hostname[:port], --host=hostname[:port]
  Connect to hostname:80 or hostname:port instead of the default localhost:80

  -u username, --username=username
  Use username instead of the username saved in ~/.ph.

Commands:
  get [-hsnjuatlkv] [path]
  Retrieve path from bridge/gateway.

  put [-hv] resource [body]
  Update resource on bridge/gateway with body.

  post [-hv] resource [body]
  Create resource on bridge/gateway with body.

  delete [-hv] resource [body]
  Delete resource from bridge/gateway with body.

  discover [-h]
  Discover bridges/gateways.

  config [-h]
  Retrieve bridge/gateway configuration (unauthenticated).

  description [-h]
  Retrieve bridge/gateway description.

  createuser [-h]
  Create bridge/gateway API username.

  unlock [-h]
  Unlock bridge/gateway so new API username can be created.

  touchlink [-h]
  Initiate a touchlink.

  search [-h]
  Initiate a seach for new devices.

  lightlist [-hv]
  Create/update lightlist resourcelink.

  probe [-hv] [-t timeout] light
  Probe light for supported colour (temperature) range.

  restart [-hv]
  Restart deCONZ gateway.

For more help, issue: ph command -h

See https://github.com/ebaauw/homebridge-hue-utils for more info.
(homebridge-hue-utils v1.0.2, node v8.16.0)
```

**Comment by ebaauw** [comment]
> What's the one-line command to install both please?

See https://github.com/ebaauw/homebridge-hue#installation or https://github.com/ebaauw/homebridge-hue/releases.

> lrwxrwxrwx 1 root staff 78 Jul 10 2018 /usr/local/bin/ph -> ../lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/cli/ph.js

You still seem to have an old installation of homebridge-hue in `/usr/local/bin`.  Not sure where the latest version was installed - this depends on your system and how you installed `node` and/or `npm`.  `npm` should create the symlink on installation, but probably hasn't done this, because the old installation, with the old symlinks, hasn't been removed.

**Comment by Lorccan** [comment]
There's been history with this server - so I think that accounts for the old installation. Looking at `/usr/local/bin/' it's just a set of symlinks that are not pointing anywhere useful, so I deleted them, restarted and did a fresh installation of homebridge-hue and homebridge-lib using the one-liner in your link.

All looks OK (to me) now:

```
ls -l $(which ph)
lrwxrwxrwx 1 root root 44 Jun 13 08:32 /usr/bin/ph -> ../lib/node_modules/homebridge-hue/cli/ph.js
```

Thanks again for your help (and for the great software)!

**Comment by Lorccan** [comment]
I do have a follow-up question. I am trying to check for old installations of homebridge-hue, so I decided to execute `npm list -g | grep homebridge`.

I see all other installed homebridge plugins in the output, but homebridge-hue is not listed.

**Comment by ebaauw** [comment]
That would suggest homebridge-hue has been installed somewhere else.  Are you sure you used `-g`?  Are you sure you only have installation of `node` and of `npm`?  Do you see `homebridge` itself?  `homebridge-lib`?

**Comment by Lorccan** [comment]
Sorry for delay in response - I have been away.

I decided to rebuild a new system from scratch and now I've got only one installation of node, npm, and homebridge. All listings are OK and everything is working fine.

Thanks again.
