### ISSUE TITLE
bridge communication error ECONNREFUSED

### ISSUE THREAD

**Issue by patafix18** [ebaauw/homebridge-hue#486]
Hi,
after starting homebridge i always get these two error messages:

[2019-6-19 4:33:52 PM] [Hue] 192.***.***.26: bridge request 1: get /config
[2019-6-19 4:33:52 PM] [Hue] 192.***.***.26: bridge communication error ECONNREFUSED on 192.***.***.26

The two messages loop within bridge request 2,3,... and homebridge don't start.
Is there any fix for it?
Im using Node 10.16.0.

Thanks a lot,
Patrick

**Comment by ebaauw** [comment]
Your ISP probably shares “your” public IP address with other customers, causing homebridge-hue to discover your (internet) neighbour’s bridge.  Disable discovery by setting `”hosts”` in config.json.
