### ISSUE TITLE
Lost Connection after a period of tine

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#489]
After a period of time all hue connected devices get lost in home app.

See screenshot.
Restart of homebridge will fix it.

I cannot see any issues in homebridge log.

![029DC798-3F18-4F0E-966C-944D50219831](https://user-images.githubusercontent.com/44058592/59974988-23928400-95b3-11e9-8fd7-b163d8285560.png)

**Comment by ebaauw** [comment]
This happens when the communication between homebridge and the Home app fails.  There’s nothing homebridge-hue can do about this.

**Comment by Phoenix-DH** [comment]
Oh okay, thank you ...
