### ISSUE TITLE
Homebridge stops working when I edit the config.json for hue

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue#49]
Hi,

I have two plarforms in my config.json: eDomoticz and Nest. Both work perfectly. When I added the hue platform, both stopped working.
I don't know if it is because of node.js version since I see `npm WARN engine homebridge-hue@0.1.12: wanted: {"homebridge":"^0.4.16","node":"^6.9.1"} (current: {"node":"4.5.0","npm":"2.15.9"})` when installing `homebridge-hue` or not.
Here is how my config.json is:
```
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:21:3E:E4:DE:33",
                "port": 51826,
                "pin": "031-45-154"
        },
        "description": "Configuration file for (e)xtended Domoticz platform.",
        "platforms": [{
                        "platform": "eDomoticz",
                        "name": "eDomoticz",
                        "server": "192.168.0.104",
                        "port": "8888",
                        "ssl": 0,
                        "roomid": 0
                }, {
                        "platform": "Nest",
                        "username": "#######",
                        "password": "#######"
                }, {
                        "platform": "Hue",
                        "name": "Hue"
                }

        ],
        "accessories": []
}
```
If you have any idea, I'd be grateful.
Thanks.

**Comment by pponce** [comment]
try removing this line:
"description": "Configuration file for (e)xtended Domoticz platform.",
Doesn't seem like that should be included in the config.json file.

**Comment by ebaauw** [comment]
I develop and test homebridge-hue against node v6.9.2, that's why I put the dependency in package.json.  That doesn't necessarity mean homebridge-hue will break with an older version.

When you say "stopped working" what do you mean?  Do you get any error messages when starting homebridge?  Or has HomeKit dropped homebridge?  The latter happens when homebridge exposes more than 99 accessories, see **Caveats** in the README.  How many accessories did the eDomoticz expose?

**Comment by ooii** [comment]
eDomoticz worked fine with the description before I added Hue. And once I did that, it seems HomeKit dropped homebridge. I think the problem comes from the limit of homebridge: I have more than 60 devices in eDomoticz and more than 20 bulbs which are also exposed by eDomoticz.
I'm going to read the Caveats section.
Thanks.

**Comment by ooii** [comment]
I know that this is not this plugin issue but I have not been able to run two instances of homebridge up to now.
I keep you informed.

**Comment by ebaauw** [comment]
@ooii : any update or can we close this issue?

**Comment by ooii** [comment]
Hi,

Sorry for not giving feedback before, I was busy. I gave a look today and found this error when starting `homebridge` with the `hue plugin`: `ERROR LOADING PLUGIN homebridge-hue: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.16 which does not satisfy the current HomeBridge version of 0.4.6.`
And it seems that homebridge latest version is `0.4.10`. I changed then the `package.json` file of your plugin in order to require `homebridge` starting from version `0.4.6` and I dont' have anymore this error.
Homekit now shows my eDomoticz devices (only 26 actually) but I can't see my Hue devices the `hue` plugin.

**Comment by ebaauw** [comment]
> And it seems that homebridge latest version is 0.4.10.

On GitHub.  If you `npm -g install homebridge` you get 0.4.16.

> I changed then the package.json file of your plugin in order to require homebridge starting from version 0.4.6 and I dont' have anymore this error.

I appreciate that.  I hope you can appreciate that I don't want to change it as I don't have the time to support multiple versions (even when they probably just work).

> I can't see my Hue devices the hue plugin.

Are you still using the config.json from your previous post?  You need to add what resources you want homebridge-hue to expose, see **Configuration** in the README.  You should see a single accessory for the bridge, however (unfortunately not supported by the iOS built-in Home app).  If not, could you please post the output of `homebridge -D`, see **Troubleshooting** in the README.
