### ISSUE TITLE
Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^10.16.0 which does not satisfy the current Node version of v12.4.0. You may need to upgrade your installation of Node.

### ISSUE THREAD

**Issue by Stefan-83** [ebaauw/homebridge-hue#490]
Hi,

I'm getting this error:

> Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^10.16.0 which does not satisfy the current Node version of v12.4.0. You may need to upgrade your installation of Node.

Is my Node version "to new" ?

**Comment by ebaauw** [comment]
Yes: I develop and test my plugins against the latest LTS version of NodeJS (currently 10.16.0).  Use another version at your own risk.  It might work, but I've seen some incompatible changes in the past.

The message is actually issued by homebridge itself.  This is a warning, isn't it?  homebridge is still starting up?

**Comment by Stefan-83** [comment]
Hi ebbauw,
thanks for your quick response.
Yes, the homebridge is starting up and works well.
But the hue-plugin isn't working:

> Jun 23 20:50:54 openHABianPi homebridge[21617]: [6/23/2019, 8:50:54 PM] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^10.16.0 which does not satisfy the current Node version of v12.4.0. You may need to upgrade your installation of Node.
Jun 23 20:50:55 openHABianPi homebridge[21617]: [6/23/2019, 8:50:55 PM] ====================
Jun 23 20:50:55 openHABianPi homebridge[21617]: [6/23/2019, 8:50:55 PM] ERROR LOADING PLUGIN homebridge-hue:
Jun 23 20:50:55 openHABianPi homebridge[21617]: [6/23/2019, 8:50:55 PM] Error: Cannot find module 'homebridge-lib'
Jun 23 20:50:55 openHABianPi homebridge[21617]: Require stack:
Jun 23 20:50:55 openHABianPi homebridge[21617]: - /usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js
Jun 23 20:50:55 openHABianPi homebridge[21617]: - /usr/local/lib/node_modules/homebridge-hue/index.js
Jun 23 20:50:55 openHABianPi homebridge[21617]: - /usr/local/lib/node_modules/homebridge/lib/plugin.js
Jun 23 20:50:55 openHABianPi homebridge[21617]: - /usr/local/lib/node_modules/homebridge/lib/server.js
Jun 23 20:50:55 openHABianPi homebridge[21617]: - /usr/local/lib/node_modules/homebridge/lib/cli.js
Jun 23 20:50:55 openHABianPi homebridge[21617]: - /usr/local/lib/node_modules/homebridge/bin/homebridge
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Module.require (internal/modules/cjs/loader.js:681:19)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at require (internal/modules/cjs/helpers.js:16:16)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:22:23)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Module._compile (internal/modules/cjs/loader.js:774:30)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Module.load (internal/modules/cjs/loader.js:641:32)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
Jun 23 20:50:55 openHABianPi homebridge[21617]:     at Module.require (internal/modules/cjs/loader.js:681:19)

Do I have to "downgrade" to 10.16 ? 
The error-log tells me about "current Node version of v12.4.0"

Thanks

**Comment by ebaauw** [comment]
You need to install homebridge-lib separately, see the release notes.

**Comment by Stefan-83** [comment]
ah perfect. that was the issue. Thank You :)
I've installed the plugin via homebridge-config-ui-x 
Maybe it is possible to integrate the homebrigde-lib as a dependency to avoid that in future.

best regards

**Comment by ebaauw** [comment]
Please upgrade to homebridge-hue@0.11.30, which, once again, includes homebridge-lib as a regular dependency.

**Comment by richierockskool** [comment]
Please take a look at my development, can not get the homebridge to recognize to plugin.

"https://github.com/richierockskool/homebridge-inkbird-wifi-gateway.git"

Thank you
