### ISSUE TITLE
The requested platform 'Hue' was not registered by any plugin.

### ISSUE THREAD

**Issue by hmook** [ebaauw/homebridge-hue#491]
#### Issue

I've recently upgraded Homebridge OZNU on my RaspberryPi3b. Because Homebridge-hue gave an messages that my NodeJS was outdated. I'm now on version node.js v10.16.0. And homebridge won't start again. The log give's me the following message:

#### Log Messages

```
[6/28/2019, 8:23:03 AM] Error: The requested platform 'Hue' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[6/28/2019, 8:23:03 AM] Got SIGTERM, shutting down Homebridge...
```

#### Debug Files

Log file looks empty.

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3338232/homebridge-hue.json.gz)

**Comment by DerPhil1992** [comment]
Same here!

`Jun 28 11:36:17 raspberrypi homebridge[14044]: [6/28/2019, 11:36:17 AM] ====================
Jun 28 11:36:17 raspberrypi homebridge[14044]: [6/28/2019, 11:36:17 AM] ERROR LOADING PLUGIN homebridge-hue:
Jun 28 11:36:17 raspberrypi homebridge[14044]: [6/28/2019, 11:36:17 AM] Error: Cannot find module 'homebridge-lib'
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Module.require (internal/modules/cjs/loader.js:690:17)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at require (internal/modules/cjs/helpers.js:25:18)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:22:23)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jun 28 11:36:17 raspberrypi homebridge[14044]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

**Comment by ebaauw** [comment]
As of v0.11.18, you need to install `homebridge-lib` separately, see https://github.com/ebaauw/homebridge-hue#installation and https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.28.

If you use homebridge-config-ui-x, you can install homebridge-lib through the _Plugins_ page.

**Comment by hmook** [comment]
@ebaauw Thanks! Did an update in the UI so wasn't aware that homebridge-lib needed to be installed separately. Fixed it for me!

**Comment by DerPhil1992** [comment]
Worked for me!!!! Thanks for helping me.

**Comment by ebaauw** [comment]
Please upgrade to homebridge-hue@0.11.30, which, once again, includes homebridge-lib as a regular dependency.
