### ISSUE TITLE
Expose Hue Labs

### ISSUE THREAD

**Issue by AndreaCCIE** [ebaauw/homebridge-hue#494]
It would be nice to be able to trigger labs. Any change this can be achieved?

**Comment by ebaauw** [comment]
How do you normally trigger these?  Afaik Hue labs offers routines for automation, not something to trigger manually?

**Comment by AndreaCCIE** [comment]
Yes those are routines you can trigger from the app itself and are not easily replicable in HomeKit (like color transitions) and not even exposed. It would be nice to have a switch to trigger a lab routine.

**Comment by ebaauw** [comment]
How does the app trigger the routine?  If it’s by setting a CLIPGenericFlag or CLIPGenericStatus, you can tell homebridge-hue to expose these to HomeKit.  The Flag is already exposed as a switch.  The status is exposed as a custom characteristic, but you can create a HomeKit scene (in Eve) to start the routine (by activating the scene from Home).

**Comment by AndreaCCIE** [comment]
Actually I don't know how these routines are invoked by the app. I should dump the phone traffic and give it a look, even if I think everything is encrypted.

**Comment by ebaauw** [comment]
Yes, the Hue app now connects to the Hue bridge over https.  You would have to setup a man in the middle attack to sniff the traffic, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/270#issuecomment-484885323 (third bullet).

Alternatively you could try the following: Dump the full state of the bridge before and after installing the Hue labs routine.  By comparing them, you should be able to derive what rules, scenes and CLIP sensors the routine has created.  They might actually be listed under a resourcelink.  Then setup homebridge-hue to expose the CLIP sensors, run `homebridge -D`, and trigger the routine from the Hue app.  homebridge-hue should log the change to the CLIP sensor.

**Comment by stephanvdplas** [comment]
> Yes those are routines you can trigger from the app itself and are not easily replicable in HomeKit (like color transitions) and not even exposed. It would be nice to have a switch to trigger a lab routine.

The routines are actually not triggered from the app itself, but from a website that is showed via the app: https://labs.meethue.com/ . You need to connect the webpage once per device/browser to the bridge to be able to trigger Formulas.

**Comment by AndreaCCIE** [comment]
So I suppose there's not an easy way to achieve this

**Comment by ebaauw** [comment]
Depends on how the routine gets triggered.  If it’s a regular API call setting a CLIP sensor, it’s a matter of simply configuring homebridge-hue to expose that sensor.  If it’s some magic call available only through the remote API, homebridge-hue cannot help.

**Comment by ebaauw** [comment]
Just dusted off my (gen2) Hue bridge and installed the _Living scenes_ formula from Hue labs.  It installs a `CLIPGenericStatus` sensor _Start and stop_ which it uses to start or stop the formula.
```json
{
  "state": {
    "status": 1,
    "lastupdated": "2019-07-11T20:09:28"
  },
  "config": {
    "on": true,
    "reachable": true
  },
  "name": "Start and stop",
  "type": "CLIPGenericStatus",
  "modelid": "HUELABSVTOGGLE",
  "manufacturername": "Philips",
  "swversion": "2.0",
  "uniqueid": "2:12:b88b-24b8-4e63-a26a",
  "recycle": true
}
```
homebridge-hue already exposes `CLIPGenericStatus` sensors to HomeKit, using a custom _Status_ characteristic.  The formula can be controlled from HomeKit just as easily.  Of course, Home doesn't support custom characteristics, but you can include _Status_ in a HomeKit scene in Eve, and then recall the scene from Home.

By default, homebridge-hue assumes the range -127 to 127 for value values for _Status_.  For CLIP sensors I create myself, I (ab)use `swversion` to indicate the range (e.g. `"-2,3"` for values -2, -1, 0, 1, 2, 3).  Eve then adjusts the slider accordingly.  It looks like this formula only uses values 0 and 1, but I have no clue if that holds for all formulas.

**Comment by CarlAmbroselli** [comment]
I've built the plugin [homebridge-hue-labs-switch](https://github.com/CarlAmbroselli/homebridge-hue-labs-switch) If you want to use simple switches for hue labs formulas.
