### ISSUE TITLE
IKEA Outlet/Switch + Hue hub + homebridge-hue?

### ISSUE THREAD

**Issue by Lorccan** [ebaauw/homebridge-hue#497]
Is it possible to connect an IKEA outlet to a Hue (v2) hub and to expose it via homebridge-hue?

**Comment by ebaauw** [comment]
The IKEA Trådfri smart plug is a Zigbee 3.0 device, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/779#issuecomment-422145141.  The Hue bridge should support it, but I haven’t seen any confirmation of this.  Once connected and supported by the Hue bridge, homebridge-hue will expose it to HomeKit.

**Comment by Lorccan** [comment]
Sorry for delay in getting back to you. I wasn't able to add the plug initially - probably because I was concentrating on doing a TouchLink connection and this frustrated me.

However, today I got help and managed to get the connection working first time. In case anyone else is interested:

1. Ensure outlet has firmware v 2.0.22
2. Remove from the IKEA hub using the IKEA app
3. Hold a pin in the reset hole for > 10s
4. Search for a light in the Hue app and it should show as type On/Off plug (with the same name given to it previously in the IKEA app).
5. Restart homebridge and it appears in the Home app.
