### ISSUE TITLE
Deconz with Hue Light (no dimmer option in Home)

### ISSUE THREAD

**Issue by hmbarbosa** [ebaauw/homebridge-hue#498]
Hi,

Not sure if a issue but recently my Hue Light connected with my Deconz Combee stoped showing the dimmer option... Light still working via home with turn on & off but not dimmer...

Cheers
Berto

**Comment by ebaauw** [comment]
It’s a bug in deCONZ 2.05.66, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1616.

**Comment by hmbarbosa** [comment]
thanks for the reference. this only happen with homebridge... I have HomeAssistant running with Deconz ... and no problem with HomeAssistant the dimmer for my Hue Light are working ok... 

however I like Homebridge for home :) lets see if they can fix this issue.

cheers

**Comment by ebaauw** [comment]
Are you sure?  That would indicate another issue.  The deCONZ bug causes `state.bri` not to be exposed for Hue dimmable lights so there’s no possibility to change their brightness through the REST API.  This affects all API clients, including Phoscon and Home Assistant.  It might still show the control, but the light wouldn’t react to it.

The fix has already been merged.  You can get it today by compiling the REST API plugin, or wait for the next release of deCONZ.
