### ISSUE TITLE
3A Smart Home DE Outlet

### ISSUE THREAD

**Issue by KrtNthny** [ebaauw/homebridge-hue#499]
#### Issue

Hi,

I bought a 3A Smart Home DE power outlet thinking it would work in Homekit when I added it to the Philips Hue Bridge. It does not, so I am trying this Homebridge mod.

This is the config I'm using so far
```
 {
      "platform": "Hue",
      "users": {
        "123abc": "xxxxxxxxxxxxsxxxxxxxxxxxxxxxxxxxxxxxxxx"
      },
      "lights": true
   },
```

In Hue app I called the outlet 'TV' and I have added homebridge-hue to  my Mac.
It shows up when I run home bridge in the log as below.
It doesn't show up anywhere in the Home App. I can't find anything called TV anywhere, not in the default room, no on/off bulb called TV or not outlet called TV. I am stuck.
Im probably missing some important step?

#### Log Messages
```[7/12/2019, 3:23:36 PM] [Hue] Kurts hue bridge: Philips BSB002 bridge v1932126170, api v1.32.0
[7/12/2019, 3:23:36 PM] [Hue] Kurts hue bridge: 2 accessories
[7/12/2019, 3:23:36 PM] [Hue] masked debug info dumped to /Users/kurt/.homebridge/homebridge-hue.json.gz
[7/12/2019, 3:23:36 PM] [Hue] Initializing platform accessory 'Kurts hue bridge'...
[7/12/2019, 3:23:36 PM] [Hue] Kurts hue bridge: 2 services
[7/12/2019, 3:23:36 PM] [Hue] Initializing platform accessory 'TV'...
```

#### Debug Files
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/3385106/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3385098/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Logs look fine to me.  The outlet should be exposed as a light, called _TV_.  Tyically HomeKit places it in the same room as the (HomeKit) bridge, i.c. the homebridge accessory.

HomeKit doesn't like configuration changes, it might take a couple of minutes after restarting homebridge, before all iDevices show the new accessory.

**Comment by KrtNthny** [comment]
Hey. Thanks for the reply. I waited for ages and it didn’t show up anywhere.  I tried removing home ridge and adding it again three times.  I just got home from taking it back to the post office and sent it back for a refund and got an Eve energy outlet.
