### ISSUE TITLE
Synology - can't sync, add user

### ISSUE THREAD

**Issue by jeroen020** [ebaauw/homebridge-hue#500]
#### Issue

Trying to expose Osram Smart+ plugs to Homekit. I've installed homebridge-hue plugin on my Synology, but unlike other plugins can't get homebridge-hue to work. When I go in the config settings I add the IP address of the bridge but it never asks me to push the sync button on the bridge. I understand the config should have a "users" section which is created after homebridge-hue asks to push the button, but no "users" section appears, see below. I've tried pressing the sync button at several moments (before installing the plugin, before restarting Homebridge etc) but to no avail. When I restart homebridge keeps restarting over and over again. I have to remove the homebridge-hue config and restart to get Homebridge back in working order.

Any help is much appreciated, is there a way to manually find out valid content for the "users" section?

#### Log Messages

```
  },
        {
            "name": "Hue slaapkamer",
            "hosts": [
                "192.168.2.169:80"
            ],
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue"
        }
    ]
[7/18/2019, 9:57:34 PM] [DoorBird] Initializing DoorBird platform...
[7/18/2019, 9:57:34 PM] Error: The requested platform 'Hue' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[7/18/2019, 9:57:34 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by ebaauw** [comment]
Did you install homebridge-lib?

**Comment by jeroen020** [comment]
Ah, that was it, rookie mistake. I got it working now, thanks so much!

However one more question if I may - whenever I restart Homebridge, I have to sync my Hue (by pressing the button). Is there any way I can prevent that?

Also it looks like devices from rooms where a homebridge-hue device is present are assigned to 'default room', although I'm not sure if I can reproduce that yet.

**Comment by ebaauw** [comment]
> whenever I restart Homebridge, I have to sync my Hue (by pressing the button). Is there any way I can prevent that?

Yes, save the bridgeid and api key in `config.json`.  See https://github.com/ebaauw/homebridge-hue#installation.

> Also it looks like devices from rooms where a homebridge-hue device is present are assigned to 'default room'.

HomeKit adds bridged accessories to the same room where the HomeKit bridge is located.  That's the accessory for Homebridge itself, not the accessory that homebridge-hue creates for the Hue bridge accessory.

HomeKit rooms are not exposed over the HAP protocol, just like HomeKit scenes, automations, groups.  These can only be managed by HomeKit apps, using the HomeKit API, which is available only on iOS (and now tvOS, watchOS, iPadOS, ...).

The Hue app uses the HomeKit API to sync the rooms between the Hue bridge and HomeKit.  They used to expose a custom characteristic on their lights, so the app would recognise which lights to sync.  homebridge-hue exposes that characteristic for non-Hue lights, so the Hue app would sync these as well.  I'm not sure if the Hue app still works that way (I haven't been using a Hue bridge for a long time), nor if the same trick would also work for sensors (last I used a Hue bridge was before they exposed sensors to HomeKit).

**Comment by ebaauw** [comment]
Please upgrade to homebridge-hue@0.11.30, which, once again, includes homebridge-lib as a regular dependency.

**Comment by jeroen020** [comment]
Only just got around to try to edit the config.json tonight but just wanted to share that following your advice solved my issue, thanks so much! Now the accessories don't show up in the default room after restarting homebridge, so also on that point it's so far, so good.
