### ISSUE TITLE
npm WARN homebridge-hue@0.11.29 requires a peer of homebridge-lib@~4.2.9 but none is installed.

### ISSUE THREAD

**Issue by det-box** [ebaauw/homebridge-hue#501]
Hello, 
Since the homebridge-lib update comes the following error From homebridge-hue: 
![image](https://user-images.githubusercontent.com/8150405/61595160-e9d58d00-abf3-11e9-88a0-a1f4f545193b.png)
![image](https://user-images.githubusercontent.com/8150405/61595168-05409800-abf4-11e9-8081-c7b823372c15.png)
![image](https://user-images.githubusercontent.com/8150405/61595179-17bad180-abf4-11e9-9d2e-fe971b6170f2.png)

with homebridge 0.4.50

Is there anything else to be updated? 
Thanks a lot

**Comment by ebaauw** [comment]
Please upgrade to homebridge-hue@0.11.30, which, once again, includes homebridge-lib as a regular dependency.

**Comment by det-box** [comment]
Thanks, 
everything is OK again.
