### ISSUE TITLE
How to check if homebridge-hue is utilizing the deCONZ websocket?

### ISSUE THREAD

**Issue by fschaefer** [ebaauw/homebridge-hue#502]
deCONZ is started with `/usr/bin/deCONZ -platform minimal --http-port=80`, so I think it uses port 8081 by default. homebridge-hue seems to default to port 443 for websockets.

Is there anything I can check to see if homebridge-hue is using the websocket? Is there an option for the port in the homebridge-hue config or is it automagically discovered?

**Comment by ebaauw** [comment]
The deCONZ REST API exposes the port used for the web socket, so homebridge-hue detects this automatically.  Start `homebridge -D` to see a debug message on startup:
```
Jul 24 10:56:05 pi1 homebridge[15060]: [Hue] pi1: listening on websocket ws://127.0.0.1:443/
```
With `-D`, homebridge-hue will also issue a debug message for each web socket notification it receives:
```
Jul 24 10:57:21 pi1 homebridge[15060]: [Hue] Light 1: state changed event: {"on":true}
Jul 24 10:57:21 pi1 homebridge[15060]: [Hue] Pulse 2: state changed event: {"buttonevent":2002,"lastupdated":"2019-07-24T08:57:21"}
```
as well as for each request it sends, and for the status back from deCONZ (or the Hue bridge):
```
Jul 24 10:57:36 pi1 homebridge[15060]: [Hue] pi1: gateway request 10: get /sensors
Jul 24 10:57:36 pi1 homebridge[15060]: [Hue] pi1: gateway request 10: ok
Jul 24 10:57:36 pi1 homebridge[15060]: [Hue] pi1: gateway request 11: get /lights
Jul 24 10:57:36 pi1 homebridge[15060]: [Hue] pi1: gateway request 11: ok
```

**Comment by fschaefer** [comment]
> The deCONZ REST API exposes the port used for the web socket, so homebridge-hue detects this automatically.

I just realized that one minute ago. Anyway, thank you very much for the detailed answer!
