### ISSUE TITLE
Question: how to blacklist a resource on deCONZ

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-hue#504]
I am trying for two hours now to find out how to blacklist a resource. I have deCONZ and homgebridge hue running on the same pi. Homebridge hue is also connected to the hue bridge.

All I want now is to blacklist the humidity sensor of an Aqara temperature sensor connected to deCONZ. I used dc_eventlog and got the resource link sensors/14 but how do I issue that blacklist command now. I guess I need to use ph in some way. What is the syntax?

Please help.

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue#configuration.  You need to POST to `/resourcelinks`.  Using `ph`, this would be:
```
$ ph post /resourcelinks '{
  "name": "homebridge-hue",
  "classid": 1,
  "description": "blacklist",
  "links": [
    "/sensors/14"
  ]
}'
```

**Comment by CooperCGN** [comment]
Thank you for pointing me into the right direction, finally understood that tool with its parameters.

**Comment by CooperCGN** [comment]
Sorry, that I need to reopen this. I accidentally blacklisted the a wrong sensor, now I want to delete it with:

ph -H deCONZIP delete

but what does the body needs to look like? When I add the body like above I get a "fatal: 4 method, DELETE, not available for resource, /resourcelinks" error.

**Comment by ebaauw** [comment]
Use `ph -H ... delete /resourcelinks/xx`, replacing `xx` with the resourcelink id, to delete the resource link altogether.  Alternatively, just clear the links by `ph -H ... put /resourcelinks/xx '{"links": []}'`.

See `ph` is self-documented: run `ph -h`.  The deCONZ API is described [here](http://dresden-elektronik.github.io/deconz-rest-doc/), but that description is outdated and incomplete (the resourcelinks section is missing).  You might want to check the [resourcelinks](https://developers.meethue.com/develop/hue-api/9-resourcelinks-api/) section of the [Hue api](https://developers.meethue.com/develop/get-started-2/).

**Comment by CooperCGN** [comment]
I will have a look at the Hue API, thanks again.
