### ISSUE TITLE
Osram Smart+ outdoor switch socket support?

### ISSUE THREAD

**Issue by lexpostma** [ebaauw/homebridge-hue#505]
#### Setup description
I have an [Osram Smart+ Zigbee outdoor switch socket](https://www.amazon.de/dp/B0776YGHFN/) connected to my Hue bridge. From the Hue.app I can control it normally. But it's not exposed to Homekit from there, so I installed the homebridge-hue plugin on my existing Homebridge setup on a Mac mini. I added this to the config.json file:

```
"platform": "Hue",
"users": {
    "[something]": "[something]"
},
"lights": true
```

This exposed the Osram to Homekit in Home.app. When I tap the button in Home.app, the plugin comments in Terminal with:

```[Hue] Osram: homekit on changed from 0 to 1```

#### Issue
It gives no error, and thinks all is well. However, the switch doesn't change status. So according to Homekit and Home.app, it changed. Going to Hue.app it also changed, but IRL it didn't. Yet, changing directly from Hue.app does work.

After about 30 minutes, the plugin comments something like:

```
[Hue] Osram: set homekit status fault from 0 to 1
```

Or if I enable them in Hue.app while they were disabled in Homekit, the comment will say:

```
[Hue] Osram: homekit on changed from 0 to 1
```

So my question: **Is this Osram socket supported by the plugin? If not, how can I help adding support?**

**Comment by ebaauw** [comment]
Sounds like routing issues on the Zigbee network.  Homebridge-hue sets status fault when the bridge reports that the socket is unreachable.

The Hue app sends the same commands to the Hue bridge as homebridge-hue.  When you say you can change it from the Hue app, do you change the room the socket is in, or the socket itself?  The first sends broadcasts on the Zigbee network, typically circumventing the routing issues.  You might want to expose the (group for the) room to HomeKit.

The `homekit ... changed` messages indicate changes done from HomeKit, that homebridge-hue forwards to the bridge.  The `set homekit ...` messages indicate changes on the Hue bridge, that homebridge-hue forwards to HomeKit.  Run `homebridge -D` to see the Hue API calls the homebridge-hue makes.  You can replay them manually using`ph` or the CLIP debugger on the bridge to check which calls make it to the plug and which don’t.

**Comment by lexpostma** [comment]
You're right! I was actually toggling the room in the Hue.app, not the accessoire. I had no idea 😅 When toggling the accessoire itself nothing happens, just like in Homekit as described above. (It also says "Not available" with the accessoire 🤷‍♂️). So that was that mystery, thank you!

Now, if I want to expose only that one room, and not all the others, I'd probably do that with a whitelist, right? I read about it in the readme, with didn't understand it.

Right now I have this:

```
"platform": "Hue",
"users": {
	"[something]": "[something]"
},
"lights": false, // removes the separate light(s)
"groups": true, // needed to show the rooms
"rooms": true // all the rooms
```

So, no more separate Osram in Homekit. But now I get _all_ the rooms, including one "Entertainment room 1" which I don't know where that comes from. It seems to be a group of 2 rooms (could be the zone I have in Homekit, but that's named differently).

How do I whitelist only one of the rooms and remove all the others?

**Comment by ebaauw** [comment]
> But now I get all the rooms, including one "Entertainment room 1" which I don't know where that comes from

That's probably the setup for Hue entertainment.  Homebridge-hue can use it to switch streaming mode off, in case you want to automate that from HomeKit, see #490 

For creating a whitelist, see #504, but obviously give the resourcelink a description of `whilelist` instead of `blacklist`.

**Comment by lexpostma** [comment]
Thank you so much!

Indeed 2 things, just for documentation:

- The 'Entertainment room 1' was related to the (to me unknown) entertainment feature of syncing the light with a video source. Removing that "room" from a separate section in the Hue.app settings removed it in Homekit too.
- When you're talking about `ph` I had no idea what you meant. Eventually I figured it was the Philips Hue developer interface ([resource](https://developers.meethue.com/develop/hue-api/9-resourcelinks-api/)). 
   - So I went to `http://[bridge IP address]/debug/clip.html`. 
   - There I could GET the groups using URL `/api/[username]/groups` to find the ID of that one room. 
   - Then I could create a whitelist using
**URL:** `/api/[username]/resourcelinks`
**Body:** 
```
{
	"name": "homebridge-hue",
	"description": "whitelist",
	"classid": 1,
	"links": [
		"/groups/10"
	]
}
```

And finally the config.json:

```
{
	"platform": "Hue",
	"users": {
		"[something]": "[username]"
	},
	"lights": false,
	"groups": true
}
```

**Comment by ebaauw** [comment]
`ph` is a command-line tool I wrote to interface with the Hue API, bundled with homebridge-hue.  See https://github.com/ebaauw/homebridge-hue#commands.

**Comment by lexpostma** [comment]
🤯

Thank you for your incredible work on this _and_ your continuing support. It's really awesome!
