### ISSUE TITLE
Trådfri outlet from deconz is displayed as light in HomeKit

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#509]
Hello, Erik,

I have a short question :-)

When I train a Tradfri outlet in deconz I do it via light function. In deconz the Trådfri outlet is displayed as a socket under lights.

When I integrate the trafri outlet into HomeKit via homebridge-hue, the outlet is displayed as a light.

With some devices it is possible to change the service from light to outlet in HomeKit. With the Trådfri outlet over homebridge-hue unfortunately not. 

If I connect the outlet via the Trådfri bridge, it will also be displayed as a outlet in HomeKit.

Can you tell me why the outlet is not used as a socket? If you say Siri now turn off the light, the sockets go off with -.-

Thank You!

King Regards
Nastra

**Comment by Krocko** [comment]
See here:
 https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0

**Comment by Nastras** [comment]
I checked the changelog. But not the hint -.-

The switch to outlets worked.
What I haven't understood yet if I have several outlets how can I exclude certain ones if they are really used as light?

Is there a description for ph somewhere?

I have looked here
https://github.com/ebaauw/homebridge-hue-utils
but I can't find anything.

Thank you @Krocko 👍👍👍

**Comment by Krocko** [comment]
You can create the resourcelink also with an rest api client. I use Postman for this. 
Only put this outlets in this resourcelink, wich you want as outlet.

**Comment by Nastras** [comment]
All right, now I got it out again. It's been a long time since I have been dealing with deconz. 

@Krocko I thank you again.

**Comment by Nastras** [comment]
@Krocko @ebaauw 

i am just trying "ph" out a lot of things works but i can't get any further at one point. Therefore I need your help again.

I would like to change a username via ph and somehow he doesn't want my body in the command. You surely have an idea what is wrong?

ph -H $IP -u $USER put /api/$CHANGEUSER '{"name":"$NEWUSERNAME"}'

One more question. I noticed that Phoscon creates a new user after each login. Is that with you too? Is that the way it should be?

Thanks again Guys!

**Comment by ebaauw** [comment]
`ph` is just a command-line interface to the deCONZ REST API.  I don’t think the API supports changing a username.  Also, `ph` inserts the `/api/`_username_ part, so you only need to specify the uri after that, e.g. `ph get /lights`.

**Comment by ebaauw** [comment]
`ph` is just a command-line interface to the deCONZ REST API, see http://dresden-elektronik.github.io/deconz-rest-doc/.  I don’t think the API supports changing a username.  Also, `ph` inserts the `/api/`_username_ part, so you only need to specify the uri after that, e.g. `ph get /lights`.

**Comment by Nastras** [comment]
I've been reading the REST API all morning 😅 I have assumed that you can also change the name of the user. Well good to know that it doesn't work.

That I do not have to specify the user etc. with ph in the command any more is a good tip. I did not know yet. Thanks!

Can you possibly answer my question from above about phoscon's login? With every login to phoscon a new user is created in the whitelist.
Is it with you, too?

**Comment by ebaauw** [comment]
I don't regularly use Phoscon, but I see multiple whitelist entries for the old deCONZ WebApp.  I suppose these web apps can only store the username in a cookie and create a new username when the cookie is no longer available.

**Comment by Nastras** [comment]
Then it's gonna be that.

If you say that you still have old entries there it's of course not nice that this list gets fuller and fuller after a while. Don't make it clearer.

I thank you erik and wish you a nice day!
