### ISSUE TITLE
hue motion hide temp-sensor

### ISSUE THREAD

**Issue by Razeeer** [ebaauw/homebridge-hue#510]
Is it possible to hide the temperature sensor from the hue motion in homekit if it is connected via homebridge-hue.

I have tried it with this what did not work out
"excludeSensorTypes": ["CLIPTemperature"],

Background is that I already have a more accurate temperature sensor in the room. When I ask siri about the temperature I get different answers.

Thanks!

**Comment by ebaauw** [comment]
`CLIPTemperature` is for the CLIP temperature sensors.  To stop exposing ZigBee temperature sensors you'd specify `"excludeSensorTypes": ["ZHATemperature"]`.

**Comment by Razeeer** [comment]
I didn't know that. Great its Work!

Thank you!!!

**Comment by Razeeer** [comment]
Hello I have an additional question to the topic. I hope you can help me again.

I have hidden all temperature sensors from the motion sensor via the Config. 

I have now a motion sensor for outside with this I would like to get the temperature displayed. Is that possible without displaying the temperature sensors on all motion sensors again?

Thank you very much.

**Comment by ebaauw** [comment]
Yes create a whitelist resourcelink for the outdoor sensor.  See https://github.com/ebaauw/homebridge-hue#configuration.

**Comment by Razeeer** [comment]
Ahhh, thanks for the tip. Do I only have to specify the sensor number in the whitelist or also the ZHA temperature?
Can you give me an example?

**Comment by Razeeer** [comment]
In the config the value "excludeSensorTypes": ["ZHATemperature"] remains but for the other motion sensors?

**Comment by ebaauw** [comment]
See the README.  Instead, you put the `/sensors/xx` resource in the `links` array, rather than `/lights/xx`.

White- and blacklists overrule the config.json settings, but only for the listed resources.

**Comment by Razeeer** [comment]
Good morning
i have now created a whitelist for the temperature sensor and it works! Thanks for the quick help!
