### ISSUE TITLE
Tradfri Wireless Dimmer not in HomeKit

### ISSUE THREAD

**Issue by m4d-maNu** [ebaauw/homebridge-hue#511]
Hello,

I have a Hue bridge and a Tradfri wireless dimmer. Can I display this in HomeKit via the plugin? The dimmer is connect with my Hue Bridge and Hue lamps.  And I can control my hue lamps with this dimmer, but I can not see it in HomeKit.

greez

**Comment by ebaauw** [comment]
As long as the Hue bridge doesn't expose it through their API, there's nothing I can do.  deCONZ does expose it through their API.

> The dimmer is connect with my Hue Bridge and Hue lamps.

Technically, this is nonsense; there are no connections in ZigBee.  The dimmer has joined the same ZigBee network as the Hue bridge and the lamps.  The dimmer has a binding to each of the lights it controls.  While the Hue bridge might "see" the dimmer on the ZigBee network, it gracefully ignores it.  To wit: you can still control the lights with the dimmer, when the Hue bridge is powered down.

**Comment by m4d-maNu** [comment]
> As long as the Hue bridge doesn't expose it through their API, there's nothing I can do. deCONZ does expose it through their API.

Ah okay, thanks for this information.



> Technically, this is nonsense; there are no connections in ZigBee. The dimmer has joined the same ZigBee network as the Hue bridge and the lamps. The dimmer has a binding to each of the lights it controls. While the Hue bridge might "see" the dimmer on the ZigBee network, it gracefully ignores it. To wit: you can still control the lights with the dimmer, when the Hue bridge is powered down.

Okay, on YouTube are tutorials, they say the dimmer must be connect first with the Hue bridge and then with the lamps. So I assumed that it exists a connection to Hue Bridge.
