### ISSUE TITLE
Eve history bug

### ISSUE THREAD

**Issue by netRunner0** [ebaauw/homebridge-hue#513]
I added a new sensor (temperature), it appeared in the homekit, but in the history of eve it is always empty. I checked if there is a history file, but it (the file) is not there)
Other sensors are present.
Homebridge reloaded.
How else to influence it?)

**Comment by ebaauw** [comment]
What type of sensor did you add?  Can you list the output of `ph get /sensors/xx` for that sensor?  See the _Resource_ characteristic in Eve for the sensor ID.  Is it a standalone temperature sensor, or does it also measure humidity?

**Comment by netRunner0** [comment]
Xiaomi temperature sensor

**Comment by ebaauw** [comment]
The round temperature/humidity sensor?  You need to set `forceEveWeather` in config.json, so homebridge-hue exposes a dummy pressure sensor for the accessory.  Eve doesn't show history for a temperature/humidity sensor, only for a standalone temperature sensor, or for a combined temperature/humidity/pressure sensor (like the Eve Weather).

The history file should be there, though.

**Comment by netRunner0** [comment]
** ebaauw** Square sensor)

It’s not my first, but the only one for whom there is no history ...

**Comment by ebaauw** [comment]
The square one does temperature/humidity/pressure and should work.  There's something else going on, maybe Xiaomi silently released a new model?  Could you please attach the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file)?

Could you also please create a debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and attach that?  It should give some insight why the history file isn't created.

**Comment by netRunner0** [comment]
Just now I noticed that the sensor transmits a malfunction (inaccuracies in the measurement).

Could this be the reason?

**Comment by netRunner0** [comment]
> The square one does temperature/humidity/pressure and should work. There's something else going on, maybe Xiaomi silently released a new model? Could you please attach the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file)?
> 
> Could you also please create a debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and attach that? It should give some insight why the history file isn't created.

Ok

**Comment by netRunner0** [comment]
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/3519739/homebridge.log)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3519740/homebridge-hue.json.gz)


Problem sensor - "Multi Sensor noname"

**Comment by ebaauw** [comment]
I count 25 sensors and no lights.  They raised the number of end devices supported by the RaspBee/ConBee to 32, but then they lowered it again - not sure what the limit is for firmware 0x26330500.  You might run into the limit here.

Having said that, deCONZ is receiving updates from, _Multi Sensor noname_ and homebridge-hue is receiving these.  Also, homebridge-hue is creating history for the sensor:
```
[8/20/2019, 11:55:38 AM] [Hue] Multi Sensor noname: add history entry {"temp":28.7,"humidity":65,"pressure":989,"time":1566291338}
```
To confirm, there should be a `history_00158d0002374fb8.json` file in `~/.homebridge/accessories`.

Most likely Eve is out of sync with the accessory and doesn't display the history entries, because it thinks they are from the future.  If you have multiple iOS devices, can you check whether the history is also missing on those?  

I think the best cause of action is to delete (uninstall) Eve (so it's local data is deleted) and re-install it.  Your HomeKit configuration will be unaffected, but you will lose (layout) customisations made in Eve.

**Comment by netRunner0** [comment]
![IMG_0351](https://user-images.githubusercontent.com/44049295/63363429-fd0f8000-c38c-11e9-8053-79cc00cf8106.png)

**Comment by netRunner0** [comment]
I deleted the empty file and restarted, now it works.

I think it would be nice to add a check that if there is evidence and the file is empty, overwrite the file) Since this error is not the first time

**Comment by ebaauw** [comment]
I’m glad it’s now working for you.  I don’t think I’ve come across an empty history file before.  I would expect homebridge-hue to re-initialise the history, just as when there’s no file, but apparently it doesn’t.  I’ll have to look into that.

**Comment by tomky** [comment]
I encountered the same bug, which is surprising as the accessories with this issues are already online for months with no issues. One day these (but not all) accessories suddenly stopped reporting histories and I see those empty files in the folder. Removed and then it backs online, but the histories for months are lost. No clue what actually happened though.

**Comment by ebaauw** [comment]
What system are you running homebridge on?  Did you check the file system?

**Comment by Phoenix-DH** [comment]
I will attach also my issue to this thread.
I have the Hue Motion sensor in place since more than a year without any problems.
When I have s look to the files in the accessories folder, everything seems to be fine.
Bit in the latest updated eve app there is no history available for those 2... means there is no arrow anymore to open zhe history.

**Comment by ebaauw** [comment]
Eve v3.8.1 is way more restrictive than previous version on when it will show history, see https://github.com/simont77/fakegato-history/issues/76#issuecomment-526219855.  The history for the following accessories no longer shows:
- Temperature sensor (without Humidity/Air Pressure, as for the Hue motion sensor with `hueMotionTemperatureHistory` set in config.json);
- Thermostat.

History for motion sensors, door sensors, and smart plugs should still show.

I think I know how to fix the thermostat; for the temperature sensor I need to do some more research.

**Comment by Phoenix-DH** [comment]
Yeah, that is exactly what I have 🤷🏼‍♂️
hueMotionTemperatureHistory Set to true.

So I will wait.
Thank you for your work.

**Comment by ebaauw** [comment]
v0.11.37 restores the history for the Temperature Sensor service (when you set `forceEveWeather`) and for the Thermostat service.  See the [release notes](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.37).

**Comment by Phoenix-DH** [comment]
Great! Tried and it is working fine. History is back. The dummy is not the problem. Maybe one remark or idea for the next releases:
Possibility to move the dummy to another room ... without moving the temp.

Thank you and have a nice weekend!

**Comment by ebaauw** [comment]
> Possibility to move the dummy to another room ... without moving the temp.

That is technically impossible: they're both services of the same accessory.  And they need to be, or Eve doesn't show the history.

**Comment by Phoenix-DH** [comment]
Okay, understood.

**Comment by tomky** [comment]
Thanks for the quick update. Will try it.
Just curious if you will continue test the Eve signature trick mentioned here?

https://github.com/simont77/fakegato-history/issues/75#issuecomment-526817076

This looks like a better solution if it works.

**Comment by ebaauw** [comment]
Yes, it does look better, although I still need to confirm that it works.  Even then, It might take me some time to use this in homebridge-hue, hence this quick fix.  I see no easy way to update fakegato-history to deal with different entries for motion detected vs periodic temperature updates.  I might need to refactor homebridge-hue to use dynamic platform accessories (see #4), based on homebridge-lib.  Before that, I want to be sure homebridge-lib does what I want it to do, so I'm rewriting my other plugins (with fewer users) first.

**Comment by tomky** [comment]
Understood. Then I got another issue about the CLIPSensors in this approach. I actually have some CLIPTemperature and CLIPHumidity sensors in pairs, treated as independent accessories. Is there a way to merge them as single multi sensors in deconz or Homebridge-hue? In this way I can get the humidity history and avoid the extra dummy humidity sensor.

**Comment by ebaauw** [comment]
Yes, MultiCLIP, see #164.

**Comment by ebaauw** [comment]
> Just curious if you will continue test the Eve signature trick mentioned here?

[v0.11.38](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.38) no longer uses dummy sensors, but a (mostly) hidden Eve Weather service.

**Comment by mtressl** [comment]
Just adding that I experienced the same issue as mentioned above:
- in Eve some of my sensors did not report the history (anymore)
- I checked `~/.homebridge/accessories` and found matching 0 bytes (empty) files
- deleted all of them, restarted Homebridge, files were re-created, history values showing in Eve app

Maybe it really makes sense to implement something for the plugin to fix such issues.
