### ISSUE TITLE
Add Ikea FYRTUR (window covering) support

### ISSUE THREAD

**Issue by rgerr** [ebaauw/homebridge-hue#514]
As of last week, Ikea is selling their FYRTUR motorized window covering (https://www.ikea.com/nl/nl/catalog/products/40408196/). It should have HomeKit support (via Ikea hub) but I would like to have this on my Hue hub. 

Any chance of adding this to the hue plug-in?

**Comment by ebaauw** [comment]
> Any chance of adding this to the hue plug-in?

Yes, I plan to add support as soon as I can get my hands on one.  While published on the web side, they’re not yet in stock here in the Netherlands.

> but I would like to have this on my Hue hub.

homebridge-hue needs deCONZ or the Hue bridge to support the device in their API. I’m pretty sure this will not happen for the Hue bridge.

**Comment by rgerr** [comment]
Understood. So for it being able to work with HomeKit via homebridge-hue, you would need a deCONZ bridge. NOT a Hue bridge.

**Comment by ebaauw** [comment]
Finally got my own FYRTUR.  homebridge-hue already supports it, as the deCONZ REST API exposes it similarly to other Window Covering devices, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1121.  I'll add support for the open/close remote.

**Comment by simplenotezy** [comment]
Hi! Does that mean I don't need an IKEA bridge?

**Comment by simplenotezy** [comment]
Eg it can work using just the Hue Bridge?

**Comment by ebaauw** [comment]
> Hi! Does that mean I don't need an IKEA bridge?

Yes

> Eg it can work using just the Hue Bridge?

No, see README.

**Comment by roficas** [comment]
I have Hubitat Elevation (HE) as my Zigbee hub and I use home bridge to make the devices available to the HomeKit. I was able to pair the shades with HE and it's working very well. But when I try to open using home bridge, it goes all the way around (closing means opening and vice-versa). Anybody with the same issue?
