### ISSUE TITLE
No issue, just a question! 

### ISSUE THREAD

**Issue by 00lex** [ebaauw/homebridge-hue#515]
hi Erik! 
can you tell me how did you manage to turn on, turned off lights when you just change the color OR the color temp? 

background is, I use pimatic and there is a plugin for deconz. actual it doesn't work to switch on a light by changing color OR color temp. his workaround will be to make two requests. 
1st turn on and a second to set the input, because deconz api does not allow changes when the lamp is turned off. is this way or is there another more elegant solution? 

thank you

**Comment by ebaauw** [comment]
I don't, Siri or the HomeKit app typically send a request to turn on the light, before sending the request to change its brightness or colour (temperature).

homebridge-hue combines multiple requests from HomeKit into a single request towards deCONZ (or the Hue bridge), e.g. a PUT to `/lights/xx/state` with a body of `{"on": true, "bri": 127, "ct": 360}`.

**Comment by 00lex** [comment]
mhh there is something strange because HomeKit and Pimatic doesnt do anything while changing color OR temp when a light is off. 
anyway, that's not your problem. thank you for your reply
