### ISSUE TITLE
websocket communication error undefined

### ISSUE THREAD

**Issue by pcherkash** [ebaauw/homebridge-hue#516]
Hi, help me with some advice. deconz is installed in docker. The internal port and the external port are different from each other. How can I install an external port? (Internal is automatically selected).

config:
"platforms": [
        {
            "name": "Hue",
            "excludeSensorTypes": [
                "ZLLSwitch",
                "ZGPSwitch",
                "ZLLPresence",
                "ZLLLightLevel",
                "ZLLTemperature",
                "ZHAHumidity",
                "ZHAPressure",
                "CLIP"
            ],
            "forceEveWeather": true,
            "hosts": [
                "192.168.1.10:6681"
            ],
            "hueDimmerRepeat": true,
            "hueMotionTemperatureHistory": true,
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "wallSwitch": true,
            "platform": "Hue"
        }

Error:
[8/23/2019, 7:00:09 AM] [Hue] deconz: websocket communication error undefined on ws://192.168.1.10:443/

**Comment by ebaauw** [comment]
> How can I install an external port?

You cannot.  Homebridge-hue connects to the websocket port that deCONZ reports; there’s no configuration option to change that.

> The internal port and the external port are different from each other.

Why on Earth would you want to do that?  You can specify which ports deCONZ uses through command line parameters when starting deCONZ.  Both for the websocket port as well as for the API port.
