### ISSUE TITLE
It looks like you are using a string compare for the Homebridge version. This fails on higher version custom Homebridge spins.

### ISSUE THREAD

**Issue by mkellsy** [ebaauw/homebridge-hue#518]
#### Issue
I am getting the Homebridge version not satisfied error.

We are using a custom spin of Homebridge. With a version 3.0.2. This is higher than 0.4.50.

If you compare using strings "0.4.50" is greater than "3.0.2", which is false

**Comment by ebaauw** [comment]
> I am getting the Homebridge version not satisfied error.

That error is issued by homebridge itself, not by homebridge-hue.  Homebridge-hue does semver checking and issues a warning in case of mismatch.

> We are using a custom spin of Homebridge.

Not something that I would recommend or support.
