### ISSUE TITLE
homebridge-lib missing keyword

### ISSUE THREAD

**Issue by Foxcross** [ebaauw/homebridge-hue#521]
Hi, 
I'm using RaspBee with pre-installed SD form Phoscon/deCONZ. I updated homebridge-lib using config-ui-x, after this all of my devices stopped responding in Home app. I tried to install homebridge-lib as you suggested in deconz-rest-plugin issue, i also tried resetting Homebridge in Phoscon App and rewriting `config.json` (both did not help). I'm just a beginner, is there still a problem with homebridge-lib? `deamon.log` code snippet with potential problem:

> Sep  1 00:27:26 phoscon deCONZ-homebridge.sh[22807]: starting homebridge
> Sep  1 00:27:28 phoscon deCONZ-homebridge.sh[22807]: [9/1/2019, 12:27:28 AM] Loaded config.json with 2 accessories and 1 platforms.
> Sep  1 00:27:28 phoscon deCONZ-homebridge.sh[22807]: [9/1/2019, 12:27:28 AM] ---
> Sep  1 00:27:28 phoscon deCONZ-homebridge.sh[22807]: [9/1/2019, 12:27:28 AM] Plugin /usr/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
> Sep  1 00:27:28 phoscon deCONZ-homebridge.sh[22807]: [9/1/2019, 12:27:28 AM] Plugin /usr/lib/node_modules/homebridge-hue requires Node version of ^10.16.3 which does not satisfy the current Node version of v10.16.0. You may need to upgrade your installation of Node.
> Sep  1 00:27:30 phoscon deCONZ-homebridge.sh[22807]: [9/1/2019, 12:27:30 AM] Loaded plugin: homebridge-hue
> Sep  1 00:27:30 phoscon deCONZ-homebridge.sh[22807]: [9/1/2019, 12:27:30 AM] Registering platform 'homebridge-hue.Hue'

**Comment by ebaauw** [comment]
Homebridge-lib is no longer a peer dependency, as that was causing too many issues.  It is once again included in homebridge-hue, and does not need to be installed separately, nor mentioned in config.json.  I suggest you try the following:
= Uninstall homebridge-lib;
- Re-install homebridge-hue;
- Edit config.json and remove any reference to homebridge-lib or the `Lib` platform;
- Restart homebridge.

**Comment by Foxcross** [comment]
Did everything you said, reinstalled plugins, also updated node to 0.16.13. Log file doesn't have any errors anymore. I tried re-adding bridge in Home app but after deleting i can't discover it in Home app. config-ui-x says it listens on port 8081 but Homebridge service isn't working. I also have Pi-hole running on this machine, maybe it somehow causes the problem? `ipconfig` says broadcast and multicast is enabled:

> wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.1.14  netmask 255.255.255.0  broadcast 10.0.1.255

**Comment by ebaauw** [comment]
If you deleted homebridge from HomeKit while homebridge wasn’t running, you might need to delete the `persist` directory in `~/.homebridge`.  This is like a factory reset of homebridge, deleting any pairing info.

Homebridge listens on the port specified in config.json, typically 51826, HomeKit needs to find it through Bonjour, which uses multicast.  You might want to disable pihole temporary, to see if that is causing an issue.

**Comment by Foxcross** [comment]
Thanks a lot. At the and i deleted pihole and it helped. Homebridge is up and running. Now only find out why pihole was blocking homebridge.
