### ISSUE TITLE
Support Lutron Aurora Switches

### ISSUE THREAD

**Issue by warhammerkid** [ebaauw/homebridge-hue#522]
#### Issue
The [Lutron Aurora](http://www.lutron.com/en-US/Products/Pages/StandAloneControls/Dimmers-Switches/SmartBulbDimmer/overview.aspx) switches are identified but not recognized. It appears that they have two pieces - the switch button and the dimmer wheel.

#### Log Messages
Here's what I get in the logs to describe them:
```
[9/1/2019, 1:53:30 PM] [Hue] Philips hue: /sensors/7: warning: ignoring unknown sensor type {"state":{"rotaryevent":2,"expectedrotation":64,"expectedeventduration":400,"lastupdated":"2019-09-01T17:32:08"},"swupdate":{"state":"noupdates","lastinstall":"2019-09-01T15:26:15"},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Bedroom 1 Aurora Switch","type":"ZLLRelativeRotary","modelid":"Z3-1BRL","manufacturername":"Lutron","productname":"Lutron Aurora","diversityid":"2c3a75ff-55c4-4e4d-8c44-82d330b8eb9b","swversion":"3.1","uniqueid":"ff:ff:00:0f:e7:fe:95:cd-01-fc00-0014","capabilities":{"certified":true,"primary":true,"inputs":[{"repeatintervals":[400],"events":[{"rotaryevent":1,"eventtype":"start"},{"rotaryevent":2,"eventtype":"repeat"}]}]}}
[9/1/2019, 1:53:30 PM] [Hue] Philips hue: /sensors/8: warning: ignoring unknown ZLLSwitch sensor {"state":{"buttonevent":1002,"lastupdated":"2019-09-01T17:45:47"},"swupdate":{"state":"noupdates","lastinstall":"2019-09-01T15:26:15"},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Lutron Aurora 2","type":"ZLLSwitch","modelid":"Z3-1BRL","manufacturername":"Lutron","productname":"Lutron Aurora","diversityid":"2c3a75ff-55c4-4e4d-8c44-82d330b8eb9b","swversion":"3.1","uniqueid":"ff:ff:00:0f:e7:fe:95:cd-01-fc00","capabilities":{"certified":true,"primary":false,"inputs":[{"repeatintervals":[800],"events":[{"buttonevent":1000,"eventtype":"initial_press"},{"buttonevent":1001,"eventtype":"repeat"},{"buttonevent":1002,"eventtype":"short_release"},{"buttonevent":1003,"eventtype":"long_release"}]}]}}
```

#### Other
If you need any more information just let me know. I'm also quite comfortable testing a PR branch if you need verification.

**Comment by ebaauw** [comment]
I’m unfamiliar with these switches.  Luckily, the Hue API now lists their capabilities.  The button looks pretty straightforward, similar to the Hue dimmer switch.  I have no clue how to expose the wheel to HomeKit.

**Comment by warhammerkid** [comment]
I hadn’t ever looked through the HomeKit docs before, but I agree that there doesn’t seem to be anything ideal to map the rotary switch to. In theory it looks like it could be mapped to some kind of clockwise / counterclockwise “button” event, but I can’t see any value in doing that for myself.

**Comment by ebaauw** [comment]
The Hue bridge doesn't support event notifications, so I have to poll it.  I find the gen2 bridge is able to handle being polled every 2 seconds, but every 1 second is too much.  This means (if I read the capabilities right) that I'll lose 4 out of 5 rotary events, making it very difficult to expose anything more sophisticated than a clockwise or counterclockwise turn.

I take it the Hue bridge doesn't expose the switch to HomeKit?

Could you attach the debug dump file homebridge-hue creates on startup (see https://github.com/ebaauw/homebridge-hue#debug-dump-file)?  Maybe the Hue app has created some rules for the wheel that would give me some more insight.

**Comment by warhammerkid** [comment]
The Hue bridge does not expose the switch to HomeKit.

Here's the debug file: [homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3564012/homebridge-hue.json.gz).

**Comment by tomky** [comment]
I am interested in this switch/dimmer as well. Will this be supported through deconz?

**Comment by ebaauw** [comment]
Best open an issue in the deconz repository, requesting device support, see https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by ebaauw** [comment]
Button is supported In [v0.11.38](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.38).

**Comment by siobhanellis** [comment]
I'm running V0.11.44 and the button is not visible in HK.

**Comment by ebaauw** [comment]
Added support for the Lutron Aurora, when connected to deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2305#issuecomment-585998322.  
When connected to deCONZ, the dimmer switch is exposed with three buttons: _Button_, _Right Turn_, and _Left Turn_, each supporting _Single Press_.

Added support for the ZLLRelativeRotary `/sensors` resource for the Lutron Aurora, when connected to the Hue bridge.
When connected to deCONZ, the dimmer switch is exposed with three buttons: _Button_, supporting _Single Press_ and _Long Press_; and _Right Turn_ and _Left Turn_, both supporting _Single Press_.

**Comment by ebaauw** [comment]
In v0.11.54.

**Comment by siobhanellis** [comment]
now running v.0.11.55 (quick catch on the issue in 11.54 BTW), and I still can't see it.

**Comment by ebaauw** [comment]
What's your config.json?

**Comment by siobhanellis** [comment]
`{
            "name": "Hue",
            "users": {
                "001788FFFE49C73E": "38KkSc1f5LRemVOt9BUdzkKhUGxNI4N1YTVb7TfN",
                "ECB5FAFFFE02DEEF": "L0v17RUcbkaVNvThaHnYvePJiyqYSBnWWt5FXMgr"
            },
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue"
        }`

**Comment by siobhanellis** [comment]
{
            "name": "Hue",
            "users": {
                "001788FFFE49C73E": "38KkSc1f5LRemVOt9BUdzkKhUGxNI4N1YTVb7TfN",
                "ECB5FAFFFE02DEEF": "L0v17RUcbkaVNvThaHnYvePJiyqYSBnWWt5FXMgr"
            },
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue"
        }

**Comment by ebaauw** [comment]
You need to set `"sensors": true` to expose `/sensors` resources.  You might want to set `"excludeSensorTypes": ["CLIP"]` to prevent the CLIP sensors created by the Hue app from being exposed.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by siobhanellis** [comment]
I'll give it a go and let you know. Wasn't obvious I had to enable sensors... as it's a switch :-)

**Comment by siobhanellis** [comment]
Yes, that worked. I now see it in HK as a Dimmer with 3 buttons.

**Comment by javontathomas** [comment]
Is it possible to hide this from Homekit without hiding all sensors? Don't need it on HK as it's already working via Hue.

**Comment by ebaauw** [comment]
> Is it possible to hide this from Homekit without hiding all sensors?

Include it in a `blacklist` resourcelink, see https://github.com/ebaauw/homebridge-hue#configuration.

> Don't need it on HK as it's already working via Hue.

Do you mean that the Hue bridge now exposes it to Homekit?  I haven’t seen that before.  I’d better not expose it when `nativeHomeKitSensors` is set.

**Comment by ebaauw** [comment]
Double-checked: the Hue bridge does **not** expose the Aurora to HomeKit.
