### ISSUE TITLE
Hide/Delete duplicated Hue Bridge Device(Exposed but no Function)

### ISSUE THREAD

**Issue by Kallitho** [ebaauw/homebridge-hue#524]
Why there is shown a Second Philips Hue Device? This is exposed from Homebridge (_shown when clicking on Bridge_)via this Plugin. 

**I want to hide or delete this Duplicate**, because it has no function. The Home App says: 

> This device is currently not supported by the Home app.

Possible?

![F4908355-C6BF-4ECF-8F34-3A870F241AA0](https://user-images.githubusercontent.com/54825661/64163206-1c081a80-ce41-11e9-80b0-207e3d6f63e7.jpeg)

**Comment by ebaauw** [comment]
No, see #140.

**Comment by Kallitho** [comment]
Okay, now i unterstand the Plugin needs This Accessory to work, But really no Chance to hide it With a Spezial Parameter? 

Maybe i move it to an extra room with no Function 😬
Can you find a way To bring an Update in the Future for This (a bit) confusing thing? 🙂

Also Thanks for the great work, your Plugin runs perfect. Used This to make the cheap Osram Smart+ Plug (Zigbee) HomeKit compatible! 👌🏻

**Comment by ebaauw** [comment]
> But really no Chance to hide it With a Spezial Parameter?

No that I know of.  I tried all the tricks in my book, but I cannot work around this limitation of Apple's Home app.

**Comment by Kallitho** [comment]
Okay I understand. Then it has to stay that way.
Thanks for the Reply’s.
