### ISSUE TITLE
Hue Dimmer not showing up in Home app

### ISSUE THREAD

**Issue by menbren** [ebaauw/homebridge-hue#525]
First up, I'm a new user so its probably a case of _PEBCAK_. So, apologies in advance :) 

#### Question
I'm running a Raspberry Pi with Raspbee board as my Homebridge server, including deCONZ. I have a Hue dimmer showing up in deCONZ and deCONZ in my Homebridge config, but the dimmer is not showing up in the home app.

- deCONZ version: 2.05.67 with firmware 26330500
- Homebridge-hue: 0.11.37
- Homebridge: 0.4.50

Upon GET /api<apikey>/sensors I get the following output:
```
 "3": {
        "config": {
            "battery": 37,
            "group": "28992",
            "on": true,
            "reachable": true
        },
        "ep": 2,
        "etag": "29aebcb4f4c07bada2b667bf78f41274",
        "manufacturername": "Philips",
        "mode": 1,
        "modelid": "RWL021",
        "name": "Dimmer Switch",
        "state": {
            "buttonevent": null,
            "lastupdated": "none"
        },
        "swversion": "5.45.1.16265",
        "type": "ZHASwitch",
        "uniqueid": "00:17:88:01:10:48:d4:64-02-fc00"
    }
```

So it appears the dimmer is correctly setup in the Phoscon. How can I expose it to Homekit?

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3570044/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
The switch doesn't show in the debug log.  Did you restart homebridge after adding the switch?

**Comment by menbren** [comment]
Hi Erik,

Thanks for your prompt respone!

Yes I did, multiple times actually. Any other suggestions?

**Comment by ebaauw** [comment]
The above dump file is from 10:16 this morning.  Does the timestamp on the `homebridge-hue.json.gz` file change when restarting homebridge?

If yes, could you please attach it again; if no: how do you (re-)start homebridge and how did you install homebridge-hue?

**Comment by menbren** [comment]
Unfortunately the log file doesn't update.

I tried restarting it in three ways:
1. from the Phoscon web interface
2. `sudo systemctl restart homebridge`
3. `sudo reboot`

However, every time I restart, I have to hit the Authenticate App button in the Phoscon web interface. Otherwise it remains unavailable in Apple Home. 

I have installed is homebridge and deconz as a service enabled on boot.

As you can probably tell from my log file, I have also added my Hue bridge next to the Raspbee. This works fine, as it allows me to expose an Ikea light that would otherwise not have shown up in homekit. This gives me the impression that homebridge-hue is running (well).

**Comment by ebaauw** [comment]
I think you’re running homebridge using a different user directory.  From what directory did you get homebridge-hue.json.gz.  Are you sure that’s the only place with this file?  What dies the homebridge.service file look like?

**Comment by menbren** [comment]
Hi Erik,
Thanks! I have two homebridge folders: `~/.homebridge` and `/etc/default/homebridge`, so I probably messed something up during the installation. I'll try to deduplicate those or start with a clean install if necessary.

**Comment by ebaauw** [comment]
`/etc/default/homebridge` should be a file with environment variables for `homebridge.service`.  Does it contain a dump file (with a timestamp corresponding to the homebridge restart)?  And a `config.json`?

**Comment by menbren** [comment]
Yes it does, and the dimmer is also showing up now. What I have done:
- I replaced the content of the `config.json` file under '/var/homebridge`. (By mistake, I mentioned `/etc/default/homebridge` in my previous reply, but that is where the `homebridge.service` file is located, pointing to '/var/homebridge`. 
- I removed the other config file to prevent future mistakes.

**Comment by menbren** [comment]
And thanks for all the help!
