### ISSUE TITLE
Device-type of an deConz-Accessoire

### ISSUE THREAD

**Issue by hajanet** [ebaauw/homebridge-hue#526]
Hello @ebaauw, thanks a lot for your good work!

I'm using your plugin since many years. I have added a Osram Plug a year ago which I used for my christmas tree. It was declared as a light in Homekit.

Now I want to use this plug for a fan. I've added the plug to my deConz-Setup and it is exposed to homekit through your plugin; but it is exposed as a light. 
Normally this is not a problem. But when I Siri "turn off all lights in bedroom" the fan turns off.
This is not what it should do... I dont have any possibility to change the type in the home-app.
Is there a way to change the type of the device to a switch or plug in your plugin?

Thanks a lot!

**Comment by ebaauw** [comment]
Add it to an outlet resourcelink to make homebridge-hue expose it as an _Outlet_.  Then you can change the device type in HomeKit.  See https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0.

**Comment by hajanet** [comment]
@ebaauw, dankje!!!!  That worked! You are a genius. Thanks a lot!
