### ISSUE TITLE
Recommended deCONZ Version

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#527]
Hi, Erik,

short question about the warning recommended version deconz.

I have installed the current stable version of deconz 2.05.67 over apt but get the warning from homebridge-hue that is recommended version 2.05.69. 

https://github.com/dresden-elektronik/deconz-rest-plugin/releases

The version 2.05.69 is not officially distributed by apt yet and I think it is still in beta status.

I know that I can change the warning or the version in package.json until the next homebridge-hue update.

With the recommended Node you always use the LTS version as dependencies.

Wouldn't it make more sense to warn with recommended deconz if a version is older than the stable version?

Best Regards

Nastra

**Comment by ebaauw** [comment]
I list the version against which I develop and test homebridge-hue.  Typically that’s the latest deCONZ beta version available on Raspbian through `apt`.

**Comment by Nastras** [comment]
I understand that. 

But that beta and stable are valid would not be possible?

This would leave the user to decide which version to use without receiving the warning message.

**Comment by Nastras** [comment]
I just adapted it to test my package.json. This would cover stabel and beta version without any warning. In the future you have to set the dependencies to stable.

 "deCONZ": ">=2.5.67",

But you know that better than me 😄

I would be very happy if you implement it. Thanks a lot!

**Comment by ebaauw** [comment]
That’s not going to happen.

**Comment by Nastras** [comment]
Can not do anything you will have your reasons.

Thanks anyway!
