### ISSUE TITLE
Homebridge Plugin Dev related question

### ISSUE THREAD

**Issue by steilerDev** [ebaauw/homebridge-hue#528]
Hi @ebaauw,

reaching out this way, because I am not sure how else to contact you.

I am also developing my [own Homebridge plugin](https://github.com/steilerDev/homebridge-openhab2-complete), and I got a [feature request](https://github.com/steilerDev/homebridge-openhab2-complete/issues/9) for numeric battery states within the item based on the functionalities offered by your plugin right here.

I studied the implementation and tried reproducing it, however I can't get it to work. Feel free to take this offline and [shoot me an email](mailto:frank@steilerdev.de) about this, or comment on my issue above. Would love to understand what I am doing wrong, especially since Homebridge's documentation is very sparse on this.

Thank you!

**Comment by ebaauw** [comment]
You just need to expose a _BatteryService_ with all three characteristics, see https://github.com/KhaosT/HAP-NodeJS/blob/cfbb9368800a2582deb0d7f1e9572c1a2dca64e2/src/lib/gen/HomeKit.ts#L3121.  You might need to pass a name when creating the service.

The screenshot seems Apple’s Home app alright.  Note that the battery is shown in the _Settings_ window.

**Comment by steilerDev** [comment]
I was thinking about this as well, but my logs (for some reason, and I guess this is the issue) show the following:
```
HAP Warning: Characteristic 0000008F-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000096-0000-1000-8000-0026BB765291. Adding anyway.

HAP Warning: Characteristic 00000068-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000096-0000-1000-8000-0026BB765291. Adding anyway.
```

**Comment by ebaauw** [comment]
Did you create a new instance of the service?

**Comment by steilerDev** [comment]
I found the issue. Accidentally my logic was removing characteristics in certain behaviours. Thank you for your help!
