### ISSUE TITLE
dresden elektronik switch is not recognized

### ISSUE THREAD

**Issue by volschin** [ebaauw/homebridge-hue#531]
#### Issue

the dresden elektronik switch is not recognized (using v0.11.40)
#### Log Messages

```
[9/14/2019, 12:11:03 PM] [Hue] Phoscon-GW: /sensors/5: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"24403","on":true,"reachable":false},"ep":1,"etag":"802be65c7c04d0f6b32aa5da591b2877","manufacturername":"dresden elektronik","mode":2,"modelid":"Lighting Switch","name":"Lichtschalter SZ","state":{"buttonevent":1002,"lastupdated":"2019-08-17T18:58:19"},"swversion":"02010030","type":"ZHASwitch","uniqueid":"00:21:2e:ff:ff:01:5c:a8-01-1000"}
[9/14/2019, 12:11:03 PM] [Hue] Phoscon-GW: /sensors/6: warning: ignoring unknown ZHASwitch sensor {"config":{"group":"24404","on":true,"reachable":false},"ep":2,"etag":"802be65c7c04d0f6b32aa5da591b2877","manufacturername":"dresden elektronik","mode":2,"modelid":"Lighting Switch","name":"Lichtschalter SZ","state":{"buttonevent":3002,"lastupdated":"2019-08-17T18:58:18"},"swversion":"02010030","type":"ZHASwitch","uniqueid":"00:21:2e:ff:ff:01:5c:a8-02-1000"}
```

**Comment by ebaauw** [comment]
Happy to add support, but I need some more info.  What `buttonevent` values does it generate, on which ZHASwitch resource?  How are the buttons labelled?

**Comment by volschin** [comment]
Not sure how to geht this out, but it should be the switch from the example 
https://dresden-elektronik.github.io/deconz-rest-doc/sensors/

**Comment by ebaauw** [comment]
I know what the resource looks like, that info is also in the message by homebridge-hue.  I don’t know the switch itself.  How many buttons does it have?  What are these buttons called?  What `buttonevent` values does deCONZ report when pressing, releasing, holding the buttons?

**Comment by volschin** [comment]
Here is a Link to the two switches from de 
https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/wireless-switch

The scene switch seem to be supported already, but I have the Lighting switch.

I try to find out the button names.

**Comment by manup** [comment]
The Lighting Switch has two sensor resources, but all button events are fired on the first endpoint resource:

```json
{
    "config": {
        "group": "15653",
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "3d21b22b243806407666de89d24a2e04",
    "manufacturername": "dresden elektronik",
    "mode": 2,
    "modelid": "Lighting Switch",
    "name": "Lighting Switch",
    "state": {
        "buttonevent": 3002,
        "lastupdated": "2019-09-15T12:51:37"
    },
    "swversion": "02010032",
    "type": "ZHASwitch",
    "uniqueid": "00:21:2e:ff:ff:00:a6:fd-01-1000"
}

{
    "config": {
        "group": "15654",
        "on": true,
        "reachable": true
    },
    "ep": 2,
    "etag": "62aebe1466f44311ffbfd4c7f058178d",
    "manufacturername": "dresden elektronik",
    "mode": 2,
    "modelid": "Lighting Switch",
    "name": "Lighting Switch",
    "state": {
        "buttonevent": 4003,
        "lastupdated": "2019-09-15T12:56:21"
    },
    "swversion": "02010032",
    "type": "ZHASwitch",
    "uniqueid": "00:21:2e:ff:ff:00:a6:fd-02-1000"
}
```
Top left button

* 1002 short press
* 1001 hold
* 1003 release

Bottom left button

* 2002 short press
* 2001 hold
* 2003 release

Top right button

* 3002 short press
* 3001 hold
* 3003 release

Bottom right button

* 4002 short press
* 4001 hold
* 4003 release

The button map is defined in https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/sensor.cpp#L14L57

**Comment by ebaauw** [comment]
Thanks for your help @manup!

> but all button events are fired on the first endpoint resource:

But then `state.buttonevent` and `state.lastupdated` would be `null` on the resource for the second endpoint?

> The button map is defined in

If I read the button map correctly, 3001, 3003, 4001, 4003 are not available when `mode` is 1 and 300x and 400x are issued on the second endpoint when `mode` is 2?  Is `mode` settable through the API?  When changed, does it take effect immediately, or only after restarting deCONZ?  I don't understand how the resource for endpoint 1 can report `state.buttonevent` 3002 in `mode` 2, or did you change the mode after the button event took place?

**Comment by volschin** [comment]
The mode is part of the configuration how you want to use the switch. So this is Not changed in normal use.

**Comment by manup** [comment]
The second endpoint only holds 3xxx and 4xxx events (for historical reasons).
The mode can only be changed via the on device switch configuration menu by following the instructions in the phoscon app.

The default mode 2 aka "two groups" is the most useful one in combination with a gateway, as its provides all events. The other modes are only useful when the switch should be used without a gateway and send specific recall scene or color temperature commands instead of just on/off and brightness control.

**Comment by ebaauw** [comment]
So best to ignore the second endpoint and to issue a warning when `mode` is not 2?

**Comment by volschin** [comment]
For me this would be fine, as I only use mode 2.

**Comment by manup** [comment]
>So best to ignore the second endpoint and to issue a warning when mode is not 2?

Yes I think that's a good approach.

**Comment by ebaauw** [comment]
In v0.11.41.

**Comment by volschin** [comment]
Thanks.
