### ISSUE TITLE
Osram Smart+ Power Plug with Hue Bridge

### ISSUE THREAD

**Issue by MacDyson909** [ebaauw/homebridge-hue#532]
Hello,
Is it possible to see this device like a plug or fan but not like a light ?
This is not really an issue, but should be great to do !
Thanks for all of your work

**Comment by ebaauw** [comment]
Yes, see https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0.

**Comment by MacDyson909** [comment]
Thank you 🙏🏻

Sébastien Mies

________________________________
De : Erik Baauw <notifications@github.com>
Envoyé : mardi, septembre 17, 2019 7:11 AM
À : ebaauw/homebridge-hue
Cc : MacDyson909; Author
Objet : Re: [ebaauw/homebridge-hue] Osram Smart+ Power Plug with Hue Bridge (#532)


Yes, see https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0.

**Comment by MacDyson909** [comment]
Hello,
I tried to understand but i’m really new in this « world » and i just understood how to add a Platform with a model… but nothing more..
I tried to type the first commend line in OSX terminal, but it’s not the good way … LOL
Is it possible to détail quickly what do you mean by 

"Make sure to run ph outlet -v to create the resourcelink, after upgrading homebridge-hue, but before(re-)starting homebridge. Double check that all your outlets are indeed listed in the in the resourcelink: »

where i must run this command line ? (i don’t understand how to generate this file and what i need to add (and where) in .json conf file….)
Where the ressource link is it ?
What do you mean by upgrading Homebridge-hue ?
After that… What is the « owner » ?

I will understand if you don’t have time to help me, and in all case, thanks for your job ! really good ;-)

Sebastien

**Comment by MacDyson909** [comment]
Ok… simple…. SO EASY !  
Again thank you ;-)
