### ISSUE TITLE
Deconz battery

### ISSUE THREAD

**Issue by netRunner0** [ebaauw/homebridge-hue#533]
How to get battery or low charge status for Xiaomi door sensors or temperature sensors?

**Comment by ebaauw** [comment]
deCONZ needs to expose `config.battery` on the sensor resource when starting homebridge.  Typically it only creates this attributes when it receives the first Xioami special attribute report.  This might take an hour after pairing the sensor.

**Comment by netRunner0** [comment]
But there is no universal key for all possible devices where there is a battery?
I would like to see the charge level in the HC and build on the basis of this automation

**Comment by ebaauw** [comment]
homebridge-hue exposes the battery using the standard HomeKit _Battery_ service and characteristic.  You can use these in HomeKit scenes and automations.  You need to use a decent HomeKit app, though; Apple’s Home app doesn’t support this.

**Comment by netRunner0** [comment]
Hmm, strange. Indeed, in the home program and other programs, the battery charge is displayed.
However, when creating automation using quick commands, this parameter cannot be extracted:

![IMG_0094](https://user-images.githubusercontent.com/44049295/65374859-064f7d80-dca8-11e9-8355-25a7ae573e55.png)

None of the “Own” charges exist.
Is it possible to place a battery charge so that it can be removed in the menu above?

**Comment by ebaauw** [comment]
No, you need to use another HomeKit app.
