### ISSUE TITLE
Conbee 2 and HA Bridge on the same host

### ISSUE THREAD

**Issue by merdok** [ebaauw/homebridge-hue#534]
Hi,

I am running Conbee 2 and HA Bridge on the same host and i just want to expose Conbee 2 devices with the homebridge-hue plugin to Homekit. How would i need to do that? When i type the ip address in the _**host**_ property then of course both of them get discovered because both of them are on the same host...

**Comment by ebaauw** [comment]
They would run on different ports, just specify _host_:_port_.

**Comment by merdok** [comment]
Didn't though about that. Thanks! HA Bridge is now gone!
