### ISSUE TITLE
Aqara Counter resets in Homekit after reboot

### ISSUE THREAD

**Issue by Mallepi** [ebaauw/homebridge-hue#536]
Hello, I've been using your plugin and deconz for a few days. I have contact sensors from Aqara in use. I noticed that after a restart of my pi the counters in HomeKit reset and are back to zero.

Can you please help me how to fix this?

Thanks!!!

**Comment by ebaauw** [comment]
That’s a limitation of the current design of homebridge-hue.  I need to refactor it to use dynamic platform accessories, see #4.

**Comment by Mallepi** [comment]
Thanks for the answer. Nice that it is already known.

I saw in #4 that the last question was about the status in July.

May I ask what it looks like at the moment?

**Comment by ebaauw** [comment]
I’m slowly but surely converting all my plugins (3 down, 3 to go), saving the best for last.  Homebridge-hue has by far the most users, and I want to make sure I’ve ironed out all issues before messing it up.  I don’t have a planning - this is a hobby project.

**Comment by Mallepi** [comment]
All right, all right. I keep my fingers crossed that everything will work out and it won't take quite as long.

Thank you for your work.
