### ISSUE TITLE
 Problem with Dual ID LED Controller (RGB + CCT) (Resolved)

### ISSUE THREAD

**Issue by MacDyson909** [ebaauw/homebridge-hue#537]
Hello,
I installed 3 LED controllers with double ID (RGB + CCT)
Everything worked for several hours then the CCT controllers have disappeared from Home (They appear in the interface "config-u-x" but we can not operate them). When activated by APP Hue, the trace is visible in the logs. I tried to delete them, reinstall the plug-in but without success ... I need help at this point ... :-(
(The only thing I would have changed would be an icon in the app hue, but I'm not sure it's correlable...)
Thx in advance for your precious help

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3659343/homebridge-hue.json.gz)

**Comment by MacDyson909** [comment]
But i have a question :
How to force to ungroup CCT and RGB in this configuration ?

Regards

**Comment by ebaauw** [comment]
They're not grouped; they are two services of the same accessory.  As of iOS 13, Apple's Home app displays that in a single tile rather than a tile per service.

**Comment by MacDyson909** [comment]
Yes, i finally understood... again thanks for all

Sébastien Mies

________________________________
De : Erik Baauw <notifications@github.com>
Envoyé : vendredi, septembre 27, 2019 12:08 PM
À : ebaauw/homebridge-hue
Cc : MacDyson909; Author
Objet : Re: [ebaauw/homebridge-hue] Problem with Dual ID LED Controller (RGB + CCT) (Resolved) (#537)


They're not grouped; they are two services of the same accessory. As of iOS 13, Apple's Home app displays that in a single tile rather than a tile per service.
