### ISSUE TITLE
Philips LivingWhites plugs / Expose only a special Philips Hue light

### ISSUE THREAD

**Issue by Rimbaud1854** [ebaauw/homebridge-hue#538]
With Firmware Update 1933144020 of the hue bridge the Philips LivingWhites plugs are not dimmable anymore in HomeKit. Therefore I want to expose the LivingWhites with Homebridge-hue, but not all the other Philips Hue lights. Because the LivingWhites are a Philips product, they are not exposed with parameter nativeHomeKitLights set to true.

Is there a way to expose only a special Philips Hue light but not all the other ones? If not, could you implement such a configuration parameter? It could be very useful for people with LivingWhites plugs.

**Comment by ebaauw** [comment]
Use the API to create a whitelist resourcelink with the `/lights` resources of the you LivingWhites.  See https://github.com/ebaauw/homebridge-hue#configuration.

**Comment by Rimbaud1854** [comment]
It works! Thanks for your answer! Even the error message in the Hue app has disappeared.

**Comment by hanwalt** [comment]
This is my current config:

        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "excludeSensorTypes": [
                "CLIPGenericStatus"
            ],
            "groups": true,
            "hosts": [
                "192.168.179.6"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "scenes": true,
            "scenesAsSwitch": true,
            "sensors": true,
            "users": {
                "001788FFFE7FA8EB": "TWGcH5dw27kfW8blRwXHwxDqINTE4tGKPxtFGNAW"
            },
            "platform": "Hue"
        },

**Comment by hanwalt** [comment]
Still any help is highly appreciated because I tried a lot but nothing works.

**Comment by hanwalt** [comment]
One more try. Can someone tell me the PH command to whitelist the LWL001
