### ISSUE TITLE
Can i use only deconz without hue bridge?

### ISSUE THREAD

**Issue by curla92** [ebaauw/homebridge-hue#539]
Can i use only deconz? When i try to use only user id deconz, homebridge ask to me hue button press link.

**Comment by ebaauw** [comment]
What’s your config.json?

**Comment by curla92** [comment]
"platforms" : [
    {
      "nativeHomeKitSensors" : false,
      "host" : "",
      "waitTimeUpdate" : 20,
      "nativeHomeKitLights" : false,
      "rules" : false,
      "lights" : true,
      "excludeSensorTypes" : [
        "CLIP",
        "Geofence",
        "Daylight"
      ],
      "schedules" : false,
      "timeout" : 5,
      "heartrate" : 2,
      "group0" : false,
      "wallSwitch" : false,
      "sensors" : true,
      "platform" : "Hue",
      "rooms" : false,
      "lowBattery" : 25,
      "groups" : false,
      "waitTimeResend" : 300,
      "users" : {
        "00212EFFFF040DBC" : "F418F196A9",
        "001788FFFE639977" : "FmNZhFmHidRzGNjhXIOmNiUM9mCQMEuuSD5GR3Df"
      },
      "parallelRequests" : 10,
      "resource" : true
    }

**Comment by ebaauw** [comment]
Looks like you have both deCONZ and a Hue bridge.  Use the `host` setting to specify only the hostname or ip address of deCONZ.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by curla92** [comment]
Oh perfect, with host function specified it works. Very thanks.
