### ISSUE TITLE
Incorrect Light Color option for light group

### ISSUE THREAD

**Issue by tomky** [ebaauw/homebridge-hue#543]
#### Issue

I created a light group containing only Hue White Ambiance bulbs in Deconz. These bulbs can only change the temperature but not color. Nevertheless, when the group is exposed to HomeKit through homebridge-hue, it receives the option to change the color too, which will fail if you really do so. This makes it impossible to adjust their temperature in Home app due to the interface. 

Notice that when only lights are exposed, the HomeKit correctly hide the color option for these bulbs. 

Not sure if this bug belongs to deconz or homebridge-hue.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Homebridge-hue simply exposes the attributes that deCONZ exposes for the group.
