### ISSUE TITLE
Hue Bluetooth bulbs support

### ISSUE THREAD

**Issue by yucar** [ebaauw/homebridge-hue#546]
Has anyone figured out how to connect Phillips Hue new Bluetooth bulbs to Homebridge? For example, using integrated Bluetooth on a Raspberry Pi, not using a Hue Bridge. Maybe using another add-on? Thanks

**Comment by ebaauw** [comment]
Afaik Signify haven’t (yet?) published the Bluetooth API.  You might want to monitor the Hue developer forum, https://developers.meethue.com/develop/get-started-2/.

**Comment by CaseyCZ** [comment]
Any update?

**Comment by joconcepts** [comment]
Any news?
