### ISSUE TITLE
Node 12.13 support 

### ISSUE THREAD

**Issue by KIBkz** [ebaauw/homebridge-hue#547]
Node 12.13 support Need

**Comment by Larsn1** [comment]
Would it be too hard to at least give some hints what you are trying to achieve with that? What are the pro‘s of having that?

Please also keep in mind that Erik is using his free time to provide us features that apple denies us to have which would otherwise be expensive.

**Comment by pponce** [comment]
I just updated and it looks like it has 12.13.0 as a dependency now.

**Comment by KIBkz** [comment]
Thx!
