### ISSUE TITLE
deCONZ - Heartrate

### ISSUE THREAD

**Issue by marcelkordek** [ebaauw/homebridge-hue#548]
#### Issue
deCONZ heartrate though connected via websocket

Hi,
is it normal that the bridge (deCONZ - Conbee II) is polled despite websocket connection?

Greetings,
Marcel

**Comment by ebaauw** [comment]
Yes, not all info is yet provided over the web socket.   If you want, you can reduce the polling interca by setting `heartrate` to 30 sec.

**Comment by marcelkordek** [comment]
Ok, thank you 😊
