### ISSUE TITLE
Exposed gatway cannot be removed from favorites in Home.app

### ISSUE THREAD

**Issue by jpawlowski** [ebaauw/homebridge-hue#551]
Referring to #524, it seems that it is also not possible to disable the "Include in Favorites" option.

I don't really get it, why is this object in Homekit required at all? Exposing light bulbs using other software would never show a dedicated device w/o any function. Okay there is the "Homebridge" gateway object, that's totally fine. But the Phoscon-GW (in my case) is only there to show manufacturer details which don't seem that important to me to be shown at the front page.

**Comment by zany92** [comment]
First of all, congratulation for this great plugin, I love it as it gave me access to tones of Zigbee devices including Xiaomi without adding a chinese bridge in my ecosystem. I faced the same problem. Last iOS version, last homebridge version but after few trials, I was finally be able to remove Phoscon GW from the favorites.

**Comment by andrbnt** [comment]
@zany92 Can you tell me how you was able to remove it from favorites?

**Comment by distantnative** [comment]
@zany92 Would also be very interested in. I don't even see the switch to show/hide it as favorite. Quite annoying sadly.

**Comment by eliassylvain** [comment]
Hello,

iOS 14.1, I have the same issue, impossible de removed the bridge from favorites in Home.app.
Version of the plugin : v0.12.0.

Can someone help please ?

Congrats for this powerful plugin !

![IMG_3042](https://user-images.githubusercontent.com/68815997/99278701-b29ade80-282f-11eb-8055-09328e881ac7.jpg)

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/issues/767#issuecomment-695763159
