### ISSUE TITLE
Hue Sync Box support?

### ISSUE THREAD

**Issue by leoneleone** [ebaauw/homebridge-hue#552]
Hue Sync Box (new HDMI) support:
1. Power Toggle the Sync Box
2. Switch to turn on and off (Start/Stop) light Syncing. 

The basic function fro the iOS Hue Sync.app would be great. 
I think Hue will be slow to develop Home.app integration for the HDMI Sync Box unfortunately. The two functions mention above are much needed as controllable switches in HomeKit.

Do you think you can add that to your plugin?

**Comment by ebaauw** [comment]
homebridge-hue already supports stopping syncing, since that’s supported by the (regular) Hue API, see #496.  I won’t be supporting the Hue entertainment API, which is required to start syncing.  I don’t even know if the HDMI box provides an API.

**Comment by MadMonkey87** [comment]
There seems to be an api, but I haven't figured out how to use it yet. There is also no documentation available an not even release note or something similar. Using https://[box ip]/api you get the following promising response:
`serviceType":"huesync","deviceType":"HSB1","support":[{"version":1,"path":"/v1","level":3`

Seems /api/v1 would be the way to go but you only get an "invalid token" message. No idea how to get one so far😑

**Comment by leoneleone** [comment]
@MadMonkey87 
https://developers.meethue.com/philips-hue-can-become-a-natural-ingredient-of-any-gaming-movie-or-audio-experience-we-believe-that-lighting-can-provide-a-new-level-of-spacial-immersion-join-us/

**Comment by MadMonkey87** [comment]
@leoneleone that is the entertainment api the hue sync box is using and not an api to controll the box itself.

**Comment by mctd** [comment]
Here are some info about the Sync Box API based on my personal research.
The box serves a REST API on SSL (self-signed cert). Authentication is made with JSON Web Tokens (JWT). I'm still working on finding how to get a fresh token, but spoofing the token of my phone, i manage to get it work. Here are some basic info, more to come :

Operation | URL | Method | data | Variables
-- | -- | -- | -- | --
Get current state | /api/v1 | GET |   |  
Change mode | /api/v1/execution | PUT | {   "mode": "_MODE_" } | _MODE_: passthrough \| powersave \| video \|   music \| game
Change brightness | /api/v1/execution | PUT | {  "brightness": 50 } | 0 -> 200
Change intensity | /api/v1/execution | PUT | { "_MODE_": { "intensity": "_INTENSITY_" } } | _MODE_: video \| music \| game   _INTENSITY_: subtle \| moderate \| high \|   intense

**Comment by ebaauw** [comment]
Looks like the Sync Box might get native HomeKit support: https://www.macrumors.com/2020/01/07/philips-hue-new-outdoor-lights/.

**Comment by MadMonkey87** [comment]
I've found out a few more things, like color palattes for the music mode and even a new ambient mode (see https://github.com/MadMonkey87/InnerCore.Api.HueSync)

**Comment by ebaauw** [comment]
https://developers.meethue.com/develop/hue-entertainment/hue-hdmi-sync-box-api/

**Comment by MadMonkey87** [comment]
> https://developers.meethue.com/develop/hue-entertainment/hue-hdmi-sync-box-api/

Pretty cool, I've updated my library already. It is pretty much the same api as described here. In addition, the secret for the registration has been dropped and IR codes and presets have been addes
