### ISSUE TITLE
Reboot Hue Bridge

### ISSUE THREAD

**Issue by Mallepi** [ebaauw/homebridge-hue#553]
Hi,

i have a question for you, is it possible to reboot the Hue Bridge via the shell or your Plugin? I saw in the iconnecthue app that it is possible to reboot the hue bridge from the app.

![DAC39E89-9881-4E65-BA81-AD8E72AA716E](https://user-images.githubusercontent.com/55745258/67978737-0cc40400-fc1b-11e9-8d19-f996a1d2fd4b.jpeg)

I searched the API and didn't find anything and I tried your PH tool. All without success.

Do you have any idea if this is possible?

Thanks!!!

**Comment by ebaauw** [comment]
Not that I know of.  Better ask this at the Hue developers forum.

**Comment by Mallepi** [comment]
Thanks for the tip. I searched the developer forum but found nothing on the topic.

I'm surprised that nobody is interested in the topic yet to restart the hue bridge remote without a outlet.

I had hoped that you know something about it.
