### ISSUE TITLE
Hue Motion Sensors reports 0,0001 lux instead of just 0

### ISSUE THREAD

**Issue by merdok** [ebaauw/homebridge-hue#555]
Hi,

I have noticed that the Hue motion sensors which i have connected to a Conbee 2 gateway report the lux level as 0,0001 lux in the Home app instead of just 0. The deconz REST api reports the correct values of:
```
"lightlevel": 0,
"lux": 0
```

Can this be fixed?

**Comment by ebaauw** [comment]
Actually, the REST API doesn't report the correct values; a `lightlevel` of 0 corresponds to 0.0001 lux, see section 2.7.1 in https://developers.meethue.com/develop/hue-api/supported-devices/.

**Comment by merdok** [comment]
Ok, i understand. But when i got the hue motion sensors connected to my hue bridge with the default home integration from philips, they never reported a lux value of 0,0001. So this is something new which i straight noticed when i started using Conbee 2.  
With the hue bridge i think the lowest was 1 lux. And also i find the 0,0001 value really odd and it doesn't make sense, so why not just show it as 0 lux?

**Comment by ebaauw** [comment]
Neither the sensor nor the Hue API reports lux; they only report `lightlevel`.

The Hue bridge would have to translate the `lightlevel` value to lux for HomeKit, just like homebridge-hue.  I don't think I ever looked how the Hue bridge does this translation 

> So this is something new which i straight noticed when i started using Conbee 2.

Actually homebridge-hue has been supporting the motion sensor in HomeKit long before the Hue bridge has.  So the lux value of 0 is actually something new, contradicting their own documentation.

**Comment by merdok** [comment]
Ok. So you think the value of 0,0001 lux is ok and it should stay like that?

**Comment by ebaauw** [comment]
It's the technically correct representation of what the sensor reports.  I was pleasantly surprised that Home and Eve would actually display this value; usually they cut off decimals to a single one or none at all, see e.g. temperature and humidity.

**Comment by merdok** [comment]
I understand that it is technically correct to display the value. But does it really makes sense for the normal user to see 0,0001 lux instead of just 0?

**Comment by ebaauw** [comment]
Honestly, I have no clue.  I don't know any normal users.  I like to think that Apple do, and the fact that Home displays this value is good enough for me.  I base my home automation on HomeKit, so I don't have to deal with the UI.

If I ever were to meet a normal user, I would strongly advice them to buy devices that natively support HomeKit, stay clear of: homebridge; of any multi-vendor ZigBee network (use deCONZ only for dresden elektronik devices); and of a developer's platform like GitHub.

**Comment by merdok** [comment]
I get your point, but what i don't understand what value you or any other user has from showing 0,0001 lux instead of just 0. This 0,0001 value is just confusing from my point of view and it is unnecessary.
