### ISSUE TITLE
How to expose window cover ikea fyrtur

### ISSUE THREAD

**Issue by Martijndevriez** [ebaauw/homebridge-hue#557]
How do i expose window cover ikea fyrtur. 

Like this ?? 

"platforms": [
    {
      "platform": "Hue",
      "users": {
        "001788FFFExxxxxx": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
      },
      "window covering": true
    }
  ]
}

**Comment by ebaauw** [comment]
No, it’s exposed by deCONZ as a `/lights` resource, so you need to set `”lights”: true`.
