### ISSUE TITLE
AnyOn instead of Power On for Group 

### ISSUE THREAD

**Issue by tomky** [ebaauw/homebridge-hue#558]
When using the deconz group exposed by homebridge-hue in HomeKit, I can use Power -> Off (or directly click the icon) to shutdown the light, but it will show errors when I try to turn it on with Power -> On. Nevertheless, I find that “AnyOn -> On” (which can be seen in Eve) can turn on the lights in the group, but not close them. 

Therefore, in order to have better user experience in Home app (can click on the icon to turn on/off the lights directly), I suggest to map AnyOn -> On  to Power -> On in HomeKit when exposing the group.

**Comment by ebaauw** [comment]
>  but it will show errors when I try to turn it on with Power -> On

What errors?

> I suggest to map AnyOn -> On to Power -> On in HomeKit when exposing the group.

Not sure what you mean.

A group resource in the REST API exposes `action.on` to set the (target) `state.on` of its member lights, and `state.all_on` and `state.any_on` to report the (current) state of its member lights.  The _On_ characteristic gets updated when `state.all_on` changes; the _Any On_ characteristic when `state.any_on` changes.  This means the group shows as on in Apple's Home app when all member lights are on.

When changing the _On_ or _Any On_ characteristic, homebridge-hue sets `action.on`.  Setting either characteristic causes all lights to turn on; clearing either characteristic causes all lights to turn off.  Of course, you can only set _Any On_ when its cleared, i.e. when all lights are off, and you can only clear _On_ when its set, i.e. when all lights are on.  So when only some lights are on, you need to turn them off in Apple's Home app, before you can turn all lights on.

**Comment by tomky** [comment]
Thanks for the explanations. Now I find that the behavior of Any On is more likely what I expect from Power for the group resource. 

The error I mentioned is as attached (see TRADFRI wireless accessory, which is a group resource in deconz). When you click the icon in Home or turn Power to off in Eve, all lights go off. But when you click the icon again or turn Power to On, it shows error in Eve and no response in Home. 

![IMG_0122](https://user-images.githubusercontent.com/566352/68475849-3062fc00-0264-11ea-9f04-9bbdc39faae0.PNG)
![IMG_0121](https://user-images.githubusercontent.com/566352/68475850-3062fc00-0264-11ea-94ea-a97a073a8d2d.PNG)

**Comment by ebaauw** [comment]
What does the homebridge log show?

**Comment by tomky** [comment]
Unfortunately, no related log entity is shown after I click the icon. 

I checked the code and find that it is due to Line 1201 in HueLights.js. If I add a constraint ( && this.type !== 'group' ), then the Power On works correctly in HomeKit.

**Comment by ebaauw** [comment]
Did you set `wallswitch` in config.json?  It shouldn’t be set for a group (which doesn’t have `state.reachable`).  The check should have been in line 555 instead.

**Comment by tomky** [comment]
Yes. I have wallSwitch set as true in config.
