### ISSUE TITLE
Bridge Devices in Home App

### ISSUE THREAD

**Issue by simondettling** [ebaauw/homebridge-hue#564]
Hello,

Apologies if this was asked before or if I overlooked something in the documentation.

Can I specify in the configuration, that homebridge-hue doesn't expose the Bridge Devices as accessories? In my case, I have a Hue Bridge and a Conbee II USB Stick, which Homekit lists as unsupported devices in the Home App.

![20191120_194821000_iOS](https://user-images.githubusercontent.com/38430400/69272922-b32a7600-0bd7-11ea-9cfb-95653702e4f5.jpg)

Thanks.

**Comment by ebaauw** [comment]
No, see #76.

**Comment by simondettling** [comment]
Overlooked that one. Thanks.
