### ISSUE TITLE
Plugs show up as lights

### ISSUE THREAD

**Issue by lepatrick** [ebaauw/homebridge-hue#566]
Hey @ebaauw 
I love your work and have huge setup in my home. It works without any issues. :)

I'm using deCONZ (2.05.66) an RasperryPi 4 and I connect some Osram Smart Plugs and tested innr SP 120 plug tooo.

In deCONZ both plus shown as plug. But in homebridge as light, so it's normal that they shown in Apple HomeKit as light to. My Fritz plugs, connected using different plugin shown up in homebridge as plug.

Is there any why to set them to plug, because if I say Siri turn out the light, the turn off music to. :(

Looking forward to your ideas, many thanks!

Best regards,
Patrick

**Comment by ebaauw** [comment]
See #402, #532,  https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0.
