### ISSUE TITLE
pairing diyhue with homebridge hue fails

### ISSUE THREAD

**Issue by andre68723** [ebaauw/homebridge-hue#567]
following setup
1.  v2 Bridge (.4)
2. diyhue (.59) for some lights 

V2 bridge is discovered and correctly setup with user.
diyhue added in hosts

```
            "hosts": [
                "192.168.0.4",
                "192.168.0.59"
            ],
```
but it's not getting to the point a user is created on startup 

```
[11/30/2019, 20:17:08] [Hue] warning: latest version: homebridge-hue v0.11.44
[11/30/2019, 20:17:08] [Hue] 192.***.***.59: bridge request 1: get /config
[11/30/2019, 20:17:08] [Hue] 192.***.***.59: bridge error 1: unauthorized user
[11/30/2019, 20:17:08] [Hue] Philips hue: Philips BSB002 bridge v1935144020, api v1.35.0
```

**Comment by ebaauw** [comment]
Did you setup diyhue for pairing with a new app?  https://diyhue.readthedocs.io/en/latest/configuration.html#pairing-diyhue-with-the-hue-app

**Comment by andre68723** [comment]
Hi,
I removed the hw bridge .4 and left only the .59 in + rm users
```
        {
            "name": "Hue",
            "forceEveWeather": true,
            "hosts": [
                "192.168.0.59"
            ],
            "hueMotionTemperatureHistory": true,
            "lights": false,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "platform": "Hue"
        }
```

activated the button via
http://{IP_ADDRESS}/hue/linkbutton + ACTIVATE

still no change though
```
[12/5/2019, 19:34:40] [Hue] 192.***.***.59: bridge request 7: get /config
[12/5/2019, 19:34:40] [Hue] 192.***.***.59: bridge error 1: unauthorized user
heartbeat lost, close socket and reconnect
closed the socket and retry
```

Also checked this one here
https://diyhue.readthedocs.io/en/latest/configuration.html#pairing-diyhue-with-the-hue-app

**Comment by ebaauw** [comment]
It would seem diyhue doesn’t implement the Hue API in full.  In particular, the unauthenticated GET of `/config` to get the `bridgeid`.  Homebridge-hue calls this before generating the username (API key).  I won’t be able to change that.

As a workaround, you could try to create a username manually and enter that in config.json.

**Comment by andre68723** [comment]
Hi, I am able to locate bridge + user in diyhue config.json and entered them
```
            "hosts": "192.168.0.59",
            "users": {
                "B827EBFFFEE0B274": "b684ae2613aa11ea900ab827ebe0b274"
            },
```
Nevertheless the /config path still is accessed with the hue app user entered 
```
[12/7/2019, 12:37:35] [Hue] 192.***.***.59: bridge request 460: get /config
[12/7/2019, 12:37:35] [Hue] 192.***.***.59: bridge error 1: unauthorized user
retry connect (0) ...: 0x000000000571d45c
```

**Comment by ebaauw** [comment]
Damn.  This is a brilliant catch-22.  I store the username (API key) under the bridge ID, to handle changing IP addresses or bridge names.  Therefore, I need to retrieve the bridge ID before I can do an authenticated request.

**Comment by andre68723** [comment]
resolved via a fix by diyhue, can be closed. Thanks!
https://github.com/diyhue/diyHue/commit/b9e567c4e987338da1c938ca2b30a8f5e7a2f2f3
