### ISSUE TITLE
wallSwitch

### ISSUE THREAD

**Issue by Jeffaffa** [ebaauw/homebridge-hue#570]
Hi,

After the last update the "wallSwitch": true, option is not working anymore.
The lights(tradfri) that i use in multiple rooms with a original wall switch keep the status on when there physically turned off. Before the status got turned off due to no response.

**Comment by ebaauw** [comment]
Update from what version?  Please attach debug dump file and debug log file when powering off and on some of your lights.  See README how to create the debug files.

**Comment by Jeffaffa** [comment]
I see this in the logging. That should indicated that it recognise that the bulb is not responsive right ?

[12/4/2019, 5:47:02 PM] [Hue] Overloop 2: homekit on changed from 1 to 0
[12/4/2019, 5:47:02 PM] [Hue] Overloop 1: homekit on changed from 1 to 0
[12/4/2019, 5:47:04 PM] [Hue] Overloop 2: homekit on changed from 0 to 1
[12/4/2019, 5:47:04 PM] [Hue] Overloop 1: homekit on changed from 0 to 1
[12/4/2019, 5:47:27 PM] [Hue] Overloop 2: set homekit status fault from 0 to 1
[12/4/2019, 5:47:28 PM] [Hue] Overloop 1: set homekit status fault from 0 to 1

In homekit it self the status does not change to off by it self.

**Comment by ebaauw** [comment]
Odd.  I’m gonna need the debug files after all.

**Comment by Jeffaffa** [comment]
I need to check on how to get the debug files. 

Also what I noticed is that the blubs from Ikea are always available within homekit app to turn on or off even when there is no physical power on them. While the original hue blubs say "no response". 
If I turn the Ikea blubs on from the homekit app I do not get the message after a while "set homekit status fault from 0 to 1". If I turn the Ikea blubs off from the hue app they will turn off in the homekit app. I am using a Apple TV as hub.

**Comment by ebaauw** [comment]
Do you expose the Hue lights using homebridge-hue, or using the Hue bridge?

**Comment by Jeffaffa** [comment]
I expose the hue lights with the hue bridge.
Only the Ikea lights use the homebridge-hue.

"name": "Hue",
            "excludeSensorTypes": [
                "CLIPPresence",
                "Geofence"
            ],
            "hosts": [
                "192.168.1.112"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "sensors": false,
            "wallSwitch": true,

**Comment by ebaauw** [comment]
> While the original hue blubs say "no response".

That's done by the Hue bridge.

> If I turn the Ikea blubs on from the homekit app I do not get the message after a while "set homekit status fault from 0 to 1".

That means that the Hue bridge doesn't mark it as `"reachable": false`.  Depending on the number of lights connected to your bridge, this might take several minutes.

> I installed the beta version.

Stupid question: you did restart homebridge after that?   Are you sure you installed homebridge globally (`sudo npm -g`) as well?

> I need to check on how to get the debug files.

See README.

**Comment by Jeffaffa** [comment]
I did a fresh installation of the homebridge. With the same results.
The status in the app does not get updated. The debug file is in the attachement.

I am not sure cause i never paid attention to the logs before. But after these lines:

Overloop 1: light reachable changed from true to false
homebridge_1  | [12/7/2019, 9:31:49 AM] [Hue] Overloop 1: set homekit status fault from 0 to 1

should it not have another line like this ?

[Hue] Overloop 1: homekit on changed from 1 to 0


[debug hue.txt](https://github.com/ebaauw/homebridge-hue/files/3934931/debug.hue.txt)

**Comment by ebaauw** [comment]
> [12/7/2019, 9:28:07 AM] [Hue] homebridge-hue v0.11.44, node v12.13.1, homebridge v0.4.50

You're not running the beta version

**Comment by Jeffaffa** [comment]
Your right. I thought it would overwrite the current version but it didn't. We have been going back and forward over the v0.11.44 version. I uninstalled that version manually and install the beta. I can confirm 0.11.45 is intalled now and the lights status do get updated now. So it works again. Do u want a debug still ?

homebridge_1  | [12/7/2019, 10:47:53 AM] [Hue] Klerenkamer 2: set homekit status fault from 0 to 1
homebridge_1  | [12/7/2019, 10:47:53 AM] [Hue] Klerenkamer 2: not reachable: force homekit on to 0
homebridge_1  | [12/7/2019, 10:47:53 AM] [Hue] Klerenkamer 2: set homekit on from 1 to 0

**Comment by ebaauw** [comment]
No, I'm good.  I'll include the fix in the next version.

**Comment by Jeffaffa** [comment]
Thanks for the help and support.
