### ISSUE TITLE
Mi wireless switch not being not being exposed to homebridge

### ISSUE THREAD

**Issue by msantagata** [ebaauw/homebridge-hue#573]
Hi everyone, 
first of all thanks @ebaauw  for the great work you did on this plugin - I'm using it to expose to homekit a few Mijia window/door sensors that are connected to a ConBee without any issue.
Now I'm trying to add and expose a Mijia wireless switch (WXKG01LM): It gets correctly paired on the Phoscon App, but it seems that it's not exposed to homebridge/homekit and I can't see it in the home app. Can you help me understand what I'm missing?
In my homebridge configuration I have:

```
    "platforms": [
        {
            "name": "Hue",
            "hosts": [
                "192.168.1.7:8023"
            ],
            "lights": true,
            "sensors": true,
            "platform": "Hue"
        }
    ]
```
All the window/door sensors are still working perfectly, and I'm sure that the wireless switch is working (I have tested it on the Xiaomi app).
Thanks for your help!

**Comment by ebaauw** [comment]
Please attach the [debug dump file](https://github.com/ebaauw/homebridge-hue#debug-dump-file) and the [debug log file](https://github.com/ebaauw/homebridge-hue#debug-log-file).

**Comment by msantagata** [comment]
Here they are @ebaauw , thanks for looking into this!

[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/3937199/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3937200/homebridge-hue.json.gz)

**Comment by msantagata** [comment]
@ebaauw , I promise I don't know why- but I see the switch correctly now!
I'll close the issue, sorry for the false alarm :)
