### ISSUE TITLE
Exposing a Philips Hue Smart Plug in Homekit to take advantage of the wallSwitch feature

### ISSUE THREAD

**Issue by ptrvg** [ebaauw/homebridge-hue#575]
#### Issue

I hope I can ask this question here, because its not really an issue.
I want to expose one of my Philips Smart Plugs in HomeKit with Homebridge-Hue to take advantage of the wallSwitch feature to set the plug as off in HomeKit when it gets unreachable. (I use the plug in combination with a regular wall switch.)
At the moment I use native Homekit support for all devices that support it with Homebridge-Hue. I would like to continue my setup like that, except expose that one smart plug with Homebridge-Hue. Is that possible or do I have to expose all Homekit compatible devices to take advantage of this feature?

thanks,

Peter

#### Log Messages

```
```

**Comment by ebaauw** [comment]
You can create a whitelist resourcelink to expose the plug, overwriting `nativeHomeKitLights` for that resource only.  Note that `wallSwitch` will not work if you expose the plug as _Outlet_.

**Comment by ptrvg** [comment]
Thanks, I overlooked the whitelist feature. Sorry! You can close this. And thanks for a wonderful plugin!
