### ISSUE TITLE
Documentation:"Note that you need a home hub..." not clear

### ISSUE THREAD

**Issue by qlp** [ebaauw/homebridge-hue#576]
What is exactly meant with the "Note that you need a home hub..." in the 'wireless switches' section?

I have a Hue Bridge and the Zigbee network also has a couple of "Busch-Jaeger Light Link wall-mounted transmitters". These transmitters are not known by the Hue Bridge (and AWAIK that is not possible), but I would like to act on button presses in HomeKit. 

What do I need to do to make that possible? Replace my Hue Bridge with deCONZ / RaspBee?

**Comment by ebaauw** [comment]
You need an AppleTV, HomePod, or iPad configured as Home hub for HomeKit automations and HomeKit remote access to work.  Stateless switches are useless in HomeKit without a Home  hub.  See the link in the **Prerequisites** section.

To expose switches (or any device) to HomeKit, homebridge-hue needs support by the Hue bridge and/or deCONZ gateway.  If the Busch-Jaeger switches aren't exposed by the Hue bridge, there's nothing for homebridge-hue to expose to HomeKit, so yes, you'd need deCONZ and a RaspBee (or ConBee).
