### ISSUE TITLE
Aqara QBKG03LM - Warning message on ZHASwitch at Homebridge-Hue initialization

### ISSUE THREAD

**Issue by ychieux** [ebaauw/homebridge-hue#578]
#### Issue
Warning message for lumi.ctrl_neutral2 for an AQARA QBKG03LM (Double rocker wall switch no neutral)

Is this warning message caused by a problem on DeconZ end (e.g. incomplete support of Aqara device) or on homebridge-hue end with the querying of the deconz api?

#### Log Messages
```
Dec 16 20:19:39 homebridge homebridge[5944]: [12/16/2019, 8:19:39 PM] [Hue] Phoscon-GW: /sensors/26: ZHASwitch "lumi.ctrl_neutral2"
Dec 16 20:19:39 homebridge homebridge[5944]: [12/16/2019, 8:19:39 PM] [Hue] Phoscon-GW: /sensors/26: warning: ignoring unknown ZHASwitch sensor {"config":{"on":true,"reachable":true,"temperature":3300},"ep":4,"etag":"b39b5d878a1976ce8a4722abd1664a4f","manufacturername":"LUMI","mode":1,"modelid":"lumi.ctrl_neutral2","name":"lumi.ctrl_neutral2","state":{"buttonevent":1002,"lastupdated":"2019-12-16T16:02:29"},"swversion":"04-25-2018","type":"ZHASwitch","uniqueid":"00:15:8d:00:03:a2:d2:29-04-0006"}
```

**Comment by ebaauw** [comment]
homebridge-hue does not support the wireless switch function of the `lumi.ctrl_neutral` switches.  The wired switch function is supported as a light.

Are you using the switch with the buttons decoupled from the wired output?

**Comment by ychieux** [comment]
Thank you Erik for your switft reply.
I did not decouple the buttons, I only paired the switch with DeconZ and moved on.

**Comment by ebaauw** [comment]
Then there doesn’t seem a need to expose the wireless switch function to HomeKit?

**Comment by ychieux** [comment]
So all in all this warning message is justified by the unsupported wireless switch function, I should therefore move the sensors/26 to the blacklist to avoid such warning message in the future or is there a better way?

**Comment by ebaauw** [comment]
Or simply ignore the warning.
