### ISSUE TITLE
npm WARN ws@7.2.1

### ISSUE THREAD

**Issue by thusithapk** [ebaauw/homebridge-hue#579]
Getting these WARN messages now at update or install.

npm: 6.12.1
node: v12.13.1

```
$ sudo npm install -g homebridge-hue
/usr/local/bin/dc_eventlog -> /usr/local/lib/node_modules/homebridge-hue/cli/dc_eventlog.js
/usr/local/bin/hap -> /usr/local/lib/node_modules/homebridge-hue/cli/hap.js
/usr/local/bin/json -> /usr/local/lib/node_modules/homebridge-hue/cli/json.js
/usr/local/bin/ph -> /usr/local/lib/node_modules/homebridge-hue/cli/ph.js
/usr/local/bin/upnp -> /usr/local/lib/node_modules/homebridge-hue/cli/upnp.js
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
```

**Comment by ebaauw** [comment]
I’m afraid this is beyond me.  See https://github.com/websockets/ws/pull/1626.

I take it homebridge-hue still works, in spite of these warnings?

**Comment by thusithapk** [comment]
Yes homebridge-hue works fine.

**Comment by smare** [comment]
I'm still understanding when peer dependencies are necessary for an app to work.  Should we install these dependencies (I'm still getting these warnings on install)?  Earlier versions of npm automatically installed peer dependencies so I'm thinking that's the recommendation, but I appreciate any insight into this (I've been reading [this](https://nodejs.org/es/blog/npm/peer-dependencies/) and [this](https://medium.com/@sergioviniciuss/how-do-peerdependencies-work-837d0ff8f63f).)

**Comment by ebaauw** [comment]
> I'm still understanding when peer dependencies are necessary for an app to work.

That really depends on the application or module that lists the peer dependencies.

> Earlier versions of npm automatically installed peer dependencies

Ancient versions, from way before my time.

> Should we install these dependencies (I'm still getting these warnings on install)?

I think they recently introduced [optional peer dependencies](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md ), which the latest version of `ws` seems to use.  No need to install these.  The latest `npm` versions no longer issues warnings for these.

**Comment by smare** [comment]
Thanks for the detailed response!

**Comment by Hou-xiaoxu** [comment]
Thank You

**Comment by Hou-xiaoxu** [comment]
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ws@7.4.2 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.2 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/cli-plugin-eslint@4.5.11 requires a peer of eslint@>= 1.6.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/cli-plugin-typescript@4.5.11 requires a peer of @vue/compiler-sfc@^3.0.0-beta.14 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/cli-service@4.5.11 requires a peer of @vue/compiler-sfc@^3.0.0-beta.14 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/eslint-config-typescript@5.1.0 requires a peer of @typescript-eslint/eslint-plugin@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/eslint-config-typescript@5.1.0 requires a peer of @typescript-eslint/parser@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-vue@6.2.2 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.1.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.1.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.2.1 requires a peer of eslint@>=1.6.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
npm WARN @vue/eslint-config-typescript@5.1.0 requires a peer of @typescript-eslint/eslint-plugin@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @vue/eslint-config-typescript@5.1.0 requires a peer of @typescript-eslint/parser@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-vue@6.2.2 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.1.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.1.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.2.1 requires a peer of eslint@>=1.6.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
