### ISSUE TITLE
Update to v.11.8

### ISSUE THREAD

**Issue by jacdec** [ebaauw/homebridge-hue#581]
Hello 

I just tried to update my homebridge-hue to v.11.8. This is what happened. What do I have to do?
![Unbenannt](https://user-images.githubusercontent.com/32842953/71198503-32bd6a80-2294-11ea-8650-a0c1b32408f6.JPG)

I'm curious to test the v.11.8 to get my Eurotronics Spirit thermostat working with DeConz.

Thanks in advance!

**Comment by ebaauw** [comment]
v0.11.8 is ancient; current version is v0.11.44.  homebridge-lib and homebridge-hue-utils are no longer separate packages, they're included in homebridge-hue.  Best uninstall any old versions and re-install (only) homebridge-hue:
```
$ sudo npm -g un homebridge-hue homebridge-hue-utils homebridge-lib
$ sudo npm -g i homebridge-hue
```

**Comment by dergreg** [comment]
This is a bit off topic, but would you mind providing a script that updates all dependencies (Node, deConz, homebridge-hue) at once? Or at least the process how you do it manually? Without warranty, of course 😉 That would be great.

I‘m not very familiar with npm and frightened to “brick“ my configuration.

**Comment by ebaauw** [comment]
That's undoable, as every environment differs.  I've installed NodeJS and deCONZ on my Raspberry Pi, so they're updated together with Raspbian when running `sudo apt update` followed by `sudo apt upgrade`.  See https://github.com/nodesource/distributions/blob/master/README.md and https://phoscon.de/en/conbee2/install#raspbian

`npm` is the NodeJS package manager, see https://docs.npmjs.com.
