### ISSUE TITLE
Requiring Node 12.14.0 Could Cause Issues With Plugins that Don't Support Node 12 Yet

### ISSUE THREAD

**Issue by mkellsy** [ebaauw/homebridge-hue#583]
#### Issue

Currently your node requirement in package.json is set to 12.14.0.
```
"node": "^12.14.0"
```

Not all plugins are ready for Node LTS yet. Does your plugin run in Node 10.17.0? If so, can you reduce the requirement?

#### Log Messages

```
[Homebridge] [12/21/2019, 07:33:18] Plugin /home/hoobs/.hoobs/node_modules/homebridge-hue requires Node version of ^12.14.0 which does not satisfy the current Node version of v10.16.3. You may need to upgrade your installation of Node.
```

**Comment by ebaauw** [comment]
I develop and test against the latest LTS version of NodeJS.  Other versions might work or not.

**Comment by mkellsy** [comment]
Thanks for NOT helping.
