### ISSUE TITLE
no scenes in homekit using deconz

### ISSUE THREAD

**Issue by sokki** [ebaauw/homebridge-hue#584]
#### Issue
I'm currently setting up deconz with homebridge-hue. Running them on the same pi using docker. 
Everything seems to work fine, but Homekit does not show my scenes.

Homebridge print them in the debug log like `[12/23/2019, 2:39:06 PM] [Hue] Phoscon-GW: /groups/1/scenes/3: "Büro Minimal"`
I do see some strange errors in the logs: `[Config] [homebridge] Error: ETIMEDOUT`

#### Config
Versions:  `homebridge-hue v0.11.45, node v12.14.0, homebridge v0.4.50, deCONZ gateway v2.5.71, api v1.16.0` 
```
{
    "bridge": {
        "name": "Homebridge EDFE",
        "username": "xxx,
        "port": 8080,
        "pin": "xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "host": "192.168.1.28",
            "users": {
                "xxx": "xxx"
            },
            "groups": true,
            "group0": true,
            "scenes": true,
            "sensors": true,
            "nativeHomeKitSensors": false,
            "excludeSensorTypes": [
                "CLIPPresence",
                "Geofence"
            ],
            "lights": true,
            "nativeHomeKitLights": false,
            "wallSwitch": true
        }
    ]
}
```

#### Log Messages

```
[12/23/2019, 2:39:06 PM] [Hue] Phoscon-GW: /groups/1/scenes/1: "Büro Chill"
[12/23/2019, 2:39:06 PM] [Hue] Phoscon-GW: /groups/1/scenes/2: "Büro Work"
[12/23/2019, 2:39:06 PM] [Hue] Phoscon-GW: /groups/1/scenes/3: "Büro Minimal"
```

```
[12/23/2019, 2:39:31 PM] [Config] [homebridge] Error: ETIMEDOUT
[12/23/2019, 2:39:36 PM] [Config] [homebridge-hue] Error: ETIMEDOUT
[12/23/2019, 2:39:36 PM] [Config] [homebridge-config-ui-x] Error: ETIMEDOUT
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3995229/homebridge-hue.json.gz)

[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/3995244/homebridge.log.gz)

**Comment by sokki** [comment]
I got a bit further. After doing 
```
pi@raspberrypi:~ $ docker exec homebridge ./node_modules/.bin/ph post /resourcelinks '{
  "name": "homebridge-hue",
  "classid": 1,
  "description": "whitelist",
  "links": [
    "/groups/1",
    "/groups/2",
    "/groups/3",
    "/groups/4",
    "/groups/5",
    "/groups/6",
    "/groups/7",
    "/groups/8",
    "/groups/9"
  ]
}'
"58"
```
I finally got the scenes in the Eve app as something I can turn on (which triggers the scene) and turns back to off automatically. 
The scenes still dont show up in the Apps Home and Home+ tho 🤔

**Comment by ebaauw** [comment]
HomeKit rooms, groups, scenes, automations, and even user-defined names can only be maintained by HomeKit apps, using the HomeKit API.  HomeKit accesories, which use the HAP protocol, cannot see, let alone change these.

Looks like the ETIMEDOUT errors are reported by homebridge-config-ui-x.

**Comment by sokki** [comment]
Thanks for the detailed explanation! That clears up a lot of my confusion.
