### ISSUE TITLE
Error while using the plugin with Hoobs

### ISSUE THREAD

**Issue by MasterofKungfu9999** [ebaauw/homebridge-hue#585]
Hi

I'm using the plugin with the Hoobs-Version of homebridge:

I'm getting following issue when i hit the hue-button:

[Homebridge] [12/23/2019, 21:26:32] [Hue] Philips hue: created user - please edit config.json and restart homebridge[Homebridge] "platforms": [[Homebridge] {[Homebridge] "platform": "Hue",[Homebridge] "users": {[Homebridge] "xxxxxx": "xxxxx"[Homebridge] }[Homebridge] }[Homebridge] ][Homebridge] [12/23/2019, 21:26:32] [Hue] Philips hue: 1 accessories[Homebridge] [12/23/2019, 21:26:32] [Hue] cannot create /home/hoobs/.hoobs/etc/@hoobs/hue.json.gz: error ENOENT[Homebridge] [12/23/2019, 21:26:32] [Hue] Initializing platform accessory 'Philips hue'...[Homebridge] [12/23/2019, 21:26:32] [Hue] Philips hue: 2 services

**Comment by ebaauw** [comment]
Looks like a problem with the hoobs setup.  Homebridge-hue expects to be able to write to the homebridge user directory.

**Comment by MasterofKungfu9999** [comment]
Thanks @ebaauw 
I thougt it was an plugin issue because the plugin is Hoobs certified
