### ISSUE TITLE
State status is not updated

### ISSUE THREAD

**Issue by suhajda3** [ebaauw/homebridge-hue#587]
Hello,

I usually see that homebridge-hue doesn't update the current state of my devices. I tried it with Tasmota switches (in Hue bridge mode) and IKEA TRÅDFRI on/off switch (connected to a Hue bridge v2) the state of the device status is never updated. For example if I turn a Tasmota switch off through it's web interface or turn a TRÅDFRI switch on through Alexa the new state in not respresented in Homebridge. Only the status that has been made inside Homebridge (HomeKit) is represented and it's not updated. If I turned a switch on in HomeKit but turned it off with Alexa, HomeKit still show the switch is turned on.

What could be the problem?

Thank you!

**Comment by ebaauw** [comment]
Could be one of two things:
1. The HomeKit app has lost the subscription to receive update notifications from the HomeKit accessory (i.c. homebridge).  Try and refresh the screen in the HomeKit app: if the new values show, this is the issue.  Best force-close the HomeKit app and restart it, or reboot your iDevice;
2. The Hue bridge hasn't (yet) updated it's cache of the device state.  I'm not sure what devices you're referring to, are these wired in-wall switches to smartify dumb lights?  If you control these outside the Hue bridge, you'll need to wait for the bridge to poll the device, before it updates its cache and homebridge-hue sees the change.  The more lights connected to the bridge, the longer this takes.  If you control these devices from the Hue app, you should see the changes immediately (modulo homebridge-hue's heartbeat), as the Hue bridge updates the cache as it controls the device.

If you check the homebridge log, you should be able to tell whether homebridge-hue sees state changes reported by the Hue bridge.  If it does, it's issue 1; if it doesn't it's issue 2.

**Comment by suhajda3** [comment]
1. It's not issue 1 because I check it on Homebridge Config UI X as well and it shows tha same state I see in the HomeKit app.
2. I don't think it's issue 2 either because [Tasmota](https://github.com/arendst/Tasmota) mimicks a Hue bridge so if I change the state on it's own web interface I doubt it is just cached and not updated right away. I only see a change state in the homebridge logs if I change the state in the HomeKit app. If I change it on the Tasmota web interface it won't update.

I have a Sonoff Basic Module. I use Tasmota version 6.7.1.

**Comment by ebaauw** [comment]
Please capture and attach a full debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and also attach the debug dump file (https://github.com/ebaauw/homebridge-hue#debug-dump-file).

**Comment by suhajda3** [comment]
Sorry for the late reply.

I have attached the debug log and debug dump files.

Here is what I during capture:

> 17:17: Balcony is OFF
> 17:18: turned the Balcony ON in it's web interface
> 17:20: homebridge-hue still didn't recognize the new state of the Balcony so I turned it ON with the HomeKit app (this way homebridge-hue recognizes the new state)
> 17:21: turned Balcony OFF in it's web interface, homebridge-hue doesn't recognize new state, still thinks it's ON

The Balcony is a Tasmota device but the same applies to my Christmas tree which is a IKEA TRADFRI control outlet.

My Hue bridge v2 doesn't have this problem. When I turn on a light with a physical remote I can see the change immediately in the HomeKit app.

Thank you!

[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4066156/homebridge.log.gz)

**Comment by suhajda3** [comment]
[homebridgehue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4066234/homebridgehue.json.gz)

**Comment by ebaauw** [comment]
The creation of the debug dump file fails (the one you attached is ancient), because (one of?) your Tasmota device(s) doesn't expose `/config/ipaddress`:
```
Jan 15 17:18:17 raspberrypi homebridge[12904]: [1/15/2020, 17:18:17] [Hue] TypeError: Cannot read property 'split' of undefined
Jan 15 17:18:17 raspberrypi homebridge[12904]:     at HuePlatform.maskHost (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:373:20)
```
Because the dump fails, the heartbeat isn't started, so homebridge-hue won't poll the bridges and won't get updates of the light states.

What version of Tasmota are you using?  It should expose `/config/ipaddress`, see #512.

**Comment by ebaauw** [comment]
v0.11.48 should start the heartbeat, even when creating the debug dump file fails.

**Comment by suhajda3** [comment]
> What version of Tasmota are you using?

I am using Tasmota version 6.7.1

I have updated homebridge-hue to v0.11.49 and everything works perfectly!

Thank you for your great support!
