### ISSUE TITLE
IKEA Trådfri on/off switch appears as a light in HomeKit

### ISSUE THREAD

**Issue by suhajda3** [ebaauw/homebridge-hue#588]
Hello,

I have a IKEA Trådfri on/off switch connected to a Hue bridge v2 (I have no Trådfri gateway). Homebridge-hue recognizes the device but exposes it to HomeKit as a light. Strangely Alexa recognizes the same device as a plug. Would it be possible to expose the IKEA Trådfri on/off switch as a plug to HomeKit?

Thank you!

**Comment by ebaauw** [comment]
> I have a IKEA Trådfri on/off switch

What device is that?  Do you mean the [Trådfri Control Outlet](https://www.ikea.com/nl/en/p/tradfri-wireless-control-outlet-90356166/)?

To expose `/lights` and/or `/groups` resources as _Outlet_, create a resourcelink on the Hue bridge.  See https://github.com/ebaauw/homebridge-hue/releases/tag/v0.10.0.

**Comment by suhajda3** [comment]
> What device is that? Do you mean the Trådfri Control Outlet?

Yes, that's it!

Thank you! I have created a resourcelink and now it shows up as and outlet.

**Comment by max-christian** [comment]
Why does Homebridge-hue no longer try to determine whether a /lights resource should be exposed as an Outlet service to HomeKit? I'm interested in restoring this functionality so everything works without having to create a resource link. At present, installing the default config and saying "Hey Siri, turn all the lights on" results in every smart plug in the home switching on, which is not a sensible default.

**Comment by ebaauw** [comment]
Simply put: because that turned out to be unfeasible.  Too many devices report the wrong device type and get incorrectly exposed: lights as _Outlet_ or outlets and wired switches as _Lightbulb_.  You might actually use a plug or wired wall switch to control a light, wanting to expose it as _Lightbulb_.  And then there’s no easy way to deal with heterogenous groups.

**Comment by albi** [comment]
Can't follow the instruction: "run ph outlet -v" Where should I do that?
