### ISSUE TITLE
Typo in homebridge-hue/wiki/Configuration

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-hue#589]
#### Issue

There is a typo in https://github.com/ebaauw/homebridge-hue/wiki/Configuration as follows:

The word wether is incorrectly. It should be whether, not wether:

resource | true | Flag **wether** to expose Resource characteristic.Set to false, to reduce the memory footprint of the accessories exposed by homebridge-hue.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
It's a Wiki, feel free to correct this yourself.

**Comment by raulfunkie** [comment]
How? It doesn't let you really edit if you're not a contributor.

**Comment by ebaauw** [comment]
Damn, I don't have a test login for GitHub, so I cannot see that.  I did find a setting that I changed.

Anyways, while at it, I corrected the typo.
