### ISSUE TITLE
Heimann (HS1CG) GAS Sensor

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#592]
Hello Erik and a happy new year .-)

I am thinking about buying this sensor from Heimann (HS1CG) soon. I would like to integrate it into Homekit via deconz and homebridge-hue. I did not find it in the list of compatible devices from homebridge-hue. So I would like to ask you first if you see a possibility to make it compatible with homebridge-hue when I buy it?

In the list of compatible deCONZ devices the sensor is listed.

Thanks!

Greetings Nastra

**Comment by Nastras** [comment]
Okay, I got tomatoes on my eyes. The sensor is already supported 👍

![05415ECF-F0E4-4B2A-9693-534E176520FB](https://user-images.githubusercontent.com/27686185/71747956-63df9280-2e71-11ea-9429-1cd69ec8482a.jpeg)

At least I wished you a happy New Year 😄

Sorry to ask.

**Comment by ebaauw** [comment]
Heiman seem to be refreshing their devices.  Same functionality, but different _Model Indentifier_, that needs to be whitelisted in deCONZ.

homebridge-hue will still expose most unknown sensors (albeit with a warning message); only switches need to be whitelisted explicitly, as deCONZ still doesn't provide a way to specify the possible button events.
