### ISSUE TITLE
Dimmer issue/problem?

### ISSUE THREAD

**Issue by buczo23** [ebaauw/homebridge-hue#594]
Hi there, I'm looking (as I can't find that in the documentation) for a possibility to "code" (somehow?) functionality which will give an option to use single/double/triple/quadruple press and long press together to exposed via Homebridge Philips hue dimmer switch. Is it possible?. I'm asking because via Homekit I can fully control multiple vendors Hue, Ikea and the cheapest Milight bulbs. None of known to me 3rd parties tools like iConnectHue or others can't do that. So I will repeat my question is it possible to achieve that via hue plugin to expose more actions than single/long press for buttons 1,4 and single press for the rest of them?

**Comment by ebaauw** [comment]
No, the Hue dimmer switch only reports press, hold, release, and release after hold.

**Comment by buczo23** [comment]
Ah, so it is stateless. Hmm, any possibilities to control the state, even temporary let's say for the 30seconds, the status could be sored locally (posix file) or in any key-value storage memcached/consul/etc? Did you try to investigate how it works over iConnectHue where it is possible to program more sophisticated action mentioned by me?

**Comment by ebaauw** [comment]
In theory, I could, I could check whether a second, third, fourth click happens within a given time period and issue a _Double Click_ to HomeKit.  I’m not going to do that, because it won’t work reliably with a Hue bridge that needs to be polled, since it doesn’t send notifications.  Because of this polling, button events in brief succession will go unnoticed.

**Comment by buczo23** [comment]
Understood. In theory, iConnectHue register new "service" in Hue API, which is treated as a separate device?. That is my theory about how iConnectHue developers achieve that. So the reliability raises if we concern this type/method. Every other press for every button is registered as another device? Maybe that is the clue for achieving that via Homebridge. This functionality programmed over iConnectHue works well if you understand how it works, but iConnectHue can't control bulbs which are not connected via Hue Bride so it could be a nice upgrade for this plugin. It could be enabled on-demand Attaching a screenshot with the mentioned registered new devices if it helps you somehow?:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/8618811/71836653-bfe62900-30b4-11ea-82a4-e69c36ee777a.png">

**Comment by ebaauw** [comment]
>  iConnectHue register new "service" in Hue API, which is treated as a separate device?. That is my theory about how iConnectHue developers achieve that.

If they do that, it should be visible in the debug dump file, as some CLIP sensors and associated rules.

**Comment by buczo23** [comment]
I can see only events which are associated with predefined rules/events like:
`homekit button single press
homekit button long press'

Double/Tripple pressing aren't visible in log file, so that theory fallen down now :-)

Other options? Can you help me with that?

**Comment by ebaauw** [comment]
The _dump_ file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by buczo23** [comment]
This one, ok. These xfiredesigns devices appear after re-editing dimmer actions in their app. I'm not sure are them responsible for double/triple presses.

``"name":"Press state XFDHueTap2Btn1","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"A718F3E1-8D11-45FA-8B1B-768973AC","recycle":false},"17":{"state":{"status":0,"lastupdated":"2020-01-06T17:26:52"},"config":{"on":true,"reachable":true},"name":"Press state XFDHueTap2Btn2","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"B5D78CD8-6F5D-4D6A-841D-23BC6D9D","recycle":false},"20":{"state":{"status":0,"lastupdated":"none"},"config":{"on":true,"reachable":true},"name":"Press state XFDHueDim3Btn1000","type":"CLIPGenericStatus","modelid":"ButtonState","manufacturername":"xfiredesigns","swversion":"1.0","uniqueid":"CD13BFC0-1412-49DF-8908-4967A029","recycle":false}},"resourcelinks":{"28080":{"name":"przełącznik Salon","description":"Resources of przełącznik Salon","type":"Link","classid":10011,"owner":"***********************************6","recycle":false,"links":["/sensors/3","/rules/9","/rules/10","/rules/8","/rules/7","/rules/6","/rules/5","/sensors/20","/scenes/0VflTppTdr465t3","/scenes/utZEnL8hEm6ZfwW","/scenes/J5a4yFIWGFYDN5K","/scenes/bBvJnQl5JhZD17H"]},"55694":{"name":"przełącznik","description":"Resources of przełącznik","type":"Link","classid":10011,"owner":"***********************************6","recycle":false,"links":["/sensors/2","/rules/3","/sensors/17","/rules/2","/sensors/16","/rules/20","/rules/1","/rules/4","/rules/21"]}}}]}``

**Comment by ebaauw** [comment]
Looks like.  If you can attach the file, I'll have a detailed look.

**Comment by buczo23** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4027504/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
OK, they do _not_ expose button events for double press, etc; they simply activate scenes from the rules on the Hue bridge.  The CLIPGenericStatus sensor counts how many times the button on the Hue dimmer has been pressed recently.  This count is reset automatically after 10 seconds.  They bluntly recall a (different) scene on each press, hoping the last scene recalled will take precedence (which in my estimation could be challenging on larger networks).  I think they'll miss two consecutive presses within a second.

Homebridge-hue exposes Hue bridge resources to HomeKit; it's not a full-blown Hue client.  It won't be maintaining Hue bridge rules (not groups, scenes, CLIP sensors, ...), like iConnectHue.

I suppose in theory, you could create a similar set of rules to drive a CLIPSwitch sensor.  I would be willing to support that sensor in homebridge-hue, so you'd be able to expose that to HomeKit, supporting _Single Press_, _Double Press_, and _Long Press_.  Creating the sensors and corresponding rules, however, is beyond homebridge-hue.

**Comment by buczo23** [comment]
From my point of view, I'm interested in achieving only the mentioned feature like double/triple/.. press. I've tested this it via iConnectHue again, and obviously, you are right, it works sequentially. So there is no point in implementing this questionable function. Thank you for your time, I appreciate that.
