### ISSUE TITLE
Hide/Deactivate Virtual Daylight Sensor

### ISSUE THREAD

**Issue by raulfunkie** [ebaauw/homebridge-hue#595]
#### Issue
I want to hide the Daylight sensor on homebridge/Homekit (I don't want HomeKit to detect and show the sensor on my home app). Is there any way to do that using the config.json?

Also, how can I find the ID of a sensor using Phoscon? I want to modify que sensivity of a Vibration sensor using [this](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1396) but I can't seem to find references as to where to find my SensorID and my apiKEY

**Comment by ebaauw** [comment]
Specify `"excludeSensorTypes": ["Daylight"]`, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

I'm sorry, I don't use Phoscon.  homebridge-hue exposes the ID through the _Resource_ characteristic in HomeKit, but Apple's Home app doesn't support custom characteristics.  Use a decent HomeKit app, like Eve, to see it.

**Comment by raulfunkie** [comment]
Thank you so much for the quick response!

Is there any way to identify my apiKEY? it's another key part of the script I'm supposed to run to customize the sensivity of the sensor.

Thanks once again for the help!

**Comment by ebaauw** [comment]
> Is there any way to identify my apiKEY?

Not anymore.  They recently ~~f*cked up~~ changed the Hue API so that only the API key currently used is reported; other keys are masked and irretrievable.

The API key that homebridge-hue uses is in config.json.  `ph` stores its API key in `~/.ph`

**Comment by raulfunkie** [comment]
just a heads up for everyone trying to change the sensivity of the Vibration Sensor (Aqara / Xiaomi)

This code worked for me:
`curl -H 'Content-Type: application/json' -X PUT -d '{"sensitivity": 1}' http://IP/api/ApiKEY/sensors/SensorID/config`

So for this line of code I used:
- IP is the IP that appears when I launch Phoscon on the raspberry Pi in this case.
- The API Key is the one that appears on the config.json (/.homebridge)
- Use an app like Eve Home to find the ID of the sensor you want to manipulate.

It returned this:
`[{"success":{"/sensors/6/config/sensitivity":1}}]`

Hopefully this means it went through and it was able to perform the change. I wonder if I need to restart phoscon, homebridge or anything for these to take effect or they just happen at once. Anybody got any idea of this?

**Comment by ebaauw** [comment]
The sensitivity is stored on the vibration sensor itself.  No need to restart anything.

**Comment by raulfunkie** [comment]
Thank you! I managed to get the info from the sensor using almost the same command above and it returned the sensivity set to 1 so should be working good.

Thanks for the help!
