### ISSUE TITLE
Hide Incompatible ROM001 button

### ISSUE THREAD

**Issue by martinorob** [ebaauw/homebridge-hue#596]
Hi, I have 3 new Hue Button that I haven't configured on the Hue App but only on the Home App.
This button now are present on the Home because are incompabile with home app and I can't hide.

I have read all the Issues closed and put this on my config
but they are still there.

How I can hide it?
Thank you

			"sensors": true,
			"nativeHomeKitSensors": false,
			"lights": true,
                        "excludeSensorTypes": ["Daylight", "CLIP", "Geofence", "CLIPPresence"],
  	                "linkButton": false,
                        "wallSwitch": false

**Comment by ebaauw** [comment]
I haven’t come across the Hue button yet.  Could you please attach the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file) so I can see what it looks like (from an API perspective) and add support.

I don’t think homebridge-hue would currently expose anything for the Hue button, not even an unsupported accessory.  To confirm, could you please capture and attach a debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file.  I think the buttons are exposed by the Hue bridge itself.  Other than not exposing the bridge to HomeKit at all, I’m not aware of anyway to limit the devices the Hue bridge exposes.

**Comment by martinorob** [comment]
Thank you 

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4036085/homebridge-hue.json.gz)
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/4036086/homebridge.log)

**Comment by ebaauw** [comment]
Ok, looking at the log, homebridge-hue _is_ exposing the ROM001 buttons.  I’ll add support for them, so you’ll no longer see unsupported accessories.  To prevent homebridge-hue from exposing them, either exclude `ZLLSwitch` In `excludedSensorTypes` (but that will also not expose any Hue dimmer switch) or create a blacklist resourcelink for these `/sensors` resources.

**Comment by martinorob** [comment]
It worked like a charm! Thank you!!!
