### ISSUE TITLE
Zigbee Lights using hue stuck in a color loop

### ISSUE THREAD

**Issue by CMaxim77** [ebaauw/homebridge-hue#597]
#### Issue

Lights always cycle in a color loop, the plugin works great otherwise.

Maybe there is something I’m missing in the configuration? Is there to option to just use a static color?
#### Log Messages

```
```

**Comment by ebaauw** [comment]
Homebridge-hue neither sets nor reports colour loops.

**Comment by CMaxim77** [comment]
It’s strange, only the lights that I expose are doing it. If I expose them with home Assistant they don’t do that but with the homebridge hue they are more reliable to switch on/off. Thanks for the response!

**Comment by ebaauw** [comment]
What types of light are these?  Did you use another Hue app to set the lights into colour loop effect?  I would think that the effect would be cancelled when turning the light off, but I’m not sure.  Power cycling the light should definitely cancel the effect.

You should be able to turn off colour looping by PUTting `{"effect": "none"}` to the light state.  Using `ph`, you’d issue:
```
$ ph put /lights/1/state '{"effect": "none"}'
```
Replacing `1` with the ID of your light.  In Eve, see the _Resource_ characteristic to find the ID.

**Comment by ebaauw** [comment]
v0.11.48 supports colorloop, so you can turn it on or off form HomeKit.  Note that you need a decent HomeKit app, as Apple's Home doesn't support custom characteristics.

**Comment by CMaxim77** [comment]
Yes, I’m sorry I didn’t respond earlier. I just unplugged the power and plugged it back in. That immediately stoped the color loop. I use the native HomeKit app but also use Home+ for more complex automations. I sincerely thank you for the work you put into this add on. And the time you took to reply and help get this corrected. I absolutely love this community!
