### ISSUE TITLE
Philip Light Bulb Bluetooth Support

### ISSUE THREAD

**Issue by artnos** [ebaauw/homebridge-hue#598]
I was just wondering, if this plugin supports Philip Light Bulb Bluetooth without the Philip Bridge

**Comment by ebaauw** [comment]
No.

**Comment by artnos** [comment]
i know you do this in your free time, do you think that is planned for the future or its not possible since its bluetooth. And only WIFI devices work with plugins.

**Comment by ebaauw** [comment]
Homebridge-hue connects to the Hue bridge, using the Hue API.  This is a RESTful API over IP.  For homebridge-hue to talk to the lights directly, they would have to implement the same API.  The CHIP initiative aspires to talk IPv6 to devices, over Wifi, bluetooth, 802.14.5, and more, but it will be some time before they’ll deliver.  Even then, I doubt that new standard will be retro-fitted to existing devices.  Even then, no way a light will expose the full Hue API.

**Comment by artnos** [comment]
thank you for explaining.
