### ISSUE TITLE
Feature request: reboot hue bridge

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#599]
Good morning Erik,
as I was also looking for a way to restart the Hue Bridge via the API, I came across this issue #553

Unfortunately @Mallepi did not get back on this topic. So I tried to get some information myself because there is nothing about it in the api.

I wrote to the developer of the iconnecthue app and he told me how to restart the bridge over the api.

I have tested it with your ph tool and it works:
ph -H 192.168.XXX.XX -u <KEY> put /config '{"reboot":true}'

Would it be possible that you include this function in your plugin and show a switch on the bridge for the reboot?

King Regards
Nastras

**Comment by ebaauw** [comment]
Cool, I’ll have a look.  deCONZ offers an API to restart the gateway, which `ph restart` uses, but I didn’t know Hue offered one as well.

Not sure you’d want to expose this to HomeKit.  Ideally, you’d restrict this function to HoneKit administrators, but no-one seems to know how to do this.

You definitely don’t want to use a standard switch - Siri will reboot the bridge when you tell her to switch on the room the bridge is in.  It’ll have to be exposed using a custom characteristic, which Home won’t support.  So you’ll have to use Eve, or some other HomeKit app.  Or create a scene in Eve and recall that from Home.

**Comment by Nastras** [comment]
Glad to hear you're implementing it!

If you implement it as a custom characteristic switch on the Bridge device it would be enough. I don't want to have additional devices for a function :-)

Did I understand you correctly above, you also implement it for the deconz Gateway?

**Comment by ebaauw** [comment]
Hm, dusted off my old gen-2 Hue bridge to do some testing:

- Indeed, it responds to the reboot command, as described above.  It does reset something (the API server is unavailable between ~2 and ~15 seconds after the command), but it doesn't do a full reboot (as in power-cycle).
- They seem to have changed the logic for the _Daylight_ sensor, `/sensors/1`.  It's `state.lastupdated` is no longer updated on power-cycle (or after reboot);
- They seem to have changed the logic for CLIPGenericFlag sensors: their `state.flag` is no longer reset to `false` on power-cycle (or after reboot);
- This means that my _Boot Time_ CLIP sensor and rules no longer work.

Double checked my gen-1 Hue bridge (even more dust to clean):
- Indeed, it responds to the reboot command as well;
- The _Daylight_ and CLIP logic hasn't changed, and the _Boot Time_ sensor and rules work as before.

**Comment by ebaauw** [comment]
In v0.11.48.

**Comment by Nastras** [comment]
Hi, cool that you already put it in. Thanks 🙏 
I just tested it and it funktioniert👍

What I noticed is that the restart option is located under colorloop. Should it be?

![4DBA02CC-146F-4485-A046-BDE66BC310AA](https://user-images.githubusercontent.com/27686185/72626401-f476a200-394a-11ea-9edb-f31973ab6c8e.jpeg)
![B603EC35-94B7-415C-941A-6156B8EF6014](https://user-images.githubusercontent.com/27686185/72626402-f50f3880-394a-11ea-8096-8d83c78cab4c.jpeg)


> but it doesn't do a full reboot (as in power-cycle).
Do you think it is a big difference to the power cycle reboot?

**Comment by ebaauw** [comment]
> What I noticed is that the restart option is located under colorloop. Should it be?

Good catch!  No, it shouldn't.  I mistakenly used the same UUID for both characteristics.  Fixed in homebridge-lib v4.4.13.  If you re-install homebridge-hue, it should pick up this version.

**Comment by Nastras** [comment]
Bug is fixed after re-install.
Once again a big thank to you👌

**Comment by Nastras** [comment]
I noticed one other little thing. The description in ph for restart would have to be adapted 🤓

![9E8A98D1-29E3-4755-BE86-BC643D44C851](https://user-images.githubusercontent.com/27686185/72641816-48917e80-396b-11ea-9934-12499b5a87a9.jpeg)
