### ISSUE TITLE
Siri response and color not accurate

### ISSUE THREAD

**Issue by danlee6992** [ebaauw/homebridge-hue#60]
First off great plugin!! I have (2) issues, even when all the lights respond to the command Siri says the following: "OK. I've communicated with the lights, but some of them aren't responding." The other issue is when I ask the lights to go to white, some do and some turn red?

**Comment by ebaauw** [comment]
@danlee6992  This sounds like it could be the same issue as #59 when using HomeKit scenes.  Could you try v0.2.3 and see if things improve?

If not, could you please post the output of `homebridge -D` from startup through to some of the Siri commands?

**Comment by danlee6992** [comment]
Thank you. V0.2.3 works like a charm!! I appreciate your help.
