### ISSUE TITLE
Recent update disables bridge "button"

### ISSUE THREAD

**Issue by rcoletti116** [ebaauw/homebridge-hue#601]
#### Issue
I just updated to latest version 0.11.47. I previously had a device representative of the Hue Bridge's button, which could be used to trigger automation. After the update the  button function no longer works. Instead the device shows up as a tile with a home icon that says not supported. I do not believe this is the same issue as #76 or #580 which was dismissed as a duplicate.

**Comment by ebaauw** [comment]
No, it's not the same issue.  I removed support for the link button in [v0.11.22](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.22), with the release of Hue bridge firmware with API v1.31.0.  As of that version, the API no longer supports resetting the link button, so homebridge-hue cannot detect a second press of the link button for another minute or so.

Do you still have a round gen-1 Hue bridge?  They haven't updated the API for that model beyond v1.16.0.  Or did you manage not to upgrade your sqaure gen-2 bridge firmware all this time?

I might have been too forthcoming removing the functionality altogether, as it would still work on a gen-1 bridge.

**Comment by rcoletti116** [comment]
I have a gen-2 bridge. Its very possible I am on outdated firmware. I do not often update intentionally because I have burned too many times by devices being crippled or altogether bricked by bad firmware. I will roll back to 0.11.21 and see if this fixes things up for me.

**Comment by rcoletti116** [comment]
Roll-back to 0.11.21 did the trick for me. I should be able to hold tight on that for while until I find an alternative homekit button.

**Comment by ebaauw** [comment]
v0.11.50 re-introduces support for the Hue bridge link button.  By default, the _Stateless Programmable Switch_ will be exposed for any Hue bridge running on firmware with API version before v1.31.0.  As before, homebridge-hue will reset the link button state immediately after detecting the button press, so you cannot create new API keys (usernames) by pressing the button.  Instead, use the _Link_ characteristic exposed under the Hue bridge accessory.

Note that homebridge-hue needs to poll `/config` to detect link button presses, so this will cause additional load on the bridge.  Set `"linkbutton": false` in config.json to prevent exposing the switch and polling `/config`.

Set `"linkbutton": true` in config.json to force exposing the switch, even on Hue bridges with a later Hue API version, which no longer supports resetting the link button state.  Note that in this case, homebridge-hue will only detect another button press, 30 sec or longer after a previous button press.

**Comment by rcoletti116** [comment]
Thanks for doing this! Works great.

**Comment by jensflorian** [comment]
Note: Signify support for 1st gen Bridge ends April 30th 2020. After this time the device is no longer secured.
