### ISSUE TITLE
Update to v0.11.48 failed

### ISSUE THREAD

**Issue by zigistar** [ebaauw/homebridge-hue#602]
Just tried updating homebridge-hue to v0.11.47 but unfortunately it failed. I'm running home bridge w/ homebridge-config-ui-x v4.7.0, where I got an notification that a new update of homebridge-hue is available. I got the following error message:

![Bildschirmfoto 2020-01-17 um 23 09 09](https://user-images.githubusercontent.com/57197922/72650033-7da7cc00-397f-11ea-9611-7f5076569f15.png)

I also attach the log file:
[2020-01-17T22_08_33_547Z-debug.log](https://github.com/ebaauw/homebridge-hue/files/4079315/2020-01-17T22_08_33_547Z-debug.log)

Thanks for your help + greetings from Austria

**Comment by ebaauw** [comment]
It's an error by `npm` itself.  I'm sorry, I have no idea what's causing it.

Have you tried uninstalling homebridge-hue and re-installing it?

**Comment by zigistar** [comment]
Yes, unfortunately the same error message :-(

![Bildschirmfoto 2020-01-17 um 23 46 33](https://user-images.githubusercontent.com/57197922/72651444-a5992e80-3983-11ea-94ed-31d626271909.png)

Reboot of Raspi done + all updates

- sudo apt-get update
- sudo apt-get upgrade
- sudo n stable
- sudo npm install -g npm@latest

installed.

Really strange - currently I don't have any more idea

**Comment by ebaauw** [comment]
If you run `sudo npm -g homebridge-hue` from the command line?

**Comment by suhajda3** [comment]
I had no problem updating to v0.11.49 (from v0.11.47) with homebridge-config-ui-x.

Are you running the latest Node.js and npm versions? Homebridge Config UI X displays them under the Status tab System Information widget.

**Comment by ebaauw** [comment]
Yes, I am.  It’s not related to the versions.  There’s some magic behind `npm` that’s beyond my comprehension.  The dependency tree looks different when installing with `npm -g` vs `npm`.  I think I did something in v0.11.48 that `npm -g` doesn’t mind, but `npm` chokes on.

**Comment by zigistar** [comment]
running sudo npm -g i homebridge-hue from the command line solved the problem for me. Now update to the new version work. Thanks a lot for your quick reply and your help.
