### ISSUE TITLE
Scene will not be added in Homekit

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#605]
Good morning,

I'm just testing your new scene feature. Great feature! 

Unfortunately not all scenes are shown to me.  So far I have managed that 1 scene in Homekit is displayed.

I have created a room kitchen with one scene and a group ceiling lamp kitchen with three scenes in hue. So far only under the group ceiling lamp kitchen a scene was shown in Homekit.

It looks as if the other scenes are not queried or passed to Homekit.

So far I have restarted hue bridge, separated Homebridge-hue from Homekit and added it again. I deleted the scenes and added them again.

Do you have any ideas?

Thanks a lot!

Greetings Nastras

Config:
},
"excludeSensorTypes": ["CLIPGenericStatus","CLIPGenericFlag","ZHATemperature","Daylight","Geofence"],
"nativeHomeKitLights": false,
"nativeHomeKitSensors": false,
"sensors": false,
"lights": false,
"scenes": true,
"groups": true,
"rooms": true,
"resource": false,
"linkbutton": true,
"lowBattery": 10,
"heartrate": 2,
"parallelRequests": 20,
"timeout": 5,
"waitTimeResend": 300,
"waitTimeUpdate": 100
}
]
}

Scenes in the group ceiling lamp kitchen in Hue:
![IMG_1FC57AC4E13B-1](https://user-images.githubusercontent.com/27686185/73118459-b3871a80-3f54-11ea-8144-efc0a791b422.jpeg)

Scenes in the group ceiling lamp kitchen in HomeKit:
![IMG_4350213AE7F2-1](https://user-images.githubusercontent.com/27686185/73118465-c1d53680-3f54-11ea-97d6-f34565255d3d.jpeg)

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4111755/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Can you please attach the debug dump file?

**Comment by ebaauw** [comment]
The "Hell" scene has the expected `appdata`, but the "Xenon" and "Szene 1" scenes don't, so homebridge-hue ignores them.  I think you did something different when creating the "Hell" scene, versus the other two scenes.  I have no idea what that would be, though.

It looks like you created the scenes in Hue Essentials instead of in the official Hue app?

I hadn't noticed before, but the scenes are created as `GroupScene` scenes.  I double-checked the Hue app, and it creates `GroupScenes` as well.  These scenes contain a `group` attribute, linking them to the associated group, so there's actually no reason for homebridge-hue to parse the `appdata`.

**Comment by ebaauw** [comment]
Could you try v0.11.51-0?  Install through `sudo npm -g i homebridge-hue@beta`.

**Comment by Nastras** [comment]
> I think you did something different when creating the "Hell" scene, versus the other two scenes.

Yeah, I did too. In the App Hue Essentials he offered me to create the Philips standard scenes while creating the group. There I once confirmed with yes. I think there were 6 scenes created by the app. But before I looked into HomeKit I had deleted all but one of them.

The other two scenes I created manually with the app.


> Could you try v0.11.51-0?

I'll try it now.

**Comment by Nastras** [comment]
Good news, after I installed the beta all scenes will be shown 💪👍

![IMG_7F1C4B437EE4-1](https://user-images.githubusercontent.com/27686185/73122124-78e7a700-3f81-11ea-8ac5-535ad62d76b4.jpeg)

**Comment by ebaauw** [comment]
Cool.  I'll create a full release later this weekend.

**Comment by Nastras** [comment]
Great, I'm looking forward to it.)

**Comment by Nastras** [comment]
Erik, short offtopic question for you, can you tell me if it is possible to switch on or off multiple lamps in one command via the API or ph?

So far, my orders look like this:
ph -H 192.168.178.XX -u XXXXXX put /lights/ID/state '{ "on": true }'

**Comment by ebaauw** [comment]
Sure, that’s what groups are for.

**Comment by Nastras** [comment]
I almost expected the answer 😅

Background of my question is that I don't want to display certain devices in homekit because I control them as a group via a cmd plugin. If I define these devices as group in hue then I can't specify true in the config for groups. 

I wanted to save myself the work of working with blacklist and whitlist 😉

Alternatively you could work with && between the commands or a script but which has a slight delay between commands.

Do I have to think about it again. Thanks!

**Comment by Nastras** [comment]
I just created scenes manually with the app iconnecthue, but unfortunately they are not included in the current beta. If I create them manually with huessential they are transferred to HK.  
The scenes are displayed in both apps.

The Philips standard scenes created by heuteessential when creating a group will still be displayed.


Yesterday I only tested with huessential, sorry -.-

**Comment by Nastras** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4113425/homebridge-hue.json.gz)

**Comment by Nastras** [comment]
One more note: If scenes are created manually in the huessential app, they will not be displayed in iconnecthue. Are there so many different ways to create a scene?

**Comment by ebaauw** [comment]
> Are there so many different ways to create a scene?

Yes, see https://developers.meethue.com/develop/hue-api/4-scenes/.

v1 scenes are created by a PUT to `/scenes`; v2 scenes by a POST to `/scenes`.  With v2 scenes, you can specify the `type`: `"LightScene"` or `"GroupScene"`.  Only the latter are linked to a group, and exposed by homebridge-hue.

Looks like iConnectHue creates light scenes.  HueEssentials and the official Hue app create group scenes.

**Comment by Nastras** [comment]
Okay, that explains the behavior. I was surprised that the iconnecthue app asks if you want to keep the scenes when you delete a group. With huessential it does not ask.

Do you have an idea for a solution to show both kinds of scenes?

I will continue to create my scenes with huessential now, seems to be the better option Philips itself uses or do you see it differently?

**Comment by ebaauw** [comment]
> I was surprised that the iconnecthue app asks if you want to keep the scenes when you delete a group. With huessential it does not ask.

Because group scenes are linked to the group, they're automatically deleted when the group is deleted.  Light scenes are not linked to a group.  They can actually be recalled from any group, where only the lights that are both in the scene and in the group are effected.  And therein lies the problem: it seems overkill to expose these scenes under all groups, especially for groups that have no lights in common with the scene.

How does iConnectHue recall the scenes?  By group/room, or for all lights?  I suppose, I could expose light scenes (and even v1 scenes) under group 0 (all lights).  You'd have to expose that group, by setting `group0` in config.json.

**Comment by Nastras** [comment]
> How does iConnectHue recall the scenes?

This depends on whether the scene was created under the rooms or groups. The scene is always only displayed where it was created.

> They can actually be recalled from any group, where only the lights that are both in the scene and in the group are effected

The scenes are not created or displayed across groups even if the same lamps are present.

> And therein lies the problem: it seems overkill to expose these scenes under all groups, especially for groups that have no lights in common with the scene.

I'm with you.

> I suppose, I could expose light scenes (and even v1 scenes) under group 0 (all lights). You'd have to expose that group, by setting group0 in config.json.

I just tried it, under group 0 no scene is displayed that was created in iconnecthue.

**Comment by ebaauw** [comment]
Sorry, I said "I could".  I hadn't done this yet.  Could you try beta  v0.11.51-1?

**Comment by Nastras** [comment]
> Sorry, I said "I could". I hadn't done this yet.

Sorry, I missed that. 
My English is not the best.-)

I have now installed the beta and displayed group 0. S
everal scenes are shown there, also those of iconnecthue. This one has a red border.

The other scenes tell me nothing.


![IMG_0046](https://user-images.githubusercontent.com/27686185/73138059-cbe35c00-405e-11ea-99cc-b61ebbec3a8e.PNG)
![IMG_0047](https://user-images.githubusercontent.com/27686185/73138063-ce45b600-405e-11ea-9045-cdd217d86fd9.jpg)

**Comment by ebaauw** [comment]
You have some old v1 scenes on your bridge.  If none of your apps show them, you can delete them thru the API.

**Comment by Nastras** [comment]
I hadn't even looked at the API. I've deleted that now. 
Now they're gone under group 0 too.

Thanks!

**Comment by ebaauw** [comment]
Published v0.11.51.
