### ISSUE TITLE
Hue bridge link button is not displayed

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#606]
Hello me again.)

unfortunately the link button is not shown on my site. I thought it should be possible again since version 0.11.50? Or have I understood something wrong?

I have already published my config.json in :
#605

![IMG_24710A1DCC4B-1](https://user-images.githubusercontent.com/27686185/73118571-3a88c280-3f56-11ea-8a2f-7228c04b80c2.jpeg)

Thank you very much for your support.

Greetings Nastras

**Comment by ebaauw** [comment]
What bridge do you have?  What API version?  See https://github.com/ebaauw/homebridge-hue/issues/601#issuecomment-575890606: as of v1.31.0, the Hue API no longer supports setting or clearing the link button thru the API.

**Comment by Nastras** [comment]
Ah, okay, mine is newer. I got it wrong then that it was available again for everyone. Thanks!
