### ISSUE TITLE
Dimdirection

### ISSUE THREAD

**Issue by ronaldvans** [ebaauw/homebridge-hue#608]
Every 5 seconds  the following message is logged in the homebridge log file:

dimDirection: set homekit status from 0 to 1

and 5 seconds later:

dimDirection: set homekit status from 1 to 0

I have been trying to find what causes this but have been unable to do so. Is there anything I can do to resolve this? I don't remember seeing this before in the logs so I don't know whether this was introduced when I installed the latest version of homebridge-hue or maybe because I added some Hue accessories like the Smart Button.

My Setup:

- Philips Hue bridge
- Deconz
- Homebridge + various plugins including homebridge-hue

All updated to the latest version.

**Comment by ebaauw** [comment]
My best guess: you're exposing a CLIPGenericStatus sensor named "dimDirection", which is being changed from rules on the Hue bridge.  The sensor and rules might very well have been created by the Hue app, when you added the Smart Button.

For a better assessment, please attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by ronaldvans** [comment]
Thanks! I excluded CLIPGenericStatus and the entries disappeared.
