### ISSUE TITLE
Where is the bridge added as a homekit accessory?

### ISSUE THREAD

**Issue by grinsekatze003** [ebaauw/homebridge-hue#61]
I'm searching for hours for the piece of code that adds the philips hue bridge to homekit as an accessory. The icon of the tile in Home looks like a House. Can someone point me in the right direction? Thank you.. 👍

**Comment by ebaauw** [comment]
homebridge-hue uses the (old) static platform accessories model, where HAP Accessories are created by homebridge itself, not by the plugin.  Homebridge calls `HuePlatform.prototype.accessories()` to get an array of objects to create accessories for.  Then it calls `getServices()` for each object to get an array of HAP Services to link to the accessory.

**Comment by grinsekatze003** [comment]
I see thanks! But.. where is the Hue Bridge accessory added to HomeKit? When I open Home, I see besides all lights a tile that is called "Philips Hue Bridge", has a house as icon and the text "Unsupported". I can't find where this is added in your code...

**Comment by ebaauw** [comment]
The "not supported" bit is added by Apple's Home app.  See the README, you need another HomeKit app, like Eve to interact with this accessory and change the heartrate.

**Comment by grinsekatze003** [comment]
Ah, I see. Thanks! Homebridge really needs a documentation..
