### ISSUE TITLE
Question: How to add this to eve

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#610]
Hey,

it lost a little bit the focus on all the functions 😂

Is it possible to add all this values to eve for example? That home will not work I know:
![EBCFD980-4811-4503-B4E7-C579A361682A](https://user-images.githubusercontent.com/44058592/73299432-77331300-420f-11ea-81fc-ae521abf27cc.png)

And can I define for which rooms I will do this?

Which config changes do I have to do?

Am I correct that by changing the config in home there are no changes?

Thank you!

**Comment by ebaauw** [comment]
You need to expose the _Wohnzimmer_ group to HomeKit.  It will be visible in Eve and in Home, as a light.  To do so, set `"groups": true` and `"rooms": true` in config.json, or create a whitelist resourcelink that contains the group (see README).  If you (also) set `"scenes": true` in config.json, homebridge-hue will expose an additional (custom) service under the group accessory per scene.  As this is a custom service, Home will not show these, but Eve and other HomeKit apps will.

**Comment by Phoenix-DH** [comment]
Hey, thank you for the fast response!
Will have a look to it.

Means that there will be at least one light with the name of the room exposed to home?
