### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by dixiklo9** [ebaauw/homebridge-hue#612]
I need help. I try to set up a conbee stick, but it doesn't work...

[Homebridge] [1/29/2020, 1:50:52 AM] [Hue] Philips hue: 1 accessories
[Homebridge] [1/29/2020, 1:50:52 AM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebrige-hue.json.gz
[Homebridge] [1/29/2020, 1:50:52 AM] [Hue] Initializing platform accessory "Phoscon-GW".
[Homebridge] [1/29/2020, 1:50:52 AM] [Hue] Phoscon-GW: 2 services
[Homebridge] [1/29/2020, 1:50:52 AM] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d52c3521-e35a-480c-94ab-45ad37cddb42
    at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
    at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:380:26)
    at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:16:19
    at /home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:293:5
    at Function.then (/home/hoobs/.hoobs/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
    at Function.<anonymous> (/home/hoobs/.hoobs/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)

**Comment by ebaauw** [comment]
Did you reset any of your ZigBee devices to pair them to deCONZ, without removing the from the Hue bridge?

**Comment by dixiklo9** [comment]
Yes, now I reset my device and I get an other error...

[Homebridge] [1/29/2020, 11:19:42 AM] [Hue] 192.***.***.29: bridge request 38: get /config
[Homebridge] [1/29/2020, 11:19:42 AM] [Hue] 192.***.***.29: bridge communication error ECONNREFUSED on 192.***.***.29
[Homebridge] [1/29/2020, 11:19:47 AM] [Hue] 192.***.***.36: bridge request 31: get /config
[Homebridge] [1/29/2020, 11:19:47 AM] [Hue] 192.***.***.36: bridge communication error ETIMEDOUT on 192.***.***.36
[Homebridge] [1/29/2020, 11:19:47 AM] [Hue] 192.***.***.36: bridge request 25: get /config
[Homebridge] [1/29/2020, 11:19:47 AM] [Hue] 192.***.***.36: bridge communication error ETIMEDOUT on 192.***.***.36
[Homebridge] [1/29/2020, 11:19:50 AM] [Hue] 192.***.***.29: bridge request 31: get /config
[Homebridge] [1/29/2020, 11:19:50 AM] [Hue] 192.***.***.29: bridge communication error ECONNREFUSED on 192.***.***.29
[Homebridge] [1/29/2020, 11:19:51 AM] [Hue] Phoscon-GW: gateway request 33: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:19:51 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:19:51 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:19:55 AM] [Hue] 192.***.***.26: bridge request 33: get /config
[Homebridge] [1/29/2020, 11:19:55 AM] [Hue] 192.***.***.26: bridge request 27: get /config
[Homebridge] [1/29/2020, 11:19:55 AM] [Hue] 192.***.***.26: bridge communication error EHOSTUNREACH on 192.***.***.26
[Homebridge] [1/29/2020, 11:19:55 AM] [Hue] 192.***.***.26: bridge communication error EHOSTUNREACH on 192.***.***.26
[Homebridge] [1/29/2020, 11:19:57 AM] [Hue] 192.***.***.29: bridge request 39: get /config
[Homebridge] [1/29/2020, 11:19:57 AM] [Hue] 192.***.***.29: bridge communication error ECONNREFUSED on 192.***.***.29
[Homebridge] [1/29/2020, 11:20:05 AM] [Hue] 192.***.***.29: bridge request 32: get /config
[Homebridge] [1/29/2020, 11:20:05 AM] [Hue] 192.***.***.29: bridge communication error ECONNREFUSED on 192.***.***.29
[Homebridge] [1/29/2020, 11:20:06 AM] [Hue] Phoscon-GW: gateway request 34: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:20:06 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:20:06 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:20:07 AM] [Hue] 192.***.***.36: bridge request 32: get /config
[Homebridge] [1/29/2020, 11:20:07 AM] [Hue] 192.***.***.36: bridge communication error ETIMEDOUT on 192.***.***.36
[Homebridge] [1/29/2020, 11:20:07 AM] [Hue] 192.***.***.36: bridge request 26: get /config

**Comment by dixiklo9** [comment]
and now 

[Homebridge] [1/29/2020, 11:26:07 AM] [Hue] Phoscon-GW: gateway request 3: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:26:07 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:26:07 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:26:22 AM] [Hue] Phoscon-GW: gateway request 4: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:26:22 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:26:22 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:26:37 AM] [Hue] Phoscon-GW: gateway request 5: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:26:37 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:26:37 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:26:52 AM] [Hue] Phoscon-GW: gateway request 6: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:26:52 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:26:52 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:27:07 AM] [Hue] Phoscon-GW: gateway request 7: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:27:07 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:27:07 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user

**Comment by ebaauw** [comment]
> Yes, now I reset my device and I get an other error...
> [Homebridge] [1/29/2020, 11:19:42 AM] [Hue] 192...29: bridge communication error ECONNREFUSED on 192...29

What device?  Looks like you turned off the Hue bridge, and homebridge-hue cannot reach it.

> [Homebridge] [1/29/2020, 11:20:06 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user

See README: you need to unlock the gateway, so homebridge-hue can create a username (API key).

**Comment by dixiklo9** [comment]
> See README: you need to unlock the gateway, so homebridge-hue can create a username (API key).

I have already generated a username and entered it in the config, but I keep getting the message.

new log

[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] npm registry: status 404 Not Found
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.72, api v1.16.0
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version undefined
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Daylight: set homekit sunrise from undefined to Wed Jan 29 2020 00:03:58
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Daylight: set homekit sunset from undefined to Wed Jan 29 2020 09:17:29
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Phoscon-GW: 2 accessories
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebrige-hue.json.gz
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Initializing platform accessory "Phoscon-GW".
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Phoscon-GW: 2 services
[Homebridge] [1/29/2020, 11:30:52 AM] [Hue] Initializing platform accessory "Daylight".
[Homebridge] [1/29/2020, 11:30:53 AM] [Hue] npm registry: status 404 Not Found
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] STA getDevice | Connected to: 192.168.178.32
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] STA getDevice | Model: roborock.vacuum.s5
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] STA getDevice | State: charging
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] STA getDevice | FanSpeed: 103
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] STA getDevice | BatteryLevel: 100
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] INF getSerialNumber | roborock.vacuum.s5 | Serial Number is R0018S84507686
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] STA getDevice | Serialnumber: R0018S84507686
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.7_002008
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] STA getDevice | Firmwareversion: 3.5.7_002008
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] INF changedCharging | roborock.vacuum.s5 | Charging is active
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 103%
[Homebridge] [1/29/2020, 11:30:54 AM] [Roborock Vacuum] WAR changedSpeed | roborock.vacuum.s5 | Speed was changed to 103%, this speed is not supported
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.72, api v1.16.0
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version undefined
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Philips hue: Philips BSB002 bridge v1935144040, api v1.35.0
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Philips hue: warning: not using recommended Hue bridge api version undefined
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Phoscon-GW: gateway request 2: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:30:58 AM] [Hue] Philips hue: 1 accessories
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 10, drift 9249
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 11, drift 8252
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 12, drift 7254
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 13, drift 6256
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 14, drift 5259
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 15, drift 4262
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 16, drift 3265
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 17, drift 2267
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 18, drift 1270
[Homebridge] [1/29/2020, 11:31:12 AM] [Sonos] warning: heartbeat 19, drift 273
[Homebridge] [1/29/2020, 11:31:22 AM] [Hue] Phoscon-GW: gateway request 3: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:31:22 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:31:22 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:31:37 AM] [Hue] Phoscon-GW: gateway request 4: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:31:37 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:31:37 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:31:52 AM] [Hue] Phoscon-GW: gateway request 5: post / {"devicetype":"homebridge-hue#hoobs"}

**Comment by ebaauw** [comment]
Did you copy/paste the entry?  The `bridgeid` field is case sensitive.

**Comment by dixiklo9** [comment]
[Homebridge] [1/29/2020, 11:37:22 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:37:22 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:37:37 AM] [Hue] Phoscon-GW: created user - please edit config.json and restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "00212EFFFXXXXAFC5": "A45BXXXDDX"
      }
    }
  ]
[Homebridge] [1/29/2020, 11:37:37 AM] [Hue] Phoscon-GW: 1 accessories
[Homebridge] [1/29/2020, 11:37:37 AM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebrige-hue.json.gz
[Homebridge] [1/29/2020, 11:37:37 AM] [Hue] Initializing platform accessory "Phoscon-GW".
[Homebridge] [1/29/2020, 11:37:37 AM] [Hue] Phoscon-GW: 2 services
[Homebridge] [1/29/2020, 11:37:37 AM] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d52c3521-e35a-480c-94ab-45ad37cddb42
    at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
    at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:380:26)
    at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:16:19
    at /home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:293:5
    at Function.then (/home/hoobs/.hoobs/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
    at Function.<anonymous> (/home/hoobs/.hoobs/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)

my config

"platforms": [
        {
            "platform": "ZP",
            "plugin_map": {
                "plugin_name": "homebridge-zp"
            },
            "name": "Sonos",
            "service": "fan"
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "users": {
                "001788FFFXXXX1F1": "aiErtXBqFVoCvXXXXXXXYbB8LsG-FtQjMLv"
            },
            "excludeSensorTypes": [],
            "hosts": []
        },
        {
            "platform": "Hue",
            "host": "192.168.178.90",
            "port": "8888",
            "users": {
                "00212EFFFXXXXAFC5": "A45BXXXDDX"
            },
            "lights": true,
            "sensors": true,
            "nativeHomeKitSensors": false,
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nupnp": true,
            "resource": true
        }

**Comment by dixiklo9** [comment]
> Did you copy/paste the entry? The bridgeid field is case sensitive.

Yeah, of course

**Comment by dixiklo9** [comment]
[Homebridge] [1/29/2020, 11:38:54 AM] [Hue] Daylight: set homekit sunset from undefined to Wed Jan 29 2020 09:17:29
[Homebridge] [1/29/2020, 11:38:54 AM] [Hue] Phoscon-GW: 2 accessories
[Homebridge] [1/29/2020, 11:38:54 AM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebrige-hue.json.gz
[Homebridge] [1/29/2020, 11:38:54 AM] [Hue] Initializing platform accessory "Phoscon-GW".
[Homebridge] [1/29/2020, 11:38:54 AM] [Hue] Phoscon-GW: 2 services
[Homebridge] [1/29/2020, 11:38:54 AM] [Hue] Initializing platform accessory "Daylight".
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.72, api v1.16.0
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version undefined
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Philips hue: Philips BSB002 bridge v1935144040, api v1.35.0
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Philips hue: warning: not using recommended Hue bridge api version undefined
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Phoscon-GW: gateway request 2: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:38:58 AM] [Hue] Philips hue: 1 accessories
[Homebridge] [1/29/2020, 11:39:13 AM] [Hue] Phoscon-GW: gateway request 3: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:39:13 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:39:13 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:39:26 AM] [Sonos] Büro Sonos: set Track from "I Didn't Realize How Empty My Bed Was Until You Left" to "Nandina"
[Homebridge] [1/29/2020, 11:39:26 AM] [Sonos] Büro Sonos: set Track from "I Didn't Realize How Empty My Bed Was Until You Left" to "Nandina"
[Homebridge] [1/29/2020, 11:39:28 AM] [Hue] Phoscon-GW: gateway request 4: post / {"devicetype":"homebridge-hue#hoobs"}
[Homebridge] [1/29/2020, 11:39:28 AM] [Hue] Phoscon-GW: gateway http status 403 Forbidden
[Homebridge] [1/29/2020, 11:39:28 AM] [Hue] Phoscon-GW: press link button on the bridge to create a user
[Homebridge] [1/29/2020, 11:39:43 AM] [Hue] Phoscon-GW: gateway request 5: post / {"devicetype":"homebridge-hue#hoobs"}

**Comment by dixiklo9** [comment]
Wenn ich Homebridge und deconz neu installiere, würde dies die Fehler beheben?
If I reinstall Homebridge and deconz, would this fix the errors?

**Comment by ebaauw** [comment]
You should only have a single `platform` entry for homebridge-hue.  Add both bridgeid/username entries under the `users` object and use `hosts` for an array of host:port entries.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by dixiklo9** [comment]
Thank you very much for your help, your patience and your free time.
