### ISSUE TITLE
bridge request 1: get /config & bridge communication error EHOSTUNREACH on 192.***.***.43`

### ISSUE THREAD

**Issue by dixiklo9** [ebaauw/homebridge-hue#613]
I got issues with my homebridge. I reinstalled hoobs completly fresh on my raspberry pi and configured hue plugin and now I get following issue.

`[Homebridge] [1/31/2020, 10:16:22 AM] [Hue] 192.***.***.43: bridge request 5: get /config
[Homebridge] [1/31/2020, 10:16:22 AM] [Hue] 192.***.***.43: bridge communication error EHOSTUNREACH on 192.***.***.43
[Homebridge] [1/31/2020, 10:16:24 AM] [Hue] Philips hue: Philips BSB002 bridge v1935144040, api v1.35.0
[Homebridge] [1/31/2020, 10:16:24 AM] [Hue] Philips hue: warning: not using recommended Hue bridge api version undefined
[Homebridge] [1/31/2020, 10:16:24 AM] [Hue] undefined: bridge request 2: get /
[Homebridge] [1/31/2020, 10:16:24 AM] [Hue] undefined: bridge http status 403 Forbidden
[Homebridge] [1/31/2020, 10:16:24 AM] [Hue] Philips hue: 1 accessories
[Homebridge] [1/31/2020, 10:16:25 AM] [Hue] 192.***.***.43: bridge request 1: get /config
[Homebridge] [1/31/2020, 10:16:25 AM] [Hue] 192.***.***.43: bridge communication error EHOSTUNREACH on 192.***.***.43`

My Hue Bridge is online too and I didn't reboot it.

**Comment by ebaauw** [comment]
Did you specify your bridge in config.json, or are you using discovery?

**Comment by dixiklo9** [comment]
Here's my config
`{
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "users": {
                "001788FFFE4B81F1": "pNSlcER5t-BR0yFzhBEWdv2M1SlDoTofasWbG7eq"
            },
            "excludeSensorTypes": [],
            "hosts": []
        }`

**Comment by ebaauw** [comment]
I think the meethue portal is returning the bridges from your (Internet) neighbours, because your ISP is sharing “your” public IPv4 address with them.  Set `nupnp` to false or specify your bridge under `hosts` to stop homebridge-hue from querying the meethue portal.
