### ISSUE TITLE
ph outlet

### ISSUE THREAD

**Issue by dixiklo9** [ebaauw/homebridge-hue#615]
I cannot execute the ph outlet command to change my Osram Power+ plug to a plug instead of a light? 

hoobs@hoobs:~/.hoobs/etc $ sudo npm -g i homebridge-lib
/usr/local/bin/hap -> /usr/local/lib/node_modules/homebridge-lib/cli/hap.js
/usr/local/bin/json -> /usr/local/lib/node_modules/homebridge-lib/cli/json.js
/usr/local/bin/upnp -> /usr/local/lib/node_modules/homebridge-lib/cli/upnp.js
+ homebridge-lib@4.4.13
added 89 packages from 88 contributors in 14.524s
hoobs@hoobs:~/.hoobs/etc $ ph outlet -v
bash: ph: command not found

**Comment by ebaauw** [comment]
`ph` is included in homebrodge-hue.  I don’t know how hoobs installs it, but there should be a symlink from `/usr/local/bin/ph` to `/usr/local/lib/node_modules/homebridge-hue/cli/ph.js`.

**Comment by dixiklo9** [comment]
Can't find ph

```
hoobs@hoobs:/usr/local/bin $ cd /usr/local/lib/node_modules/
hoobs@hoobs:/usr/local/lib/node_modules $ ls
homebridge-lib  @hoobs  npm
```

```
hoobs@hoobs:/usr/local/bin $ cd /usr/local/bin/
hoobs@hoobs:/usr/local/bin $ ls
ffmpeg  ffprobe  hap  hoobs  json  node  npm  npx  tzupdate  upnp
```

**Comment by dixiklo9** [comment]
and there is no `Homebridge-hue`

`hoobs@hoobs:~/.hoobs $ cd /home/hoobs/.hoobs/node_modules
hoobs@hoobs:~/.hoobs/node_modules $ ls
abort-controller            is-arrayish
abstract-things             is-callable
accepts                     is-date-object
agent-base                  is-fullwidth-code-point
ajv                         is-interactive
amounts                     is-ip
ansi-regex                  is-mergeable-object
ansi-styles                 is-path-cwd
appdirectory                is-path-in-cwd
archiver                    is-path-inside
archiver-utils              is-regex
array-differ                is-stream
array-flatten               isstream
array-union                 is-symbol
array-uniq                  is-typedarray
arrify                      jsbn
asap                        json-bigint
asn1                        jsonfile
assert-plus                 json-schema
async                       json-schema-traverse
asynckit                    json-stringify-safe
async-limiter               jsprim
aws4                        junk
aws-sign2                   jwa
axios                       jws
balanced-match              lazystream
base64-js                   listenercount
bcrypt-pbkdf                locate-path
big-integer                 lodash
bignumber.js                lodash.defaults
binary                      lodash.difference
bl                          lodash.flatten
bluebird                    lodash.isplainobject
body-parser                 lodash.union
bonjour-hap                 log-symbols
brace-expansion             lru-cache
buffer                      maximatch
buffer-crc32                media-typer
buffer-equal-constant-time  merge-descriptors
buffer-indexof              methods
buffer-indexof-polyfill     mime
buffers                     mime-db
buffer-shims                mime-types
bufferutil                  mimic-fn
bytes                       minimatch
camelcase                   minimist
caseless                    mkdirp
chainsaw                    moment
chalk                       ms
cli-cursor                  msgpack-lite
cli-spinners                msgpack-sock
cliui                       multicast-dns
clone                       multicast-dns-service-types
color-convert               mute-stream
color-name                  nan
colors                      ncp
color-string                negotiator
color-temperature           next-tick
combined-stream             node-cache
commander                   node-fetch
compress-commons            node-forge
concat-map                  node-gyp-build
content-disposition         node-persist
content-type                node-pty
cookie                      normalize-path
cookie-signature            oauth-sign
core-util-is                object-assign
cors                        object.assign
crc                         object-inspect
crc32-stream                object-is
cycle                       object-keys
d                           once
dashdash                    onetime
debug                       on-finished
decamelize                  ora
decimal.js                  parseurl
deep-equal                  path-exists
defaults                    path-is-absolute
deferred                    path-is-inside
define-properties           path-to-regexp
del                         performance-now
delayed-stream              pidlockfile
depd                        pify
destroy                     ping
dns-equal                   pinkie
dns-packet                  pinkie-promise
dns-txt                     pkginfo
duplexer2                   p-limit
dwaal                       p-locate
ecc-jsbn                    process-nextick-args
ecdsa-sig-formatter         promise
ee-first                    prompt
emitter-mixin               proxy-addr
emoji-regex                 prr
encodeurl                   psl
end-of-stream               p-try
errno                       punycode
es5-ext                     q
es6-iterator                qs
es6-symbol                  range-parser
es-abstract                 raw-body
escape-html                 read
escape-string-regexp        readable-stream
es-to-primitive             recursive-copy
etag                        regexp.prototype.flags
event-emitter               request
eventemitter3               require-directory
event-lite                  require-main-filename
event-target-shim           restore-cursor
express                     revalidator
express-ws                  rimraf
ext                         safe-buffer
extend                      safer-buffer
extsprintf                  samsung-remote
eyes                        sanitize-filename
fakegato-history            sax
fast-deep-equal             semver
fast-json-stable-stringify  send
fast-srp-hap                serve-static
fast-text-encoding          set-blocking
finalhandler                setimmediate
find-up                     setprototypeof
foibles                     signal-exit
folder-hash                 simple-swizzle
follow-redirects            slash
forever-agent               sshpk
form-data                   stack-trace
formidable                  statuses
forwarded                   string_decoder
fresh                       string.prototype.trimleft
fs-constants                string.prototype.trimright
fs-extra                    string-width
fs.realpath                 strip-ansi
fstream                     supports-color
fs-write-stream-atomic      tar-stream
function-bind               thunky
gaxios                      timers-ext
gcp-metadata                tinkerhub-discovery
get-caller-file             toidentifier
getpass                     tough-cookie
glob                        traverse
globby                      truncate-utf8-bytes
googleapis                  tunnel-agent
googleapis-common           tweetnacl
google-auth-library         type
google-p12-pem              type-is
graceful-fs                 @types
graceful-readlink           underscore
gtoken                      universalify
har-schema                  unix-socket-leader
har-validator               unpipe
has                         unzipper
has-flag                    uri-js
has-symbols                 url-template
he                          utf8-byte-length
homebridge-lib              utf-8-validate
homebridge-old-samsungtv    util-deprecate
homebridge-zp               utile
@hoobs                      utils-merge
http-errors                 uuid
http-signature              vary
https-proxy-agent           verror
i                           wcwidth
iconv-lite                  which-module
ieee754                     winston
iferr                       wrap-ansi
imurmurhash                 wrappy
inflight                    ws
inherits                    xml2js
int64-buffer                xmlbuilder
ip                          y18n
ipaddr.js                   yallist
ip-regex                    yargs
is-arguments                yargs-parser
isarray                     zip-stream`

**Comment by ebaauw** [comment]
I’m sorry, I don’t know hoobs; you’ll have to take this up with them.
