### ISSUE TITLE
OSRAM plugs not supported anymore?

### ISSUE THREAD

**Issue by zeromancer1972** [ebaauw/homebridge-hue#617]
It seems you removed support for OSRAM smart plugs from the plugin. This was the only reason I used it. Any chance to get it back?

**Comment by ebaauw** [comment]
What do you mean?

**Comment by zeromancer1972** [comment]
I mean plugs from OSRAM that work well in the Hue app are not exposed by the plugin anymore. I have to create a zone for each plug and then expose the zones as devices - which is a pain. It works though but it's inconvinient.

**Comment by ebaauw** [comment]
That’s odd.  Could you please attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file, and capture and attach a full debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by zeromancer1972** [comment]
A bit difficult atm to grab that files, but here is my current config which works with exposing the zones (but not the devices itself).
```
{
            "name": "Hue",
            "platform": "Hue",
            "nupnp": true,
            "scenes": false,
            "groups": true,
            "rooms": false,
            "scenesAsSwitch": true,
            "parallelRequests": 5,
            "excludeSensorTypes": [
                "CLIP",
                "Geofence",
                "Daylight"
            ],
            "users": {
                "foo": "bar"
            }
        }
```

Maybe I misunderstand the "rooms" option?

**Comment by ebaauw** [comment]
You didn't include `"lights": true`.  The plugs are exposed as `/lights` resources by the Hue bridge.

**Comment by zeromancer1972** [comment]
Weird. That worked. It didn't after the update, so I thought you dropped support. Maybe you should set "light" to true as default value, otherwise the surprise is huge...
Thanks anyway!
