### ISSUE TITLE
Problem with Ecodim Dimmer (Zigbee)

### ISSUE THREAD

**Issue by WibiNorg** [ebaauw/homebridge-hue#618]
Hey there!

I was wondering if there would be a solution for the support of the Ecodim 07 Wall Dimmer.
The dimmer can do Zigbee and Z-Wave Plus. I now have it set to Zigbee and have it paired with the Hue Bridge. It works totally fine with Hue works, but unfortunately it doesn't work with this plugin. The plugin does make is possible tho for the Ecodim to show up in Homekit, but it shows up as "Not compatible". 

Any ideas?

![IMG_5194](https://user-images.githubusercontent.com/60700377/74054422-57090e00-49de-11ea-836a-7194d83d22b1.PNG)

**Comment by ebaauw** [comment]
I need to whitelist the switch, specifying what buttonevents it supports.  homebridge-hue doesn't (yet?) read the switch buttons from the Hue API.

Please attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.  That should contain the info I need to whitelist the switch.

**Comment by WibiNorg** [comment]
Yes, it's a In-wall **dimmer**, to smartify my lights. So it's not a switch, I don't know if that could cause the issue? 

> Did you specify "lights": true in config.json?
Yes, I did.

Sorry for question but I'm quitte a newbie to coding and all and i'm using Homebridge via the program "Hoobs" on my Raspberry Pi 4. Therefore I can't (or don't know how to) get Hoobs to read the Homebridge commands.. I can get you the Hoobs-Log tho.

**Comment by ebaauw** [comment]
You need to copy the bridgeid and username (API key) from the log to config.json, see the [README](https://github.com/ebaauw/homebridge-hue#installation).  I don't know where they've hidden config.json in hoobs.

**Comment by WibiNorg** [comment]
Ah my bad. Works like a charm now, thanks!
Only thing now is that the other “Phillip hue” tile still remains in Homekit, still listed with: “Not compatible”. Any idea how I can hide this?

**Comment by ebaauw** [comment]
Move it to a dummy room (and make sure it's not selected as a Favourite).
