### ISSUE TITLE
ph: error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#619]
Hello, 

i have recently experienced the following error when using the ph tool. Unfortunately I can't say since when it occurred.

![A7368D70-5CDF-4CA8-A8F2-605C10873C82](https://user-images.githubusercontent.com/27686185/74081679-06cb9380-4a52-11ea-9789-cf26e44efbf6.jpeg)
![4977F185-F64D-47B6-BC99-D19EE253987A](https://user-images.githubusercontent.com/27686185/74081680-09c68400-4a52-11ea-9765-27baa114877f.jpeg)

It happens with every command, it doesn't matter if the command is sent to deconz or a hue bridge.

The command is still executed.

I have installed node 12.15.0 LTS and this morning I installed the Pi update to Kernel Linux 4.19.97-v7l+.

Do you have an idea what the problem is?

**Comment by ebaauw** [comment]
Looks like `~/.ph` is corrupted.  This is the (hidden) file where `ph` stores the api keys and pinned certificates of known bridges and gateways.

**Comment by Nastras** [comment]
Thanks for the tip.

I found the file. It's empty. Is there a way to create it new with the existing users via ph?

**Comment by ebaauw** [comment]
No.  With the recent Hue API versions, there’s no way to recover an API key, even if you have another valid API key.  Best restore it from backup, or delete it and use `ph createuser` to create new API keys.

**Comment by Nastras** [comment]
Restored the file from a backup. It's all working again. 

Thanks for the support and have a nice weekend.

**Comment by ebaauw** [comment]
In v0.11.54, `ph` issues a warning on corrupted `~/.ph`.
