### ISSUE TITLE
Wrong buttons on Hue dimmer switch

### ISSUE THREAD

**Issue by DJay1** [ebaauw/homebridge-hue#62]
Hi there. Thanks for the great work on homebridge-hue plugin 👍 
I noticed when I configure Button 1 by Home App with a long press, that it is not the first top button (I) on the physical hue dimmer switch but the second button (*). The also configured button 4 with a long press, works as expected. [Screenshot](http://bit.ly/2l549EI)
Am I doing something wrong or is here a bug?

**Comment by ebaauw** [comment]
I'm experiencing the same, see issue #54.  Home seems to list the buttons in random order.

Note that when you press/hold the Hue dimmer switch button, the corresponding action in Home lights up, so you can figure out which button in Home corresponds to which physical button.  Alternatively, you can use another HomeKit app to check the triggers of the rules Home created.

I'm hoping it's a bug in the iOS 10.3 beta Home app, but lacking any documentation from Apple whatsoever, I cannot know this for sure.  I'm not sure if HomeKit defines the order for the services within an accessory:  HMCatalog shows them in alphabetical order of the service name and Apple's Home doesn't show accessories at all (except for programmable switches in 10.3 beta).  However both Eve and Matthias' Home show them in the order created, so this order must be available to HomeKit apps.

**Comment by ebaauw** [comment]
I found and removed the `sortByLocalizedName()` of the services in HMCatalog.  It now shows the services in the order created, like Eve and Matthias' Home.

**Comment by DJay1** [comment]
Thx. In the eve App I see the Hue dimmer switch only like this without any change when I press the physical button on the remote. [Link](http://bit.ly/2m7G3H4)
I think in one of the past Versions of iOS or the Plugin it was different. I'm on the latest plugin version and on iOS 10.3 beta 2

**Comment by ebaauw** [comment]
@DJay1 
> I think in one of the past Versions of iOS or the Plugin it was different. I'm on the latest plugin version and on iOS 10.3 beta 2

Yes, homebridge-hue v0.1.x used to expose the Hue dimmer switche (and the Hue tap) as a `StatefulProgrammableSwitch` service, with the `ProgrammableSwitchOutputState` characteristic indicating which button was pressed last, in line with (my understanding) Apple's documentation.  As of v0.2.x, the four `StatelessProgrammableSwitch` services were added, in preparation for iOS 10.3.  
Eve v2.6 no longer shows the `StatefulProgrammableSwitch` service, so I changed that to a custom service, dropping the `ProgrammableSwitchOutputState` characteristic.
Finally, I changed `Active` to `Enabled`, introduced `Resource` and created a separate `Battery` service.

All these changes are documented in the corresponding issues mentioned in the  [release notes](https://github.com/ebaauw/homebridge-hue/releases).

Note that iOS 10.3 is still in beta and Apple has provided no documentation whatsoever how programmable switches are supposed to work.  Things might still change before the final release of iOS 10.3 (and did between beta 1 and beta 2).

> In the eve App I see the Hue dimmer switch only like this without any change when I press the 
physical button on the remote

Eve doesn't show the `StatelessProgrammableSwitch` services in _Rooms_ (not even in v2.5.x), but it does show them in _Accessories_ under _Settings_, see the screenshot in issue https://github.com/ebaauw/homebridge-hue/issues/54#issuecomment-280135860.  You can select the `Input Event` characteristics for the buttons as triggers under _Rules_.

Elgato do sell [programmable switches](https://www.elgato.com/en/eve/eve-light-switch) in North America, I'd love to see what they look like in the Eve app.  I half expected Eve v2.6 to match the iOS Home functionality, but it would seem that we have to wait for the final release of iOS 10.3.

**Comment by ebaauw** [comment]
The buttons still appear in random order on iOS 10.3 beta 3.

**Comment by ebaauw** [comment]
I'm closing this issue - further tracking in #54.
