### ISSUE TITLE
Ikea switch keeps reporting „battery low“

### ISSUE THREAD

**Issue by basti184** [ebaauw/homebridge-hue#620]
Hello, 
I have added an Ikea Tradfri remote to homebridge via DeConz and homebridge-hue. However it keeps reporting „battery low“ with a battery level of 0%. 
The remote is pretty new and works fine so the battery level is not reported correctly. 

Any way to fix this or at least hide the battery status for that device so that the warning disappears? 

![4449E7C5-138C-4056-BBD4-264D55DEC89D](https://user-images.githubusercontent.com/53945090/74102603-4d4dea80-4b45-11ea-9101-1414c8443485.jpeg)

Thanks!

**Comment by ebaauw** [comment]
homebridge-hue simply exposes the battery as reported by deCONZ over the REST API.  On pairing, the REST API plugin should configure the remote to report its battery every two hours, so it might take a while before it reports the actual battery percentage.  If it doesn't even after a couple of hours, you might try and re-pair the remote or configure the remote manually, using the deCONZ GUI.  You'd need to setup a binding from the remote's _Power Configuration_ cluster to the RaspBee/ConBee, and setup attribute reporting for _Battery Percentage Remaining_ with values 7200/7200/0.  See the GUI's user manual (under _Help_).

**Comment by basti184** [comment]
It was indeed the case for several weeks now. I have re-paired now and it works! Should have tried that before myself. Hope it will last now. 
Sorry for bothering and thanks for the quick reply.
Cheers
