### ISSUE TITLE
Is this plugin necessary if you have the latest hue bridge?

### ISSUE THREAD

**Issue by ben174** [ebaauw/homebridge-hue#621]
Since the latest hue bridge natively supports homekit, is this plugin necessary? Does it offer anything the native support doesn't?

**Comment by jensflorian** [comment]
> Does it offer anything the native support doesn't?

Privacy (when used with hue bridge alternatives such as phoscon). 

Signify  collects time,  duration and manner of use of their products and services or products and services connected. See: https://www.signify.com/global/privacy/legal-information/privacy-notice#what_types_of_data_we_collect_about_you for details.

**Comment by ebaauw** [comment]
See README for features provided by homebridge-hue.
