### ISSUE TITLE
IKEA TRADFRI Switches say "Actions may not run. Can't connect to home hub".

### ISSUE THREAD

**Issue by AronDurkinSSS** [ebaauw/homebridge-hue#622]
#### Issue
IKEA TRADFRI Switches say "Actions may not run. Can't connect to home hub".

With TRAFRI Remote Control and TRADRI wireless dimmer. I had them working just fine. Then my NUC with Conbee 2 and Deconz restarted and they lost connect. I removed and re-added.

Now both switches are visible in Homekit, and I can see in HOOBS log that Hue is picking up the presses. I can see in Homekit it's picking up the presses but it has a "!" over them all and says "This accessorys actions may not run. Can't connect to home hub". Which is true, I can assign actions but they don't run. 

Zigbee lights through hue work work fine. 

Thank you

**Comment by ebaauw** [comment]
This is an issue with your home hub not connecting to homebridge - nothing to do with homebridge-hue.

**Comment by AronDurkinSSS** [comment]
Oh I'm sorry.
