### ISSUE TITLE
Heiman HS1CG-E unknown ZHACarbonMonoxide sensor

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#627]
Hello, Erik,

Today I got the Heiman HS1CG-E Smart Combustible Gas Sensor and integrated it via deCONZ. I get the following error when starting Homebridge:

![BA4E416D-6EE5-4A2F-AB7C-050524E87A6E](https://user-images.githubusercontent.com/27686185/75098365-82325680-55b5-11ea-954f-7a96f68f94ed.jpeg)

I can't check how it looks like in Homekit. I have deleted my home and have to set it up again.

It be possible that you integrate it?

I made you an excerpt from the sensor's config, if you need anything else let me know?

![011ABACD-D7CD-47EC-9EC5-7D9209C4F650](https://user-images.githubusercontent.com/27686185/75098358-75adfe00-55b5-11ea-90c5-d1c940b7be22.jpeg)

Thanks a lot.

Best regards
Nastra

**Comment by ebaauw** [comment]
It's just a warning.  The sensor will probably work just fine in HomeKit.  Once exposed by the REST API, most sensors are actually pretty standard, and don't require special handling by homebridge-hue.  The exceptions are wireless switches (with different `buttonevent` values) and motion sensors (with different behaviour when motion is no longer detected).

Hopefully API v2 will list `capabilities` cf. the Hue bridge, so there's no more need for whitelisting devices in any API client.

**Comment by Nastras** [comment]
Now I have integrated the sensor into HK and it looks like everything works.
Worried about nothing 😅

Thanks for the support!

**Comment by Nastras** [comment]
One more question, do you have the option to hide the warning message with the next version of homebridge-hue?

**Comment by ebaauw** [comment]
> do you have the option to hide the warning message with the next version of homebridge-hue?

No, by design.

**Comment by ebaauw** [comment]
In v0.11.56.

**Comment by Nastras** [comment]
Hello @ebaauw, I hope I understood your answer correctly. The message should have disappeared with the new version or?

If so, then is there something wrong because it is still displayed?

![A7FAB86A-051B-4E91-8FFA-CA3B289EBBEB](https://user-images.githubusercontent.com/27686185/75613294-368b2a00-5b2c-11ea-8f88-3c6ff01dd094.jpeg)

**Comment by ebaauw** [comment]
I'm afraid I completely overlooked the type.  I listed it under ZHAFire, next to the old model `GAS_V15`.  These are combustable gas sensors, not CO sensors.  The new model should also have been exposed as ZHAFire, instead of as ZHACarbonMonoxide.

This a bug in deCONZ, caused by a typo: `Gas` instead of `GAS`:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/69946322ade31ba98f2d0827f3dc7a8fc07a71b5/de_web_plugin.cpp#L3989

**Comment by Nastras** [comment]
Cool that you pull so fast. Thanks!

**Comment by Nastras** [comment]
Good morning @ebaauw 

I have updated deCONZ to V2.5.75 today and expected that the message has disappeared now.

Unfortunately it is still displayed.

Do you have an idea why?

<img width="1063" alt="Bildschirmfoto 2020-03-09 um 07 07 00" src="https://user-images.githubusercontent.com/27686185/76187067-9e004400-61d4-11ea-9189-dd83afe7b4fc.png">

**Comment by ebaauw** [comment]
Did you delete the sensor resource from deCONZ and re-pair the sensor?

**Comment by Nastras** [comment]
Now I've deleted it and added it again. Unfortunately this message is still displayed.
<img width="1063" alt="Bildschirmfoto 2020-03-09 um 07 52 23" src="https://user-images.githubusercontent.com/27686185/76189473-1833c700-61db-11ea-9c66-05a731054fad.png">

**Comment by ebaauw** [comment]
Can you please attach the dump file?

**Comment by Nastras** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4305111/homebridge-hue.json.gz)

**Comment by Nastras** [comment]
Another off topic question for you, do you know a way to mark all nodes in the decont web gui without selecting them all individually with ctrl?

**Comment by ebaauw** [comment]
> web gui

What do you mean: the GUI or the web app (Phoscon)?  I don't use Phoscon and know next to nothing about it.  In the GUI you can only select one node at a time.

**Comment by ebaauw** [comment]
> Can you please attach the dump file?

The `/sensors` resource is still has a `type`of `"ZHACarbonMonoxide"`.  I double-checked that indeed no other resources have been created for this sensor.

I double-checked the deCONZ REST API plugin code, as published on GitHub: my change was included.  Are you sure you deleted the `/sensors` resource through the API before re-pairing?  Just deleting the node in the GUI won't do it.  Was the sensor resource re-created with the same ID?  Maybe the record needs to be purged from the database.

**Comment by Nastras** [comment]
> What do you mean: the GUI or the web app (Phoscon)? I don't use Phoscon and know next to nothing about it. In the GUI you can only select one node at a time.


Sorry I misspoke. I meant the deconz gui.

You can select multiple nodes to move them by holding down the ctrl key but only one after the other.

I thought there was another key to select all of them.

> The /sensors resource is still has a typeof "ZHACarbonMonoxide". I double-checked that indeed no other resources have been created for this sensor.

I double-checked the deCONZ REST API plugin code, as published on GitHub: my change was included. Are you sure you deleted the /sensors resource through the API before re-pairing? Just deleting the node in the GUI won't do it. Was the sensor resource re-created with the same ID? Maybe the record needs to be purged from the database.


Of course I did not delete the nodes via the API but via the gui and then added them again. 

I will try it again later.

Thanks!

**Comment by Nastras** [comment]
Good morning Erik,
sorry to call so late. You were right, after I deleted and added the sensor via the api the warning message is gone.

So thanks again for your tireless efforts and have a nice weekend!
