### ISSUE TITLE
bridge communication error ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by misanthrophy** [ebaauw/homebridge-hue#629]
Hi, since the last update of homebridge-hue, I can no longer find any of my Osram and/or Ikea lights. My hue bridge is on the latest firmware version: 1937045000 and API: 1.36.0.

My log shows this:

`Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] npm registry: The "listener" argument must be of type function. Received an instance of Object
Code
Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] Philips hue: bridge request 1: get /
Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] Philips hue: bridge communication error ERR_INVALID_ARG_TYPE on 192.***.***.7
Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] Philips hue:
Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] Philips hue: 1 accessories
Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] Initializing platform accessory 'Philips hue'...
Feb 23 12:46:37 raspberrypi homebridge[9038]: [2/23/2020, 12:46:37] [Hue] Philips hue: 2 services`

I tried to:

- Restart homebridge
- Restart my Raspberry Pi
- Restart my hue bridge via App and with power cycling it
- uninstalled and reinstalled homebridge-hue
- updated node and NPM to the latest version to satisfy homebridge-hue
- removed the host from my config.json and only left the user
- removed the user as well to pair it again --> after that I was no longer able to connect to the bridge, because homebridge-hue never recognized, that I pressed the link button, even though iConnectHue and Hue itself recognized it immediately
- removed homebridge-hue.json.gz and cachedAccessories

According to the error message "ERR_INVALID_ARG_TYPE" the issue should be already resolved in a previous version (v0.11.54) but not in my case.

Right now, I was able to restore my homebridge with the previous version homebridge-hue v0.11.52 and all my Osram and Ikea lights are exposed again. (I still have to redo my scenes and move them between rooms, but at least it is working.

**Comment by G60GT** [comment]
I experience the same error since I updated homebridge-hue yesterday. My Osram Lightify plugs are no longer exposed to HomeKit.

> [Hue] Philips Hue: Philips BSB002 bridge v1937045000, api v1.36.0
[Hue] Philips Hue: bridge request 1: get /
[Hue] Philips Hue: bridge communication error ERR_INVALID_ARG_TYPE on 192.***.***.20
[Hue] Philips Hue:
[Hue] Philips Hue: 1 accessories
[Hue] masked debug info dumped to /var/homebridge-hue/homebridge-hue.json.gz
[Hue] Initializing platform accessory 'Philips Hue'...
[Hue] Philips Hue: 2 services

**Comment by G60GT** [comment]
Not sure if it helps, but issuing

`ph -H 192...20 get`

works flawlessly.

**Comment by ebaauw** [comment]
Could you please capture and attach a full debug log file?  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by G60GT** [comment]
I'd love to, but somehow it doesn't seem to work. I run multiple instances of homebridge, and when I add the -D argument to the hue-instance it doesn't make a difference in the log output.

**Comment by Nastras** [comment]
You have to set the -D in the option file under /etc/default/homebridge-xxxxx when you using multiple instances.

Example:
# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
DEBUG=* homebridge -D

Otherwise @ebaauw would like to have the homebridge-hue.json.gz from you. It is already created by the plugin under: /var/homebridge-hue/homebridge-hue.json.gz

You should attach this file here.

**Comment by G60GT** [comment]
First, homebridge-hue.json.gz:

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4244617/homebridge-hue.json.gz)

Will try the other part now.

OT: @Nastras - are you the one from the smartapfel Forums?

**Comment by Nastras** [comment]
> OT: @Nastras - are you the one from the smartapfel Forums?
yes I am

**Comment by G60GT** [comment]
> > OT: @Nastras - are you the one from the smartapfel Forums?
> 
> yes I am

I followed your instructions on multiple instances then :)

**Comment by rotorsim** [comment]
Same problem since last update I did today. Zigbee lights and switches that are coupled with the hue bridge but are not native hue devices are no longer exposed to the homebridge.

Homebridge log says:

```
[2020-2-26 13:46:55] [Hue] npm registry: The "listener" argument must be of type Function. Received type object
[2020-2-26 13:46:55] [Hue] Philips hue: Philips BSB002 bridge v1937045000, api v1.36.0
[2020-2-26 13:46:55] [Hue] Philips hue: bridge request 1: get /
[2020-2-26 13:46:55] [Hue] Philips hue: bridge communication error ERR_INVALID_ARG_TYPE on 192.***.***.20
[2020-2-26 13:46:55] [Hue] Philips hue:
[2020-2-26 13:46:55] [Hue] Philips hue: 1 accessories
[2020-2-26 13:46:55] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
[2020-2-26 13:46:55] [Hue] Initializing platform accessory 'Philips hue'...
[2020-2-26 13:46:55] [Hue] Philips hue: 2 services
```

This is the content of homebrige-hue.json:

`{"versions":{"node":"v12.14.1","homebridge":"v0.4.50","homebridge-hue":"v0.11.55"},"config":{"name":"Hue","forceCt":true,"hosts":["192.***.***.20"],"lights":true,"nativeHomeKitLights":true,"nativeHomeKitSensors":true,"nupnp":true,"resource":true,"sensors":true,"platform":"Hue","users":{"ECB5FAFFFE167081":"***************************************1"}},"bridges":[null]}`

**Comment by misanthrophy** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4256132/homebridge-hue.json.gz)

See the attached file

**Comment by ebaauw** [comment]
Sorry folks, the dump files don’t contain anything useful, since the `GET /` failed.  I really need a debug log file to analyse what’s going on.  I cannot reproduce this error.

What system are you running homebridge on?  How did you install homebridge?  How did you update homebridge-hue?  What’s the output of `sudo npm -g list homebridge-hue`?  Or `npm list homebridge-hue`, if you installed it locally.

**Comment by G60GT** [comment]
Running on a Pi 4. 
Homebridge install via `sudo npm i-g homebridge@latest`
Update via `sudo npm i -g homebridge-hue@latest`

Output:
`/usr/local/lib
└── homebridge-hue@0.11.55 `

Regarding the debug log - it seems to contain confidential information like the password. Can I send it to you directly or censor it?

**Comment by mrbeach69** [comment]
I got the Same issue. Running Homebridge in Docker on Synology NAS

**Comment by rotorsim** [comment]
Running on a Pi 3 B+, homebridge installed via `sudo npm install -g --unsafe-perm homebridge`. homebridge-hue installed via homebridge-config-ui-x. Last Update today. 

sudo npm -g list homebridge-hue says:

```
/usr/local/lib
└── homebridge-hue@0.11.55 
```

Tomorrow I will try to get a log file.

**Comment by ebaauw** [comment]
Damn `npm`.  I want to see the tree of dependencies underneath homebridge-hue, but apparently it doesn't show it with `npm list` _package_.
```
├─┬ homebridge-hue@0.11.55
│ ├── chalk@3.0.0
│ ├── debug@4.1.1
│ ├── fakegato-history@0.5.6
│ ├── homebridge-lib@4.5.1
│ ├── moment@2.24.0
│ ├── semver@7.1.3
│ ├── ws@7.2.1
│ └── xml2js@0.4.23
```
Could please log the output of `sudo npm -g list --depth=1`?

> Regarding the debug log - it seems to contain confidential information like the password. Can I send it to you directly or censor it?

homebridge-hue masks the bridge API keys and IP addresses in the log and dump file.  I don't know about other plugins, but feel free to mask any passwords.

**Comment by rotorsim** [comment]
```
├─┬ homebridge-hue@0.11.55
│ ├── chalk@3.0.0
│ ├── debug@4.1.1
│ ├── fakegato-history@0.5.6
│ ├── homebridge-lib@4.5.2
│ ├── moment@2.24.0
│ ├── semver@7.1.3
│ ├── ws@7.2.1
│ └── xml2js@0.4.23
```
There is a difference to your dump in homebridge-lib.

**Comment by ebaauw** [comment]
I  released a new version of homebridge-lib after releasing homebridge-hue@0.11.55, but that shouldn’t be causing these issues.  I’ll test tonight just to be sure, though.

What version of node are you running?

The errors (note the npm registry error in the screenshot above) smell like an older version of homebridge-lib, <4.5.0, is being used.  I’ve seen some funny `npm` stuff, where it flattens `node_modules` instead of storing the dependencies under each package, when not run with `-g`.

**Comment by rotorsim** [comment]
```
pi@raspberrypi:~ $ node -v
v12.16.1
pi@raspberrypi:~ $ npm -v
6.13.4
```

**Comment by rotorsim** [comment]
And her the log file beginning with the shutdown before setting option -D.
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4260358/homebridge.log.gz)

**Comment by rotorsim** [comment]
> The errors (note the npm registry error in the screenshot above) smell like an older version of homebridge-lib, <4.5.0, is being used. I’ve seen some funny `npm` stuff, where it flattens `node_modules` instead of storing the dependencies under each package, when not run with `-g`.
 
I localized its `package.json` at `/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib `containing `"version": "4.5.2"`. So I assume it is really the current version.

**Comment by ebaauw** [comment]
> And her the log file beginning with the shutdown before setting option -D.

Thanks.  You also get the error on the npm registry, strengthening my suspicion that the cause is indeed somewhere in the dependencies.  Unfortunately, that still doesn't give me a clue what's happening.

Could you please capture and attact a log file, running `DEBUG=* homebridge -D`?

DId you try to uninstall and re-install homebridge-hue from the command line (not using homebridge-config-ui-x)?
```
sudo npm -g un homebridge-hue
sudo npm -g i homebridge-hue
```

**Comment by rotorsim** [comment]
Yes, I tried to uninstall and reinstall via terminal commands. No success.

This is the output of the DEBUG=* command:
[debug.txt](https://github.com/ebaauw/homebridge-hue/files/4261766/debug.txt)

**Comment by rotorsim** [comment]
Possibly this is a bit more informative:
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4262066/homebridge.log.gz)

**Comment by ebaauw** [comment]
Thanks.  It is, and it isn't.  Homebridge-hue is doing exactly what I expect it to do.  I double-checked running v0.11.55 with homebridge-lib@4.5.2 - no issue here; homebridge-hue does the same.

Did you try and run homebridge-hue as only plugin in homebridge?  Disable the other plugins by setting `"plugins": ["homebridge-hue]"` at the top level in config.json (and remove their sections from the `"platforms"` and/or `"accessories"` arrays?

**Comment by ebaauw** [comment]
Could you try v0.11.56-0, install through `sudo npm -g homebridge-hue@beta`.  I don't expect it to solve the issue, but it should log a stack trace on each of the errors.  I'm hoping that might shed some light on what's happening.

**Comment by ebaauw** [comment]
@rotorsim, are you running a reverse proxy or firewall for https traffic?

**Comment by rotorsim** [comment]
@ebaauw, thank you very much for your perfect support!

There is no proxy or firewall for https traffic, anyway to my knowledge. I'm only rudimentarily familiar with Linux, so there may be things, that I don't see. But I can make the note: Hombridge including homebridge-hue is installed since 5 weeks and worked fine until this week. 

[curl.txt](https://github.com/ebaauw/homebridge-hue/files/4266305/curl.txt)

**Comment by rotorsim** [comment]
And here the log with v0.11.56-0 installed:
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/4266430/homebridge.log)

**Comment by ebaauw** [comment]
OK, it looks like the fritz plugin breaks https:
```
[2020-2-28 10:50:13] [Hue] npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:109:11)
    at ClientRequest.once (events.js:431:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at HttpClient.request (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HttpClient.get (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
    at HuePlatform.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:271:38)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
...
[2020-2-28 10:50:13] [Hue] Philips hue: error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:109:11)
    at ClientRequest.once (events.js:431:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at HttpClient.request (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HueClient._request (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:350:41)
    at HueBridge.request (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:1093:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async HueBridge.getFullState (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:315:17)
```
Can you try running homebridge without loading that plugin?  See https://github.com/ebaauw/homebridge-hue/issues/629#issuecomment-592093857.

**Comment by rotorsim** [comment]
I am reluctant to do that, because this will break most likely my very complex automations for the heating installation. But it will be unavoidable. 

I'll report.

**Comment by rotorsim** [comment]
Bingo! That's it.
Thank you so much!

**Comment by ebaauw** [comment]
I just released a new beta with a `forceHttp` config.json setting, to prevent homebridge-hue from using https.  Not sure how long the Hue bridge will continue to allow non-https traffic, though.  And it’s really bad practice to modify the global setting in NodeJS.  I would isolate the fritz plugin in a separate homebridge instance.

@misanthrophy @G60GT @mrbeach69 can you please confirm that you’re also running the fritz plugin?

**Comment by floduen** [comment]
Hey had the same problem here - works fine with beta and forcehttp (I’m also using the fritz plugin) @ebaauw  thank you so much for your support

**Comment by mrbeach69** [comment]
@ebaauw yes, after uninstall the fritz plugin, it is working again. Thanks.

**Comment by G60GT** [comment]
I do not use the fritz plugin. No AVM hardware in this household. I wonder what my problem is, then …

**Comment by ebaauw** [comment]
@G60GT could you try the beta with the `forceHttp` setting in config.json?

If that still causes an issue, please capture a debug log file and attach that here or mail that to me (if you're worried about passwords etc).

**Comment by G60GT** [comment]
Sorry, just saw this:

> I just realised that the failed requests are https, were the http request succeeds. Do you have SSL support on your machines/containers? What’s the output of
> 
> ```
> curl https://registry.npmjs.org/homebridge-hue/latest
> ```
> 
> when run from the container?
> 
> @G60GT Does you `ph` command use https? Does `~/.ph` contain the fingerprint for the Hue bridge certificate? Did you run it from the same machine/container as homebridge?

> pi@homebridge:~ $ curl https://registry.npmjs.org/homebridge-hue/latest
{"name":"homebridge-hue","description":"Homebridge plugin for Philips Hue and deCONZ","author":{"name":"Erik Baauw"},"license":"Apache-2.0","version":"0.11.55","keywords":["homebridge-plugin","homekit","philips","hue","philipshue","philips-hue","deconz","raspbee","conbee"],"main":"index.js","bin":{"dc_eventlog":"cli/dc_eventlog.js","ph":"cli/ph.js"},"engines":{"BSB001":"1.16.0","BSB002":"1.36.0","deCONZ":"2.5.73","homebridge":"^0.4.50","node":"^12.16.1"},"dependencies":{"chalk":"~3.0.0","debug":"~4.1.1","fakegato-history":"~0.5.6","homebridge-lib":"~4.5.1","moment":"~2.24.0","semver":"~7.1.3","ws":"~7.2.1","xml2js":"~0.4.23"},"scripts":{"prepare":"standard","test":"standard && echo \"Error: no test specified\" && exit 1"},"repository":{"type":"git","url":"git+https://github.com/ebaauw/homebridge-hue.git"},"bugs":{"url":"https://github.com/ebaauw/homebridge-hue/issues"},"homepage":"https://github.com/ebaauw/homebridge-hue#readme","gitHead":"6571ffbd7252789f968f6b87f97b78dd90e71f7a","_id":"homebridge-hue@0.11.55","_nodeVersion":"12.16.1","_npmVersion":"6.13.7","dist":{"integrity":"sha512-nYkhdlgjZueRt7z2b7HWl1nEA+Prg6kNiE5EJRkHqi+9pOUl7NWSNpXaTEvUrC1Z8ffvSVK9p/r5m79MtQhl8w==","shasum":"43dc8c6b0a010f5bebfcf1d310f8bbe5544f78fd","tarball":"https://registry.npmjs.org/homebridge-hue/-/homebridge-hue-0.11.55.tgz","fileCount":17,"unpackedSize":301998,"npm-signature":"-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.4\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJeTv7TCRA9TVsSAnZWagAAMb8P/jo2vckzNHXucJKx3siq\nk7GmEO62m10VPne0HnBZuwUu53ngEt/q4uPfvw10ujN7OG5QDyEBJRrrdrfH\nlbPwC7EI9tWgHJdcL25vhAn792/QgK7BkbL+Y26sFx6VXSjjx4TMIgUr4Nzk\n42Rpm3I1srfST/wLcmxNqFuUxNJqzfmPl41h9nrm6CROLm/DPKrfMtrgzWks\n7YbKR/2H+5+tqNDAtwqvkQRoJ8bdG13a2Xsw6Y/11N5zDp13ElTXyojlNV1C\ng3AchKAvMfP98vUhnrhSJi7RhjW62St37/EZtq/7ImnsIG/fxyMjxG+BvcuJ\n6iteIUnhZ4kkViNND4NxiBkRacpR+XbVwg9SyUESIOZ2z2MDMCWN/iA9Qoqd\nVx5FtfObua2Nn9jRO0aCrluJLKD1Yf5I8qzUtO1B3E2fP/Saaz7G2iTCFk66\nGrnHWqEyNLkWYFh2LqxZSdRf4AeigNfDNRWbta9g+0yRI2ehbsy9tj+3ytFp\niAhnBttntSO4Am1SfyaGyIjzZ2wapKwokuhmZydpbwC7SdNdv6Jw8f1rVeDs\n246V4esjgWyObPKSgieQXRzP42wU5Je7InvduSDXCwof5Tn3g8Ig3lmPwRqq\n9ViBJgXb99oHWdhAlYjJHzoZnr51Jhk4p2BuSCPgpJs9I0M4YNVc/iI7KD6h\n+9G+\r\n=5amK\r\n-----END PGP SIGNATURE-----\r\n"},"maintainers":[{"name":"ebaauw","email":"erik.baauw@xs4all.nl"}],"_npmUser":{"name":"ebaauw","email":"erik.baauw@xs4all.nl"},"directories":{},"_npmOperationalInternal":{"host":"s3://npm-registry-packages","tmp":"tmp/homebridge-hue_0.11.55_1582235346693_0.10429360849025615"},"_hasShrinkwrap":false}

How can I see if ph uses https? The command is run from the exact same machine as homebridge.

**Comment by ebaauw** [comment]
> How can I see if ph uses https?

Does ~/.ph contain the fingerprint for the Hue bridge certificate?

What other plugins are you using with homebridge?

**Comment by G60GT** [comment]
> > How can I see if ph uses https?
> 
> Does ~/.ph contain the fingerprint for the Hue bridge certificate?
> 

Yes
> > I do not use the fritz plugin.
> 
> What other plugins are you using with homebridge? Maybe it's a common dependency.

On the same instance of homebridge or all other plugins?

**Comment by ebaauw** [comment]
> On the same instance of homebridge or all other plugins?

That depends... (sorry).  If the plugins are loaded, they could potentially already mess things up.    Homebridge loads all installed plugins on startup, see the log:
```
[2/28/2020, 2:57:35 PM] ---
[2/28/2020, 2:57:35 PM] Loaded plugin: homebridge-config-ui-x
[2/28/2020, 2:57:35 PM] Registering platform 'homebridge-config-ui-x.config'
[2/28/2020, 2:57:35 PM] ---
[2/28/2020, 2:57:36 PM] Loaded plugin: homebridge-hue
[2/28/2020, 2:57:36 PM] Registering platform 'homebridge-hue.Hue'
[2/28/2020, 2:57:36 PM] ---
```
You can prevent installed plugins from being loaded by whitelisting the plugins you want to be loaded in config.json.  Add `"plugins": [ "homebridge-config-ui-x", "homebridge-hue" ]` (using the list of plugins needed for this instance) to the top-level object.  Make sure each plugin mentioned in `platforms` or `accessories`, or homebridge will give "not registered" errors.

**Comment by G60GT** [comment]
Same instance: No other plugin than homebridge-hue.

On the machine, in all instances:

- homebridge-airrohr
- homebridge-automation-switches
- homebridge-calendar
- homebridge-camera-ffmpeg
- homebridge-cmdtrigger
- homebridge-config-ui-x
- homebridge-daily-sensors
- homebridge-delay-switch
- homebridge-dummy
- homebridge-eveatmo
- homebridge-mi-airpurifier
- homebridge-neato
- homebridge-occupancy-delay
- homebridge-people
- homebridge-pihole
- homebridge-raspberrypi-temperature
- homebridge-weather-plus
- homebridge-zway

**Comment by G60GT** [comment]
With the beta, everything works as expected.

**Comment by ebaauw** [comment]
Is that with `"forceHttp": true` or without?

Did you try setting `"plugins": ["homebridge-hue"]` in the homebridge-hue instance's config.json?

**Comment by G60GT** [comment]
> Is that with `"forceHttp": true` in config.json or without?
>
I just installed the beta, I did not change anything in the config.

> Did you try setting `"plugins": ["homebridge-hue"]` in the homebridge-hue instance's config.json?
No, since it's the only plugin in that instance.

**Comment by ebaauw** [comment]
OK, then your issue was likely due to an installation quirk.

**Comment by G60GT** [comment]
Strange, since I tried uninstalling and reinstalling. Whatever, I'm glad it's working now.
Since I did not change the config, I'm still using https, right? No need to worry?

**Comment by ebaauw** [comment]
> Since I did not change the config, I'm still using https, right?

Yes.

**Comment by rotorsim** [comment]
> I just released a new beta with a `forceHttp` config.json setting, to prevent homebridge-hue from using https. Not sure how long the Hue bridge will continue to allow non-https traffic, though. And it’s really bad practice to modify the global setting in NodeJS.

Very true. Bad practice and at best a workaround.
I have retired the "Fritz Platform" plugin and changed to "Homebridge Fritz" by @andig (https://github.com/andig/homebridge-fritz#readme). First experience is promising.

**Comment by ebaauw** [comment]
Just release v0.11.56 with `forceHttp` and improved error logging.

**Comment by derjonny88** [comment]
Hello, I still have the problem even though forceHttp is switched on. I need the Fritz-Platform plugin for my automations. 

Are there any other solutions?

**Comment by ebaauw** [comment]
Are you sure it’s the same problem?  Please attach a debug log file.

The other solution is to run homebridge-hue and homebridge-fritz-platform in separate Homebridge instances.

**Comment by Christian-CFP** [comment]
And again same issue here! since now.

**Comment by ebaauw** [comment]
What do you mean “again”?  When did you have this issue before?  When did it stop, what chaned?  When did it start again, what changed?

Please capture and attach a full debug log file, and attach the deug dump file.

**Comment by Christian-CFP** [comment]
The first time, but as you see some other had this issue before. Now I got it.
restored to 0.11.46. It works. But now to try it again, can not update to 0.11.62 ??

**Comment by Christian-CFP** [comment]
Hey Erik, and whats the solution for this issue?

**Comment by ebaauw** [comment]
As you can see from your stack trace, the `http-proxy-agent` library has broken `https`.  Because of the non-standard way hoobs installs plugins, I cannot see which plugin is using this library.  You need to run Homebridge Hue and that plugin on different Homebridge instances.  I have no idea if that’s possible under hoobs, please contact hoobs support for that.

As a workaround, you might try setting `forceHttp` in config.json, as mentioned above.  This causes Homebridge Hue to use plain `http` instead of `https`.  Not sure how long the Hue bridge API will continue to support this, though.

**Comment by tthoma24** [comment]
Forgive me for reviving a closed issue, but neither using HTTP or running separate homebridge instances seem like solutions. How could this be addressed without either of those to workarounds?

**Comment by ebaauw** [comment]
The solution is for the offending plugin not to break `https`, which means they either need to stop using `http-proxy-agent` or get that library fixed.  This is not an issue caused by homebridge-hue, and apart from the mentioned workarounds, there’s nothing to be done in homebridge-hue.

**Comment by apexad** [comment]
This issue may now be resolved as some of the agent-base dependencies have been fixed.

**Comment by apexad** [comment]
Was talking with @ebaauw and he made a good point.
Try re-installing all plugins and then re-install homebridge-ws and you may find that it works, but we cannot know with 100% certainty because of how node works with dependencies.
