### ISSUE TITLE
Fyrtur blinds and DeCONZ 

### ISSUE THREAD

**Issue by mtjoernelund** [ebaauw/homebridge-hue#630]
I have two Fyrtur blinds installed and paired with the Deconz hub, and added to homekit via Homebridge and Homebridge-Hue. Physically both works flawlessly. I can open and close the blinds using both the open/close remote as well as in the home app. I can also open them partly using both methods and I can set their statein scenes in homekit.

However, there is one minor annoyance. When the blinds are fully open, all is good. But when the blinds are partially or fully closed, the Home app reports the blinds as “Closing”. I assume that they should do so while in the process of closing, but once they have reached their set state (e.g. fully closed) I would expect them to report as “Closed”. Am I incorrect? What is the expected behavior?

Homebridge log does not output anything from the blinds themselves, only a message regarding button presses on the open/close remotes.

I am running homebridge v. 0.4.50, Homebridge Hue v. 0.11.55 and Deconz v. 2.05.73.

**Comment by ebaauw** [comment]
> I would expect them to report as “Closed”.

So would I.

> Homebridge log does not output anything from the blinds themselves, only a message regarding button presses on the open/close remotes.

That might explain why Home continues to show _Closing..._, but then the current state shouldn't be updated as well.  What do other HomeKit apps show?

Even if deCONZ has failed to setup attribute reporting, the blind state should be updated next time homebridge-hue polls the gateway.  Please capture and attach a debug log file, so I can see what's going on, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by mtjoernelund** [comment]
Quick update, will add a complete log file when I am back at my computer. But I just did a quick check changing position of the blinds in HomeKit with homebridge debug logging. And when I change position of the blinds I see log entries saying: “HomeKit target position changed from x to y”. However there is never a “success” message in the log (should there be?). 

Off interest, both The Eve and Home+ app always report position as 100%. However, regardless if set in one app or the other both apps report the requested percentage. 

Another thing that I noticed (however not sure if this is at all related) is that both blinds  report battery at 0% (or have just not reported battery level).

So it seems that commands send to the blinds does come through to the blinds, but no status reports are received from the blinds.

**Comment by mtjoernelund** [comment]
One more observation maybe of interest. In NodeRed, the blinds does not report state changes, and even if I manually query the blinds they consistently report value of brightness as 0 notwithstanding actual state. Goes for both my blinds. Maybe an issue with the binding in DeCONZ?

**Comment by ebaauw** [comment]
I’m afraid that’s an issue between the blind and deCONZ.  I have seen the blind becoming unreachable from the gateway, but not the other way round.  Try removing the battery from the blind for a couple of seconds.

> However there is never a “success” message in the log (should there be?).

You should see a gateway command to PUT the light state, and a corresponding OK.  Then you should see messages that state.bri has changed and Homekit current position is updated.

**Comment by ebaauw** [comment]
I’m afraid that’s an issue between the blind and deCONZ.  I have seen the blind becoming unreachable from the gateway, but not the other way round.  Try removing the battery from the blind for a couple of seconds.

> However there is never a “success” message in the log (should there be?).

You should see a gateway command to PUT the light state, and a corresponding OK.  Then you should see messages that state.bri has changed and Homekit current position is updated.

**Comment by mtjoernelund** [comment]
Ok. I tend to think that you are on point, i.e. that this is an issue between the blinds and the gateway. Been messing about in DeCONZ gui this afternoon, and by forcing an update in the gui, the position of the blinds suddenly got updated and the missing battery report went away. However, when I quit the gui and reverted to headless, one of the blinds messed up its position again, but the other one did not. I think I may need to try to repair them to the gateway and see if this improves things. Thanks for your input and work on this!

**Comment by ebaauw** [comment]
> I think I may need to try to repair them to the gateway and see if this improves things.

Or setup the binding and attribute reporting manually.

**Comment by mtjoernelund** [comment]
So, this morning I tried removing the batteries for about 15 sec and reinserting. This seems to have done the trick, although I would like to see it work over time. But so far fingers crossed. 

> Or setup the binding and attribute reporting manually.

Appreciate the suggestion, but I’m not sure my knowledge of Zigbee extends that far. I was literally blundering my way around the DeCONZ gui yesterday learning as I went along. But if they stop working again I may need to do the homework and try to understand better. 

One last question: my blinds are on firmware ver 2.2.007. Latest version seem to be 2.2.009. What version are you running?

**Comment by ebaauw** [comment]
I updated my blind to 2.2.009 a while ago.  I don’t think I’ve seen much difference with 2.2.007.

**Comment by mtjoernelund** [comment]
Thanks. I am not going to try to force an update then. So far it seems to work flawlessly after the removing of the battery. 

Just want to say thanks for some great software and your quick feedback. It is really appreciated!

**Comment by parruda** [comment]
For those that land here looking for a solution, I solved my problem by creating this binding and setting the reporting interval attributes manually in deCONZ. I posted the steps in another issue:
https://github.com/ebaauw/homebridge-hue/issues/530#issuecomment-691092127

**Comment by parruda** [comment]
@mtjoernelund were you able to make the open/close remote also stop the action when you press it a second time? I can't figure this out.

For example, if you press `close` on the remote, then mid-closing you press `close` again, the blinds should stop where they are. That's the behaviour when setting up the blinds the original way.

**Comment by mtjoernelund** [comment]
Actually I just installed another Fyrtur. While I am a little afraid to jinx this, here goes: 

This time I did nothing but pair first the Fyrtur then the remote using the Deconz web. 

With that done I first tried making a group in the web-view. I could add the Fyrtur, but not the remote for some reason. However, opening the old web-interface, I could simply add the Fyrtur to the group that is automatically created for the remote. 

Doing this all works flawlessly. I can single press the remote to drive the blinds all the way up/down. I can press and hold for the blinds to go up/down til I release the button and I can press either up/down on the remote to stop the blind where it is.

**Comment by mtjoernelund** [comment]
It seems that I did speak to soon. After restarting Homebridge the blinds show in Homekit and while I can control them the state reporting seems to be missing as per my original post in this thread...

**Comment by mtjoernelund** [comment]
Ok, solution was pretty simple. Remove the battery in the blinds and wait for a few seconds before putting them back. Then the blinds started to report state to Homebridge. After rebooting Homebridge, status also updated perfectly in Homekit. 

So to summarize for anybody tripping over this thread in the future, these are the steps that made it work for me:
1. Pair the blind in Deconz Web GUI
2. Pair the remote in Deconz Web GUI
3. In the old web-app add the blinds to the group created by the remote
4. Restart Homebridge
5. Remove the battery from the blind for some seconds and then reinsert it
6. Restart Homebridge again
