### ISSUE TITLE
Delay with original Philips switches

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#631]
#### Issue
Hi,
I have moved over from a direct connection (HomeKit to my Hue Bridge (V2)) to Homebridge-Hue.

Since this change all my switches are switching really slow (all original Philips switches).
I have a delay of 2-4sec on every press via the plugin. 
Is there a way to get them faster?
The Hue Bridge and Homebridge are on the same vLAN, my Apple TVs are on a different one. If I control the lamps via the Apple Home App, all works really fast (from the same vLAN like the Apple TVs). It must be related to the switches directly.

Thanks for your help!

JSON:
   

            "name": "Homebridge-Hue",
            "anyOn": true,
            "excludeSensorTypes": [
                "ZLLRelativeRotary",
                "ZLLPresence",
                "ZLLLightLevel",
                "ZLLTemperature",
                "ZHAHumidity",
                "ZHAPressure",
                "ZHAOpenClose",
                "ZHAAlarm",
                "ZHACarbonMonoxide",
                "ZHAFire",
                "ZHAVibration",
                "ZHAWater",
                "ZHAConsumption",
                "ZHAPower",
                "ZHAThermostat",
                "Daylight",
                "CLIPGenericFlag",
                "CLIPGenericStatus",
                "CLIPPresence",
                "CLIPLightLevel",
                "CLIPTemperature",
                "CLIPHumidity",
                "CLIPPressure",
                "CLIPOpenClose",
                "CLIPAlarm",
                "CLIPCarbonMonoxide",
                "CLIPFire",
                "CLIPVibration",
                "CLIPWater",
                "CLIPConsumption",
                "CLIPPower",
                "Geofence",
                "CLIP"
            ],
            "forceCt": true,
            "hosts": [
                "192.168.0.50"
            ],
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "users": {
                "xxxxxxxxxx": "yyyyyyyyyyyy"
            },
            "platform": "Hue"
        }
    ]
}

**Comment by ebaauw** [comment]
The Hue bridge doesn't support push notifications, so homebridge-hue needs to poll the bridge.  By default it does so once every 5 seconds.  You can change that (using Eve) dynamically in the accessory that homebridge-hue exposes for the Hue bridge.  To change that permanently, set `heartrate` in config.json, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.  While supported by homebridge-hue, a `heartrate` of `1` might be too much for the Hue bridge.

**Comment by jostrasser** [comment]
Thanks for the fast feedback!
I will give him a try and set a heartrate of „2“.
Thanks!

**Comment by Nastras** [comment]
I have noticed the same behaviour.

I have also tried a lot of things by changing the heartrate from 1 to 2 and from 2 to 1.

Unfortunately I have not found a solution for the problem yet.

Last week after the hue firmware update, when the buttons in homekit were deleted, I had to program everything temporarily via hue. My wife is enthusiastic about the performance of the switches and lights. No delay present.

She forbids me to switch back to homekit which is a pity as I can't create any rules in connection with the blinds but only day and night 🤪

If we could find a solution to this problem, that would be great.

**Comment by ebaauw** [comment]
In general, I wouldn’t recommend HomeKit automations for controlling ZigBee devices from other ZigBee devices.  I have programmed all of these controls using rules on the deCONZ gateway (or the Hue bridge).  Far less user friendly to create and maintain, but far more reliable, faster, and restorable (if you create them from scripts).  I only use HomeKit automations to control non-ZigBee devices (notably my Sonos speakers), and for detecting who’s at home.

People have been bitching about the lack of support for notifications on the Hue developer forum for years, to no avail.  I don’t think we’ll see any change there.  If you insist on using HomeKit automations, expose the switches natively through the Hue bridge, or move to deCONZ (which does support notifications), to eliminate the polling delay.

**Comment by Nastras** [comment]
Thanks for the explanation. Yes you told me in another issue that it is better for the switches and lights not to be put on HomeKit. There I agree with you in principle also!

But as I own roller blinds I would like my house to continue to use the night rule for the switches when the blinds are closed. Therefore I have to set the blinds as a condition and this is unfortunately only possible via homekit itself.

But I didn't know that the switches work worse than with deconz via the hue bridge. I assumed that hue and deconz are the same.

I will later change a switch to deconz and try it.

**Comment by Nastras** [comment]
Hey Erik, once again you were right. If you put the switches above deconz, the delay is gone.

So the behaviour is only present if you connect the switches via homebridge-hue and the hue bridge.

Of course it is a pity that I have to move all switches to deconz now. I would have liked to have them on the hue bridge to program the switches myself in case of an emergency via hue.

I already tried to integrate everything via deconz. We were writing together back then, but the performance is very slow with the amount of equipment. So I sit here with my 4 Zigbee Bridges j3 x Hue and 1 x deCONZ) because of the speed and now I have to bake something 😅

Thanks for the tip.

**Comment by ebaauw** [comment]
> Of course it is a pity that I have to move all switches to deconz now.

Or expose them natively (although I don’t think the Hue bridge exposes _Long Press_).

> to program the switches myself in case of an emergency via hue.

You can do the same programming in deCONZ.  And with deCONZ you can also make the switches control lights directly, even when the gateway is down, by adding lights to the associated group.

**Comment by ebaauw** [comment]
> Of course it is a pity that I have to move all switches to deconz now.

Or expose them natively (although I don’t think the Hue bridge exposes _Long Press_).

> to program the switches myself in case of an emergency via hue.

You can do the same programming in deCONZ.  And with deCONZ you can also make the switches control lights directly, even when the gateway is down, by adding lights to the associated group.

**Comment by Nastras** [comment]
Exactly natively there is no double press, furthermore I would miss the key 3 with 4 and 5 with 6 in the hue tap.

In order to program the lights in deconz I would have to re-train all lights on the deconz gateway. And there I had big speed problems due to the number of devices.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1741

That would be great if it would work with only one gateway. 

Or is there a possibility to program switches and lights across bridges with deconz?
So lamp 1 is on hue bridge and switch 1 is on the deconz gateway.

BTW: In the meantime I have also taken everything from ikea out of service and completely converted to hue 😉

**Comment by ebaauw** [comment]
With an external program you could receive notifications from deCONZ for a Hue dimmer switch, and write the buttonevent value to a CLIPSwitch on another deCONZ instance (or even a Hue bridge).  Then use the usual rules on the other instance to control the lights.  Wouldn’t recommend this (another component to fail), unless you already integrate the multiple bridges/gateways in some home automation system anyways

There is an ancient mechanism in deCONZ to forward group commands from one gateway to another, or even to a Hue bridge, effectively spanning a group over two gateways.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/287.

**Comment by Nastras** [comment]
Thanks for the advice, I'll take a closer look at it next time.
