### ISSUE TITLE
Support for Aqara Opple Deconz

### ISSUE THREAD

**Issue by raddi** [ebaauw/homebridge-hue#637]
Will there be Aqara Opple support as in the newest beta/stable release of the deconz rest plugin the switch is already supported:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2061
It's not displayed in the phoscon app but it does show up in the device map of deconz. Is it therefore usable in homebridge-hue?
Thanks for your work!

**Comment by ebaauw** [comment]
Not yet, it doesn't report the right `buttonevent` values.

**Comment by ebaauw** [comment]
In v0.11.57, in anticipation of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2061.
