### ISSUE TITLE
Issue with v0.11.55 and Zigbee RGBCCT Strip Controller

### ISSUE THREAD

**Issue by Sciphere** [ebaauw/homebridge-hue#638]
#### Issue

The latest update seems to break compatibility with my Zigbee RGBCCT Strip Controller. I rolled back the version to v0.11.52 and it seems to have fixed the issue. Please look into this.

Thanks!

[(here is the controller on Amazon for reference) 
](https://www.amazon.com/Zigbee-Controller-Compatible-Lightify-Control/dp/B07FTD9H7T/ref=sr_1_1?keywords=GIDERWEL+Home+Smart+Zigbee+RGBCCT+Strip+Controller+Compatible+with+Hue+Bridge+Amazon+Echo+Plus+Alexa+and+Lightify+Hub+for&qid=1582899779&sr=8-1)

btw, the log below was the only thing out of the ordinary before I reverted the version.. not sure if its related. 

#### Log Messages

``` 
[2/28/2020, 9:08:14 AM] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.36.0
```

**Comment by ebaauw** [comment]
Is that a GLEDOPTO GL-C-008?  If so, see #636.

Otherwise, please capture and attach a debug log file, and also attach the debug dump file.  See https://github.com/ebaauw/homebridge-hue#troubleshooting.

**Comment by Sciphere** [comment]
I can't find any model numbers on the device.. but it does say GLEDOPTO  (I guess they changed the name?)

I went ahead and tried your beta update and it seems to have fixed the issue. 

thanks

**Comment by ebaauw** [comment]
> I can't find any model numbers on the device.

No, you'd need to check the API or the deCONZ GUI.  Anyway, since the beta fixed it, it is a GL-C-008.
