### ISSUE TITLE
HomeKit color adjustments of native hue lamps not reliable

### ISSUE THREAD

**Issue by dibimuc** [ebaauw/homebridge-hue#641]
I run Philips Hue via Hoobs in HomeKit. Perfect integration!
However, I discover that changing the colors in HomeKit to a native Hue bulb ist not reliable. 

For instance, if I activate a scene in HomeKit, the last values of the bulb stetted manually are chosen. Sometimes, a scene is overwritten with this values. 
![tg - 1](https://user-images.githubusercontent.com/61652682/75625416-fd9b9580-5bbd-11ea-8fe5-3638639b9dc0.png)

**Comment by ebaauw** [comment]
See #571
