### ISSUE TITLE
Gledopto issues

### ISSUE THREAD

**Issue by peterb99** [ebaauw/homebridge-hue#644]
#### Issue

Hello Eric

I have an Gledopto RGB+CCT controller for led strip with two different ID's one for color LED strip control and one for the white leds.
Only one of the two shows up in the HomeKit as a light ( 'Color at wall')
When looking at the home bridge accessories window, both lights show up, but with same model id; GL-C-007
It should be, GL-C-006 and GL-C-007

The dump file show both with correct model ID

I've toggled the force CT setting, but do not see a difference.
Any thoughts?

Regards
Peter

#### Log Messages

Initializing platform accessory 'E******d 1'...
3/2/2020, 3:55:36 PM Edgehead 1: 2 services
3/2/2020, 3:55:36 PM [HuePB] Initializing platform accessory 'Color at wall'...
Setup Payload:
X-HM://0024XPK8Q12KH
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
┌────────────┐ 
 │ 8**-46-**6                           │   
└────────────┘  
 Homebridge is running on port 51646.
3/2/2020, 3:55:56 PM] [Config] [admin] Accessory layout changes saved.
[3/2/2020, 3:56:00 PM] [admin] Accessory layout changes saved.
[3/2/2020, 3:57:29 PM] [Config][admin] Accessory layout changes saved.

+ lights controlled via philips hue app +
[3/2/2020, 4:05:44 PM][HuePB] Bright at wall: set homekit on from 1 to 0
[3/2/2020, 4:05:49 PM][HuePB]Color at wall: set homekit on from 0 to 1
[3/2/2020, 4:05:54 PM][HuePB]Color at wall: set homekit on from 1 to 0
[3/2/2020, 4:05:54 PM][HuePB] Bright at wall: set homekit on from 0 to 1
[3/2/2020, 4:05:59 PM][HuePB] Bright at wall: set homekit on from 1 to 0
+ light controlled via HomeKit, note the on/off by tapping icon does not work, need to use slider in icon to change light on and off +
[3/2/2020, 4:06:07 PM[HuePB]Color at wall: homekit brightness changed from 0% to 28%
[3/2/2020, 4:06:07 PM] Color at wall: homekit on changed from 0 to 1
[3/2/2020, 4:06:07 PM][HuePB]Color at wall: homekit brightness changed from 28% to 31%
[3/2/2020, 4:06:12 PM][HuePB]Color at wall: homekit brightness changed from 31% to 0%
[3/2/2020, 4:06:12 PM][HuePB]Color at wall: homekit on changed from 1 to 0
[3/2/2020, 4:06:14 PM][HuePB]Color at wall: set homekit brightness from 0% to 16%

#### Debug Files

[hb3.json.gz](https://github.com/ebaauw/homebridge-hue/files/4276360/hb3.json.gz)

**Comment by ebaauw** [comment]
> I have an Gledopto RGB+CCT controller for led strip with two different ID's one for color LED strip control and one for the white leds.
> It should be, GL-C-006 and GL-C-007

Is this a five-channel RGB+CCT controller?  The GL-C-007/GL-C-006 I've seen is a four-channel RGWB controller.  The GL-C-008 five-channel RGB+CCT controller I've seen only has one endpoint (and one `/lights` resource).  Can you drive the RGB and CCT channels separately from their respective `/lights` resources?  What happens if you set `ct` on the _Extended color light_ resource?

You didn't attach a debug log file, but by default homebridge-hue exposes your controller as a single accessory with two _Lightbulb_ services.  Depending on the accessory settings, Apple's Home app might show this as one or two tiles.  The model is at the accessory level and taken from the first resource.

To expose the controller as two separate accessories, create a `splitlight` resource link, see #493.

**Comment by peterb99** [comment]
Hallo Eric


> On 2 Mar 2020, at 19:55, Erik Baauw <notifications@github.com> wrote:
> 
> I have an Gledopto RGB+CCT controller for led strip with two different ID's one for color LED strip control and one for the white leds.
> It should be, GL-C-006 and GL-C-007
> 
> Is this a five-channel RGB+CCT controller? The GL-C-007/GL-C-006 I've seen is a four-channel RGWB controller.
> 
It is,

> The GL-C-008 five-channel RGB+CCT controller I've seen only has one endpoint (and one /lights resource). Can you drive the RGB and CCT channels separately from their respective /lights resources? What happens if you set ct on the Extended color light resource?
> 
> 
Indeed,

> You didn't att
> 




> ach a debug log file,
> 

I thought I did, it was visible in the text part of the message to my surprise.

> but by default homebridge-hue exposes your controller as a single accessory with two Lightbulb services. Depending on the accessory settings, Apple's Home app might show this as one or two tiles. The model is at the accessory level and taken from the first resource.
> 
> To expose the controller as two separate accessories, create a splitlight resource link, see #493 <https://github.com/ebaauw/homebridge-hue/issues/493>.
> 
> 
Ill have a look at that.

Groetjes
Peter

**Comment by peterb99** [comment]
> On 2 Mar 2020, at 19:55, Erik Baauw <notifications@github.com> wrote:
> To expose the controller as two separate accessories, create a splitlight resource link, see #493 <https://github.com/ebaauw/homebridge-hue/issues/493>.
> 
> 
Having read through the thread, I think in this case the lights are already split by gledopto it self, but for some reason the homebridge combines them in a halfway form.

See below showing each light as separate light in the json output;

"20" : {
                    "state" : {
                        "on" : false,
                        "bri" : 1,
                        "hue" : 35840,
                        "sat" : 81,
                        "effect" : "none",
                        "xy" : [
                            0.2799,
                            0.2887
                        ],
                        "ct" : 322,
                        "alert" : "select",
                        "colormode" : "xy",
                        "mode" : "homeautomation",
                        "reachable" : true
                    },
                    "swupdate" : {
                        "state" : "notupdatable",
                        "lastinstall" : "2020-01-22T22:25:42"
                    },
                    "type" : "Extended color light",
                    "name" : "Color at wall",
                    "modelid" : "GL-C-007",
                    "manufacturername" : "GLEDOPTO",
                    "productname" : "Extended color light",
                    "capabilities" : {
                        "certified" : false,
                        "control" : {
                            "colorgamuttype" : "other",
                            "ct" : {
                                "min" : 0,
                                "max" : 65535
                            }
                        },
                        "streaming" : {
                            "renderer" : false,
                            "proxy" : false
                        }
                    },
                    "config" : {
                        "archetype" : "huelightstrip",
                        "function" : "mixed",
                        "direction" : "omnidirectional"
                    },
                    "uniqueid" : "00:12:4b:00:1f:7a:94:6e-0b",
                    "swversion" : "2.0.2"
                },
                "21" : {
                    "state" : {
                        "on" : true,
                        "bri" : 254,
                        "ct" : 442,
                        "alert" : "select",
                        "colormode" : "ct",
                        "mode" : "homeautomation",
                        "reachable" : true
                    },
                    "swupdate" : {
                        "state" : "notupdatable",
                        "lastinstall" : "2020-01-22T22:25:45"
                    },
                    "type" : "Color temperature light",
                    "name" : "Bright at wall",
                    "modelid" : "GL-C-006",
                    "manufacturername" : "GLEDOPTO",
                    "productname" : "Color temperature light",
                    "capabilities" : {
                        "certified" : false,
                        "control" : {
                            "ct" : {
                                "min" : 158,
                                "max" : 500
                            }
                        },
                        "streaming" : {
                            "renderer" : false,
                            "proxy" : false
                        }
                    },
                    "config" : {
                        "archetype" : "huelightstrip",
                        "function" : "functional",
                        "direction" : "omnidirectional"
                    },
                    "uniqueid" : "00:12:4b:00:1f:7a:94:6e-0f",
                    "swversion" : "2.0.2"
                },

**Comment by ebaauw** [comment]
> I think in this case the lights are already split by gledopto it self,

It exposes two ZigBee endpoints (0x0b and 0x0f): one _Extended color light_ and one _Color temperature light_.  The Hue bridge creates a `/lights` resource per endpoint.  Note the `uniqueid` attribute: it's composed of the mac address and the endpoint.

> but for some reason 

By design

> the homebridge combines them in a halfway form

See my earlier answer: 
> by default homebridge-hue exposes your controller as a single accessory with two _Lightbulb_ services

**Comment by peterb99** [comment]
> On 3 Mar 2020, at 19:23, Erik Baauw <notifications@github.com> wrote:
> 
> I think in this case the lights are already split by gledopto it self,
> 
> It exposes two ZigBee endpoints (0x0b and 0x0f): one Extended color light and one Color temperature light. The Hue bridge creates a /lights resource per endpoint. Note the uniqueid attribute: it's composed of the mac address and the endpoint.
> 
> but for some reason
> 
> By design
> 
> the homebridge combines them in a halfway form
> 
> See my earlier answer:
> 
> by default homebridge-hue exposes your controller as a single accessory with two Lightbulb services
> 
> 
Why are those two lightbulb services not showing up ? It does not seem to be possible to control each lightbulb service separately like in the philips hue app?

**Comment by ebaauw** [comment]
> Why are those two lightbulb services not showing up ?

See my previous answer:
> Depending on the accessory settings, Apple's Home app might show this as one or two tiles.

> It does not seem to be possible to control each lightbulb service separately like in the philips hue app?

It should be.  If you want me to investigate, please capture and attach a full debug log, and attach screen shots of the tile, of the popup window (that appears when pressing the tile) and of the settings window (that appears when pressing the gear symbol at the bottom of the popup window).

**Comment by peterb99** [comment]
> On 3 Mar 2020, at 20:24, Erik Baauw <notifications@github.com> wrote:
> 
> Why are those two lightbulb services not showing up ?
> 
> See my previous answer:
> 
> Depending on the accessory settings, Apple's Home app might show this as one or two tiles.
> 
> It does not seem to be possible to control each lightbulb service separately like in the philips hue app?
> 
> It should be. If you want me to investigate, please capture and attach a full debug log, and attach screen shots of the tile, of the popup window (that appears when pressing the tile) and of the settings window (that appears when pressing the gear symbol at the bottom of the popup window).
> 
> 
Thanks for your help. I had a further look. It seems that under the initial tile , two ‘operator panels’ are available. It is not obvious as the second one is hidden underneath the first one and you have to scroll down to get to it. See screenshots below.
