### ISSUE TITLE
Aqara motion sensors take very long to switch back to "no motion" can i adjust this? (Question not issue) 

### ISSUE THREAD

**Issue by skitzow88** [ebaauw/homebridge-hue#645]
I just bought a Conbee 2 and installed Deconz/Phoscon. When migrating my sensors from the aqara hub to deconz i noticed a very big change in the reporting of the motions sensors. It takes roughly 2 minutes of no motion before state can be switched back. I am completely new to deconz/conbee, so to make a long story short "is there a way i can adjust this?"

**Comment by ebaauw** [comment]
homebridge-hue just forwards the status from deCONZ.  I don't have this device myself, but it's been discussed extensively in the deCONZ repository, see e.g. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1671.

**Comment by skitzow88** [comment]
Thank you for the information will look in to it.
