### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by netRunner0** [ebaauw/homebridge-hue#647]
Is it possible to change the timer through the characteristics to turn on / off the light on the hue motion sensor?

**Comment by netRunner0** [comment]
![IMG_0553](https://user-images.githubusercontent.com/44049295/75914828-3d40d680-5e77-11ea-9ac3-cd5069361a45.png)

**Comment by ebaauw** [comment]
I have no idea.  This functionality is offered by the app, not by homebridge-hue.

**Comment by netRunner0** [comment]
Ok, I’ll take advantage of turning off the sensor instead of increasing the timer
