### ISSUE TITLE
Support "Show as" for Plugs?

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-hue#649]
Hi,

(sorry if this is a duplicate or already supported. #566 and #63 did not really help.)

I'm using deCONZ with a few OSRAM plugs. They're exposed as `/light`s via the API, so they're shown as "Light" in HomeKit and work as expected. But I dont use them for lights.

I have an old Eve Energy Plug (native HomeKit support via bluetooth). In the HomeApp you can specify how HomeKit should show it (it's called "Anzeigen als" in german). It's possible to select Light, Fan or Outlet.

Is this already possible with homebridge-hue? If not, is it possible to add this?

I already have the "outlet" resourcelink:

```
{
  "classid": 1,
  "description": "outlet",
  "links": [
    "/lights/3",
    "/lights/4",
    "/lights/5",
    "/lights/11",
    "/lights/14"
  ],
  "name": "homebridge-hue",
  "owner": "...",
  "recycle": false,
  "type": "Link"
}
```

![IMG_5632](https://user-images.githubusercontent.com/869857/76070082-3fe51e00-5f94-11ea-8656-ec9acee4c870.PNG)

![IMG_5631](https://user-images.githubusercontent.com/869857/76070094-42e00e80-5f94-11ea-82c3-a40ee6a3dc1c.PNG)

**Comment by ebaauw** [comment]
That setting is accessible only to HomeKit apps similar to accessory and service names, rooms, groups, scenes, and automations.  It's not exposed over HAP, so there's nothing homebridge-hue can do.

**Comment by jan666** [comment]
hm, are you sure about this?

I have a homematic plug thats added in fhem. I just added it to homebridge via homebridge-fhem (https://www.npmjs.com/package/homebridge-fhem) and it just works like on the eve:

<img width="419" alt="838-1620-max" src="https://user-images.githubusercontent.com/869857/76077363-da4b5e80-5fa0-11ea-8290-924e974d0a93.png">

there is no native homekit support for homematic or fhem

**Comment by jan666** [comment]
Uh, WTF.

I wanted to test the deCONZ -> FHEM -> homebridge-fhem route. Added my osram plug to fhem via deCONZ REST API, added it to my homebridge-fhem room, restartet homebridge and it worked like I wanted. But now all the deCONZ -> homebridge-hue plugs do it, too. It still works after removing it from homebrige-fhem. How is that even possible? I'm really confused.

<img width="398" alt="796-1620-max" src="https://user-images.githubusercontent.com/869857/76080622-9019ab80-5fa7-11ea-9807-01cf040225cf.png">
