### ISSUE TITLE
Multi-resource devices

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#65]
Some devices, like the Hue motion sensor and the dresden electronic [FLS-PP lp](https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/wireless-ballasts/?L=1) wireless ballast, use multiple resources on the Hue bridge.  For each of these resources, homebridge-hue creates a separate HomeKit service.
Historically, homebridge-hue created a separate HomeKit accessory for each service.  As of v0.3, homebridge-hue will create a single HomeKit accessory for a multi-resource device, containing the services for all its resources.  The `AccessoryInformation` and `Battery` services will be linked to the first resource on the Hue bridge for the device.

Apart from HomeKit reflecting more accurately the real-world, this change reduces the number of accessories created by homebridge-hue.  With the HomeKit limit of 99 bridged accessories, this allows homebridge to support more devices, without having to resort to running multiple instances.  While there is another HomeKit limit of 99 services per accessory, we won't be hitting that limit.

This change has subtle, but only limited impact on the user experience:
- The iOS built-in Home app shows a tile per service.  The only change you'll notice is that when you change the location (room) of one service, the other services for the device move as well.  
- Elgato's Eve app shows a line per service in the _Rooms_ view.  In the details, it shows all services of the corresponding accessory, in alphabetical order of the service name.  Under _Settings_, _Accessories_ Eve shows the accessories.  In the details under _Siri Names_, it shows the services in order of creation.
- Matthias' Home app shows a line per (supported) service in the _Services_ view.  In the  _Home_ view, it shows a line per accessory, with the supported services.  In the details, it shows all services, in order of creation.

After updating to homebridge-hue v0.3, the newly exposed accessories will appear in the default room.  You will have to update manually any HomeKit rooms, groups, scenes, and rules that contained one of the old accessories (hence the bump in minor version number).

@pponce, @tkropf, could you please check if this works correctly for the FLS-PP?

**Comment by pponce** [comment]
Just commented under issue #64.
I see one accessory and am expecting to see 2 based on the description. 
And the accessory i see seems to be just the RGB light for one of the ballasts. I don't see the white led.
(By the way i really appreciate the very thorough notes/documentation you provide ).

**Comment by ebaauw** [comment]
That's a bug alright.  Should be fixed in v0.3.1.

**Comment by pponce** [comment]
v0.3.2 looks like it did the trick.
Things are working as described with the ballasts.
thanks!

**Comment by ebaauw** [comment]
Could you please check v0.3.3?  There's another issue with v0.3.2, see #64.

**Comment by pponce** [comment]
installing right now and will give it a go.

**Comment by pponce** [comment]
0.3.3 works great. thanks for the fix and for all the work on this plugin.

**Comment by tkropf** [comment]
Confirmed, works like a charme for the FLS-PP. Also kudos to you for all the great work on this plugin!
