### ISSUE TITLE
nupnp config option is ignored

### ISSUE THREAD

**Issue by bachandi** [ebaauw/homebridge-hue#653]
#### Issue

The platform nupnp config option is not accounted for during dicovery. In HueDiscovery.js the nupnp config options has to be checked in the _nupnp function. 

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Thanks for the PR!

Looks like I missed it when introducing `HueDiscovery`, which was over 1.5 years ago.  I suppose not too many people are actually using this setting.

**Comment by bachandi** [comment]
Thanks for the merge. Yes the discovery logic back then was still in the platform search logic. But I didn‘t find/search the exact commit it was lost.
Great project btw. Cheers

**Comment by ebaauw** [comment]
In v0.11.58.
