### ISSUE TITLE
Question on Characteristic.StatusActive

### ISSUE THREAD

**Issue by ceraz68** [ebaauw/homebridge-hue#656]
#### Question
Hi ebaauw, you seem to be only person with clean code using Characteristic.StatusActive. But still haven't figured it it's purpose, maybe you can share some experience?

I have a working plugin with a light sensor that shows up fine on IOS 13. I'd like the homekit icon to turn on (like a contact sensor triggering) when a certain lux value is reached. Is this what the optional characteristic StatusActive is supposed to do?

I couldn't find any on-line explanation if it changes anything to the icon and nothing show up in the Eve app.

Thanks a lot!

#### Code

So I added the optional characteristic as follows under the plugin getServices function:
		this.smaSensor = new Service.LightSensor(this.name);
		this.smaSensor
			.getCharacteristic(Characteristic.CurrentAmbientLightLevel)
                        .on("get", this.getSensorValue.bind(this));
                this.smaSensor
        	       .addCharacteristic(Characteristic.StatusActive)
                       .on("get", this.getSensorStatus.bind(this));

In the referred getSensorStatus, I just forced to true to check what happens (but nothing does):
getSensorStatus: function(callback) {callback(null, true);}

And in the main function of the accessory plugin, I tried
this.smaSensor.updateCharacteristic(Characteristic.StatusActive, true)

#### Log Messages
N/A

**Comment by ebaauw** [comment]
You don't want to be using `characteristic.on('get', ...)` - better push the changed value through `charactertistic.setValue()` or `charactertistic.updateValue()` or the service variants.

Eve displays an exclamation mark when `StatusActive` is false.  I don't think Home does anything with it.

**Comment by ceraz68** [comment]
Thanks ebaauw, i struggled a bit and found a working solution for my plugin. In the home app it adds a new "Status Active" property in the icon settings. This can't be used for automations. Also visible in Eve as "Inactive" or "Active" but can't be used as a rule trigger.

So not very useful for the moment. I'll leave the code in case some features pop-up in the future.

Under getservices for the light sensor accessory, I added: `this.smaSensor.setCharacteristic(Characteristic.StatusActive, this.StatusActive);`

where "this.Status active" is true or false depending on lux value

In the main function I have as follows (couldn't get updateValue or setValue working - I not read at coding), `self` is there for scope reasons:

`if (self.power >= 10) self.smaSensor.setCharacteristic(Characteristic.StatusActive, true)
  else self.smaSensor.setCharacteristic(Characteristic.StatusActive, false);`

**Comment by ebaauw** [comment]
This looks OK to me, though personally, I would optimise the code to:
```
self.smaSensor.setCharacteristic(Characteristics.StatusActive, self.power >= 10);
```
