### ISSUE TITLE
Friends of hue long press

### ISSUE THREAD

**Issue by dergreg** [ebaauw/homebridge-hue#659]
Hi Erik,

Is there a way to configure a long press for the friends of Hue Switches?
I just setup a Voltus four button switch and it works fine both in the Hue app and in HomeKit. But in HomeKit I miss a long press option for any of the buttons.

**Comment by ebaauw** [comment]
I don't know that switch.  Could you please attach the debug dump file, so I can have a look at how the Hue bridge exposes it?  See https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by dergreg** [comment]
It is this switch, connected to a Hue bridge (not deCONZ): https://www.voltus.de/?cl=details&anid=d8efb94f672f104547a752e153b27d0f

I attached a part of the json file, the original is 10000 lines long and contains sensitive data (ihmo). Hope this is fine for you, if you need more info, feel free to ask.

Thanks!

[voltus_foh.json.log](https://github.com/ebaauw/homebridge-hue/files/4333982/voltus_foh.json.log)

**Comment by ebaauw** [comment]
> the original [...] contains sensitive data (ihmo). 

I mask IP addresses and API keys (although the Hue bridge has already masked all but the key you're using).

> I attached a part of the json file [...] Hope this is fine for you

Yes, it is; this is the info I was looking for.

The switch doesn't send anything on long press, only on press and on release.  As the Hue bridge doesn't provide push notifications, homebridge-hue needs to poll the bridge.  This typically means that the press message will be missed, so homebridge-hue only looks for the release messages.

The switch is exposed as a six-button switch, with each button only supporting _Single Press_.  The fifth and sixth buttons are for pressing/releasing both top and both bottom buttons.

**Comment by dergreg** [comment]
> > the original [...] contains sensitive data (ihmo).
> 
> I mask IP addresses and API keys (although the Hue bridge has already masked all but the key you're using).

You‘re right, I just didn‘t want to expose my whole house setup 😉

> 
> > I attached a part of the json file [...] Hope this is fine for you
> 
> Yes, it is; this is the info I was looking for.
> 
> The switch doesn't send anything on long press, only on press and on release. As the Hue bridge doesn't provide push notifications, homebridge-hue needs to poll the bridge. This typically means that the press message will be missed, so homebridge-hue only looks for the release messages.
> 
> The switch is exposed as a six-button switch, with each button only supporting _Single Press_. The fifth and sixth buttons are for pressing/releasing both top and both bottom buttons.

Any chance to expose the buttons 5 and 6 in HomeKit then? I only see four in the home app, iConnectHue also supports six.
![99E31468-9650-4C48-AF97-D90B67766B25](https://user-images.githubusercontent.com/39279568/76699651-e4134700-66af-11ea-8b81-4713cd784b7a.jpeg)

**Comment by ebaauw** [comment]
Are you exposing the switch through the Hue bridge, or through homebridge-hue?

**Comment by dergreg** [comment]
Good catch, I guess through the Hue bridge:

`{
            "platform": "Hue", 
            "users": {
                "xx": "xx"
            }, 
            "host": "xx.xx.xx.xx", 
            "excludeSensorTypes": [
                "CLIPPresence", 
                "Geofence"
            ],
            "lights": true
        }`

Maybe setting `nativeHomeKitSensors: false` will do the trick?

**Comment by ebaauw** [comment]
Yeah, you need to set `"sensors": true` and `"nativeHomeKitSensors": false`.  That will expose all `/sensors` resources on the bridge, incl. any CLIP sensors created by the Hue app or iConnectHue.  You might want to add some more entries to `excludeSensorTypes`.

Alternatively, you could only expose the FOH switch by including it in a whitelist resource link (see https://github.com/ebaauw/homebridge-hue#configuration).  Unfortunately, there's no way to select which devices the Hue bridge should expose, so you'll have to "hide" the switch as exposed by the bridge by moving it to a dummy room.

**Comment by dergreg** [comment]
I implemented the second option, using a whitelist. Now I have buttons 5 and 6 visible in the home app and programmed button 6 (left and right bottom) to trigger the "Good night" scene. Homebridge-hue always detects the click: 

`[3/17/2020, 21:06:33] [Hue] Wohnzimmer Schalter Bottom Both: homekit button single press`

But the scene is not trigged always (maybe 1-2 out of 5 times) or with a delay of about 5 seconds. Any ideas what might be causing this?

**Comment by ebaauw** [comment]
Most likely the network connection between your Home hub (AppleTV or Home Pod) and homebridge.  Preferably they’re both wired to the same switch, otherwise to the same WiFi access point, using the same frequency (both 5 GHz or both 2.4 GHz).  Double-check with `netstat` on the server running homebridge that the Home hub keeps an open connection to homebridge.

**Comment by dergreg** [comment]
Yeah unfortunately the hub is an iPad right now, battery powered and connected via WiFi.

But the actual case here is working now, thanks.

**Comment by holypetrus** [comment]
Hey, can somebody explain how exactly I could use the Ressource-links? Maybe with an example? To be honest, I do not understand how to use them in order to expose my Friends of Hue switches with the two additional buttons.
It would be cool if there would be a way to use the "hold" function.

**Comment by akrtek** [comment]
hi @ebaauw 

Came across this thread and have a similar issue. I have a friends of hue switch - the RunLessWire click. It has two skinny rockers that allow a single and long press in phillips hue. 

I have successfully added it via homebridge but found that I have 6 individual single click options now instead of 4 short and 4 long. Added the log dump. If it is a similar situation to the previous user where the device only handles 6 inputs, can you suggest a switch that works well for homekit that will do long and short or even double clicks

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/7738749/homebridge-hue.json.gz)
