### ISSUE TITLE
Homebridge-Hue crashes Hoobs

### ISSUE THREAD

**Issue by ScharV** [ebaauw/homebridge-hue#661]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4334094/homebridge-hue.json.gz)

#### Issue
Did a fresh install on raspberry with hoobs. Everything works fine but Homebridge hue doesn't.
When I install the plugin, it crashes hoobs. Tried different versions but nothing helps. Just wanted to install the plugin, take my old config and create new users but doesn't work.

#### Log Messages

```
undefined: TypeError: bridgeid: missing string value
```

#### Debug Files

![Bildschirmfoto 2020-03-15 um 11 46 58](https://user-images.githubusercontent.com/50781370/76700293-54bd6200-66b6-11ea-9de6-a9b34ae2a9f9.png)

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4334096/homebridge-hue.json.gz)
[homebrige-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4334097/homebrige-hue.json.gz)

**Comment by ebaauw** [comment]
Please capture and attach a full debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by ScharV** [comment]
@ebaauw have been searching for the debug-log-file on Hoods but didn't find it. 
However, bricked the Server yesterday and did another fresh install today and now it works fine.
Thanks for your great work and your fast reply.
