### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7bcad4ad-f730-4c1b-a6eb-0fba236b0abe

### ISSUE THREAD

**Issue by SchulzMichael** [ebaauw/homebridge-hue#662]
#### Issue

I have moved my lamps from a Lightify and a Hue v2 bridge to deCONZ, unfortunately the hoobs log file always says that there are already devices. I took both old bridges out of the network and removed all lamps separately. 
I also deleted the accessories folder, no success.
I tried the whole thing on two different homebrideges.

Thank you for your help 
#### Log Messages

```Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7bcad4ad-f730-4c1b-a6eb-0fba236b0abe
```

#### Debug Files

[Hue] Initializing Hue platform...
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] homebrige-hue v0.11.46, node v12.16.1, homebridge v0.4.50
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] warning: not using recommended node version v7.0.0 LTS
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] warning: not using recommended homebridge version v0.4.22
[Homebridge] [3/21/2020, 1:13:46 PM] Loading 0 accessories...
[Homebridge] [3/21/2020, 1:13:46 PM] Load homebridge-mi-airpurifier.MiAirPurifierPlatform
[Homebridge] [3/21/2020, 1:13:46 PM] API launched
[Homebridge] [3/21/2020, 1:13:46 PM] [Ferseher im Büro] is running on port 42758.
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] npm registry: status 404 Not Found
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Conbee2-Hue: dresden elektronik deCONZ gateway v2.5.75, api v1.16.0
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Conbee2-Hue: warning: not using recommended deCONZ gateway version undefined
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Daylight: set homekit sunrise from undefined to Sat Mar 21 2020 06:34:01
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Daylight: set homekit sunset from undefined to Sat Mar 21 2020 18:48:31
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Daylight: set homekit light level from 0.0001 lux to 100000 lux
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Conbee2-Hue: 12 accessories
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] masked debug info dumped to /hoobs/etc/homebrige-hue.json.gz
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Initializing platform accessory "Conbee2-Hue".
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Conbee2-Hue: 2 services
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Initializing platform accessory "WZ Fernseher".
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Initializing platform accessory "Configuration tool".
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7bcad4ad-f730-4c1b-a6eb-0fba236b0abe
    at Bridge.Accessory.addBridgedAccessory (/hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
    at Server.<anonymous> (/hoobs/node_modules/@hoobs/homebridge/lib/server.js:380:26)
    at /hoobs/node_modules/@hoobs/hap/lib/util/once.js:16:19
    at /hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:293:5
    at Function.then (/hoobs/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/hoobs/node_modules/deferred/deferred.js:138:15)
    at Function.<anonymous> (/hoobs/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/hoobs/node_modules/deferred/deferred.js:138:15)

**Comment by ebaauw** [comment]
```
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] homebrige-hue v0.11.46, node v12.16.1, homebridge v0.4.50
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Conbee2-Hue: dresden elektronik deCONZ gateway v2.5.75, api v1.16.0
```
You're running a (too) old version of homebridge-hue against a (too) new version of deCONZ.  
```
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] npm registry: status 404 Not Found
[Homebridge] [3/21/2020, 1:13:46 PM] [Hue] Conbee2-Hue: warning: not using recommended deCONZ gateway version undefined
```
It's beyond me why the hoobs people think it a good idea to mutilate homebridge-hue and break the version checks.  Please contact them on how to upgrade homebridge-hue in hoobs.

**Comment by SchulzMichael** [comment]
Thank you very much. That's it. 

i have turned a hoobs installation into a normal homebridge installation and it works.

it should not be HOOBS but HIOOBS called Homebridge issues out of the box :)
