### ISSUE TITLE
rror: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by SSkull995** [ebaauw/homebridge-hue#663]
Hello all! 
I am sorry to bother for this thing, that I found to be already discussed. However, something very weird happened today, while I was trying to add some bulbs and a smart plug to the phoscon app. 
I have a raspi 4 with raspbee installed, no problems since before the bulb addition! When I tried to add a bulb, something unexpected arose:

Vendordresden elektronik
ModelRaspBee
Version 0x26330500
Firmware is up to date.
The light is assigned to the following group

**This is an apparent bulb that the raspbee found, Unknown 1, that I CANNOT delete! If I try to remove it, the phoscon app goes not working and in the log file of homebridge this happens:** 

0|homebridge  | [3/22/2020, 3:10:22 PM] [Hue] warning: latest version: homebridge-hue v0.11.58
0|homebridge  | [3/22/2020, 3:10:22 PM] [Hue] 192.***.***.118: bridge request 1: get /config
0|homebridge  | [3/22/2020, 3:10:22 PM] [Hue] 192.***.***.118: bridge communication error ECONNREFUSED on 192.***.***.118
0|homebridge  | [3/22/2020, 3:10:37 PM] [Hue] 192.***.***.118: bridge request 2: get /config

I attach both the log, here: 

/home/pi/.pm2/logs/homebridge-out.log last 15 lines:
0|homebrid | [3/22/2020, 3:22:32 PM] [Hue] On/Off plug-in unit 2: set homekit on from 1 to 0
0|homebrid | [3/22/2020, 3:23:04 PM] [Hue] TRADFRI on/off switch  On: homekit button long press
0|homebrid | [3/22/2020, 3:23:16 PM] [Hue] TRADFRI on/off switch : set homekit battery level from 74% to 60%
0|homebrid | [3/22/2020, 3:23:17 PM] [Hue] TRADFRI on/off switch  Off: homekit button long press
0|homebrid | [3/22/2020, 3:23:40 PM] [Hue] Dimmable light 4: set homekit status fault from 0 to 1
0|homebrid | [3/22/2020, 3:31:32 PM] Got SIGINT, shutting down Homebridge...
0|homebrid | [3/22/2020, 3:31:33 PM] Loaded config.json with 1 accessories and 4 platforms.
0|homebrid | [3/22/2020, 3:31:33 PM] ---
0|homebrid | [3/22/2020, 3:31:35 PM] Loaded plugin: homebridge-camera-ffmpeg
0|homebrid | [3/22/2020, 3:31:35 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
0|homebrid | [3/22/2020, 3:31:35 PM] ---
0|homebrid | [3/22/2020, 3:31:36 PM] Loaded plugin: homebridge-hue
0|homebrid | [3/22/2020, 3:31:36 PM] Registering platform 'homebridge-hue.Hue'
0|homebrid | [3/22/2020, 3:31:36 PM] ---
0|homebrid | [3/22/2020, 3:31:36 PM] Loaded plugin: homebridge-mi-hygrothermograph

0|homebridge  | [3/22/2020, 3:31:38 PM] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
0|homebridge  | [3/22/2020, 3:31:38 PM] ---
0|homebridge  | [3/22/2020, 3:31:38 PM] Loaded plugin: homebridge-sonoff
0|homebridge  | [3/22/2020, 3:31:38 PM] Registering platform 'homebridge-sonoff.Sonoff'
0|homebridge  | [3/22/2020, 3:31:38 PM] ---
0|homebridge  | [3/22/2020, 3:31:39 PM] Loaded plugin: homebridge-weather-plus
0|homebridge  | [3/22/2020, 3:31:40 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
0|homebridge  | [3/22/2020, 3:31:40 PM] ---
0|homebridge  | [3/22/2020, 3:31:40 PM] Loading 4 platforms...
0|homebridge  | [3/22/2020, 3:31:40 PM] [WeatherPlus] Initializing WeatherPlus platform...
0|homebridge  | [3/22/2020, 3:31:40 PM] [WeatherPlus] Initializing platform accessory 'Now'...
0|homebridge  | [3/22/2020, 3:31:40 PM] [WeatherPlus] Initializing platform accessory 'Today'...
0|homebridge  | [3/22/2020, 3:31:40 PM] [Hue] Initializing Hue platform...
0|homebridge  | [3/22/2020, 3:31:40 PM] [Hue] homebridge-hue v0.11.41, node v10.16.3, homebridge v0.4.50
0|homebridge  | [3/22/2020, 3:31:40 PM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
0|homebridge  | [3/22/2020, 3:31:40 PM] [Sonoff] Initializing Sonoff platform...
0|homebridge  | [3/22/2020, 3:31:40 PM] Loading 1 accessories...
0|homebridge  | [3/22/2020, 3:31:40 PM] [Living Room] Initializing Hygrotermograph accessory...
0|homebridge  | [3/22/2020, 3:31:40 PM] [Living Room] address option is not set. When running multiple sensors this will cause interference. See README for instructions.
0|homebridge  | [3/22/2020, 3:31:40 PM] [Sonoff] Loaded accessory HiFi
0|homebridge  | [3/22/2020, 3:31:40 PM] [Sonoff] Loaded accessory Printer
0|homebridge  | [3/22/2020, 3:31:40 PM] [Sonoff] Loaded accessory BedroomLamp
0|homebridge  | [3/22/2020, 3:31:40 PM] [Sonoff] Cached accessories loaded.
0|homebridge  | [3/22/2020, 3:31:40 PM] Foscam is running on port 37919.
0|homebridge  | [3/22/2020, 3:31:40 PM] Please add [Foscam] manually in Home app. Setup Code: 031-45-154
0|homebridge  | [3/22/2020, 3:31:40 PM] [Living Room] Start scanning.
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] warning: latest version: homebridge-hue v0.11.58
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] Gateway: dresden elektronik deCONZ gateway v2.5.74, api v1.16.0
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] Gateway: warning: not using recommended deCONZ gateway version 2.5.69
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] Gateway: 6 accessories
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] masked debug info dumped to /home/pi/.homebridge/homebridge-hue.json.gz
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] Initializing platform accessory 'Gateway'...
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] Gateway: 2 services
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] Initializing platform accessory 'Unknown 1'...
0|homebridge  | [3/22/2020, 3:31:41 PM] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f1f08b1b-62f5-4319-9079-ef7e48dbdb7b
0|homebridge  |     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
0|homebridge  |     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:416:24)
0|homebridge  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
0|homebridge  |     at request.then.catch.then.then.then.catch.then (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:282:5)
0|homebridge  |     at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:65:13)
0|homebridge  |     at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
0|homebridge  |     at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)
0|homebridge  |     at Function.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/ext/promise/catch.js:29:4)
0|homebridge  |     at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
0|homebridge  |     at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)

It seems that the problem relies on the Hue plugin, right after this Unknown 1 bulb gets loaded. The result is that all my home bridge is frozen and nothing works! 
I really hope you can help me out here, many thanks!

**Comment by ebaauw** [comment]
See #662.

**Comment by SSkull995** [comment]
Hello! I read it, but why does it happen to me, that I have moved nothing?

**Comment by ebaauw** [comment]
Did you upgrade deCONZ recently?

**Comment by SSkull995** [comment]
actually not

**Comment by ebaauw** [comment]
> while I was trying to add some bulbs and a smart plug to the phoscon app

That would trigger the creation of the "Unknown 1" `/lights` resource for the coordinator.   Could also have happened earlier; Homebridge Hue will only handle new resources when Homebridge is restarted.

**Comment by SSkull995** [comment]
ok perfect so I managed to update both your plugin Hue and node+npm+homebridge. Now everything works! Thanks
