### ISSUE TITLE
Xiaomi smart plugs 

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#664]
Hi I added lumi.plug.mmeu01, on and off work but consumption and history do not work.  Do I need to do any configuration in the hue plugin.

![EE9843BD-59DC-4A37-A87A-119B0A34DD97](https://user-images.githubusercontent.com/34716572/77420874-7cf24280-6dd3-11ea-8836-99bb12479bd8.png)

**Comment by ebaauw** [comment]
As per your own remark, these aren’t yet supported by the deCONZ REST API.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2583#issuecomment-603182473.

**Comment by Kristian8606** [comment]
Hello!  I installed Deconz-dev and got support for this Smart contact, but I have some problems.
The first problem is a fault code error 1. The second problem is that the device does not record historical data.
I am taking screenshots.
![89E597F9-5C8D-4EF3-9F32-8CAD640BFD79](https://user-images.githubusercontent.com/34716572/78671310-cc626380-78e7-11ea-8c7b-9a0c07b55733.png)
![15F65482-C603-4835-9110-E1AB021020D0](https://user-images.githubusercontent.com/34716572/78671316-ce2c2700-78e7-11ea-8237-f0e9b851267b.png)
![B107C232-34BD-40F4-BB3A-1D2808DF7ADB](https://user-images.githubusercontent.com/34716572/78671320-ce2c2700-78e7-11ea-88a1-aa6c01a4a4d0.png)

**Comment by ebaauw** [comment]
Status Fault indicates that deCONZ has marked the device unreachable.  Looking at _Last Updated_ it seems that deCONZ is not proving updated values through the API.

The double entries in the history look suspicious.  I don’t know what could be causing that, unless you have multiple instances of Homebridge Hue exposing this sensor.  The Eve app doesn’t take the Home nor the HomeKit bridge into account when linking the history to the accessory.  Having a production and test home on the same iCloud account with the same accessory will confuse the hell out of Eve, possibly breaking history.  If lucky, you can remove the history from the Eve app, otherwise you might need to uninstall and re-install Eve (so its local data is deleted).

**Comment by Kristian8606** [comment]
In the Phoscon app, this accessory works flawlessly. When I turn the ignition off, the error disappears when I turn it on, the error I receive as soon as the data is updated.
What will you advise me on what I can do?

**Comment by ebaauw** [comment]
Please capture and attach a full debug log, https://github.com/ebaauw/homebridge-hue#debug-log-file.  

Please also attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by Kristian8606** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4447678/homebridge.log.gz)

**Comment by Kristian8606** [comment]
I formatted the sd card and reinstalled everything. Now the story runs and writes every 10 minutes, fault code error 1 is gone. Voltage and amps are now missing.
Unable to delete total consumption by uninstalling eve application. I noticed an error starting the homebridge.

`Phoscon-GW: error: /sensors/2: {
  config: [Object],
  ep: 21,
  etag: 'ceb85c0f2bea3679d4bea255a358816c',
  lastseen: '2020-04-07T23:41:00.690',
  manufacturername: 'LUMI',
  modelid: 'lumi.plug.mmeu01',
  name: 'Power 2',
  state: [Object],
  swversion: '09-06-2019',
  type: 'ZHAPower',
  uniqueid: '04:cf:8c:df:3c:76:3f:fb-15-000c'
}
 TypeError: Cannot read property 'outlet' of undefined
    at HueSensor.checkValue (/usr/lib/node_modules/homebridge-hue/lib/HueSensor.js:1821:69)
    at new HueSensor (/usr/lib/node_modules/homebridge-hue/lib/HueSensor.js:1507:12)
    at HueAccessory.exposeSensorResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:319:20)
    at HueAccessory.exposeSensorResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:309:12)
    at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:126:8)
    at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:534:49)
    at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:94:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:310:29)[39m[22m
`

**Comment by ebaauw** [comment]
Looks like the error only occurred shortly after (re-)starting deCONZ?  They re-re-re-introduced the issue that `/lights` resources are not available until a minute or longer after startup, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2473.

Homebridge Hue doesn't expect to find a ZHAPower sensor without corresponding `/lights` resource.  That's a bug alright, which I'll fix.

But in your case this bug is actually a blessing in disguise: if Homebridge would have started the accessories and services for your `/lights` resources would not be exposed to HomeKit.  You probably want to run `ph lightlist` to create a `lightlist` resourcelink, whcih will make sure Homebridge Hue delays startup, until deCONZ has exposed all `/lights` resources.

**Comment by Kristian8606** [comment]
i followed your guide to get HomeKit to expose the accessory as a socket rather than a light bulb, and this slows down the startup and error is gone. 
The question remains what should be done to expose the amper and volts in the eve application.  along with amper and volts, the option to enter a price per kilowatt has also disappeared.

**Comment by ebaauw** [comment]
> i followed your guide to get HomeKit to expose the accessory as a socket rather than a light bulb, and this slows down the startup and error is gone.

Yes, that would have the same effect as a `lightlist` for the resources in the `outlet` link.

> The question remains what should be done to expose the amper and volts in the eve application. 

From the log file it would seem that deCONZ doesn't expose these.  I need to see the dump file to be sure.

**Comment by Kristian8606** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4452936/homebridge-hue.json.gz)

**Comment by Kristian8606** [comment]
i noticed this ... i added lights / 5 but lights / 1 i didn't add it in the link or it was inadvertently. Is it okay to i remove lights / 1?
> "classid": 1,
				"description": "outlet",
				"links": ["/lights/1", "/lights/5"],

**Comment by ebaauw** [comment]
> which tells me that the accessory measures voltages and amper.

The dump file tells me that deCONZ isn't exposing these over the API.  Maybe you need to compile the plugin with that code, and re-pair the sensor.  Just open the network and read the _Basic_ cluster attributes.  Or maybe these attributes only get created after the first Xiaomi special report is received?  Or maybe they forgot to support the sensor in `database.cpp` ("there's always one more place to whitelist a device...").
```
        {
          "config": {
            "on": true,
            "reachable": true,
            "temperature": 2400
          },
          "ep": 21,
          "etag": "f164febdde961decffc530a6105b6873",
          "lastseen": "2020-04-08T19:31:23.554",
          "manufacturername": "LUMI",
          "modelid": "lumi.plug.mmeu01",
          "name": "Power 2",
          "state": {
            "lastupdated": "2020-04-08T19:20:37.435",
            "power": 4
          },
          "swversion": "09-06-2019",
          "type": "ZHAPower",
          "uniqueid": "04:cf:8c:df:3c:76:3f:fb-15-000c"
        }
```

**Comment by Kristian8606** [comment]
I'm not that advanced but rather a user. I can only follow the instructions and not to confuse something, I will also turn to SwoopX to confirm what measurements its accessory has.

**Comment by Kristian8606** [comment]
SwoopX responded to the problem, made the necessary adjustments, and now the outlet shows all measurements.
I will continue to watch it as there was another glitch that I didn't mention because the outlet still didn't have full support.
Within hours of plugging in, he did not respond to commands given by the applications home and eve (on / off) but switched on and off in Phoscon.
I hope this bug is gone after these adjustments.
I will follow and report.
Thank you, I will be glad to watch these projects expand and get better.

**Comment by Kristian8606** [comment]
Аfter removing and re-adding the device the accessory reports fault code 1 reappeared today.

**Comment by ebaauw** [comment]
Did you restart Homebridge after you re-paired the device to deCONZ?

**Comment by Kristian8606** [comment]
I restarted deconz and homebridge.

**Comment by ebaauw** [comment]
I'm going to have to ask you for the log files once again.

**Comment by Kristian8606** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4491592/homebridge-hue.json.gz)
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4491594/homebridge.log.gz)

**Comment by Kristian8606** [comment]
Everything seems fine, but it really isn't
![2A2BB62F-0E81-4B20-947B-1748ACB114ED](https://user-images.githubusercontent.com/34716572/79544625-fcec8f00-8097-11ea-9c63-d5d8c1caffab.jpeg)

**Comment by ebaauw** [comment]
> Everything seems fine, but it really isn't

Indeed:
```
[4/17/2020, 10:21:24 AM] [homebridge-hue] Phoscon-GW: 04CF8CDF3C763FFB: LUMI lumi.plug.mmeu01 "Smart plug 5"
[4/17/2020, 10:21:24 AM] [homebridge-hue] Phoscon-GW: /lights/5: Smart plug "Smart plug 5"
[4/17/2020, 10:21:24 AM] [homebridge-hue] Phoscon-GW: /lights/5: config: {"on":true,"bri":false,"ct":false,"xy":false,"colorloop":false,"wallSwitch":false,"outlet":true,"resetTimeout":500,"waitTimeUpdate":20,"windowCovering":false,"unknown":true}
[4/17/2020, 10:21:24 AM] [homebridge-hue] Phoscon-GW: /sensors/3: ZHAConsumption "Consumption 3"
[4/17/2020, 10:21:24 AM] [homebridge-hue] Phoscon-GW: /sensors/2: ZHAPower "Power 2"
[4/17/2020, 10:21:24 AM] [homebridge-hue] Phoscon-GW: /sensors/19: ZHAConsumption "Consumption 19"
[4/17/2020, 10:21:24 AM] [homebridge-hue] Phoscon-GW: /sensors/21: ZHAPower "Power 21"
```
deCONZ exposes the `/sensors` resources for this twice?!  `/sensors/19` and `/sensors/21` report `"reachable": false`, causing the _Status Fault_.

```
$ json -al homebridge-hue.json | grep 04:cf:8c:df:3c:76:3f:fb
/bridges/0/lights/5/uniqueid:"04:cf:8c:df:3c:76:3f:fb-01"
/bridges/0/sensors/2/uniqueid:"04:cf:8c:df:3c:76:3f:fb-15-000c"
/bridges/0/sensors/3/uniqueid:"04:cf:8c:df:3c:76:3f:fb-16-000c"
/bridges/0/sensors/19/uniqueid:"04:cf:8c:df:3c:76:3f:fb-01-0702"
/bridges/0/sensors/21/uniqueid:"04:cf:8c:df:3c:76:3f:fb-01-0b04"
```
I don't know where `/sensors/19` and `/sensors/21` came from (a previous test version of the REST API plugin, or from the most recent pairing), but they're clearly wrong.  As per https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2583#issuecomment-603182473, the plugin doesn't have these clusters on endpoint 0x01.  Better talk to @SwoopX.

**Comment by ebaauw** [comment]
In v0.11.63.
