### ISSUE TITLE
How to expose SONOFF Basic ZBR3 as HomeKit Fan

### ISSUE THREAD

**Issue by ychieux** [ebaauw/homebridge-hue#665]
I recently added few SONOFF Basic ZBR3 to my deconz setup. I have two units for extractor fans that I'd like to expose to homekit as fan rather than light to avoid having Siri turning on and off fans when asked to control actual lights.

Would you mind pointing to the set of ph commands to achieve this change of HomeKit accessory type?

**Comment by ebaauw** [comment]
You need homebridge-hue to expose them as _Outlet_ and then set the type to _Fan_ in HomeKit.  To expose them as _Outlet_, create an `outlet` resourcelink with the `/lights` resources for the Sonoffs, see https://github.com/ebaauw/homebridge-hue#configuration.
