### ISSUE TITLE
Homebridge to Hue Bridge connectivity

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#666]
Hi,

I only have a small question about the connectivity between the Homebridge-Hue plugin running on Homebridge and the physical Philips Hue Bridge himself:

I have to configure the Hue Bridge IP in the config of the plugin.

In general: is the Bonjour discovery needed between the two components (Homebridge and Hue Bridge) or is this IP setting the only thing which is needed to communicate correctly with the physical Hue Bridge?

I am asking because I want to put my Homebridge into a different network but I cannot enable a mDNS repeater/reflector between the networks because the physical Hue Bridge is crashing every 5-15mins if I do that.

The Hue Bridge is not designed to work properly over VLANs.

Thanks JO!

**Comment by ebaauw** [comment]
Hue bridge discovery uses UPnP and the meethue portal.  When specified in config.json, discovery is skipped. Afaik the Hue API is perfectly routable, so there’s no need to have Homebridge Hue and the Hue bridge in the same subnet.

Note that if you use the native HomeKit function of the gen-2 (square) Hue bridge, it needs to be in the same subnet as your iDevices, since they use Bonjour to find the HAP server on the bridge.

**Comment by jostrasser** [comment]
Right now I am only using the Huebridge-Hue plugin via the Homebridge and not the native HomeKit integration of the physical bridge.

My plan is to place my virtual Homebridge into the same subnet where my Apple TVs and iOS devices are located and I want to move only my physical Hue Bridge to a different VLAN.

The Hue Bridge is only crashing if it receive mDNS broadcasts from different subnets.
I have done many tests and this is the only possible solution for me I think.

Any thoughts about it?

BR/JO!

**Comment by ebaauw** [comment]
> My plan is to place my virtual Homebridge into the same subnet where my Apple TVs and iOS devices are located and I want to move only my physical Hue Bridge to a different VLAN.

That should work.

> The Hue Bridge is only crashing if it receive mDNS broadcasts from different subnets.

Interesting.  I only have one subnet and never experienced this myself, but I think I might have seen a similar report on the Hue developer forum.

**Comment by jostrasser** [comment]
Here an example:


https://community.ui.com/questions/Weird-mDNS-issue/e4fe9528-cf5d-49f7-90d9-8c5b7c0dae9b#answer/bd9dca36-133e-4fc6-af0e-89888f836763

BR/JO
