### ISSUE TITLE
IKEA Fyrtur roller blind position

### ISSUE THREAD

**Issue by r2ixuz** [ebaauw/homebridge-hue#667]
I am using mainly Homekit to close my Fyrtur roller blinds to 100% and open it 100%. Over time of cycles going by I can observe that on every cycle the Fyrtur roller blind is a little bit more (maybe 1cm) unrolled. So after a certain amount of cycles the roller blinds gets rolled in the opposite direction.

Is this a Deconz Issue or a homebridge-hue problem?

I can reset this "faulty state/behaviour" by manually pressing the physically "up" button on the roller blind which seems to rolling it up to the end position (mechanical resistance).

**Comment by ebaauw** [comment]
My best guess: neither.  It would seem to be a Fyrtur problem.  You might want to double-check the Homebridge debug log (when running `homebridge -D`) to see that Homebridge Hue continues to send the same command on close.  And sniff the ZigBee traffic that deCONZ continues to send the same command to the Fyrtur (I don't think it shows in the deCONZ log).

Did you set the maximum closed limit on the Fyrtur?  I think if you don't the blind will continue to move after closing all the way, opening the wrong way round (after which the open and close directions appear to be reversed).

**Comment by r2ixuz** [comment]
FTR: After two years of using the blinds I installed the IKEA Fyrtur firmware update for the first time via deconz. Jump was from 2.2.xxx to 2.3.088. Now the problem is gone. :-)
