### ISSUE TITLE
TRÅDFRI bulb E27 WS opal 980lm error !

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#668]
`[4/12/2020, 9:50:16 PM] [homebridge-hue] Phoscon-GW: gateway request 529: put /lights/3/state {"bri":254}
[4/12/2020, 9:50:16 PM] [homebridge-hue] Phoscon-GW: gateway communication error: Internal error, 951`

What causes this error?
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4467074/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4467075/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
It's a "bridge busy" error returned by deCONZ.  Typically it returns this, when it cannot queue the Zigbee message for sending to the RaspBee/ConBee.  Either the device hasn't joined the network (check in the deCONZ GUI) or there is too much radio interference (check in the deCONZ log).

**Comment by Kristian8606** [comment]
I figured there might be a problem because the circle in the home app color temperature instrument always returns to the same position.
