### ISSUE TITLE
Had to remove homebridge-hue after lastest update

### ISSUE THREAD

**Issue by robboz4** [ebaauw/homebridge-hue#672]
#### Issue
Had a message to update today and it didn't work. Had to remove hue from the config.json file to get homebridge to run again.
Current versions:

homebridge-hue v0.11.62, 
node v12.16.2, 
npm 6.14.4
homebridge v0.4.53
homebridge-config-ui-x v4.16.0
homebridge-platform-wemo v1.5.5
homebridge-apple-tv-remote v0.7.6
homebridge-http-garagedoorcontroller v2.0.1

This is an V1 Hue. Has worked with homebridge without any hiccups for years.

#### Log Messages

```
ERROR LOADING PLUGIN homebridge-hue:
Apr 21 16:36:58 Homebridge homebridge[10773]: [4/21/2020, 4:36:58 PM] Error: Plugin /usr/local/lib/node_modules/homebridge-hue requires a HomeBridge version of ~0.4.53 which does not satisfy the current HomeBridge version of 0.4.52. You may need to upgrade your installation of HomeBridge.

```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4513066/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
> Had a message to update today

By whom?  I only issue messages that a new version is available.  Please check the release notes before deciding whether to upgrade.
> Log Messages

I think the message is pretty self-explanatory: as mentioned in the [release notes](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.62), v0.11.62 requires homebridge v0.4.53; you're running v0.4.52.

Best delay upgrading Homebridge Hue until you're ready to upgrade Homebridge.

**Comment by robboz4** [comment]
According to my post I am running the latest version. That’s what I don’t understand and that’s why I filed an issue. The update was to Homebridge.

**Comment by ebaauw** [comment]
The message is issued by Homebridge itself, not by Homebridge Hue.  Do you have multiple installations of Homebridge on your system?

**Comment by robboz4** [comment]
Hi!
It looks I might have but no idea how. The system has been in use for over a year with out any major issues. I update regularly. Here’s the output of where is, ps and the journal for Homebridge:
root     10773     1  0 Apr21 ?        00:05:15 homebridge
root     10804 10773  0 Apr21 ?        00:01:07 homebridge-config-ui-x
pi       15754 15635  0 11:48 pts/0    00:00:00 grep --color=auto homebridge
pi@Homebridge:~

homebridge: /usr/bin/homebridge /usr/local/bin/homebridge
pi@Homebridge:~ $ 

Apr 22 11:52:15 Homebridge homebridge[10773]: [4/22/2020, 11:52:15 AM] [Config] /usr/local/lib/node_modules/homebridge
Apr 22 11:52:15 Homebridge homebridge[10773]: [4/22/2020, 11:52:15 AM] [Config] /usr/lib/node_modules/homebridge
pi@Homebridge:~ $ 

It’s seems I have two installed, but only one running.
Can you point me in the direction to fix this? 
Is this the issue for the hue plugin? 
It’s accessing an older version? 
Why was it working with all the previous update?

Thanks

**Comment by robboz4** [comment]
I traced the symbolic links and have two homebridge files exactly the same:

pi@Homebridge:/usr/lib/node_modules/homebridge/bin $ ls -l
total 4
-rwxr-xr-x 1 root root 342 Oct 26  1985 homebridge

pi@Homebridge:/usr/local/lib/node_modules/homebridge/bin $ ls -l
total 4
-rwxr-xr-x 1 root staff 342 Oct 26  1985 homebridge

All other Homebridge seems to be in /var/Homebridge

From this command:
lrwxrwxrwx 1 root staff 45 Mar 20 17:28 /usr/local/bin/homebridge -> ../lib/node_modules/homebridge/bin/homebridge
pi@Homebridge:/var/homebridge $

It looks like /usr/local is the one to use. Should I get rid of /usr/lib version?

**Comment by ebaauw** [comment]
You probably have two versions of node and npm as well.  Depending on which npm you run, packages get installed to /usr/lib/node_modules or /usr/local/lib/node_modules.  You most likely used different users to upgrade homebridge vs homebridge-hue.  Or one with, the other without sudo.

Other than taking up disk space and confusing the hell out of you, this doesn’t cause any harm.  I would definitely cleanup this mess, though, if only to avoid future confusion.  I’m sorry, but I cannot help you with this.

Homebridge loads the plugins.  Plugins don’t choose the homebridge version; you do, when starting homebridge.

**Comment by robboz4** [comment]
I traced the symbolic links and have two homebridge files exactly the same:

pi@Homebridge:/usr/lib/node_modules/homebridge/bin $ ls -l
total 4
-rwxr-xr-x 1 root root 342 Oct 26  1985 homebridge

pi@Homebridge:/usr/local/lib/node_modules/homebridge/bin $ ls -l
total 4
-rwxr-xr-x 1 root staff 342 Oct 26  1985 homebridge

All other Homebridge seems to be in /var/Homebridge

**Comment by robboz4** [comment]
OK thanks.
Homebridge —version indicates the old version, but Homebridge UI says it’s the new version that is running.
So I assume the plugin looks at the static files and not the currently running one. 

I’ll close this. Thanks once again for the help.
