### ISSUE TITLE
ENOENT no such file or directory

### ISSUE THREAD

**Issue by FSorrow** [ebaauw/homebridge-hue#673]
hi, after a long battle i'm finally running hoobs e deconz on the same pi without issue.
While i'm restarting the pi in the hoobs log appear this error:

[Homebridge] [4/22/2020, 13:28:02] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.72, api v1.16.0
[Homebridge] [4/22/2020, 13:28:02] [Hue] Phoscon-GW: 3 accessories
[Homebridge] [4/22/2020, 13:28:02] [Hue] error: /home/hoobs/.hoobs/etc/@hoobs/hue.json.gz: /home/hoobs/.hoobs/etc/@hoobs/hue.json.gz: cannot open: ENOENT no such file or directory
[Homebridge] [4/22/2020, 13:28:02] [Hue] Initializing platform accessory "Phoscon-GW"...
[Homebridge] [4/22/2020, 13:28:02] [Hue] Phoscon-GW: 2 services
[Homebridge] [4/22/2020, 13:28:02] [Hue] Initializing platform accessory "Window / Door Sensor"...
[Homebridge] [4/22/2020, 13:28:02] [Hue] Initializing platform accessory "Esterno"...
[Homebridge] [4/22/2020, 13:28:02] Homebridge is running on port 51826.
[Homebridge] [4/22/2020, 13:40:02] [Hue] Esterno: set homekit temperature from 16.9°C to 17.2°C
[Homebridge] [4/22/2020, 13:40:02] [Hue] Esterno: set homekit humidity from 42% to 41%

Is something that i have to fix ? in which way ? Everything at the moment is running without issues.
thank you

**Comment by ebaauw** [comment]
Please contact hoobs support for issues running hoobs.
