### ISSUE TITLE
cannot connect: ETIMEDOUT - retrying in 15s

### ISSUE THREAD

**Issue by zeromancer1972** [ebaauw/homebridge-hue#674]
I see this when I startup Homebridge with the latest version of Hue plugin and Homebridge 0.4.53:
[2020-4-23 9:29:00] [Hue] 192.***.***.230: 192.168.1.230:80: cannot connect: ETIMEDOUT - retrying in 15s
What is the plugin trying to connect to? This is not even an IP in my network, not even close to my IP range. This prevents Homebridge from starting, and of course, Hue stuff doesn't work at all.
Any hints?

**Comment by ebaauw** [comment]
Your Internet provider is sharing "your" public IP address with others, and the Hue bridge discovery returns the bridge of one of your Internet neighbours.  Set `nupnp` to false to disable discovery through the MeetHue portal (and dresden elektronik appspot server), or specify your bridge(s)/gateway(s) under `hosts` to disable discovery altogether.

**Comment by zeromancer1972** [comment]
Hm not happy with that solution, disabling discovery and using a static host works now but how can I make sure the bridge always uses this static ip? I didn't find any setting in the Meethue account.

**Comment by ebaauw** [comment]
> Hm not happy with that solution

You’d need to take that up with Signify and/or your ISP.

> how can I make sure the bridge always uses this static ip

Whitelist the bridge’s mac address in your dhcp server, linking it to a static, but dynamically assigned IP address.  Or configure a static IP address on the Hue bridge using the Hue app.

If you set `nupnp` to false, local discovery through UPnP still works.  Homebridge Hue and the Hue bridge need to be in the same subset, or you need some networking magic to reflect the UPnP local link multicasts to the other subnet.

**Comment by zeromancer1972** [comment]
Ah thank you, didn't know that I can assign a static address to the bridge.

**Comment by RaspberryPee** [comment]
Hi ebaauw,

first o all i would like to give you a big thank you as well as a big respect for building this beautiful Hue plugin.

I have the same issue like zeromancer1972 had. 
But i dont understand a word about how he solved the problem.

The point is, everytime i shutdown my PRI where Homebridge is running on (PRI Zero W), Homebridge server doesnt start.

At the protocoll this message repeats all the time ater start:

**[12/12/2020, 13:46:06] [Hue] request 1: GET /config
[12/12/2020, 13:46:06] [Hue] 192.168.178.39: timeout after 5 seconds
[12/12/2020, 13:46:06] [Hue] 192.***.***.39: 192.168.178.39: timeout after 5 seconds - retrying in 15s**

My config looks like this so ar:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "hosts": [
                "192.168.178.39"
            ],
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "users": {
                "ECB****i covered***": "UBAZ5hJV***i covered***9rzDPlSFyOEArr"
            },
            "platform": "Hue"
        }
    ],
    "accessories": []
}


**What im doing wrong?**
My Hue Bridge does have another IP in my network. But it changes automaticly to another IP. But thats what it should do, right?

Sorry, im rlly just a beginner in this PRI and Homebridge topic.

Mayn thanks in advanced.

**Comment by ebaauw** [comment]
> My Hue Bridge does have another IP in my network. But it changes automaticly to another IP. But thats what it should do, right?

If you use `hosts`, your Hue bridge needs to have a fixed IP address.  Either configure a static address on the bridge (using the Hue app), or configure your DHCP server (typically your router) to assign a fixed address to the Hue bridge, based on its mac address.

Alternatively, don't use `hosts` and let Homebridge Hue discover your bridge automatically.

**Comment by RaspberryPee** [comment]
thank you for your quick supply!
It worked now. I just deleted the host. 

### Looking like this now:
{
            "name": "Hue",
            "anyOn": true,
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "users": {
                "ECBXXXXXXXX2F4": "UBAZXXXXXXXXXXXXXXXXXyOEArr"
            },
            "platform": "Hue"
        }

Thanks again. Rlly happy with your plugin. 👍
