### ISSUE TITLE
Inconsistent behaviour of devices

### ISSUE THREAD

**Issue by rickdhoy** [ebaauw/homebridge-hue#675]
#### Issue

Firstly let me thank you for creating this plugin and supporting it. Secondly, thank you in advance for any help you might be able to proffer so I can get the house working consistently.

So on to the issues, I have been running the home bridge-hue for a while and I am suffering from quite a few inconsistencies which I am hoping you may be able to help with.

These issues involve devices that work inconsistently within apple HomeKit and become unresponsive or stuck in an "updating" loop.

If I restart the Homebridge server sometimes they come back up. On other occasions i need to actually physically power cycle a device to reset.

I am also experiencing a lot of issues with response times from Hue sensors to turn on different lights/switches. I am getting 1 to 3 second delays ( sometimes longer )  i.e. I will walk into our stairwell and be half way up or down it before the lights activate. I am in full exposure to the sensor.

I was wondering if the issues for the sensors are how I brought them into he system ? Should they be added through the HIUE app or through Homekit ? Which application should be managing them ? i.e. Automation through Homekit or Hue.

Also, I I make any changes of updates in the HIUE app it seems to remove devices from the individual rooms and put them all into the default room.

The Hue app consistently says it is not synced with HomeKit and if I update it it moves all the devices. 

I am hoping through your experience you might be able to assist me. :-)

I thought I might also assist you if I supply an outline of my system.

**System details and structure**

- 1/. Home bridge is being run on a Apple Mac Mini 2011 2.3 GHz Intel Core i5 with 16GB of RAM running macOS High Sierra 10.13.6

I use this mac as the DHCP server and as I found it better than my router.  It is also our media server and home file server. Not a great deal of pressure on it. When not serving media it sits at about 10% of its CPU and approx 7 Gb of available Memory.

2/. I am running home bridge-hue v0.11.62

3/. Node v12.16.2

4/. Homebridge v0.4.53

5/. I have a mesh network using Linksys Velop and 3 nodes spread over the houses two floors. I seem to have good connectivity throughout the house.

6/. I also have a CAT6 network that delivers connectivity to most of the VELOP wireless points, only one VELOP is using wireless to connect to the network with no physical connectivity.

7/. I have a D-link DSL-4320L Modem Router

8/. As to devices I have a mixture outlined below.

 a. Sonoff wifi Smart Switches running the Ravencore Firmware
 b. Zigbee Smart Switches from a  company called www.3asmarthome.com
 c. Ecobee thermostats
 d. 2 x Apple HomePods
 e. 3 AppleTVs
 f. 1 x Automate Pulse2 blind controller
 g. 1 x Hue hub
 h. 1 x logi Hub and a few wireless switches 
 i. Hue Sensors x 12
 j. A number of Hue lights and LED light strips

9/. I have an Australian NBN service which consistently runs at about 85 x 25Mbps with a 11 to 15 millisecond Ping

10/. I am running the HUE hub and the homebridge-hue at the same time which seems to show two sets of some of the devices in Apple Homekit.

#### Log Messages

```
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4526519/homebridge-hue.json.gz)

I can't seem to find the log, I tried doing what was outlined in the link but still can't locate it ? Sorry I am certainly only learning all this as I go along. ( I have also done some googling trying to find a solution )

**Comment by rickdhoy** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4526830/homebridge-hue.json.gz)

Updated file, just found that this might contain the debug info

**Comment by ebaauw** [comment]
Devices becoming unresponsive is almost always related to the network between the accessory (the Hue hub or homebridge) and the HomeKit runtime on your iDevice.  HomeKit uses Bonjour (multicast DNS) to discover the accessories.  Best make sure all your access points connect to the same (wired) port on your router, and turn off the wireless network on your router.

From a response time and stability perspective, Hue bridge rules are preferable over HomeKit rules.  Note that the Hue bridge doesn't provide push notifications over the API, so Homebridge Hue needs to poll the bridge to detect changes.  If you use the Motion sensors exposed by Homebridge Hue, better set `heartrate` to 2 in config.json.

If you use the motions sensors as exposed by the Hue bridge, you'll get better response times (the bridge does push changes to HomeKit), but poorer functionality (no history in Eve).

The Hue app likes to sync the room assignments for HomeKit accessories with the room assignments on the Hue bridge.  This should also work for the non-Hue lights exposed by Homebridge Hue.  I'm not too sure about sensors, though.

**Comment by rickdhoy** [comment]
Hi Erik,

Thank you for this, I am trying a few things and I'll let you know how I get on.

Appreciate your thoughts.

Keep safe and well in your home country.


Rick Hoy

7 St Martins Terrace
Buderim, 4556
Queensland, Australia

M-Aus: +61 448 000 242
M-Can: +1 250 262 5651
Rick@kiwari.com.au
