### ISSUE TITLE
Update to v0.11.63 also on homebridge version 0.4.53 possible?

### ISSUE THREAD

**Issue by Phoenix-DH** [ebaauw/homebridge-hue#678]
Hi,

can I also update to the latest version v0.11.63 without having an update to homebridge v1.0.0?

Thank you.

**Comment by ebaauw** [comment]
No, v0.11.63 uses new features provided by Homebridge v1.0.0.

**Comment by Phoenix-DH** [comment]
Okay, thanks, so I will first have to try homebridge v1.0.0

Thanks.
