### ISSUE TITLE
Homebridge doesn't start after update to 1.0

### ISSUE THREAD

**Issue by hboltz** [ebaauw/homebridge-hue#679]
I updated my Homebridge to the latest version 1.0 and all installed plugins also. Now the Homebridge doesn't start anymore as a service. The relevant messages I can see are these:

Apr 27 13:33:57 Homebridge homebridge[9889]: [2020-4-27 13:33:57] ERROR LOADING PLUGIN homebridge-hue:
Apr 27 13:33:58 Homebridge homebridge[9889]: [2020-4-27 13:33:58] Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ~0.4.53 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.
...
Apr 27 13:33:58 Homebridge homebridge[9889]: [2020-4-27 13:33:58] Error: The requested platform 'Hue' was not registered by any plugin.
Apr 27 13:33:58 Homebridge homebridge[9889]:     at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at /usr/lib/node_modules/homebridge/src/server.ts:361:37
Apr 27 13:33:58 Homebridge homebridge[9889]:     at Array.forEach (<anonymous>)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:348:27)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:151:29)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at cli (/usr/lib/node_modules/homebridge/src/cli.ts:74:10)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 27 13:33:58 Homebridge homebridge[9889]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 27 13:33:58 Homebridge homebridge[9889]: [2020-4-27 13:33:58] Got SIGTERM, shutting down Homebridge...

any idea whatI can do?

thanks a lot!!

**Comment by ebaauw** [comment]
See #676.
