### ISSUE TITLE
Motion sensor add a bunch of sensors to home kit

### ISSUE THREAD

**Issue by MP0w** [ebaauw/homebridge-hue#68]
I tried to understand the README but failed to understand.
I have a motion sensor and I now see in homekit other stuff like temperature and daylight 🆒 !
However there are 3 sensors not compatible:
1. MotionSensor 7.Companion ("Not compatible")
2. Philips Hue ("Not compatible")
3. Waking-up-huelabs-(random_chars) ("Not compatible")

And a "Go to sleep" switch that I can't understand what's for (except it's kind of dimming the light up and down and doesn't look like I can stop it or make it work reliably with its state).

Could you explain me what are these sensor for and where do they come from?

Also in the REAMDE you mention complex rules for the Hue bridge, where can I create these rules (e.g. when motion detected between some hours do this, etc?) Do I have to use the Hue App?

**Comment by ebaauw** [comment]
> I have a motion sensor and I now see in homekit other stuff like temperature and daylight 🆒 !

Yes, the motion sensor includes a light sensor and a temperature sensor.

> MotionSensor 7.Companion ("Not compatible")

This is a `CLIPGenericStatus` sensor that the Hue app creates on the Hue bridge when configuring the motion sensor.  It is used in conjunction with the rules to dim the lights 30 seconds before turning them off, when there's been no motion.

> Philips Hue ("Not compatible")

That's the accessory for the bridge itself.  The iOS built-in Home app doesn't want to know it, but from other HomeKit apps (like Elgato's Eve), you can change the polling interval (heartrate) through that.

> Waking-up-huelabs-(random_chars) ("Not compatible")

That's another `CLIPGenericStatus` sensor, probably created by Hue labs or the Hue app for a wakeup routine.

> And a "Go to sleep" switch

That's a `CLIPGenericFlag` sensor, probably also created by Hue labs or the Hue app.

If you start homebridge through `homebridge -D`, homebridge-hue issues a debug message for each sensor, including its bridge resource and type.   You can prevent the CLIP sensors from being exposed to HomeKit by specifying `"excludeSensorTypes": ["CLIP"]` in `config.json`.

The official Hue app from Philips creates standard rules on the Hue bridge to deal with motion sensors, dimmer switches, and taps.  These are limited in functionality.  Other Hue apps create more sophisticated rules.  You can also create them yourself using the [Hue API](https://developers.meethue.com/documentation/getting-started).

**Comment by MP0w** [comment]
Thank you very much will play around and eventually try to contribute to the documentation . Have a nice day!

**Comment by ebaauw** [comment]
I would really appreciate the help on the documentation.  The README is too large and too intimidating to read.  I'm setting up some documentation in the Wiki and would trim down the README to the minimum, with links to the Wiki.

In think the Wiki should have multiple sections:
- Walkthrough understanding and setting up homebridge-hue (basically stuff currently README, but more accessible in separate pages);
- Reference section (like the stuff currently there);
- FAQ (based on questions from issues).
