### ISSUE TITLE
How to downgrade Homebridge-hue?

### ISSUE THREAD

**Issue by zany92** [ebaauw/homebridge-hue#681]
Hello,

Upgrading to HomeBridge 1.0.0 was a total mess for me so I had to downgrade to 0.4.53 using sudo npm install -g --unsafe-perm homebridge@0.4.53. However, I can't find out how to downgrade Homebridge-hue plugin.

Could you please help?
Thank you 🙏

**Comment by ebaauw** [comment]
Same way you downgrade any `npm` package: `sudo npm -g i homebridge-hue@0.11.62`.

**Comment by zany92** [comment]
thank you
