### ISSUE TITLE
rgbw bulb

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#682]
Hi, I read a lot about colored bulbs but I didn't understand why some bulbs don't work well with the homekit color wheel and the color temperature tool.  homekit requires the features brightness, hue, and saturation.  I used this example to build my own color band https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/magic_home_strip/magic_home.c  and it works fine, but I don't understand why my the bulb I have works well with deconz but not homebridge-hue?

my bulb is like this https://www.amazon.de/Lang-AC100-240-Leuchtmittel-Schlafzimmer-Dekoration/dp/B0785K6QSZ

Feibit Inc co., Modelid: FB56- ZCW08KU1.1

**Comment by ebaauw** [comment]
Sorry I don't understand your setup.  Is this a Zigbee bulb paired with deCONZ and exposed to HomeKit using Homebridge Hue?

**Comment by Kristian8606** [comment]
Excuse me.  Yes this is my bulb that works well with deconz and is displayed on HomeKit via Homebridge hue.  But in homekit there is a problem with the color wheel and the color temperature adjustment tool.  The problem is difficult to describe.  It might be easier if I make a short video.

**Comment by Kristian8606** [comment]
Through the link above, I gave an example of an esp8266 based LED strip that works well with the homekit-Demo example.  it gets brightenss, hue, and saturation and works very well unlike my zigbee bulb

**Comment by ebaauw** [comment]
> But in homekit there is a problem with the color wheel and the color temperature adjustment tool. The problem is difficult to describe.

Is it the problem described in https://github.com/ebaauw/homebridge-hue/issues/571?  Is this an _Enhanced Color Light_, also supporting `ct`?  Did you try and set `forceCt` to false in config.json?

**Comment by Kristian8606** [comment]
According to the manufacturer  rgbw. Is not supported ct, forceCt improved the color wheel.  In fact, when should forceCt be used?

**Comment by ebaauw** [comment]
> According to the manufacturer rgbw. Is not supported ct, forceCt improved the color wheel.

If `forceCt` helps, deCONZ does expose `ct`, or Homebridge Hue never would have exposed _Color Temperature_.  I would need to see screenshots of the deCONZ GUI, in particular of the _Color Control_ cluster with all attributes read, to see if deCONZ is in error, or if the light actually supports setting color temperature from Zigbee (which, of course, is achieved by mixing the RGBW channels).

>  In fact, when should forceCt be used?

Apple's Home app doesn't deal well with _Lightbulb_ services that contain both _Hue_/_Saturation_ and _Color Temperature_.  Normally it fakes _Color Temperature_ by translating it to _Hue_/_Saturation_.  That's fine for 3-channel RGB (and 4-channel RGBW) lights, that mix RGB to obtain the colour temperature.  But not for five-channel RGB+CCT lights, that actually drive the cool white/warm white channels on setting the colour temperature (and, of course, the RGB channels when setting colour).  Homebridge Hue exposes _Color Temperature_, so you can set `ct` from HomeKit.  If you mostly use scenes or automations to control your lights, or other HomeKit apps, this works out fine.  If you manually set the colour in Apple's Home app, not so much.  Setting `forceCt` to false prevents Homebridge Hue from exposing _Color Temperature_ for enhanced color lights.

> When I set pink and brightness below 20%, the color changes to red and over 20% turns pink.

Do you see the same when controlling the light from Phoscon or another deCONZ API client?  I think it's the bulb's firmware.  I'd guess the bulb uses the R, B and W channels to mix pink.  Below a certain brightness, the B and W channels turn off and only R is used.  This almost makes me want to cut off the diffuser and check what the individual LEDs are doing.

Note that different manufacturers use different RGB LEDs, so the same colour might look different on different bulb models.

**Comment by Kristian8606** [comment]
> Do you see the same when controlling the light from Phoscon or another deCONZ API client?

Yes! Now I understand that pink is a  bulb problem.

![Screenshot 2020-04-29 at 0 09 08](https://user-images.githubusercontent.com/34716572/80538646-c293c380-89ae-11ea-8866-0455bf3833d2.png)
![Screenshot 2020-04-29 at 0 10 45](https://user-images.githubusercontent.com/34716572/80538668-cc1d2b80-89ae-11ea-9227-a088953ca18e.png)
![Screenshot 2020-04-29 at 0 11 10](https://user-images.githubusercontent.com/34716572/80538688-d3dcd000-89ae-11ea-91b7-d80ddd4e1659.png)
![Screenshot 2020-04-29 at 0 12 01](https://user-images.githubusercontent.com/34716572/80538699-d7705700-89ae-11ea-8ef7-f9af0bf5094a.png)

**Comment by ebaauw** [comment]
Color capabilities 0x000f indeed means no color temperature support.  It does expose the _Color Temperature_ attribute (0x0007) though, maybe that confuses deCONZ?

**Comment by Kristian8606** [comment]
This explains the presence of a color temperature slider in the deconz.  How can I resolve this issue, should I request a support request?

**Comment by ebaauw** [comment]
Best open an issue in the deCONZ REST API plugin repository, referencing this issue.  I’ll see if I can take a look in their code this weekend.

**Comment by ebaauw** [comment]
Confirmed to be an issue with deCONZ.
