### ISSUE TITLE
Homebrige-hue not responding anymore

### ISSUE THREAD

**Issue by zany92** [ebaauw/homebridge-hue#683]
Yesterday, I upgraded to homebridge@1.0.0 / homebridge-hue@0.11.64 and instantly most of my plugins stopped responding including homebridge-hue. 

Upgrading to 1.0.1 then 1.0.2 did not fixed the problem so I tried downgrading to homebridge@0.4.53 and homebridge-hue@0.11.62. All plugins started to work fine again except homebridge-hue devices which are still in 'no response' state and their Home configuration were lost (back to default room, etc), so were related automations (UUID lost ?) in Home.

So, I tried to upgrade again to homebridge@1.0.2 and homebridge-hue@0.11.64 and surprisedly, all plugins are now responding except homebridge-hue which is still  in 'no reponse' state even if I can see accessories are updating correctly in Homebridge log.

Here is the json log.
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4545009/homebridge-hue.json.gz)

**Comment by zany92** [comment]
Interesting observation: I removed homebridge-hue@0.11.64 completely including its configuration from the config.json and I still see the accessories in 'no response' state. scary as I have no clue how to remove them now. So the problem is certainly in the Homebridge 1.0.x.

Any suggestions are welcome.

**Comment by donavanbecker** [comment]
Have you tried v1.0.2?

**Comment by zany92** [comment]
yes

> So, I tried to upgrade again to **homebridge@1.0.2** and homebridge-hue@0.11.64 and surprisedly, all plugins are now responding except homebridge-hue which is still in 'no reponse' state even if I can see accessories are updating correctly in Homebridge log.

**Comment by ebaauw** [comment]
> their Home configuration were lost (back to default room, etc), so were related automations (UUID lost ?) in Home.

This can only happen if you started Homebridge without Homebridge Hue exposing the accessories, and then restarted Homebridge with Homebridge Hue exposing the accessories.  Are you using deCONZ or a Hue bridge?

> Interesting observation: I removed homebridge-hue@0.11.64 completely including its configuration from the config.json and I still see the accessories in 'no response' state

Homebridge Hue is a static platform plugin, meaning that accessories are re-created on Homebridge startup.  If you removed Homebridge Hue from config.json, restarted Homebridge and still see accessories:
- Either these are left-over from a previously paired but now removed Homebridge instance; or
- They're exposed by another Homebridge instance (or the Hue bridge);

**Comment by zany92** [comment]
> This can only happen if you started Homebridge without Homebridge Hue exposing the accessories, and then restarted Homebridge with Homebridge Hue exposing the accessories. Are you using deCONZ or a Hue bridge?

Yes, that's what I did in order to understand if the problem was related to Hue or Homebridge.
I'm using deCONZ

> Homebridge Hue is a static platform plugin, meaning that accessories are re-created on Homebridge startup. If you removed Homebridge Hue from config.json, restarted Homebridge and still see accessories:
>- Either these are left-over from a previously paired but now removed Homebridge instance; or
>- They're exposed by another Homebridge instance (or the Hue bridge);

After rebooting, they disappeared. I will pair again the Phoscon-GW gateway and see how it reacts as I now lost completely the connection. 
Thank you for the feedbacks and support, greatly appreciated.

**Comment by zany92** [comment]
Tried to upgrade again and get the same result then downgrade Hue and Homebridge and i started to work smoothly again.

**Comment by ebaauw** [comment]
I’m afraid that’s an issue with Homebridge v1.0.x, see https://github.com/homebridge/homebridge/issues/2518.  They’re still figuring out what’s causing that.  Please provide the info they request on that issue.

**Comment by zany92** [comment]
thank you, I just did it to try to help
