### ISSUE TITLE
Enabling / Disabling Sensors

### ISSUE THREAD

**Issue by nubicula** [ebaauw/homebridge-hue#69]
I may have misunderstood, but your Readme says you can enable / disable etc the sensors and schedules. What is the correct Siri command to action this. I have tried say turn off the bathroom sensor, but it actually turns off everything in the bathroom.

**Comment by ebaauw** [comment]
I deliberately use a custom characteristic `Enabled` for enabling/disabling the sensors, schedules, and rules, so Siri cannot accidentally do so.  Unfortunately, the iOS built-in Home app cannot deal with custom characteristics, so you need another HomeKit app (like Elgato's Eve) to access these.

If you deliberately want to enable/disable sensors from Siri, you can create a HomeKit scene (from another HomeKit app), that sets/clears the custom `Enabled` characteristic.  Once created, the scene can be triggered by Siri and from the built-in Home app.

**Comment by niggydotcom** [comment]
Has this gone now? I can't see the enabled attribute of my motion sensor in iOS 14.1
