### ISSUE TITLE
No fatal error message in log

### ISSUE THREAD

**Issue by siobhanellis** [ebaauw/homebridge-hue#690]
#### Issue
It's not a major issue, just annoying.

#### Log Messages
Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^12.16.2 which does not satisfy the current Node version of v13.6.0. You may need to upgrade your installation of Node.

**Comment by ebaauw** [comment]
I develop and test against the latest LTS version of node.  Other versions might work, or not.  Hence the warning.
