### ISSUE TITLE
No update on 0.11.64 on HOOBS

### ISSUE THREAD

**Issue by Christian-CFP** [ebaauw/homebridge-hue#691]
No update on 0.11.64 on HOOBS.

**Comment by ebaauw** [comment]
Please contact hoobs support.

**Comment by Christian-CFP** [comment]
Now it is there but crashes with this:
`WARN notsup Unsupported engine for homebridge-hue@0.11.64: wanted: {"BSB001":"1.16.0","BSB002":"1.37.0","deCONZ":"2.5.75","homebridge":"~1.0.0","node":"^12.16.2"} (current: {"node":"12.14.1","npm":"6.14.4"})
2.5.2020, 00:26:37 npm WARN notsup Not compatible with your version of node/npm: homebridge-hue@0.11.64
npm WARN notsup Unsupported engine for homebridge-lib@4.6.1: wanted: {"homebridge":"~1.0.4","node":"^12.16.3"} (current: {"node":"12.14.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-lib@4.6.1`

and the plugin disappears and could not be installed again.

**Comment by donavanbecker** [comment]
Use Homebridge instead of HOOBs.
