### ISSUE TITLE
Tasmota support broken?

### ISSUE THREAD

**Issue by suhajda3** [ebaauw/homebridge-hue#693]
Hello,

I have updated my Tasmota devices to v8.2.0 Elliot and homebridge-hue to v0.11.64. Since then my Tasmota devices disappeared from the Apple Home app.

Since version 8.2.0 Tasmota supports Zigbee for Hue emulation.

I have attached the two log files.

What could be the problem?

Thank you!
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4567420/homebridge-hue.json.gz)
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4567421/homebridge.log.gz)

**Comment by ebaauw** [comment]
I don't have any Tasmota devices myself, so support is on a best effort basis.  The Tasmota doesn't fully comply to the Hue API, so, unfortunately, occasional issues are to be expected.

```
[5/2/2020, 11:11:16] [Hue] Philips hue: TypeError: Cannot read property 'replace' of undefined
    at HueBridge.exposeLight (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:684:47)
```
While adding support for Develco devices, v0.11.61 and later remove `/` characters from the `manufacturername`, because Eve cannot handle these.  Not taking into account that the Tasmota devices fail to expose `manufacturername`.

**Comment by suhajda3** [comment]
👍  Now it works again.

@s-hadinger Are there any plans on the Tasmota side to have better Hue compatibility? The module parameters like manufacturer name and model type are already defined in Tasmota just needed to be exposed to Hue.

**Comment by s-hadinger** [comment]
What do you mean with "better Hue compatibility"? There is a high risk that if you don't pretend to be a Philips device, and a known Philips bulb, that device will discard the response. Actually announcing Philips devices is the best Hue compatibility we can get.

**Comment by s-hadinger** [comment]
Ok you convinced me. I will take a look and check that it does not break Alexa compatibility.

**Comment by s-hadinger** [comment]
@suhajda3 Confirmed, changing `modelid` and `manufacturername` does not break Alexa compatibillity, but they are not surfaced in the Alexa app either. So I'm not exactly sure why you want them changed?

What field do you expect in `modelid` and `manufacturername`? For Z2T (Zigbee) I do have a manuf/modelid. For other devices I only have the Template name which can be used for `modelid`, but nothing as `manufacturername`.

**Comment by suhajda3** [comment]
I knew that Alexa doesn't use them that's why it was always working. But other apps that use Hue like homebridge-hue uses them. This ticket was created because of this. homebridge-hue also passes these values to homebridge. You can eve see them in Homebridge Config UI X.
For example my IKEA outlet that is connected to my Hue gateway and homebridge-hue connects it to my Apple Home app displays the following:
Manufacturer: IKEA of Sweden
Model: TRADFRI control outlet

I expect the manufacturername to be Tasmota and the modelid to be the template name.

Thank you!

**Comment by s-hadinger** [comment]
@suhajda3 I did the changes but unfortunately it breaks the Alexa compatibility. If the modelId is not "Extended color light", the device is not recognized as a light, and if I change the modelid it's not recognized at all.

The only thing I can safely change is the `manufacturername` which is not very interesting.
