### ISSUE TITLE
Heiman Smoke detector send low battery alarm with a full battery

### ISSUE THREAD

**Issue by delucs** [ebaauw/homebridge-hue#695]
#### Issue
Heiman Smoke detector shows low battery in Homebridge (Hoobs) even with new battery. (the gateway is a DeCOnz)
![2020-05-07_17h31_56](https://user-images.githubusercontent.com/7610744/81314817-d4015d80-9089-11ea-8e79-e1ad5f7ce197.png)

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Please attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by odeckmyn** [comment]
Same issue with all battery-powered IKEA Tradfri switches, and with IKEA Furtyr rolling shutter

**Comment by delucs** [comment]
thanks Erik, even if it is a Hoobs fork, i appreciate looking into this
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4620535/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
```
        "35": {
          "config": {
            "battery": null,
            "on": true,
            "reachable": true
          },
          "ep": 1,
          "etag": "1f8271f0d1b11a1d4259832ee1d1c99e",
          "manufacturername": "Heiman",
          "modelid": "SmokeSensor-N-3.0",
          "name": "SmokeSensor-N-3.0",
          "state": {
            "fire": null,
            "lastupdated": "none",
            "lowbattery": null,
            "tampered": null
          },
          "swversion": "2000-0001",
          "type": "ZHAFire",
          "uniqueid": "00:15:8d:00:04:c3:45:6c-01-0500"
        }
```
deCONZ hasn't read/received the battery value from the smoke detector (`config.battery` is null), so Homebridge Hue reports 0%, and Home displays the low battery warning.

Note that deCONZ hasn't received any state update from the detector either (`state` attributes contain default values).  I looks like the detector dropped off the network, or hasn't been configured properly (by the REST API plugin).  You can check in Eve, whether _Last Updated_ gets populated/updated regularly.

You could try power cycling the detector (remove the battery for a couple of seconds).  If that doesn't work, try resetting and re-pairing it (do **not** delete it from deCONZ).  If that doesn't work either, you might need to configure the detector manual, from the deCONZ GUI.  If you need help with that, best open an issue on the deCONZ REST API plugin repository.

**Comment by delucs** [comment]
thanks, I will check and follow your instructions. Right now I see in EVE that there is no "Last Updated" information. Will re-bind it and report back to you

**Comment by delucs** [comment]
I did a new pairing, deCONZ found the device, confirmed with a green « sensor ready », but it does not appear in the list of sensors in deCONZ.... which seems strange....

**Comment by ebaauw** [comment]
Do you mean in the Phoscon web app?  Not so strange, it doesn't support all devices supported by the REST API plugin.  Is _Last Updated_ populated in Eve?

**Comment by delucs** [comment]
Yes, i mean the  Phoscon app. Eve is latest on iphone.

**Comment by ebaauw** [comment]
Sorry, I meant does the _Last Updated_ characteristic in Eve not contain a value?

**Comment by delucs** [comment]
"Last Updated" still has "N/A", never showed a last date and time

**Comment by ebaauw** [comment]
I'm afraid there's nothing I can do in Homebridge Hue.  Best check the deCONZ GitHub, you might need to enrol the sensor manually from the deCONZ GUI.
