### ISSUE TITLE
Tradfri motion sensor. Problem with history of data

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#696]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4606782/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4606783/homebridge-hue.json.gz)

Hello @ebaauw! Eve stopped showing historical data on the Tradfri motion sensor (the new model), it works but shows no history.
I deleted the Eve application and reinstalled it did not help.
I deleted a sensor from the deCONZ and added it again without result.
Аll other sensors show history?
What could be the problem?

**Comment by ebaauw** [comment]
Does the history show on another iDevice, or is it missing from all devices?  Deleting an re-installing Eve should cleanup everything Eve has stored locally, but I don't know how this works in relation to recent iCloud sync introduced in Eve.

If multiple devices don't show history, it's probably a corrupted history file.  Could you check if the file `history_680AE2FFFE3E048D.json` in your `accessories` folder contains valid JSON?  Could you also check the date on the file, to see if it has been updated recently (compare with the other history files).

Not sure what to recommend here.  It's probably easiest to stop Homebridge, delete the file, and rebuild the history from now on.

**Comment by Kristian8606** [comment]
Yes this file was old, and it was empty.  I don't know what caused the deletion of its contents, but I deleted it and now everything works.  I am very grateful to you for the quick response!
