### ISSUE TITLE
latest version "no bridge found searching again in 30 seconds". 

### ISSUE THREAD

**Issue by BrandonHacks** [ebaauw/homebridge-hue#698]
please help. I updated to the latest homebridge and the latest hue plugin.. afterwards the bridge is not found when loading the platform. I downgraded back to previous version which I was on a version from like Febuary and it works again.. what is the problem???

**Comment by ebaauw** [comment]
Please attach the debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file
