### ISSUE TITLE
Tradfri bulb E27 WS opal 1000lm

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#699]
Hi Eriк!
I noticed that the color picker of the light bulb exposed from the homebridge-hue bridge is different from the same light bulb exposed from the tradfri gateway and homekit.
The bulb is a Tradfri bulb E27 WS opal 1000lm.
Can this be fixed?
![C21BEFB9-C4BE-4BA7-A80E-74DF1C419D33](https://user-images.githubusercontent.com/34716572/81951937-797a7b00-960e-11ea-82e0-3fd13fc32ef9.jpeg)
![7726FB26-505D-47D5-A837-7A8155D6A310](https://user-images.githubusercontent.com/34716572/81952171-cfe7b980-960e-11ea-8d62-c8c48c2339e1.jpeg)

**Comment by ebaauw** [comment]
Did you pair the Trådfri bulb to the Hue bridge or to deCONZ?

I take it, the first picture is from Homebridge Hue; the second is from the Trådfri Hub?  As far as I know, this light supports `ct` values in the range of 250 to 454 (see the `/lights` resource as exposed by the Hue bridge / deCONZ gateway).  Homebridge Hue sets these limits on the _Color Temperature_ characteristic, and Home displays the corresponding range.  I think it's a bug in the Trådfri hub, that it shows colour temperature values that the light cannot display.

**Comment by Kristian8606** [comment]
the first photo is from the Trådfri gateway and the second from deCONZ with set  ‘forceCt’ false

**Comment by ebaauw** [comment]
Hm, could you please attach the debug dump file?  See https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by Kristian8606** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4631401/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4631402/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
```
        "2": {
          "ctmax": 65535,
          "ctmin": 0,
          "etag": "fc9eedc7ebba5fbce36cdcdd61ca1fd0",
          "hascolor": true,
          "manufacturername": "IKEA of Sweden",
          "modelid": "TRADFRI bulb E27 WS opal 1000lm",
          "name": "temperature light bedroom",
          "powerup": 7,
          "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "ct": 370,
            "on": false,
            "reachable": true
          },
          "swversion": "2.0.023",
          "type": "Color temperature light",
          "uniqueid": "ec:1b:bd:ff:fe:a2:69:fb-01"
        },
```
Odd, the light reports bogus values for `ctmin` and `ctmax`, so Homebridge Hue would be using the default range of 153 to 500.  Also note the `colormode` which is obviously incorrect, as the bulb doesn't support `xy`.  That might also be firmware related.

My Trådfri White Spectrum bulb does report the correct values:
```
  "15": {
    "ctmax": 454,
    "ctmin": 250,
    "etag": "538128cbb7aef55856e4c86dbfb04155",
    "hascolor": true,
    "lastseen": "2020-05-15T13:13:30.912",
    "manufacturername": "IKEA of Sweden",
    "modelid": "TRADFRI bulb E27 WS�opal 980lm",
    "name": "Trådfri TW",
    "state": {
      "alert": "none",
      "bri": 1,
      "colormode": "ct",
      "ct": 454,
      "on": false,
      "reachable": true
    },
    "swversion": "2.3.007",
    "type": "Color temperature light",
    "uniqueid": "00:0b:57:ff:fe:39:35:7f-01"
  }
```
Note that I've updated mine to the latest Zigbee 3.0 firmware.  Not sure if we have the same light (1000lm vs 980lm).  Mine has the funny character in the `modelid` since the update.

Can you update the bulb firmware and see if that solves the issue?

**Comment by Kristian8606** [comment]
I bought it soon and updated it.  I will check for available updates.

**Comment by Kristian8606** [comment]
I can confirm that the bulb has been updated to the latest version.

**Comment by ebaauw** [comment]
Has updated now, or earlier?  Can you read the _Color Control_ cluster attributes in the deCONZ GUI, and double-check what it reports for _Color temperature min_ (0x400B) and _Color temeperature max_ (0x400C)?

**Comment by Kristian8606** [comment]
> Has updated now, or earlier?

I updated it two weeks ago
![Screenshot 2020-05-17 at 0 45 25](https://user-images.githubusercontent.com/34716572/82130884-12a8bd80-97d8-11ea-9549-aaf701af538b.png)

**Comment by ebaauw** [comment]
So those are the correct values!  Did the API plugin update the resource?  Otherwise it might need re-pairing.

**Comment by Kristian8606** [comment]
I removed it bulb and then paired it. Only one strange behavior of the colored instrument remained. he always returns to the same position

**Comment by ebaauw** [comment]
Can you run `homebridge -D` and check the debug messages with the commands Homebridge Hue send to deCONZ?

**Comment by Kristian8606** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4639346/homebridge.log.gz)

**Comment by ebaauw** [comment]
Homebridge Hue sends the right `ct` command, but deCONZ seems to translate it to `xy`.  The light might actually accept this, but it doesn’t update it’s _Color temperature_ attribute. On the next poll, the old `ct` value is reported back, which Homebridge Hue forwards to HomeKit.

It's a bug in the deCONZ REST API plugin, see
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2507#issuecomment-605420146

**Comment by Kristian8606** [comment]
I'm with the newest master branch and obviously this is not fixed.

**Comment by ebaauw** [comment]
Closing this issue, as there's nothing Homebridge Hue can do here.  To be continued in the deCONZ issue...
