### ISSUE TITLE
Question: Works but requires hue bridge button press each time i restart

### ISSUE THREAD

**Issue by nickbrown20** [ebaauw/homebridge-hue#70]
The plugin works great. My question is why when I upload a new config.json file (that has not changed the hue area of the file) that I need to tap the connect button on the top of the hue bridge each time? Probably very straight forward answer, but I can't locate it at the present.

**Comment by ebaauw** [comment]
You need to edit config.json and add the username homebridge-hue has created.  See the homebridge log output and the README.

**Comment by flighter18** [comment]
hi

I have the same problem.

I added the username and the password to config.json but after the restart of the homebridge service i had to press the button again. This goes on and on.

This is my config

	 {
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

       "platforms": [
		{
		       "platform": "LifxLan",
		       "name": "Licht Büro"
   		},
		  {
		      "platform": "Hue",
		      "name": "Hue",
		      "user": {
			"001788FFXXXXXXXX": "HQFSa7Ojs5vAcNfzeFxt08SCwhRFFncYoXaR7Xbg"
	      	      },
		    "heartrate": 5,
		    "timeout": 5,
		    "lights": true,
		    "philipslights": true,
		    "groups": false,
		    "group0": false,
		    "rooms": false,
		    "sensors": true,
		    "clipsensors": true,
		    "schedules": false,
		    "rules": false
		      }
	],

	"accessories": [{
		"accessory": "Sonos",
		"name": "Musik Mobil",
		"room": "Mobil"
	}, {
		"accessory": "Sonos",
		"name": "Musik Wohnzimmer",
		"room": "Wohnzimmer"
	},{
                "accessory": "Sonos",
                "name": "Musik Schlafzimmer",
                "room": "Schlafzimmer"
	},{
                "accessory": "Sonos",
                "name": "Musik Bad",
                "room": "Bad"

	},
	    {
		      "accessory": "SSH",
		      "name": "Stein Lampe",
		      "on": " /home/pi/xxxo > /dev/null",
		      "off": "/home/pi/xxxf > /dev/null",
		      "status": "cat /home/pi/xxxs",
		      "ssh": {
			"user": "root",



			"host": "pi",
			"port": 22
		      }
	    }
	]
}

**Comment by ebaauw** [comment]
@flighter18 You might want to check the output of homebridge:

```
[3/1/2017, 11:29:22 PM] [Hue] Initializing Hue platform...
[3/1/2017, 11:29:22 PM] [Hue] config.json: warning: user: ignoring unknown key
[3/1/2017, 11:29:22 PM] [Hue] homebridge-hue v0.3.8, node v6.9.4, homebridge api v2.1
```
The parameter is `"users"` (plural), not `"user"` (singular).

**Comment by flighter18** [comment]
oh my god what a mistake.
Thank you much !
