### ISSUE TITLE
HomeBridge 1.1.0 hue plugin not work

### ISSUE THREAD

**Issue by CypressGTX** [ebaauw/homebridge-hue#700]
After updating HomeBridge to 1.1.0 the hue plugin get the next error:
![1](https://user-images.githubusercontent.com/64326376/82151773-9bb60800-985d-11ea-8a2f-e2d07209df33.jpg)

After that error I downgrade HomeBridge back to 1.0.4 and reinstall Hue plugin.
After fill in the hostname 192.168.2.1 and put the user in the config I get the next error.

<img width="1316" alt="Schermafbeelding 2020-05-17 om 16 26 58" src="https://user-images.githubusercontent.com/64326376/82151797-bb4d3080-985d-11ea-8493-31bdc19099cb.png">

what's happen? thank you!

**Comment by ebaauw** [comment]
What server do you run Homebridge on?  What version of NodeJS?

**Comment by CypressGTX** [comment]
thank you

node 13.1.0

running on Raspberry PI

**Comment by ebaauw** [comment]
I don't get any of this running Homebridge v1.1.0 on Raspbian Stretch on a Raspberry Pi 3B+.
What version of Raspbian are you on?  How did you install Homebridge?

I have no idea what the `uuid` module does nor what the error means.  Looks like the error happens loading the JavaScript files, before Homebridge Hue even does anything.  I'm afraid it's an issue with your installation.

v13.1.0 is quite an old version of node.  Best try the latest v13.  Support for node v13 will end soon, better use v12 or v14.  Note that you need to re-compile any libraries using C or C++ modules after installing a new major release of node.

**Comment by CypressGTX** [comment]
Hi ebaauw

Thanks for helping, i reinstalled my homebridge with the latest raspbian include homebridge image and everything works great with your plugin.

Ticket closed 💪🏼
