### ISSUE TITLE
homebridge-hue compatibility with color temperature tool "Kelvin"

### ISSUE THREAD

**Issue by brandungskieker** [ebaauw/homebridge-hue#701]
I want my lights to be bright blueish when the sun is up, and warm when the sun is down. This should be automatic. By searching for a fitting solution I came around [Kelvin](https://github.com/stefanwichmann/kelvin) a little helper bot who will automate the lights by controlling Philips Hue. 
Is there a way to make Kelvin compatible with homebridge-hue?

**Comment by kmplngj** [comment]
Hi, nice find. 

I make this with Home Assistent, the Fluxer Integration and Deconz. 

Why does Homebridge-Hue need to be compatible with Kelvin?

Homebridge-Hue connects to the Hue Bridge and Kelvin connects to the Hue Bridge. 

Bye
Jan

**Comment by brandungskieker** [comment]
Hi Jan, thanks, got it. Do you have further tips/links to solve this specific automation (daylight-specific light temperature) on Home Assistent?

**Comment by kmplngj** [comment]
[Home Assistant Docu](https://www.home-assistant.io/integrations/flux/)
