### ISSUE TITLE
It would be nice to have an option to hide the enabled characteristic via config

### ISSUE THREAD

**Issue by bachandi** [ebaauw/homebridge-hue#702]
Something like the resource config option would be nice to have for the enabled characteristic.

**Comment by ebaauw** [comment]
Why?

**Comment by bachandi** [comment]
Was just reading the config options and noticed `resource`: Set to false, to reduce the memory footprint of the accessories exposed by homebridge-hue. Many probably don't need the enabled characteristic for the sensors so I thought it would be nice to no show them with the same argument as for `resource`

**Comment by ebaauw** [comment]
Resource is a string characteristic, enabled is boolean.  Argument doesn’t really apply.
