### ISSUE TITLE
HOOBS Certification

### ISSUE THREAD

**Issue by mkellsy** [ebaauw/homebridge-hue#703]
I wanted to let you know we have certified this plugin.

We run and test your plugin in HOOBS, and offer support for you.

The plugin page can be found here.
https://plugins.hoobs.org/plugin/homebridge-hue

Your plugin works as of 3.2.5+

**Comment by mkellsy** [comment]
We also certified homebridge-zp

https://plugins.hoobs.org/plugin/homebridge-zp

**Comment by ebaauw** [comment]
See #694.

I have never used HOOBS, nor will I ever do so.  I did not ask for HOOBS certification.  I do not want HOOBS support.

Please use the HOOBS support channels to support HOOBS users.

**Comment by mkellsy** [comment]
Hay man, I'm just trying to be friendly.

I don't know what your image is of us, but I feel it is wrong. HOOBS is a project of mine that I personally use. I don't make any money from it and any donations we get or profit, from hardware sales, go straight to our cloud provider.

I think you have great plugins, and I just want to coloraborate with you. No hard feelings, keep up the great work.
