### ISSUE TITLE
 Ikea Tradfri Blinds stopped working after upgrade to v0.11.69

### ISSUE THREAD

**Issue by lc808** [ebaauw/homebridge-hue#705]
Hello,

I updated yesterday the homebridge-hue plugin to new version  v0.11.69. Unfortunately it seems like my Ikea Tradfri Blinds are not receiving any control signals anymore. In the Home App they show "Opening" and config UI-shows "Closing...". Physically they are closed while taking this screenshot.
If it try to control them nothing happens.

Out of Deconz/Phoscon I am able to control them.

Anything I have to adjust in the config after the update or what could be the problem?

<img width="331" alt="Screen Shot 2020-06-01 at 10 36 49 AM" src="https://user-images.githubusercontent.com/60233804/83391501-da1dfc00-a3f3-11ea-96b7-22383066c6f8.png">

**Comment by lc808** [comment]
short update: the issue seems to be linked to v0.11.69 - I just verified by downgrading back to v0.11.68 and it`s working....

**Comment by ebaauw** [comment]
Did you update deCONZ to v2.05.77?  Homebridge Hue v0.11.69 needs that version for controlling the blinds using the new API attributes, `state.open` and `state.lift`.

**Comment by lc808** [comment]
I just did this update and now it works properly. Sorry, I was not aware that i have to update deconz itself, i was until now only checking the firmware version in the phoscon app!

thanks a lot for your help and thanks for this great plug in!
