### ISSUE TITLE
Strange behavior of the slider in homekit

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#706]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4711105/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4711106/homebridge-hue.json.gz)

When you slide the slider up at a higher speed to about 70 percent, it returns to zero and then goes back to 70 percent.
To understand me correctly I am attaching this video.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34716572/83406695-dbf9b680-a417-11ea-88c2-00663281ae3e.gif)

Is it possible to correct it?

**Comment by ebaauw** [comment]
> Is it possible to correct it?

No, it's a fundamental design flaw in HomeKit.  It doesn't distinguish between current and target brightness (and other light attributes such as hue, saturation, and colour temperature).

I think you're using deCONZ and an IKEA or OSRAM light (one that supports attribute reporting)?

You set the target brightness using the slider, causing Homebridge Hue to send a Zigbee command to change the brightness.  The light starts transitioning from it's current brightness (or off position) to the target brightness.  Depending on the transition time, and the attribute reporting settings, the API updates the reported brightness several times during this transition.  Homebridge Hue uses this to update the slider.

**Comment by Kristian8606** [comment]
Yes this is an IKEA bulb.  I noticed that this behavior does not appear with  Chinese bulb and also with the Trådfri gateway for this I assumed that the problem could be corrected in deconz or homebridge-hue

**Comment by ebaauw** [comment]
If you disable attribute reporting for the IKEA bulb, or remove the binding from its _Level Control_ cluster to the coordinator, you won't see this behaviour for the default transition time of 0.4 seconds.  However, I think the REST API plugin might restore these settings.

**Comment by Kristian8606** [comment]
Is it possible while the slider is moving, Homebridge-Hue to ignore the returned state from api and after some time to apply the last returned state from api?

**Comment by Kristian8606** [comment]
I noticed that this problem only appears when the light bulb is off, but if it is 1 percent and you slide the slider, the problem is gone.

**Comment by ebaauw** [comment]
> Is it possible while the slider is moving

No, HomeKit doesn’t provide any info as to whether the slider is still moving.  It just reports the current position.  You could try and tweak `waitTimeUpdate` to make Homebridge Hue wait a little longer to see if HomeKit sends another value before sending the command to deCONZ.

> Homebridge-Hue to ignore the returned state from api and after some time to apply the last returned state from api?

I don’t have the equivalent of `waitTimeUpdate` to set the HomeKit state.  I could ignore updates from the API for a brief period (0.5 seconds) after sending a command, but that probably won’t work out well, as you might need to wait until Homebridge Hue next polls the gateway before the actual state is reflected.

What version of deCONZ are you on?  How long have you been seeing this behaviour?  I suspect this is one of the unforeseen side-effects of sending the same commands as the Hue bridge, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2475.  I think I’d better change that back, if only for non-Hue lights.

**Comment by Kristian8606** [comment]
My deconz is with version .77 and the latest firmware of conbee 2.  I have been using deconz recently and the problem was with the .75 version

**Comment by Kristian8606** [comment]
I experimented with the time of waitTimeUpdate there is no effect on the problem.

**Comment by ebaauw** [comment]
> My deconz is with version .77 and the latest firmware of conbee 2. I have been using deconz recently and the problem was with the .75 version

Sorry is the problem with .75 and with .77, or only with .75?  In the first case: my recent changes in deCONZ handling the light state don't influence the issue.  I'm afraid there's nothing I can do without introducing other issues elsewhere.

**Comment by Kristian8606** [comment]
The problem is present in .75 and .77  versions.

In the examples I have with esp8266 esp_homekit_demo I notice that the slider does not receive feedback on its status during the up or down drag.
I update its status only when I enter the home application or when I increase the brightness with a button that calls this function https://github.com/Kristian8606/simple_dimming_LED/blob/1518e95f16db6044c25a1697716d7eb5b9587327/main.c#L232

**Comment by Kristian8606** [comment]
I would do a test. Would you direct me where in your code  to stop updatings the slider to test?

**Comment by ebaauw** [comment]
The _Brightness_ characteristic is updated here:
https://github.com/ebaauw/homebridge-hue/blob/e9a8ec165983a8d61b5585f78674594124c899b4/lib/HueLight.js#L998

Updating the light when moving the slider is handled here:
https://github.com/ebaauw/homebridge-hue/blob/e9a8ec165983a8d61b5585f78674594124c899b4/lib/HueLight.js#L1555

**Comment by Kristian8606** [comment]
for test I managed to ignore the slider feature updates, and it started to behave steadily and move smoothly.
The question is how do I ignore updates only when the slider is moving?

**Comment by Kristian8606** [comment]
`this.obj.state.bri` is a global variable?

**Comment by ebaauw** [comment]
`this.obj` in an instance variable, of course.  It points to the light or group object from the full bridge state created during startup.  It's maintained only by the `HueLight` instance for the light or group.

**Comment by Kristian8606** [comment]
I analyzed the behavior of Ikea bulbs and realized that when the bulb receives a brightness update, it immediately returns to its current brightness and after a few seconds returns to its already updated brightness, this behavior makes the slider in the home app jump.  I will try to give an example: if the slider is 20% and touch its upper end to 100% the bulb immediately returns its current brightness 20% which updates the slider to 20 and after a few seconds returns the already updated value 100%

**Comment by Kristian8606** [comment]
I made a slight change to the code that eliminates this behavior.  I'm sure it's not the best solution but I hope you look at it and I'm also sure you'll find a good way to implement

**Comment by ebaauw** [comment]
The logic was already implemented in `HueLight.js` for `ct` and `xy`.  I just wasn't applied to `bri`.

**Comment by Kristian8606** [comment]
Great

**Comment by Kristian8606** [comment]
I tested but sometimes it doesn't work

**Comment by ebaauw** [comment]
What do you mean by “Doesn’t work”?  Please attach a debug log file.

The code just ignores any updates of the value by deCONZ for 500ms after sending the changed value to deCONZ.  It doesn’t count the number of updates.

Afaik no light is capable of sending multiple updates in 300 ms.

**Comment by Kristian8606** [comment]
I'm sorry I was in a hurry and I couldn't explain what I meant.
I restarted my Raspberry pi because I have observed that after a long use (3-5 days) the reaction of sensors and bulbs slows down and after the restart they work quickly again.
After the restart I started testing the slider and everything seems to be fine but sometimes the function obviously fails to ignore the update and the slider jumps again.
As far as I remember the bulbs on the ikea, websocket send several status messages, 3-5 for a period of 300-350 milliseconds after touching the slider and another one after about 4-5 seconds. 
example: first message 2ms after touching the slider, second - 8ms third 9ms fourth 112ms fifth last 4-5000ms.
I suspect that the function does not ignore the first 2 commands one updates the slider to 1% the next to 100%.
I hope for now this information will be useful to you, as soon as I have time I will try to recreate the problem and upload the logs.

**Comment by ebaauw** [comment]
Did you manage to re-create the issue while capturing a log?

**Comment by Kristian8606** [comment]
I tested several times after restarting the radpberry pi.  I can confirm that the problem is still present, most often I reproduce it on a bulb TRADFRI bulbE27 WS opal 1000lm.
Unfortunately I still can't save log files

**Comment by Kristian8606** [comment]
https://youtu.be/ySZlL_eTMjQ

**Comment by ebaauw** [comment]
I really need a debug log file to see what's happening.  Latest version of Homebridge Config UI X now allows downloading the log file from the _View Logs_ screen, if you use `hb-service`.

**Comment by Kristian8606** [comment]
[homebridge.log.txt.gz](https://github.com/ebaauw/homebridge-hue/files/5137159/homebridge.log.txt.gz)

Sorry for the delay! Here is the file

**Comment by ebaauw** [comment]
What is the attribute reporting configuration for the _Current Level_ attribute of the bulb?  It seems to take the light 5 seconds to report the (final) brightness.  Meanwhile, Homebridge Hue is polling the gateway, receiving the initial brightness (for which the attribute report was ignored alright).  With standard 1/300/1 settings, I would expect the light to report the final brightness after a second, not after 5 seconds.  You could try a setting of 0/300/1.  That might cause multiple reports, but they should appear in the 0.4 seconds of the transition.

I cannot do anything about this in Homebridge Hue.  As workaround, you might disable attribute reporting for the bulb (but the deCONZ REST API Plugin will probably re-configure it), or you might increase the `heartrate` to 30 (you can do this runtime in Eve for testing), so there's a smaller chance that the gateway is polled in between the reports.

Here you set the light to on and 87% brightness.
```
[2020-8-27 17:54:17] [Hue] TRADFRI bulb Bedroom: homekit brightness changed from 66% to 87%
[2020-8-27 17:54:17] [Hue] TRADFRI bulb Bedroom: homekit on changed from 0 to 1
[2020-8-27 17:54:17] [Hue] Phoscon-GW: gateway request 11: put /lights/6/state {"bri":221,"on":true}
[2020-8-27 17:54:17] [Hue] Phoscon-GW: gateway request 11: ok
```
deCONZ updates it's cache and echoes the values back to Homebridge Hue:
```
[2020-8-27 17:54:17] [Hue] TRADFRI bulb Bedroom: state changed event: {"alert":null,"bri":221,"colormode":"ct","ct":250,"on":true,"reachable":true}
```
There's no update needed, as HomeKit already reflects that brightness.

Next, deCONZ receives an attribute report from the bulb and issues a web socket notification.  Homebridge Hue rightfully ignores this change, due to the recent update from HomeKit:
```
[2020-8-27 17:54:17] [Hue] TRADFRI bulb Bedroom: state changed event: {"alert":null,"bri":2,"colormode":"ct","ct":250,"on":true,"reachable":true}
[2020-8-27 17:54:17] [Hue] TRADFRI bulb Bedroom: light bri changed from 221 to 2
[2020-8-27 17:54:17] [Hue] TRADFRI bulb Bedroom: recently updated - ignore changed bri
```
When next polling the gateway, Homebridge Hue notices the brightness differs from HomeKit and updates HomeKit:
```
[2020-8-27 17:54:22] [Hue] Phoscon-GW: gateway request 15: get /lights
[2020-8-27 17:54:22] [Hue] Phoscon-GW: gateway request 15: ok
[2020-8-27 17:54:22] [Hue] TRADFRI bulb Bedroom: light bri changed from 221 to 2
[2020-8-27 17:54:22] [Hue] TRADFRI bulb Bedroom: set homekit brightness from 87% to 1%
```
Only thereafter, the attribute from the light arrives, and Homebridge Hue updates the HomeKit brightness:
```
[2020-8-27 17:54:22] [Hue] TRADFRI bulb Bedroom: state changed event: {"alert":null,"bri":221,"colormode":"ct","ct":250,"on":true,"reachable":true}
[2020-8-27 17:54:22] [Hue] TRADFRI bulb Bedroom: light bri changed from 2 to 221
[2020-8-27 17:54:22] [Hue] TRADFRI bulb Bedroom: set homekit brightness from 1% to 87%
```

**Comment by Kristian8606** [comment]
I hope IKEA for updates this bulb.
thanks for the help.
