### ISSUE TITLE
Exclude specific sensors, not types?

### ISSUE THREAD

**Issue by FlipMuc** [ebaauw/homebridge-hue#707]
Hi,

is it possible to exclude certain sensors (not types) from being exposed to Homekit?

For example: I have multiple motions throughout the house which are needed for for various Homekit automations.

Some other motion sensors are used in Node Red flows only and the results are published to Homekit via MQTT. Therefor these Motion Sensors don't need to be published to HK.

**Comment by ebaauw** [comment]
Use a `blacklist` resource link, see https://github.com/ebaauw/homebridge-hue#configuration.

**Comment by FlipMuc** [comment]
awesome! thanks!

**Comment by wills721** [comment]
This doesnt work if you have more than one HOOBs server.  If you blacklist a device it is blacklisted globally.  Based on my read of the docs anyway.  I would prefer a way to have the HOOBs server define which devices are excluded -- similar to what Tuya Web HOOB plug in does.  This way specific HOOBs servers can exclude.
