### ISSUE TITLE
Issue with choosing color temperature colors on gledopto 1ID controller...

### ISSUE THREAD

**Issue by ivantomicic-crowdhouse** [ebaauw/homebridge-hue#708]
So if I'd go and choose either warm or cold white, homekit would override it with (I guess not random) color - therefore I can't really create automations with cold/warm white on RGBCCT strips, does anyone have an idea why that might be happening?

**Comment by ebaauw** [comment]
Because Home doesn't support all of HomeKit.  Use Eve to create the HomeKit scene instead.

**Comment by ivantomicic-crowdhouse** [comment]
But it does work with regular Hue lights?

**Comment by ebaauw** [comment]
Home doesn't support both _Hue_ / _Saturarion_ and _Color Temperature_ on the same _Lightbulb_ service.  So when you think you select a colour temperature using the wheel, Home actually sends _Hue_ and _Saturation_ to the accessory (in this case: Homebridge Hue).

This is no issue for the older "regular" gamut-B Hue lights, that only support three channels, RGB, and create colour temperatures using these.  They've optimised the RBG LEDs on these lights, so they produce proper colour temperatures, at the expense of full blue and green.

It is an issue for the newer "regular" gamut-C Hue lights and for the GLEDOPTO, which support five channels, RGB/WW/CW.  Sending _Hue_ and _Saturation_ drives the RGB channels (through setting `xy`), whereas sending _Color Temperature_ drives the WW/CW channels (through setting `ct`).

I worked around this issue by using an old custom _Color Temperature_ characteristic (from before Apple defined the standard characteristic).  Eve still recognises it, and Home happily ignores it.

**Comment by ivantomicic-crowdhouse** [comment]
Ah that sucks! I have more than 20 gledopto controllers that I want to use :/

As workaround I thought about exposing these Phillips Hue sccenes to homekit as switches and toggle colors that way, but I can't get scenes to show in homekit, any idea why?

**Comment by ebaauw** [comment]
You can use HomeKit scenes alright, you just need to create them in Eve.  You can still recall them from Home and Siri.

To expose scenes on the Hue bridge or deCONZ, set `groups`, `group0`, and `scenes` to true in config.json.  Or whitelist the groups whose scenes you want to expose.  The scenes are exposed as additional _Switch_ services to the accessory for the group.

**Comment by ivan-diversyfund** [comment]
Hey man! Thank you, I've been messing with this for a few days now, and kindof figured how I will use it...

One last question, would 2ID controller give me an option to control temperature with that 2nd light which would be only white, or would it do the same thing? Thanks!

**Comment by ebaauw** [comment]
I never laid my hands on a 2ID controller, but I think it works like the old RGBW controllers: it exposes two endpoints, one _Color Light_ to drive the RGB channels, and one _Color Temperature_ light to drive the CW/WW channels.  I think you can drive both channel groups independently, and at the same time, whereas the 1ID drives either RGB or CW/WW.

Homebridge Hue should exposes the 2ID as two separate _Lightbulb_ services in a single accessory, one with _Hue_ and _Saturation_, the other with the Apple standard _Color Temperature_.

**Comment by ivan-diversyfund** [comment]
Yeah, thats right, but I was wondering if that other light would control actual color temperature of strip or would it do same thing as 1ID and try to mimic colors with RGB part of the strip... I guess I'll order one and give it a try :D

**Comment by ebaauw** [comment]
The 1ID light doesn’t mimic anything.  Apple’s Home app does.  As it will see a _Lightbulb_ with only _Color Temperature_, it won’t display the colour wheel, and send _Color Temperature_ changes, which Homebridge Hue translates to `ct`.
