### ISSUE TITLE
Motion Sensor Duration (Delay) characteristic? 

### ISSUE THREAD

**Issue by leoneleone** [ebaauw/homebridge-hue#71]
Hello

The plugin keeps getting better and better. Thank you for maintaining it so well! 👍🏼

I know I've mentioned this before but I think it deserves repeating: 
Is there any way to create a "Duration" (Delay) HomeKit Characteristic which delays the MotionUndetected call by a set X amount of Seconds?
This "Duration" would only be affective within the HomeKit network and not carry over to the Hue Bridge in any way, and is totally independent of the Motion Off Delay accessable using the Hue.app 

It would only be useful for creating HomeKit triggers based on the Hue Motion Sensor "Motion Undetected" info. Of course the default can be set to Zero so that the current Hue Motion info behaves the same as it currently does in HomeKit. The "Duration" characteristic would be useful to users who want to set a delay for individual sensors which will sustain "motion Detected" status visible in HomeKit by a pretermined time in seconds. 

Both the Elgato Eve Motion Sensor, and Fibaro Motion Sensor offer this configurable behaviour from within HomeKit apps. It would only be logical to emulate something similar for the Hue Motion Sensor support within this plugin. It would be a simple definable variable which effect the Duration of the Motion Detected status visible in HomeKit. 

The Elgato Eve "Duration" Characteristic, viewable and configurable using the Eve.app:
**Copied from the last comment at https://gist.github.com/gomfunkel/b1a046d729757120907c 

"..the settings/attributes for the Elgato Eve Motion Sensor:..

E863F120-079E-48FF-8F27-9C2605A29F52 - Sensitivity
readable/writeable
0 <= UInt8 <= 7

E863F12D-079E-48FF-8F27-9C2605A29F52 - Duration
readable/writeable
2 <= UInt16 <= 65000 // I assume seconds
"

Thanks again man for the wonderful work on this plugin.

**Comment by ebaauw** [comment]
@leoneleone I'll take it under consideration, but I disagree with your reasoning.

> The "Duration" characteristic would be useful to users who want to set a delay for individual sensors which will sustain "motion Detected" status visible in HomeKit by a pretermined time in seconds.

You can do that today using a Hue bridge rule (that does support conditions like "10 minutes after the motion was no longer detected") that sets a `CLIPGenericFlag` sensor and base the HomeKit rule on that sensor instead.  See my earlier comment https://github.com/ebaauw/homebridge-hue/issues/7#issuecomment-272622339.

> Both the Elgato Eve Motion Sensor, and Fibaro Motion Sensor offer this configurable behaviour from within HomeKit apps. It would only be logical to emulate something similar for the Hue Motion Sensor support within this plugin.

It would only be logical for Philips to provide something similar for the Hue motion sensor.  They could probably do it with just a bridge firmware update.  Did you ask them?  
Then again, it would only be logical for Philips to expose the Hue motion sensor to HomeKit in the first place (and Hue dimmer switches, and non-Philips lights, and everything else homebridge-hue provides).

>It would be a simple definable variable which effect the Duration of the Motion Detected status visible in HomeKit.

The variable itself is simple enough, indeed.  Implementing the behaviour associated with this variable is more elaborate.  When `presence` becomes `false` I need to set a timeout to turn off `MotionDetected`.  When `presence` becomes `true` before the timeout expires, I need to cancel the timeout.  
Sensitivity is straightforward: that's an attribute on the Hue bridge.  I'm not sure why you'd want to set that from HomeKit (or from rules regardless where).  Much light the thresholds for dark and daylight, I've used it only to calibrate the sensors.

> The Elgato Eve "Duration" Characteristic

Cool!  Hadn't come across that one yet.  Do you know if Fibaro uses the same custom characteristic type?

**Comment by ebaauw** [comment]
@leoneleone I'm trying to add the `Sensitivity` and `Duration` characteristics as per the specs you mention, but Eve doesn't show them.  They do show in other HomeKit apps, so Elgato probably expose these characteristics in a special, custom service.  I don't have any Eve Motion Sensor, but the Eve Energy and the Eve Door & Window Sensor actually expose two services: one standard HomeKit service, `Outlet` or `Contact Sensor`, and one custom service.  As far as I can see the custom service provides the history, and means to reset it.

Could you provide some screenshots of what the Eve Motion Sensor actually looks like in Eve, in particular: where can you set the Sensitivity and Duration?

**Comment by ebaauw** [comment]
Checking the [Elgato blog](https://blog.elgato.com/new-elgato-eve-motion/), they seem to "hide" the configuration under Settings under Accessories.  I did find a screenshot in the [iLounge review](http://www.ilounge.com/index.php/reviews/entry/elgato-eve-motion) of the Elgato motion sensor.

Still, the `Sensitivity` and `Duration` don't show up there either.  Also asked this question at the [Elgato Eve gist](https://gist.github.com/gomfunkel/b1a046d729757120907c#gistcomment-2036449).

For now, I'll be creating my own custom characteristic types.

**Comment by leoneleone** [comment]
@ebaauw 
Sorry for the late reply but I've been extremely busy recently.

You are correct that Elgato and Fibaro each use individual custom characteristics for the delay/duration setting. I think this will be the case until Apple standardises the Characteristic in iOS 11 hopefully.

Thank you so much for adding this functionality, as I said before I believe it to be integral to using a Motion Sensor service within HomeKit.

I'll test the new additions later today and let you know how it works.

You da man!!

**Comment by ebaauw** [comment]
Added `Duration` and `Sensitivity` to v0.3.12.

For now, I've defined custom characteristics for both myself.  `Duration` is in minutes, between `0` and `120`.  @leoneleone, please let me know if this works for you.  I tried seconds between `0` and `7200` at first, but this makes it impossible to set the value precisely using the slider in Eve.  Note that you need to set `Duration` after each restart of homebridge, as I cannot persist the value using static platform accessories (see issue #4).

I really think these characteristics (together with `Enabled`, `Status Active`, `Status Fault`) should be exposed using a separate configuration service, probably with Admin only access.  I like that Eve shows the Eve Motion Sensor configuration only under _Accessories_, and not under _Rooms_.  However, I don't have access to one of those, so it's hard for me to figure out how they've done that.

**Comment by leoneleone** [comment]
Hi @ebaauw 
Hope you're well Erik.
Sorry I never got back to you with feedback since my last communication. 

The changes you've made, and continue to make, are really very impressive. I really commend you for the support you're giving to the users of your plugin. 

The plugin works great now, and the addition of the Duration/Delay field for the Motion Sensors is a good one. Unfortunately, as you have pointed out before, the Duration Characteristic is of very little use unless it is somehow tied to the the Duration for the motion off command which is set by the Hue Bridge (configurable via the Hue.app). You have explained before that this is a limitation from the Hue API itself, as it doesn't expose the Motion off delay time that is already configured. If in the future there is a way to duplicate the Motion sensor duration that would be the way to go. 

In the meantime, I am using the Power Off command/value for the lights (which is triggered by the Hue motion sensors) in my HomeKit automations - in place of the Hue Motion (motion undetected) HomeKit value. I have found this to be more reliable, and is an accurate representation of the Hue Motion delay time which is set in the Hue app.

Great work Erik!!

**Comment by ebaauw** [comment]
I'm no fan of (ab)using light states for signalling myself.  If you're willing and able to create your own Hue bridge rules, rather than using the Hue app, you could set a CLIPGenericFlag sensor when motion is detected, and clear it x minutes after motion is no longer detected.  Homebridge-hue exposes this flag as a switch to HomeKit.  Then you would control your lights through Hue bridge rules based on the flag changing, and your other HomeKit accessories using HomeKit automation.  I use this setup to control my lights and Sonos speakers when entering and leaving a room.

The Hue motion sensor actually supports the ZigBee attribute for the presence no longer detected delay.  Using a ZigBee dongle and accompanying software, I was able to change this.  This seemed to work, but I had to reset the sensor before I could change it again.

**Comment by twentyNoise** [comment]
Hi Erik,

I had a question along the lines of this topic. I just purchased a Hue Bridge v2 and a Hue Motion Sensor. I was hoping to buy a few of the motion sensors and use them around the house. I love the Hue Motion Sensor because it's so compact.

Anyhow, I was having a few issues and was wondering if Homebridge-hue could solve them for me.

1. The Hue Bridge now exposed motion, lux and temp to HomeKit, but of course I can't set the motion sensor 'no motion detected' delay, or the sensitivity in HomeKit. I see that I 'could' change the default config.duration to something like 5 minutes. You said it needs to be reset after each Homebridge restart, but I feel like I saw in another thread that I could hardcode it in the config?

2. How do I set the sensitivity for the Hue Motion Sensor via Homebridge-hue? I was testing the Hue Motion Sensor the other night and our cats were setting it off.

I was hoping that I could set this all in the Hue app, but that's not possible. Because I don't have any Hue lights or other hue accessories I can't even 'get into the main part of the app'. All I see is the HomeKit & Siri config, but if I hit next it won't let me get past the 'add lights' screen. But I'm pretty sure this is normal, as I read that I can't config the Hue Motion Sensor in Hue AND HomeKit, that is you can only use it in one or the other.

I bought the Eve Motion to test, and while it's actually a great sensor, it's like double the size of the Hue and it's Bluetooth so I don't think it will connect from a few areas of the house where I'd like to put Motion Sensors.

Anyhow, it seems like the duration delay is possible, now I just need to see about the sensitivity (as though I'm changing this in the Hue app - again, I know this sensitivity slider is in the app, but I can't get to it anyway and doesn't seem like it would matter if I could).

Thanks for your help

**Comment by ebaauw** [comment]
Indeed, the Hue motion sensors are great, I’ve got 12 of them around my house, but I find the Hue bridge and Hue app do a poor job supporting them.  Indeed the Hue app is only fully functional when you have at least one light connected to the bridge.  
I love the design of the Eve products and their app, but, indeed, Bluetooth doesn’t seem the right protocol for home automation.  I prefer ZigBee.

You can set sensitivity (and usertest) through the Hue API.  Value 2 is high, value 0 is low.  homebridge-hue doesn’t expose these to HomeKit.

While the sensor itself supports no motion delay, the Hue bridge doesn’t expose this through the Hue API (we do expose it through the deCONZ API).  To overcome this, homebridge-hue exposes a _Duration_ to HomeKit, whose value is kept in memory, and lost when restarting homebridge.  You can change this value in HomeKit.  The default value after starting homebridge is hard coded.  
I still plan to move to dynamic platform assessories (see #4), so the _Duration_ value will be persisted across homebridge restarts.

**Comment by twentyNoise** [comment]
Thanks for the info.

So then are you saying I could technically set the sensitivity outside of HomeKit, and then the Hue Motion Sensor would use the set sensitivity in my HomeKit setup (even though HomeKit can’t set sensitivity)?

If so, you said I can set it through the Hue API, how exactly? Can I set it with Homebridge-hue and even though it’s not exposed to HomeKit, the setting will persist?

Thanks again for your help. I’m really hoping I can hang on to the Hue sensors. The Eve actually works quite well in our Kitchen, as responsive as the hue was, but the kitchen is also right next to our Apple TV / Bluetooth.

**Comment by twentyNoise** [comment]
Erik,

Thanks for this! I'll have to try this tonight.

If that's the case, I'll bet I could also buy a cheap Hue bulb for $8 to get access to the app, to set the sensitivity. But why bother spending the money, haha.

Thanks again!

**Comment by ebaauw** [comment]
Both sensitivity and duration are actually stored on the motion sensor, and exposed through the deCONZ REST API.  Note that deCONZ uses `config.delay`, to distuinguish it from the duration that deCONZ maintains for other motion sensors that don’t issue a message when they no longer detect motion.  Also note that the Hue bridge doesn’t expose duration, so homebridge-hue implements a fake duration (per sensor), which indeed resets when homebridge restarts.  To change that, I need to refactor homebridge-hue completely, to support the dynamic accessories model of homebridge, see #4.

Both sensitivity and duration are exposed to HomeKit. Of course, Apple’s Home app doesn’t support these custom characteristics, but they work fine in Eve.  They can be found on the accessory configuration screen (the little gear icon at the top of the accessory details screen, where you also set the room).  I now use the same custom characteristic as Eve - this was needed to support history.
