### ISSUE TITLE
same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by Olepir** [ebaauw/homebridge-hue#710]
#### Issue

[6/5/2020, 16:13:02] [Hue] homebridge: error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8dd05041-7360-4a97-9d75-64f4e5276192
#### Log Messages

```
[6/5/2020, 16:12:50] [HB Supervisor] Starting Homebridge with extra flags: -I
[6/5/2020, 16:12:50] [HB Supervisor] Started Homebridge v1.1.0 with PID: 8069
[6/5/2020, 16:12:51] Loaded config.json with 0 accessories and 4 platforms.
[6/5/2020, 16:12:51] ---
[6/5/2020, 16:12:53] Loaded plugin: homebridge-cmdswitch2@0.2.10
[6/5/2020, 16:12:53] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[6/5/2020, 16:12:53] ---
[6/5/2020, 16:12:53] Loaded plugin: homebridge-config-ui-x@4.21.0
[6/5/2020, 16:12:53] Registering platform 'homebridge-config-ui-x.config'
[6/5/2020, 16:12:53] ---
[6/5/2020, 16:12:56] Loaded plugin: homebridge-hue@0.11.69
[6/5/2020, 16:12:56] Registering platform 'homebridge-hue.Hue'
[6/5/2020, 16:12:56] ---
[6/5/2020, 16:12:56] Loaded plugin: homebridge-webos-tv@1.8.7
[6/5/2020, 16:12:56] Registering accessory 'homebridge-webos-tv.webostv'
[6/5/2020, 16:12:56] Registering platform 'homebridge-webos-tv.webostv'
[6/5/2020, 16:12:56] ---
[6/5/2020, 16:12:56] Loading 4 platforms...
[6/5/2020, 16:12:56] [webostv] Initializing webostv platform...
[6/5/2020, 16:12:56] [CMD Switch] Initializing cmdSwitch2 platform...
[6/5/2020, 16:12:56] [Config] Initializing config platform...
[6/5/2020, 16:12:56] [Config] Running in Service Mode
[6/5/2020, 16:12:56] [Hue] Initializing Hue platform...
[6/5/2020, 16:12:56] [Hue] homebridge-hue v0.11.69, node v12.17.0, homebridge v1.1.0
[6/5/2020, 16:12:56] [webostv] Init - initializing devices
[6/5/2020, 16:12:56] [webostv] Init - initializing device with name: LG TV
[6/5/2020, 16:12:56] [CMD Switch] Initializing platform accessory 'Playstation'...
[6/5/2020, 16:12:56] LG TV is running on port 40791.
[6/5/2020, 16:12:56] Please add [LG TV] manually in Home app. Setup Code: 234-05-546
[6/5/2020, 16:12:57] [Hue] searching bridges and gateways
[6/5/2020, 16:13:02] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
[6/5/2020, 16:13:02] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
[6/5/2020, 16:13:02] [Hue] Phoscon-GW: 1 accessories
[6/5/2020, 16:13:02] [Hue] Phoscon-GW: 1 accessories
[6/5/2020, 16:13:02] [Hue] masked debug info dumped to /var/lib/homebridge/homebridge-hue.json.gz
[6/5/2020, 16:13:02] Initializing platform accessory 'Phoscon-GW'...
[6/5/2020, 16:13:02] [Hue] Phoscon-GW: 2 services
[6/5/2020, 16:13:02] Initializing platform accessory 'Phoscon-GW'...
[6/5/2020, 16:13:02] [Hue] Phoscon-GW: 2 services
[6/5/2020, 16:13:02] [Hue] homebridge: error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8dd05041-7360-4a97-9d75-64f4e5276192

```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4736936/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Somehow your gateway is discovered twice.  Never seen that before.  What is the output of `ph discover -v`?

**Comment by Olepir** [comment]
`{
  "deconz": {
    "192.168.5.234:4530": "00212EFFFF05B55D"
  },
  "meethue": {},
  "upnp": {
    "192.168.5.234:4530": "00212EFFFF05B55D"
  }
}`

**Comment by ebaauw** [comment]
That's looking fine.  Could you please run `homebridge -D` and capture the output?

**Comment by Olepir** [comment]
I removed the plugin and installed again, all works now.
Sorry to bother you.
Thanks!

**Comment by Dreiviertelblut** [comment]
Also the same here. Double entry of Phoscon-GW during start-up of Homebridge:

[6/11/2020, 22:31:59] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
[6/11/2020, 22:31:59] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.77, api v1.16.0
[6/11/2020, 22:31:59] [Hue] Philips hue neo: Philips BSB002 bridge v1939070020, api v1.38.0
[6/11/2020, 22:31:59] [Hue] Philips hue: Philips BSB002 bridge v1939070020, api v1.38.0

**Comment by ebaauw** [comment]
As I said above, I have no idea what could be causing this.  I need the debug log file and the output of `ph discover -v` when this happens to start troubleshooting.

**Comment by Dreiviertelblut** [comment]
Many thanks for the quick reply. Phoscon is running on 192.168.177.45. 

I've now added the "hosts" parameter array with the three ip addresses to config.json and could not replicate it anymore. Probably this did the trick?


$ ph discover -v
{
  "deconz": {
    "127.0.0.1": "0021FE2FFF05C146"
  },
  "meethue": {
    "192.168.177.39": "001877FFFE70DB77",
    "192.168.177.57": "ECBAF5FFFE188996"
  },
  "upnp": {
    "192.168.177.39": "001877FFFE70DB77",
    "192.168.177.45": "0021FE2FFF05C146",
    "192.168.177.57": "ECBAF5FFFE188996"
  }
}

**Comment by ebaauw** [comment]
> I've now added the "hosts" parameter array with the three ip addresses to config.json and could not replicate it anymore. Probably this did the trick?

Yes.  That disables discovery and simply expose the listed gateways/bridges.

So, it seems deCONZ registers with the portal under `127.0.0.1`, whereas it advertises the correct address on UPnP.  That’s a bug in deCONZ alright.  Could you check `ph discover` on another machine (than running deCONZ), or try a `curl https://phoscon.de/discover`?

I would expect Phoscon to behave strangely as well (when run on another machine): showing two gateways, or not being able to connect to the gateway.

**Comment by Dreiviertelblut** [comment]
Many thanks again for the super swift reply! Last start of the machine was a regular reboot. First start of Deconz was done manually, as originally after installation Deconz-Gui was running and had massive problems with the right timing to start the Deconz-Gui during start-up. Don't know, if that is relevant here.

I was doing a firmware update of raspbee II today due to not working RTC functionality. Stopped the homebridge + deconz. Started up both services up again (manually) and gave it another try. It advertises the right ip addresses.

$ ph discover -v
{
"deconz": {
"192.168.177.45": "0021FE2FFF05C146"
},
"meethue": {
"192.168.177.39": "001877FFFE70DB77",
"192.168.177.57": "ECBAF5FFFE188996"
},
"upnp": {
"192.168.177.39": "001877FFFE70DB77",
"192.168.177.45": "0021FE2FFF05C146",
"192.168.177.57": "ECBAF5FFFE188996"
}
}

Then did a regular reboot of my Raspberry and 127.0.0.1 was back again.

Curl command from my NAS:
curl http://phoscon.de/discover
[{"id":"0021FE2FFF05C146","internalipaddress":"127.0.0.1","macaddress":"0021FE2FFF05C146","internalport":80,"name":"Phoscon-GW","publicipaddress":"xx.xxx.xx.xxx"}]

Phoscon:
![grafik](https://user-images.githubusercontent.com/57370038/84479408-31915700-ac93-11ea-9fa5-922961851096.png)

**Comment by ebaauw** [comment]
> First start of Deconz was done manually, as originally after installation Deconz-Gui was running and had massive problems with the right timing to start the Deconz-Gui during start-up.

You might want to check out https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2482.

> I was doing a firmware update of raspbee II today due to not working RTC functionality.

Pi 4B?  See: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2864

> Then did a regular reboot of my Raspberry and 127.0.0.1 was back again.

Thanks, that confirms my suspicion.  I'll open an issue in the deCONZ REST API plugin repository.

**Comment by Dreiviertelblut** [comment]
It's a Pi 2B on my end. But also there, real issues with the hwclock!
You might want to check: https://github.com/dresden-elektronik/raspbee2-rtc/issues/3

Many thanks for the link to solve the deconz-Gui timing problem. Moreover, as I now have the opportunity.....Many thanks for your great job providing an excellent solution with homebridge-hue. Absolutely great and works fantastic!

**Comment by ebaauw** [comment]
Above commit filters out duplicate bridges/gateways in discovery or `hosts`.

**Comment by DJBenson** [comment]
I've just restarted my homebridge instance and I am seeing this issue.

homebridge is version 1.1.1
homebridge-hue is version 0.11.72

homebridge crashes with the following;

>[6/25/2020, 16:42:40] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d2ec417a-6b6b-4f38-96cb-a9890822f3f1
    at Bridge.Accessory._this.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:310:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:270:69)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:158:10)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

Which led me to this defect.

The output of ph discover -v is

> {
  "deconz": {
    "192.168.1.10:8888": "00212EFFFF05B691"
  },
  "meethue": {},
  "upnp": {
    "192.168.1.10:8888": "00212EFFFF05B691"
  }
}

deCONZ is version 2.05.78.

**Comment by DJBenson** [comment]
@ebaauw does this need a new bug report or are you happy for it to continue here?

**Comment by ebaauw** [comment]
If you specify `hosts`, Homebridge Hue doesn’t use the discovery.

Are you using any other Homebridge plugins?  Could you please attach the debug dump file and capture and attach a debug log file?  See https://github.com/ebaauw/homebridge-hue#debug-log-file and https://github.com/ebaauw/homebridge-hue#debug-dump-file

**Comment by DJBenson** [comment]
> If you specify `hosts`, Homebridge Hue doesn’t use the discovery.
> 
> Are you using any other Homebridge plugins? Could you please attach the debug dump file and capture and attach a debug log file? See https://github.com/ebaauw/homebridge-hue#debug-log-file and https://github.com/ebaauw/homebridge-hue#debug-dump-file

Since I ended up trashing my install anyway, I have re-built the install adding each config entry one by one and I've tracked it down to another plugin. I landed on homebridge-hue as it was the last plugin to log before it died but I've not enabled it yet and I'm getting the same error from another plugin so I think my issue is elsewhere.

Thanks for the quick response.

**Comment by scharti** [comment]
I was running in to the same issue after a blackout. What is the solution? thanks
RPi with hoobs

19.3.2021, 22:38:51 HOOBS listening on port 80.
19.3.2021, 22:38:52 Initializing HAP-NodeJS v0.9.3...
19.3.2021, 22:38:53 [3/19/2021, 3:38:53 PM] The plugin "homebridge-hue" requires Node.js version of ^14.16.0 which does not satisfy the current Node.js version of v12.16.3. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
19.3.2021, 22:38:55 Loaded plugin 'homebridge-hue'
19.3.2021, 22:38:55 Loading 1 platforms...
19.3.2021, 22:38:55 [3/19/2021, 3:38:55 PM] Registering platform 'homebridge-hue.Hue'
19.3.2021, 22:38:55 [Hue] Initializing Hue platform...
19.3.2021, 22:38:55 [Hue] homebridge-hue v0.13.3, node v12.16.3, homebridge v1.3.3
19.3.2021, 22:38:55 [Hue] config.json: plugin_map: invalid key
19.3.2021, 22:38:55 [Hue] searching bridges and gateways
19.3.2021, 22:39:00 [Hue] PhosconGW: dresden elektronik deCONZ gateway v2.9.3, api v1.16.0
19.3.2021, 22:39:00 [Hue] PhosconGW: dresden elektronik deCONZ gateway v2.9.3, api v1.16.0
19.3.2021, 22:39:01 [Hue] PhosconGW: 21 accessories
19.3.2021, 22:39:01 [Hue] PhosconGW: 21 accessories
19.3.2021, 22:39:01 Initializing platform accessory 'PhosconGW'...
19.3.2021, 22:39:01 [Hue] PhosconGW: 2 services
19.3.2021, 22:39:01 Initializing platform accessory 'Küche Decke'...
19.3.2021, 22:39:01 Initializing platform accessory 'Flur Vorn'...
19.3.2021, 22:39:01 Initializing platform accessory 'Bad Licht 3'...
19.3.2021, 22:39:01 Initializing platform accessory 'Flur Hinten Licht 1'...
19.3.2021, 22:39:01 Initializing platform accessory 'Flur Hinten Licht 2'...
19.3.2021, 22:39:01 Initializing platform accessory 'Flur Hinten Licht 3'...
19.3.2021, 22:39:01 Initializing platform accessory 'Bad Licht 1'...
19.3.2021, 22:39:01 Initializing platform accessory 'Küche Arbeitslicht'...
19.3.2021, 22:39:01 Initializing platform accessory 'Daylight'...
19.3.2021, 22:39:01 Initializing platform accessory 'Bad Taster'...
19.3.2021, 22:39:01 Initializing platform accessory 'Flur Hinten Bewegung'...
19.3.2021, 22:39:01 Initializing platform accessory 'Bad Sensor'...
19.3.2021, 22:39:01 Initializing platform accessory 'Flur Vorn Bewegung'...
19.3.2021, 22:39:01 Initializing platform accessory 'Wohnzimmer Sensor'...
19.3.2021, 22:39:01 Initializing platform accessory 'Schlafzimmer Sensor'...
19.3.2021, 22:39:01 Initializing platform accessory 'Arbeitszimmer Sensor'...
19.3.2021, 22:39:01 Initializing platform accessory 'Schlafzimmer Taster'...
19.3.2021, 22:39:01 Initializing platform accessory 'Dimmschalter'...
19.3.2021, 22:39:01 Initializing platform accessory 'Zauberwürfel'...
19.3.2021, 22:39:01 Initializing platform accessory 'Küche Taster'...
19.3.2021, 22:39:01 Initializing platform accessory 'PhosconGW'...
19.3.2021, 22:39:01 [Hue] PhosconGW: 2 services
19.3.2021, 22:39:01 [Hue] homebridge: error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 32fc1ba7-8dfd-4d94-8a24-xxxxxxxxxxx
19.3.2021, 22:39:28 [Hue] heartbeat 11, drift 15260
19.3.2021, 22:39:28 [Hue] heartbeat 12, drift 14264
19.3.2021, 22:39:28 [Hue] heartbeat 13, drift 13267
19.3.2021, 22:39:28 [Hue] heartbeat 14, drift 12270
19.3.2021, 22:39:28 [Hue] heartbeat 15, drift 11273
19.3.2021, 22:39:28 [Hue] heartbeat 16, drift 10280


hoobs@hoobs:/home/hoobs/.hoobs/etc $ ph discover
{
"127.0.0.1:1881": {
"apiversion": "1.16.0",
"bridgeid": "00212EFFFF0658DF",
"datastoreversion": "93",
"devicename": "ConBee II",
"factorynew": false,
"mac": "dc:a6:32:2d:5c:2d",
"modelid": "deCONZ",
"name": "PhosconGW",
"replacesbridgeid": null,
"starterkitid": "",
"swversion": "2.9.3"
},
"192.168.100.41:1881": {
"apiversion": "1.16.0",
"bridgeid": "00212EFFFF0658DF",
"datastoreversion": "93",
"devicename": "ConBee II",
"factorynew": false,
"mac": "dc:a6:32:2d:5c:2d",
"modelid": "deCONZ",
"name": "PhosconGW",
"replacesbridgeid": null,
"starterkitid": "",
"swversion": "2.9.3"
}
}

**Comment by ebaauw** [comment]
Your gateway gets discovered twice, once using the localhost address.  Haven’t seen that before.  Could you run `ph -D discover` to check by what method the 127.0.0.1 is returned?  Are you running deCONZ and hoobs on the same Pi?

**Comment by scharti** [comment]
Im running both hoobs and deCONZ on the same Pi. If im using the host function of the hue plugin it works. If I delete the host and reboot hoobs this is what if got:
```
hoobs@hoobs:/home/hoobs/.hoobs/etc $ ph -D discover
ph: upnp: request 1: M-SEARCH *
ph: upnp: listening on 0.0.0.0:44514
ph: meethue: request 1: GET /
ph: phoscon: request 1: GET /
ph: upnp: found 00212EFFFF0658DF at 192.168.100.41:1881
ph: 192.168.100.41: request 1: GET /config
ph: 192.168.100.41: request 1: 200 OK
ph: meethue: request 1: 200 OK
ph: phoscon: request 1: 200 OK
ph: phoscon: found 00212EFFFF0658DF at 127.0.0.1:1881
ph: 127.0.0.1: request 1: GET /config
ph: 127.0.0.1: request 1: 200 OK
ph: upnp: search done
{
  "127.0.0.1:1881": {
    "apiversion": "1.16.0",
    "bridgeid": "00212EFFFF0658DF",
    "datastoreversion": "93",
    "factorynew": false,
    "mac": "dc:a6:32:2d:5c:2d",
    "modelid": "deCONZ",
    "name": "PhosconGW",
    "replacesbridgeid": null,
    "starterkitid": "",
    "swversion": "2.9.3"
  },
  "192.168.100.41:1881": {
    "apiversion": "1.16.0",
    "bridgeid": "00212EFFFF0658DF",
    "datastoreversion": "93",
    "factorynew": false,
    "mac": "dc:a6:32:2d:5c:2d",
    "modelid": "deCONZ",
    "name": "PhosconGW",
    "replacesbridgeid": null,
    "starterkitid": "",
    "swversion": "2.9.3"
  }
}
```

Thanks

**Comment by ebaauw** [comment]
> `ph: phoscon: found 00212EFFFF0658DF at 127.0.0.1:1881`

So deCONZ has registered under `127.0.0.1` with `https://phoscon.de/discover`.  That's clearly a bug in the REST API plugin.  It's probably caused by deCONZ starting before the network stack.  Does this change when you restart deCONZ, without rebooting the Pi?  If so, you might want to set the Pi to wait for network before booting (option `S6` in `raspi-config`).

When running deCONZ and Homebridge on the same Pi (as I would strongly recommend anyways), I would simply add `"hosts": ["127.0.0.1:`_port_`"]` to config.json to bypass discovery.

**Comment by ebaauw** [comment]
Added a check whether discovered bridge has already been exposed.

**Comment by scharti** [comment]
> > `ph: phoscon: found 00212EFFFF0658DF at 127.0.0.1:1881`
> 
> So deCONZ has registered under `127.0.0.1` with `https://phoscon.de/discover`. That's clearly a bug in the REST API plugin. It's probably caused by deCONZ starting before the network stack. Does this change when you restart deCONZ, without rebooting the Pi? If so, you might want to set the Pi to wait for network before booting (option `S6` in `raspi-config`).
> 
> When running deCONZ and Homebridge on the same Pi (as I would strongly recommend anyways), I would simply add `"hosts": ["127.0.0.1:`_port_`"]` to config.json to bypass discovery.

Thanks this is exactly what I did.

**Comment by ebaauw** [comment]
> Added a check whether discovered bridge has already been exposed.

In v0.13.4.

**Comment by scharti** [comment]
> > Added a check whether discovered bridge has already been exposed.
> 
> In v0.13.4.

Thanks for the quick update 👍

**Comment by G0sch** [comment]
sorry for re-activating this older thread, but I have a similar issue.
By adding the hosts parameter, I got rid of the most issue, but I see now the phoscon 2 times in the Home(kit)-app.
Normal as phoscon device (flagged as "unsupported") and as "CLIP-Sensor PUSHDIM-TOOGLE"
Any idea where this come from?
![IMG_0FAD54ACB737-1](https://user-images.githubusercontent.com/51472553/212936714-2b7926b9-3a22-4608-94ce-a93d714930cc.jpeg)
