### ISSUE TITLE
Install dresden elektronik deconz one same raspberry than Homebridge

### ISSUE THREAD

**Issue by batatat** [ebaauw/homebridge-hue#711]
Hello,
I bought a raspbee II for my raspberry who run actually with Homebridge. I tried to install deconz with this : https://phoscon.de/en/raspbee2/install#raspbian but it look don't work. @ebaauw, I saw on your description that you did that. Have you advice to install both on same raspberry ?

**Comment by ebaauw** [comment]
I just followed those steps.  For help with deCONZ, best go to the deCONZ Discord, or open an issue in the deCONZ GitHub repository.
