### ISSUE TITLE
Expose native hue lights to Config UI X 

### ISSUE THREAD

**Issue by pponce** [ebaauw/homebridge-hue#712]
Not sure if this is possible.
I currently I have my hue bridge v2 exposing native hue lights to homekit and your plugin allows me to expose non hue lights that are paired to the same hue bridge to homekit. Everything works great.

I recently installed config-ui-x and wanted to know if I could have the hue lights exposed as accessories only for use with config-ui-x.
Maybe the "right way" to do this is to have your plugin expose everything to homekit and stop having hue expose the native lights. But was hoping I could leave my working setup as is and still use config-ui-x with the hue native lights.
thoughts?

**Comment by ebaauw** [comment]
Run a separate homebridge instance just exposing the Hue lights for Config UI X.

**Comment by pponce** [comment]
Brilliant!
