### ISSUE TITLE
Aqara Switch Opple Phoscon

### ISSUE THREAD

**Issue by ebrger** [ebaauw/homebridge-hue#713]
Hello, I am using Homebridge V1.1.0, Hue plugin 0.11.69 and Phoscon 2.05.77 
 
I have Aqara Opple 4/6 Switch these are also shown in Phoscon (with picture, but i don't know if you can configure buttons, it's my first project with Phoscon...) i would like to use the switches in HomeKit. 
 
They also appear, just like the Phoscon Gateway in HomeKit.  But there is a call sign at the switches.  I guess it is because no battery status is transmitted. 
 
Unfortunately the buttons do not work.  I have assigned a scene or device but nothing happens. 
 
Is this a known problem?  Can I help with the solution or is there already someone who has the Opple switches in HomeKit?

Thanks a lot!

![5C9CB3D2-2BE1-4215-ABDF-1086BDCE49C2](https://user-images.githubusercontent.com/31549020/84438622-24467f00-ac37-11ea-8bae-e07d2ec6c225.png)

**Comment by ebaauw** [comment]
I have the 6-button Opple and it works just fine in HomeKit.  All buttons register _Single Press_, _Double Press_ and _Long Press_.

Did you just pair the switch?  It might take a few hours before the battery is populated.

Note that you need a Home hub (Apple TV, HomePod, or always-powered iPad) for the buttons to work.  Handling the buttons is like a HomeKit automation: this is done by the Home hub.

If you need more help troubleshooting, please capture a debug log file, while pressing the Opple's buttons, and attach the file here.  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by ebrger** [comment]
Hey you, I got an iPad. I'm afraid I just got to the logs, but I think they're incorrect, don't you?
I'm not able to switch buttons with it yet.
Unfortunately I still get an error in the battery display.
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/4776370/homebridge.log.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4776371/homebridge-hue.json.gz)

**Comment by ebrger** [comment]
@ebaauw can you help me? I don't know if the logs are right or if I'm doing something wrong.
But unfortunately I still can't figure it out, the buttons don't trigger any action and a battery problem is displayed.
Thanks a lot

**Comment by ebaauw** [comment]
Sorry, haven’t yet found the time to look at the logs.  Need to be at my mac to do that.

**Comment by ebaauw** [comment]
> I'm afraid I just got to the logs, but I think they're incorrect, don't you?

The debug log is what I want to see, but it looks like you didn't press any buttons while capturing the log.

The debug dump file reveals two Opple switches: a 6-button one that seems to work, and a 4-button one for which Homebridge Hue has never received a `buttonevent`.  I think it hasn't paired correctly to deCONZ.

**Comment by ebrger** [comment]
Thanks for your Support!!!
This is strange, both switches are displayed in Phoscon (Deconz).  But I do not understand why I have problems in HomeKit.  The problem with the battery indicator is still there, it does not disappear even after a few days. 
this is what it looks like for me in HomeKit.Maybe it's the same problem?
![34306FBC-FDD7-4000-A37B-A95F7D64485C](https://user-images.githubusercontent.com/31549020/84810548-cb4a6280-b00b-11ea-823a-48e4b0798387.jpeg)
![48F5570B-847D-44EC-ABAF-3ECE55DC6791](https://user-images.githubusercontent.com/31549020/84810685-fa60d400-b00b-11ea-9d59-8c3cf08b5a59.jpeg)
![3311E1FA-5E97-4448-9EFF-16706FAE0E47](https://user-images.githubusercontent.com/31549020/84810695-fcc32e00-b00b-11ea-9fa4-0a89214279dc.jpeg)

**Comment by ebaauw** [comment]
> This is strange, both switches are displayed in Phoscon (Deconz).

That only means that the REST API plugin has created resources for the switches.  It say nothing about whether the switches are actually communicating with deCONZ.

I think the issue is between the switch and deCONZ, nothing to do with Homebridge Hue.  You can double-check in the deCONZ GUI if the _Present Value_ attribute of the _Multistate Input_ cluster changes when pressing the corresponding button.  If it doesn't, message from the switch don't arrive at deCONZ.

**Comment by ebrger** [comment]
Thanks for your Support!
After upgrading to Homebridge-Hue V. 0.11.71 and deCONZ v2.05.78, every think works Fine!
