### ISSUE TITLE
Default Philips Hue on Home App 

### ISSUE THREAD

**Issue by martinorob** [ebaauw/homebridge-hue#716]
After upgrading to the last version, even if in my config is the same, now I have the "Default Philips Hue (Not compatible)" button on my Home App

"platforms": [{
			"platform": "Hue",
			"users": {
				"XXXX": "XXXX"
			},
			"sensors": true,
			"nativeHomeKitSensors": false,
			"lights": true,
			"excludeSensorTypes": ["Daylight", "CLIP", "Geofence", "CLIPPresence", "ZLLSwitch"],
			"linkButton": false,
			"wallSwitch": false
		},

**Comment by ebaauw** [comment]
Not sure what you mean.  Homebridge Hue exposes an accessory for the Hue bridge, that Apple’s Home app doesn’t support, but that has been there From the very first version.

**Comment by martinorob** [comment]
ok sorry, #close
