### ISSUE TITLE
Gledopto GL-C-007 doesn't respond to Home App automations

### ISSUE THREAD

**Issue by SanderBaron** [ebaauw/homebridge-hue#719]
Hi,
Using your plugin in Hoobs on a Raspberry. Works perfect with my Hue stuff. Only have a problem with the two Gledopto GLC-C-007 five channel (RGBWW) led controllers. 
When I control them directly from the Home app or from the Hue app, they seem to respond good, but when I put them in a Home app Automation (ie 30 minutes after sunset go to 100% a certain color temp) they are never responding... It drives me crazy. When I set up the automation and press the button 'test automation' they work perfect, but when I run the automation they don't respond. Most of the times when I check the Home app they light do switch on, but are set at 1%... 
I don't know if this is a Gledopto thing, an HomeKit thing or it has to do something with the Homebridge-Hue plugin, but I really hope you can help out!
I'm not a Linux expert, but I can follow detailed instructions very well! 
Thanks!
![Schermafdruk 2020-06-25 23 49 58](https://user-images.githubusercontent.com/53954610/85959247-5841d400-b99b-11ea-8bad-02424a6308b0.png)

**Comment by ebaauw** [comment]
HomeKit automations run on your Home hub (AppleTV, HomePod, or iPad).  Testing the automation runs on your iPhone (or where you run the Home app).  If that works, Homebridge Hue is doing its thing correctly.

Does your hub show as active in the Home app?  Can you double-check (using `netstat` Or running `DEBUG=* homebridge -D`) that your Home hub is connected to Homebridge?  If these check out, I think the synchronisation (over iCloud) of your HomeKit automations and/or scenes to your Home hub has failed.  You might try restarting your Home hub, logging out from iCloud on your Home hub and back in, turn off all automations, wait for these changes to propagate to your other devices, and turn them back on.

**Comment by SanderBaron** [comment]
Hi, thanks for your fast reply. The hub is running fine. I already tried rebooting, deleting automations and rebuilding them etc. etc. I added the issue here because I was reading other issues about Gledopto controllers icm HomeKit / homebrigde-hue.
I have been testing some setting, also with other apps like Eve. I deleted the Home automations and rebuilt them from scratch. This time I used a temperature setting instead of a color and tonight the automation fired correct!
I still don't know why the Gledopto Controllers behave differently compared with the Hue controllers.

**Comment by ebaauw** [comment]
> I still don't know why the Gledopto Controllers behave differently compared with the Hue controllers.

Because they are different devices, different hardware and different firmware.  I don’t think these differences are related to your HomeKit automation issues, though.
