### ISSUE TITLE
unable to get modified config.json file to work correctly. Unable to get Hue to auto load on startup.

### ISSUE THREAD

**Issue by FotoGen1** [ebaauw/homebridge-hue#720]
#### Issue

Everything works when using the original config.json file. But when I use this config.json file with the users added:

{
    "bridge": {
        "name": "Homebridge EE1C",
        "username": "XX:XX:XX:XX:XX",
        "port": 51144,
        "pin": "512-42-768"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": true,
            "n/Users/garyr/Library/Mobile Documents/com~apple~TextEdit/Documents/Untitled 2.txtativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue",
            "users": {
              "008817FFFE491C00": "UVnvMEUW2NSB8d4Mkeu6La3RDs-R1LG6SYTMRztM"
            }
        }
    ]
}

It doesn't initialize and it just outputs multiple lines of
[6/28/2020, 11:39:30 AM] [Hue] heartbeat 457, drift 4021

with different numbers for heartbeat and drift

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Please capture and attach a debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file.  Please also attach the debug dump file, https://github.com/ebaauw/homebridge-hue#debug-dump-file.
