### ISSUE TITLE
Samsung SmartThings Plug Seen As LightBulb

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-hue#722]
Not sure if this is an issue with deCONZ, or the Homebridge-Hue plugin (suspect the former) but my Samsung SmartThings mains plug is detected as a light.  I know the Philips Hue plug one also does this, but it's really frustrating as - in this case - I have a DVR plugged into it, and that's certainly not a light!

Is there any way these smart plugs can be detected/translated to the Outlet service type rather than the LightBulb one?

Thanks!

**Comment by ebaauw** [comment]
Create an `outlet` resourcelink with the `/lights` and `/groups` resources to expose as _Outlet_.

**Comment by fullphat** [comment]
Thanks!  Could you explain how to do this?
