### ISSUE TITLE
Disable battery reporting

### ISSUE THREAD

**Issue by mtjoernelund** [ebaauw/homebridge-hue#724]
Would it be possible to incorporate a setting (probably under advanced) to always report battery state as 100%.

Use case: I am using Homekit only as a front end for manual control, setting scenes etc. This is used by both myself and my wife. All automations and management is handled in NodeRed and NodeRed Dashboard, which only I access. Sometimes battery reporting, both from Ikea switches and from Aqara sensors are a bit erratic. When that happens I have one or more reports in Apple’s Home app, stating that battery level in various accessories are low, which is just annoying. 

If I could overrule and just have them always report 100% in homekit, I would not get those annoying warnings cluttering up the home app, while still having access to updated information in NodeRed.

**Comment by ebaauw** [comment]
There is a setting for the threshold for the low battery status, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.  Not sure if all HomeKit apps look at this status; I think Eve gives a warning when battery is below 20%, irrespective of the status.  Last I check, Home did seem to use it.

**Comment by mtjoernelund** [comment]
Thanks. Not sure how I managed to miss this. Have set this and see if Apple home app actually respects this. 

I think (hope) I’ve said this before. But thanks for some great work on this plugin and for always being quick to respond.
