### ISSUE TITLE
Hue Motion sensor reporting battery as 0%

### ISSUE THREAD

**Issue by bluefangs** [ebaauw/homebridge-hue#725]
#### Issue
I do not use the native hue app / ios Home connection since 80% of the time, home reports that none of my devices are responding. So for a good few months, I relied on homebridge-hue to expose hue lights and motion sensors on to Apple Home
My Hue setup was a bit slow so I reset the hue bridge and stated over. I set up the hue bulbs and sensors via the hue app, then paired it with homebridge-hue. And now I notice that all my 5 motion sensors are reporting battery as 0%. This was not happening prior to the reset. I would like to drill down to see where the problem lies. Apple home promptly reports these devices in Red color indicating that the battery is low.

I'm attaching the logs as required by the template. I've stripped down my current homebridge setup to JUST the hue module. I have removed other devices that I used to use in homebridge - for the sake of simplicity.

Kindly let me know where the problem could lie.

Thanks!
#### Log Messages

I took a look at homebridge-hue.json.gz and noticed that the battery is null. Is this supposed to be this way?

```
"2": {
				"state": {
					"presence": false,
					"lastupdated": "2020-07-07T10:46:49"
				},
				"swupdate": {
					"state": "noupdates",
					"lastinstall": "2020-07-07T09:48:21"
				},
				"config": {
					"on": true,
					"battery": null, =====================> should this be null?
					"reachable": true,
					"alert": "none",
					"sensitivity": 2,
					"sensitivitymax": 2,
					"ledindication": false,
					"usertest": false,
					"pending": []
				},
				"name": "Dining Room Motion Sensor",
				"type": "ZLLPresence",
				"modelid": "SML001",
				"manufacturername": "Signify Netherlands B.V.",
				"productname": "Hue motion sensor",
				"swversion": "6.1.1.27575",
				"uniqueid": "00:17:88:01:06:f7:60:3e-02-0406",
				"capabilities": {
					"certified": true,
					"primary": true
				}
			}
```

#### Debug Files

Zip file contents: 
[debug-files.zip](https://github.com/ebaauw/homebridge-hue/files/4884432/debug-files.zip)

homebridge-logs.txt ==> homebridge console logs
config.json ==> homebridge config.json
homebridge-hue.json

**Comment by ebaauw** [comment]
> I took a look at homebridge-hue.json.gz and noticed that the battery is null. Is this supposed to be this way?

Supposed: no, possible: yes.  Battery-powered devices cannot be queried by the Hue bridge, as their radio is off almost all the time.  On pairing, the bridge should setup attribute reporting for the _Battery Percentage Remaining_ attribute of the _Power Configuration_ cluster, so the device periodically reports it battery level.  Sometimes this fails somehow, and `battery` remains `null`.  Note that for the Hue motion sensor, the battery is supposed to be reported once per two hours, so you might just need to have some patience.

If they're not updated in a day or so, try re-pairing the sensor.

**Comment by bluefangs** [comment]
Thanks for the quick response @ebaauw 
I happened to change the ZigBee frequency and it that possibly triggered the battry to be reported correctly now. I suppose removing the sensors and re-pairing them would have had a similar effect. Good to close this one out.

Thanks!
