### ISSUE TITLE
Retrieve temperature info from Aqara Leak Sensor

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-hue#726]
#### Issue

I've just purchased an Aqara Leak sensor and I notice it also exposes the current temperature in the Phoscon app, however homebridge-hue only exposes the `LeakSensor` and `Battery` services.  Any chance support for `CurrentTemperature` could be added?

#### Log Messages

```
```

**Comment by ebaauw** [comment]
No, see https://github.com/ebaauw/homebridge-hue/issues/657.
