### ISSUE TITLE
HB V11.73 recommends Nodejs V12.18.2+

### ISSUE THREAD

**Issue by duceduc** [ebaauw/homebridge-hue#727]
Homebridge V11.73 recommends nodejs V12.18.1 to be install. 
Homebridge GUI shows nodejs version as 12.18.1; however, on rpi it is showing v12.18.2. I am confuse as which version is actually installed. I have already submit an issue with Homebridge. I just want to verify with Homebridge-hue plugin as well.

**Comment by ebaauw** [comment]
You might need to restart the supervisor after upgrading node, or it will still show the old version as that’s what it’s running in.  Other common cause is multiple installations of node.
