### ISSUE TITLE
Full support for eCozy thermostat

### ISSUE THREAD

**Issue by honzakeller** [ebaauw/homebridge-hue#728]
#### Issue

Recently I found out that eCozy thermostat headers are supported by deConz so I reach for couple old ones I purchased in the past. I try to pair them with my RaspBee and they really works... kind of.

In Home app I can set temperature for Heating and the settings are correctly transferred to the thermostat. But the Home app always showing 0 degree current temperature.

I don't know what exactly to provide to improve the integration, so at least few screenshots for the beginning. I can even send one thermostat over if it helps.

The question is if the problem is in homebridge-hue or deConz or somewhere else.

eCozy are not really the best and most reliable and for that I don't use them anymore but if bringing them over to deConz and HomeKit works I would give them another chance.

RaspBee, deConz v2.05.77, homebridge-hue v0.11.72

<img width="369" alt="Screenshot 2020-07-11 at 23 25 26" src="https://user-images.githubusercontent.com/880755/87234369-71517880-c3d0-11ea-8128-a39113e6cbc7.png">

<img width="307" alt="Screenshot 2020-07-11 at 23 25 47" src="https://user-images.githubusercontent.com/880755/87234371-77475980-c3d0-11ea-802b-f696d1ce4e67.png">

![IMG_1898](https://user-images.githubusercontent.com/880755/87234362-55e66d80-c3d0-11ea-90cb-de669bcfa39f.jpg)

**Comment by ebaauw** [comment]
Could you attach the debug dump file.  I need to see how deCONZ exposes the thermostat.

**Comment by honzakeller** [comment]
Cannot find homebirdge.log.gz. If this is not enough I will provide more later today.

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4908115/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Looks like deCONZ hasn't populated the `state` (yet?).  I don't know if its because the pairing went wrong (binding/attribute reporting wasn't setup), or if the integration is not yet complete.  Happy to take a look at the device if you can provide one.  Please PM me on discord.
```
        "8": {
          "config": {
            "battery": 50,
            "heatsetpoint": 1450,
            "offset": 0,
            "on": true,
            "reachable": true,
            "scheduler": null,
            "scheduleron": false
          },
          "ep": 3,
          "etag": "d94623a378e7398a1f1aab16daa329b4",
          "lastseen": "2020-07-04T21:38:43.223",
          "manufacturername": "eCozy",
          "modelid": "Thermostat",
          "name": "Thermostat",
          "state": {
            "lastupdated": "none",
            "on": null,
            "temperature": null
          },
          "swversion": "20160824eCozy930",
          "type": "ZHAThermostat",
          "uniqueid": "70:b3:d5:de:00:00:14:08-03-0201"
        },
```

**Comment by ebaauw** [comment]
OK, got the TRV linked to my test network.  Haven't yet installed it onto a radiator.  Did manage to link it to a SmartThings multi-sensor for remote temperature sensing.  After setting _Remote Sensing_ to 0x01, the current temperature shows -32768, but after receipt of the first attribute report from the SmartThings, it reflects the temperature reported by that device.  Incidentally, the SmartThings seems happy with two bindings from the _Thermostat_ cluster: one to the TRV and one to RaspBee.

I don't think the attribute reporting config for _Local Temperature_ and _PI Heating Demand_ make much sense.  I need to check if these are the factory default settings, or settings made by the API plugin.

The TRV seems to keep time, but seems to lack the ability to sync its clock.  I would expect a client _Time_ cluster for that.  It starts counting from Jan 1, 2000 after reset.  Haven't yet tried writing the time, GUI doesn't allow writing a `utc` data type.

The thermostat seems to support on-device schedules, but there seems something wrong in the REST API plugin implementation, causing deCONZ to hang.  Probably need to play with the CLI plugin first to understand these.

**Comment by ebaauw** [comment]
> I don't think the attribute reporting config for Local Temperature and PI Heating Demand make much sense. I need to check if these are the factory default settings, or settings made by the API plugin.

With my latest PR, the deCONZ REST API plugin sets up the attribute reporting correctly.

Still working on full support for the eCozy in deCONZ.  After that, I want to see if I can support managing the on-device schedules from Eve.  Leaving this issue open for that.

**Comment by ebaauw** [comment]
Cannot seem to keep the eCozy TRV reliably in the deCONZ network.  Tried a network with the gateway device as only router, and still no joy.
