### ISSUE TITLE
All Homebridge-Hue accessories gone/reset

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-hue#729]
Just noticed all my Homebridge-Hue accessories had disappeared from HomeKit. 

Checked the Phoscon app and everything seemed up and running, so I restarted Homebridge and they've all reappeared but now need placing back in the correct rooms and adding back into various scenes.

I've not changed anything or updated anything.  Any suggestions as to how this may have happened?

Thanks

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/issues/471.

**Comment by fullphat** [comment]
I checked out that issue, but my problem is more wide-ranging.  I have about 10 temperature sensors and they all disappeared as well?

Also, I didn't reboot or restart the deCONZ gateway at all (unless it did that without me knowing).

**Comment by ebaauw** [comment]
Homebridge Hue cannot delete accessories while running; this is technically impossible for static platform accessory plugins.  The accessories are (re-)created when Homebridge starts, before the HAP server starts.  Homebridge Hue delays the startup of the HAP sever, until all bridges/gateways specified in `hosts` have been connected to or when at least one bridge has been discovered.  If a `lightlist` resourcelink is present, it waits for the lights in that list to be exposed.  The “something bad” must have been a restart of Homebridge while deCONZ was unavailable or not yet exposing all resources.

**Comment by fullphat** [comment]
Thanks, but just trying to avoid it happening again.  If I know what went wrong I can try to avoid it in the future 😃

**Comment by ebaauw** [comment]
> Any way to tell if either deCONZ or Homebridge crashed or rebooted? Any persistent logs I can check?

That really depends on how you installed these, and is beyond the scope of Homebridge Hue.

> If I know what went wrong I can try to avoid it in the future

Set `hosts` in config.json and create a `lightlist` resource link.

> Not suggesting it's the plugin that's causing the issue

It's a combination of a deCONZ bug and the use of static platform accessories by Homebridge Hue, see #4.
