### ISSUE TITLE
warning api version log

### ISSUE THREAD

**Issue by jojost1** [ebaauw/homebridge-hue#73]
I get this log since the last update:

> [2017-3-1 23:19:44] [Hue] Bridge Joost: BSB002 bridge, api v1.17.0
> **[2017-3-1 23:19:44] [Hue] Bridge Joost: warning api version 1.17.0**

Homebridge-hue seems to work fine, what does this log mean and how to resolve it? :)

**Comment by ebaauw** [comment]
Apparently your Hue bridge firmware has been updated and now your bridge now provides v1.17.0 of the Hue API.

**Comment by ebaauw** [comment]
I'm now seeing the Hue bridge firmware update for my v2 bridge, but not yet for my v1 bridge.  Looking at the [Hue API change log](https://developers.meethue.com/documentation/changelog), homebridge-hue shouldn't have any issues with 1.17.0.

**Comment by jojost1** [comment]
Ah, good. Why does it give the 'warning' in red? Any particular reason for it?

**Comment by ebaauw** [comment]
So that some-one would notice, raise an issue, and alert me of the new version ;-)

Technically, I issue a `log.error()` which homebridge paints red automagically.

**Comment by ebaauw** [comment]
v0.3.9 no longer gives the warning.
