### ISSUE TITLE
How to use ph command to remove configuration

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-hue#731]
When homebridge-hue starts, I see this warning:

`[deCONZ] Conbee2: /sensors/33: warning: ignoring unknown ZHASwitch sensor [....]`

And I end up with an invalid "lumi.ctrl_neutral1 33" accessory in the Home App.

I think all this is linked to a failed attempt to get an Aqara wall switch to work. 😀 I removed the switch from the Phoscon app, but it could be that some of the configuration has been left behind.

If I run 'ph get /`

I see the following under `sensors`:

```
"32": {
      "config": {
        "battery": 100,
        "on": true,
        "reachable": true,
        "temperature": 2400
      },
      "ep": 1,
      "etag": "e8b7f17cd74ec29dfeacc93cd6646980",
      "lastseen": "2020-07-12T06:49:15.116",
      "manufacturername": "LUMI",
      "mode": 1,
      "modelid": "lumi.sensor_switch.aq3",
      "name": "Bedroom Switch",
      "state": {
        "buttonevent": 1003,
        "lastupdated": "2020-07-09T22:01:54.435"
      },
      "swversion": "20180629",
      "type": "ZHASwitch",
      "uniqueid": "00:15:8d:00:02:f2:40:55-01-0006"
    },
    "33": {
      "config": {
        "on": true,
        "reachable": false,
        "temperature": null
      },
      "ep": 4,
      "etag": "833e98440890320fbc0a4ba796d04da3",
      "lastseen": "2020-06-25T12:53:07.074",
      "manufacturername": "LUMI",
      "mode": 1,
      "modelid": "lumi.ctrl_neutral1",
      "name": "lumi.ctrl_neutral1 33",
      "state": {
        "buttonevent": 1002,
        "lastupdated": "2020-06-25T12:51:45.891"
      },
      "swversion": "04-25-2018",
      "type": "ZHASwitch",
      "uniqueid": "00:15:8d:00:04:51:55:e7-04-0006"
    },
```

How can I safely remove these?

Thanks!

**Comment by ebaauw** [comment]
These are valid sensor resources alright.  32 is for a wireless switch, 33 for a wired switch.  Homebridge Hue doesn’t support the ZHASwitch resource for the wired switch, probably because I never saw any use for it, as the button cannot be detached from the output wire.

You could delete the sensors using `ph delete /sensors/33`, but they’ll probably end up being re-created when you pair another device.  You can create a `blacklist` resourcelink to have Homebridge Hue ignore them, or simply ignore the warning.

**Comment by fullphat** [comment]
Thanks!  I physically removed the wall switch so it shouldn't re-appear.  I'll try deleting them and see if they come back. 👍

**Comment by fullphat** [comment]
Done and it's disappeared from the Home app 👍
