### ISSUE TITLE
Ikea Trådfri Dimmer

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-hue#732]
I understand this dimmer works with deCONZ and homebridge-hue, but could you explain how it's presented in HomeKit?  Does it appear as a statelessSwitch, or something else?  

Thanks!

**Comment by ebaauw** [comment]
Yes, as a four-button _Stateless Programmable Switch_.

The wireless dimmer is troublesome at best.  Make sure to update it to the latest firmware.  Still, I prefer the on/off remote (which also dims on hold).

**Comment by olliox** [comment]
Hi, is it possible to use the long press option (for button I or O) for dimming hue lights - via home-app? I was just able to set a value like 20% brightness for example but no dynamic dimming. Is there an option for that?

**Comment by ebaauw** [comment]
The Trådfri dimmer has no buttons, just a dial, and no presses.

**Comment by olliox** [comment]
![46355376-EF86-4BBC-8CAB-59F0029BA4C8](https://user-images.githubusercontent.com/63616086/91387753-37301f00-e836-11ea-8af5-1a88fba6155c.jpeg)
I thought it was about this dimmer. I think it has the dimming function by pressing the buttons long. They work with your plugin, but in homekit it shows 4 button options . button(I/O)  short/long press.

**Comment by ebaauw** [comment]
Ok, the on/off switch is exposed with two buttons, each supporting _Single Press_ and _Long Press_.  Normally they dim lights in the associated groups out-of-the-box, even when deCONZ isn’t running.  For more advanced automations, you an use deCONZ rules.  I wouldn’t recommend HomeKit automations to control Zigbee actuators from Zigbee controllers, but Homebridge Hue supports this.

Use the _Brightness Change_ characteristic to set relative brightness.  You need a decent HomeKit app for this, as Apple’s Home app doesn’t support custom characteristics.  Best create a scene in Eve, and assign that Scene to the button action in Home.

**Comment by fullphat** [comment]
I'm doing exactly this.  I have the Tradfri exposed as a switch via Homebridge-Hue and that then runs selected HomeKit scented:

I press: lights on 50%
I long-press: lights on 100%
O press: lights off
O long-press: lights on 25%

Works a treat.  Have one in the lounge and one on the landing.

**Comment by olliox** [comment]
> I'm doing exactly this. I have the Tradfri exposed as a switch via Homebridge-Hue and that then runs selected HomeKit scenes:
> 
> I press: lights on 50%
> I long-press: lights on 100%
> O press: lights off
> O long-press: lights on 25%
> 
> Works a treat. Have one in the lounge and one on the landing.

This already works in my setup too. But what I was looking for is the option to dim up (while pressing I long or dim the lights down while pressing O long) Not a fixed % value but a dynamic behavior. I will try the solution ebaauw commented before and will post my experiences here.

**Comment by martind1983** [comment]
@olliox any update on this one? having the same 'issue': 
"I will try the solution ebaauw commented before and will post my experiences here.
