### ISSUE TITLE
Feature request Xiaomi door and window sensor temperature

### ISSUE THREAD

**Issue by apfelflo89** [ebaauw/homebridge-hue#734]
#### Issue

Would it be possible to include and expose temperature values from Xiaomi door and window sensors, like working in 
Samjin (SmartThings) Multipurpose Sensors ?
Both sensors include a temperature sensor aswell so it would be nice to see both behave the same. 

#### Log Messages

```
```

#### Debug Files

![doortemp](https://user-images.githubusercontent.com/48082211/87717310-79cef800-c7b0-11ea-9c51-2901cc08dc84.png)
![doorsensor_xiaomi](https://user-images.githubusercontent.com/48082211/87717313-7a678e80-c7b0-11ea-8142-3f3bd1dea9b8.jpg)
![multisensor_smartthings](https://user-images.githubusercontent.com/48082211/87717316-7a678e80-c7b0-11ea-8a99-47476b02dd25.jpg)

**Comment by ebaauw** [comment]
No, see https://github.com/ebaauw/homebridge-hue/issues/657.
