### ISSUE TITLE
Aqara Temp/Humidity sensor not reporting Air Pressure

### ISSUE THREAD

**Issue by nukedrk** [ebaauw/homebridge-hue#735]
I have an Xiaomi Aqara Temperature and Humidity Sensor connected through a Raspbee II bridge running on HOOBS.  HOOBS can see the associated Temperature, Humidity and Battery accessories though homebridge-hue (and is passing them to HomeKit), but the Air Pressure accessory from the Aqara is not showing up.  The Air Pressure shows up on the Phoscon App, and It looks like homebridge-hue expects it , but I can't find it in HOOBS or through HomeKit.

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4940932/homebridge-hue.json.gz)
[logs.txt.zip](https://github.com/ebaauw/homebridge-hue/files/4940931/logs.txt.zip)

**Comment by ebaauw** [comment]
You are using a decent HomeKit app, aren't you?  Apple's Home app doesn't support _Air Pressure_.

From the dump:
```
        "4": {
          "config": {
            "battery": 100,
            "on": true,
            "reachable": true
          },
          "ep": 1,
          "etag": "a6c57e182866bf5cbcc288ad99c57ba5",
          "lastseen": "2020-07-18T01:22:48.486",
          "manufacturername": "LUMI",
          "modelid": "lumi.weather",
          "name": "Den Temp Sensor",
          "state": {
            "lastupdated": "2020-07-18T00:59:02.286",
            "pressure": 778
          },
          "swversion": "20161129",
          "type": "ZHAPressure",
          "uniqueid": "00:15:8d:00:02:38:c4:6b-01-0403"
        },
```
The pressure sensor reports 778 HPa.  Unless you live on Mount Everest, that seems ridiculously low but still within the range (700-1100) of the HomeKit characteristic.

You didn't run `homebridge -D`, so the log file doesn't contain any useful information.

**Comment by nukedrk** [comment]
I think the problem may have been a keyboard/screen short.  Air pressure does show up in Eve, so I think it is actually working.  I was mislead because it didn’t show up in the HOOBS device panel, though I assume this is a HOOBS issue, not homebridge-hue.  (I don’t use the HOOBS panel for anything, so it doesn’t really matter.)

The air pressure is reading low (we’re in the Mountains, but not Nepal); however, I don’t have a second one of these to check against, so, for now, I have to assume this is a hardware issue.

Thank you for the quick response.

Regards,
Jeff

Dr. Jeffrey C. King (kingjc@mines.edu<mailto:kingjc@mines.edu>)
Associate Professor
Department of Metallurgical and Materials Engineering
Director, Nuclear Science and Engineering Center
Manager, Hot Shop and Foundry
Colorado School of Mines



On Jul 18, 2020, at 4:34 AM, Erik Baauw <notifications@github.com<mailto:notifications@github.com>> wrote:



You are using a decent HomeKit app, aren't you? Apple's Home app doesn't support Air Pressure.

From the dump:

        "4": {
          "config": {
            "battery": 100,
            "on": true,
            "reachable": true
          },
          "ep": 1,
          "etag": "a6c57e182866bf5cbcc288ad99c57ba5",
          "lastseen": "2020-07-18T01:22:48.486",
          "manufacturername": "LUMI",
          "modelid": "lumi.weather",
          "name": "Den Temp Sensor",
          "state": {
            "lastupdated": "2020-07-18T00:59:02.286",
            "pressure": 778
          },
          "swversion": "20161129",
          "type": "ZHAPressure",
          "uniqueid": "00:15:8d:00:02:38:c4:6b-01-0403"
        },


The pressure sensor reports 778 HPa. Unless you live on Mount Everest, that seems ridiculously low but still within the range (700-1100) of the HomeKit characteristic.

You didn't run homebridge -D, so the log file doesn't contain any useful information.
