### ISSUE TITLE
Get lots of heartbeat xx, drift yyy messages in Homebridge log...

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-hue#737]
No homebridge-hue accessories working, getting lots of:

```
[7/19/2020, 22:17:49] [deCONZ] heartbeat 70, drift 10476
[7/19/2020, 22:17:49] [deCONZ] heartbeat 71, drift 9479
```

In the Homebridge log.  Help please!

**Comment by ebaauw** [comment]
Something is blocking NodeJS, causing the scheduled heartbeat to be delayed by over 10s.  Might be the system is overloaded, might be another plugin doing synchronous I/O.

**Comment by fullphat** [comment]
Thanks!  Rebooted Apple TV and that seems to have resolved everything.  Just checking now...

**Comment by fullphat** [comment]
Apple TV reboot seems to have fixed it.  Log messages in Homebridge gone - didn't even need to reboot Homebridge itself!

**Comment by mtressl** [comment]
> Something is blocking NodeJS, causing the scheduled heartbeat to be delayed by over 10s. Might be the system is overloaded, might be another plugin doing synchronous I/O.

Having the same problem since a couple of days. Everything is up-to-date: Homebride, Hue plugin, deCONZ. Also did a restart of the HomeKit hub (AppleTV). Still getting a lot of those messages.
```
[7/23/2020, 10:29:49 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3893, drift 781
[7/23/2020, 10:29:52 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3896, drift 1297
[7/23/2020, 10:29:52 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3897, drift 315
[7/23/2020, 10:29:56 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3899, drift 1795
[7/23/2020, 10:29:56 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3900, drift 818
[7/23/2020, 10:29:59 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3903, drift 1316
[7/23/2020, 10:29:59 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3904, drift 345
[7/23/2020, 10:30:03 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3906, drift 1839
[7/23/2020, 10:30:03 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3907, drift 874
[7/23/2020, 10:30:06 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3910, drift 1403
[7/23/2020, 10:30:06 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3911, drift 430
```
Any idea how to debug this further?

**Comment by ebaauw** [comment]
Monitor the system load to see if it's system related.

If not, selectively disable plugins to determine if one of those is causing this.

**Comment by mtressl** [comment]
It's not system load related, CPU is usually 3-5%. And if I do other stuff on the Pi and load goes to 20 or 30%, same drifts appear.
I am quite sure it all started when I upgraded deCONZ to 2.05.79 (latest).

**Comment by joebiber** [comment]
I too have this issue. I get hundreds of log messages very quickly. Any idea what could be causing ?

**Comment by mtressl** [comment]
Just as a remark, the latest update did not solve the `heartbeat xx, drift yyy messages` in the logs.

**Comment by ebaauw** [comment]
It isn't supposed to.  As I said before, the message indicates that the scheduled heartbeat is off by more than 0.5s.  NodeJS wasn't able to schedule the heartbeat at the appropriate time, either because its main event loop was blocked or because it didn't get enough system resources.  If this happens often, it could indicate there's a problem with another Homebridge plugin blocking NodeJS, or with your system being over loaded.

**Comment by mtressl** [comment]
Not to bother you, and maybe I just don't get it:
- system being over loaded > what values would you consider over load?
- plugin blocking NodeJS > would this appear in the logs, or could I investigate with debug log-level?

Thanks for your help @ebaauw !

**Comment by ebaauw** [comment]
> system being over loaded > what values would you consider over load?

That really depends on your system.  I'd track CPU and memory usage, and, on Unix-like systems, the load average.

> plugin blocking NodeJS > would this appear in the logs, or could I investigate with debug log-level?

That really depends on how detailed (debug) log messages that plugin issues.  Typically you don't get any hint in the log, that's why I issue the heartbeat drift warning messages.

**Comment by mtressl** [comment]
> I'd track CPU and memory usage, and, on Unix-like systems, the load average.
- homebridge-config-ui-x: Memory 0.9 GB (total), 0.44 GB (available), CPU 3-5% Load
- ssh to RaspberryPi -> top: load average: 2.56, 1.92, 1.77

So from what you are saying, the load average could point to something wrong. Correct?

**Comment by ebaauw** [comment]
I'm no performance specialist, but I understand that, generally speaking, you want the load average (# processes ready to be executed) below the number of cores in your system.  On a quad-core Pi 4B these values wouldn’t be a problem, but on a one-core Pi Zero they would.

Still these values seem rather high to me.  I run deCONZ, two Homebridge instances and some other stuff on a Pi 3B+ and its load average is well below 1.5, with the deCONZ GUI open, running `htop` in an `ssh` session.  CPU is around 20% and CPU temperature around 60°C.

On a Raspberry Pi, you also want to monitor whether it throttles the CPU frequency, see https://github.com/ebaauw/homebridge-rpi/wiki/Hardware-Monitoring.

It could also be a badly written Homebridge plugin blocking NodeJS, e.g. by doing synchronous I/O.

**Comment by mtressl** [comment]
Thanks @ebaauw - I will further investigate.
I have a Pi 3B+ as well, running one Homebridge instance and deCONZ, and a Transmission client. All through docker containers. Will report back if I find something.

**Comment by ebaauw** [comment]
Did you run `top` on the host or from one of the containers?  I suppose Docker could account for the higher load average.  I don't know, but I would think Homebridge Config UI X only shows data from the container.

**Comment by mtressl** [comment]
I did run `top` on the RPi host directly, right after ssh'ing to the PRi. I did some cleanup of my Docker, mainly getting rid of old and unused containers which were just sitting there and wasting space.

Now `top` (on host) gives me: `load average: 0.98, 1.03, 1.16` which compared to yesterdays result is much better (`load average: 2.56, 1.92, 1.77`), but still I have the heartbeat / drift log entries:
```
[8/3/2020, 11:57:42 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3950, drift 989
[8/3/2020, 11:57:46 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3953, drift 1540
[8/3/2020, 11:57:46 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3954, drift 570
[8/3/2020, 11:57:49 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3956, drift 2032
[8/3/2020, 11:57:49 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3957, drift 1076
[8/3/2020, 11:57:53 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3960, drift 1534
[8/3/2020, 11:57:53 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3961, drift 553
[8/3/2020, 11:57:56 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3964, drift 1041
[8/3/2020, 11:58:00 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3967, drift 1571
[8/3/2020, 11:58:00 AM] [Philips Hue & deCONZ (ZigBee)] heartbeat 3968, drift 619
```
Btw: is it strange to have Node running twice? Once by root, once by user pi?
```
29356 root      20   0  150872  34852  18916 S   5.3  3.7   1334:50 deCONZ                                                                                                                        
**14133 pi        20   0 1270804 165124  27560 S   3.6 17.4   6:09.98 node**                                                                                                                          
**14108 root      20   0  188304  80388  28388 S   2.3  8.5   2:42.87 node**                                                                                                                          
  367 avahi     20   0    7376   1612    920 S   1.3  0.2 352:52.25 avahi-daemon              
```

**Comment by ebaauw** [comment]
I have no idea what this would look like in a Docker environment.  I think Homebridge Config UI X's supervisor runs in a separate process, but I don't think it should be running as `root`.
