### ISSUE TITLE
Change of State of Wall switches

### ISSUE THREAD

**Issue by rickdhoy** [ebaauw/homebridge-hue#742]
#### Issue

HI,

I am having an issue with he state changes on all my wall switches.

They are:
Manufacturer | 3A Smart Home DE
Model | LXN-1S27LX1.0
Zigbee 3.0

So when I manually turn the switches on and off it is not changing the state in Apple HomeKit app.

The states change when controlled by HomeKit or with the Philips Hue app.

Any suggestions please as I am trying to get some automations working when a switch is manually activated so I can turn it off after a time lapse.

Thank you.

p.s. I am running the homebridge instance on a Rasperry PI 4, using Homebridge Config UI X with the latest versions of Homebridge, and all plugins are up to date.

#### Log Messages

```
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4976952/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Does the Hue app reflect the state change when you manually change the switch?  Does HomeKit reflect the new state after a while (up to a minute)?

Normally, these type of switches should send a _Report Attributes_ to the gateway when controlled manually.  However, the Hue bridge doesn’t set this up, as Hue devices don’t support this.  Hue is based on the principle that all devices are controlled exclusively by the Hue bridge.  The bridge should poll devices to reconcile the cached state in the Hue bridge with the actual device state.  How frequently this happens depends on the number of devices in your network.
