### ISSUE TITLE
Osram Outlet

### ISSUE THREAD

**Issue by electromitter** [ebaauw/homebridge-hue#743]
Hi,

Is it possible to change the symbols of an  Osram Outlet to a Waterpump?
I switch may Poolfilter with an Osram Outlet and it would be nice to change the symbol.

Thanks Gregor

**Comment by ebaauw** [comment]
Create a `valve` resourcelink to expose the linked `/lights` resource as _Valve_.  It even supports the remaining time and switching off automatically.

**Comment by electromitter** [comment]
is it only possible to make a valve resourcelink?

**Comment by ebaauw** [comment]
Yes.

**Comment by electromitter** [comment]
ok thanks
