### ISSUE TITLE
Sensor and Host Problem

### ISSUE THREAD

**Issue by clipse2004** [ebaauw/homebridge-hue#744]
Hello,
so first of all great work!
However, I cannot cope with two things where I briefly need your help. (I use HUE Bridge V2 and Deconz)

1. I have various sensors / switches:
"CLIP sensor PUSHDIM-TOOGLE-ON-OFF",
"VPIR movement",
"FSM_STATE",
"Motion Sensor 13 Activity State"
I just can't get them not to show up in HomeKit! I tried exlude Sensor, no chance and I can't quite manage the blacklist either.
How do I insert this correctly into the existing config?

2. The other problem is the hosts. I register:
"hosts": "192.168.178.XX: 80", "192.168.178.XX"
and always get a message with not value.
: /

I hope you can help me.

Big thanks!

**Comment by ebaauw** [comment]
Make sure you use a text editor to edit config.json, not some document editor that replaces the quotes.  Make sure to use a json validator.  Easiest is using Homebridge Config UI X.

Note that the keys are case sensitive.   See https://github.com/ebaauw/homebridge-hue/wiki/Configuration for an overview of all keys.

Both `hosts` and `excludeSensorTypes` take an array value.  Also, make sure there’s no space between the ip address and the `:`.

**Comment by clipse2004** [comment]
Yes it worked :) 

big thanks!!
