### ISSUE TITLE
add donation links

### ISSUE THREAD

**Issue by b2un0** [ebaauw/homebridge-hue#746]
hey,

you should add donation links to your project

https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Donation-Links

https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by ebaauw** [comment]
Thanks, working on that (onzu pinged me on Discord the other day).

**Comment by ebaauw** [comment]
In v0.11.75.
