### ISSUE TITLE
Hide Motion Sensor Lightgroup 

### ISSUE THREAD

**Issue by timwegenerDE** [ebaauw/homebridge-hue#747]
Hi there,

when adding a Motion Sensor (e.g. IKEA Tradfri) DeConz is creating a (Light-)Group for the sensor. In the Phoscon UI it's not even visible (so also I can't delete the group). But I'm exposing all of my lights as groups so the motion sensor group gets also exposed as Light. Because I will add more and more motions sensors over time it will become annoying. 

It would be great if I could disable the exposure of groups with only a motion sensor in it.

**Comment by ebaauw** [comment]
> But I'm exposing all of my lights as groups

That's not possible.  I think you mean: you're exposing all groups as lights.

> It would be great if I could disable the exposure of groups with only a motion sensor in it.

The motion sensor cannot be "in a group".  It's the group associated to the motion sensor; the motion sensor has a binding to the group, so it sends commands to that group.

To selectively expose groups use a `blacklist` resourcelink to prevent Homebridge Hue from exposing individual groups, or alternatively, unset `groups` in config.json and use a `whitelist` resourcelink to indicate which groups you want to expose.  See https://github.com/ebaauw/homebridge-hue#configuration.

**Comment by timwegenerDE** [comment]
I'm grouping all my (physical) lights and expose the groups - That's what I meant :)

Could you give me an example where to add these resourcelinks-block in the config.json?

Thank you! :)

**Comment by ebaauw** [comment]
You don't add them to config.json; you create them using the API on deCONZ.  Do a POST to `/resourcelinks` with a body as listed in the README.

**Comment by timwegenerDE** [comment]
Thanks, worked! 👍 

I think for a "regular" user it has to be easier to hide single devices or groups... What do you think?

**Comment by ebaauw** [comment]
I think this is an advanced user feature.  You need to understand REST resources and the way Homebridge Hue exposes these, as HomeKit accessories, services, and characteristics.  The structure to specify this in config.json will be too complex for a regular user, leading to even more support questions.
Ideally, there would be a configurator UI for Homebridge Hue, where you can scroll through all resources and indicate if and how to expose each.  One of the reasons I’m into HomeKit is that I don’t like to develop UIs.  I’ve been fantasising about exposing this through HomeKit, but that’s a hell load of work and the result will be awkward.

**Comment by timwegenerDE** [comment]
You are right. Also it’s not only a hue specific requirement; maybe it‘s something for homebridge itself or homebridge config ui.
