### ISSUE TITLE
Question regarding Ubisys J1 Window covering device via deCONZ

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-hue#748]
Hello, 

I'm using an Awning with a Ubisys J1 controller via deCONZ REST-API. Works great so far but I have 2 questsions:

1. on homebridge start there is a warning:

[8/17/2020, 07:37:10] [Hue] warning: latest version: homebridge-hue v0.11.75
[8/17/2020, 07:37:10] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.5.79
[8/17/2020, 07:37:10] [Hue] Phoscon-GW: /sensors/34: warning: ignoring unknown ZHASwitch sensor {"config":{"mode":"rocker","on":true,"reachable":true,"windowcoveringtype":5},"ep":2,"etag":"34f96eb562d9624b03d1f5964c51145a","lastseen":"2020-08-17T05:36:54.933","manufacturername":"ubisys","mode":1,"modelid":"J1 (5502)","name":"J1 (5502) 34","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"20200429-DE-FB0","type":"ZHASwitch","uniqueid":"00:1f:ee:00:00:00:51:4a-02-0102"}

Is it safe to just ignore that? (deCONZ creates one light and 3 sensors for the J1)

2. once the open or close command is sent its impossible to stop it. Clicking the icon again in the home app stops for a short time but continues right after that. In deCONZ there is a "stop" command which works. Is this something that can work or is it impossible to do in homekit?

**Comment by ebaauw** [comment]
Ad 1: yes.  I’m not familiar with the J1, but I understand that one of the sensors is needed to calibrate and configure the J1.  I don’t think they have another function?

Ad 2: That’s yet another limitation of the Home app.  You might want to try another HomeKit app; e.g. in Eve you get a _Stop_ button.

**Comment by jan666** [comment]
Thanks. I think we can just close the issue then.

Just for info if you care: I used the sensor 34 to do the calibration (and set the mode to "rocker").

```
{
  "config": {
    "mode": "rocker",
    "on": true,
    "reachable": true,
    "windowcoveringtype": 5
  },
  "ep": 2,
  "etag": "34f96eb562d9624b03d1f5964c51145a",
  "lastseen": "2020-08-17T05:58:02.230",
  "manufacturername": "ubisys",
  "mode": 1,
  "modelid": "J1 (5502)",
  "name": "J1 (5502) 34",
  "state": {
    "buttonevent": null,
    "lastupdated": "none"
  },
  "swversion": "20200429-DE-FB0",
  "type": "ZHASwitch",
  "uniqueid": "00:1f:ee:00:00:00:51:4a-02-0102"
}
```

The other 2:

```
{
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 3,
  "etag": "2cd10738545f34f926c46263057d721c",
  "lastseen": "2020-08-17T05:58:38.190",
  "manufacturername": "ubisys",
  "modelid": "J1 (5502)",
  "name": "Consumption 35",
  "state": {
    "consumption": 18,
    "lastupdated": "2020-08-17T05:58:38.190",
    "power": 0
  },
  "swversion": "20200429-DE-FB0",
  "type": "ZHAConsumption",
  "uniqueid": "00:1f:ee:00:00:00:51:4a-03-0702"
}
```

```
{
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 3,
  "etag": "06aefa4e213cb19e16f4a02b39665fc6",
  "lastseen": "2020-08-17T05:58:58.323",
  "manufacturername": "ubisys",
  "modelid": "J1 (5502)",
  "name": "Power 36",
  "state": {
    "current": 0,
    "lastupdated": "2020-08-17T05:58:42.656",
    "power": 0,
    "voltage": 232
  },
  "swversion": "20200429-DE-FB0",
  "type": "ZHAPower",
  "uniqueid": "00:1f:ee:00:00:00:51:4a-03-0b04"
}
```

There was something in the homebridge log (which I already deleted) about power consumption.

**Comment by ebaauw** [comment]
Ah, of course, the ZHAConsumption and ZHAPower sensors.  I think Homebridge Hue supports these?

**Comment by jan666** [comment]
I dont see anything new in the home app. There is just the "light"

**Comment by ebaauw** [comment]
Thanks for the info.
