### ISSUE TITLE
Hue Bridge dependency needs updating

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-hue#749]
#### Issue

Hue plugin complains about old Hue bridge api version
However Hue bridge api version is up to date
Hue plugin dependencies need updating

#### Log Messages

```
[8/17/2020, 18:41:02] [Hue] Philips hue: Philips BSB002 bridge v1940042020, api v1.40.0
[8/17/2020, 18:41:02] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.38.0
```

**Comment by ebaauw** [comment]
Still no release notes for the firmware version nor any change log for the API version.  Did you notice anything odd or broken?

They did post a breaking change warning in v1.40.0 for the Hue Beyond, but I suppose their price is way out of reach for anyone using Homebridge.
