### ISSUE TITLE
Remote turn off of Heiman smoke sensor?

### ISSUE THREAD

**Issue by Stefan-83** [ebaauw/homebridge-hue#753]
Hi,

Is it possible with this plugin to turn off the alarm (e.g. false alarm) remotely?

Thanks 
Stefan

**Comment by ebaauw** [comment]
Does the sensor even support that?

**Comment by Stefan-83** [comment]
I would think so, when I'm reading the manufacturers website:
![image](https://user-images.githubusercontent.com/52136837/91631542-94fd6c00-e9da-11ea-80d5-c5fb781a6670.jpeg)

**Comment by ebaauw** [comment]
Last time I checked, the siren couldn’t be activated (nor deactivated) over Zigbee.  I’m not sure about resetting the alarm condition, it needs to be exposed by the deCONZ REST API, before Homebridge Hue can support it.  I had a loaner a couple of years ago, maybe they added these features in later (firmware) revisions.  I don’t think they have a native hub and corresponding app that could be sniffed?

**Comment by ebaauw** [comment]
They do seem to have a native gateway and corresponding app.  I would appreciate the sniffer logs if any who has the gateway can sniff what it sends to the sensor when silencing the alarm.
