### ISSUE TITLE
Problem with Aqara Opple 6 Button Edition

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#754]
Hello,

the Opple switch does not react in Homekit and the battery is displayed as 0%.

I am on the latest homebridge and homebridge-hue version. deconz is on 2.05.80, Firmware 26350500.

This is my config:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:89",
		"manufacturer": "homebridge.io",
		"model": "homebridge",
		"port": 51889,
		"pin": "031-45-154"
	},
	"description": "Phoscon",
	"platforms": [{
		"platform": "Hue",
		"host": "192.168.178.98",
		"users": {
			"yyyyyyyy": "xxxxxxxx"
		},
		"sensors": true,
		"nativeHomeKitSensors": false,
		"excludeSensorTypes": ["CLIPPresence", "Daylight", "Geofence"],
		"lights": true
	}],
	"accessories": []
}

@ebaauw 

Have you any ideas?

Greets Manuel

**Comment by Kohle81** [comment]
![CFEE794F-2BDD-4E42-8A60-8E5C4E2FECCE](https://user-images.githubusercontent.com/33038709/91635160-6097a900-e9f6-11ea-986d-16f316832c57.png)
![Uploading A9ED8A5D-7F3A-43D7-B19E-8B5650F747B7.png…]()

**Comment by Kohle81** [comment]
![26904492-BBA8-43C6-890E-A7A5987FF4B0](https://user-images.githubusercontent.com/33038709/91635165-668d8a00-e9f6-11ea-9096-695237e9c891.png)

**Comment by Kohle81** [comment]
![600D7E9D-7DEE-421D-8996-85D62A7F9795](https://user-images.githubusercontent.com/33038709/91635174-7e650e00-e9f6-11ea-8b10-bb516ea6193c.png)

**Comment by ebaauw** [comment]
Does the REST API show any change when you press a button?  If so, please capture and attach a debug log file, and also attach the debug dump file.  If not, the issue is with deCONZ.

**Comment by Kohle81** [comment]
29 14:08:45] Loading 1 platforms...
Aug 29 14:08:45 phoscon homebridge[17752]: [2020-8-29 14:08:45] [Hue] Initializing Hue platform...
Aug 29 14:08:45 phoscon homebridge[17752]: [2020-8-29 14:08:45] [Hue] homebridge-hue v0.11.75, node v12.18.3, homebridge v1.1.2
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.80, api v1.16.0
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.5.79
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] [Hue] Phoscon-GW: 4 accessories
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] Initializing platform accessory 'Phoscon-GW'...
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] [Hue] Phoscon-GW: 2 services
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] Initializing platform accessory 'Multisensor'...
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] Initializing platform accessory 'OPPLE Schalter 3-fach'...
Aug 29 14:08:46 phoscon homebridge[17752]: [2020-8-29 14:08:46] Initializing platform accessory 'Dimmschalter'...
Aug 29 14:08:46 phoscon homebridge[17752]: Setup Payload:
Aug 29 14:08:46 phoscon homebridge[17752]: X-HM://0023ISYWY1BHM
Aug 29 14:08:46 phoscon homebridge[17752]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ebaauw** [comment]
Did you press the buttons while capturing the log file?  Please enable DEBUG mode in Homebridge.  Please also attach the dump file.

**Comment by Kohle81** [comment]
The fault was probably with deconz.  apparently the switch was not recognized correctly.  I removed it again and added it again, now everything is fine. 🙈👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
