### ISSUE TITLE
Uninstall homebridge-hue ?

### ISSUE THREAD

**Issue by leovj** [ebaauw/homebridge-hue#755]
I installed the Homebridge Hue plugin on HOOBS. I uninstalled it, but the HOOBS log keeps telling me:

1/9/2020, 08:19:58 [Hue] no bridges or gateways found - retrying in 30 seconds1/9/2020, 08:19:58 [Hue] searching bridges and gateways

Why?
Thanks

**Comment by ebaauw** [comment]
Dunno.  Please contact HOOBS support for issue on HOOBS.
