### ISSUE TITLE
Feature Request: "wallSwitch" per device?

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-hue#756]
It would be great if we could set "wallSwitch" per device, not just once for all devices. I saw #80 and #92 and I have both "problems" as I have some lights I turn on and off via wallSwitch but have a few Osram Lightify Plug.

**Comment by ebaauw** [comment]
I strongly recommend agains using wall switches, but you can use a `wallswitch` resourcelink to list the individual `/lights` resources.

**Comment by jan666** [comment]
Ah, wallswitch + resourcelink leads to #387. I think I can figure it out reading this - thanks.

I'd love to not use wall switches, but I have not yet found a good replacement for them that keeps the abilty to power-cycle the lights from time to time without power cycling the whole floor...
