### ISSUE TITLE
unknown light model

### ISSUE THREAD

**Issue by h0mesmart** [ebaauw/homebridge-hue#757]
#### Issue
After adding a zigbee RGB Led strip controller model n° YSR-MINI-Z01 I got in the log this warning. I've noticed the green and
blue is reversed. 

#### Log Messages

```
Hue] Philips hue: /lights/31: warning: using default colour gamut for unknown light model {"state":{"on":false,"bri":254,"hue":55040,"sat":86,"effect":"none","xy":[0.3296,0.3219],"ct":379,"alert":"select","colormode":"xy","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-08-25T08:33:28"},"type":"Extended color light","name":"Bande Lumineuse","modelid":"FB56-ZCW20FB1.2","manufacturername":"FeeBit  RGBW    ","productname":"Extended color light","capabilities":{"certified":false,"control":{"colorgamuttype":"other","ct":{"min":210,"max":234}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"huelightstrip","function":"mixed","direction":"omnidirectional"},"uniqueid":"00:12:4b:00:1f:87:7a:46-0b","swversion":"1.0.0"}
```

#### Debug Files
[homebridge.log.txt](https://github.com/ebaauw/homebridge-hue/files/5175725/homebridge.log.txt)
[homebridge-hue.json-2.gz](https://github.com/ebaauw/homebridge-hue/files/5175726/homebridge-hue.json-2.gz)

Thanks for any help

**Comment by ebaauw** [comment]
Homebridge Hue doesn’t drive the channels; the controller firmware does.  Most likely you mixed the wires, or the controller mixed the labels.
