### ISSUE TITLE
Lights are missing (Conbee II)

### ISSUE THREAD

**Issue by Stefan-83** [ebaauw/homebridge-hue#758]
Hi,
i'm using Conbee II at my raspberry. After I changed the ports of deCONZ, all lights are gone missing in HomeKit. My 15 Sensors are all available. 
I've tried to restart my homebridge several times.

`
[9/4/2020, 18:24:25] [Hue] ZigBee: dresden elektronik deCONZ gateway v2.5.78, api v1.16.0
[9/4/2020, 18:24:25] [Hue] ZigBee: 15 accessories
`

Is this the same issue like: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/97 ?

I'm using the Gateway version: 2.05.78
Is this fixed in the newer (beta-)version?

Or is there another workaround?

Thanks,
Stefan

**Comment by ebaauw** [comment]
I think it is.  If you restart Homebridge a couple of minutes after starting deCONZ, you should see the lights again.  Use a `lightlist` resourcelinks to have Homebridge Hue delay the Homebridge startup, until all linked lights are available.

**Comment by Stefan-83** [comment]
hm, i did several restarts hours after I restarted the deconz service - still no lights available.

But I noticed, that there two instances of deconz running?
```
pi@homebridge:~ $ systemctl restart deconz.service
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to restart 'deconz.service'.
Multiple identities can be used for authentication:
 1.  ,,, (pi)
 2.  root
Choose identity to authenticate as (1-2):

```
Which one is the correct one? 
Should I deactivate one?

Thanks again,
Stefan

**Comment by ebaauw** [comment]
> But I noticed, that there two instances of deconz running?

That could explain the missing lights.  The device can only be connected to one instance.  For help on deCONZ, please see the deCONZ GitHub repository or Discord.

**Comment by Kristian8606** [comment]
> Използвайте `lightlist`връзки към ресурси, за да накарате Homebridge Hue да забави стартирането на Homebridge, докато не са налични всички свързани светлини.

Is it possible to add a timer to slow down the start without having to use a  `lightlist`, it will be easier for the average user.

**Comment by ebaauw** [comment]
Sure.  You have to setup a timer service to delay starting Homebridge after boot.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1535#issuecomment-520122255 as an example how they did that for deCONZ, to give the system time to start the graphical environment.

Not sure I would recommend this approach.  I'm not sure what value I would use for `OnBootSec`.  The delay before deCONZ shows the `/lights` resources varies greatly between versions;   Worst I've seen is 20 minutes (which was due to another bug).

> it will be easier for the average user.

I doubt that.

**Comment by Stefan-83** [comment]
hm, i'm still wondering why the lights are missing.... (while all sensors are available)

**Comment by ebaauw** [comment]
On startup, the REST API plugin re-creates sensor resources from the database.  It only re-creates light resources after the deCONZ core has re-created the corresponding node.  I think the core only does that after connecting to the RaspBee or ConBee and joining the network.

**Comment by Stefan-83** [comment]
Hm, and is it possible to start the recreation process of the node (manually)?
Or when does that happen?

**Comment by ebaauw** [comment]
Please restart Homebridge.  If the lights don’t show after that, please attach the debug dump file.

**Comment by simplenotezy** [comment]
@ebaauw how come you keep closing this issue? It's obviously a major fault in the app, whether it be this codebase or a dependency. This library ought to have a big warning sign: "Please be aware that lights will be missing if your server should restart/power cycle for ANY reason and you will have to set up all your scenes again in Homekit"

![image](https://user-images.githubusercontent.com/3786627/108274882-cbd86180-7175-11eb-88f0-4eeda6afb5e2.png)
