### ISSUE TITLE
Hue bridge listed a second time and not compatible with homekit

### ISSUE THREAD

**Issue by lcorsini** [ebaauw/homebridge-hue#76]
Don't know if this is a config issue or a wanted behaviour but, it seems that homebridge exposes the Hue bridge as an Accessory incompatible with Home named Philips Hue in Default Room. 

I installed homebridge to be able to use an Osram Lightify Plug which is not compatible with HomeKit
I've been able to do that using this configuration

`"platforms": [
        {
            "platform" : "Hue",
            "name" : "Hue",
            "users": {
                        "XXXXXXXXX": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                     },
            "host": "192.168.1.191",
            "lights": "true"
        }
`

It works, I can add it to home app and see only my plug
but when I pair Homebridge it also lists a second accessory, that is the hue bridge

`[3/4/2017, 6:07:48 PM] [Hue] Initializing Hue platform...
[3/4/2017, 6:07:48 PM] [Hue] homebridge-hue v0.3.9, node v6.10.0, homebridge api v2.1
[3/4/2017, 6:07:49 PM] [Hue] Philips hue: BSB002 bridge, api v1.16.0
[3/4/2017, 6:07:49 PM] [Hue] Ventola: warning: OSRAM: unknown Plug 01 light model
[3/4/2017, 6:07:49 PM] [Hue] Philips hue: 2 accessories
[3/4/2017, 6:07:50 PM] [Hue] Initializing platform accessory 'Philips hue'...
[3/4/2017, 6:07:50 PM] [Hue] Philips hue: 2 services
[3/4/2017, 6:07:50 PM] [Hue] Initializing platform accessory 'Ventola'...
`

I don't need it because it's already defined as bridge by the hue app, I put it into default but I'm asking if it can be avoided

**Comment by ebaauw** [comment]
The bridge accessory is compatible with HomeKit, it's the iOS built-in Home app that doesn't support it.  In another HomeKit app, like Eve, you can use it to control the heartrate, the interval homebridge-hue uses for polling the Hue bridge.  Also, for debugging, it dumps the Bridge state on Identify.  It cannot be disabled.

I'm not sure what you mean by "listed a second time"?

> [3/4/2017, 6:07:49 PM] [Hue] Ventola: warning: OSRAM: unknown Plug 01 light model 

That's interesting, my OSRAM plugs show model `Plug - LIGHTIFY`.  Could you please do a GET of  `/lights/#` (where `#` is the number for the plug) in the API debugger and post the response (below is what my plug looks like)? 

```
{
  "state": {
    "on": false,
    "alert": "none",
    "reachable": true
  },
  "type": "On/Off plug-in unit",
  "name": "Living Room Fan",
  "modelid": "Plug - LIGHTIFY",
  "manufacturername": "OSRAM",
  "uniqueid": "84:18:26:00:00:05:73:6b-03",
  "swversion": "V1.03.21"
}
```

**Comment by lcorsini** [comment]
Listed two times I mean that when I add homebridge to my Home App I get another Philips Hue Object listed as not compatible  with and when I look at the properties I see that is the same Philips Hue Bridge that is working and already added in another room
The only difference is that the hue hub added has the same model number BSB002, but the serial number is the USERNAME listed in config file

Here you can see my room with the Hue bridge that I added before running Homebridge, and Homebridge itself
![hue_correct](https://cloud.githubusercontent.com/assets/1501930/23586533/5afb8070-0197-11e7-9dd3-7c58d40e1e80.PNG)

Here the accessory that gets added when I add Homebridge to my home
![hue_incompatible](https://cloud.githubusercontent.com/assets/1501930/23586542/8d00d52a-0197-11e7-8f7d-35639237713e.PNG)

As you can see in HomeBridge properties it lists 2 accessories
![homebridge_properties](https://cloud.githubusercontent.com/assets/1501930/23586544/9fa51704-0197-11e7-9956-a6caec38c413.PNG)

But if I look in accessories details I find only my plug
![accessories_detail](https://cloud.githubusercontent.com/assets/1501930/23586547/bc260bf4-0197-11e7-83be-bc8be8ea9310.PNG)


As for the plug, I'll look how to use the API debugger (first time I work with node and homebridge) to extract the info you need
JFYI the plug has never been paired with a lightify bridge (because I don't own any) but only with Hue (so maybe there is an old firmware)

**Comment by ebaauw** [comment]
Ah, I see.  Yes, this is confusing, there's a difference between the Hue bridge and a HomeKit bridge.

- The first Philips hue accessory (in Studio) has nothing to do with home bridge.  It is exposed by the Hue v2 (square) bridge for the bridge itself.  This accessory is a HomeKit bridge, providing access to the accessories for the Philips lights connected to the Hue bridge.  These light accessories are exposed by the Hue bridge as well.
- The Homebridge accessory (in Studio) is created by homebridge itself.  This is a HomeKit bridge, providing access to the accessories created by homebridge plugins (like homebridge-hue) and exposed through homebridge.
- The second Philips Hue accessory (in Default) is created by homebridge-hue for the Hue bridge.  This accessory is not a HomeKit bridge, but a regular HomeKit accessory, bridged by the Homebridge accessory, just as the Bagno Ventola accessory.

> As for the plug, I'll look how to use the API debugger (first time I work with node and homebridge) to extract the info you need

Thanks!  The API debugger is a feature of the Hue bridge, see [Getting Started](https://developers.meethue.com/documentation/getting-started) on the Hue developer portal.  
I'm about to publish v0.3.10 of homebridge-hue.  This version will log the details of an unsupported light with the warning, so you wouldn't have to deal with the API debugger.

**Comment by lcorsini** [comment]
> The first Philips hue accessory (in Studio) has nothing to do with home bridge. It is exposed by the Hue v2 (square) bridge for the bridge itself. This accessory is a HomeKit bridge, providing access to the accessories for the Philips lights connected to the Hue bridge. These light accessories are exposed by the Hue bridge as well.
Right, and this was there already before I installed homebridge, and details every accessory connected to it (supported by Apple HomeKit)

> The Homebridge accessory (in Studio) is created by homebridge itself. This is a HomeKit bridge, providing access to the accessories created by homebridge plugins (like homebridge-hue) and exposed through homebridge.
Ok, and this is expected since is my "universal" bridge.

> The second Philips Hue accessory (in Default) is created by homebridge-hue for the Hue bridge. This accessory is not a HomeKit bridge, but a regular HomeKit accessory, bridged by the Homebridge accessory, just as the Bagno Ventola accessory.
And this the odd one, since it gets added as an accessory, which in fact isn't, so, it doesn't appear in accessory list (as you can see from the screenshot where it says 2 accessories, but in detail only the Ventola was present) and listed as non compatible in a room.
 to me, if I'm not missing something this shouldn't get advertised as accessory and shouldn't appear in HomeKit

> Thanks! The API debugger is a feature of the Hue bridge, see Getting Started on the Hue developer portal.
> I'm about to publish v0.3.10 of homebridge-hue. This version will log the details of an unsupported light with the warning, so you wouldn't have to deal with the API debugger.
Thanks I'm checking the Dev portal right now, always interested in study :)

**Comment by lcorsini** [comment]
> That's interesting, my OSRAM plugs show model Plug - LIGHTIFY. Could you please do a GET of /lights/# (where # is the number for the plug) in the API debugger and post the response (below is what my plug looks like)?

OK, different issue, but here it is

```
"5": {
		"state": {
			"on": false,
			"alert": "select",
			"reachable": true
		},
		"type": "On/Off plug-in unit",
		"name": "Ventola",
		"modelid": "Plug 01",
		"manufacturername": "OSRAM",
		"uniqueid": "84:18:26:00:00:0b:5c:3d-03",
		"swversion": "V1.04.12"
	}
```

**Comment by ebaauw** [comment]
> OK, different issue, but here it is

Thanks!  Your plug seems to have a later firmware version than mine.  Last time I checked, the OSRAM app reported no available firmware update for the plug, but I'll check again.  Anyway, I'll add `Plug 01` to the list of supported lights.

> I also checked inside the Hue app, and the plug model is empty

The Hue app seems to show the Model only for Philips lights.

**Comment by ebaauw** [comment]
> And this the odd one, since it gets added as an accessory, which in fact isn't

In HomeKit it is.

> it doesn't appear in accessory list (as you can see from the screenshot where it says 2 accessories, but in detail only the Ventola was present)

Indeed, another "feature" of the iOS built-in Home app: it hides accessories it doesn't support from the bridged accessories view.  I hadn't noticed this before.

>  if I'm not missing something this shouldn't get advertised as accessory and shouldn't appear in HomeKit

homebridge-hue keeps some configuration per Hue bridge.  This configuration is advertised as an accessory, so it can be viewed and changed from HomeKit (using other HomeKit apps).  Today, is this configuration is static, defined at startup time in `config.json`, with the exception of `heartrate`, and the accessory might seem superfluous.

However, once homebridge-hue will use the dynamic platform accessory model (see issue #4), most of the configuration per bridge will become dynamic, defined at runtime.  This will include the bridge username, so you no longer have to edit config.json to include it.  The accessory will be needed to persist the configuration between homebridge restarts.
