### ISSUE TITLE
IKEA Trådfri motion sensor - not reachable, fault state

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-hue#762]
I have a IKEA Trådfri motion sensor added to deCONZ. After 24 hours of not detecting anything it switches to "unreachable". That leads to the "fault" state in Home. Is it possible to ignore "not reachable" (maybe some magic resource link?)?

**Comment by ebaauw** [comment]
No.  Best check with deCONZ why it marks the sensor as `reachable` false.
