### ISSUE TITLE
Hide Temperature Hue Motion Sensor "excludeSensorTypes": ["ZHATemperature"] isn't working

### ISSUE THREAD

**Issue by mac89muc** [ebaauw/homebridge-hue#763]
#### Issue

Hello Eric, many thanks for your plugin. 
I'd like to hide the Temperature from the Hue Motion Sensors from my HomeKit setup because I've other Temperature Sensors that are more accurate than the Hue Motion Sensors.

I tried the steps you described it at several closed issues and at the wiki - but unfortunately I couldn't get it working. 

Neither the  "excludeSensorTypes": ["ZHATemperature"] ist working nor the "excludeSensorTypes": ["ZLLTemperature"]
The temperatures are still shown at the Home App

At the moment my config.json is looking like that

> {
>       "platform": "Hue",
>       "users": {
>         "abcedefghijklmno": "somepasscode"
>                 },
>       "name": "Hue",
>       "host": „192.168.xxx.xx",
>       "excludeSensorTypes": ["ZLLTemperature","ZHATemperature"],
>       "forceHttp": true,
>       "lights": true
>   },

Do you have a suggestion what the problem could be?

Regards
Christian
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5231708/homebridge-hue.json.gz)

#### Log Messages

```
```

**Comment by ebaauw** [comment]
With that config.json, you're not exposing any sensors through Homebridge Hue.  I think they're exposed natively by the Hue bridge?  Unfortunately, that's all-or-nothing, so the only way to achieve what you want is to remove the Hue bridge from HomeKit and to expose all devices, incl. Hue lights and sensors, though Homebridge Hue.

**Comment by mac89muc** [comment]
Hello Erik,

thank you for your fast reply.
If I delete the hue bridge from my homekit setup vis the home app and add it afterwards via the homekit plugin are my rules, scenes and names for the lamps gone, or they're still safed on the bridge and appearing unchanged after the transfer?

Regards

**Comment by ebaauw** [comment]
Hue bridge groups and scenes are actually Zigbee groups and scenes, and are stored in the lights non-volatile memory.  API resources are stored on the Hue bridge, incl. names, rules, schedules, etc.
Homekit groups, scenes, automations, room assignments and service and accessory names are stored in the HomeKit database on your iOS device(s), and are lost when you (temporarily) remove the corresponding accessory.
