### ISSUE TITLE
Heiman smoke sensor - no alarm in Homekit

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#764]
Hello Erik, I have integrated the Heiman smoke sensor into Homekit via deconz.  The sensor is also shown in Homekit as ready for use.  I was able to check the sensor with a test spray, it gave an alarm, but the status in Homekit was unchanged.  Have you or someone else tested this before in the event of an alarm?  Greetings Manuel

**Comment by ebaauw** [comment]
Does the deCONZ REST API show the alarm?  If so, please capture and attach a debug log file while triggering the alarm.  If not, most likely the _IAS Zone_ hasn’t been enrolled and you need to write the mac address of the RaspBee or ConBee to the _IAS_CIE_Address_ attribute in the deCONZ GUI.

**Comment by Kohle81** [comment]
Thanks for your tip, I want to have a look for it.

![D145BC3A-7459-476F-A937-AAFAE14B7F57](https://user-images.githubusercontent.com/33038709/93579093-5ab23980-f99e-11ea-83c5-b3d9c9d15e56.png)
![01960C69-8A93-4764-8D80-EF2D6AB9BE2B](https://user-images.githubusercontent.com/33038709/93579102-5dad2a00-f99e-11ea-8a19-31dda1477902.png)
![80C35CE7-4146-4893-ABAC-76A0019B326F](https://user-images.githubusercontent.com/33038709/93579107-5e45c080-f99e-11ea-8bec-f44815d84056.png)

Am I in the right direction at this point to enter the mac address?

**Comment by ebaauw** [comment]
Scroll down in the _Cluster Info_ panel to see the attributes.

**Comment by Kohle81** [comment]
Hi @ebaauw 

I have found the mac adress of the raspbee modul, 0x00212effff........


When I open the attribut editor to write the mac adress in the IAS_CIE_Adrr I get the message „writing failed“.

##I am writing the adress and click on the button „write“, but nothing happens......





<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ebaauw** [comment]
Make sure to wake the sensor.

**Comment by Kohle81** [comment]
How can I wake up the sensor?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ebaauw** [comment]
Briefly pressing the test button (cover your ears) or the reset button (hole).

**Comment by Kohle81** [comment]
> Does the deCONZ REST API show the alarm? If so, please capture and attach a debug log file while triggering the alarm. If not, most likely the _IAS Zone_ hasn’t been enrolled and you need to write the mac address of the RaspBee or ConBee to the _IAS_CIE_Address_ attribute in the deCONZ GUI.

Hi Erik, please excuse my ignorance and helplessness.  I was able to enter the MAC address on the smoke sensor.  However, no alarm is shown in homekit.  How can I check whether the deconz rest api is even receiving an alarm signal?  Unfortunately, I am not very familiar with deconz.  Greetings Manuel

![0D6A0C0E-76CA-4398-81F6-9667ED1D6FDD](https://user-images.githubusercontent.com/33038709/93719817-55631380-fb85-11ea-8a7f-d09a5a7aeeeb.png)

**Comment by Kohle81** [comment]
If I am pressing the test button, there is a accustic signal and in deconz the left led is blinking green.

![E2A58214-D8C0-474D-B706-678971105D64](https://user-images.githubusercontent.com/33038709/93719990-898b0400-fb86-11ea-8330-f52f61745d5f.jpeg)

**Comment by ebaauw** [comment]
The test button should trigger the alarm in the API and in HomeKit, for a few seconds.  However, the sensor still shows as _Not Enrolled_ in your latest screenshot.  It needs to be _Enrolled_ to send the _Zone Status Change Notification_ commands that the API plugin uses to update `state.fire`. 

Usually, writing the _IAS CIE Address_ is enough to enroll the device.  Not sure why it wasn’t now.  Maybe try again, or reset and re-pair the sensor.

**Comment by Kohle81** [comment]
Now it works, I have the Raspberry rebootet and the mac adress from the raspbee modul was not saved in deconz.
I have written the mac adress a second time and now it works 👍👍👍

Thank you Erik for your help and for the great work to your plugin. Can I spent you a coffee?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
