### ISSUE TITLE
Heiman Smoke Sensor - no Alarm in Homekit

### ISSUE THREAD

**Issue by Kohle81** [ebaauw/homebridge-hue#765]
Hello Erik, I have integrated the Heiman smoke sensor into Homekit via deconz.  The sensor is also shown in Homekit as ready for use.  I was able to check the sensor with a test spray, it gave an physical alarm, but the status in Homekit was unchanged.  Have you or someone else tested this before in the event of an alarm?  Greetings Manuel

**Comment by ebaauw** [comment]
See #764.
