### ISSUE TITLE
Modify device type

### ISSUE THREAD

**Issue by skelurr** [ebaauw/homebridge-hue#769]
Hello,

i have the plugin, with the conbee II in use.
Unfortunately the plugin (Aqara smart plug model: sp-euc01) is sent to the homebridge as a light bulb.
Is it possible to recognize these devices and identify them as plug sockets/switches or similar?
It would help me if I could make the change for the devices myself.

**Comment by ebaauw** [comment]
Create an `outlet` resourcelink.

**Comment by skelurr** [comment]
I'm sorry, but how do I do that?
I'm relatively new to the game and still have to learn how to do it.

**Comment by palletodap** [comment]
I have same question- How is this possible? Cant find documentation for this in the wiki page

**Comment by ebaauw** [comment]
You need to create a `resourcelink` resource using the API, linking the `/lights` resources you want to expose as _Outlet_ instead of _Lightbulb_.  You van use `ph outlet` as a start, but you’ll probably need to review and change the links.  There’s too many plugs that expose the wrong device type, breaking automated discovery of outlets.

**Comment by palletodap** [comment]
Thanks for the quick answer! Im a half newby doing this- How to i change the links if anything goes wrong? 🙃 Would it be possible to get an official guide to do this in the wiki page? I guess there's a lot having this problem 😄

**Comment by sUyMur** [comment]
For anyone who might stumble upon this and also struggled with it, I found [this thread on reddit](https://www.reddit.com/r/homebridge/comments/maaduy/has_anyone_successfully_changed_a_device_from/)
Basically:

- Press link button on phoscon (Gateway → Erweitert → App verbinden)
- Visit Homebridge website, open Homebridge terminal
- ph -H DECONZ_IP_ADDRESS:PORT createuser (and save resulting User = DECONZ_USERNAME)
- ph -H DECONZ_IP_ADDRESS:PORT -u DECONZ_USERNAME outlet -v 
- ph -H DECONZ_IP_ADDRESS:PORT -u DECONZ_USERNAME get /resourcelinks/1 
- Done.

Supplement DECONZ_IP / PORT with corresponding bridge IP and port (can also be hue bridge)
