### ISSUE TITLE
How to identify a temperature and lux sensors embedded in a hue motion sensor

### ISSUE THREAD

**Issue by ooii** [ebaauw/homebridge-hue#77]
Hi,
Once again, thanks for this great plugin.
I have 6 Hue motion sensors at home and each of them exposes one temperature and one lux sensors. However, these temperature and lux sensors have IDs ranging from 1 to 6 that do not allow to associate them with the motion sensors. Is there anyway to achieve that?
Thank you very much for your help.

**Comment by ooii** [comment]
Once I asked the question, as usual, I got an idea. I did a `GET` request on `/api/<username>/sensors` and was able, if I'm not wrong, to use `uniqueid` to identify sensors belonging to the same device.
In the `uniqueid`, the last part varies from `a8-02-0406` to `a8-02-0400`. I think that the common part (`a8-02-04` here) allows to identify the sensors.

**Comment by ebaauw** [comment]
Close.  For Zigbee devices, the unique ID seems to be made up of the Zigbee MAC address and the device type.  The MAC address is the 8 pairs of hex digits separated by colons, the device type is the part after the (first) dash.

In your example, the `02-406` indicates a `ZLLPresence` sensor, and `02-0400` indicates a `ZLLLightLevel` sensor.  The device type seems to be manufacturer specific; Philips uses `0b` for lights, OSRAM `03`, and innr `01`.

In your example, `a8` is the last byte of the MAC address, but in general, that won't identify fully the sensor.  You need to check the full MAC address.  Ranges of MAC addresses are allocated to a manufacturer.  The first three (or four, or five?) bytes in the MAC address indicate the manufacturer (`00:17:88` belongs to Philips), but a manufacturer might use multiple ranges.  

To see which Hue bridge resources correspond to which HomeKit service, homebridge-hue now exposes a custom characteristic `Resource` with each service.  Unfortunately, the iOS built-in home app doesn't show custom characteristics, but they show nicely in Eve or another HomeKit app.

**Comment by ooii** [comment]
Thanks @ebaauw 
I was trying with Eve and could not use it to identify light and temperature sensors.

One more question : what are "hue ambient light" and "current luminescence" measures? (I can ask the question somewhere else of course).

**Comment by ebaauw** [comment]
> I was trying with Eve and could not use it to identify light and temperature sensors.

What version of homebridge-hue are you on?  Here's what Eve 2.6 shows me for homebridge-hue v0.3.10:
![img_0005](https://cloud.githubusercontent.com/assets/22179355/23712837/5e5dd6ac-0424-11e7-89e2-a71cfdb10295.PNG)

> what are "hue ambient light" and "current luminescence" measures?

I think they're just used as fancy words fro "light level".  Where did you read them?  
The Hue app only allows you to name the ZLLPresence sensor of the Hue motion sensor.  I think it names the ZLLLightLevel sensor "hue ambient light 1", etc.  
I haven't come across "current luminescence", my guess would be an English to French back to English translation of "current light level".

**Comment by ooii** [comment]
@ebaauw, thanks for taking time to answer.
Indeed, after updating your plug-in to the latest version, I have the same behavior. I was setting everything together in the Home app where services belonging to the same device were not grouped in the same view like Eve does. It's easier with this latter.

About the difference between "hue ambient light" and "current luminescence", it is my mistake. "Current luminescence" is brought from Fibaro sensors via domoticz plugin. My bad.
