### ISSUE TITLE
Hiding "Philips hue" device

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#772]
Hi,

Today I lost my HomeKit mapping because my homebridge crashes.

After reconfiguring Homebridge-hue I can see a new device in the "Standard Room"... It is called "Philips Hue" and was exposed by the plugin.

Any idea how I can hide it? If I take a look to it I can see the last heartbeat state...timestamp...

Config:

"name": "Homebridge-Hue",
            "anyOn": true,
            "excludeSensorTypes": [
                "ZLLRelativeRotary",
                "ZLLPresence",
                "ZLLLightLevel",
                "ZLLTemperature",
                "ZHAHumidity",
                "ZHAPressure",
                "ZHAOpenClose",
                "ZHAAlarm",
                "ZHACarbonMonoxide",
                "ZHAFire",
                "ZHAVibration",
                "ZHAWater",
                "ZHAConsumption",
                "ZHAPower",
                "ZHAThermostat",
                "Daylight",
                "CLIPGenericFlag",
                "CLIPGenericStatus",
                "CLIPPresence",
                "CLIPLightLevel",
                "CLIPTemperature",
                "CLIPHumidity",
                "CLIPPressure",
                "CLIPOpenClose",
                "CLIPAlarm",
                "CLIPCarbonMonoxide",
                "CLIPFire",
                "CLIPVibration",
                "CLIPWater",
                "CLIPConsumption",
                "CLIPPower",
                "Geofence",
                "CLIP"
            ],
            "forceCt": true,
            "heartrate": 1,
            "timeout": 3,
            "hosts": [
                "192.168.0.50"
            ],
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,

Thanks!

**Comment by W3llenreiter** [comment]
From what I learned reading older issues here on GitHub this additional HUE hub seems to be required for additional features in 3rd party Homekit apps. Being a user of the defaule Apple Home app I would also appreciate if there was an option to add a line in the config file to hide this additional virtual hub in the Apple Home app..

**Comment by gizmotronic** [comment]
I see something similar with my deCONZ gateway. I don't even really care that it's visible in the room it's assigned to. I would just prefer not to see it in my favorites in the Home app.

**Comment by ebaauw** [comment]
https://github.com/ebaauw/homebridge-hue/issues/767
