### ISSUE TITLE
Adding Support for Xiaomi Wall Switch (single rocker)

### ISSUE THREAD

**Issue by crazylenni** [ebaauw/homebridge-hue#775]
#### Feature Request

I bought the Xiaomi WXKG03LM Wall Switch (single rocker) but received the WXKG06LM. Its the newer version and is supported in deconz since 2.05.80 (beta). Through homebridge-hue its diplayed as unrecognised device in homekit.

Please add support for this switch (**WXKG06LM**). Thank you very much!

#### Log Messages

Homebridge-Log:
```
[Hue] Phoscon-GW: /sensors/3: warning: ignoring unknown ZHASwitch sensor {"config":{"battery":100,"on":true,"reachable":true,"temperature":2900},"ep":1,"etag":"e21270d6b28852cb094f06404ff07a53","lastseen":"2020-09-30T15:15Z","manufacturername":"LUMI","mode":1,"modelid":"lumi.remote.b186acn02","name":"Xiaomi Wandschalter 1","state":{"buttonevent":1004,"lastupdated":"2020-09-10T15:38:47.920"},"swversion":"20190329","type":"ZHASwitch","uniqueid":"00:15:8d:00:04:4e:41:e7-01-0012"}
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5313001/homebridge-hue.json.gz)

**Comment by crazylenni** [comment]
I just found the corresponding pull request (https://github.com/ebaauw/homebridge-hue/pull/774).
Can you merg this in the next version?
Thanks!

**Comment by ebaauw** [comment]
Thanks.

Unfortunately, the deCONZ API doesn’t report what button events a switch supports, so they need to whitelisted.

**Comment by ebaauw** [comment]
In v0.11.17

**Comment by crazylenni** [comment]
> In v0.11.17

Just updated. Thank you very much!
