### ISSUE TITLE
Osram LED strip has no Color Temperature in Home.app

### ISSUE THREAD

**Issue by cbeckmann** [ebaauw/homebridge-hue#781]
Hi,

I have two LED strips connected to the Hue base and accessible via Homebridge. 

They are recognized as the following:

`[10/13/2020, 1:44:35 AM] [Hue] Philips hue: 7CB03EAA0A008D49: OSRAM LIGHTIFY Indoor Flex RGBW "Lichtschlauch"`
`[10/13/2020, 1:44:35 AM] [Hue] Philips hue: /lights/1: Extended color light "Lichtschlauch"`
`[10/13/2020, 1:44:35 AM] [Hue] Philips hue: /lights/1: config: {"on":true,"bri":true,"ct":true,"xy":true,"speed":false,"colorloop":true,"lastBoot":false,"lastSeen":false,"resetTimeout":500,"waitTimeUpdate":20,"minCT":125,"maxCT":666,"gamut":{"r":[0.6877,0.3161],"g":[0.1807,0.7282],"b":[0.1246,0.058]},"unknown":false}`
`[10/13/2020, 1:44:35 AM] [Hue] Philips hue: 00124B00213EEE28: GLEDOPTO GL-MC-001 "Monitorbeleuchtung"`
`[10/13/2020, 1:44:35 AM] [Hue] Philips hue: /lights/3: Extended color light "Monitorbeleuchtung"`
`[10/13/2020, 1:44:35 AM] [Hue] Philips hue: /lights/3: config: {"on":true,"bri":true,"ct":true,"xy":true,"speed":false,"colorloop":true,"lastBoot":false,"lastSeen":false,"resetTimeout":500,"waitTimeUpdate":20,"minCT":155,"maxCT":495,"gamut":{"r":[0.7006,0.2993],"g":[0.1387,0.8148],"b":[0.151,0.0227]},"unknown":false}`

GLEDOPTO supports color temperature via Home.app. However, the OSRAM LIGHTIFY Indoor Flex RGBW **does not** work with color temperature via Home.app, instead it translates to setting hue and saturation, leaving the dedicated white LED aside.

` [10/13/2020, 2:28:42 AM] [Hue] Monitorbeleuchtung: set homekit hue from 37˚ to 33˚`
` [10/13/2020, 2:28:42 AM] [Hue] Monitorbeleuchtung: set homekit saturation from 61% to 99%`

I assume, the support for this OSRAM LED strip is not yet there. Do you plan support for it, or at least provide me a hint, where to embed it?

Thanks

**Comment by ebaauw** [comment]
The Home app supports either _Hue_ and _Saturation_ or _Color Temperature_, but not both.  In case of colour lights, the _Temperature_ wheel sends _Hue_ and _Saturation_, just as the _Colour_ wheel.  This is OK for RGB lights that mix colour temperature using the RGB channels, but not for RGB+CCT lights that use separate WW/CW channels for colour temperature.  I'm unfamiliar with the GLEDOPTO model you're using, but I suppose it has only RGB channels?  I'm unfamiliar with the OSRAM model you're using, but I would expect it to mix in the W channel for lower saturation values.  It would still need to use the RGB channels to mix the colour temperature, as it only has one W channel.

To drive the WW/CW channels from HomeKit, Homebridge Hue exposes _Colour Temperature_ using the old custom characteristic, used by the Hue bridge before HomeKit supported the standard _Color Temperature_.  Custom characteristics are not supported by Home, but other HomeKit apps, like Eve, do support it.  You can create a scene in Eve containing the custom characteristic, and still recall that scene from Home.

**Comment by cbeckmann** [comment]
Thanks @ebaauw,

GLEDOPTO is a LED RGB CW WW strip and works flawlessly with color temperature.
OSRAM LIGHTIFY Indoor Flex is a LED RGB WW strip, without additional CW LED. 

So, your assumptions are true ;-) 
I was wondering if it does make sense to add `this.model = 'RGBW'` to the `models` section for OSAM, in order to support the basic W-behavior via the color temperature setting?

**Comment by ebaauw** [comment]
I'm not sure what you mean by "basic W-behaviour"?  Homebridge Hue doesn't know about the number of channels, and exposes the OSRAM and GLEDOPTO to HomeKit in the same way.  Both expose themselves as _Extended Color Light_.  You can set the colour temperature from HomeKit through Eve.

You could try through the API setting various values for `xy` and `ct` to see if the two strips behave differently, or use the GUI with _Move to Color_ (specifying _Current X_ and _Current Y_) or _Move to Color Temperature_ (specifying _Color Temperature_).

**Comment by cbeckmann** [comment]
Thanks. Yes, setting color temperature via Eve works for both strips. 

I was just wondering why these two stips behave differently in Home.app; when their config-strings appear to be the same.

`[10/25/2020, 2:30:58 PM] [Hue] GLEDOPTO: homekit color temperature changed from 367 mired to 492 mired` uses the ct-features, while 

`[10/25/2020, 2:32:19 PM] [Hue] OSRAM: set homekit hue from 20˚ to 321˚`
`[10/25/2020, 2:32:19 PM] [Hue] OSRAM: set homekit saturation from 29% to 73%` uses the xy-feature.

Anyways, the workaround via Eve scene works. It allows for some basic colour-tempature settings for the OSRAM strip.
