### ISSUE TITLE
Support for Danalock

### ISSUE THREAD

**Issue by simplenotezy** [ebaauw/homebridge-hue#782]
Would you consider adding support for the danalock? Or Perhaps guiding me towards making this possible? I'd love to help out

**Comment by ebaauw** [comment]
Please list the resource(s) that the deCONZ REST API creates for it.  And some clue as how to control it through the API.

**Comment by simplenotezy** [comment]
Hey @ebaauw I would be happy to, but I'm quite new to this (just installed Homebridge today). Let me know how I may help - list the exact steps for me to take.

**Comment by ebaauw** [comment]
Best attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by simplenotezy** [comment]
@ebaauw ok. I can do that. But currently my Eco2 is not connected in any way to Homebridge. Don't I at least need to connect my ZWave Stick before the dumps/Logs will help anything? I'm pretty new to this so please bear with me :)

**Comment by ebaauw** [comment]
Homebridge Hue doesn’t do anything with ZWave.

Devices need to be supported by the deCONZ REST API or by the Hue bridge API for Homebridge Hue to support them.  The dump contains the full details of what the gateway/bridge exposes (masking ip addresses and api keys).

**Comment by simplenotezy** [comment]
I see. I guess this repo is not the place to be then. Danfoss Eco / Danalock is not supported by Hue

**Comment by simplenotezy** [comment]
Hmmm. Actually it looks like decons rest api supports danalock now

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/520

**Comment by simplenotezy** [comment]
Question is how I would go about setting it up

**Comment by simplenotezy** [comment]
Heres the log as requested, although I am not sure what it could help, since Danalock should not be connected to my Homebridge in any way: https://gist.github.com/simplenotezy/181628d04711819c66c390a875e59cca

Anyhow, while tailing the log, I went ahead and locked and unlocked the door.

**Comment by ebaauw** [comment]
I need the dump file, not the log file.  And I need it from deCONZ, when the Danalock has been paired and exposed by the REST API.

**Comment by simplenotezy** [comment]
Sorry @ebaauw. Can you please spell it out for me. I am brand new in this.

I have this:
- Danalock
- Danalock WiFi Bridge
- Danalock Keypad
- Hue Bridge
- IKEA Trådfri Bridge
- Raspberry Pi with Homebridge

I don't have deCONZ.

How do I pair the Danalock, and how do I expose the REST API?

**Comment by ebaauw** [comment]
You need the Zigbee version of the Danalock and deCONZ (with support for the Danalock v3).  Pair the Danalock to deCONZ, so it exposes it over the API.  Homebridge Hue supports the Hue API by the Hue bridge and the REST API by deCONZ (see README); the Hue bridge only supports ZLL and ZB3 lights and plugs and (Friends-of-)Hue switches and sensors (again: see README).

The Danalock WiFi bridge and Trådfri hub use their own APIs, maybe there's a plugin for each of these.

**Comment by simplenotezy** [comment]
I see, thanks @ebaauw for the throughout explanation. It makes more sense now.

I have the Danalock V3 BT (EAN: 5712560000509) so I guess I have a supported version.

I'll pair the Danalock with deCONZ as soon as I can. Would I need to buy any hardware for the deCONZ (like the: https://phoscon.de/en/conbee2) or can I use my Z-Stick?

**Comment by ebaauw** [comment]
> I have the Danalock V3 BT (EAN: 5712560000509) so I guess I have a supported version.

Are you sure?  I don’t know Danalock, but “BT” usually means Bluetooth, not Zigbee.

> Would I need to buy any hardware for the deCONZ

Yes, a RaspBee or ConBee.  See https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-for-Dummies.

> can I use my Z-Stick?

See my previous answer: ZWave has nothing to do with Zigbee.

**Comment by smulle48** [comment]
Any chance to get it working? Danalock already supported by deConz. It's treated as a light

**Comment by malmentm** [comment]
Would also like to have this lock up and running 💯

**Comment by ebaauw** [comment]
See #889.
