### ISSUE TITLE
Support for Danfoss Eco 2 Thermostats

### ISSUE THREAD

**Issue by simplenotezy** [ebaauw/homebridge-hue#783]
Would you consider adding support for setting the heat via Danfoss Eco 2 Thermostats? I would be happy to help developing this, but I need some help getting started ;)

**Comment by ebaauw** [comment]
Should be relatively easy as the Eurotronic TRVs are already supported.  Please list the REST resources that the deCONZ API creates for this device, or attach the debug dump file.

**Comment by simplenotezy** [comment]
I would be happy to. Let me know what I should do exactly and I'll do it ;)

**Comment by ebaauw** [comment]
Best attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by simplenotezy** [comment]
I have just spoken to Support, and despite having found this PDF https://store.zwavecenter.com/image/catalog/PDF/DAN_ECO2.pdf it's not Z-wave/ZigBee but Bluetooth. Thanks anyway.

@ebaauw If you have any ideas how I can integrate to Homekit nevertheless, I would greatly appreciate the pointer ;)
