### ISSUE TITLE
Aqara motion sensor : lux not updating in iOS 14

### ISSUE THREAD

**Issue by Galiwyx** [ebaauw/homebridge-hue#784]
#### Issue

Hello,
I use an Aqara Motion sensor with homebridge on Raspbian. It’s works but LUX not updating, it displays 8 lux 99% of the time. Sometimes it display 23 lux but very rarely. I tested in the total black or in outdoor. Lux not updating. 

Thank you 
#### Log Messages

```
Nothing related to lux is displayed on the log
```

**Comment by ebaauw** [comment]
Does `state.lightlevel` in the API update?  If not, the issue is with deCONZ.  If so, please capture a debug log file while placing the sensor in different light conditions, and **attach** it, together with the debug dump file.  See README.
