### ISSUE TITLE
Device type problem

### ISSUE THREAD

**Issue by burakcankose** [ebaauw/homebridge-hue#786]
Hello everyone, 

I have conbee 2 devices. There is an outlet of ikea product. I see it as an outlet on conbee but as a switch on homebridge. how can i fix this on homebridge?

**Comment by massari46** [comment]
I have the same problem :(

**Comment by ebaauw** [comment]
Create an `outlet` resource link with the `/lights` resources to expose as outlet.  `ph outlet` will create one based on the device types, but not all outlets expose the correct type.  Search the closed issues for details.
