### ISSUE TITLE
homebridge-hue dont'i synk all scenes

### ISSUE THREAD

**Issue by alexcarsso** [ebaauw/homebridge-hue#788]
Hi, I am unsuccessfully trying to sonchronize the scenes created with the Hue app in the homekit. in my config.json i activated scenes, group, group0 and linkbutton on true. The scenes that are synchronized are only 5, but there are many more.
I used the command ph -H xxx.xxx.xxx.xxx -u user get to read the configuration on the bridge. i noticed that homebdrige-hue exposes scenes that have no group, here is an example: "HL7E5B1L73J8UG69": {
      "name": "Let's Watch A Movie",
      "type": "LightScene",
      "lights": [
        "10",
        "12",
        "13",
        "18",
        "23",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "34"
      ],
Other scenes have a group, like this example:
"0is0ZJuIkY21g3m": {
      "name": "Soft light in the living room",
      "type": "GroupScene",
      "group": "5",
      "lights": [
        "10",
        "12",
        "13",
        "18",
        "23",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "34"
      ],
in this example there is "group": 5, in other example I have "group": 14, and these scenarios are not synchronized. Can someone help me?
thanks a lot and sorry for my english!

**Comment by ebaauw** [comment]
Please capture and attach a debug log (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and attach the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file).

**Comment by alexcarsso** [comment]
Hi, thanks for your reply, I am attaching the files. homebridge-hue intercepts all scenes but in the home app only exposes group 0
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/5408315/homebridge.log)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5408319/homebridge-hue.json.gz)

**Comment by alexcarsso** [comment]
in file 1 the scenes intercepted by the plugin, in file 2 the scenes exposed in the homekit. Thanks a lot
![1](https://user-images.githubusercontent.com/46610746/96580701-f950f380-12d8-11eb-9e4b-ff697fdc2f5e.png)
![2](https://user-images.githubusercontent.com/46610746/96580715-fe15a780-12d8-11eb-8bf4-a23799aba4ef.png)

**Comment by ebaauw** [comment]
> [2020-10-20 13:01:08] [Hue] Philips hue: /groups/5: Room excluded

Ah, those are _Room_ groups, and only exposed when you also set `rooms` in config.json.

**Comment by alexcarsso** [comment]
it works for me, thanks a lot for the replies. I have read that I can insert blacklists and whitelists to filter lights. In the documentation there is the configuration part in the config.json but hombridge processes it as a new plugin and it doesn't work for me. can I have a complete sample config.json?
Thanks again

**Comment by alexcarsso** [comment]
it works for me, thanks a lot for the replies.
