### ISSUE TITLE
(IKEA) Sensors are exposed as sensors and lights

### ISSUE THREAD

**Issue by Einstein2150** [ebaauw/homebridge-hue#789]
#### Issue
(IKEA) Sensors are exposed as sensors and lights

#### Log Messages
No Logs but Screenshots

![IMG_5442](https://user-images.githubusercontent.com/22019133/96832097-7ea1e880-143e-11eb-94b6-5134d9b108a2.jpeg)
![IMG_5443](https://user-images.githubusercontent.com/22019133/96832108-83669c80-143e-11eb-8a94-d55dc3a5ef67.jpeg)

For every switch or motion sensor I get a additional light in home. This light-device of the button or motion sensor is absolutely out of sense. I tried different configs but nothing worked to remove it...

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5420464/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
No they’re not.  The lights you see are for the groups linked to the switches.  Set `groups` to false not to expose them.

**Comment by Einstein2150** [comment]
Ok. By switching from groups to lights in the plugin it worked.

It seems it was my wrong concept using the existing groups for home. Now I grouped all separate light manually again in home so that it looks like before 👍
