### ISSUE TITLE
TRADFRI bulb E14 WS 470lm is exposed as color-changeable in home

### ISSUE THREAD

**Issue by Einstein2150** [ebaauw/homebridge-hue#790]
#### Issue
TRADFRI bulb E14 WS 470lm is exposed as color-changeable in home. The bulb has only different kinds of white - no color. The is no color selection in the deconz-webapp - only in home.

#### Log Messages
No log.

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5420520/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
According to the attached dump file, you don’t have that model light in your system?

**Comment by Einstein2150** [comment]
It's not in the dump. I checked it too. But why isn't the dump presenting the actual configuration? Hmm...

Here is a screenshot from the light in phoscon:
![IMG_5445](https://user-images.githubusercontent.com/22019133/96873851-c132e780-1475-11eb-9a14-12225588e386.png)
Here the correct settings for brightness and white-temperature in phoscon:
<img width="675" alt="Bildschirmfoto 2020-10-22 um 14 51 13" src="https://user-images.githubusercontent.com/22019133/96874225-2dade680-1476-11eb-8a2e-8c1122f5e503.png">
And here the same light in home offering color and white-temperature:
![IMG_5452](https://user-images.githubusercontent.com/22019133/96875025-0c99c580-1477-11eb-9b8c-47ed53b620c1.PNG)

**Comment by ebaauw** [comment]
Did you start Homebridge shortly after starting deCONZ?  It doesn’t expose all `/lights` resources on startup, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2473.

Could you restart Homebridge (**without** restarting deCONZ) and attach the new dump?

**Comment by Einstein2150** [comment]
Here the correct dump. There was a permission issue writing to the dump file in /var/homebridge. The owner was root. I Chown'd the file to the correct user homebridge and now the dump is working correct.

The bulb is named "Stern"

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5427540/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
The lights seems to be exposed correctly by the deCONZ REST API.

You also have a group named "Stern", but you're not exposing groups, are you?

You're not on any iOS beta, are you?  If you are, could you please check a released iOS or macOS version of Home?  Or check how Eve displays the light?

If the issue appears across multiple HomeKit apps, please capture and attach a debug log file, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by Einstein2150** [comment]
Ok. Yesterday I switched from the "groups" to the (single) "lights". I checked it again and now there is only the white-level to see 💪

Could it be that the deconz-groups always show the color selector? That seems not to be correct ...

**Comment by ebaauw** [comment]
> Could it be that the deconz-groups always show the color selector? That seems not to be correct ...

Yes, unlike the Hue bridge, deCONZ doesn't check what type of lights are in the group, to expose the group accordingly.  So the `action` of a group of only _On/Off_ lights still contains attributes for `bri`, `ct`, and `xy`.  Homebridge Hue exposes the light based on these attributes.  You can force the group to be exposed as an _Outlet_ (with only On/Off control) using an `outlet` resourcelink, but there's no way to limit what light attributes are exposed.  I think this should be solved in the deCONZ REST API - feel free to open an issue in their repo.
