### ISSUE TITLE
Jumitech switch

### ISSUE THREAD

**Issue by Silkjaer** [ebaauw/homebridge-hue#792]
I am trying to set up the plugin to replace my need for syncing with the native Hue bridge as I had some issues with that. But this presents other issues, where when sensors is set to true, it will include several unsupported tiles in HomeKit, such as "Rocker support", "textState", "presenceState", but also tiles for routines. Some switches are also included in homebridge 6-8 times (as if it is included once per possible action (four buttons, click + hold)

Sensors I have:
Switches: https://jumitech.dk/philips-hue/
Philips Hue outdoor motion sensor

#### Log Messages

```
```

**Comment by ebaauw** [comment]
You’re probably exposing the CLIP sensors made by the Hue app for routines.  Use `excludeSensorTypes` to filter out sensor types (see https://github.com/ebaauw/homebridge-hue/wiki/Configuration), or use a `blacklist` resourcelink to filter out individual sensors (see https://github.com/ebaauw/homebridge-hue#configuration).

**Comment by Silkjaer** [comment]
Thanks! Excluding CLIP worked perfectly 👍🏻
