### ISSUE TITLE
Homebridge restart

### ISSUE THREAD

**Issue by jad8k** [ebaauw/homebridge-hue#795]
Hello, can you help me with homebridge and deconz. Everytime when I restart HB, I have to authenticate app in deconz. Is there any solution? thank you 

#### Log Messages

```
```

**Comment by jad8k** [comment]
this is my configuration 

        {
            "name": "Hue",
            "anyOn": true,
            "forceEveWeather": true,
            "groups": true,
            "hosts": [
                "192.168.1.7:4530"
            ],
            "hueMotionTemperatureHistory": true,
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "wallSwitch": true,
            "platform": "Hue"
        },

**Comment by ebaauw** [comment]
See the README.
