### ISSUE TITLE
Problems when setting whitelist ressourcelinks

### ISSUE THREAD

**Issue by pr3d1ction** [ebaauw/homebridge-hue#796]
Hi all,
unfortunately I'm not able to set resourcelinks after the update:

 ph --host=xxx -u xxx post /resourcelinks
>> '{
>>   "name": "homebridge-hue",
>>   "classid": 1,
>>   "description": "whitelist",
>>   "links": [
>>     "/lights/32"
>>   ]
>> }'
ph post: warning: api error 5: invalid/missing parameters in body

Is there something additonally missing in the description?

Thanks!

**Comment by ebaauw** [comment]
Are you sure the body starts on the same line?   Is this a Hue bridge or a deCONZ gateway?  I think the Hue API uses `class` instead of `classid`, see https://developers.meethue.com/develop/hue-api/9-resourcelinks-api/.
