### ISSUE TITLE
"no response" in homekit, apple-tv ?

### ISSUE THREAD

**Issue by FSTNDonald** [ebaauw/homebridge-hue#798]
yes, as per advisory I did screen the available resources, my fault, if I missed something. But thanks in advance for guiding to a solution ...

Homekit ist top of the tree, feeded by HUE plugin (homebridge, deconz-II usb stick, orange pi zero, no other plugins) and by red-node (ELV homematic devices) and by native homekit 'non certified' devices (koogeek, dohome).

After iOS 14 upgrade I stumbled 2 weeks to find reason for "no response" devices, when not at home (i.e. not WLAN, but ATV bridging).  Taking iphones out of "home", "icloud", "keychain" did not help - solution was to take the old iphones (not running ios 14) completely(!) out of the apple account.

Result: no more "no response" from any device regardless of in reach of home WLAN or remotely via iCloud/ATV-bridge - 
**BUT** the HUE plugin devices ONLY still exhibit an unstable respones. As well as in home WLAN as well as remote via iCloud/ATV.

As per the described excercise I learned, that (even in a home WLAN) connectivity of the homekit bridges to the local LAN ATV(s) is a must for a proper response status. Even an iphone connected to the home WLAN does not talk to the bridges straight, but involves iCloud.

Just my 2 cents - might connectivity of homebridge and/or HUE plugin with ATV (after their TV OS Upgrade) be root cause ... ???
take care & stay @home - Donald

**Comment by ebaauw** [comment]
The connectivity with HomeKit clients, incl. the Apple TV or other home hub, is handled by Homebridge (or rather the underlying HAP-NodeJS).  Nothing Homebridge Hue or any other plugin can do.  You can check using `netstat` on the server running Homebridge that the Apple TV has an active session to Homebridge (you should see an incoming session for each active HomeKit client).  If, for some reason, your iPhone cannot find Homebridge on the local network, it reverts to remote access over iCloud to the home hub.  HomeKit uses https to control devices, but Bonjour (multicast DNS) to locate Homebridge.  If the latter fails, devices show as not responding.  Bonjour isn’t routable by default, and IGMP snooping on your switch or router tends to break it.  Best connect the Homebridge server and Apple TV by ethernet, using a dumb, unmanaged switch.

**Comment by FSTNDonald** [comment]
Hi Erik,
identified the culprit ... It is congestion of radio channels.
I am using 5 access points (Draytek AP90x), with AUTO channel selection, i.e. they 'see' their AP neighbours and operate on unoccupied channels. ZIGBEE operates on 2,4 GHz as the APs do I found from the spec.
Fix: put the ZIGBEE channel on the highest (25, Phoscon UI) and block channels 11-13 on the AP from the AUTO selection range, thats all. Stable operation after that change.
