### ISSUE TITLE
Lights and Plugs visible in Phoscon App but gone in Apple Home App

### ISSUE THREAD

**Issue by gruenberg** [ebaauw/homebridge-hue#800]
Hi there,

assuming that this is the right place to drop this line,
I have the following issue:

I have homebridge-hue installed via phoscon, version 0.11.77.
All sensors & lights show up correctly in the phoscon app, but no lights (Philips hue, Müller Licht) and only the sensors show up in the Apple Home App.

I assume that something's going wrong when advertising a light or is incompatible now, since it has worked in a prior version.

Question:
What needs to be done to solve the issue regarding the disappeared lights?

Cheers // Oliver

**Comment by gruenberg** [comment]
if you please could tell me what to check for I can offer to start investigation...
any hints appreciated!

**Comment by ebaauw** [comment]
I though I had posted a reply, but apparently it didn’t take...

Please attach the debug dump file, see https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by gruenberg** [comment]
ok, here we go:

stopped the service via 'sudo systemctl stop deconz-homebridge.service'

please find attached log files
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/5471631/homebridge.log)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5471632/homebridge-hue.json.gz)


What to do next?

**Comment by gruenberg** [comment]
one error in the dumped log files brought me to do:

cd /home/pi/
sudo chown -R pi:pi .homebridge

After a restart the problem was still there... but when I did 'sudo systemctl restart deconz-homebridge.service' suddenly the lights were visible in the Apple Home App...

Again, after a restart nothing, had to restart the service manually again in order to make the lights visible.

Question: Is this the cause of the problem? If so, where must I place the call to start the service correctly on boot?

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2473.

**Comment by Lucleonhart** [comment]
I did a fresh install of homebridge with deconz and homebridge-hue and ran into this exact same problem.
Now i started to apply the lightlist workaround but creating a user for the ph command seems to be broken for me:
`pi@FuPi:~ $ ph -H 192.168.178.31:4530 lightlist -v
ph: fatal: missing username - unlock gateway and run "ph -H 192.168.178.31:4530 createuser"
pi@FuPi:~ $ ph -H 192.168.178.31:4530 createuser
ph createuser: fatal: TypeError: Cannot read property 'type' of undefined
    at HueClient.createuser (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:234:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Main.createuser (/usr/local/lib/node_modules/homebridge-hue/cli/ph.js:638:22)
    at async Main.main (/usr/local/lib/node_modules/homebridge-hue/cli/ph.js:458:7)`
