### ISSUE TITLE
No bulbs in Home app

### ISSUE THREAD

**Issue by simplenotezy** [ebaauw/homebridge-hue#802]
All of a sudden (after a restart) there's no lights in the Home app. 

I see the two Switches I have as well as the Phoscon Gateway, but no lights.

If I check the Phoscon web UI I see all lights.

What could this be?

**Comment by simplenotezy** [comment]
I just noticed now that the bulbs seem to have been reset somehow. At least they are now under my Apartment in "Default Room". So I had to rearrange everything.

Wonder what could have caused this.

**Comment by ebaauw** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2473
