### ISSUE TITLE
Hue Bridge and Conbee shown as 'not supported' accessories.  Any way to remove them from My Home screen?

### ISSUE THREAD

**Issue by Moskvitch** [ebaauw/homebridge-hue#804]
#### Issue
I understand per #76 these serve a function and must be there, but is there a way to remove these as 'favourites' from My Home screen?  There is no Settings button for these if you press their icons so no way to turn off 'Include in favourites'.

Am I missing something obvious here?

Thank you

![IMG_6701](https://user-images.githubusercontent.com/11635627/97833319-2b555300-1ce6-11eb-97cd-cbd607fae90d.jpg)
![IMG_6702](https://user-images.githubusercontent.com/11635627/97833325-2e504380-1ce6-11eb-9192-b666dae9cec2.PNG)

#### Log Messages

```
```

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/issues/767.

**Comment by Moskvitch** [comment]
Thanks. Removed fro My Home using an old iPad running 12.4.8
