### ISSUE TITLE
Osram smart+ plug not shown in homekit with v0.12.0

### ISSUE THREAD

**Issue by toto77github** [ebaauw/homebridge-hue#809]
#### Issue

Osram smart+ plug not visible in homekit with Homebridge Hue v0.12.0. In Homebridge UI it is visible and works correctly. After changing to previous version v0.11.77 it works in homekit, too.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
If the UI shows it, Homebridge Hue exposes it, and it should be visible in HomeKit.  Did you check _Accessories_ under _Bridges_ in the _Home Settings_?

**Comment by toto77github** [comment]
I tried it with v0.12.0 again.  Unfortunately it disappers from HomeKit and from Eve. I checked Accessories under Bridges in the Home Settings. No success. After switching back to v.011.77 -> Osram plug is back again.

**Comment by ebaauw** [comment]
Could you please attach the debug dump file from running v0.12.0 and capture and attach a debug log file?  See https://github.com/ebaauw/homebridge-hue#debug-dump-file and https://github.com/ebaauw/homebridge-hue#debug-log-file.
