### ISSUE TITLE
Need Help Editing Config Json

### ISSUE THREAD

**Issue by kimihiro-0104** [ebaauw/homebridge-hue#817]
#### Issue

I tried to edit the Config.json with the Bridge id and api but I got Json error every time when trying to save it. 
Is there any simpler way as I am a noob in coding

Thanks
#### Log Messages

```
```

**Comment by ebaauw** [comment]
Use Homebridge Config UI X.  If not, make sure to use a text editor, not some document editor that changes the quotes.

**Comment by kimihiro-0104** [comment]
I am using the Homebridge Config UI X but still no luck on saving it. Am I doing anything wrong?

> {
    "bridge": {
        "name": "Homebridge 8533",
        "username": "0E:47:CE:89:85:33",
        "port": 51955,
        "pin": "788-25-472"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "hosts": [
                "192.168.50.243"
            ],
            "lights": true,
            "linkButton": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue"
            "users": {
                "001788FFFE4B0B1C": "9DlF8qv3sJYwnuaPOR80POQVLOsEYQ5IxOYblh34"
            }
        ]
    }

>

**Comment by ebaauw** [comment]
You're missing a comma.  Paste the contents into https://jsonlint.com.
