### ISSUE TITLE
OSRAM smart plugs disappear when settings sensors=true

### ISSUE THREAD

**Issue by zeromancer1972** [ebaauw/homebridge-hue#818]
Since I use a Conbee 2 with some sensors I added this bridge to the config where my Hue stuff already was in. Since I enabled the sensors in the config, the smart plugs are not available anymore. Any thoughts?

```json
{
            "name": "Hue",
            "platform": "Hue",
            "nupnp": true,
            "scenes": false,
            "groups": true,
            "rules": true,
            "rooms": false,
            "lights": false,
            "sensors": true,
            "scenesAsSwitch": false,
            "heartrate": 2,
            "anyOn": true,
            "excludeSensorTypes": [
                "CLIP",
                "Geofence",
                "Daylight"
            ],
            "users": {
                "001788FFFE6E4BC7": "-i9xaNNPjTig-evW9GERHut5Q-yEeDV1zoFDC5Gy",
                "00212EFFFF065201": "4FACFEB543"
            }
        }
```

I found out that with light:true the socket re-appear but now I also have all the lights from Hue in the Home app - which is annoying. Any chance to have both?

**Comment by ebaauw** [comment]
Set `nativeHomeKitLights` to refrain from exposing lights already exposed by the Hue bridge.  See https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by zeromancer1972** [comment]
Thanks, I already tried that and it didn't work - now it works. Strange... sorry
