### ISSUE TITLE
Motion Sensor HomeKit/Phoscon Adaptiv Light 

### ISSUE THREAD

**Issue by clipse2004** [ebaauw/homebridge-hue#823]
#### Issue

Hello, I have a question rather than an issue ;)
I use motion detectors in almost every room that turn the light on and off accordingly. I had done that in Phoscon so far because the detection there is more accurate than in the HomeKit. Now there's the adaptive light, but I can't choose in Phoscon, that is, I have to go via HomeKit. In use I have Hue and Aqara motion detectors, duration and delay I have already found and put further down (5 and 10). But now it's the case that if you stay in a room for a long time, the light will eventually turn off and turn on again after 1 second -> there movement. However, this was recognized in Phoscon and remained permanently switched on. Do you have a tip or a solution for me? BTW, I'm using your HUE beta, everything works perfectly so far. However, I noticed that my Raspberry is sometimes allowed to work quite well when the Adaptiv Light values are queried (hab 10 lamps in use)
 I thank you

**Comment by ebaauw** [comment]
If you turn on adaptive lighting in HomeKit, it remains active even if you turn the light off and back on from Phoscon, see https://github.com/ebaauw/homebridge-hue/issues/766#issuecomment-731560178.  Just don't set the colour from Phoscon.
