### ISSUE TITLE
updated everything (homebridge and homebridge-hue) - hue native lights appear in home then disappear 

### ISSUE THREAD

**Issue by Krispy44** [ebaauw/homebridge-hue#824]
Hey there, every time I restart homebridge, homebridge-hue briefly exposes my hue bulbs to the home app, but then they disappear, but are still available in homebridge. I have the setting enabled in homebridge-hue to expose these to homekit.

**Comment by ebaauw** [comment]
The only way accessories exposed by Homebridge Hue can disappear from HomeKit is when you restart Homebridge, after the accessories are exposed.  How do you restart Homebridge?  Please attach a debug dump file and debug log file (see README).

**Comment by Krispy44** [comment]
I restarted through the homebridge web ui. 

Whatever causes the accessories to disappear happens after the upgrade from 11.77 to 12.0, as when I downgrade to 11.77 with the same settings, they appear and stay there. I've been able to repeat this behavior through upgrading and downgrading. They appear in homebridge in both versions, but only in the home app in 11.77.

I do not know how to provide a debug log file, I am a little new to everything and had help from someone more knowledgeable than me in setting it up (I mostly use the web homebridge ui and only a little bit of ssh in terminal to interact with homebridge). 


I've attached a debug dump file. (These were created just after an upgrade to 12.0)
[homebridge-hue.json-2.gz](https://github.com/ebaauw/homebridge-hue/files/5578407/homebridge-hue.json-2.gz)

**Comment by Krispy44** [comment]
I've also attached a log file here, but I've taken out everything before the restart.
[homebridge.log.txt](https://github.com/ebaauw/homebridge-hue/files/5578472/homebridge.log.txt)

**Comment by ebaauw** [comment]
From what I can tell from the log files, Homebridge Hue is working alright.  Also, if you can see the accessories in Homebridge Config UI X, Homebridge Hue must be working.

Are only the Hue lights disappearing and not the sensors?  Are you sure they weren't moved to another room?  What version of iOS are you running?  Did you try other HomeKit apps?  Other iOS devices?

**Comment by Krispy44** [comment]
I'm on ios 14.2 on all my devices, including two ipads as hubs. The sensors don't show up either. I've also included the hue portion of my config below, minus the details under "users". This is the same config setup I had under the previous homebridge-hue version and it worked. Does this look alright as well?


{
            "name": "Hue",
            "anyOn": true,
            "hueMotionTemperatureHistory": true,
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "users": {
                "": ""
            },
            "platform": "Hue"
        }

**Comment by ebaauw** [comment]
That part was already captured in the dump file.  Still looking OK.

And the accessories exposed by other plugins in the same Homebridge instance don’t disappear?  Did you upgrade to Homebridge v1.2.3 at the same time as upgrading Homebridge Hue?  Does the issue occur with Homebridge Hue v0.12.0 under Homebridge v1.1.6?

If accessories by other plugins also disappear, it’s probably because one of your plugins is exposing a malformed accessory.  Some plugin is trying to add an `undefined` characteristic as well as _Current Relative Humidity_ to a _Temperature Sensor_:
```
HAP Warning: Characteristic undefined not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
```

**Comment by Krispy44** [comment]
No other accessories disappeared and all of them work. I upgrade to Homebridge v1.2.3 before upgrading homebridge-hue.

I'm trying to learn how to downgrade just my homebridge version right now and will get back to you.

**Comment by Krispy44** [comment]
Just downgraded to 1.1.6 and the same issue happens. I've tried removing most of my plugins and that wasn't a solve either. The only thing that works is downgrading homebridge-hue to v11.77 (I found downgrading homebridge-hue to fix the problem on both homebridge versions).

**Comment by Krispy44** [comment]
Ok, update here, I updated homebridge to v1.3.0-beta.27 and it works again, with all the plugins included. I have no idea why.
