### ISSUE TITLE
Phoscon Events not forwarded?

### ISSUE THREAD

**Issue by k1th** [ebaauw/homebridge-hue#827]
#### Issue
After coming home, pressing BJ ZLL switches show events in Phoscon, but no Homekit Actions triggered. 
After starting the Home App on my iPhone everything’s good again. 

Setup:
Raspi, Raspbee II, Phoscon/Deconz, Homebridge, Hue Plug-in, Shelly Plug-in etc. 
all current stable versions. 

Should I debug anything?

#### Log Messages

```
Nov 23 10:51:25 raspberrypi homebridge[10755]: [23/11/2020, 10:51:25] [RPi] pi: set Current Temperature from 60°C to 58°C
Nov 23 10:51:25 raspberrypi homebridge[10755]: [23/11/2020, 10:51:25] [RPi] pi: set Frequency from 600MHz to 800MHz
Nov 23 10:51:25 raspberrypi homebridge[10755]: [23/11/2020, 10:51:25] [RPi] pi: set Load from 0.12 to 0.17
Nov 23 10:51:29 raspberrypi homebridge[10755]: [23/11/2020, 10:51:29] [Phoscon] Wandsender 4-Kanal Button 8: homekit button single press
Nov 23 10:51:33 raspberrypi homebridge[10755]: [23/11/2020, 10:51:33] [Phoscon] Wandsender 4-Kanal Button 8: homekit button single press
Nov 23 10:51:40 raspberrypi homebridge[10755]: [23/11/2020, 10:51:40] [RPi] pi: set Current Temperature from 58°C to 59°C
Nov 23 10:51:40 raspberrypi homebridge[10755]: [23/11/2020, 10:51:40] [RPi] pi: set Frequency from 800MHz to 600MHz
Nov 23 10:51:40 raspberrypi homebridge[10755]: [23/11/2020, 10:51:40] [RPi] pi: set Load from 0.17 to 0.22
Nov 23 10:51:55 raspberrypi homebridge[10755]: [23/11/2020, 10:51:55] [RPi] pi: set Current Temperature from 59°C to 60°C
Nov 23 10:51:55 raspberrypi homebridge[10755]: [23/11/2020, 10:51:55] [RPi] pi: set Frequency from 600MHz to 1500MHz
Nov 23 10:51:55 raspberrypi homebridge[10755]: [23/11/2020, 10:51:55] [RPi] pi: set Load from 0.22 to 0.17
Nov 23 10:52:10 raspberrypi homebridge[10755]: [23/11/2020, 10:52:10] [RPi] pi: set Current Temperature from 60°C to 61°C
Nov 23 10:52:10 raspberrypi homebridge[10755]: [23/11/2020, 10:52:10] [RPi] pi: set Load from 0.17 to 0.36
```

**Comment by ebaauw** [comment]
This is a typical symptom when your home hub has lost the connection with Homebridge.  Note that actions are executed from the home hub.  When you start Home, it connects to Homebridge and receives the triggers.  It syncs the state to the home hub over iCloud, so now the actions are all of a sudden executed.

Best check using `netstat` on the Homebridge server whether the home hub has an open session with Homebridge.  If not, restart the hub (AppleTV, HomePod, iPad).

**Comment by k1th** [comment]
Yeah, the conn is there now
```
root@raspberrypi:~# netstat -anp | grep -i 10.0.1.58
tcp6       0      0 10.0.1.42:51826         10.0.1.58:49255         ESTABLISHED 10755/homebridge
```
Since I got home it hasn't disconnected.

The connection is outbound. (.58 is the Apple TV). At what point and how often does Homebridge connect to the Home Hub?

**Comment by ebaauw** [comment]
The connection is inbound (from the hub to Homebridge).  The local port should match the port from the `bridge` section in config.json.

**Comment by k1th** [comment]
of course, sorry, you're right.
an yeah, the port matches.

I wonder how I could debug this. They are even both on the same network with Ethernet, not even Wifi.

**Comment by ebaauw** [comment]
I’m sorry, this is between the home hub (Apple) and Homebridge/HAP-NodeJS, nothing to do with Homebridge Hue.  Please check the Homebridge and/or HAP-NodeJS repositories for details.  The usual Bonjour blues apply here as well.

**Comment by k1th** [comment]
yeah, that :)
Will see if someone there has some kind of hack...
