### ISSUE TITLE
Can´t delete an osram plug in Phoscon

### ISSUE THREAD

**Issue by JoMensdorf** [ebaauw/homebridge-hue#828]
Hi!

I´m using the hue plugin in homebridge v1.2.3 on a rasp3+ with an conbee II stick and a native hue hub.
One of the osram plugs bound to the conbee seems to be broken, it won´t react anymore and always shows
switched on. I can rename it and move it to another room in the phoscon app, but once I delete it there the hue plugin
prevents the homebridge from starting.
Tried deCONZ v2.05.77 and v2.6.0

Log Messages
[11/21/2020, 11:56:32] [Hue] Phoscon: dresden elektronik deCONZ gateway v2.6.0, api v1.16.0
[11/21/2020, 11:56:32] [Hue] Phoscon: warning: not using recommended deCONZ gateway version 2.5.84
[11/21/2020, 11:56:32] [Hue] Philips hue: Philips BSB002 bridge v1939070020, api v1.38.0
[11/21/2020, 11:56:32] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.41.0
[11/21/2020, 11:56:32] [Hue] Phoscon: /resourcelinks/1: /lights/11: not available
[11/21/2020, 11:56:32] [Hue] Phoscon: gateway not yet initialised - wait 1 minute

This is my config, I can reach the phoscon app under the mentioned adress:
{
            "name": "Hue",
            "anyOn": true,
            "excludeSensorTypes": [
                "CLIP",
                "Daylight",
                "Geofence"
],
            "groups": false,
            "hosts": [
                "192.168.178.83",
                "192.168.178.99:8199"
],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": false,
            "rules": false,
            "scenes": false,
            "schedules": false,
            "sensors": true,
            "users": {
                "001788FFFEA7AB0A": "XX1",
                "00212EFFFF05AA66": "XX2"
},
            "platform": "Hue"
},

And I get this if I try to 
ph lightlist -v

ph: error: TypeError: Cannot read property 'substring' of undefined
at HueClient.connect (/usr/local/lib/node_modules/homebridge-hue/lib/HueClie nt.js:79:23)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Main.main (/usr/local/lib/node_modules/homebridge-hue/cli/ph.js:413 :11)
ph: fatal: localhost: not a Hue bridge nor deCONZ gateway

Does somebody have an idea how I can get rid of that osram plug?

Thanks,
Jo

**Comment by ebaauw** [comment]
You need to specify which deCONZ gateway you want `ph` to connect to, using `ph -H 192.168.178.99:8199 lightlist -v` or by setting PH_HOST.

**Comment by JoMensdorf** [comment]
Ok, thanks for the reply.
I´m sorry, I´m not sure if I git what you mean, bu I try :-)
If I ph -H 192.168.178.99:8199 lightlist -v the reply is:
ph -H 192.168.178.99:8199 lightlist -v
ph: fatal: missing username - unlock gateway and run "ph -H 192.168.178.99:8199 createuser"

I did that and created a new user, now the reply is:
ph -H 192.168.178.99:8199 lightlist -v                       
ph lightlist: /resourcelinks/2: 11 lights

And now?

Thanks again,
jo

**Comment by ebaauw** [comment]
`ph lightlist` created resourcelink 2, but your log above indicates resourcelink 1?  Maybe that’s the `outlet` resourcelink?  If `/lights/11` is the only link in there, just delete the resourcelink, otherwise you would need to update it.

**Comment by JoMensdorf** [comment]
Ok, I have a backup of my rasp sdcard, so I can try anything. If I knew how :-)
I tried 
ph 192.168.178.99:8199 delete /resourcelinks/1 
but got: 
ph: fatal: 192.168.178.99:8199: unknown command

**Comment by ebaauw** [comment]
You forgot the `-H`.

**Comment by JoMensdorf** [comment]
Thats because I have no idea what I´m doing. Thanks!
That worked, but now my homebridge log says:
[11/23/2020, 17:58:14] [Hue] Phoscon: /resourcelinks/2: /lights/3: not available
[11/23/2020, 17:58:14] [Hue] Phoscon: gateway not yet initialised - wait 1 minute
And it won´t start.

**Comment by JoMensdorf** [comment]
Or would it make sense to delete all recourcelinks and relink to homebrisge then?

Thanks,
Jo

**Comment by ebaauw** [comment]
Did you delete a light from Phoscon after running `ph lightlist`?  The idea is that `ph lightlist` creates a resourcelink which links all `/lights` resources.  This enables Homebridge Hue to check that deCONZ is exposing all of them.  It delays the Homebridge startup, until all lights are available, to prevent the corresponding accessories from being removed by HomeKit.

Unfortunately, deCONZ doesn’t update the resourcelinks automatically when deleting a `/lights` resource.  This causes Homebridge Hue to wait indefinitely for deCONZ to expose the light.  So you need to update the resourcelink every time you remove a light from deCONZ.

I don’t know how many resourcelinks you have, nor what you use them for.  But if you delete them all, and the re-run `ph lightlist` you should be good to go.

**Comment by JoMensdorf** [comment]
Ok, I think I´m slowly getting there thanks to your help.
I did delete the osram plug in Phoscon and ran 

ph -H 192.168.178.99:8199 lightlist -v with the reply
ph lightlist: /resourcelinks/2: 10 lights

Thanks a lot!!!!
