### ISSUE TITLE
Aqara Wireless Switch on Phoscon-GW stops to toggle scenes after a while

### ISSUE THREAD

**Issue by DrDoom666** [ebaauw/homebridge-hue#829]
My Aqara Smart Wireless Switch triggers some Homekit Scenes.
Everything works fine. After a couple of hours the switch doesn’t toggle my scenes any more.
If I look at the homebridge log, the Phoscon-GW recognizes that the button is pushed once or twice, but Homekit doesn’t trigger my scenes any more.
If I restart the homebridge, everything works perfectly for a couple of hours.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Does Homebridge Hue issue a log message for the button press?  If so, the issue is between your home hub and Homebridge.  See #827.

**Comment by DrDoom666** [comment]
Yes, I saw this other issue. But I have no idea how to solve this problem.
Both are connected over Ethernet. My Raspberry direct to my Fritzbox, the Apple TV over a simple Gigabit-Switch, because I have no ports free on the Fritzbox anymore.

**Comment by ebaauw** [comment]
HomeKit automations (incl. button actions) and remote access run on your home hub.  The Home app communicates directly with Homebridge.

**Comment by DrDoom666** [comment]
Oh. That would explain it.

**Comment by DrDoom666** [comment]
Do you have any good advice for me?

**Comment by ebaauw** [comment]
Reboot the AppleTV, check with `netstat` that it connects to Homebridge (see other issue).  Monitor whether the connection remains solid.  If not, checkout the Homebridge and HAP-NodeJS repositories for Bonjour issues.

**Comment by DrDoom666** [comment]
Thank you!

The problem was solved by connecting the Apple TV and the Raspberry to the same managed switch and disabling IGMP-Snooping.
