### ISSUE TITLE
Workaround for IKEA lights that don't update multiple state attributes

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#830]
Several IKEA lights have a firmware bug, where they don't execute a second command received from the Hue bridge or deCONZ gateway, when the previous command is still in transition.  Typically when setting both `bri` and `ct` or both `bri` and `xy` in one API call, the colour (temperature) changes, but the brightness does not.  This is especially noticeable when adaptive lighting is enabled, as this changes the colour temperature when changing the brightness.

The usual workaround is to add a `transitiontime` of 0 to the API call.  As of v0.12.3, Homebridge Hue does this automatically.  The trade-off is, of course, that the transition is less smooth than usual.  Because of this, the lights with the firmware bug need to be whitelisted, so well-behaving lights don't suffer unnecessarily.

Currently the following models are whitelisted:
- `TRADFRI bulb E27 CWS opal 600lm`;
- `TRADFRI bulb E27 WS opal 980lm`.

Please reply to this issue when you have another model with the firmware bug.  I need the precise (case sensitive) `modelid` to whitelist the light, including any spaces and unprintable characters.  Best attach the debug dump file, or run `ph get /lights/xx/modelid` and copy/paste the output.

**Comment by dheckl** [comment]
Please put the following bulb on the whitelist, which also has the firmware bug:

`"modelid": "TRADFRI bulb E12 WS2 opal 600lm"`

**Comment by miquellaboria** [comment]
Also: “TRADFRI bulb E27 WS opal 1000lm”
Thanks!

**Comment by Einstein2150** [comment]
"modelid": "FLOALT panel WS 60x60",

    "modelid": "TRADFRI bulb GU10 WS 400lm",

    "modelid": "TRADFRI bulb E14 WS 470lm",

**Comment by jensflorian** [comment]
"modelid": "FLOALT panel WS 30x30"

**Comment by ebaauw** [comment]
That's a lot of models with the firmware bug.  Are there any IKEA lights that don't have this bug?  I might be easier just to enable the workaround for all IKEA lights...

**Comment by luedefengzi** [comment]
- `FLOALT panel WS 30x90`

This one is also having the same issue. And yes, probably all of the IKEA bulbs seem to have this bug, which might be an issue for quite some time now (even with Tradfri bridge it seems): https://www.reddit.com/r/tradfri/comments/jda2p5/homekit_scenes_dont_change_light_colour/?sort=confidence

btw: Thanks for this great plugin!

**Comment by Kristian8606** [comment]
Ikea needs to fix the firmware on their bulbs and they know about the problem. Until that happens, is it possible to add a button to turn off this option only for ikea bulbs, as my Chinese bulbs have no problem with this.

**Comment by kmplngj** [comment]
@ebaauw Is this something decenz should be fix in the first row?

**Comment by ebaauw** [comment]
It’s something that IKEA should fix in their firmware.

I’m really not sure whether a workaround should be implemented in the deCONZ REST API plugin, or in clients of the API, like Homebridge Hue.  With their respective current designs, it’s relatively easy to implement in Homebridge Hue, and next to impossible in deCONZ.  Also, the issue mostly appears with API clients for integration into other systems, updating multiple attributes in a single API call, rather than API clients providing a UI, typically providing separate controls (sliders) for brightness vs colour (temperature).  For efficiency, Homebridge Hue combines the user-initiated new brightness and the computed colour temperature under adaptive lighting in one API call, further increasing exposure to the IKEA firmware bug.

**Comment by luedefengzi** [comment]
It’s just quite unfortunate that IKEA hasn’t fixed this since quite some time now. So your current work around is really helping me. Thank you for that!

**Comment by ebaauw** [comment]
Looks like all IKEA light models exhibit the firmware bug.  I'll just whitelist the brand, so we don't have to whitelist each model individually.

**Comment by ebaauw** [comment]
In v0.12.6.

**Comment by FezVrasta** [comment]
Hi, I still experience this problem. Most of the times when I turn on an Ikea bulb nothing happens. May you please let me know if have you noticed a regression?

**Comment by ebaauw** [comment]
> Most of the times when I turn on an Ikea bulb nothing happens.

That's something completely different.  Please don't hijack closed threads.

**Comment by FezVrasta** [comment]
I don't think it's a different issue, this can be observed when a 100% brightness + color commands are sent in the same call, like it's described in this issue.

**Comment by ebaauw** [comment]
> (Because sometimes only the color command is applied but the bulb stays off.)

That is technically impossible.  Zigbee doesn’t support changing colour or brightness while a light is off.
