### ISSUE TITLE
wallSwitch=true turns off the bulb in Homebridge but not in Hue bridge

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-hue#832]
#### Issue

I have a non-Hue bulb paired to the Hue bridge and working fine. It is in a room where people often turn off the light with the wall switch. So I set wallSwitch=true and the bulb appears off in the Home app. All good so far.
However, the Hue bridge shows the bulb as reachable=false, and the last state: on=true. This means the bulb stays on in the Hue app.
To solve the Hue app problem, I added an automation in Homekit using this curl command to turn off the lights on the Hue app:
curl -X PUT -d '{"on":false}' http://myHueIpAddress/api/myHomebridgeHueUsernmae/lights/23/state

The reason I do this is fundamentally cosmetic but also to prevent confusion with my other home members who like to use the Hue app: 
I'd like the Hue app to show the bulb state, which in this case is off as the wall switch is off. 
Note that should the wall switch ever come on again, the Hue app currently updates the status automatically and shows it as on again. So the action of turning on the wall switch to switch on the bulb is correctly caught in the Hue app.

Would it be possible to have Homebridge Hue update the Hue Bridge lamp status so that the lamp appears off in the Hue app when wallSwitch=true?

#### Log Messages

None needed

#### Debug Files

None needed

**Comment by ebaauw** [comment]
Technically: yes.  However, I'm not going to do that.

`reachable` doesn't reflect whether the light is off (powered down).  It doesn't even reflect whether the light is reachable; it only reflects whether the light responded the last (couple of) time(s) the bridge tried to communicate with the light.  Especially on non-Hue lights might show `reachable` as false occasionally for a brief period for no apparent reason.  If Homebridge Hue would set `on` to false, the light would turn off, seemingly spontaneously, and I would get a lot of support issues.

You really don't want to be using 20th century wall switches with smart lights.

**Comment by jsiegenthaler** [comment]
OK, understood. Thanks for the explanation. I'll stick with my current solution - which is triggered by a delay switch, so it only fires once.
