### ISSUE TITLE
transition control fails after restarting homebridge + ct-range-issues

### ISSUE THREAD

**Issue by Einstein2150** [ebaauw/homebridge-hue#833]
#### Issue
I activated the transition control. At the time of first activation the transition starts and works. After a restart of homebridge it doesn't trigger anymore but he light is still marked as "transition-enabled" in home:

![IMG_62E664B5CF61-1](https://user-images.githubusercontent.com/22019133/100319545-15267400-2fc0-11eb-8c96-0c15a75d7184.jpeg)

After switching to a fixed ct-value and switching back to transition-mode it works again.

#### Log Messages

When setting transition control:

`Deckenlampe Büro vorne: homekit transition control set to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-26T07:06:55.870Z","2.1.2.3":"CDA4AD53FE6441D8"},"runtime":1,"curve":{"entries":[{"adjustmentFactor":-1.288888931274414,"mired":381.8888854980469,"offset":0},{"adjustmentFactor":-1.2333333492279053,"mired":373.3333435058594,"offset":1385000},{"adjustmentFactor":-1.1333333253860474,"mired":363.3333435058594,"offset":1800000},{"adjustmentFactor":-1.0444444417953491,"mired":354.4444580078125,"offset":1800000},{"adjustmentFactor":-0.9888888597488403,"mired":348.8888854980469,"offset":1800000},{"adjustmentFactor":-0.9555555582046509,"mired":345.5555419921875,"offset":1800000},{"adjustmentFactor":-0.9333333373069763,"mired":343.3333435058594,"offset":1800000},{"adjustmentFactor":-0.9222221970558167,"mired":342.22222900390625,"offset":1800000},{"adjustmentFactor":-0.9333333373069763,"mired":343.3333435058594,"offset":1800000,"duration":10800000},{"adjustmentFactor":-0.9555555582046509,"mired":345.5555419921875,"offset":1800000},{"adjustmentFactor":-1,"mired":350,"offset":1800000},{"adjustmentFactor":-1.0444444417953491,"mired":354.4444580078125,"offset":1800000},{"adjustmentFactor":-1.1222221851348877,"mired":362.22222900390625,"offset":1800000},{"adjustmentFactor":-1.211111068725586,"mired":371.1111145019531,"offset":1800000},{"adjustmentFactor":-1.2333333492279053,"mired":382.3333435058594,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":397.4444580078125,"offset":1800000},{"adjustmentFactor":-1.3111110925674438,"mired":416.1111145019531,"offset":1800000},{"adjustmentFactor":-1.4555555582046509,"mired":439.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6333333253860474,"mired":463.3333435058594,"offset":1800000},{"adjustmentFactor":-1.6666666269302368,"mired":470.6666564941406,"offset":1800000},{"adjustmentFactor":-1.6222221851348877,"mired":470.22222900390625,"offset":1800000},{"adjustmentFactor":-1.5777777433395386,"mired":469.77777099609375,"offset":1800000},{"adjustmentFactor":-1.5222222805023193,"mired":469.22222900390625,"offset":1800000},{"adjustmentFactor":-1.4666666984558105,"mired":468.6666564941406,"offset":1800000},{"adjustmentFactor":-1.399999976158142,"mired":468,"offset":1800000},{"adjustmentFactor":-1.3444443941116333,"mired":467.4444580078125,"offset":1800000},{"adjustmentFactor":-1.3666666746139526,"mired":467.6666564941406,"offset":1800000,"duration":10800000},{"adjustmentFactor":-1.399999976158142,"mired":468,"offset":1800000},{"adjustmentFactor":-1.4444444179534912,"mired":468.4444580078125,"offset":1800000},{"adjustmentFactor":-1.5,"mired":469,"offset":1800000},{"adjustmentFactor":-1.4777777194976807,"mired":462.77777099609375,"offset":1800000},{"adjustmentFactor":-1.355555534362793,"mired":447.5555419921875,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":433.4444580078125,"offset":1800000},{"adjustmentFactor":-1.1555556058883667,"mired":419.5555419921875,"offset":1800000},{"adjustmentFactor":-1.1333333253860474,"mired":407.3333435058594,"offset":1800000},{"adjustmentFactor":-1.1888889074325562,"mired":395.8888854980469,"offset":1800000},{"adjustmentFactor":-1.2999999523162842,"mired":385,"offset":1800000},{"adjustmentFactor":-1.288888931274414,"mired":381.8888854980469,"offset":415000}],"adjustmentIid":11,"adjustmentRange":{"min":10,"max":100}},"updateInterval":60000,"notifyIntervalThreshold":600000}}
[26.11.2020, 08:06:56] [Hue] Deckenlampe Büro vorne: set homekit transition control to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-26T07:06:55.870Z","2.1.2.3":"CDA4AD53FE6441D8"},"runtime":150}}`

While the transition control works:

`[26.11.2020, 08:06:56] [Hue] Deckenlampe Büro vorne: homekit adaptive lighting color temperature changed from 250 mired to 265 mired
[26.11.2020, 08:06:56] [Hue] Deckenlampe Büro vorne: set homekit transition control to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-26T07:06:55.870Z","2.1.2.3":"CDA4AD53FE6441D8"},"runtime":187}}
[26.11.2020, 08:06:56] [Hue] Deckenlampe Büro vorne: set homekit transition control to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-26T07:06:55.870Z","2.1.2.3":"CDA4AD53FE6441D8"},"runtime":192}}`

After a restart of homebridge:

`[26.11.2020, 08:15:34] [Hue] Deckenlampe Büro vorne: set homekit transition control to ""`

#### Debug Files
none

**Comment by Einstein2150** [comment]
There is another strange thing with transition control. I put the light in a state of a really warm ct. Activating transition control switches it to mired 261. `[26.11.2020, 08:24:15] [Hue] Deckenlampe Büro vorne: homekit adaptive lighting color temperature changed from 454 mired to 261 mired` but the value of 261 is out of the transition-config 🤔. Looking at the mired values in the setup you can see that it should switch it between 342 (lowest value) and 470 (highest value) !??

**Comment by Einstein2150** [comment]
Looking at another strange light while the transition is working. What the hell is he switching the whole time between 250 and another value?
`[26.11.2020, 08:42:45] [Hue] Kinderschreibtisch rechts: homekit adaptive lighting color temperature changed from 310 mired to 225 mired
[26.11.2020, 08:42:45] [Hue] Kinderschreibtisch rechts: set homekit color temperature from 225 mired to 265 mired
[26.11.2020, 08:42:45] [Hue] Kinderschreibtisch rechts: set homekit color temperature from 265 mired to 225 mired
[26.11.2020, 08:42:48] [Hue] Kinderschreibtisch rechts: set homekit color temperature from 225 mired to 250 mired
[26.11.2020, 08:43:33] [Hue] Kinderschreibtisch rechts: homekit adaptive lighting color temperature changed from 250 mired to 224 mired
[26.11.2020, 08:43:53] [Hue] Kinderschreibtisch rechts: set homekit color temperature from 224 mired to 250 mired
[26.11.2020, 08:44:33] [Hue] Kinderschreibtisch rechts: homekit adaptive lighting color temperature changed from 250 mired to 223 mired
[26.11.2020, 08:44:38] [Hue] Kinderschreibtisch rechts: set homekit color temperature from 223 mired to 250 mired
[26.11.2020, 08:45:33] [Hue] Kinderschreibtisch rechts: homekit adaptive lighting color temperature changed from 250 mired to 223 mired
[26.11.2020, 08:45:38] [Hue] Kinderschreibtisch rechts: set homekit color temperature from 223 mired to 250 mired
[26.11.2020, 08:46:33] [Hue] Kinderschreibtisch rechts: homekit adaptive lighting color temperature changed from 250 mired to 222 mired
[26.11.2020, 08:46:38] [Hue] Kinderschreibtisch rechts: set homekit color temperature from 222 mired to 250 mired`

**Comment by ebaauw** [comment]
> I activated the transition control. At the time of first activation the transition starts and works. After a restart of homebridge it doesn't trigger anymore but he light is still marked as "transition-enabled" in home:

RTFM, https://github.com/ebaauw/homebridge-hue/issues/766#issuecomment-731560178

> Looking at the mired values in the setup you can see that it should switch it between 342 (lowest value) and 470 (highest value) !??

RTFM. Hint: what do you think `adjustmentFactor` means?

> REST Output after clicking "read" in the 0300-cluster of the deCONZ-GUI-node:

So make sure deCONZ has read the Zigbee attributes and exposes the correct `ctmin` and `ctmax` values for all your lights, then restart Homebridge.  Without those settings, Homebridge Hue sets the `ct` to a value not supported by the light.  When the gateway next polls the light, the actual value is returned, and Homebridge Hue updates HomeKit to reflect the actual value.

**Comment by Einstein2150** [comment]
OK, sorry. 1 and 2 are clear now.

> So make sure deCONZ has read the Zigbee attributes and exposes the correct `ctmin` and `ctmax` values for all your lights, then restart Homebridge. Without those settings, Homebridge Hue sets the `ct` to a value not supported by the light. When the gateway next polls the light, the actual value is returned, and Homebridge Hue updates HomeKit to reflect the actual value.

I clicked every light an read every 0300 cluster. Seems that it works now. Is there a faster way than clicking trough the UI of deCONZ? Before adaptive-lightening,  the home-color-picker seems to worked normal so it was in my oppinion not necessary to obtain additional attributes by the manual way from the lights 🤷🏻‍♂️

**Comment by ebaauw** [comment]
The _Temperature_ picker in the Home app conveniently ignores the supported range.  You should be able to see it in Eve.
