### ISSUE TITLE
Remote pressed, action not executed

### ISSUE THREAD

**Issue by Zazou89** [ebaauw/homebridge-hue#838]
#### Issue
Regularly, when I press the buttons on the remote controls, nothing happens. I can clearly see the action in Homebridge. I have to restart Homebridge for it to work.

I use Philipps Dimmer and Ikea remote control.

#### Log Messages

```
[11/30/2020, 10:10:38 AM] [Hue] Télécommande lit Alex On: homekit button single press
[11/30/2020, 10:10:39 AM] [Hue] Télécommande lit Alex On: homekit button single press
```

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5615037/homebridge-hue.json.gz)
[homebridge.log](https://github.com/ebaauw/homebridge-hue/files/5615049/homebridge.log)

**Comment by ebaauw** [comment]
This is unrelated to Homebridge Hue.  It's caused by your Home hub losing the connection to Homebridge.  See e.g. #827.

**Comment by Zazou89** [comment]
I loose the connection everyday currently. Who is the guilty, homebridge or Phoscon ?
