### ISSUE TITLE
Color loop

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#840]
From the last update I notice that the color loop of all color bulbs does not work.
Would you consider this problem?

**Comment by ebaauw** [comment]
It’s working for me on v0.12.4.  Make sure you’ve selected a colour with a high saturation before enabling the colour loop, or you won’t see any differences.  The colour loop only loops over hue.

If it’s not working, please attach the debug dump file, capture and attach a debug log file, and indicate which lights you’re trying.  See the README about the dump and log files.

**Comment by Kristian8606** [comment]
It works but I notice that it does not update the color in the application.
For you, the color is updated in the home or elgato eve application?

**Comment by ebaauw** [comment]
What type of light do you have?  The colour in HomeKit is updated from `xy` (as the `hue` and `sat` values are meaningless), but colour loop uses `hs` mode.  You need a light whose firmware updates `xy` on setting `hue`.  Afaik, that’s only Hue and, I’m told, dresden elektronik lights.

**Comment by Kristian8606** [comment]
The bulb is febite and the rgb controller is gledopto gl-mc01 the strange thing is that a few days ago both updated the color

**Comment by ebaauw** [comment]
What version was that?  What version are you running now?  Did you also update deCONZ?

Please capture and attach a full debug log of the working version and of the non-working version.

**Comment by Kristian8606** [comment]
Is it possible to make changes to the Hue plugin to handle both hue and sat.  Obviously, the latest deconz updates make changes that cause the color update to stop.
As soon as I have the opportunity I will upload a log file.

**Comment by Kristian8606** [comment]
When I activate the color loop and observe it in the decon, I notice that the hue, sat and x, y are updated.
But in the Hue plugin, hue is updated.

![556E97A7-97A1-41EC-A565-1E64D31E9F6A](https://user-images.githubusercontent.com/34716572/101140542-c90cac80-361b-11eb-8882-7bcfef6e846b.png)

**Comment by ebaauw** [comment]
> Is it possible to make changes to the Hue plugin to handle both `hue` and `sat`.

No, `hue` and `sat` are useless.  Their values mean different colours to different light models, and I don't now how to translate these into HomeKit _Hue_ and _Saturation_ values.

> Obviously, the latest deconz updates make changes that cause the color update to stop.

It's actually a change in Homebridge Hue.  I'm now ignoring `xy` values in `colormode` `ct` and `hs`, unless the light has been whitelisted to update `xy` in these colour modes.  This change was needed to support how iOS 14 handles colour temperature.

I only whitelisted Hue and dresden lights, but I stand corrected: there's more lights that actually update `xy` from other colour modes.  At least the Tint by Mueller Light and GLEDOPTO.

> As soon as I have the opportunity I will upload a log file.

Never mind; I have all the info I need to understand what's going on.

But could you please list the exact `manufacturername` of the lights that do update `xy` during colour loop, so I can whitelist them?

Please note that they need to update `xy`; if they only update `hue` and/or `sat`, whitelisting them won't help and will break showing the correct colour when setting `ct` (directly or through adaptive lighting).

**Comment by ebaauw** [comment]
Damn, it's worse.  The Tint and GLEDOPTO do update `xy` when in `hs` colour mode, but not from `ct` colour mode.  I'll change the code only to ignore `xy` in `ct` colour mode, unless whitelisted.  That saves me a lot of whitelisting.

**Comment by ebaauw** [comment]
Fixed in v0.12.6.

**Comment by Kristian8606** [comment]
Thanks!  
And the new colorLoopSpeed ​​feature is super useful.

**Comment by kmplngj** [comment]
Just a question: how do I get the colorloop stuff in HomeKit? 🤪 I could not find it.

**Comment by Kristian8606** [comment]
Try this app if you don't have it.  Also your bulb needs to support it.

https://apps.apple.com/bg/app/eve-for-homekit/id917695792
