### ISSUE TITLE
New Error with 0.12.7

### ISSUE THREAD

**Issue by TheBassfly** [ebaauw/homebridge-hue#845]
I updated my Homebridge Hue Plugin and now the Bridge doesn't start with the following error:

Dec 05 17:47:30 raspberrypi homebridge[2445]:     at newError (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:26:10)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:331:25)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at ClientRequest.emit (events.js:315:20)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at Object.onceWrapper (events.js:421:28)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at TLSSocket.emit (events.js:327:22)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at TLSSocket.Socket._onTimeout (net.js:483:8)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at listOnTimeout (internal/timers.js:554:17)
Dec 05 17:47:30 raspberrypi homebridge[2445]:     at processTimers (internal/timers.js:497:7)
And after this the Bridge ist shutting down.

**Comment by ebaauw** [comment]
Please attach the full debug log file.

**Comment by michaelstein60** [comment]
I'm seeing the same issue. I can post the log later today. I also found that the error persists even if I roll back to an earlier version of homebridge-hue. I have to restore a full backup SD image to recover the system.

**Comment by DrDoom666** [comment]
Same here. Even with roll back to previous version the error remains, homebridge is in boot loop...

Error: registry.npmjs.org: timeout after 5 seconds
at newError (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:26:10)
at ClientRequest. (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:331:25)
at ClientRequest.emit (events.js:315:20)
at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
at Object.onceWrapper (events.js:421:28)
at TLSSocket.emit (events.js:327:22)
at TLSSocket.Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)

**Comment by DrDoom666** [comment]
I have updated 0.12.4 to 0.12.6  -->  I have got the 5s timeout error, but homebridge was still starting and even all hue/deconz components worked fine...

I have updated 0.12.6 to 0.12.7  -->  I have got the 5s timeout error and nothing worked any more...

**Comment by ebaauw** [comment]
> Can you set the timeout to 30s or 60s ?

Yes, set `timeout` in config.json.

Please attach a debug log file, so I can see what's going on.

**Comment by ebaauw** [comment]
If contacting the NPM registry fails, Homebridge exits due an unchecked error in Homebridge Hue v0.12.7. The NPM registry isn't the most stable service on the Internet, so the error will be intermittent.

Homebridge Hue v0.12.8 should fix this (and some more possible unchecked errors).
