### ISSUE TITLE
Warning: using default colour gamut for unknown light model "Paul Neuhaus"

### ISSUE THREAD

**Issue by DerHendrikS** [ebaauw/homebridge-hue#850]
Hi Erik,

i have the same issue described here [#455](https://github.com/ebaauw/homebridge-hue/issues/455) with the difference that the **manufacturername** and **modelid** the  of my light does **not** end with a **space** character.

Here the warning of the home bridge plugin:
`Phoscon-GW: /lights/11: warning: using default colour gamut for unknown light model {"colorcapabilities":31,"ctmax":370,"ctmin":200,"etag":"4ffbb3c855f7275d73b88b601fc0ce60","hascolor":true,"lastannounced":"2020-12-09T15:44:33Z","lastseen":"2020-12-09T15:52Z","manufacturername":"Neuhaus Lighting Group","modelid":"NLG-RGBW light","name":"Küchenlampe","state":{"alert":"none","bri":149,"colormode":"hs","ct":250,"effect":"none","hue":6069,"on":true,"reachable":false,"sat":220,"xy":[0.4623,0.4149]},"swversion":"1001-0007","type":"Extended color light","uniqueid":"00:15:8d:00:02:a1:59:a9-02"}`

The suggested command
`ph probe -v /lights/11`

gives me following output:
```
ph probe: /lights/11: cool ... done
ph probe: /lights/11: warm ... done
ph probe: /lights/11: red ............... timeout
ph probe: /lights/11: green ............... timeout
ph probe: /lights/11: blue ............... timeout
{
  "manufacturername": "Neuhaus Lighting Group",
  "modelid": "NLG-RGBW light",
  "type": "Extended color light",
  "bri": true,
  "ct": {
    "min": 200,
    "max": 370
  },
  "xy": {
    "r": [
      0.9961,
      0.0001
    ],
    "g": [
      0.0001,
      0.9961
    ],
    "b": [
      0.0001,
      0.0001
    ]
  }
}
```

Erik, can you update your file HueLight.js again to suppress the error message?

Kind regards
Hendrik

**Comment by ebaauw** [comment]
Is this a different light model or firmware, or is deCONZ now trimming the names?

**Comment by DerHendrikS** [comment]
My light model seems to have the same firmware version 1001-0007 as the model from issue #445. So it is possible, that deCONZ is trimming trailing spaces.

**Comment by DerHendrikS** [comment]
No more warning since v0.12.11

Great, Thank you
Hendrik

**Comment by ebaauw** [comment]
Please open a new issue, rather than hijacking one that's been closed for almost a year.
