### ISSUE TITLE
Changing websocketport

### ISSUE THREAD

**Issue by llamafilm** [ebaauw/homebridge-hue#851]
A few days ago, I installed a web server on the same machine running Homebridge.  It needs port 443 so I had to move deconz web socket port to a different port.  Since then, Homebridge has been working okay, but I noticed an error every few seconds in the log:
```
Phoscon-GW: websocket communication error Unexpected server response: 400
```

I could not find any description of this issue, but looking through the source code I see it's an easy fix, just add `websocketport` to config.json.  I suggest documenting this somewhere.

**Comment by ebaauw** [comment]
No, I'm not going to do that.  deCONZ reports the port it uses for the web socket over the API.  Homebridge Hue connects to that port.

**Comment by llamafilm** [comment]
Oh that's good!  I probably just forgot to restart Homebridge then.  Sorry about that.
