### ISSUE TITLE
Target NodeJS 12?

### ISSUE THREAD

**Issue by Bouke** [ebaauw/homebridge-hue#853]
Currently this package requires NodeJS 14 or newer. My Raspberry running Raspbian Stretch only provides v12 (12.20.0), which is [still supported](https://nodejs.org/en/about/releases/) until 2022-04-30. Upgrading NodeJS is a hassle, as it would require building NodeJS from sources, which I rather not do.

Is it feasible for this package to continue supporting NodeJS v12 for some time?

**Comment by ebaauw** [comment]
That depends on your definition of “support”.  I develop and test against the latest LTS version of NodeJS.  I simply don’t have the bandwidth to test any other versions.  I haven’t done anything (at least consciously) to break my plugins on v12.x, so they’ll probably work, but sometimes some very subtle differences between NodeJS versions might break something.

**Comment by Einstein2150** [comment]
Raspbian buster

> Currently this package requires NodeJS 14 or newer. My Raspberry running Raspbian Stretch only provides v12 (12.20.0), which is [still supported](https://nodejs.org/en/about/releases/) until 2022-04-30. Upgrading NodeJS is a hassle, as it would require building NodeJS from sources, which I rather not do.
> 
> Is it feasible for this package to continue supporting NodeJS v12 for some time?

Isn't `sudo n lts` installing the latest 14.15.1?

**Comment by ebaauw** [comment]
I’m running NodeJS v14 on Stretch, installed through `apt`.  See https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions.

**Comment by Bouke** [comment]
As an FOSS contributor I understand your position regarding time investment. The following is just a somewhat scary warning:

> <img width="488" alt="image" src="https://user-images.githubusercontent.com/235882/101920326-f2a17700-3bcb-11eb-9cd2-de13acc8d653.png">

Thank you for pointing me to nodesource. I've upgraded to Node 14 now and things seem to work fine thus far.
