### ISSUE TITLE
TY0202 is active but nothing is detected

### ISSUE THREAD

**Issue by feimat28** [ebaauw/homebridge-hue#854]
#### Issue

The LIDL/Silvercrest TY0202 is added in deconz and seen in Homekit (as well in Home Assistant), but no sensor updates are given. When motion is detected the sensor's red light blinks. In both Homekit and Home Assistant the sensor gives "not detected"/ "no presence".

Since I saw a warning (see below) while starting Homebridge I thought this was te place to go.
Note: I run two instances of Homebridge (on for Homekit and one for Google Home), but both give me the same result 

#### Log Messages

```
[10-12-2020 12:25:48] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0
[10-12-2020 12:25:48] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.5.88
[10-12-2020 12:25:49] [Hue] Phoscon-GW: /sensors/11: warning: unknown ZHAPresence sensor {"config":{"battery":100,"duration":60,"on":true,"pending":[],"reachable":false},"ep":1,"etag":"32db982a3b3076d6870b78ad6dc74c0e","lastseen":null,"manufacturername":"SILVERCREST","modelid":"TY0202","name":"TY0202","state":{"lastupdated":"none","lowbattery":null,"presence":null,"tampered":null},"swversion":"2019.12.12","type":"ZHAPresence","uniqueid":"bc:33:ac:ff:fe:34:c9:b8-01-0500"}
[10-12-2020 12:25:49] [Hue] Phoscon-GW: 14 accessories
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5672446/homebridge-hue.json.gz)

[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/5672525/homebridge.log.gz)]

**Comment by feimat28** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5672543/homebridge-hue.json.gz)
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/5672544/homebridge.log.gz)

Apparently they didn't come through the first time

**Comment by ebaauw** [comment]
Did you double-check in the deCONZ GUI that the sensor has enrolled?

**Comment by feimat28** [comment]
This is what my deCONZ GUI looks like:
![Schermafbeelding 2020-12-10 om 19 30 41](https://user-images.githubusercontent.com/75787627/101814313-43f32d00-3b1e-11eb-9b1c-f6df588790cb.png)

**Comment by ebaauw** [comment]
Please check out the user manual (under help).  You need to select the _IAS Zone_ cluster in the sensor, open the _Cluster Info_ panel, wake the sensor by waving in front of it and read the attributes.  It should be enrolled, and the coordinator's MAC address should be read for _IAS CIE address_.  If not, write the coordinator's mac address to this field.  For deCONZ support, please see the deCONZ Discord or GitHub repository.

**Comment by feimat28** [comment]
In Debug View with INFO checked this keeps coming every 3-5 minutes:

'''
19:46:28:642 DeviceAnnce of SensorNode: 0xBC33ACFFFE34C9B8 [1]
19:46:30:670 Bind response success for 0xbc33acfffe34c9b8 ep: 0x01 cluster: 0x0500
19:46:33:699 ZCL attribute report 0xBC33ACFFFE34C9B8 for cluster: 0x0001, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
'''

**Comment by feimat28** [comment]
Thank you very much, that worked! (Feel quiet stupid for not knowing how to do this..)

**Comment by yberion20** [comment]
Do you happen to know whether I can arrange this setting via ssh (headless)?
