### ISSUE TITLE
The problem with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by Alexandr137** [ebaauw/homebridge-hue#855]
Hello
after reboot, homebridge does not start, gives an error
Hoobs, Huу and Deconz all latest version

11.12.2020, 09:18:29 HOOBS listening on port 80.
11.12.2020, 09:18:34 Loaded plugin 'homebridge-hue'
11.12.2020, 09:18:34 [12/10/2020, 11:18:34 PM] Registering platform 'homebridge-hue.Hue'
11.12.2020, 09:18:35 Loaded plugin 'homebridge-samsung-tizen'
11.12.2020, 09:18:35 [12/10/2020, 11:18:35 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
11.12.2020, 09:18:35 Loading 2 platforms...
11.12.2020, 09:18:35 [Hue] Initializing Hue platform...
11.12.2020, 09:18:35 [Hue] config.json: warning: plugin_map: ignoring unknown key
11.12.2020, 09:18:35 [Hue] homebridge-hue v0.12.11, node v14.15.1, homebridge v1.1.6
11.12.2020, 09:18:35 [SamsungTizen] Initializing SamsungTizen platform...
11.12.2020, 09:18:35 External port pool ran out of ports. Fallback to random assign.
11.12.2020, 09:18:35 TV is running on port 38115.
11.12.2020, 09:18:35 Please add [TV] manually in Home app. Setup Code: 031-45-154
11.12.2020, 09:18:36 [Hue] searching bridges and gateways
11.12.2020, 09:18:41 [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0
11.12.2020, 09:18:41 [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0
11.12.2020, 09:18:41 [Hue] Phoscon-GW: 4 accessories
11.12.2020, 09:18:41 [Hue] Phoscon-GW: 4 accessories
11.12.2020, 09:18:41 [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
11.12.2020, 09:18:41 Initializing platform accessory 'Phoscon-GW'...
11.12.2020, 09:18:41 [Hue] Phoscon-GW: 2 services
11.12.2020, 09:18:41 Initializing platform accessory 'Daylight'...
11.12.2020, 09:18:41 Initializing platform accessory 'Multi Sensor'...
11.12.2020, 09:18:41 Initializing platform accessory 'Thermostat'...
11.12.2020, 09:18:41 Initializing platform accessory 'Phoscon-GW'...
11.12.2020, 09:18:41 [Hue] Phoscon-GW: 2 services
11.12.2020, 09:18:41 [Hue] homebridge: error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b77dffa3-e3b0-4c2f-8a7a-ea7635d8f4d9
11.12.2020, 09:18:47 [TV] Failed to pair! Make sure TV is online and you click "Allow" on the popup
11.12.2020, 09:19:06 [Hue] heartbeat 6, drift 18003
11.12.2020, 09:19:06 [Hue] heartbeat 7, drift 17004
11.12.2020, 09:19:06 [Hue] heartbeat 8, drift 16006
11.12.2020, 09:19:06 [Hue] heartbeat 9, drift 15007
11.12.2020, 09:19:06 [Hue] heartbeat 10, drift 14009
11.12.2020, 09:19:06 [Hue] heartbeat 11, drift 13012
11.12.2020, 09:19:06 [Hue] heartbeat 12, drift 12014
11.12.2020, 09:19:06 [Hue] heartbeat 13, drift 11017
11.12.2020, 09:19:06 [Hue] heartbeat 14, drift 10019
11.12.2020, 09:19:06 [Hue] heartbeat 15, drift 9019
11.12.2020, 09:19:06 [Hue] heartbeat 16, drift 8023
11.12.2020, 09:19:06 [Hue] heartbeat 17, drift 7025
11.12.2020, 09:19:06 [Hue] heartbeat 18, drift 6027
11.12.2020, 09:19:06 [Hue] heartbeat 19, drift 5028
11.12.2020, 09:19:06 [Hue] heartbeat 20, drift 4028
11.12.2020, 09:19:06 [Hue] heartbeat 21, drift 3031
11.12.2020, 09:19:06 [Hue] heartbeat 22, drift 2033
11.12.2020, 09:19:06 [Hue] heartbeat 23, drift 1034
11.12.2020, 09:20:05 [Hue] Thermostat: set homekit status fault from 1 to 0
11.12.2020, 09:20:05 [Hue] Thermostat: set homekit status fault from 1 to 0
11.12.2020, 09:20:32 Loaded plugin 'homebridge-hue'
11.12.2020, 09:20:32 [12/10/2020, 11:20:32 PM] Registering platform 'homebridge-hue.Hue'
11.12.2020, 09:20:32 Loaded plugin 'homebridge-samsung-tizen'
11.12.2020, 09:20:32 Loading 2 platforms...
11.12.2020, 09:20:32 [12/10/2020, 11:20:32 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
11.12.2020, 09:20:32 [Hue] Initializing Hue platform...
11.12.2020, 09:20:32 [Hue] config.json: warning: plugin_map: ignoring unknown key
11.12.2020, 09:20:32 [Hue] homebridge-hue v0.12.11, node v14.15.1, homebridge v1.1.6
11.12.2020, 09:20:32 [SamsungTizen] Initializing SamsungTizen platform...
11.12.2020, 09:20:33 External port pool ran out of ports. Fallback to random assign.
11.12.2020, 09:20:33 TV is running on port 34549.
11.12.2020, 09:20:33 Please add [TV] manually in Home app. Setup Code: 031-45-154
11.12.2020, 09:20:33 Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
11.12.2020, 09:20:33 Got SIGTERM, shutting down Bridge...
11.12.2020, 09:20:33 [Hue] searching bridges and gateways
11.12.2020, 09:20:36 [Hue] goodbye

**Comment by ebaauw** [comment]
I see a number of issues with your installation:
- Homebridge Hue seems to find your gateway twice?  Please attach your config.json, the debug dump file, and list the output of `ph discover -v`.  This causes the error message, but doesn’t cause Homebridge to stop;
- Something is blocking NodeJS for 18 seconds during startup.  Typically this is caused by another plugin doing synchronous I/O;
- You seem to be trying to run Homebridge multiple times, causing a conflict on the port for the TV, and causing a Bonjour name conflict that causes Homebridge to stop.

**Comment by Alexandr137** [comment]
Here is ph discover -v's output
{
  "deconz": {
    "10.0.1.196:1881": "00212EFFFF060C9D"
  },
  "meethue": {},
  "upnp": {
    "10.0.1.196:1881": "00212EFFFF060C9D"
  }
}


its config 
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": ",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "ru",
        "temp_units": "celsius",
        "country_code": "RU",
        "postal_code": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "",
        "username": ""
    },
    "description": "",
    "ports": {},
    "plugins": [
        "homebridge-hue",
        "homebridge-samsung-tizen"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "users": {
                "00212EFFFF060C9D": "89FADE6BF7"
            },
            "lights": true,
            "sensors": true,
            "wallSwitch": true
        },
        {
            "platform": "SamsungTizen",
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "TV",
                    "ip": "10.0.1.147",
                    "mac": "84:C0:EF:E3:6B:1F",
                    "inputs": [
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "YouTube",
                            "type": "app",
                            "value": "111299001912"
                        }
                    ],
                    "keys": {
                        "INFORMATION": "KEY_HOME"
                    }
                }
            ]
        }
    ],
    "package_manager": "npm",
    "system": "hoobs"
}

**Comment by Alexandr137** [comment]
unfortunately I could not find the dump file

**Comment by ebaauw** [comment]
> 11.12.2020, 09:18:41 [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz

**Comment by Alexandr137** [comment]
yes everything is correct this is a working config
I found a debug file, but I do not know how to get it from homebridge

**Comment by ursusHU** [comment]
I had exactly the same issue when I decided to leave Hoobs and switched to Homebridge.
You could try to reset your Homekit connection in Hoobs.

**Comment by Alexandr137** [comment]
I don't even connect the Hoobs to the Homekit
I put a clean Hombridge and tuned hue
I made a log, the same error
[homebridge.log.txt](https://github.com/ebaauw/homebridge-hue/files/5698235/homebridge.log.txt)

**Comment by ebaauw** [comment]
Homebridge Hue still seems to find your gateway twice.
```
[15/12/2020, 22:49:35] [Hue] searching bridges and gateways
[15/12/2020, 22:49:40] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0
[15/12/2020, 22:49:40] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0
```
I have no idea why.

As workaround, try and set `"hosts": ["10.0.1.196:1881"]` in config.json, to disable discovery.

**Comment by Alexandr137** [comment]
Everything worked out
Helped: As workaround, try and set "hosts": ["10.0.1.196:1881"] in config.json, to disable discovery.

Thank you
