### ISSUE TITLE
Phoscon-GW: RaspBee/ConBee not yet initialised - wait 1 minute [deCONZ/ConBeeII]

### ISSUE THREAD

**Issue by beniaminrychter** [ebaauw/homebridge-hue#857]
#### Issue
Hi everyone. I'm struggling with error during booting up my homebridge with homebridge-hue plugin. I've installed hombridge on docker as well as deCONZ. deCONZ and Phoscon are running great, all my Zigbee devices working properly, connection with ConBeeII is set. 

But the problem is to connect deCONZ with Homebridge. Before restarting Homebrige I've ofcourse gone to Phoscon -> Gateway -> Advanced and clicked: "Atuhenticate App". But it not helps at all. I really don't know what to do with that. 

Below I post screenshots of my installation and console logs.

#### Log Messages
```
[12/12/2020, 1:25:22 PM] [Hue] searching bridges and gateways
[12/12/2020, 1:25:27 PM] [Hue] Phoscon-GW: RaspBee/ConBee not yet initialised - wait 1 minute
[12/12/2020, 1:25:42 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[12/12/2020, 1:26:02 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[12/12/2020, 1:26:22 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
```

Config
```
        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "forceHttp": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue"
        }
```

#### Screenshots
![Zrzut ekranu 2020-12-12 o 13 34 19](https://user-images.githubusercontent.com/27733472/101983991-bf6bf000-3c7e-11eb-95ad-810ae4a92188.png)
![Zrzut ekranu 2020-12-12 o 13 34 14](https://user-images.githubusercontent.com/27733472/101983995-cd217580-3c7e-11eb-8c55-beb0058922ca.png)

**Comment by ebaauw** [comment]
> [12/12/2020, 1:25:27 PM] [Hue] Phoscon-GW: RaspBee/ConBee not yet initialised - wait 1 minute

The deCONZ REST API plugin returns a `bridgeid` of `0000000000000000`, instead of the Mac address of the RaspBee or ConBee.  Typically this indicates that deCONZ hasn't connected to the coordinator device.  Homebridge Hue deliberately prevents Homebridge from starting, so you won't lose any accessories from HomeKit.

**Comment by beniaminrychter** [comment]
I can not agree with this answer, because I've tried to connect with deCONZ through "Hue Essentials" app on my iPhone and everything went fine and the app is connected to deCONZ and I can control all my ZigBee units. So it has to be something with plugin it-self or my homebridge installation.
