### ISSUE TITLE
Support Ledvance (Osram) Smart+ Switch Mini

### ISSUE THREAD

**Issue by jeroen020** [ebaauw/homebridge-hue#858]
Just go a couple of Ledvance (formerly Osram) [Smart+ Switch Mini](https://www.ledvance.com/consumer/products/smart-home/smart-home-products-with-zigbee-technology/smart-home-components/smart-switch-mini/index.jsp) Zigbee switches. deCONZ discovers them as a switch (Vendor: OSRAM Product: Lightify switch mini). When I look in Homebridge under Accessories, only the battery percentage is reported, but the switch itself does nothing. Homekit shows it as a tile with a house icon and in red text 'Not Supported'. After starting homebridge-hue the log shows the following:

```
[15/12/2020, 15:54:21] [Hue] Phoscon-GW: /sensors/64: warning: ignoring unknown ZHASwitch sensor {"config":{"battery":100,"group":"6","on":true,"reachable":true},"ep":1,"etag":"aa0aa4e4b8a70771325d0d0674feca25","lastseen":"2020-12-15T14:40Z","manufacturername":"OSRAM","mode":1,"modelid":"Lightify Switch Mini","name":"Lightify switch mini","state":{"buttonevent":2002,"lastupdated":"2020-12-15T09:54:22.159"},"type":"ZHASwitch","uniqueid":"00:0d:6f:00:13:f4:df:35-01-0006"}
```
Any chance there's a way to get this switch to work? I'd gladly send one over if that helps.

**Comment by ebaauw** [comment]
> Any chance there's a way to get this switch to work? I'd gladly send one over if that helps.

Thanks, but if it's already supported by the deCONZ REST API plugin, I don't need access to the physical device.  I do need to know: how many buttons it has; the names of buttons; and the `buttonevent` values the switch generates.

**Comment by jeroen020** [comment]
Thanks!

> how many buttons it has
3

> the names of buttons
They're an up arrow, circle in the middle, and down arrow. Or is there somewhere I can find the names in deCONZ?

> and the buttonevent values the switch generates.
This is what I found in the log (a section of my earlier post):
`"buttonevent":2002,"lastupdated":"2020-12-15T09:54:22.159"},"type":"ZHASwitch","uniqueid":"00:0d:6f:00:13:f4:df:35-01-0006"`
Is that what you need?

Much appreciated!

**Comment by ebaauw** [comment]
Found the buttonmap for the switch.  Apparently they're called "Up", "Down", and "Middle".  Looks like all three support _Single Press_ and _Long Press_.

**Comment by jeroen020** [comment]
Thanks for implementing this so quickly! Looking forward to find it in the next update of the plugin!

**Comment by jeroen020** [comment]
Just checked the update and can confirm it works. Thanks again!
