### ISSUE TITLE
http status 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by dibimuc** [ebaauw/homebridge-hue#862]
#### Issue

I use Home+ for changing the brightness of my bulbs. I know that the problem "bri is not modifiable" is a structural problem with HomeKit. Nevertheless I suppose that the 503 Error which is new causes a problem. The problem is that the light, after changing the brightness with a scene - is not accessible anymore. But you're able switch the light on or off. The HomeKit icon then only shows on or off not the brightness level in %. By Changing the level manually in the Home App, the bulb is accessible again and the correct %-value is shown.

I run Node version 12.14.1 (cannot update because using Hoobs).

#### Log Messages

[Hue] http status 503 Service Temporarily Unavailable
[Hue] Philips hue: bridge request 20086: error 201 parameter, bri, is not modifiable. Device is set to off.
22.12.2020, 16:53:09
[Hue] Philips hue: bridge request 20087: put /lights/12/state {"bri":89}

22.12.2020, 17:11:55 npm
22.12.2020, 17:11:55 
22.12.2020, 17:11:55 WARN
22.12.2020, 17:11:55 
22.12.2020, 17:11:55 notsup
22.12.2020, 17:11:55  Unsupported engine for homebridge-hue@0.12.11: wanted: {"BSB001":"1.16.0","BSB002":"1.41.0","deCONZ":"2.7.1","homebridge":"^1.1.0","node":"^14.15.1"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN
22.12.2020, 17:11:55 
22.12.2020, 17:11:55 notsup Not compatible with your version of node/npm: homebridge-hue@0.12.11
22.12.2020, 17:11:55 npm WARN notsup Unsupported engine for homebridge-lib@4.8.4: wanted: {"homebridge":"^1.1.0","node":"^14.15.2"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN
22.12.2020, 17:11:55 
22.12.2020, 17:11:55 notsup Not compatible with your version of node/npm: homebridge-lib@4.8.4
22.12.2020, 17:11:55 
22.12.2020, 17:11:55 + homebridge-hue@0.12.11
updated 3 packages in 22.851s
22.12.2020, 17:11:56 
15 packages are looking for funding
  run `npm fund` for details
22.12.2020, 17:12:03 Plugin "homebridge-hue" updated.

**Comment by ebaauw** [comment]
Please capture and attach a full debug log file, and attach the debug dump file.

**Comment by dibimuc** [comment]
[homebridge.log-parallelrequest5.txt](https://github.com/ebaauw/homebridge-hue/files/5731289/homebridge.log-parallelrequest5.txt)
[logs-2.txt](https://github.com/ebaauw/homebridge-hue/files/5731290/logs-2.txt)

**Comment by ebaauw** [comment]
Thanks.

The old logs are very useful: they confirm my suspicion that the latest Hue bridge firmware, v1941132080, is acting differently.  There's no 503 HTTP status errors with the previous version, v1941056000.

Otherwise, see https://github.com/ebaauw/homebridge-hue/issues/848.  Homebridge Hue v0.12.12 should deal adequately with the changed Hue bridge firmware, although you might see some `MaxListenersExceededWarning` messages.
