### ISSUE TITLE
What could be causing heartbeat/drift messages on logs ?

### ISSUE THREAD

**Issue by AllSeeingGoatWizard** [ebaauw/homebridge-hue#863]
I've just installed hb-hue with deconz and conbee 2. Everything is working and stable but I keep getting heartbeat and drift messages on logs quite a bit. I found that a motion sensors Lux value takes forever to update to homeapp but motion detection is fast. Could this be causing these messages? I'm not that good at this stuff so I could troubleshoot it myself.

**Comment by ebaauw** [comment]
The drift messages indicate that something is blocking NodeJS, causing the scheduled heartbeat to be delayed. Might be the system is overloaded, might be another plugin doing synchronous I/O.  See #737.

What motion sensor?  Define "forever".  Does the `lightlevel` attribute in the API also take "forever" to update?

**Comment by AllSeeingGoatWizard** [comment]
Aqara motion sensor. Lux takes minutes to update. Cpu at 3-7%.

**Comment by AllSeeingGoatWizard** [comment]
Would excluding lux as a value from that sensors stop this behaviour? I don't really need that as an automation trigger.

**Comment by ebaauw** [comment]
I don't think the heartbeat drift is related to the light sensor.

I don't know the Aqara motion sensor, but typically motion sensors only update their `lightlevel` periodically and when detecting motion.  Without motion, it might take the Hue motion sensor up to 5 minutes to report changed light level.  To preserve the battery, the sensor is asleep most of the time, and only wakes on regular intervals and when detecting motion.

**Comment by AllSeeingGoatWizard** [comment]
Uninstalling the verified network precence plugin seems to have gottem rid of those messages in the log.
