### ISSUE TITLE
adaptive lighting StartTime

### ISSUE THREAD

**Issue by JanLp** [ebaauw/homebridge-hue#864]
Anyone can tell me why StartTime is 15:23:15, should StartTime be 16:23:15?

`[25/12/2020, 16:23:15] [Hue] Køkkenloft: set homekit transition control to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-12-25T15:23:15.682Z","2.1.2.3":"35A8179523860A81"},"runtime":124}}`

**Comment by ebaauw** [comment]
No, it should not, see https://en.wikipedia.org/wiki/ISO_8601.
