### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#865]
Hello, Merry Christmas!
Is it possible for `ctMax` `ctMin` to be set dynamically? That is, the `ctMax` `ctMin` characteristic from homekit should be set to the maximum and minimum values for each bulb. Thus, the user experience with the temperature wheel in homekit will be more expensive.
Excuse my bad English, I hope you understand my question.

**Comment by ebaauw** [comment]
Please send your feature request to Apple.

Homebridge Hue already sets the minValue and maxValue properties for _ColorTemperature_ to the light’s minimum and maximum supported values.  Apple’s Home app gracefully ignores these, but other HomeKit apps do honour these settings.
