### ISSUE TITLE
Loosing all Hue Devices after a few seconds

### ISSUE THREAD

**Issue by mareeekkkk** [ebaauw/homebridge-hue#866]
Similar issue to #824 

Hi! 
After updating the homebridge-hue plugin some days ago, all lights defaulted back to the Standardroom. After a few seconds, they disappear. Every other Homebridge Accessory is running good (Samsung Tizen, Unifi Protect Camera etc.)

I did a clean install of homebridge with LTS version of Homebridge, homebridge-hue and node / npm. Still no change, same problem occurs. The lights come back after a homebridge restart and then disappear after a few seconds. 

Switched to Homebridge 1.3.0-beta.33 like described in #824. Still no change, same behaviour. 

Heres a debug dump: 
[homebridge-hue.json.zip](https://github.com/ebaauw/homebridge-hue/files/5744659/homebridge-hue.json.zip)

Thank you for your support! If more information or testing is required i will provide what i can 👍

**Comment by ebaauw** [comment]
This is probably caused by the Hue app, syncing HomeKit with the Hue bridge configuration, or by an old iOS version, causing the sync over iCloud between your devices to fail.  See #813.

**Comment by mareeekkkk** [comment]
I created a new HomeKit "Home" with no sharing. Removed all other iCloud devices from Home-Sync. Added only homebridge and didn't touch the Hue-App at all. It's not added as accessory nor configured for HomeKit use. 

Same issue as before. All lights disappear after a few seconds.

**Comment by ebaauw** [comment]
As I explain in #813, technically Homebridge Hue cannot make accessories disappear.

> Removed all other iCloud devices from Home-Sync.

I have no idea what that means.  Did you turn of _Home_ under _Apps using iCloud_ in the _iCloud_ settings of all your devices (except the one you're using to interact with the new home).  Including any Home hub(s)?  It's probably easier to create the new home under a different iCloud account.

**Comment by mareeekkkk** [comment]
Yes, turned off the iCloud syncs for all devices using this iCloud account. I started a new issue on the Homebridge Github. #2760 
If its not a Plugin issue i hope there is some solution to the problem. I am curious because i have multiple places where i maintain homebridge setups with the same configuration (homebridge+hue) and they all run the same softwareversions and i never had this problem before.

**Comment by ebaauw** [comment]
Are you saying it's also accessories by other plugins?  In that case, it's probably an issue with Homebridge starting with the wrong configuration, not exposing any accessories, and HomeKit kicking them out.  After you restart Homebridge with the right config, the accessories are re-exposed, but HomeKit sees them as new accessories.  Double-check how you start Homebridge, under which user, with which user directory (containing `config.json`), using `sudo` or not, etc.  Are you sure you changed the `username` in the `bridge` section when creating a new Homebridge instance?

**Comment by mareeekkkk** [comment]
Sorry, i wrote it wrong in the Homebridge Issue #2760. Its only the hue lights that disappear. I will doublecheck everything tomorrow. But i already did a clean install of the raspberry following the official install guide, and the same problem occured. 
More and more, i am concerned that it has something to do with the iCloud or iOS device setup.

**Comment by ebaauw** [comment]
> More and more, i am concerned that it has something to do with the iCloud or iOS device setup.

That, or the Hue app syncing the Hue bridge config with HomeKit.  I'll refrain from exposing _Unqiue ID_ in the next version of Homebridge Hue, so the Hue app should no longer mess with accessories exposed by Homebridge Hue.

**Comment by mareeekkkk** [comment]
Just to update you on this issue. I sorted it out by removing all devices from the iCloud Home sync, creating a new home and adding a fresh install of homebridge to Homekit. So issues since then.
Thanks for your support!
