### ISSUE TITLE
Philips Hue Dimmer causing Heartbeat Errors

### ISSUE THREAD

**Issue by Marfre888** [ebaauw/homebridge-hue#867]
-->
#### Issue
Hi, I have two Philips Dimmer Hue connected to Deconz, which get almost no use. I have been noticing recently that when the switches update their battery percentage, homebridge Hue heartbeat drifts for a couple of seconds. The problem seems intermittent as most of the time it seems to update perfectly fine, but the heartbeat drift seems to be exclusively tied with the Philips dimmers as none of my other devices attached to Deconz seem to trigger the drift. I have also tried downgrading to version 0.12.0 and the problem persists

#### Log Messages

```
[37m[12/27/2020 15:50:01] [39m[36m[Hue] [39mShades Switch: set homekit battery level from 67% to 86%
[37m[12/27/2020 15:51:35] [39m[36m[Hue] [39m[33mheartbeat 126, drift 403[39m
[37m[12/27/2020 15:51:37] [39m[36m[Hue] [39m[33mheartbeat 127, drift 1135[39m
[37m[12/27/2020 15:51:37] [39m[36m[Hue] [39m[33mheartbeat 128, drift 532[39m
[37m[12/27/2020 15:51:38] [39m[36m[Hue] [39m[33mheartbeat 129, drift 261[39m
```

```
[37m[12/27/2020 16:39:25] [39m[36m[Hue] [39mWindows Switch: set homekit battery level from 95% to 93%
[37m[12/27/2020 16:39:44] [39m[36m[Hue] [39m[33mheartbeat 125, drift 974[39m
[37m[12/27/2020 16:39:45] [39m[36m[Hue] [39m[33mheartbeat 126, drift 965[39m
[37m[12/27/2020 16:39:45] [39m[36m[Hue] [39m[33mheartbeat 127, drift 338[39m

```

#### Other
I also seem to be running a memory leak. I've traced it down to Adaptive lighting and downgrading to 0.12.2 seemed to have fixed it. but I cannot reproduce it on command as it takes a couple of hours to build up. Will write a separate issue regarding that.

**Comment by ebaauw** [comment]
See my reply to the other issue about the meaning of the drift messages.  These are unrelated to the Hue dimmer switch.

**Comment by Marfre888** [comment]
@ebaauw I understand that they are unrelated to the dimmer itself. However, the drift messages are only produced when these two dimmer switches checks for battery level. Even then it is about once every 10 times

I have 15 other sensors and none produce any drift messages when these check for battery level

**Comment by ebaauw** [comment]
There's over 1.5 minutes between the update message and the drift message in your first example, and 19 seconds in the second example.  If they were related, the drift would be in the order of 90000 and 19000 respectively.

I have no idea what you mean by "when these two dimmer switches checks for battery level".  The Hue dimmer switch sends an attribute report for _Battery Percentage Remaining_ to the Hue bridge every 5 minutes; the Hue bridge updates `config.battery` if it the percentage has changed.  Homebridge Hue sees the changed value when it polls the Hue bridge on the next heartbeat, and updates the HomeKit value, while issuing the log message.  The check whether the value has changed happens on every heartbeat.

**Comment by Marfre888** [comment]
What I'm trying to say is the drift messages are reported after homebrdige hue issues a battery report for these dimmer switches, but otherwise it doesn't report any drift messages.

Could I monitor what I causing these drift messages?

**Comment by ebaauw** [comment]
Monitor the system load (e.g. using `htop`) and the Raspberry Pi hardware, see https://github.com/ebaauw/homebridge-rpi/wiki/Hardware-Monitoring.

If these values are normal, the cause within the NodeJS, probably a plugin doing synchronous I/O.  I'm afraid that's trial and error, disabling all plugins and adding them back one by one.
