### ISSUE TITLE
Hue Scenes

### ISSUE THREAD

**Issue by cdaniels77** [ebaauw/homebridge-hue#871]
Hello sir,

I’m new to the homebridge, so I apologize if I make a newbie mistake

I’m downloaded your Hue Plug-In, I was able to see my hue lights in homebridge and HomeKit, the issue I’m having is my Hue scenes are not showing up in homebridge or HomeKit. I have the expose scene set to yes. Am I missing something?

My hue bridge is updates with the last east version and also you plug in is the latest version.

**Comment by ebaauw** [comment]
The scenes are exposed under the `/groups` accessory, so you need to set `groups` and, depending on the type of scene and group, `rooms` and/or `group0` as well.

**Comment by cdaniels77** [comment]
That work thank you so much
