### ISSUE TITLE
Question for groups

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#872]
When I expose the groups to the deconz in the `homebridge-hue,` they all have a colored wheel.
Is it possible to change a certain group so that it exposes only the color temperature without hue, I have a group of 15 GU10 on ikea and I would like them to have only a color temperature characteristic.

**Comment by ebaauw** [comment]
This needs to be solved in deCONZ.  Homebridge Hue just creates the _Lightbulb_ on what deCONZ exposes.

**Comment by Kristian8606** [comment]
Does the hue bridge better handle a group of lights grouped in the ios home?
I am considering buying a hue bridge but I don't know if I can create a group of 15 lights to expose to a home and thus achieve a better user experience with the groups?
If I group a lot of lights in ios, the home application sometimes crashes or doesn't respond, I guess because of the many API requests and responses.
If I create a group in deconz, it is not displayed correctly in the home application.

**Comment by ebaauw** [comment]
The Hue bridge and deCONZ handle groups in the same way: they use Zigbee groups, sending a single broadcast to change all lights in the group at once.  HomeKit groups are handled entirely by HomeKit.  They’re invisible to the Hue bridge and to the deCONZ gateway.  They result in a unicast command per light, to change one light at a time.  Homebridge Hue does a lot of effort to throttle these requests, not to drown the Zigbee network.  I don’t know how the native HomeKit function of the Hue bridge works here.  My guess is it will simply choke.

deCONZ is more powerful than the Hue bridge; the RaspBee and ConBee have bigger queues for Zigbee commands.  Using HomeKit groups and scenes is more challenging to the Hue bridge than to deCONZ.

Last I checked, the Hue bridge is smart enough to check what types of lights are in a group, and only expose what at least one light supports.  E.g. a group of dimmable lights will not expose colour.  Consequently, Homebridge Hue will not expose colour for that group.  The native HomeKit function of the Hue bridge doesn’t expose groups.  I think the Hue app might create HomeKit groups to mimic the Zigbee groups, but I’m not sure.

**Comment by ebreg** [comment]
I do have a similar issue with a luminary with multiple white ambience bulbs. All my other luminaries have colored bulbs and for them I use `/groups` (plus `blacklist` and `whitelist`) so that the bulbs are combined into one accessory. My workaround is to do the grouping in HomeKit.
But I am just wondering if this is the right way to go. Should I use `/groups` or a `multilight` resource link and what are the differences?

**Comment by ebaauw** [comment]
A `multilight` resourcelinks simply causes the HomeKit services for different lights to be exposed under a single HomeKit accessory, mainly to mitigate the limit of 249 bridged accessories per HomeKit bridge, see https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links.  The effects on HomeKit are largely optical: by default, Home will show a single tile for all the services, but if you select _Show as Multiple Tiles_, it will show a tile per service.  HomeKit still sends events per service (just as for HomeKit groups or HomeKit scenes).  The only real difference with a HomeKit group is that all services are in the same room (since they belong to the same accessory).

If you expose a `/groups` resource, the bulbs aren't combined into a HomeKit accessory; the Zigbee group is exposed as HomeKit accessory.  HomeKit treats the group as a single service, which is way more efficient.

**Comment by ebreg** [comment]
Thanks for the perfect explanation!

**Comment by Kristian8606** [comment]
@ebaauw Can you check this?
> I think the Hue app might create HomeKit groups to mimic the Zigbee groups, but I’m not sure.

**Comment by ebaauw** [comment]
In the _HomeKit & Siri_ section under _Settings_ of the Hue app, it does provide an overview of _Room_ and whether they're synced with HomeKit.  Rooms are a type of groups.

**Comment by Kristian8606** [comment]
Other question.
How the hue-bridge controls a group of lights> 10-15 from the native hue application when you move the slider slowly up or down.
When I run the Tradfri gu10 group created in Deconz by Homebridge - hue, and I try to darken slowly I get a pulsating blackout..
I don't remember if this effect is seen in the Phoscon app

**Comment by ebaauw** [comment]
The Hue app sends a PUT of `/groups/xx/action` to the Hue bridge, which translates it to a _Move to Level_ Zigbee command sent to the corresponding Zigbee group.

I don’t understand what you’re asking next.  Homebridge Hue doesn’t create groups in deCONZ.  When you expose a deCONZ group using Homebridge Hue, it should work the same as Phoson or a Hue bridge group in the Hue app: a single PUT to `/groups`, resulting in a Zigbee group broadcast.

Turn on debug mode in the Homebridge UI or run `homebridge -D` to have Homebridge Hue log the commands it sends to the Hue bridge or deCONZ gateway.

**Comment by Kristian8606** [comment]
Sorry for my bad English.
I have a group created by Deconz when I increase or decrease the brightness of the group slowly through homebridge-hue
the group of lights increases or decreases at short intervals similar to hiccups.

**Comment by Kristian8606** [comment]
I was experimenting with homebridge-hue and sending commands from a group of 11 bulbs grouped in the home of ios app I noticed an error
`{"address": "/ lights / 26 / state / bri", "description": "Internal error, 951", "type": 901}}]` I guess I'm clogging Deconz with requests, but I decided to split the sent command into two separate `'on':` `true` and `'bri':%` by sending `(on)` only once, then sending only `(bri)` to adjust the brightness. So with the single command I did not get an error, also the lights were controlled as one group without any lagging behind or crashing.
Do you think this approach is good and would it help to manage larger groups of 11 lights or groups created in deconz. I am not familiar with the Zigbee protocol and I do not know what harm or benefit this would lead to.

**Comment by ebaauw** [comment]
> I was experimenting with homebridge-hue and sending commands from a group of 11 bulbs grouped in the home of ios app
> guess I'm clogging Deconz with requests

What version of Homebridge Hue?  This should no longer happen in v0.12.12.  If it does, please capture and attach a debug log file.

> but I decided to split the sent command into two separate 'on': true and 'bri':% by sending (on) only once, then sending only (bri) to adjust the brightness.

How are you doing this?  Homebridge Hue doesn’t support this.

> Do you think this approach is good and would it help to manage larger groups of 11 lights or groups created in deconz. I am not familiar with the Zigbee protocol and I do not know what harm or benefit this would lead to.

it’s more efficient to use Zigbee groups and scenes, but the interactive control using a slider (sending multiple updates in close succession) is challenging, see earlier.

**Comment by ebaauw** [comment]
v0.12.13 has `waitTimePut` and `waitTimePutGroup` new config.json parameters.  `waitTimePut` is 50ms by default (for 20 requests per second) and `waitTimePutGroup` is 1000ms by default (for 1 request per second).  Note that PUT requests don't translate 1:1 to Zigbee commands.

**Comment by Kristian8606** [comment]
I'm sorry to confuse you.
I built a test Homebridge plugin through which I experimented with 15 lights.
I found that the separate commands `on` and `bri` do not cause errors on the part of the deconz.
That is, I sent the command `on` it only once, and then I sent only the brightness control `bri,`
and I noticed that it works without causing an error.
This made me think that Phoscon sends the commands `on` and `bri` separately, but I can't check if that's the case.
Does Homebridge-hue send separate commands?

**Comment by ebaauw** [comment]
By default Homebridge Hue combines multiple changes for the same light into one API command.  Set `waitTimeUpdate` to 0 in config.json to send each change as a separate command.  Note however, that the order in which HomeKit sends the changes is undefined, so you might see "cannot update - device is set to off" errors if _Brightness_ is changed before _On_.

**Comment by Kristian8606** [comment]
Do I have to send a command `on` every time I increase the brightness?
I find that when I send it `bri` and `on` API request to multiple bulbs I get an error.
When I send `on` once and then send only `bri` in one API request (without `on)` then I do not get an error, also the bulbs increase simultaneously.
I don't know how it will work with> 50 lights.

**Comment by ebaauw** [comment]
See https://developers.meethue.com/develop/get-started-2/important-notes/.

**Comment by Kristian8606** [comment]
From the link you provided, I understand that the command `on` only needs to be sent once.

>Don’t Always Send ‘ON’
Once you have sent the ‘ON’ attribute to a light, it will stay on. Do not repeatedly send the ‘ON’ command as this will slow the responsiveness of the bridge.

**Comment by Kristian8606** [comment]
The section `Hue System Performance` answered many of my questions.
Thanks!

**Comment by Kristian8606** [comment]
Is it possible to add a slider to the hue settings to set a timeout before the answer from the bulb updates the HomeKit application

**Comment by ebaauw** [comment]
The timeout is there already, but it's currently hard-coded to 500ms.  That should prevents any jumps with the default transition time of 0.4s.  For longer transition times, you want the HomeKit state to mimic the transitions.

https://github.com/ebaauw/homebridge-hue/blob/faaf96c8661fcd7e068505f78f0aa01769bb06f7/lib/HueLight.js#L2168-L2170.

**Comment by Kristian8606** [comment]
I think a longer wait period is necessary as I notice that grouped lights in homekit> 10 drive the slider crazy and sometimes even the HomeKit crashes.  It would be good to be able to increase the time.

**Comment by ebaauw** [comment]
You can change it in the code to experiment.  I have no idea what a reasonable value range would be.

I wouldn’t recommend (large) groups in HomeKit (or any other Home automation system) as they are unsuited for Zigbee networks.  Apple’s Home app is one of the worst apps ever.  The real issue is a fundamental design flaw in HomeKit (and in the Hue API), not distinguishing between target vs current light state.  I’m happy to provide reasonable workarounds where possible, but and I’m worried that they might introduce other issues.

**Comment by ebaauw** [comment]
What is actually happening when the slider goes crazy?  Have you double-checked that it’s indeed the updates by Homebridge Hue driving it crazy?  Did you check the Homebridge log with DEBUG mode enabled?  What lights are in the HomeKit group?  Do they even support attribute reporting?

Increasing `waitTimeUpdate` might actually be far more effective, “debouncing” the slider changes.

**Comment by Kristian8606** [comment]
In the esp8266-HomeKit example, the slider is not updated because the firmware controls the bulb directly.  It is only updated when the application or controlcenter is open.  For this reason, the user experience with the WiFi bulbs I have is more enjoyable.  In zigbee, the dozens of messages that update the slider make it bounce, sometimes even bring it down while I drag it.

> What is actually happening when the slider goes crazy? Have you double-checked that it’s indeed the updates by Homebridge Hue driving it crazy? Did you check the Homebridge log with DEBUG mode enabled? What lights are in the HomeKit group? Do they even support attribute reporting?

>Increasing waitTimeUpdate might actually be far more effective, “debouncing” the slider changes.

I will check again.
This problem is only with tradfri bulbs.
