### ISSUE TITLE
Pressing Link Button everytime Homebridge restarts.

### ISSUE THREAD

**Issue by lsd05** [ebaauw/homebridge-hue#873]
#### Issue

Hi i currently have Homebridge set up on my Macbook, I am no expert with it all but have so far managed to link Homebridge to my Hue hub and my Ring devices. So they are able to be used with Homekit. 

The issue i have is everytime i restart my Homebridge the Hue requires me to press the Link button again on the hub. Each and everytime. 

I have already looked around online and learnt that i have to somehow add my User ID or something which i am unable to find anywhere. On my config.json there is no user ID or and other login info. This is all i have..
 
      "name": "Hue",
            "anyOn": true,
            "effects": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue"

Just wondering if anyone could help point me in the right direction as i am lost at the moment. 

Thanks in advance for any help or advice. 

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Check the Homebridge log.

**Comment by lsd05** [comment]
I have mate. It states that error cause link button not pressed. I looked online at another person who posted the same issue. And someone said i need to add the bridge id / username. It may of been you who replied. With a link. I followed the link. But still cant seem to find any info about where to find the bridge id or username. So cant add it to the config.json.

In the homebridge link there is no bridge id or username that i can see. Im happy to copy and paste if that helps.

Thanks for swift reply.



Sent from my iPhone

On 30 Dec 2020, at 20:20, Erik Baauw <notifications@github.com> wrote:

﻿

Check the Homebridge log.

**Comment by ebaauw** [comment]
After you’ve pressed the link button, Homebridge Hue logs the bridgeid and username (API key) to be copied into config.json.

**Comment by lsd05** [comment]
Ahhh. Wicked mate. Il try that right now.

Any particular order i have to add it in? Or just straight copy and paste?

Thanks again.

Sent from my iPhone

On 31 Dec 2020, at 00:04, Erik Baauw <notifications@github.com> wrote:

﻿

After you’ve pressed the link button, Homebridge Hue logs the bridgeid and username (API key) to be copied into config.json.

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue#configuration for examples.

**Comment by lsd05** [comment]
Thanks mate. I got the user id. Got this…

"platforms": [
    {
      "platform": "Hue",
      "users": {
        "ECB5FAFFFE169271": "9iln4KGnoI9-r5wVqC2p6Sa6qg53hVcLQXNZr4tm"
      }
    }
  ]

But it wont let me add it… says config syntax error invalid config.

Sorry for all the super simple questions mate and thanks for the quick responses.
On 31 Dec 2020, at 00:13, Erik Baauw <notifications@github.com<mailto:notifications@github.com>> wrote:



See https://github.com/ebaauw/homebridge-hue#configuration for examples.

**Comment by ebaauw** [comment]
Use a JSON checker to verify the syntax, e.g. https://jsonlint.com/.  Make sure to use a text editor that doesn’t corrupt the quotes.
