### ISSUE TITLE
Hue Bridge visible after update

### ISSUE THREAD

**Issue by dibimuc** [ebaauw/homebridge-hue#875]
#### Issue

After the latest several updates, the symbol of the Hue bridge is available in the Home App. In previous versions this was disabled and not visible was a button. Is there a way to disable it?
<img width="159" alt="Bildschirmfoto 2020-12-31 um 15 42 30" src="https://user-images.githubusercontent.com/61652682/103414578-d8313c80-4b7e-11eb-9e91-a883fe6b92ce.png">

#### Log Messages

```
```

**Comment by ebaauw** [comment]
You cannot un-expose the accessory.  To show it as a button, so you can unset it as favourite, set `linkButton` in config.json.
