### ISSUE TITLE
Display Trådfri Smart Plug as Plug

### ISSUE THREAD

**Issue by rene-mueller** [ebaauw/homebridge-hue#876]
Hello,

I bought a Trådfri smart plug and connected it to homebridge-hue via deConz. In the home app on my iPhone it shows as a light.

Currently I have a fan connected to it. Is it possible to change the device type in the configuration?

**Comment by ebaauw** [comment]
Yes, create an `outlet` resourcelink.

**Comment by rene-mueller** [comment]
@ebaauw can you send me an example?

**Comment by ebaauw** [comment]
I've written up a Wiki: https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links
