### ISSUE TITLE
Ikea Trådfri one button with interchangeable pictures

### ISSUE THREAD

**Issue by frogger11** [ebaauw/homebridge-hue#877]
#### Issue

Hi I have some truble adding the new Ikea Trådfri switch with the interchangeable pictures. Is it supported?

https://www.ikea.com/se/sv/p/tradfri-genvaegsknapp-vit-40356381/

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Almost.  I have it working, but need to cook a new release.

**Comment by frogger11** [comment]
> Almost. I have it working, but need to cook a new release.

That sounds great, looking forward to the new release.
Br

**Comment by ebaauw** [comment]
In v0.12.13.

**Comment by frogger11** [comment]
Thanks for a good job. Many thanks.
Just want to inform that the @latest homebridge-hue version is set to 0.12.12, and not 0.12.14. Tried to update plugin yesterday it did not work. Discovered this this morning. When I manually changed to 0.12.14 it worked.

**Comment by ebaauw** [comment]
> Just want to inform that the @latest homebridge-hue version is set to 0.12.12, and not 0.12.14. 

Yes, see the release notes of v0.12.14.
