### ISSUE TITLE
RGBW Controller Color not behaving as expected in HomeKit

### ISSUE THREAD

**Issue by mareeekkkk** [ebaauw/homebridge-hue#883]
I got two rgbw controllers for led strips connected to my hue system. Both work as expected when using the hue app.
Since 1-2 month, one of the two strips seems to not get the right color values from HomeKit. Setting it to orange in HomeKit results in a warm white output, full red results in magenta output. 
The other strip with the same controller behaves as expected. 

All colors work fine on both controllers in hue app.
One of them has color problems when using homekit.
See screenshots attached. 

Using homebridge v1.1.7 with homebridge-hue v0.12.12

![image](https://user-images.githubusercontent.com/52048049/104089850-70f84400-5272-11eb-9a4f-4b452d54c24d.jpeg)
![image](https://user-images.githubusercontent.com/52048049/104089865-8b322200-5272-11eb-89f4-55b5c549de04.jpeg)

![image](https://user-images.githubusercontent.com/52048049/104089853-73f33480-5272-11eb-8851-4ff1d6913944.jpeg)
![image](https://user-images.githubusercontent.com/52048049/104089849-6d64bd00-5272-11eb-94bc-954833eac484.jpeg)

**Comment by ebaauw** [comment]
Stupid question: did you try power cycling the strip?

If that doesn't help, please attach the debug dump file, and tell me what's the resource (or name) for the controller that works, and for the controller that doesn't work.

Afaik, the Hue app issues the same API commands as Homebridge Hue when setting the colour.  Since they use HTTPS, you'd need a MITM setup to sniff the traffic.  Homebridge Hue logs the calls it makes when Homebridge DEBUG mode is enabled (under _Homebridge Settings_ in the Homebridge UI).

**Comment by mareeekkkk** [comment]
I already did a powercycle on all devices; e.g. the Controller, hue Bridge, homebridge, no change after that

I attached you the dump log file. Both controllers have the following specification (hue app)
![image](https://user-images.githubusercontent.com/52048049/104092655-a5c1c680-5285-11eb-871d-de5159d44a59.jpeg)

They were both working for ~1 year, and then one of them startet getting the colors wrong.

There is one more thing that's strange: When I take the HomeKit colorpicker handle on this particular led-strip and drag it to full orange, it snaps to a weird mixcolor after one second.(see screenshot)
![image](https://user-images.githubusercontent.com/52048049/104092748-47491800-5286-11eb-841a-0609a53f6135.jpeg)

**Comment by ebaauw** [comment]
> I attached you the dump log file.

Thanks.  They seem to be the same controller type and firmware.

> They were both working for ~1 year, and then one of them startet getting the colors wrong.

That would suggest a hardware issue.  When was this?  Did that coincide with upgrade to Homebridge Hue [v0.11.76](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.11.76) or later?  I whitelisted these controllers in that version, based on info I got on Discord on Aug 19 last year.

Could you run `ph -H x.x.x.x probe -v /lights/12` and `ph -H x.x.x.x probe -v /lights/30`?  Could you monitor the colours of the strips while `ph probe` is running, and see if they are the same for both controllers?

> When I take the HomeKit colorpicker handle on this particular led-strip and drag it to full orange, it snaps to a weird mixcolor after one second.

That's a design flaw in HomeKit.  It doesn't distinguish between target and actual colour.  The controller cannot generate the target colour you requested.  I reports back the actual colour, which Homebridge Hue uses to update the HomeKit colour.  Does the strip reflect the reported actual colour?

**Comment by mareeekkkk** [comment]
Yes they are both the same.

I have to correct myself, both controllers are not behaving as expected. The other one just had some "old" color information.
On both controllers Homekit-Red is always magenta, whereas Hue-Red is full Red.

> That would suggest a hardware issue. When was this? Did that coincide with upgrade to Homebridge Hue v0.11.76 or later? I whitelisted these controllers in that version, based on info I got on Discord on Aug 19 last year.

Not quite sure when it happened, but it could definately be happened after the 0.11.76 update.

Logs of ph probe are attached

[ph probe #883.txt](https://github.com/ebaauw/homebridge-hue/files/5791273/ph.probe.883.txt)

The observation of the ph probe process was, that blue looks blue, green looks green, but red looks like a full magenta (255R/0G/255B). Checked all colors with the hue app, here everything is behaving as expected.

**Comment by ebaauw** [comment]
Looks like the gamut reported through probing doesn't work.  I've seen this with one other light model as well, but don't remember which one.

Could you comment out the lines below in `/usr/lib/node_modules/homebridge-hue/lib/HueLight.js`, restart Homebridge, and check whether light controllers behave as intended?

https://github.com/ebaauw/homebridge-hue/blob/febd3e663328bf8e564dfaffb145334bf1d066e7/lib/HueLight.js#L21-L28

**Comment by mareeekkkk** [comment]
Thats a fix! 👍 

Both controllers are working as expected now.

**Comment by ebaauw** [comment]
In v0.12.14.
