### ISSUE TITLE
config.json: warning: nupnp: ignoring unknown key

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-hue#885]
Hello @ebaauw,
after the new update 0.12.14 I get the following warning message when starting the hue instances:
If I delete the entry nupnp: true in the config this error disappears. Looks somehow like it no longer recognizes this value?

![5CF63548-E4C7-40AA-9543-B348A51A41CD](https://user-images.githubusercontent.com/27686185/104129701-974eda00-536d-11eb-849f-60b0e7daea6f.jpeg)

Regards
Nastras

**Comment by ebaauw** [comment]
Oops, should have mentioned that in the release notes.  The `HueDiscovery` now checks that any discovered bridge is reachable, before passing it back to Homebridge Hue.  Consequently, the `nupnp` setting is no longer needed.

**Comment by Nastras** [comment]
All right, I was just surprised that the value was still in the wiki. Therefore the query 😉

**Comment by iMonZ** [comment]
> Oops, should have mentioned that in the release notes. The `HueDiscovery` now checks that any discovered bridge is reachable, before passing it back to Homebridge Hue. Consequently, the `nupnp` setting is no longer needed.

So should I remove : ""nupnp": true," completely out of my config have I understood that correctly?
