### ISSUE TITLE
Deconz: Unavailable lights appear as "On"

### ISSUE THREAD

**Issue by WinceWe** [ebaauw/homebridge-hue#886]
#### Issue

Hello.
I recognized that all my Deconz lights which are unavailable (off by manual switch) appear as "on" in homebridge.
Since that´s a quite common case in my house: Is there a way to let them appear as "Off" or "not available"?

Sorry, if that is already described somewhere. Can´t find anything about that in the wiki or here.

Thanks a lot!

#### Log Messages

```
```

**Comment by Lilfaen** [comment]
There is an option in the Homebridge-Hue settings under `how`: `wallSwitch`. 

https://github.com/ebaauw/homebridge-hue/wiki/Configuration

**Comment by ebaauw** [comment]
Sorry, I thought I had answered this, but apparently the answer wasn’t saved.

I strongly recommend against using 20th century wall switches to power off your Zigbee smart lights.  Not only does this disrupt the Zigbee mesh network, there’s no reliable way to detect a light being powered off.  See also https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2590.

Having said that, set `wallSwitch` in config.json to have Homebridge Hue turn the lights off when deCONZ reports them as unreachable.

**Comment by WinceWe** [comment]
No problem. There was also another reply today as far as I can see in my mails, so thank you to you both! I really missed it in the wiki obviously. Sorry for that. 
Thank you very much @ebaauw also for educating me. Didn’t really think about that but unfortunately I can’t do smth about it anyways since it has several other “reasons” why lights get powered off by wall switches. I would need to glue them or partly remove to be safe they don’t get used ;)

But thank you anyways again for the help and the hint!
