### ISSUE TITLE
Hue and Deconz parallel configured issue: ph: error: TypeError: Cannot read property 'isDeconz' of undefined

### ISSUE THREAD

**Issue by MaxiKingXXL** [ebaauw/homebridge-hue#888]
I have added a Deconz  device to my existing Hue configuration. 

The Hue everything works fine. But on my new Deconz device I can read light status but not change status.

[Hue] Phoscon-GW: request 21: PUT /lights/2/state {"on":true}
[Hue] Phoscon-GW: request 21: api error 3: resource, /lights/2, not available

ph lightlist
ph: error: TypeError: Cannot read property 'isDeconz' of undefined
    at Main.main (/usr/local/lib/node_modules/homebridge-hue/cli/ph.js:506:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by ebaauw** [comment]
Which version are you on?

**Comment by MaxiKingXXL** [comment]
[Hue] homebridge-hue v0.12.14, node v14.15.4, homebridge v1.1.7
[Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1942135050, api v1.42.0
[Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.7.1, api v1.16.0

pi@raspberrypi:~ $ ph createuser
ph: error: TypeError: config: not an object
    at newTypeError (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:35:52)
    at Function.toObject (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:432:13)
    at Object._callbacks.<computed> [as config] (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:756:40)
    at OptionParser.parse (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:818:29)
    at new HueClient (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:170:8)
    at Main.main (/usr/local/lib/node_modules/homebridge-hue/cli/ph.js:509:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by ebaauw** [comment]
That's weird.  What does `ph config` return?

**Comment by MaxiKingXXL** [comment]
ph config

{
  "0": 10,
  "1": 32,
  "2": 32,
  "3": 32,
  "4": 32,
  "5": 60,
  "6": 33,
  "7": 100,
  "8": 111,
  "9": 99,
  "10": 116,
  "11": 121,
  "12": 112,
  "13": 101,
  "14": 32,
  "15": 104,
  "16": 116,
  "17": 109,
  "18": 108,
  "19": 62,
  "20": 10,
  "21": 32,
  "22": 32,
  "23": 32,
  "24": 32,
  "25": 60,
  "26": 104,
  "27": 116,
  "28": 109,
  "29": 108,
  "30": 32,
  "31": 108,
  "32": 97,
  "33": 110,
  "34": 103,
  "35": 61,
  "36": 39,
  "37": 101,
  "38": 110,
  "39": 39,
  "40": 62,
  "41": 10,
  "42": 32,
  "43": 32,
  "44": 32,
  "45": 32,
  "46": 32,
  "47": 32,
  "48": 32,
  "49": 32,
  "50": 60,
  "51": 104,
  "52": 101,
  "53": 97,
  "54": 100,
  "55": 62,
  "56": 10,
  "57": 32,
  "58": 32,
  "59": 32,
  "60": 32,
  "61": 32,
  "62": 32,
  "63": 32,
  "64": 32,
  "65": 32,
  "66": 32,
  "67": 32,
  "68": 32,
  "69": 60,
  "70": 109,
  "71": 101,
  "72": 116,
  "73": 97,
  "74": 32,
  "75": 99,
  "76": 104,
  "77": 97,
  "78": 114,
  "79": 115,
  "80": 101,
  "81": 116,
  "82": 61,
  "83": 39,
  "84": 117,
  "85": 116,
  "86": 102,
  "87": 45,
  "88": 56,
  "89": 39,
  "90": 62,
  "91": 10,
  "92": 32,
  "93": 32,
  "94": 32,
  "95": 32,
  "96": 32,
  "97": 32,
  "98": 32,
  "99": 32,
  "100": 32,
  "101": 32,
  "102": 32,
  "103": 32,
  "104": 10,
  "105": 32,
  "106": 32,
  "107": 32,
  "108": 32,
  "109": 32,
  "110": 32,
  "111": 32,
  "112": 32,
  "113": 32,
  "114": 32,
  "115": 32,
  "116": 32,
  "117": 60,
  "118": 116,
  "119": 105,
  "120": 116,
  "121": 108,
  "122": 101,
  "123": 62,
  "124": 226,
  "125": 151,
  "126": 143,
  "127": 32,
  "128": 60,
  "129": 47,
  "130": 116,
  "131": 105,
  "132": 116,
  "133": 108,
  "134": 101,
  "135": 62,
  "136": 10,
  "137": 32,
  "138": 32,
  "139": 32,
  "140": 32,
  "141": 32,
  "142": 32,
  "143": 32,
  "144": 32,
  "145": 32,
  "146": 32,
  "147": 32,
  "148": 32,
  "149": 60,
  "150": 108,
  "151": 105,
  "152": 110,
  "153": 107,
  "154": 32,
  "155": 114,
  "156": 101,
  "157": 108,
  "158": 61,
  "159": 39,
  "160": 115,
  "161": 116,
  "162": 121,
  "163": 108,
  "164": 101,
  "165": 115,
  "166": 104,
  "167": 101,
  "168": 101,
  "169": 116,
  "170": 39,
  "171": 32,
  "172": 104,
  "173": 114,
  "174": 101,
  "175": 102,
  "176": 61,
  "177": 39,
  "178": 112,
  "179": 105,
  "180": 104,
  "181": 111,
  "182": 108,
  "183": 101,
  "184": 47,
  "185": 98,
  "186": 108,
  "187": 111,
  "188": 99,
  "189": 107,
  "190": 105,
  "191": 110,
  "192": 103,
  "193": 112,
  "194": 97,
  "195": 103,
  "196": 101,
  "197": 46,
  "198": 99,
  "199": 115,
  "200": 115,
  "201": 39,
  "202": 62,
  "203": 10,
  "204": 32,
  "205": 32,
  "206": 32,
  "207": 32,
  "208": 32,
  "209": 32,
  "210": 32,
  "211": 32,
  "212": 32,
  "213": 32,
  "214": 32,
  "215": 32,
  "216": 60,
  "217": 108,
  "218": 105,
  "219": 110,
  "220": 107,
  "221": 32,
  "222": 114,
  "223": 101,
  "224": 108,
  "225": 61,
  "226": 39,
  "227": 115,
  "228": 104,
  "229": 111,
  "230": 114,
  "231": 116,
  "232": 99,
  "233": 117,
  "234": 116,
  "235": 32,
  "236": 105,
  "237": 99,
  "238": 111,
  "239": 110,
  "240": 39,
  "241": 32,
  "242": 104,
  "243": 114,
  "244": 101,
  "245": 102,
  "246": 61,
  "247": 39,
  "248": 97,
  "249": 100,
  "250": 109,
  "251": 105,
  "252": 110,
  "253": 47,
  "254": 105,
  "255": 109,
  "256": 103,
  "257": 47,
  "258": 102,
  "259": 97,
  "260": 118,
  "261": 105,
  "262": 99,
  "263": 111,
  "264": 110,
  "265": 115,
  "266": 47,
  "267": 102,
  "268": 97,
  "269": 118,
  "270": 105,
  "271": 99,
  "272": 111,
  "273": 110,
  "274": 46,
  "275": 105,
  "276": 99,
  "277": 111,
  "278": 39,
  "279": 32,
  "280": 116,
  "281": 121,
  "282": 112,
  "283": 101,
  "284": 61,
  "285": 39,
  "286": 105,
  "287": 109,
  "288": 97,
  "289": 103,
  "290": 101,
  "291": 47,
  "292": 120,
  "293": 45,
  "294": 105,
  "295": 99,
  "296": 111,
  "297": 110,
  "298": 39,
  "299": 62,
  "300": 10,
  "301": 32,
  "302": 32,
  "303": 32,
  "304": 32,
  "305": 32,
  "306": 32,
  "307": 32,
  "308": 32,
  "309": 60,
  "310": 47,
  "311": 104,
  "312": 101,
  "313": 97,
  "314": 100,
  "315": 62,
  "316": 10,
  "317": 32,
  "318": 32,
  "319": 32,
  "320": 32,
  "321": 32,
  "322": 32,
  "323": 32,
  "324": 32,
  "325": 60,
  "326": 98,
  "327": 111,
  "328": 100,
  "329": 121,
  "330": 32,
  "331": 105,
  "332": 100,
  "333": 61,
  "334": 39,
  "335": 115,
  "336": 112,
  "337": 108,
  "338": 97,
  "339": 115,
  "340": 104,
  "341": 112,
  "342": 97,
  "343": 103,
  "344": 101,
  "345": 39,
  "346": 62,
  "347": 10,
  "348": 32,
  "349": 32,
  "350": 32,
  "351": 32,
  "352": 32,
  "353": 32,
  "354": 32,
  "355": 32,
  "356": 32,
  "357": 32,
  "358": 32,
  "359": 32,
  "360": 60,
  "361": 105,
  "362": 109,
  "363": 103,
  "364": 32,
  "365": 115,
  "366": 114,
  "367": 99,
  "368": 61,
  "369": 39,
  "370": 97,
  "371": 100,
  "372": 109,
  "373": 105,
  "374": 110,
  "375": 47,
  "376": 105,
  "377": 109,
  "378": 103,
  "379": 47,
  "380": 108,
  "381": 111,
  "382": 103,
  "383": 111,
  "384": 46,
  "385": 115,
  "386": 118,
  "387": 103,
  "388": 39,
  "389": 32,
  "390": 97,
  "391": 108,
  "392": 116,
  "393": 61,
  "394": 39,
  "395": 80,
  "396": 105,
  "397": 45,
  "398": 104,
  "399": 111,
  "400": 108,
  "401": 101,
  "402": 32,
  "403": 108,
  "404": 111,
  "405": 103,
  "406": 111,
  "407": 39,
  "408": 32,
  "409": 119,
  "410": 105,
  "411": 100,
  "412": 116,
  "413": 104,
  "414": 61,
  "415": 39,
  "416": 50,
  "417": 53,
  "418": 54,
  "419": 39,
  "420": 32,
  "421": 104,
  "422": 101,
  "423": 105,
  "424": 103,
  "425": 104,
  "426": 116,
  "427": 61,
  "428": 39,
  "429": 51,
  "430": 55,
  "431": 55,
  "432": 39,
  "433": 62,
  "434": 10,
  "435": 32,
  "436": 32,
  "437": 32,
  "438": 32,
  "439": 32,
  "440": 32,
  "441": 32,
  "442": 32,
  "443": 32,
  "444": 32,
  "445": 32,
  "446": 32,
  "447": 60,
  "448": 98,
  "449": 114,
  "450": 62,
  "451": 10,
  "452": 32,
  "453": 32,
  "454": 32,
  "455": 32,
  "456": 32,
  "457": 32,
  "458": 32,
  "459": 32,
  "460": 32,
  "461": 32,
  "462": 32,
  "463": 32,
  "464": 60,
  "465": 112,
  "466": 62,
  "467": 80,
  "468": 105,
  "469": 45,
  "470": 60,
  "471": 115,
  "472": 116,
  "473": 114,
  "474": 111,
  "475": 110,
  "476": 103,
  "477": 62,
  "478": 104,
  "479": 111,
  "480": 108,
  "481": 101,
  "482": 60,
  "483": 47,
  "484": 115,
  "485": 116,
  "486": 114,
  "487": 111,
  "488": 110,
  "489": 103,
  "490": 62,
  "491": 58,
  "492": 32,
  "493": 89,
  "494": 111,
  "495": 117,
  "496": 114,
  "497": 32,
  "498": 98,
  "499": 108,
  "500": 97,
  "501": 99,
  "502": 107,
  "503": 32,
  "504": 104,
  "505": 111,
  "506": 108,
  "507": 101,
  "508": 32,
  "509": 102,
  "510": 111,
  "511": 114,
  "512": 32,
  "513": 73,
  "514": 110,
  "515": 116,
  "516": 101,
  "517": 114,
  "518": 110,
  "519": 101,
  "520": 116,
  "521": 32,
  "522": 97,
  "523": 100,
  "524": 118,
  "525": 101,
  "526": 114,
  "527": 116,
  "528": 105,
  "529": 115,
  "530": 101,
  "531": 109,
  "532": 101,
  "533": 110,
  "534": 116,
  "535": 115,
  "536": 60,
  "537": 47,
  "538": 112,
  "539": 62,
  "540": 10,
  "541": 32,
  "542": 32,
  "543": 32,
  "544": 32,
  "545": 32,
  "546": 32,
  "547": 32,
  "548": 32,
  "549": 32,
  "550": 32,
  "551": 32,
  "552": 32,
  "553": 60,
  "554": 97,
  "555": 32,
  "556": 104,
  "557": 114,
  "558": 101,
  "559": 102,
  "560": 61,
  "561": 39,
  "562": 47,
  "563": 97,
  "564": 100,
  "565": 109,
  "566": 105,
  "567": 110,
  "568": 39,
  "569": 62,
  "570": 68,
  "571": 105,
  "572": 100,
  "573": 32,
  "574": 121,
  "575": 111,
  "576": 117,
  "577": 32,
  "578": 109,
  "579": 101,
  "580": 97,
  "581": 110,
  "582": 32,
  "583": 116,
  "584": 111,
  "585": 32,
  "586": 103,
  "587": 111,
  "588": 32,
  "589": 116,
  "590": 111,
  "591": 32,
  "592": 116,
  "593": 104,
  "594": 101,
  "595": 32,
  "596": 97,
  "597": 100,
  "598": 109,
  "599": 105,
  "600": 110,
  "601": 32,
  "602": 112,
  "603": 97,
  "604": 110,
  "605": 101,
  "606": 108,
  "607": 63,
  "608": 60,
  "609": 47,
  "610": 97,
  "611": 62,
  "612": 10,
  "613": 32,
  "614": 32,
  "615": 32,
  "616": 32,
  "617": 32,
  "618": 32,
  "619": 32,
  "620": 32,
  "621": 60,
  "622": 47,
  "623": 98,
  "624": 111,
  "625": 100,
  "626": 121,
  "627": 62,
  "628": 10,
  "629": 32,
  "630": 32,
  "631": 32,
  "632": 32,
  "633": 60,
  "634": 47,
  "635": 104,
  "636": 116,
  "637": 109,
  "638": 108,
  "639": 62,
  "640": 10,
  "641": 32,
  "642": 32,
  "643": 32,
  "644": 32
}

**Comment by ebaauw** [comment]
OK, that's the raw byte values for:
```

    <!doctype html>
    <html lang='en'>
        <head>
            <meta charset='utf-8'>
            
            <title>● </title>
            <link rel='stylesheet' href='pihole/blockingpage.css'>
            <link rel='shortcut icon' href='admin/img/favicons/favicon.ico' type='image/x-icon'>
        </head>
        <body id='splashpage'>
            <img src='admin/img/logo.svg' alt='Pi-hole logo' width='256' height='377'>
            <br>
            <p>Pi-<strong>hole</strong>: Your black hole for Internet advertisements</p>
            <a href='/admin'>Did you mean to go to the admin panel?</a>
        </body>
    </html>
```
Looks like port 80 is running the pihole UI?  You need to issue `ph -H 127.0.0.1:`_port_` createuser`, substituting the port that deCONZ runs on.

**Comment by MaxiKingXXL** [comment]
Yes, pihole runs on the same server on port 80. 

In the Hue plugin I had configured: <local IP>:8080

When I try to change change a light status it fails.

[Hue] Phoscon-GW: request 9: PUT /lights/2/state {"on":false}
[Hue] Phoscon-GW: request 9: api error 3: resource, /lights/2, not available
[Hue] Fernsehleuchte: homekit on changed from true to false
[Hue] Phoscon-GW: request 10: PUT /lights/2/state {"on":false}
[Hue] Phoscon-GW: request 10: api error 3: resource, /lights/2, not available

But when I change the status in the Phoscon app the status change is showing correct in Homebrige log.

[Hue] Fernsehleuchte: set homekit on from true to false
[Hue] Fernsehleuchte: set homekit on from false to true
[Hue] Fernsehleuchte: set homekit on from true to false

When I run the following I get a 10 char user string. 
ph -H 127.0.0.1:8080 createuser

But I have an API key already create by pressing the Phoscon app button and it's in the Config file. At least the connection seem to work partly.

Where do I need this new created user for?

**Comment by ebaauw** [comment]
> [Hue] Phoscon-GW: request 9: api error 3: resource, /lights/2, not available

deCONZ is not exposing `/lights/2`.  This could be because the light has been deleted after you started Homebridge, or because of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2473.

> Where do I need this new created user for?

For `ph`.  It has saved it in `~/.ph`.  You can set `PH_HOST` In the environment, so you don’t have to specify `-H 127.0.0.1:8080` every time.  Best to use a different API key per app, so you can check which app created what resources on the gateway.

**Comment by MaxiKingXXL** [comment]
Now the config returns proper values.  But lights parameter has no return value. Looks like lights get lost somehow.

ph -H 127.0.0.1:8080 -u ... config
{
  "apiversion": "1.16.0",
  "bridgeid": "...",
  "datastoreversion": "93",
  "devicename": "ConBee II",
  "factorynew": false,
  "mac": "...",
  "modelid": "deCONZ",
  "name": "Phoscon-GW",
  "replacesbridgeid": null,
  "starterkitid": "",
  "swversion": "2.7.1"
}

What's the syntax for ~/.ph file? Can't find a URL which describs the paramter syntax.
Is the following right?
PH_HOST = 127.0.0.1:8080

**Comment by ebaauw** [comment]
> But lightlist parameter has no return value.

Yeah, it's kinda silent.  Run `ph lightlist -v` to get some feedback.

> What's the syntax for ~/.ph file?

Undocumented.  It's a single JSON object with API key and fingerprint for the pinned SSL certificate per bridge/gateway.

> Can't find a URL which describs the paramter syntax.

Run `ph -h` or `ph --help`.

> Is the following right?

Except for the spaces.  This is Linux/Unix shell syntax.  You might want to export it from `.profile` or similar:
```
export PH_HOST=127.0.0.1:8080
```

**Comment by ebaauw** [comment]
Fix `ph createuser` and improved bridge recognition in v0.12.15.
