### ISSUE TITLE
Danalock support

### ISSUE THREAD

**Issue by smulle48** [ebaauw/homebridge-hue#889]
Hi

Is there any chance Danalock will be supported soon? or it's possible to change it from a bulb to a lock?

I'm trying to move away from Jeedom to this, as this plugin is blazing fast compared to Jeedom, but in Jeedom I can define the type for every lights, switches, etc.

So as I know that the Danalock shows up as a light in Jeedom, I just redefine it as a lock, before exposing it to homebridge.

![Skærmbillede 2021-01-11 kl  13 56 56](https://user-images.githubusercontent.com/24297824/104213344-77371d80-5436-11eb-9726-188acdb6cd24.png)

**Comment by ebaauw** [comment]
Is the Danalock supported by deCONZ yet?  If so, please list the resource.

**Comment by smulle48** [comment]
> Is the Danalock supported by deCONZ yet? If so, please list the resource.

Yes it was merged the 14. July 2020

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3030/files

You mean the resource from deconz gui?

**Comment by ebaauw** [comment]
Not sure I can support this.  HomeKit needs current lock state vs target lock state for locks.  Also, I understand from the deCONZ issue, the battery isn't exposed.  I would better be exposed as `/sensors` resource (it doesn't support Zigbee groups anyways), with current lock state in `state` and target lock state in `config`, similar to thermostats.

I won't be able to test it, as I don't have the Danalock myself (or any other Zigbee lock).  After long considerations, I decided to go for Nuki instead, because of their Opener.  Bluetooth sucks, of course, but they have a bridge that provides a local HTTP API, taking care of the Bluetooth connections to the Smart Lock and to the Opener.  Of course, I've created a Homebridge plugin for that API, which works better than I'd hoped for.  I can now tell Siri to "buzz" me in: übercool.

**Comment by smulle48** [comment]
> Not sure I can support this. HomeKit needs current lock state vs target lock state for locks. Also, I understand from the deCONZ issue, the battery isn't exposed. I would better be exposed as `/sensors` resource (it doesn't support Zigbee groups anyways), with current lock state in `state` and target lock state in `config`, similar to thermostats.
> 
> I won't be able to test it, as I don't have the Danalock myself (or any other Zigbee lock). After long considerations, I decided to go for Nuki instead, because of their Opener. Bluetooth sucks, of course, but they have a bridge that provides a local HTTP API, taking care of the Bluetooth connections to the Smart Lock and to the Opener. Of course, I've created a Homebridge plugin for that API, which works better than I'd hoped for. I can now tell Siri to "buzz" me in: übercool.

After Danalock contracted with the Norwegian Department of Defence, they went into total darkness and only rarely makes updates to the locks :-/ Therefore I don't want to waste yet another €100,- just for a bridge for the lock, though that bridge has Homekit :-)

Anyway, With the Danalock, you have to define yourself how far it has to turn, to be either locked or unlocked, so unless it's able to turn so far, it won't change state. Same with my setup now. Though deConz treat it as a bulb, if I turn that bulb on and off, it will momentarily change state, but shortly after change to the current state, so if it's unlocked (bulb off) and I lock the door (bulb on), and the lock somehow is jammed, it will stay bulb off. That also goes for the other way around.

**Comment by malmentm** [comment]
> > Not sure I can support this. HomeKit needs current lock state vs target lock state for locks. Also, I understand from the deCONZ issue, the battery isn't exposed. I would better be exposed as `/sensors` resource (it doesn't support Zigbee groups anyways), with current lock state in `state` and target lock state in `config`, similar to thermostats.
> > I won't be able to test it, as I don't have the Danalock myself (or any other Zigbee lock). After long considerations, I decided to go for Nuki instead, because of their Opener. Bluetooth sucks, of course, but they have a bridge that provides a local HTTP API, taking care of the Bluetooth connections to the Smart Lock and to the Opener. Of course, I've created a Homebridge plugin for that API, which works better than I'd hoped for. I can now tell Siri to "buzz" me in: übercool.
> 
> After Danalock contracted with the Norwegian Department of Defence, they went into total darkness and only rarely makes updates to the locks :-/ Therefore I don't want to waste yet another €100,- just for a bridge for the lock, though that bridge has Homekit :-)
> 
> Anyway, With the Danalock, you have to define yourself how far it has to turn, to be either locked or unlocked, so unless it's able to turn so far, it won't change state. Same with my setup now. Though deConz treat it as a bulb, if I turn that bulb on and off, it will momentarily change state, but shortly after change to the current state, so if it's unlocked (bulb off) and I lock the door (bulb on), and the lock somehow is jammed, it will stay bulb off. That also goes for the other way around.

Is it the same if you set the lock to use end to end unlock?

**Comment by smulle48** [comment]
> > > Not sure I can support this. HomeKit needs current lock state vs target lock state for locks. Also, I understand from the deCONZ issue, the battery isn't exposed. I would better be exposed as `/sensors` resource (it doesn't support Zigbee groups anyways), with current lock state in `state` and target lock state in `config`, similar to thermostats.
> > > I won't be able to test it, as I don't have the Danalock myself (or any other Zigbee lock). After long considerations, I decided to go for Nuki instead, because of their Opener. Bluetooth sucks, of course, but they have a bridge that provides a local HTTP API, taking care of the Bluetooth connections to the Smart Lock and to the Opener. Of course, I've created a Homebridge plugin for that API, which works better than I'd hoped for. I can now tell Siri to "buzz" me in: übercool.
> > 
> > 
> > After Danalock contracted with the Norwegian Department of Defence, they went into total darkness and only rarely makes updates to the locks :-/ Therefore I don't want to waste yet another €100,- just for a bridge for the lock, though that bridge has Homekit :-)
> > Anyway, With the Danalock, you have to define yourself how far it has to turn, to be either locked or unlocked, so unless it's able to turn so far, it won't change state. Same with my setup now. Though deConz treat it as a bulb, if I turn that bulb on and off, it will momentarily change state, but shortly after change to the current state, so if it's unlocked (bulb off) and I lock the door (bulb on), and the lock somehow is jammed, it will stay bulb off. That also goes for the other way around.
> 
> Is it the same if you set the lock to use end to end unlock? Does it show in Home App as lock or bulb?

I haven't tried the end to end lock/unlock as my lock only takes about 1 round to lock/unlock, but I'm guessing it would be the same as it's measuring the distance.

As standard it shows up as a bulb, but homebridge in Jeedom got the ability to change the characteristics on every device before it's exposed to homebridge, so I'm able to manually change it to a lock

This is from deConz
![Skærmbillede 2021-01-12 kl  17 19 11](https://user-images.githubusercontent.com/24297824/104341749-6c45c100-54fa-11eb-9837-37cc25cdab9f.png)
![Skærmbillede 2021-01-12 kl  17 19 29](https://user-images.githubusercontent.com/24297824/104341758-6fd94800-54fa-11eb-8421-37fe37ad42e4.png)

This is before it's exposed to homebridge
![Skærmbillede 2021-01-12 kl  17 20 48](https://user-images.githubusercontent.com/24297824/104341894-94cdbb00-54fa-11eb-80d3-fd48ef74bf0c.png)

And this is all the options I got:
![Skærmbillede 2021-01-12 kl  17 23 17](https://user-images.githubusercontent.com/24297824/104342268-eece8080-54fa-11eb-844d-ffc57e6e9941.png)
![Skærmbillede 2021-01-12 kl  17 23 26](https://user-images.githubusercontent.com/24297824/104342276-f1c97100-54fa-11eb-8d0f-8af3d70fb2fd.png)

**Comment by malmentm** [comment]
I guess battery status does not work either?

**Comment by smulle48** [comment]
> I guess battery status does not work either?

That's correct but I'm only changing it to a lock because it looks wrong as an bulb (my kids kept turning it on and off) but also so I can use the automations in the home app

**Comment by smulle48** [comment]
> Not sure I can support this. HomeKit needs current lock state vs target lock state for locks. Also, I understand from the deCONZ issue, the battery isn't exposed. I would better be exposed as `/sensors` resource (it doesn't support Zigbee groups anyways), with current lock state in `state` and target lock state in `config`, similar to thermostats.
> 
> I won't be able to test it, as I don't have the Danalock myself (or any other Zigbee lock). After long considerations, I decided to go for Nuki instead, because of their Opener. Bluetooth sucks, of course, but they have a bridge that provides a local HTTP API, taking care of the Bluetooth connections to the Smart Lock and to the Opener. Of course, I've created a Homebridge plugin for that API, which works better than I'd hoped for. I can now tell Siri to "buzz" me in: übercool.

I can see the code has been updated to report current state on the lock

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3751/files

**Comment by ebaauw** [comment]
That's actually making it worse: you set the lock, but it immediately reports back that it's still unlocked.

**Comment by smulle48** [comment]
> That's actually making it worse: you set the lock, but it immediately reports back that it's still unlocked.

Well it's working perfectly here. Guess I'll have to jump back to zigbee2mqtt

**Comment by ebaauw** [comment]
> Guess I'll have to jump back to zigbee2mqtt

If that's an option: please do and don't bother me.

**Comment by smulle48** [comment]
Fine!! what a waste of time! I'll promise I'll never ask you anything again!

**Comment by ebaauw** [comment]
For those of you who do appreciate that I'm providing Homebridge Hue for free, in my own time:

v0.12.17 provides experimental support for `/lights` resources of type `Door Lock`.  I don't have any Zigbee door lock, so I cannot test this in full.  I did test the HomeKit interaction with a regular light, and that seems OK.  Some remarks:
- I understand from the deCONZ code that a `state.on` value of `true` means locked, and `false` means unlocked.  This is counter-intuitive, as Home shows the Tile as on when unlocked;
- I only set _LockCurrentState_ from Homebridge Hue; _LockTargetState_ is only set from HomeKit (except on startup, where it mirrors _LockCurrentState_;
- On setting _LockTargetState_, Homebridge Hue sends the appropriate PUT to the light state, but doesn't update anything in HomeKit.  The deCONZ API should change `state.on` when the lock has changed, causing Homebridge Hue to update _Lock Current State_.  The _Opening..._ or _Closing..._ state in Home is maintained by Home itself, on the values of _Current Lock State_ and _Target Lock State_.
- As mentioned above, no battery state, as the API doesn't expose this;
- I see the resource exposes `state.alert`.  Does that do anything?  What values does it take?  For now, I'm ignoring it.

**Comment by simplenotezy** [comment]
That's really cool @ebaauw, happy to see you've seen the coolness of having automated locks. I have had danalock for a while, but unfortunately only the BT version. I'll buy a ZigBee version and test this code out for you!

**Comment by ebaauw** [comment]
I've known that smart locks are pretty cool for some time.  I just have no experience with Zigbee smart locks.

I installed a Nuki Smart Lock on the door of my apartment and an Opener for the front door of the building.  Of course, I created by own Homebridge plugin for these.  Now can I can tell Siri from my Apple Watch to buzz me in: übercool!

**Comment by pponce** [comment]
This is awesome.
I’m in the market for locks and will buy Yale locks once deconz supports them.  I see work is being done to do so.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3750
