### ISSUE TITLE
Exclude Ikea Trådfri from Hue discovery

### ISSUE THREAD

**Issue by Farmand77** [ebaauw/homebridge-hue#892]
#### Log Messages

```
```

**Comment by Farmand77** [comment]
I am having problems defining what "names" to use if i want to exclude devices identified from Conbee II. To allow for dimming of light in an Trådfri on/off switch i create this on the phoscon page since dimming is not really an option in apple homekit. but dimming up and down is presented as two new devices that cant be used nor hidden from homekit.
Im running on an RPI 4 with Conbee II dongle

**Comment by ebaauw** [comment]
Check the details on those two devices in Eve to figure out for what resource types and what resources they are created.  I don’t use Phoscon, but I’d guess these are CLIPGenericStatus sensors.  You can exclude them using `excludeSensorTypes` in config.json.

**Comment by Farmand77** [comment]
Im using Homebridge-hue in Hoobs.
When i press ID in Eve i get a failed

________________________________
Fra: Erik Baauw <notifications@github.com>
Sendt: 13. januar 2021 11:56
Til: ebaauw/homebridge-hue <homebridge-hue@noreply.github.com>
Cc: Farmand77 <jesper-frost@live.dk>; Author <author@noreply.github.com>
Emne: Re: [ebaauw/homebridge-hue] Exclude Ikea Trådfri from Hue discovery (#892)


Check the details on those two devices in Eve to figure out for what resource types and what resources they are created. I don’t use Phoscon, but I’d guess these are CLIPGenericStatus sensors. You can exclude them using excludeSensorTypes in config.json.
