### ISSUE TITLE
After Homebridge reboot, LIDL light Strip show not response to status, but works fine

### ISSUE THREAD

**Issue by miquellaboria** [ebaauw/homebridge-hue#893]
Yesterday, I reboot Homebridge after a plugin update and Home App shows in the top status "LED Estudio" no response. 
The button of the device looks well and all works fine.

![IMG_0123](https://user-images.githubusercontent.com/1266767/104428585-f175b800-5584-11eb-9afd-cd90d3963c2a.PNG)

**Comment by ebaauw** [comment]
If the button works, it’s probably a quirk in Home.  Homebridge Hue doesn’t set a _Not Responding_ state in HomeKit.  Did you force-quit Home and restart it?

Are you sure this isn’t _Status Fault_?  Homebridge Hue will set that when the bridge/gateway reports the strip as not reachable.  If the Hue bridge reports this in error, the strip can still be controlled.

**Comment by miquellaboria** [comment]
I restart Home App & Homebridge and doesn't work, I have this light for a month and no issues before.
I'm using RapsBee and no issue reported and logs does'nt have any issue also.
It's very strange... :(

In Mac App shows de device doesn't not respond, but in the button not...

![Captura de Pantalla 2021-01-13 a les 12 11 38](https://user-images.githubusercontent.com/1266767/104444744-7fa76980-5598-11eb-9469-61d7ad0a8b5f.png)

**Comment by ebaauw** [comment]
Please attach the debug dump file.

**Comment by miquellaboria** [comment]
I attach the file: [homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5809138/homebridge-hue.json.gz)

Thanks!

**Comment by miquellaboria** [comment]
I have restart the raspberry and the Lidl strip and the alert was disappeared.

Thanks for your help!

**Comment by ebaauw** [comment]
From the dump, the deCONZ API reported the strip as `reachable` false.  Consequently, Homebridge Hue set _Status Fault_.  The deCONZ API doesn't accept state changes to unreachable lights, causing Homebridge Hue to report an error to HomeKit when it tries to update the light.  HomeKit sets the error state.  Unfortunately, Homebridge Hue (or any accessory) cannot push to HomeKit that the light is no longer in error.  You need to refresh the view in Home (or switch between _Home_ and _Room_ views), so Home can conclude that itself.

**Comment by miquellaboria** [comment]
@ebaauw thanks!
