### ISSUE TITLE
Adaptive lightnbing disabled after restart of homebridge

### ISSUE THREAD

**Issue by malmentm** [ebaauw/homebridge-hue#895]
When have enabled adaptive lightning for a Philips bulb the adaptive light settings is disabled after restarting homebridge. Is this an known bug?

**Comment by ebaauw** [comment]
Yes, see https://github.com/ebaauw/homebridge-hue/issues/766#issuecomment-731560178.

Currently, Homebridge Hue has no memory; I need to migrate to dynamic platform accessories to persist the state of Homebridge Hue between restarts (see #4).

**Comment by Phoenix-DH** [comment]
I did not really understand this topic. I have AL enabled for all my lights, no need to reenable something in home. The icon is still visible and by changing the % the color will change.
