### ISSUE TITLE
With latest version V0.12.16 API error after changing brightness

### ISSUE THREAD

**Issue by dibimuc** [ebaauw/homebridge-hue#896]
#### Issue

Since latest version V0.12.16 again the problem that lights are not responding in Home App when changing the brightness itself with a scene. 
#### Log Messages

```
```

#### Debug Files

[logs.txt](https://github.com/ebaauw/homebridge-hue/files/5821578/logs.txt)

**Comment by ebaauw** [comment]
```
15.1.2021, 15:59:59 - [Hue] Philips hue: request 376: PUT /lights/10/state {"bri":127}
15.1.2021, 15:59:59 - [Hue] Philips hue: request 376: api error 201: parameter, bri, is not modifiable. Device is set to off.
```
The bridge / gateway reports the light as off and doesn't accept the request to change the brightness.  Make sure to recall this scene only when the lights are already on, or include the _On_ characteristic for each light in the scene.

```
15.1.2021, 15:28:59 - HAP Warning: Characteristic undefined not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
```
I don't think that's Homebridge Hue?  You seem to be exposing lights only?  Service `0A` is _Temperature Sensor_.

**Comment by dibimuc** [comment]
Changing the brightness without turning the lights on worked fine before this update. It just causes warnings.

**Comment by ebaauw** [comment]
> Changing the brightness without turning the lights on worked fine before this update.

Are you running a Hue bridge or deCONZ gateway?  What version did you upgrade from?

> And the most interesting thing is that some lights are not showing a connection problem in the Home App and some do.

_Not Responding_ accessories have nothing to do with Homebridge Hue.  These are caused by communication issues between your iDevice and Homebridge.

**Comment by dibimuc** [comment]
I am running a Hue bridge in the latest version. I also upgrade from the latest version (I don't skip versions).

It's not that simple. The behavior is that I change the brightness with the Home+ App (a scene covering 5 lamps). The API Error 201 is new and since then some lights in this scene are changing their brightness, some don't. This behavior seems to be random. When I see the communication error in the Home App, the device still works and once I change the brightness in the Home App (then with the lights on since the Home app enforces this) the communication error in the Home App disappears.

**Comment by ebaauw** [comment]
> The API Error 201 is new

It’s not, actually.  The Hue bridge has been returning this for years.  What’s new is that Homebridge Hue logs it, but this change was from before v0.12.16.  Homebridge Hue does **not** report this error to HomeKit, so whatever you’re seeing in Home is unrelated to the log message.

Unlike deCONZ, the Hue bridge still sends the associated Zigbee command, after issuing the 201 error.  If the light doesn’t respond, it’s either unreachable by the Hue bridge, or its firmware doesn’t like the command.  Both are more likely for non-Hue lights.  The random behaviour would suggest reachability issues.

Note that the Hue bridge (nor any other Zigbee gateway) doesn’t accurately report whether a light is reachable.  When it does, Homebridge Hue sets _Status Fault_, which is shown in Eve, but ignored by Home.  Homebridge Hue does **not** mark a light as _Not Reachable_.

**Comment by MasterofKungfu9999** [comment]
I have the same issue. I'm using a deconz gateway. Some lights are not reachable. Only activating at homebridge brings them back to the home app on iOS

**Comment by sieren** [comment]
Same issue here, Lights stop responding, I have to manually retrigger them in the Phoscon API for them to work again.

**Comment by ebaauw** [comment]
Please capture and attach a debug log file.

**Comment by aschmidt74** [comment]
Hi there & same issue here ;)

I run `homebridge-hue` and `deconz`.
the behaviour of the hue dimmer-switch became pretty erratic.
sometimes a command makes it to the lamps, most of the times the lamps blink, and go off.
the homebridge.log seems to reflect this:
```
[1/23/2021, 8:08:24 PM] [Hue] Phoscon-GW: request 435: PUT /lights/2/state {"bri":127}
[1/23/2021, 8:08:24 PM] [Hue] Phoscon-GW: request 435: api error 201: parameter, bri, is not modifiable. Device is set to off.
```
the plugin dumpfile: [homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5860912/homebridge-hue.json.gz)

I've set `Homebridge Settings` `Environment Variables` `DEBUG` = `*`
pressed `I` on the dimmer switch, two times, some seconds apart, and expected 3 lights to turn `on`

the lines containing 'Hue' read like this:
```
[1/23/2021, 8:30:47 PM] [Hue] Switch Office On: homekit button single press
[1/23/2021, 8:30:47 PM] [Hue] Office Mitte: set homekit on from false to true
[1/23/2021, 8:30:47 PM] [Hue] Office Links: set homekit on from false to true
[1/23/2021, 8:30:47 PM] [Hue] Office Rechts: set homekit on from false to true
[1/23/2021, 8:30:47 PM] [Hue] Office Links: set homekit on from true to false
[1/23/2021, 8:30:47 PM] [Hue] Office Links: homekit on changed from false to true
[1/23/2021, 8:30:47 PM] [Hue] Office Mitte: set homekit on from true to false
[1/23/2021, 8:30:47 PM] [Hue] Office Rechts: set homekit on from true to false
...
[1/23/2021, 8:31:02 PM] [Hue] Switch Office On: homekit button single press
[1/23/2021, 8:31:02 PM] [Hue] Office Mitte: set homekit on from false to true
[1/23/2021, 8:31:02 PM] [Hue] Office Rechts: set homekit on from false to true
[1/23/2021, 8:31:02 PM] [Hue] Office Links: set homekit on from true to false
[1/23/2021, 8:31:02 PM] [Hue] Office Links: set homekit on from false to true
[1/23/2021, 8:31:03 PM] [Hue] Office Mitte: set homekit on from true to false
[1/23/2021, 8:31:03 PM] [Hue] Office Rechts: set homekit on from true to false
[1/23/2021, 8:31:05 PM] [Hue] Office Links: set homekit on from true to false
```
interestingly the api-errors seen earlier and above didnt show up in the debug-run.

**Comment by ebaauw** [comment]
I need the log file of Homebridge running in DEBUG mode from the UI (or running `homebridge -D` from the command line), from the moment Homebridge starts to where the error occurs.

The error is from the deCONZ API: it doesn't allow you to change brightness (nor colour/colour temperature) while (the gateway thinks) a light is off.  If you don't know the light state, include _On_ in the HomeKit scene you activate from the button.

> interestingly the api-errors seen earlier and above didnt show up in the debug-run.

How did you configure the dimmer switch?  The partial log suggests the lights are updated from the Hue bridge, and Homebridge Hue syncs the state to HomeKit.  No requests from HomeKit to change the light state.

**Comment by aschmidt74** [comment]
I'll redo the debug run. The one described above seemed to have worked partially only, not *.

The hue Dimmer switch is being configured in the HueEssentials app. The only problem is: you can assign a lot of actions to a button, including 3 options not listed here (blink, motion sensor action...) BUT a simple on/off cannot be assigned!

![286B4541-9355-482A-9C9E-3DDB7287E6D1](https://user-images.githubusercontent.com/45806825/105645779-33afcb00-5e9c-11eb-8a9a-ddf562bc9585.jpeg)

Indeed, what the app's 'wizzard' assigns by default to the I button is: brightness 100%.

I would expect that the zigbee switch via deconz directly sets the hue lights. And my guess is that Homebridge just gets actively in the way.
