### ISSUE TITLE
0.12.16 linkButton not shown on Phoscon Hub

### ISSUE THREAD

**Issue by malmentm** [ebaauw/homebridge-hue#897]
Hello
Just installed homebridge-hue from scratch and set the linkbutton to "true" to be able to hide it from favorites in home app. That options does no longer seem to work? It worked in 0.12.14. Is this a bug?

**Comment by ebaauw** [comment]
Yes, in v0.12.16 the `linkButton` setting only works for Hue bridges.  Sorry.  Fixed in v0.12.17.

**Comment by malmentm** [comment]
Thanks! 👍
