### ISSUE TITLE
Support sensor config

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-hue#9]
Currently homebridge-hue only supports the `on`, `battery`, and `alert` sensor `config` attributes, where `on` maps to `StatusActive`, which is readonly in homekit, `battery` to `BatteryLevel` and `alert` to `Identify`, which is write only in homekit.

I wanted to support enabling/disabling a sensor from homekit, by mapping `on` to a homekit `On` characteristic.  However homekit doesn't support multiple characteristics of the same type for one service (which would be needed for enabling/disabling a CLIPGenericFlag or supporting additional boolean configuration parameters, like `ledindication` and `usertest`.  Homekit does support multiple services per accessory, but this seems to confuse most homekit apps.

**Comment by sommo** [comment]
to enable or disable sensor i installed the other repo plugin homebridge-huesensor, it can do the trick, don't know what's the difference between yours plugin

**Comment by ebaauw** [comment]
Hi @sommo 
As far as I can see, they don't expose the sensor value itself.  They only support enabling/disabling the sensor.  Therefore they don't run into a conflict of multiple `On` characteristics per service.

**Comment by ebaauw** [comment]
HomeKit now provides a read/write characteristic `Active` in addition to the read-only `Status Active`.    I'll use `Active` to enable/disable a sensor - no need for an additional service for a (potentially) second `On` characteristic.

**Comment by ebaauw** [comment]
Since recently, Siri also sets the `Active` characteristic off (in addition to the `On` characteristic), when askied to turn off a room, effectively disabling all sensors.

To avoid this, v0.2.0 uses a custom characteristic `Enabled` instead of `Active`.

In v0.2.0, `BatteryLevel` is exposed in a separate `BatteryStatus` service, consistent with Apple's iOS 10.3 Home app.  This service also includes mandatory characteristics `StatusLowBattery` and `ChargingState`.  The threshold for low battery can be set in `config.json`.  `ChargingState` is always _Not Chargeable_.

I'm closing this issue now, as I have no plans to support the other `config` attributes.
