### ISSUE TITLE
Duplicate sensors and bridge in "Default Room", all "Not Supported"

### ISSUE THREAD

**Issue by JosephDuffy** [ebaauw/homebridge-hue#90]
Since installing homebridge-hue a few months ago I've had 3 phantom accessories in my Home app. They are called "Daylight" (a daylight sensor), "MotionSensor 3.Companion" (a motion sensor), and "Philips hue" (a bridge). The manufacturer of all of these is "homebridge-hue", and they all show as "Not Supported".

I will note that I upgraded to the latest version of homebridge-hue and the "Daylight" sensor has become functional, although I now have 2 light sensors, one named "Daylight" and the other (original) one called "Ambient light sensor 1".

I have 2 non-Hue lights and 1 Hue motion sensor. The lights are coming through fine, but the motion sensor seems to be causing issues. If I disable sensors in the config file it makes the extra motion sensor go away, but the extra bridge is still present.

Below is a copy of my `~/.homebridge/config.json` file:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },

    "platforms": [
        {
            "platform": "Hue",
            "name": "Hue",
            "users": {
                "0...": "T..."
             },
	    "sensors": true,
            "lights": true,
	    "heartrate": 1
        }
    ]
}
```

**Comment by ebaauw** [comment]
There's nothing phamtom about these accessories - it's just the iOS builtin Home app thet doesn't support them.  They are functional in other HomeKit apps.

"Daylight" is the builtin daylight sensor from your Hue bridge.  "Motionsensor 3.Companion" is likely a CLIPGenericStatus sensor created by the Hue app for the motion sensor.  You can disable these by using the `excludeSensorTypes` key in config.json, see the README, section 8.

"Philips hue" is not a sensor nor a bridge, but a regular accessory homebridge-hue creates for your Hue bridge.  It cannot be disabled.
