### ISSUE TITLE
Removing IKEA KADRILJ / FYRTUR from deconz does not remove from homekit

### ISSUE THREAD

**Issue by malmentm** [ebaauw/homebridge-hue#900]
Hello
When i try to remove a KADRILJ or FYRTUR blind from Phoscon GW it is removed from the Phsocon gateway but remains in homekit as an usupported device with a house symsol instead of the normal curtain.

**Comment by ebaauw** [comment]
Be sure to delete also the ZHABattery `/sensors` resource from deCONZ.

**Comment by malmentm** [comment]
I know this isn't a deconz support forum but how can i do that? :D

**Comment by ebaauw** [comment]
Through the API.  I prefer to use `ph`, but any REST API client like `postman` or even `curl` will do.

Do a GET on `/sensors` to see if there's any stale ZHABattery sensors for the blinds, then do a DELETE of `/sensors/xx` for each of these resource.

**Comment by malmentm** [comment]
thanks!

**Comment by Helgimagg01** [comment]
I am having this same issue, I am struggling to find out how to execute the command to access the sensors to get the option to delete the stale ones, can somebody share the command string? (I have curl installed)
Thanks in advance
