### ISSUE TITLE
request 1: get /config request 1: invalid response

### ISSUE THREAD

**Issue by pponce** [ebaauw/homebridge-hue#901]
Hi I recently just updated to the latest homebridge hue. And I’m getting and invalid response error.
I’m using the host setting and specifying the location of my bridge. I’m using the right IP.

Also of note. I have one hue bridge version 2. That one does not show the error. I get a 200 ok response from the get /config request.

The bridge I have an issue with is my deconz running on the same rPi that homebridge is running on.

Anything I can send you to troubleshoot?

**Comment by ebaauw** [comment]
Did you double-check the port?

**Comment by pponce** [comment]
Apologies: Where do i check and or set the port?
I don't believe i've changed any default ports.
i've not changed any settings (at least i don't think i have) and have been running fine for years.

**Comment by pponce** [comment]
Just to test i systematically installed past versions until i got things working again.
v0.12.14 works fine for me.
V.0.12.15 and higher don't see to work for me. I get the same error.

**Comment by ebaauw** [comment]
Could you list the output of `ph -DD -H `_host_` config`, substituting the `hosts` entry for deCONZ from config.json for _host_?

**Comment by pponce** [comment]
Sure will do that later today and send your way.
Should be fine to stay on v0.12.14 correct?
Assuming yes.

**Comment by pponce** [comment]
Ok here is the output when running on v0.12.14
pi@homebridge:~ $ ph -DD -H 192.168.84.3 config
192.168.84.3: request 1: GET /config
192.168.84.3: request 1: GET http://192.168.84.3/api/config
192.168.84.3: request 1: response: {"apiversion":"1.16.0","bridgeid":"XXXXXXXXX","datastoreversion":"93","devicename":"RaspBee","factorynew":false,"mac":"XX:XX:XX:XX:XX:XX","modelid":"deCONZ","name":"Phoscon-GW","replacesbridgeid":null,"starterkitid":"","swversion":"2.9.0"}
192.168.84.3: request 1: 200 OK
{
  "apiversion": "1.16.0",
  "bridgeid": "XXXXXXXXXX",
  "datastoreversion": "93",
  "devicename": "RaspBee",
  "factorynew": false,
  "mac": "XX:XX:XX:XX:XX:XX",
  "modelid": "deCONZ",
  "name": "Phoscon-GW",
  "replacesbridgeid": null,
  "starterkitid": "",
  "swversion": "2.9.0"
}

**Comment by ebaauw** [comment]
What is the `bridgeid`?  It should be the Zigbee mac address of the RaspBee or ConBee: 16 hexadecimal digits in uppercase (starting with `00212EFFFF`).

**Comment by pponce** [comment]
Ah sorry. I removed that thinking maybe should not be shared in the open.

**Comment by ebaauw** [comment]
It seems to be derived from the network mac address of the server?  Homebridge Hue doesn’t actually check for that, but it does expect it to be in uppercase.

**Comment by pponce** [comment]
Yes. That’s what it looks like. is there something I need to change?
Homebridge-hue seems to work fine in v0.12.14 and has been working perfectly since forever. 😄 
Would changing my bridge ID to upper case in the user  block of the config do the trick?

**Comment by ebaauw** [comment]
I added a sanity check in v0.12.15, because pi hole also exposes a `/api/config` endpoint, causing some nasty errors later on when people misconfigured Homebridge Hue.  I’ll relax the sanity check to accept lowercase as well.

**Comment by pponce** [comment]
Thanks! I wonder how I ended up with a lower case bridge ID.

**Comment by pponce** [comment]
Just wanted to report back that things are working fine with the HueDiscovery.js edits you made.
thanks again!
