### ISSUE TITLE
Adding door/window sensor

### ISSUE THREAD

**Issue by Johan8012** [ebaauw/homebridge-hue#903]
#### Issue

Hello! I'm new to this sorry. I have HOOBS and installed the Hue plugin. I have a hue bridge (v2, square). I pressed the hue hub button and got the hue plugin connected to the hub. Now I have a door window sensor Mijia named. ( I believe its the same as aqara). How do I connect the sensor to  the hue hub, and hue plugin?

#### Log Messages

```
```

**Comment by ebaauw** [comment]
> How do I connect the sensor to the hue hub

You don't; the Hue bridge only supports (friends-of-)Hue sensors and switches.  See https://github.com/ebaauw/homebridge-hue/wiki/Features.
