### ISSUE TITLE
List of Ikea Sensor types or Phoscon group id names? 

### ISSUE THREAD

**Issue by Farmand77** [ebaauw/homebridge-hue#905]
#### Issue

I would like to know if there is a list of sensor type names for Ikea products or might be Phoscon names i need.
Reason is that i create groups in the Phoscon software to make sure Lights and switches are working if Homebridge is down.
This creates 4 new switches that is exposed to Homebridge and apple homekit. This makes the overview confusing.
Exclude sensor types in the config should be able to remove these if i only know the "name"

#### Log Messages

```
```

**Comment by ebaauw** [comment]
I don’t use Phoscon, better ask in their repo.
