### ISSUE TITLE
Duplicated Devices in Homekit

### ISSUE THREAD

**Issue by McFly24** [ebaauw/homebridge-hue#906]
Is there any option to add the lights etc. only to the homebridge config ui.

When i add the hue-bridge to the homebridge i got all the devices 2 times in the homekit app because i have the hue bridge in the homekit app and i don't wont to remove it

**Comment by ebaauw** [comment]
Don’t pair Homebridge with HomeKit.

**Comment by McFly24** [comment]
is there any other option to add the lights without having it duplicated in homekit

**Comment by ebaauw** [comment]
Don’t pair the Hue bridge with HomeKit, but you don’t want to do that.
