### ISSUE TITLE
request 1: get /config request 1: invalid response - again

### ISSUE THREAD

**Issue by jojodat** [ebaauw/homebridge-hue#909]
Hi, i have the same issue as in https://github.com/ebaauw/homebridge-hue/issues/901 - at least i thought so
But for me the Update didn't help.
Here is my "ph -DD -H" output on v0.12.14

`192.168.0.213: request 1: GET /config
192.168.0.213: request 1: GET http://192.168.0.213/api/config
192.168.0.213: request 1: response: {"name":"Philips hue","mac":"CC:50:E3:29:0E:D5","dhcp":true,"ipaddress":"192.168.0.213","netmask":"255.255.255.0","gateway":"192.168.0.1","proxyaddress":"none","proxyport":0,"bridgeid":"CC50E3FFFE290ED5","UTC":"2021-01-22T23:02:21","whitelist":{"290ed5":{"last use date":"2021-01-22T23:02:21","create date":"2021-01-22T23:02:21","name":"Remote"}},"swversion":"01041302","apiversion":"1.17.0","swupdate":{"updatestate":0,"url":"","text":"","notify":false},"linkbutton":false,"portalservices":false}
192.168.0.213: request 1: 200 OK
{
  "name": "Philips hue",
  "mac": "CC:50:E3:29:0E:D5",
  "dhcp": true,
  "ipaddress": "192.168.0.213",
  "netmask": "255.255.255.0",
  "gateway": "192.168.0.1",
  "proxyaddress": "none",
  "proxyport": 0,
  "bridgeid": "CC50E3FFFE290ED5",
  "UTC": "2021-01-22T23:02:21",
  "whitelist": {
    "290ed5": {
      "last use date": "2021-01-22T23:02:21",
      "create date": "2021-01-22T23:02:21",
      "name": "Remote"
    }
  },
  "swversion": "01041302",
  "apiversion": "1.17.0",
  "swupdate": {
    "updatestate": 0,
    "url": "",
    "text": "",
    "notify": false
  },
  "linkbutton": false,
  "portalservices": false
}`

and on v0.12.18
`ph: 192.168.0.213: request 1: GET /config
ph: 192.168.0.213: request 1: GET http://192.168.0.213/api/config
ph: 192.168.0.213: request 1: response: {"name":"Philips hue","mac":"CC:50:E3:29:0E:D5","dhcp":true,"ipaddress":"192.168.0.213","netmask":"255.255.255.0","gateway":"192.168.0.1","proxyaddress":"none","proxyport":0,"bridgeid":"CC50E3FFFE290ED5","UTC":"2021-01-22T23:11:31","whitelist":{"290ed5":{"last use date":"2021-01-22T23:11:31","create date":"2021-01-22T23:11:31","name":"Remote"}},"swversion":"01041302","apiversion":"1.17.0","swupdate":{"updatestate":0,"url":"","text":"","notify":false},"linkbutton":false,"portalservices":false}
ph: 192.168.0.213: request 1: 200 OK
ph: 192.168.0.213: request 1: GET /config
ph: warning: 192.168.0.213: request 1: invalid response
ph: error: 192.168.0.213: not a Hue bridge nor deCONZ gateway`

Info: i have no original Philips or Deconz - it is a Lightbulb is flashed with Tasmota and enabled there the Hue Switch Emulation

**Comment by ebaauw** [comment]
Not exactly the same issue.  The `bridgeid` value is in uppercase alright, but the Tasmota doesn’t seem to expose `modelid` (for the virtual bridge).  I’ll relax the sanity check a bit more.

Please note that I only support the Hue bridge and deCONZ gateway.  I’m happy that Homebridge Hue works with Tasmota, but I don’t have any such device to test.

**Comment by ebaauw** [comment]
In v0.12.18.

**Comment by jojodat** [comment]
I have to thank you even more for the change, although tasmota is not supported.
