### ISSUE TITLE
Need help reinstalling

### ISSUE THREAD

**Issue by scottsimon1979** [ebaauw/homebridge-hue#91]
Hello - I had Homebridge-hue up and running for a bit, but was having some issues with it and instead of messing with the config - I just uninstalled it and decided to run my lights through Smartthings integration.  Turns out I don't like that so much (the smart things platform doesn't seem to be near as responsive) so I'd like to reinstall homebridge-hue.  The problem is that now it won't work...it keeps saying that says "[Hue] 192.168.1.116: hue bridge request #1: get /config
[3/30/2017, 12:41:12 PM] [Hue] 192.168.1.116: hue bridge communication error ETIMEDOUT
[3/30/2017, 12:41:12 PM] [Hue] 192.168.1.116: 0 accessories

I've tried erasing the config in the json and removing the users field, but it won't connect nor prompt me again to "re-pair" the bridge.  Can you give me any guidance on how I can just reset it and set it back up as new?

Thank you in advance!!

**Comment by ebaauw** [comment]
It would seem like homebridge-hue is using the wrong (an old?) IP address of your Hue bridge.  Did you specify that in config.json, using the `host` key?  The `users` key is used for the api username, not for discovering the bridge.  If you remove the `host` key, homebridge-hue should discover your bridge at its current IP adddress.

If this is the right IP address, then please attach your config.json and the output of `homebridge -D`.
