### ISSUE TITLE
Keeps Asking for Button Press

### ISSUE THREAD

**Issue by thelewiss1** [ebaauw/homebridge-hue#911]
#### Issue
In the log, I keep getting asked to press the link button.
I have copied the line from the log into the config and yet when i restart HOOBs it asks again. It works fine even though it is asking

#### Log Messages

```
4/01/2021, 14:55:39 [Hue] Philips Hue: request 255: POST / {"devicetype":"homebridge-hue#hoobs"}
24/01/2021, 14:55:39 [Hue] Philips Hue: request 255: api error 101: link button not pressed
24/01/2021, 14:55:39 [Hue] Philips Hue: press link button on the bridge to create a user - retrying in 15s
24/01/2021, 14:55:54 [Hue] Philips Hue: request 256: POST / {"devicetype":"homebridge-hue#hoobs"}
24/01/2021, 14:55:54 [Hue] Philips Hue: request 256: api error 101: link button not pressed
24/01/2021, 14:55:54 [Hue] Philips Hue: press link button on the bridge to create a user - retrying in 15s
```

#### Debug Files

I'm not sure where to find the log files.

### Configuration
`            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "users": {
                "001XX8XXXEA06XXX": "e0fDSwPhXXXXXXXXXXXXXXXXXXXXXXXXXXGzKXTx7"
            },
            "noResponse": true,
            "rooms": false,
            "rules": false,
            "scenes": false,
            "scenesAsSwitch": false,
            "schedules": false,
            "sensors": false,
            "lights": true,
            "linkButton": true,
            "lowBattery": 25,
            "groups": false,
            "group0": false,
            "heartrate": 5,
            "hueMotionTemperatureHistory": false,
            "hueDimmerRepeat": true,
            "timeout": 5,
            "waitTimePut": 50,
            "waitTimePutGroup": 1000,
            "waitTimeResend": 300,
            "waitTimeUpdate": 20,
            "wallSwitch": false,
            "parallelRequests": 10,
            "forceHttp": false,
            "forceEveWeather": false,
            "brightnessAdjustment": 100,
            "configuredName": false,
            "excludeSensorTypes": [],
            "hosts": []`

**Comment by ebaauw** [comment]
Please attach the full log file.

**Comment by thelewiss1** [comment]
I've found it. It was different than what it would be in homebridge.
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5862538/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
That's the dump file Homebridge Hue makes on startup, listing the devices connected to the Hue bridge.  I need the Homebridge log file from starting Homebridge, while Homebridge DEBUG mode is enabled.

**Comment by thelewiss1** [comment]
It seems that after rebooting HOOBs the problem has gone away.
Thank you.
