### ISSUE TITLE
HUE Bridges (not) as tile in HK

### ISSUE THREAD

**Issue by Christian-CFP** [ebaauw/homebridge-hue#913]
Hey how are you?

So I have a little problem and I need help if it is possible.
The HUE bridges are included as tiles in HK. These also appear under favorites. I don't have the option to remove this from my favorites - which would be enough for me.

But my question would be: Is it possible not to implement the HUE Bridges as independent tiles in HK?

It's a bridge and shouldn't appear as a device.

**Comment by ebaauw** [comment]
See FAQ

**Comment by Christian-CFP** [comment]
Thank you. 
I'm sorry about it. Should have looked in there beforehand.
