### ISSUE TITLE
Auto diyHue Bridge activation

### ISSUE THREAD

**Issue by g-philipp** [ebaauw/homebridge-hue#914]
Currently i have a startscript in homebridge to activate the bridge via curl (/hue/linkbutton?username=&password=&action=Activate). Sometimes it works and sometimes it doesnt, can this be a feature to automaticly trigger the button, so that you can checkbox the setting auto connect or something like that and you can define user and password. The curl command is: `curl --user user:password http://ip/hue/linkbutton?action=Activate`

**Comment by ebaauw** [comment]
What issue are you trying to solve?

**Comment by g-philipp** [comment]
The issue that it wont connect to the bridge until you click the button yourself

**Comment by ebaauw** [comment]
See the README and the FAQ
