### ISSUE TITLE
motion detectors

### ISSUE THREAD

**Issue by tuxnetDE** [ebaauw/homebridge-hue#915]
Is it possible to integrate a switch that activates / deactivates the motion detectors ?

**Comment by ebaauw** [comment]
It’s already there.  The _Enabled_ characteristic matches `config.on`.  Technically this doesn’t disable the sensor, but causes the bridge/gateway to ignore sensor updates.  The Hue bridge truly no longer updates the `state`; deCONZ no longer fires rules, but still updates the state - this is a bug in deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/90.

**Comment by bkarakashev** [comment]
Hi @ebaauw, is this functionality enabled in any of your Hue/deCONZ plugins?
https://github.com/steedferns/homebridge-huesensors#readme
Like are you able to toggle a switch that disables any motion sensors and then toggle back the switch?
For example, if you don't want your lights to be triggered by the sensor, switch them off.
Currently, I am using the HueSeonsors plugin but if it is all supported in deCONZ or Hue/Hue2 plugging then I don't need 2 plugins for that 🙂
Thanks in advance.
