### ISSUE TITLE
Bridge not found - retrying in 30s after update from 0.12.12 to a newer version

### ISSUE THREAD

**Issue by AlexKusnezov** [ebaauw/homebridge-hue#916]
#### Issue

after updating the plugin from 0.12.12 to a newer version my huebridge (diyHue) isn't recognized anymore. Tried the latest version today
I run homebridge in docker v1.2.5

#### Log Messages

```
[1/29/2021, 9:51:44 AM] [Hue] 192.168.2.109: request 1: GET /config
[1/29/2021, 9:51:44 AM] [Hue] 192.168.2.109: request 1: invalid response
[1/29/2021, 9:51:44 AM] [Hue] 192.168.2.109:80: not found - retrying in 30s
[1/29/2021, 9:51:44 AM] [TuyaWebPlatform] Missing required `id` property on device configuration, received:
{
  "device_type": "form"
}
```

#### Debug Files

[homebridge.log.txt](https://github.com/ebaauw/homebridge-hue/files/5893048/homebridge.log.txt)

**Comment by ebaauw** [comment]
Probably similar to #901.  What is the output of `ph -H 192.168.2.109 -DD config`?

Note that I only support the Hue bridge and deCONZ gateway.  I'm happy for Homebridge Hue to work with other (virtual) bridges, but I cannot test them.

**Comment by AlexKusnezov** [comment]
@ebaauw this is what I get with v.0.12.12:
```
request 1: GET /config
request 1: GET http://192.168.2.109/api/config
request 1: response: {"name":"RPi diyHue","datastoreversion":70,"swversion":1942135050,"apiversion":"1.35.0","mac":"b8:27:eb:b5:da:33","bridgeid":"B827EBFFFEB5DA33","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}
request 1: 200 OK
request 1: GET /config
request 1: GET http://192.168.2.109/api/config
request 1: response: {"name":"RPi diyHue","datastoreversion":70,"swversion":1942135050,"apiversion":"1.35.0","mac":"b8:27:eb:b5:da:33","bridgeid":"B827EBFFFEB5DA33","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}
request 1: 200 OK
{
  "name": "RPi diyHue",
  "datastoreversion": 70,
  "swversion": 1942135050,
  "apiversion": "1.35.0",
  "mac": "b8:27:eb:b5:da:33",
  "bridgeid": "B827EBFFFEB5DA33",
  "factorynew": false,
  "replacesbridgeid": null,
  "modelid": "BSB002",
  "starterkitid": ""
}
```

**Comment by AlexKusnezov** [comment]
>Note that I only support the Hue bridge and deCONZ gateway. I'm happy for Homebridge Hue to work with other (virtual) bridges, but I cannot test them

@ebaauw It's fine I'll stick with 0.12.12 for now

**Comment by ebaauw** [comment]
Hm, the response seems valid to me.  Did you run `ph` from within the container?

Please capture and attach a full debug log, running Homebridge in DEBUG mode, so Homebridge Hue logs the request and response to/from diyHue.
