### ISSUE TITLE
Problems with ZGPSWITCH and FOHSWITCH

### ISSUE THREAD

**Issue by modi80** [ebaauw/homebridge-hue#917]
#### Issue

Hey, I have a problem with the Hue Switches ZGPSWITCH and FOHSWITCH. Inside the Hue-App the two switches are working great. If I use them via Apple Home the programmed scenes/switches of devices sometimes are not being executed. In that case I have to press the button a few times until it's working. It is noticeable that the push on the button of the switch is recognized in the configuration window in Apple Home, even though the programmed command is not being executed.

#### Log Messages

```
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5894843/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
See the FAQ, this is a communication issue between your home hub and Homebridge.

**Comment by modi80** [comment]
Hey, thank you for your help and your project. I already thought that an (wireless connected) iPad is not efficient enough as Home Hub. Therefore i ordered an Apple TV now.
