### ISSUE TITLE
Unable to rename Accessories

### ISSUE THREAD

**Issue by sieren** [ebaauw/homebridge-hue#919]
#### Issue

I'm unable to rename accessories exposed from homebridge-hue. Somehow these jump back to the ones defined in Deconz after a few minutes. Has this always been like that? 
This only happens with devices exposed through homebridge-hue, I had no issues renaming other devices exposed through homebridge (e.g. MQTT devices).
Running v0.12.21

https://user-images.githubusercontent.com/5174440/106485916-6156ce80-64b1-11eb-8959-2776d43e6e8f.mov

#### Log Messages

```
```

**Comment by sieren** [comment]
Ah, seems to be related to https://github.com/ebaauw/homebridge-hue/issues/910 ... just curious: Why is this the default behaviour and not the other way around?

**Comment by ebaauw** [comment]
I don’t want to expose _Configured Name_ for new installations.
