### ISSUE TITLE
Declaring a ZigBee lamp as something different?

### ISSUE THREAD

**Issue by permaMonk** [ebaauw/homebridge-hue#921]
I just added a Zigbee Sonoff Basic ZBR3 under the deCONZ Phoscon web app as a light. Yes as a light not as a switch. This is how it has to be, according to deCONZ.

Via HB Hue plugin and settings "lights": true I´ve got it into Homekit. Therefore, the device is logically presented as a lamp in the Homekit.

Are there any setting options in the hue plugin to declare this device as something other than a lamp (icon)?

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links.

**Comment by permaMonk** [comment]
Ok that's looking really as I´m searching for.
But I'm little confused how to set the settings.

1. In settings of the hue plugin go to "How" and set "Resources" on. Now I can see in my HB config ""resource": false,". Should be at "true"?
2. Restart
3. I think I need the "outlet" entry. So where I should set in fx your example
$ ph outlet -v
ph outlet: /resourcelinks/6: 0 outlets
$ ph get /resourcelinks/6
{
  "classid": 1,
  "description": "outlet",
  "links": [],
  "name": "homebridge-hue",
  "owner": "**********",
  "recycle": false,
  "type": "Link"
}

in my config
{
            "name": "Hue",
            "anyOn": true,
            "effects": false,
            "excludeSensorTypes": [
                "Daylight",
                "Geofence",
                "CLIP"
            ],
            "heartrate": 30,
            "hosts": [
                "xxx.xxx.xxx.xxx",
                "yyy.yyy.yyy.yyy"
            ],
            "hueMotionTemperatureHistory": false,
            "lights": true,
            "linkButton": false,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "sensors": true,
            "users": {
                "xxx": "111",
                "yyy": "222"
            },
            "platform": "Hue"
        },

**Comment by permaMonk** [comment]
Ok with ""resource": true," I see an extra field of the Sonoff Basic with "/LIGHTS/2" in the Eve app.

**Comment by ebaauw** [comment]
See the Wiki: resource links are on the Hue bridge or deCONZ gateway.  Nothing to do with config.json.

**Comment by permaMonk** [comment]
Ups. Ok.
