### ISSUE TITLE
Hue with Samotech

### ISSUE THREAD

**Issue by pjbarnett** [ebaauw/homebridge-hue#923]
Just wondering if someone here can help. However not really Homebridge related.

I have the common home sync issue with rooms created in Homebridge and Hue but I dont think thats the issue.

I've got another make inline dimmers throughout and all added to hue and Apple home witihout issue.

Added 4 Samotech switch units over the weekend and they have all come into Hue and then onto Apple Home without issue as they were added. However I have 2 devices that show perfectly fine in Hue app but when I add the 2nd one (doesnt matter on the order) the previous 1 disappears from Apple Home. If I then delete and re add the last one into hue, it comes back but the previous one disappears again from Apple Home. But both stay in Hue and have control without issue!!

Very frustrating so I was hoping someone had worked around it. I was wondering if I change the option that Homebridge shows all hue lights, maybe I can then see them that way rather than Hue syncing to Home directly.

Any thoughts or suggestions?

**Comment by ebaauw** [comment]
> I have the common home sync issue with rooms created in Homebridge and Hue but I dont think thats the issue.

The Homebridge UI isn't linked to HomeKit; it keeps its own set of rooms and room assignments.  HomeKit rooms can only be accessed by HomeKit apps, which need to run on iOS (or similar or macOS).

> Added 4 Samotech switch units over the weekend and they have all come into Hue and then onto Apple Home without issue as they were added.

Are these the wireless Friends-of-Hue switches?  Do you expose them through Homebridge Hue or through the Hue bridge?  If through Homebridge Hue, please attach the debug dump file and capture and attach a debug log file, see README.  If though the Hue bridge, I cannot help you.

**Comment by pjbarnett** [comment]
Thank you for coming back to me. 

Yes i've been reading on various forums about the Hue app sync causing issues when syncing. For example every time it tries to sync it moves 1 of my rooms Homebridge kit to Default room, and moves some heating thermostats to other rooms! So it then takes me about 5 mins to rearrange all the rooms again in Homekit.

So the Samotech are the 1 channel light switching unit SM308 which sits behind a retractive switch for local on/off of the circuit. At the moment I simply added them with Hue app as a light and then they show in Apple Homekit. So I don't currently bring anything in Homebridge that is already added from the Hue app.

Am I correct in saying there is an option that would then bring them into Homebridge using your module and therefore I don't need the Hue to sync anything to Homekit to fix this and the annoying random moving of kit?

Kind regards

**Comment by pjbarnett** [comment]
Just a quick update to redeem myself from being lazy and not experimenting.

I used the:- 

"nativeHomeKitLights": false

option and now I have all the lights from the Hue within Homebridge with your module thank you. Obviously I have a few duplicates now that the Hue app has successfully linked to HomeKit however I can deal with that. At least this way I can add anything I need into hue and get straight back out of the app without it attempting to sync and messing up my layout.

Kind regards
