### ISSUE TITLE
Support for Tuya 4 Button Switch

### ISSUE THREAD

**Issue by cdc31** [ebaauw/homebridge-hue#924]
Hi,

Could you please add support for the Tuya 4 button switch? It works with Conbee2 but shows as unsupported device in HomeKit when connecting to phoscon using the hue plugin. 

This thread contains the details on its implementation in phoscon/deconz:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3611

Thank you!

Clemens

**Comment by ebaauw** [comment]
Please list the message that Homebridge Hue logs on the unsupported switch.  Also please provide an overview of the buttons, incl. their labels and possible `buttonevent` values.

**Comment by c-chaskel** [comment]
Hi ebaauw,

of course:

[Hue] Phoscon-GW: /sensors/79: **warning: ignoring unknown ZHASwitch sensor** {"config":{"battery":null,"on":true,"reachable":true},"ep":1,"etag":"1534913eb91c7517dc81d10a5da07215","lastseen":"2021-02-10T12:24Z","manufacturername":"_TZ3000_vp6clf9d","mode":1,"modelid":"TS0044","name":"Switch","state":{"buttonevent":null,"lastupdated":"none"},"type":"ZHASwitch","uniqueid":"5c:02:72:ff:fe:c8:83:9b-01-0006"}

Short press
buttonevent: 4002

Long press
buttonevent: 4003

Double press
buttonevent: 4003

That's the top left button. 

Others (same ending digits for short, long and double press as above) 
  top left             400*
  top right           300*
  bottom left      100*
  bottom right    200*
  
In Homekit it is shown as follows with no function:
![homekit](https://user-images.githubusercontent.com/39637693/107511562-f0e13900-6ba5-11eb-9d11-db0375a7d054.png)

Regards

Clemens

**Comment by ebaauw** [comment]
Is that the same `buttonevent` value for long press and double press?

**Comment by c-chaskel** [comment]
> Is that the same `buttonevent` value for long press and double press?

No, copy-paste stupidity. Sorry... Corrected it!

**Comment by ebaauw** [comment]
In v0.12.22.

**Comment by c-chaskel** [comment]
> In v0.12.22.

Working flawless. Thank you!!!

I got a little confused about the mapping of the switch buttons when testing just now, as button 1 is not actually top left.
However, that's exactly how it is written in the manual, so it's correct. :)

Here's the button mapping as a reference for anyone else who would expect button 1 on the top left:

![buttons](https://user-images.githubusercontent.com/39637693/107763482-fcac3700-6d2e-11eb-95cd-6f1a7d2832ed.jpg)


Thanks!

Clemens

**Comment by ebaauw** [comment]
> I got a little confused about the mapping of the switch buttons when testing just now, as button 1 is not actually top left.

That's what you indicated yourself:
> Others (same ending digits for short, long and double press as above)
top left 400*
top right 300*
bottom left 100*
bottom right 200*

It's quite common for Friend-of-Hue switches to number the buttons counter-clockwise.  I have no clue about Tuya.

**Comment by c-chaskel** [comment]
> It's quite common for Friends-of-Hue switches to number the buttons counter-clockwise. I have no clue about Tuya.

Yes, your implementation is spot on. Exactly what the manual says!

In the Homekit app the buttons are numbered and start bottom left, going anti-clockwise.
Just wanted to highlight this as it confused me at first.

Nothing to change, all correct. :)

Thanks!
Clemens
