### ISSUE TITLE
SONOFF ZBMini: Switch identified as Light, unable to change to Fan

### ISSUE THREAD

**Issue by retrography** [ebaauw/homebridge-hue#929]
I am currently experiencing the exact same issue as #361 with SONOFF ZBMini (Model: 01MINIZB): It is identified as a light, with no possibility of changing the type. I saw the Feibit patch and tried to adapt it to SONOFF but it didn't work:

```js
  SONOFF: {
    models: {
      '01MINIZB': {
        fix: function () {
          this.obj.type = 'On/Off plug-in unit'
        }
      }
    }
  }
```

What am I missing here?

**Comment by ebaauw** [comment]
See the FAQ, you need to create an `outlet` resource link on the Hue bridge, listing the resources to be exposed as _Outlet_.

**Comment by retrography** [comment]
My bad. I should have read better and done my homework! Thanks.
