### ISSUE TITLE
Support for deconz v2.10.0-beta devices

### ISSUE THREAD

**Issue by palletodap** [ebaauw/homebridge-hue#930]
#### Issue
Deconz v2.10.0-beta supports a lot of new devices, but devices like the Lidl doorbell isn't supported by this plugin yet.

Right now it shows up in homekit as an "Not supported" device, and cannot be hidden :/

**Comment by ebaauw** [comment]
Create a `blacklist` resource link to exclude the unsupported devices from being exposed, see Wiki.

Please list the warning messages created by Homebridge Hue to request support for these devices.  For switches, please also list the labels on the buttons and the `buttonevent` values.

**Comment by palletodap** [comment]
Hi, Thanks for the response! 

Is node-red debug (deconz plugin) values enough for you?- or should I get them from somewhere in the deconz gui?

Sorry for the stupid questions, i'm still trying to figure out all of this debugging stuff😅

**Comment by ebaauw** [comment]
From the Homebridge log.

**Comment by palletodap** [comment]
Im using HOOBS (Dont know if that makes a difference), and it's not showing anything in the log when the im pressing the button.

Here's what i get in the output i get from node-red, when i do a normal single-press (Hope that's useful for something):

{"topic":"","payload":{"lastupdated":"2021-02-22T19:14:51.868","lowbattery":false,"tampered":false},"payload_raw":{"e":"changed","id":"42","r":"sensors","state":{"lastupdated":"2021-02-22T19:14:51.868","lowbattery":false,"tampered":false},"t":"event","uniqueid":"84:2e:14:ff:fe:f3:0f:e3-01-0500"},"meta":{"config":{"battery":100,"enrolled":1,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"e7ef54e743f9a19a57563410ac846663","lastseen":"2021-02-22T19:14Z","manufacturername":"SILVERCREST","mode":1,"modelid":"TS0211","name":"TS0211 42","state":{"lastupdated":"2021-02-22T19:14:51.868","lowbattery":false,"tampered":false},"swversion":"2020.8.4","type":"ZHASwitch","uniqueid":"84:2e:14:ff:fe:f3:0f:e3-01-0500","device_type":"sensors","device_id":42},"_msgid":"4c3f18fa.3148a8"}

**Comment by ebaauw** [comment]
Homebridge Hue issues warning messages on startup, indicating that it's ignoring an unknown device.  I don't know how or where hoobs keeps the Homebridge log.  For switches, I also need to know what the buttons are called, and what button events they support.

**Comment by palletodap** [comment]
Error from homebridge log:

`[Hue] Phoscon-GW: /sensors/42: warning: ignoring unknown ZHASwitch sensor {"config":{"battery":100,"enrolled":0,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"92f5a7cad94ee27e559d819866c0391e","lastseen":"2021-02-23T09:51Z","manufacturername":"SILVERCREST","mode":1,"modelid":"TS0211","name":"TS0211 42","state":{"buttonevent":0,"lastupdated":"2021-02-22T19:15:09.752","lowbattery":false,"tampered":false},"swversion":"2020.8.4","type":"ZHASwitch","uniqueid":"84:2e:14:ff:fe:f3:0f:e3-01-0500"}`

**Comment by ebaauw** [comment]
Is that the doorbell?  What buttonevent values does it generate?

**Comment by palletodap** [comment]
Yea that's the doorbell. 

Normally I'm able to see the event values through node-red debug of the deconz output, but I can't see any event when I press this one...

It only shows its status values like I showed in my previous comment. 

I haven't had the chance to look inside deconz directly, but I will check asap.
