### ISSUE TITLE
Phillips Hue Dimmer Delay

### ISSUE THREAD

**Issue by LewisSpring** [ebaauw/homebridge-hue#931]
#### Issue

When using the Dimmer Remote device provided by the plugin, it takes a few seconds after keypress for anything to change.
This is different to the native dimmer and Lights - they have no delay
#### Log Messages

```
[20/02/2021, 11:01:26] [Hue] Dimmer Switch Off: homekit button single press
[20/02/2021, 11:01:51] [Hue] Dimmer Switch Dim Down: homekit button single press
[20/02/2021, 11:03:36] [Hue] Dimmer Switch On: homekit button long press
```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6014786/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
You're using a Hue bridge with a (default) `heartrate` of 5 seconds.  That means it can take up to 5 seconds for Homebridge Hue to next poll the Hue bridge and notice the button action.

**Comment by LewisSpring** [comment]
Hi there! Thanks.
Is there any reason not to make the heartrate slower?

**Comment by ebaauw** [comment]
Not as long as the server running Homebridge and the Hue bridge can handle it.  Using a value of 2 should work on a gen-2 (square) Hue bridge.  A value of 1 usually doesn't.

**Comment by LewisSpring** [comment]
Awesome! Thanks!
