### ISSUE TITLE
Hue Plugin makes Hoobs crash

### ISSUE THREAD

**Issue by AndiGlaesser** [ebaauw/homebridge-hue#934]
#### Issue
Its a brand new installation of Hoobs with a Phoscon RaspBee II. Both installations behave without any problems.
As soon as I install the Hue/deConz plugin, Hoobs crashes or the service stops. There is no way to restart the service. Only after uninstalling Hue/deConz does Hoobs run normally again.

#### Log Messages

```
[Hue] Philips hue: request 12: POST / {"devicetype":"homebridge-hue#hoobs"}
23.2.2021, 08:29:29 [Hue] Philips hue: request 12: api error 101: link button not pressed
23.2.2021, 08:29:29 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
23.2.2021, 08:29:44 [Hue] Philips hue: request 13: POST / {"devicetype":"homebridge-hue#hoobs"}
23.2.2021, 08:29:44 [Hue] Philips hue: request 13: api error 101: link button not pressed
23.2.2021, 08:29:44 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
23.2.2021, 08:29:58 Initializing HAP-NodeJS v0.9.1...
23.2.2021, 08:29:59 [23.2.2021, 08:29:59] The plugin "homebridge-hue" requires Node.js version of ^14.15.5 which does not satisfy the current Node.js version of v14.15.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
23.2.2021, 08:29:59 [Hue] Philips hue: request 14: POST / {"devicetype":"homebridge-hue#hoobs"}
23.2.2021, 08:29:59 [Hue] Philips hue: request 14: api error 101: link button not pressed
23.2.2021, 08:29:59 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
23.2.2021, 08:30:02 Loaded plugin 'homebridge-hue'
23.2.2021, 08:30:02 [23.2.2021, 08:30:02] Registering platform 'homebridge-hue.Hue'
23.2.2021, 08:30:02 Loading 1 platforms...
23.2.2021, 08:30:02 [Hue] Initializing Hue platform...
23.2.2021, 08:30:02 [Hue] config.json: warning: plugin_map: ignoring unknown key
23.2.2021, 08:30:02 [Hue] homebridge-hue v0.12.22, node v14.15.1, homebridge v1.3.0
23.2.2021, 08:30:02 [Hue] warning: not using recommended node version v14.15.5 LTS
23.2.2021, 08:30:02 [Hue] searching bridges and gateways
23.2.2021, 08:30:03 [Hue] xxx.xxx.xxx.xx: request 1: GET /config
23.2.2021, 08:30:03 [Hue] xxx.xxx.xxx.xx: request 1: xxx.xxx.xxx.xx:8080: cannot connect: ECONNREFUSED
23.2.2021, 08:30:07 [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1943082030, api v1.42.0
23.2.2021, 08:30:07 [Hue] Philips hue: request 1: POST / {"devicetype":"homebridge-hue#hoobs"}
23.2.2021, 08:30:07 [Hue] Philips hue: request 1: api error 101: link button not pressed
23.2.2021, 08:30:07 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
23.2.2021, 08:30:14 [Hue] Philips hue: request 15: POST / {"devicetype":"homebridge-hue#hoobs"}
23.2.2021, 08:30:14 [Hue] Philips hue: request 15: api error 101: link button not pressed
23.2.2021, 08:30:14 [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
23.2.2021, 08:30:18 removed 97 packages and audited 3 packages in 6.707s
23.2.2021, 08:30:18 found 0 vulnerabilities
23.2.2021, 08:30:18 Plugin "homebridge-hue" removed.
23.2.2021, 08:30:19 Initializing HAP-NodeJS v0.9.1...
23.2.2021, 08:30:21 No plugins installed.
23.2.2021, 08:30:21 Preparing Advertiser for 'HOOBS 1D00' using bonjour-hap backend!
23.2.2021, 08:30:21 Starting to advertise 'HOOBS 1D00' using bonjour-hap backend!
23.2.2021, 08:30:21 Bridge is running on port 51826.
23.2.2021, 08:30:23 [Hue] Philips hue: request 2: POST / {"devicetype":"homebridge-hue#hoobs"}
```

#### Debug Files

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYDPGL",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "de",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxx-xx-xxxx",
        "username": "xx:xx:xx:xx:xx:xx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}

**Comment by ebaauw** [comment]
I don't know Hoobs, and I see nothing in the log suggesting a crash.  Also, the log suggests you have a Hue bridge instead of a deCONZ gateway.

Please see README: you need to press the link button on the Hue bridge for Homebridge Hue to create an API key (username).  By design, Homebridge Hue will delay the startup of Homebridge, until you've done that.  Make sure to edit config.json, adding the info from the log (as instructed by the README), or you'll end up having to press the link button on each Homebridge restart.

**Comment by toastbrotxy** [comment]
I do face the same issue. Also after pressing the button of hue bridge.  For me it’s that the hue bridge is already registered (I guess w/ Apple HomeKit). If I unplug my hue bridge the Plugin works. Is there any chance to exclude hue bridge? I already skimmed through the wiki and tried to specify the host by entering deconz ip adress.

**Comment by AndiGlaesser** [comment]
> I don't know Hoobs, and I see nothing in the log suggesting a crash. Also, the log suggests you have a Hue bridge instead of a deCONZ gateway.
> 
> Please see README: you need to press the link button on the Hue bridge for Homebridge Hue to create an API key (username). By design, Homebridge Hue will delay the startup of Homebridge, until you've done that. Make sure to edit config.json, adding the info from the log (as instructed by the README), or you'll end up having to press the link button on each Homebridge restart.

I also have a Hue Bridge, but I am only interested in the deCONZ / RaspBee for now. I can't add the user. The plugin does not save the input at all. Could there be a read-write problem in the files? I also tried to update node.js to 14.16.0, but that doesn't work at all. Hoobs doesn't seem to get along with this version.

**Comment by ebaauw** [comment]
> Is there any chance to exclude hue bridge?

Use the `hosts` key in config.json to specify which bridges/gateways Homebridge Hue should expose, bypassing discovery

> The plugin does not save the input at all.

By design, Homebridge Hue does **not** write config.json.  See the README, you need to edit the file manually.

> Hoobs doesn't seem to get along with this version.

I strongly recommend using a standard Homebridge installation.

**Comment by AndiGlaesser** [comment]
> I strongly recommend using a standard Homebridge installation.

I already tried that, but the GUI for the Hue/deCONZ PlugIn is much easier with Hoobs. I couldn't manage to edit the USER with the normal Homebridge installation.

>

> > The plugin does not save the input at all.
> 
> By design, Homebridge Hue does **not** write config.json. See the README, you need to edit the file manually.
> 
> >

I meant that the write permissions on the SD card may not be set correctly.

**Comment by ebaauw** [comment]
> I meant that the write permissions on the SD card may not be set correctly.

That's nothing to do with Homebridge Hue.
