### ISSUE TITLE
Request to add a device

### ISSUE THREAD

**Issue by Kristian8606** [ebaauw/homebridge-hue#935]
Hello!  I received support from deconz for a new door sensor, now it works well in the home app but not in the elgato eve app.  Here is the information about it that I get in the homebridge

![C90A02EC-4D8B-4415-AEA6-995AADB12619](https://user-images.githubusercontent.com/34716572/109063616-0ac86300-76f2-11eb-8d58-9b232c9f5416.jpeg)

**Comment by ebaauw** [comment]
What is not working in Eve?

**Comment by Kristian8606** [comment]
There is no history.

![5550CF43-7730-4C2C-ADD2-3A3D6E32CBA2](https://user-images.githubusercontent.com/34716572/109074918-1707ec80-7701-11eb-8d81-77bc81dba408.jpeg)

**Comment by ebaauw** [comment]
Can you check whether there's a file name `history_00124B0008ED56FA.json` in the `accessories` directory?  If not, please capture and attach a debug log file (from Homebridge start to opening/closing the door a couple of times) and also attach the debug dump file (see README).  If the file is there, try force-quitting and restarting Eve or try Eve on another iDevice.

**Comment by Kristian8606** [comment]
Strange!  The file was there, I deleted it, restarted the raspberry pi and then closed elgato eve completely.  the behavior is the same, the sensor is present in device types but is not displayed in a room.

**Comment by Kristian8606** [comment]
he is not here!

![BC920D5A-9444-4BF7-AB06-585903C977D8](https://user-images.githubusercontent.com/34716572/109210467-8808dc00-77b5-11eb-98d3-cddd5223f020.png)

but here it is present

![C8DD13F3-B11C-4769-8E97-517099BA091A](https://user-images.githubusercontent.com/34716572/109210574-aff83f80-77b5-11eb-8b45-55c2b3544755.png)

**Comment by Kristian8606** [comment]
Here is the log file
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6045580/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
I see nothing wrong in the debug files.  Homebridge Hue should have re-created the history file.

I have never seen a sensor disappear from the _Rooms_ view but still visible in the _Types_ view.  Does it show in another room (maybe the room where the Homebridge accessory resides)?  Does it show in the Home app?  Could you check Eve on another iDevice?

Have you exposed the sensor before, maybe from a test installation of HomeKit?  Eve stores the history under the device serial number, differently from how HomeKit stores the accessory, under the bridge and accessory UUID.  Sometimes Eve gets confused if the same device is exposed by different Homebridge instances.  The remedy is to delete the history from Eve (but that's only possible if it shows at least some), or to uninstall and re-install Eve (which will clear all history from the iDevice).

**Comment by Kristian8606** [comment]
I just uninstalled and installed eve but that didn't help either.
missing even in (At a Glance)

**Comment by Kristian8606** [comment]
> Does it show in another room (maybe the room where the Homebridge accessory resides)?

No 


> Does it show in the Home app?

Yes


> Could you check Eve on another iDevice?

No I can not


> Have you exposed the sensor before, maybe from a test installation of HomeKit?

No

**Comment by Kristian8606** [comment]
I noticed  this, maybe something confuses eve?


![89DA2AC1-7A3B-4EF3-A042-20E0139347B1](https://user-images.githubusercontent.com/34716572/109219801-c657c880-77c0-11eb-9e5d-a610913417dd.jpeg)

**Comment by ebaauw** [comment]
This suggests the sensor is in the Living Room.  Under what room is it shown in the Home app?

Eve thinks the accessory is an Eve Window Guard with Tilt Detection function.  I haven't seen that before, and this is a different accessory from the original Eve Door & Window.  I think the Gamabit is the first ZHAOpenClose sensor I've seen that exposes `state.tampered`.  Homebridge Hue exposes this as _Status Tampered_.  Maybe that triggers Eve to think it's a Window Guard.  In that case, probably some other characteristic is missing, or maybe it uses a different history configuration, causing Eve not to show the history.  That would be unrelated to the room thing, though.

**Comment by Kristian8606** [comment]
can you fix this so that it works and displays history as a door sensor?

**Comment by Kristian8606** [comment]
> This suggests the sensor is in the Living Room. Under what room is it shown in the Home app?
> 
Living room

**Comment by MAPEZ1** [comment]
Hi also here,
as I'm also got my first Sonoff Door/Window (SNZB-04) and saw this conversation, I took also a look in HomeKit and EveApp.
The sensor does not show up in a EveApp Room either - only under Types as Contact. There it shows that is in my Top Level Room. But there it's not visible in EveApp - but in HomeKit.
Also no history in EveApp.
When HB start and Homebridge-Hue is loading it throwes:
```
[Zigbee] Phoscon-GW: /sensors/2: warning: unknown ZHAOpenClose sensor {"config":{"battery":100,"enrolled":1,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"34bd15f00ecad3aa33a9bcc2eaa53ca1","lastseen":"2021-02-25T20:48Z","manufacturername":"eWeLink","modelid":"DS01","name":"Window / Door Sensor","state":{"lastupdated":"2021-02-25T17:32:00.520","lowbattery":false,"open":false,"tampered":false},"swversion":"20201026","type":"ZHAOpenClose","uniqueid":"00:12:4b:00:22:67:2f:a3-01-0500"}
[2/25/2021, 10:31:20 PM] [Zigbee] Phoscon-GW: 3 accessories
[2/25/2021, 10:31:20 PM] [Zigbee] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
[2/25/2021, 10:31:20 PM] Initializing platform accessory 'Phoscon-GW'...
[2/25/2021, 10:31:20 PM] [Zigbee] Phoscon-GW: 2 services
[2/25/2021, 10:31:20 PM] Initializing platform accessory 'Window / Door Sensor'...
[2/25/2021, 10:31:20 PM] Initializing platform accessory 'Thermostat'...
```
pls let me know if I can help any further
cheers

**Comment by ebaauw** [comment]
Could you try beta v0.12.24-0?  I have no device to test this myself, but this version should ignore `state.tampered` when Eve Door & Window history is used.  Could you please test both opening/closing the sensor as well as triggering the tampered state?  Please capture and attach a debug log file, so I can check whether Homebridge Hue is actually doing what it should be doing.

**Comment by MAPEZ1** [comment]
Installed beta
In HomeKit, Tampered is gone in the sensor Status list
and it shows up in the EveApp Room with history also from past :-)

[homebridge-hue.json(1).gz](https://github.com/ebaauw/homebridge-hue/files/6049056/homebridge-hue.json.1.gz)

**Comment by ebaauw** [comment]
> No idea how to trigger the 'tampered' state

Usually there's a small button on the device that is pressed when it's seated in its holder, and released when the device is removed from its holder.  If not, deCONZ shouldn't expose `state.tempered`.

Please capture and attach a debug _log_ file.  The dump just logs the configuration from deCONZ, which doesn't change when exposing a device differently by Homebridge Hue.

**Comment by MAPEZ1** [comment]
OK...the sensor is not equipped with anything that could modify the tampered state.
It just provides the state, but not function on the senor to identify tampered....

Debug log...I need to check how to, as I have never done before.

**Comment by Kristian8606** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/6051549/homebridge.log.gz)

**Comment by MAPEZ1** [comment]
@Kristian8606 can you let me know how you create the debug log and where then the file can be found
Would shorten my learning curve and search :-)

**Comment by Kristian8606** [comment]
/var/lib/homebridge/ 
this is my path to homebridge.log

**Comment by MAPEZ1** [comment]
hmmm....nope..don't have that path
Hope the above homebridge.log is OK for debuging...
Otherwise pls let me know
cheers

**Comment by ebaauw** [comment]
> how you create the debug log and where then the file can be found

Wrote a FAQ entry for that.

> I confirm that the story is now displayed in the eve application.

Cool.  Did you check that other contact sensor are still working?

**Comment by Kristian8606** [comment]
I have an aqara and a xiaomi door sensors, they still work without a problem.

**Comment by ebaauw** [comment]
Cool.  I'll include the fix in the next release.

**Comment by jsiegenthaler** [comment]
@ebaauw 
Typo in your Release Notes

v0.12.24
Enhancements
Don't expose **StatusTempered** on accessories with Eve history for Eve Door & Window, see #935.

I think you mean StatusTampered

Tempered and Tampered are both English words, but with very different meanings....

**Comment by Kristian8606** [comment]
Hello, after the last beta of Deconz the other two sensors (GMB-HAS-VB-B01, ZHAVibration) vibration sensor and (GMB-HAS-WL-B01, ZHAWater) leak sensor were added.
The leak sensor is displayed in the elgato eve app and works normally but has no history.
Actually, I'm not sure if the leak sensors support history?
The vibration sensor also works and maintains history but is recognized as a motion sensor, which is incorrect.
They also exhibit `tampered` but do not physically support it.
Is it possible to adjust the vibration sensor to be exposed as such and not as a motion sensor?

**Comment by ebaauw** [comment]
I don’t think the Eve Water Guard has history, but if it has, they haven’t reversed engineered it.  So no history for leak sensors.

Homebridge Hue exposes ZHAVibration `/sensors` resources as _Motion Sensor_, incl. history.  Not sure what else to expose them as, but I’m open to suggestions.

If the sensor doesn’t support tampered, deCONZ shouldn’t expose `state.tampered`.

**Comment by Kristian8606** [comment]
Yes I just realized that homekit has no characteristic for vibration sensor.
