### ISSUE TITLE
Set HomeKit transition

### ISSUE THREAD

**Issue by Perilax-De** [ebaauw/homebridge-hue#939]
When I restart my Homebridge I get these log entries:

[28.2.2021, 08:44:28] [Hue] innr Lightstrip: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}
[28.2.2021, 08:44:28] [Hue] innr Lightstrip: set homekit transition control to ""
[28.2.2021, 08:44:29] [Hue] innr Lightstrip: set homekit transition control to ""

And then from time to time (15-60 minutes) I get this log entry again and again:

[Hue] innr Lightstrip: set homekit transition control to ""

The lightstrip is not connected because I only use it sometimes. 

Here my config:

 {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "192.168.178.62:80"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "noResponse": false,
            "resource": true,
            "users": {
                "xxxxxxx": "Xxx"
            },
            "platform": "Hue"
        },

ConBee II 2.09.03
HUE Plugin 0.12.23
Homebridge 1.3.1
Node.js 14.16.0

Is this normal ? Or can I do something against this log entries ?

**Comment by ebaauw** [comment]
See #938.
