### ISSUE TITLE
Hue and Conbee stick or Gateway in parallel

### ISSUE THREAD

**Issue by ChalesGiron** [ebaauw/homebridge-hue#940]
Hi, 

I unfortunately almost reached the 63 items in Hue and now want to use the conbee stick in parallel. Is there an option to integrate both via homebridge-hue? Is there a config example I missed? Thanks for your kind help! And: Thanks for the great plugin!!!I ;o))

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Homebridge Hue supports multiple bridges and/or gateways in parallel, up to the hard limit of 149 accessories per HomeKit bridge.  If you use discovery, there’s nothing to configure, except, of course, you need to specify the bridgeid/username for both bridges/gateways.
