### ISSUE TITLE
All lights disappear in HomeKit 

### ISSUE THREAD

**Issue by McDin** [ebaauw/homebridge-hue#942]
Hi,

I use Conbee II and in Phoscon every light is available but sometimes all lights disappear in HomeKit. So all Scenes are gone. When Hoobs is restarted the lights are back but I think as new lights because there aren't matched to scenes and rooms any more. Is there some fix for this?

Thanks and regards
Marc

**Comment by ebaauw** [comment]
What version of deCONZ are you running?  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2473.

**Comment by McDin** [comment]
Version 2.07.01. I had the problem with starting the bridge and the lights are not available, too and solved it with a delayed start of home bridge. But they also disappear sometimes by their own.

**Comment by ebaauw** [comment]
A delayed start is a lousy workaround, as you don't know how long it takes deCONZ to expose the `/lights` resources.  A better workaround would be using a `lightlist` resourcelink, as mentioned in the issue.  Even better would be updating deCONZ, as the bug has been solved in v2.9.

Technically it's impossible for lights to disappear on their own.  This can only happen when Homebridge restarts and Homebridge Hue cannot find the `/lights` resources on startup.

**Comment by McDin** [comment]
Okay, thank you very much. I will update to last beta of deCONZ.

**Comment by ebaauw** [comment]
Or to stable v2.9.3.
