### ISSUE TITLE
GLEDOPTO not work anymore on this plan-in?

### ISSUE THREAD

**Issue by Nude2life** [ebaauw/homebridge-hue#943]
HI, my GLEDOPTO bulbs and strip controller all seem not working anymore on this, can see in the home app but cannot control, all not ON/OFF or change color!!! What shall I do?
#### Log Messages

```
```

**Comment by ebaauw** [comment]
Please attach the debug dump file and capture and attach a debug log file.  See FAQ on how to do that.
