### ISSUE TITLE
EnergyCost Option under EVE not available

### ISSUE THREAD

**Issue by mhin76** [ebaauw/homebridge-hue#944]
Hi Erik

I have connected a Xiaomi Smart Plug (Zigbee version) to my infrastructure. This plug monitors the power consumption and shows at the same time also the energy cost. All works fine, just one thing is missing. Based on EveHome webpage the cost per kWh should be configurable under Setting -> General (https://www.evehome.com/en/blog/all-features-eve-energy). But I don't see the option "Energy Cost" listed there.
Is it possible that this only works if Eve App identifies a power monitoring plug from their company?
I guess currently it takes a default cost of 0.23 per kWh.

Kind regards, Martin

**Comment by ebaauw** [comment]
I wouldn't know.  I recently set a new test environment with a new home on another iCloud account, and indeed, Eve doesn't show the _Enegery Cost_.  I do have some first-generation Eve Energy plugs hidden away in a cupboard, that I used previously with my production home.

The _Total Cost_ and _Projected Cost_ are pretty useless anyways: they don't account for multi-tiered rates, nor for any fixed monthly costs.   I have different rates for (work) day vs night (incl. weekends and public holidays).  Of course neither the Eve Energy (nor any Zigbee plug) nor the Eve app would know what rate is active at what time, but my smart electricity meter reports this though Homebridge P1.

Eve seems to somehow retrieve the average rate per country.  I don't know where they get it from, nor how often this is updated (my iPad shows "Last updated: 3 March 2021" instead.
![IMG_0252](https://user-images.githubusercontent.com/22179355/110097621-8a63cb00-7d9f-11eb-8596-c2491ab649a3.PNG)

**Comment by ebaauw** [comment]
I added Homebridge Hue to the test home and now Eve does show the _Energy Cost_.  Homebridge Hue exposes some innr SP120 and some Heiman plugs.  Both these plus types expose _Total Consumption_, _Consumption_, _Current_, and _Voltage_.  What does the Xiaomi plug expose?  Do you see Eve history on the _Total Consumption_?  I think _Total Cost_ is linked to _Total Consumption_ and _Projected Cost_ to _Consumption_

**Comment by mhin76** [comment]
Hi Erik. Thank you for your fast reply!
Yes true, we also have different rates here in Switzerland depending on the time of the day or if its weekend or not. I see in your eve application that Energy Cost setting is available. I checked on my ipad but it does look differently. No Energy Cost option available. Strange. I am using version 5.0.2.
The Eve history shows all nicely, total consumption, consumption, current, ... Just wanted to adjust the cost pero kWh but as you wrote, only makes limited sense. 

here the printscreens, sorry all in German
![image](https://user-images.githubusercontent.com/49210075/110103286-0cef8900-7da6-11eb-8a62-64504581f7fd.png)
![image](https://user-images.githubusercontent.com/49210075/110103326-1d9fff00-7da6-11eb-9222-42df687eb01f.png)

**Comment by ebaauw** [comment]
I read German, no problem.  It looks like you don't expose the `/lights` resource (to switch the plug on and off)?  That's probably required for Eve to recognise the plug as "Eve Energy".

I cannot see from the screen print whether the sensor also exposes (current) _Consumption_ (in W).  deCONZ should either expose a ZHAConsumption `/sensors` resource with additional `state.power`, or a separate ZHAPower `/sensors` resource.  I don't know the Xiaomi plug, but knowing Xiaomi (to the extent that's possible), they probably use different clusters for `state.consumption` and `state.power`.

**Comment by mhin76** [comment]
ah, that's it! Yes, it does show as different cluster. Power and Consumption are on one, but the corresponding plug (light) is detached and only shows (when navigating to detail) the power button.
![image](https://user-images.githubusercontent.com/49210075/110105663-f696fc80-7da8-11eb-8055-cc8d9b699045.png)

**Comment by ebaauw** [comment]
OK, there's something odd in your configuration.  deCONZ exposes the plug as three different resources.  Homebridge Hue should combine them into one accessory with one service, but it looks like there's three different services.  Could you attach the debug dump file and capture and attach a debug log file?  See the FAQ how to do that.

**Comment by mhin76** [comment]
that is odd. in deCONZ I see all three functionality listed below each other.
![image](https://user-images.githubusercontent.com/49210075/110111931-5beeeb80-7db1-11eb-9855-93341ae1d898.png)
In the log file I see that under ID 00158D0002FB3C54 the consumption and power sensors are listed, however the switches are not listed at all and I have installed 5 switches (from IKEA and Xiaomi). Am I using wrong setting of your plugin? 
[homebridge.log.txt](https://github.com/ebaauw/homebridge-hue/files/6090376/homebridge.log.txt)

**Comment by ebaauw** [comment]
You're not exposing `/lights` resources through Homebridge Hue.  The wireless switches are exposed, according to your log.  I don't know where you got the other services in _Garten_, but not from Homebridge Hue.

**Comment by mhin76** [comment]
ah, understood! very likely the lights get in via the "Homebridge Platform Deconz" plugin that I had installed first. I will test it out.

**Comment by mhin76** [comment]
I am going to close this issue. It seems to be on my Eve app somehow. Last entry in this forum: https://forum.smartapfel.de/forum/thread/4118-eve-f%C3%BCr-homekit-eintrag-f%C3%BCr-energiekosten-messung-nicht-vorhanden/ has the same issue. and they are not using your plugin. So nothing wrong with your plugin. When I have a solution I can still add it to this thread.
Thanks again for your help Erik! At least now the devices are listed a lot nicer :)
