### ISSUE TITLE
Can’t rename any devices from hue/homebridge

### ISSUE THREAD

**Issue by d3bing** [ebaauw/homebridge-hue#947]
Very weird thing happening since I updated homebridge and hue to latest version. I can’t rename my accessories. I change the name in Home app, but after a few seconds it falls back to previous name. It happens with any hue light and aqara Zigbee accessory (anything coming from my RPI/Debian/DeConz/Hue/Homebridge combo. Other HomeKit accessories have no issue.

What’s even more weird - in the Home app, if I go into “Bridges”, tap homebridge and then “accessories”, it shows a list of accessories from the bridge. THERE the name sticks to the change, but once you open the accessory it only shows the old one. Screenshots attached.
![IMG_3437](https://user-images.githubusercontent.com/23664257/110507507-efc3fe80-80b4-11eb-950c-af978b281b74.jpeg)
![IMG_3438](https://user-images.githubusercontent.com/23664257/110507512-f0f52b80-80b4-11eb-85fb-c0e96d765a11.jpeg)
![IMG_3439](https://user-images.githubusercontent.com/23664257/110507514-f0f52b80-80b4-11eb-81c8-dbd8a72832f9.jpeg)
![IMG_3440](https://user-images.githubusercontent.com/23664257/110507518-f18dc200-80b4-11eb-9a3f-6b8d7bb0003c.jpeg)
![IMG_3441](https://user-images.githubusercontent.com/23664257/110507521-f2265880-80b4-11eb-8791-21594a3c6390.jpeg)

#### Log Messages
Nothing appears in the homebridge log.

#### Debug Files
[homebridge-hue.gz](https://github.com/ebaauw/homebridge-hue/files/6110151/homebridge-hue.gz)

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/issues/910.

**Comment by d3bing** [comment]
bingo! ConfiguredName worked. I did try to search for issues but didn't find, sorry for that. Thanks for the help!
