### ISSUE TITLE
Linkind Button Wireless Switch Support

### ISSUE THREAD

**Issue by SirGc** [ebaauw/homebridge-hue#949]
#### Issue
The button is not supported.
There is one button. Similar to the Aqara wireless switch. According to the Amazon listing (https://www.amazon.com/gp/product/B07V5VLRNL), it supports a one tap event and a tap and hold event.

#### Log Messages
**Homebridge Log Event:**
>Phoscon: /sensors/7: warning: ignoring unknown ZHASwitch sensor {"config":{"battery":82,"group":"16394","on":true,"reachable":true},"ep":1,"etag":"93a83746da23e90f65f9b2b6b3729462","lastseen":"2021-03-10T22:45Z","manufacturername":"lk","mode":1,"modelid":"ZBT-DIMSwitch-D0001","name":"Switch","state":{"buttonevent":1002,"lastupdated":"2021-03-10T22:45:51.996"},"swversion":"2.22","type":"ZHASwitch","uniqueid":"08:6b:d7:ff:fe:fc:a4:39-01-1000"}

**DeConz INFO Log Event:**
This is for one tap
>[INFO] - Button 2002 - ZBT-DIMSwitch-D0001, broadcast to: 0x400A, endpoint: 0x01, cluster: ONOFF (0x0006), action: Off, payload: None, zclSeq: 77

This is for the next one tap
>[INFO] - Button 1002 - ZBT-DIMSwitch-D0001, broadcast to: 0x400A, endpoint: 0x01, cluster: ONOFF (0x0006), action: On, payload: None, zclSeq: 98

This is a tap and hold

> 17:15:07:802 [INFO] - Button 1001 - ZBT-DIMSwitch-D0001, broadcast to: 0x400A, endpoint: 0x01, cluster: LEVEL_CONTROL (0x0008), action: Move up, payload: 007F0000, zclSeq: 114
>17:15:07:948 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
>17:15:08:948 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
>17:15:09:948 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
>17:15:10:623 [INFO] - Button 1003 - ZBT-DIMSwitch-D0001, broadcast to: 0x400A, endpoint: 0x01, cluster: LEVEL_CONTROL (0x0008), action: Stop, payload: 0000, zclSeq: 115
#### Debug Files
Homebridge Log file: https://d.pr/f/bk7YB8

**Comment by ebaauw** [comment]
I don't understand: this is a one-button device, but deCONZ exposes two buttons?

**Comment by SirGc** [comment]
Yes there’s only one physical button. That looked like the relevant lines from the log. Is there a better way I could give you more info about the device? 
I looked at that other linked issue. It sounds like the same button. I’m new to working in DeConz, but I’m willing to learn and help getting any info you need.

**Comment by ebaauw** [comment]
Support in v0.13.1, but only for the first button.  I think the _Off_ and _Move Down_ commands should be mapped to 100x as well, but this needs to be fixed in deCONZ.

**Comment by SirGc** [comment]
Ya. This worked great. Are you able to map deCONZ button 1002 and 2002 to the same Homekit single press button? The Long press works perfect how you have that configured.

**Comment by ebaauw** [comment]
Actually, I can (with considerably less effort than I feared).  Not too happy about this, though - it really should be fixed in deCONZ.

**Comment by ebaauw** [comment]
In v0.13.3.

**Comment by SirGc** [comment]
I created an issue with deCONZ: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4598
