### ISSUE TITLE
Homebridge/HUE plugin doesnt find my Bridge Anymore

### ISSUE THREAD

**Issue by malikramires** [ebaauw/homebridge-hue#950]
Hello @ebaauw 
unfortanetly since today i get the following Error Codes in the log

[3/14/2021, 5:08:54 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[3/14/2021, 5:09:10 PM] [Hue] http://192.***.***.216: not found - retrying in 30s
[3/14/2021, 5:09:14 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.

I didnt change anything.Everything worked fine until today.Maybe you have any ideas ?

**Comment by ebaauw** [comment]
Please update to v0.13.1.

Homebridge Hue v0.13.0 tries to connect to the masked host, instead of the true IP address.  I had fixed this in the v1 branche, but didn't realise the issue appears in the master branche as well.

**Comment by malikramires** [comment]
@ebaauw 
i already updated to v0.13.1.

**Comment by miquellaboria** [comment]
I have same problem with v.0.13.1.

**Comment by bigrichwood** [comment]
0.13.1 fixed it for me.

**Comment by ebaauw** [comment]
@malikramires @miquellaboria do you get the same error message as above?  Or the same as in #951?  Or yet another one?

**Comment by malikramires** [comment]
@ebaauw No,just the Errors as mentioned.

Switching back to older Version homebridge-hue v0.12.20 works for now.

**Comment by ebaauw** [comment]
The "not found" message?

**Comment by malikramires** [comment]
Yes exactly

**Comment by ebaauw** [comment]
Could you please capture a full debug log file (see FAQ) and attach that?

**Comment by ebaauw** [comment]
Damn, fix introduced a new bug.  Could you try beta v0.12.2-0? Install through Install Previous Version in the UI or through sudo npm -g i homebridge-hue@beta.

**Comment by malikramires** [comment]
@ebaauw  Beta works good for me !

**Comment by ebaauw** [comment]
Published v0.13.2.

**Comment by miquellaboria** [comment]
V.0.13.2 fix to me also!

thank you @ebaauw !!
