### ISSUE TITLE
config.json: parallelRequests: invalid key

### ISSUE THREAD

**Issue by Marfre888** [ebaauw/homebridge-hue#953]
You are probably already aware of this, but as of 0.13.2, I am getting a warning from Homebridge `config.json: parallelRequests: invalid key`

As I understand from your release notes, you haven't yet migrated to dynamic platform, so this key should still be valid

**Comment by ebaauw** [comment]
My bad, made a typo in the code; it’s looking for `parallelrequests`.

The key has nothing to do with static vs dynamic accessories platform plugin.

**Comment by Marfre888** [comment]
Ahh, I assumed since you're adding dynamic accessories, parallelRequests might not be necessary anymore.

Thank you for continuing to maintain this plugin

**Comment by ebaauw** [comment]
In v0.13.3.
