### ISSUE TITLE
Hue warns not using recommended Hue bridge api version 1.42.0 but current version is higher: 1.43.0

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-hue#954]
#### Issue

homebridge-hue v0.13.2 warns not using recommended Hue bridge api version 1.42.0 but current Hue bridge api version is higher: 1.43.0

The log warning causes uncertainty in the user
Suggestion: suppress the warning if the Hue bridge api minor version is >= the version recommended by Homebridge Hue?
Or otherwise: bump the dependencies at each release of a new Hue bridge api version. 

#### Log Messages

```
[15/03/2021, 07:17:35] [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
[15/03/2021, 07:17:35] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.42.0
```

**Comment by ebaauw** [comment]
Looks like Signify silently pushed a new undocumented Hue bridge firmware version last week.  See https://github.com/ebaauw/homebridge-hue/issues/951#issuecomment-798970816.

**Comment by jsiegenthaler** [comment]
Thanks. I have a feeling that a few bridge updates might happen in the near future due to the new Hue products appearing on the market at the moment.... or soon...

**Comment by lugaetsch** [comment]
> Thanks. I have a feeling that a few bridge updates might happen in the near future due to the new Hue products appearing on the market at the moment.... or soon...

change the package.json as @ebaauw mentioned before. Restart underlying platform after and the alert should be gone.

**Comment by ebaauw** [comment]
In v0.13.3.
