### ISSUE TITLE
Plugin Generated a warning from the characteristic 'Last Activation'

### ISSUE THREAD

**Issue by Marfre888** [ebaauw/homebridge-hue#957]
#### Issue
I have 5 Aqara Door and Window Sensors connected through Deconz. I have a weird problem where 3 of the door sensors generate the below error, and the other two do not. This issue happens when I open/close the door. I've had a look in the rest api, and they are all identical and not missing any attributes. The 'lastupdated' attribute also seems to be updating once the sensor has been triggered. I haven't tried removing the offending devices from Deconz and re-adding them, mostly in the interest of testing the issue. All these devices were added before the HB 1.3.0 beta, and to my knowledge, the issue didn't present itself during HB 1.3.0.

#### Log Messages

```
[3/17/2021 14:33:03] [Hue] Bedroom Door: set homekit contact from 0 to 1
[3/17/2021 14:33:03] [homebridge-hue] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
```

#### Debug Files

Let me know if you need me to generate these logs in a specific way

**Comment by ebaauw** [comment]
Saw that before on Discord, on 2021/03/06.  To quote my answer there:
> This is the _Last Motion_ characteristic that Eve uses in conjunction with the history.  It should be set to the delta between now and the initial time as reported by `fakegato-history`.  I suppose fakegato's `getInitialTime()` returns something odd, so the delta yields NaN.
Do you this is for only a single sensor, or for multiple sensors?  If only a single sensor, best note the serial number (Zigbee Mac Address) of the sensor, stop Homebridge, delete the history file (`history_`_MacAddress_`.json`),  and restart Homebridge.

In that instance, it was a single accessory, and deleting the history file did solve the issue.

In your case, it's the _Last Opened_ characteristic (Eve uses the same characteristic, but a different name between motion and contact sensors).  The history files are preserved when you un-expose and re-expose the devices.  I'm not sure which Homebridge version the message was enabled, but the underlying issue has probably been there "forever".  The _Last Activation_ characteristic is Eve-specific: Home doesn't look at it and Eve doesn't seem to mind, so no harm done.

**Comment by Marfre888** [comment]
> Saw that before on Discord, on 2021/03/06. To quote my answer there:
> 
> > This is the _Last Motion_ characteristic that Eve uses in conjunction with the history.  It should be set to the delta between now and the initial time as reported by `fakegato-history`.  I suppose fakegato's `getInitialTime()` returns something odd, so the delta yields NaN.
> > Do you this is for only a single sensor, or for multiple sensors?  If only a single sensor, best note the serial number (Zigbee Mac Address) of the sensor, stop Homebridge, delete the history file (`history_`_MacAddress_`.json`),  and restart Homebridge.
> 
> In that instance, it was a single accessory, and deleting the history file did solve the issue.
> 
> In your case, it's the _Last Opened_ characteristic (Eve uses the same characteristic, but a different name between motion and contact sensors). The history files are preserved when you un-expose and re-expose the devices. I'm not sure which Homebridge version the message was enabled, but the underlying issue has probably been there "forever". The _Last Activation_ characteristic is Eve-specific: Home doesn't look at it and Eve doesn't seem to mind, so no harm done.

Ok, so deleting the 'history_MacAddress.json' seems to have fixed the issue. What I observed is that the history files of the sensors which were producing this error in the log were empty (with only a single space inputted). Deleting the file caused homebridge-hue to recreate it with the proper data.

So far so good.

Thanks for you help.

**Comment by ebaauw** [comment]
Unfortunately, I have no clue how the files get to be empty.  The logic is handled by the `fakagato-history` library.  I will move to my own implementation with the refactor to dynamic platform accessories (which I already use for my other plugins) and have some more control on what's happening here.
