### ISSUE TITLE
Home app showing hue bridge and phoscon gateway now as non removable favorites

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-hue#960]
Apple”s home app shows the phoscon gateway and the hue bridge icon now in favorites without a toggle switch 
to remove them. Even when adding homebridge hue with a different app all devices are automatically added to favorites. I recognized this after I had to setup my home from the ground up.

![D22E7539-52EB-482B-B7D3-5B3437BA8E7C](https://user-images.githubusercontent.com/29116509/111832559-3dc8d580-88f1-11eb-8b2d-b9d8e6aa3395.jpeg)

**Comment by ebaauw** [comment]
See FAQ.
