### ISSUE TITLE
deCONZ groups always exposed with colortemperature and saturation

### ISSUE THREAD

**Issue by jeankone** [ebaauw/homebridge-hue#961]
#### Issue
I have a Chandelier with 3x Philips Hue LWV001 lights, capable of only dimming. Exposed as 3 single lights Homekit will recognize them appropriately as dimmable lights.
To have them appear in HomeKit as a single accessory, i'm making use of the `resourcelinks` `whitelist` and `blacklist` feature, as described in the wiki. Therefore im blacklisting all three `lights`, create a group in Phoscon and whitelist that.
Now it appears that a group consisting of only dimmable lights, inevitably will expose with values for color temperature and saturation and therefore have a color picker in HomeKit or Eve, which shows a blue color as default.

Is there any way to expose a "dimmable-only-lights" group as exactly that?

Thx and best regards
Jan

#### group:
```
{
  "action": {
    "alert": "none",
    "bri": 127,
    "colormode": "ct",
    "ct": 260,
    "effect": "none",
    "hue": 0,
    "on": false,
    "sat": 127,
    "scene": null,
    "xy": [
      0,
      0
    ]
  },
  "devicemembership": [],
  "etag": "e886871a69d4ebb4e3b8597a2b18da9b",
  "id": "18",
  "lights": [
    "23",
    "24"
  ],
  "name": "Zufahrt Hofbeleuchtung",
  "scenes": [],
  "state": {
    "all_on": false,
    "any_on": false
  },
  "type": "LightGroup"
}
```

**Comment by ebaauw** [comment]
This is a long present bug in the deCONZ REST API and needs to be fixed there.  See e.g. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4067.
