### ISSUE TITLE
Return non-hue lights to previous state after power failure

### ISSUE THREAD

**Issue by zsolt-dev** [ebaauw/homebridge-hue#962]
Hi Erik,

First let me thank you for developing and maintaining homebridge-hue. Really great work!

I was thinking about a feature that would return non hue lights to their previous state after power failure.

I understand it would take couple of seconds to switch the lights to their previous state, so it will not be as nice as the original hue lights experience. Since the homebridge itself would reboot, it would probably take longer than a minute to return lights to the previous state.

But I still there is still a use case for this. Is this something that you have considered implementing?

Thank you

**Comment by ebaauw** [comment]
I have, but not in Homebridge Hue.  I've created a group containing all lights that don't support the poweron on/off setting.  You can turn this group off by including `ph put /groups/`_xx_`/action '{"on": false}'` somewhere in your startup script.  I actually run my Raspberry Pi on an el-cheapo UPS (see https://github.com/ebaauw/homebridge-rpi/wiki/Raspberry-Pi-UPS) and call this from the power restored script.

**Comment by zsolt-dev** [comment]
Thank you!

Really cool solution.
