### ISSUE TITLE
Phoscon-GW stop working after upgraded Hue plugin to V0.13.5 

### ISSUE THREAD

**Issue by freemanuk** [ebaauw/homebridge-hue#964]
I am not sure what had happened, after upgraded the Hue plugin to V0.13.5, my Conbee II stop working.
Below is the error from the log.  

06/04/2021, 15:25:18 [Hue] Phoscon-GW: websocket connection to ws://192.168.50.3:8088 closed - retrying in 15s
06/04/2021, 15:25:23 [Hue] Phoscon-GW: request 99: GET /sensors
06/04/2021, 15:25:23 [Hue] Phoscon-GW: request 99: 192.168.50.3:8080: cannot connect: ECONNREFUSED

**Comment by ebaauw** [comment]
ECONNREFUSED means that Homebridge Hue can reach the server running deCONZ, but nobody is listening to the port.  Most likely because deCONZ is down or using a different port.  Could also be that a firewall is blocking the traffic.
