### ISSUE TITLE
Hue lights no longer exposed to HomeKit upon update.

### ISSUE THREAD

**Issue by tigerquoll** [ebaauw/homebridge-hue#967]
#### Issue
After updating to most recent version of the  plugin (sorry don't know what version I was on previously), native hue lights are no longer exported to homekit.  Other non-hue lights are still exported.
Using the square hue hub,  The hub is not joined up to HomeKit.
Plugin conf: "Native home kit lights" set to "no"

#### Log Messages
 [Hue] Philips hue: error: /lights/27: {"state":{"on":true,"bri":254,"hue":14988,"sat":141,"effect":"none","xy":[0.4575,0.4101],"ct":366,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":false},"swupdate":{"state":"noupdates","lastinstall":"2021-03-04T10:18:35"},"type":"Extended color light","name":"Dining 3","modelid":"LCT007","manufacturername":"Signify Netherlands B.V.","productname":"Hue color lamp","capabilities":{"certified":true,"control":{"mindimlevel":2000,"maxlumen":800,"colorgamuttype":"B","colorgamut":[[0.675,0.322],[0.409,0.518],[0.167,0.04]],"ct":{"min":153,"max":500}},"streaming":{"renderer":true,"proxy":true}},"config":{"archetype":"sultanbulb","function":"mixed","direction":"omnidirectional","startup":{"mode":"safety","configured":true}},"uniqueid":"00:17:88:01:02:44:9a:37-0b","swversion":"5.130.1.30000"}
TypeError: Cannot read property 'updateValue' of undefined

(one of these messages for each hue light no longer available).

**Comment by ebaauw** [comment]
Are you running the recommended Homebridge version?

**Comment by tigerquoll** [comment]
Hello @ebaauw,  Apologies, your reply email got junked.  I was a minor version behind on hoobs.  Updating hoobs seems to have fixed the issue.  Thanks for all your work on homebridge hue.  It's awesome!.
