### ISSUE TITLE
Cannot delete resourcelink after deletting light

### ISSUE THREAD

**Issue by honzakeller** [ebaauw/homebridge-hue#968]
Hello, I end up in the situation when Homebridge cannot start because of the resourcelink is not available.

What I did:
I deleted Tradfri socket from the Phoscon app. Then made some unrelated changes that required restart Homebridge. 
After that Homebrodge cannot start:
_[Hue] Phoscon-GW: /resourcelinks/1: /lights/4: not available
[Hue] Phoscon-GW: gateway not yet initialised - wait 1 minute_

But now I cannot delete resourcelink or run ph lightlist -v because all i get is:
_ph: error: get /config: http status 404 Not Found
ph: fatal: localhost: not a Hue bridge nor deCONZ gateway_

What else can be done to delete the resources to make Phoscon gateway initialise?

**Comment by ebaauw** [comment]
You need to specify what host `ph` should connect to (unless you're running deCONZ on `localhost:80`).  See `ph -h`.

**Comment by honzakeller** [comment]
So finally I manage to do that by _ph -H 127.0.0.1:8080 delete /resourcelinks/1_. I feel so dumb. Sorry for your time. Maybe someone find it helpful in the future.
