### ISSUE TITLE
WallSwitch set to false but still exposed to Home and working

### ISSUE THREAD

**Issue by ng-4r** [ebaauw/homebridge-hue#970]
First of all, thank you for the work done with this plugin! :)

I’m facing an issue with the Hue WallSwitch accessory. I tried to add it through homebridge but I noticed there was too much delay, so I decided to set the key “WallSwitch” to false, but it is still exposed to HomeKit, and it is also working normally. Obviously, I restarted homebridge service after editing the configuration, and also rebooted the system, but the switch is still there.
Any advice on how to remove it? Hope not to remove the plugin and start from scratch!

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Configuration for the meaning of `wallSwitch`.

To prevent a single resource from being exposed, use a `blacklist` resource link, see https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links.

**Comment by ng-4r** [comment]
Sorry for the misunderstanding! I found the “WallSwitch “ line already in the default configuration and I thought it was referring to smart switches...

Anyway, I read the page about blacklisting, but do I have to create a blacklist using the ph command line, not by adding it to the configuration?

What is the syntax to do it? I want to exclude a Philips dimmer switch

**Comment by ebaauw** [comment]
See the example in the Wiki.
