### ISSUE TITLE
Question: Philips Hue Tab is showing 6 buttons?

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#972]
Hi @ebaauw 

I have a question about Philips Hue Tab switches.

I don´t understand why I can see "6 buttons" to configure in Apple Home.

The switches himself are having 4 buttons.

Any ideas?

Thanks!

![Unknown](https://user-images.githubusercontent.com/14274103/115181416-31928c80-a0d8-11eb-94e3-f4478ceb3ba7.jpeg)

![IMG_4841](https://user-images.githubusercontent.com/14274103/115181489-5b4bb380-a0d8-11eb-8550-f23009ce0984.PNG)

**Comment by ebaauw** [comment]
Button 5 is for pressing 1 and 2 simultaneously; button 6 for 3 and 4.  Pressing 1 and 2 simultaneously is physically impossible on the Hue tab housing, but some people put the module in in-wall switches.

**Comment by jostrasser** [comment]
thanks for your explanation!
