### ISSUE TITLE
update to latest version gives error

### ISSUE THREAD

**Issue by arp013** [ebaauw/homebridge-hue#977]
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-hue@latest

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== integrity checksum failed when using sha512: wanted sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/fakegato-history: sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== integrity checksum failed when using sha512: wanted sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-05-01T11_22_06_855Z-debug.log

Command failed. Please review log for details.

**Comment by arp013** [comment]
log file:
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'homebridge-hue@latest'
0 verbose cli ]
1 info using npm@7.11.2
2 info using node@v14.16.1
3 timing npm:load:whichnode Completed in 5ms
4 timing config:load:defaults Completed in 8ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 11ms
8 timing config:load:env Completed in 3ms
9 timing config:load:file:/usr/local/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/pi/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 5ms
17 timing config:load:setEnvs Completed in 4ms
18 timing config:load Completed in 42ms
19 timing npm:load:configload Completed in 43ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 7ms
22 timing npm:load:cleanupLog Completed in 10ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 69ms
26 timing config:load:flatten Completed in 13ms
27 timing arborist:ctor Completed in 3ms
28 timing idealTree:init Completed in 34ms
29 http fetch GET 304 https://registry.npmjs.org/homebridge-hue 513ms (from cache)
30 timing idealTree:userRequests Completed in 570ms
31 silly idealTree buildDeps
32 silly fetch manifest homebridge-hue@0.13.9
33 silly placeDep ROOT homebridge-hue@0.13.9 OK for:  want: 0.13.9
34 silly fetch manifest fakegato-history@~0.6.1
35 silly fetch manifest homebridge-lib@~5.1.2
36 silly fetch manifest semver@^7.3.5
37 silly fetch manifest ws@^7.4.5
38 silly fetch manifest xml2js@~0.4.23
39 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== integrity checksum failed when using sha512: wanted sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
40 warn registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
41 http fetch GET 200 https://registry.npmjs.org/fakegato-history 173ms (from cache)
42 http fetch GET 200 https://registry.npmjs.org/homebridge-lib 276ms (from cache)
43 http fetch GET 200 https://registry.npmjs.org/ws 273ms (from cache)
44 http fetch GET 200 https://registry.npmjs.org/semver 282ms (from cache)
45 http fetch GET 200 https://registry.npmjs.org/xml2js 328ms (from cache)
46 timing idealTree:#root Completed in 390ms
47 silly placeDep node_modules/homebridge-hue fakegato-history@ OK for: homebridge-hue@0.13.9 want: ~0.6.1
48 silly placeDep node_modules/homebridge-hue homebridge-lib@ OK for: homebridge-hue@0.13.9 want: ~5.1.2
49 silly placeDep node_modules/homebridge-hue semver@ OK for: homebridge-hue@0.13.9 want: ^7.3.5
50 silly placeDep node_modules/homebridge-hue ws@ OK for: homebridge-hue@0.13.9 want: ^7.4.5
51 silly placeDep node_modules/homebridge-hue xml2js@ OK for: homebridge-hue@0.13.9 want: ~0.4.23
52 timing idealTree:node_modules/homebridge-hue Completed in 54ms
53 timing idealTree:node_modules/homebridge-hue/node_modules/fakegato-history Completed in 0ms
54 timing idealTree:node_modules/homebridge-hue/node_modules/homebridge-lib Completed in 0ms
55 timing idealTree:node_modules/homebridge-hue/node_modules/semver Completed in 1ms
56 timing idealTree:node_modules/homebridge-hue/node_modules/ws Completed in 0ms
57 timing idealTree:node_modules/homebridge-hue/node_modules/xml2js Completed in 0ms
58 timing idealTree:buildDeps Completed in 454ms
59 timing idealTree:fixDepFlags Completed in 5ms
60 timing idealTree Completed in 1070ms
61 timing command:install Completed in 1211ms
62 verbose type system
63 verbose stack FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/fakegato-history: sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== integrity checksum failed when using sha512: wanted sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
63 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:162:15
63 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
63 verbose stack     at async Promise.all (index 0)
63 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:924:5)
63 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
63 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
63 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:137:5)
64 verbose cwd /usr/local
65 verbose Linux 5.10.17-v7+
66 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-hue@latest"
67 verbose node v14.16.1
68 verbose npm  v7.11.2
69 error code EINTEGRITY
70 error errno EINTEGRITY
71 error Invalid response body while trying to fetch https://registry.npmjs.org/fakegato-history: sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== integrity checksum failed when using sha512: wanted sha512-XEAhykEkc+NVybYF1UucxCicIPbJgwF8nm3wCPLYX8nvRJKkmJHLBSFphaUSrGFZSzlk+OK70cXK3bik03iFRw== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
72 verbose exit 1

**Comment by ebaauw** [comment]
This is an error with `npm`, not with Homebridge Hue.  I’d try clearing the `npm` cache: `sudo npm cache clear -f`.

**Comment by arp013** [comment]
ok thanks, the clear command didn't solve

**Comment by ebaauw** [comment]
I'm sorry, I have no clue.  You might try a web search for `EINTEGRITY`: it seems to be an issue with the `npm` connection to the npm registry or with a corrupted npm cache.

**Comment by arp013** [comment]
did a fresh install now everything working again
