### ISSUE TITLE
Exposing an outlet as read-only device for just metering

### ISSUE THREAD

**Issue by muratcorlu** [ebaauw/homebridge-hue#978]
I have some smart plugs to reading consumption of my white appliances. But the problem is, sometimes we accidentally turn off them and having this is not good if you think about refrigerator or heating system. I checked how can I make an outlet read only (as homebridge-p1 exposes electricity consumption resources) and came to [resource links document](https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links). I feel like I can expose an outlet as a dummy device but I couldn't figure out how to do it.

Firstly, is this possible via current configurations? If so, how? If not, is it an idea to add an option to set a device "read-only"?

**Comment by ebaauw** [comment]
If you blacklist the `/lights` resource, Homebridge Hue should only expose the power and consumption sensors.

**Comment by muratcorlu** [comment]
That worked greatly. Just for documenting if someone will come for same issue. I just run this command in Rpi:

```bash
$ ph post /resourcelinks '{
  "name": "homebridge-hue",
  "classid": 1,
  "description": "blacklist",
  "links": [
    "/lights/5",
    "/lights/7"
  ],
  "recycle": false
}'
```

And restarted Homebridge. Then there is smart plug in home app anymore but consumption data still visible in Eve Home app.

Thank you @ebaauw. I'm closing this.
