### ISSUE TITLE
LIDL (Silverquest) unknown ZHAPresence sensor

### ISSUE THREAD

**Issue by ghdbwise** [ebaauw/homebridge-hue#979]
deCONZ RPIxx: /sensors/40: warning: unknown ZHAPresence sensor {"config":{"battery":100,"duration":10,"enrolled":1,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"799127ba1531b19b03b9064611303fcb","lastseen":"2021-05-05T21:34Z","manufacturername":"SILVERCREST","modelid":"TY0202","name":"BWM LIDL","state":{"lastupdated":"2021-05-05T20:58:45.290","lowbattery":false,"presence":false,"tampered":false},"swversion":"2019.12.12","type":"ZHAPresence","uniqueid":"ec:1b:bd:ff:fe:c7:3f:52-01-0500"}

**Comment by ebaauw** [comment]
Does it work?

**Comment by ghdbwise** [comment]
Yes it works. Just noticed the warning.

**Comment by ebaauw** [comment]
Whitelisted in v0.13.10.
