### ISSUE TITLE
diyhue Support? (in v0.12.12 it was there) 

### ISSUE THREAD

**Issue by AlexKusnezov** [ebaauw/homebridge-hue#980]
#### Issue

I'm using diyhue and from v0.12.13 and up it suddenly stopped working, not sure what the problem is.
Can you please help me. I'm heavily relying on that plugin.
What I'm constantly getting is:
```
[5/6/2021, 2:15:46 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[5/6/2021, 2:15:50 PM] [Hue] 192.***.***.109: request 1: GET /config
[5/6/2021, 2:15:50 PM] [Hue] 192.168.2.109: request 1: invalid response
[5/6/2021, 2:15:50 PM] [Hue] 192.168.2.109:80: not found - retrying in 30s
```

#### Log Messages

I tried to run ph -H 192.168.2.109 -DD config and this is what I get:
```
/homebridge # ph -H 192.168.2.109 -DD config
ph: 192.168.2.109: request 1: GET /config
ph: 192.168.2.109: request 1: GET http://192.168.2.109/api/config
ph: 192.168.2.109: request 1: response: {"name":"RPi diyHue","datastoreversion":70,"swversion":1943185030,"apiversion":"1.35.0","mac":"b8:27:eb:b5:da:33","bridgeid":"B827EBFFFEB5DA33","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}
ph: 192.168.2.109: request 1: 200 OK
ph: 192.168.2.109: request 1: GET /config
ph: warning: 192.168.2.109: request 1: invalid response
ph: error: 192.168.2.109: not a Hue bridge nor deCONZ gateway
```

**Comment by AlexKusnezov** [comment]
Fyi, I finally managed to get back to v0.12.12, after struggling a bit, since you can't select in anymore in homebridge.
This is what I get when I run **ph -H 192.168.2.109 -DD config** 
```
/homebridge # ph -H 192.168.2.109 -DD config
request 1: GET /config
request 1: GET http://192.168.2.109/api/config
request 1: response: {"name":"RPi diyHue","datastoreversion":70,"swversion":1943185030,"apiversion":"1.35.0","mac":"b8:27:eb:b5:da:33","bridgeid":"B827EBFFFEB5DA33","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}
request 1: 200 OK
request 1: GET /config
request 1: GET http://192.168.2.109/api/config
request 1: response: {"name":"RPi diyHue","datastoreversion":70,"swversion":1943185030,"apiversion":"1.35.0","mac":"b8:27:eb:b5:da:33","bridgeid":"B827EBFFFEB5DA33","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}
request 1: 200 OK
{
  "name": "RPi diyHue",
  "datastoreversion": 70,
  "swversion": 1943185030,
  "apiversion": "1.35.0",
  "mac": "b8:27:eb:b5:da:33",
  "bridgeid": "B827EBFFFEB5DA33",
  "factorynew": false,
  "replacesbridgeid": null,
  "modelid": "BSB002",
  "starterkitid": ""
}
```

Alo on v0.12.13 it's kind of supported, but makes the plugin homebridge-gsh v2.1.0 non-functional :(
 
Using the latest version is the worst, since it prevent homebridge from starting

**Comment by ebaauw** [comment]
Looks like diyhue exposes `swversion` as numeric value instead of string.  I added some sanity checks on the response some versions ago, because Pihole also exposes a `/config` endpoint, which would lead to very weird errors later on.

**Comment by AlexKusnezov** [comment]
@ebaauw cool, do you know if I can somehow fix it on my end?

**Comment by ebaauw** [comment]
Sorry, I don't know diyhue.  I don't even know if the value is hard-coded or read from some config file.

The check is here:
https://github.com/ebaauw/homebridge-hue/blob/15f4a5dd1842e45af6a4de8691426f33e8ea1670/lib/HueDiscovery.js#L82

You could patch the file and comment out this check.  That should make both `ph` and Homebridge Hue accept the diyhue response.

**Comment by AlexKusnezov** [comment]
@ebaauw just wanted to let you know, that your suggestion works, thank you so much!
