### ISSUE TITLE
Warnings after Homebridge start

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#983]
Hi,

I can see the following after starting homebridge, no idea if this can cause issues:

`[10/05/2021, 09:34:23] [Homebridge-Hue] Philips hue: warning: not using recommended Hue bridge api version 1.43.0`

and

`[10/05/2021, 09:34:23] [Homebridge-Hue] Philips hue: /lights/18: warning: using default colour gamut for unknown light model {"state":{"on":true,"bri":25,"hue":6415,"sat":208,"effect":"none","xy":[0.4462,0.4112],"ct":344,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-05-11T12:50:31"},"type":"Extended color light","name":"Büro Decke","modelid":"371000002","manufacturername":"Paulmann Licht","productname":"Extended color light","capabilities":{"certified":false,"control":{"colorgamuttype":"other","ct":{"min":153,"max":370}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"classicbulb","function":"mixed","direction":"omnidirectional"},"uniqueid":"00:15:8d:00:04:4a:28:4a-01","swversion":"1400-0001"}`

The lamp `/lights/18` is a Paulmann Amaris lamp (controlled via Zigbee / Hue Bridge).

Thanks!

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6450837/homebridge-hue.json.gz)

**Comment by jostrasser** [comment]
Also saw:

```
[10/05/2021, 10:29:15] [Homebridge-Hue] config.json: nupnp: invalid key
[10/05/2021, 10:29:15] [Homebridge-Hue] config.json: forceCt: invalid key
```

**Comment by jostrasser** [comment]
Output:

```
root@homebridge:/home/pi# ph probe -v /lights/18
ph: localhost: request 1: GET /config
ph: warning: localhost: request 1: 127.0.0.1:80: cannot connect: ECONNREFUSED
ph: error: localhost: not a Hue bridge nor deCONZ gateway
root@homebridge:/home/pi# 
```

**Comment by ebaauw** [comment]
Use `-H` or set `PH_HOST` to specify the IP address of the Hue bridge.  See `ph -h` for help.

**Comment by jostrasser** [comment]
hmm, when I try to run `ph -H 192.168.0.50:80 probe -v /lights/18`i will get:
`ph: fatal: missing username - press link button and run "ph -H 192.168.0.50:80 createuser"`

will this overwrite anything of the config on the homebridge side?

**Comment by ebaauw** [comment]
No, `ph` keeps its own usernames in `~/.ph`.

**Comment by lugaetsch** [comment]
@jostrasser you might change the **package.json** file in the homebridge-hue file directory and edit:

`"engines": {
    "BSB001": "1.16.0",
    "BSB002": "1.44.0",`

To make the command run, @ebaauw posted above do:

ph -H <ipofyourhuebridge> -u <InsertUserSeenInYourHomeBridgeConfig> probe -v /lights/18

**Comment by ebaauw** [comment]
Hue bridge API v1.44.0 in v0.13.10.

**Comment by jostrasser** [comment]
> To make the command run, @ebaauw posted above do:
> 
> ph -H -u probe -v /lights/18

does not work for me...

```
pi@homebridge:~ $ ph -H 192.168.0.50:80 -u probe -v /lights/18
ph: error: -v: unknown option
```

**Comment by lugaetsch** [comment]
> > To make the command run, @ebaauw posted above do:
> > ph -H -u probe -v /lights/18
> 
> does not work for me...
> 
> ```
> pi@homebridge:~ $ ph -H 192.168.0.50:80 -u probe -v /lights/18
> ph: error: -v: unknown option
> ```

sry @jostrasser: may I correct my last post on this?

First check the user for the homebridge-hue plugin. The user was set when you started the plugin for the first time.
You can check the user in homebridge config, should look like this:

`"lights": true,
            "linkButton": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": false,
            "sensors": false,
            "users": {
                "**xxxxxxxx**": "**xxxxxxx**"
            },
            "platform": "Hue"`

As soon as you have the user ID you can insert it in the following comment followed by -H command which sets the huebridge-ip:

ph -H <IP-of-Huebridge> -u <user> probe -v /lights/18

**Comment by jostrasser** [comment]
> > > To make the command run, @ebaauw posted above do:
> > > ph -H -u probe -v /lights/18
> > 
> > 
> > does not work for me...
> > ```
> > pi@homebridge:~ $ ph -H 192.168.0.50:80 -u probe -v /lights/18
> > ph: error: -v: unknown option
> > ```
> 
> sry @jostrasser: may I correct my last post on this?
> 
> First check the user for the homebridge-hue plugin. The user was set when you started the plugin for the first time.
> You can check the user in homebridge config, should look like this:
> 
> `"lights": true, "linkButton": true, "nativeHomeKitLights": true, "nativeHomeKitSensors": true, "resource": false, "sensors": false, "users": { "**xxxxxxxx**": "**xxxxxxx**" }, "platform": "Hue"`
> 
> As soon as you have the user ID you can insert it in the following comment followed by -H command which sets the huebridge-ip:
> 
> ph -H -u probe -v /lights/18

copied the user from the config...
output:

```
pi@homebridge:~ $ ph -H 192.168.0.50 -u xxxxxxxxxxxxxxxx probe -v /lights/18
ph probe: request 1: GET /lights/18
ph probe: error: request 1: api error 1: unauthorized user
pi@homebridge:~ $
```

**Comment by lugaetsch** [comment]
Hi Johannes,

please make sure to use the second entry of your configs "users" entry (the second part in quotation marks after ' : ' )
and try the command again I have mentioned above.
Otherwise do set another user on the huebridge by doing:

Press link button on your Huebridge and do run

ph -H 192.168.0.50 createuser

The command should create another user on your hue bridge which you can use to have access to API and you should be able to use the mentioned command above.

Good luck ;)
