### ISSUE TITLE
When triggering a (colored) scene from the Hue App lights always change to adaptive lighting "white"

### ISSUE THREAD

**Issue by maximklein** [ebaauw/homebridge-hue#986]
Hello,

I hope someone can help me with my problem. At first I want to say thanks for this amazing plugin it works extremely well for my 30+ lights. 

I only have one issue. At night I sometimes want the lights in the bathroom to come on to a nice blue color. As soon as I trigger this scene from the Hue App directly, it mostly takes a few seconds and then my RGBW bulbs turn from the blue color to the current adaptive lighting color temperature (white) from the Home App. The interesting point is, that this also happens when adaptive lighting is NOT selected in the Home app. I had this Scene already before I integrated my Hue Bridge in HomeKit so I know that It did work before. I just want to know if the fault is on my Side, or if there's a workaround to get this working for me. 

Thanks a lot!

**Comment by ebaauw** [comment]
Please capture and attach a debug log file (see FAQ).

**Comment by maximklein** [comment]
Due to a power fail I completely had to reconfigure my Router Settings today and now It works like a charm. Don’t know what the actual issue was, but thank you!
