### ISSUE TITLE
Hue homebridge Plugin interference

### ISSUE THREAD

**Issue by Ludelag** [ebaauw/homebridge-hue#987]
Good afternoon, More than an Issue I have a question. Actually I have the hue Philips bridge working directly with homekit, but since I also run homebridge for many devices and sometimes I don't find access to my hue Philips lamps and sensors, I was wondering if will be good to install this plugin, maybe it could work better than the Hue bridge direct. My question comes here; if I install the plugin won't have interference with the actual installation of the Hue? should I first uninstall the Hue in Homekit before run the Plugin in my my Homebridge?

Thank you in advance for the assistance.

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/wiki/Features for a comparison between Homebridge Hue and the native HomeKit features of the Hue bridge.

As far as the Hue bridge is concerned, Homebridge Hue is just another API client.  I've seen some reports of the Hue app messing with the HomeKit setup of accessories exposed by Homebridge Hue - best to disable any syncing in the Hue app between the Hue bridge and HomeKit.

Depending on how you configure Homebridge Hue (see https://github.com/ebaauw/homebridge-hue/wiki/Configuration), you might see duplicate accessories in HomeKit for the same Hue device: one exposed by the Hue bridge, one by Homebridge Hue.  The Hue bridge doesn't support fine grained configuration what it exposes to HomeKit, the only choice you have is removing the Hue bridge from HomeKit.
