### ISSUE TITLE
Incorrect device type Zemismart Roller Driver via Deconz

### ISSUE THREAD

**Issue by schweppy** [ebaauw/homebridge-hue#991]
Zemismart Zigbee Roller Blind Driver (M515EGBZTN) connected via Deconz shows in Phoscon as a light (but useable to open and close blind), however homebridge Hue exposes as a Not Supported Battery device.

I cant find any known issues, although there are some over on the Deconz GitHub regarding the reasons Phoscon sees the device as a bulb.
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6649957/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
You don't expose `/lights` resources.  The blind is exposed as a `/lights` resource (except for the battery).

**Comment by schweppy** [comment]
Ah yes! Now it appears as a blind in homekit and working, however, it is showing zero battery percentage and a low battery warning. Anything I can do about this?

**Comment by ebaauw** [comment]
deCONZ hasn’t received any battery percentage and reports it as 0 (according to your logfile).  You’ll have to ask over there why this is the case.

**Comment by schweppy** [comment]
Thanks, i have asked, however, no solution at the moment. Any chance to incorporate a setting to hide battery level or make it show a custom value?

**Comment by ebaauw** [comment]
Don’t expose the ZHABattery resource through `excludeSensorTypes` In config.json or by creating a `blacklist` resourcelink.  See Wiki.

**Comment by schweppy** [comment]
Thank you! Ive used excludesensortypes for now and working well to hide my blind battery!! In fact, all my other zigbee door/window sensor battery levels are still being reported to HomeKit. Is that how it should work?

**Comment by ebaauw** [comment]
Yes, for those the battery is exposed on the `/sensors` resource, only the blinds, which are exposed as `/lights` resources have a separate ZHABattery.

**Comment by schweppy** [comment]
Ah ok. Thank you for the explanation. Great stuff!
