### ISSUE TITLE
host: invalid key

### ISSUE THREAD

**Issue by Ghost108** [ebaauw/homebridge-hue#993]
Hello :)

i have installed the newest version of your plugin and the recommend version of nodejs.
System works fine , but I have a warning message in the logs:

`[homebridge-hue] config.json: host: invalid key`

How can I solve this?

**Comment by ebaauw** [comment]
See the release notes, https://github.com/ebaauw/homebridge-hue/releases/tag/v0.13.2: the `host` key is no longer used.  Use `hosts` with an array value.
