### ISSUE TITLE
New Hue Firmware / API released (1.45)

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#994]
Hi,

only FYI: new Hue Bridge Firmware was released (API 1.45)

Warnings:
[26/06/2021, 06:33:06] [Homebridge-Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1945163030, api v1.45.0
[26/06/2021, 06:33:06] [Homebridge-Hue] Philips hue: warning: not using recommended Hue bridge api version 1.44.0

**Comment by ebaauw** [comment]
In v0.13.16, but no clue what has changed.

The link to the firmware release notes seems to have disappeared from their site.  The [page](https://www.philips-hue.com/en-us/support/release-notes) itself is still available, but no info about the latest Hue bridge version.

The [API documentation changelog](https://developers.meethue.com/develop/hue-api/api-documentation-changelog/) hasn't been updated in a year.

The latest [Developer update](https://developers.meethue.com/updates-20210602/) seems to suggest they're  becoming more and more closed: now hiding the rules created by the Hue app from the API.

**Comment by jostrasser** [comment]
Hi,

Thanks.

That means we should ignore the warning of homebridge-hue for now?

**Comment by ebaauw** [comment]
Warning no longer appears in v0.13.16.

**Comment by jostrasser** [comment]
Ok, great!

Thanks a lot!
